### ISSUE TITLE
Broken build variants

### ISSUE THREAD

**Issue by UgVaDevLabs** [schwabe/ics-openvpn#1000]
2 out of three modules have build variants that work fine (remoteExample and tlsexternalcertprovider) but the third module (main) has an enormous amount of build variants. Normaly we should see flavor+buildType and all other possible combinations, but in main module we see flavor+buildType+CPU architecture combinations. I am using Android Studio 3.3 latest stable version.

![screenshot 2019-02-07 at 17 11 24](https://user-images.githubusercontent.com/43786958/52420787-69b2e380-2afb-11e9-8d44-0733c2a3ee32.png)

**Comment by schwabe** [comment]
That is not broken that is just the way Android Studio now presents you projects that have native binaries. Strictly speaking this are also 4 different variants. 

If you want to file a bug about this behaviour you should file it upstream with the Android Studio team
