### ISSUE TITLE
Feature Request: Add setting for turning off sound and vibration

### ISSUE THREAD

**Issue by nikolayhg** [schwabe/ics-openvpn#1004]
# General information
1. Android Version: 8.0.0
2. Android Vendor/Custom ROM:
3. Device: any
4. Version of the app: 0.7.5
 
# Description of the issue
Once connected to a VPN Server, the user turns off the WiFi. After few seconds the status changes from "Connected" to "Unknown state: PAUSEnoNetwork" and
- If the volume is on, then a sound is played.
- If the volume is off, then a vibration is triggered.

The disadvantages of this behavior are:
- **disturbance**: If the user is in a noise sensitive environment (library, bed, silent room with other people), sound or vibration are disturbing for the environment.
- **confusion**: If the user does not know where the sound or vibration is coming, he may wonder what has happened with this phone.

# Suggested Solutions
- Add a boolean setting for turning on/off sound and vibration.

**Comment by schwabe** [comment]
See the FAQ. Also for new Android version like Android 8 you can customise the per App notifcation setting from OS.
