### ISSUE TITLE
Disconnect Intent failing

### ISSUE THREAD

**Issue by RobertLHarris** [schwabe/ics-openvpn#1005]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Stock Android 9
2. Stock Android 9
3. Pixel 2XL
4. App version 0.75
# Description of the issue

I use tasker work Intents to start OpenVPN for Android when connecting to specific networks.  This works perfectly, i never forget to connect to the VPN at Starbucks, work, etc.  I want to have it disconnect when I'm at home or not in WiFi though and the only intents i could find do not work for disconnection and i do not see any documentation either.

**Comment by schwabe** [comment]
There are already Intent for that. https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/AndroidManifest.xml#L240
