### ISSUE TITLE
Add ability to start openvn process without cert/static-key

### ISSUE THREAD

**Issue by HRomie** [schwabe/ics-openvpn#1007]
# General information
1. Android:  8.0.0
2. Version of the app: 0.7.5
 
# Description of the issue
It is possible for OpenVPN process, to be run without any cert/static-key. In such case, the OpenVPN process would output a message similar to this:

> ******* WARNING *******: All encryption and authentication features disabled -- All data will be tunnelled as clear text and will not be protected against man-in-the-middle changes. PLEASE DO RECONSIDER THIS CONFIGURATION!

Such setup would be helpful when the underlying OpenVPN traffic is already secured by other means (e.g, via stunnel). adding an extra layer of protection, just slows things down, causes more battery consumption, and adds an unnecessary overhead to each packet.

Right now OpenVPN for Android refuses to run without any cert/static-key set and demands that the user provides one.

**Comment by schwabe** [comment]
that is a very weird mode to run OpenVPN in. Why aren't you using a normal OpenVPN configuration with just cipher none and auth none?

**Comment by HRomie** [comment]
> that is a very weird mode to run OpenVPN in. Why aren't you using a normal OpenVPN configuration with just cipher none and auth none?

Well, I would argue not specifying any cert or static key, is less weird of a mode than specifying '--cipher none' and '--auth none'.

But fair enough, I just gave such setup a try (using a static key). My testing however shows that the bytes overhead of using this method, is higher than not specifying any key at all.

To put it into perspective, Using TCP mode and pinging the other end of the tunnel with 64 bytes of data, results in final packet size of **138 bytes** when no cert/static-key is specified, and **146 bytes** when using a static key with '--cipher none' and '--auth none' set.

Now I was actually able to make this setup work with the app. If I set the app to use static key and then go to the 'AUTHENTICATION/ENCRYPTION' tab and turn off 'Use TLS Authentication' option and immediately exit the settings, it works. But if I browse other tabs, the setting will be turned on again.

But this feels like a very hacky solution which could stop working in future.

**Comment by 1anomaly1** [comment]
ALL I KNOW IS THE DUMB APP HAS DROPPED SECURE CONNECTION AT RANDOM, MORE THAN ONCE. THIS APP IS UNTRUSTWORTHY,  AND IN MY MIND, A PRIMARY TARGET BY NSA. IT'S PROVEN TO BE UNRELIABLE ONE TOO MANY TIMES, SO I DON'T USE IT FOR THESE REASONS. I MISTRUST IT MORE NOW, BUT THAT DOESN'T MEAN I'D GIVE UP ON IT AS A USER. IT JUST MEANS U DEVS NEED TO FIND OUT WHO THE NSA MOLE IS, AND FIGHT BACK.

**Comment by 1anomaly1** [comment]
THE NSA MOLE THAT ADDS CODE TO ANY OF THESE APPS ARE THE ONES ADDING ANYTHING UNNECESSARY WITH THE GUISE OF CONVENIENCE,  AND INSISTING THERE IS NO OTHER WAY. THESE ARE THE SHIT HACKS WORKING FOR NSA. FREEDOM, AND PRIVACY IS VERY SIMPLE, AS LONG AS THE NSA, AND THEIR LIES ARE CALLED OUT FOR WHAT THEY ARE. THEY ARE THE PEDIPHILES THAT THEY TELL YOU THEY ARE PROTECTING YOU FROM.

**Comment by schwabe** [comment]
@HRomie So cipher none/auth none adds 8 byte overhead. It might be that we included the IV even without encryption/authentication since that mode is barely used at all.

@1anomaly1 There even an FAQ in the app why the app does not has a Killswitch or pretends to have one. And I am not sponsored by the NSA. I wish I were because the extra money they would need to pay to actually do what conspiracy theorist think that I do, would be very nice! :P

**Comment by HRomie** [comment]
> @HRomie So cipher none/auth none adds 8 byte overhead. It might be that we included the IV even without encryption/authentication since that mode is barely used at all.

No, I doubt that that's it. The test was done using 2 normal openvpn instances and not on android. Even using the deprecated '--no-iv' option doesn't change the result. whatever that overhead is, is placed by openvpn internally.

Now if you want, I can probably track it down to find out why there is an 8 bytes of overhead when  '--cipher none' and '--auth none' set (as opposed to not specifying any encryption key at all). But honestly, I still think the best way would be a 'disable' option for the encryption type in the app.
