### ISSUE TITLE
Simply Custom UI to connect and disconnet VPN Profile

### ISSUE THREAD

**Issue by tomeroto** [schwabe/ics-openvpn#1008]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
   Marshmello
2. Android Vendor/Custom ROM 
    Lenovo
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

Sorry before, I am newbie on VPN. I was successfully run 2 apk: main and remoteExample.
But how to custom UI with simplified layout that have connect disconnect button. And also I need it run on one APK.

Please help me, I am student thant need to research this app.

Thank you.

**Comment by schwabe** [comment]
What are you trying to accomplish?

**Comment by tomeroto** [comment]
Thank you for your response.
I want to make simply hardware for my study to make communication between Android and Respberry PI (Base On Linux) via VPN. I think VPN is secure.

Can you help me?

**Comment by schwabe** [comment]
I am not sure why you need an extra app for that and cannot just use my app

**Comment by tomeroto** [comment]
because your code too difficult to be learn, and to many layout in your app and it will make user confuse.
please give me simply source for simply UI

**Comment by schwabe** [comment]
@tomeroto What you are asking is what all commercial VPN apps wants.

You have to convince me that you are not one of them. Please also read: 
https://github.com/schwabe/ics-openvpn/blob/master/doc/README.txt#L38

**Comment by tomeroto** [comment]
Ok, what can I do for commercial purpose, I have not much time to explain actual project what I do in my study. Please give me solution.

**Comment by tomeroto** [comment]
@schwabe Im waiting for your response, how to get comercial source?

**Comment by schwabe** [comment]
@tomeroto contact me via email but I am currently quite busy.

**Comment by tomeroto** [comment]
where your email address?
