### ISSUE TITLE
Quick setting tile on Android P doesn't turn on/off VPN connection

### ISSUE THREAD

**Issue by spi43984** [schwabe/ics-openvpn#1009]
# General information
1. Android Version
Android Pie
2. Android Vendor/Custom ROM
LineageOS 16
3. Device
Xiaomi Mi Mix 2S
4. Version of the app (version number/play store version/self-built)
0.7.8
 
# Description of the issue
I've been using OpenVPN for Android for quite some time on different phones. On LineageOS 14.1 I could turn on and off the VPN by tapping the quick setting tile. This didn't work on a Xiaomi Android 8 ROM (I assumed the Xiaomi ROM just didn't support 3rd party tiles) but it also doesn't work on LineageOS 16 which is based on Android P.

I get the error "no VPN selected". In the device settings under the VPN section I only see the two options "always-on VPN" and "Block connections without VPN" for OpenVPN. Both options don't allow me to use the quick setting tile to turn on/off the VPN. The quick setting tile changes it appearance though if I turn on/off the VPN through the OpenVPN app.

Is this an Android P/OpenVPN issue or an intentional behaviour?

Cheers,
Sebastian

**Comment by schwabe** [comment]
The always on VPN should be called Standard VPN and the summary tells you that it is also used for the quick tile.

**Comment by spi43984** [comment]
Hm, no. The setting doesn't have any impact on the tile. So tapping the tile doesn't turn on or off the VPN connection.

The settings only talk about always on - but still I have to turn on the VPN in the app itself.

I watch a screenshot of the Android VPN settings.

**Comment by schwabe** [comment]
Attachments only work if you reply directly on github, not if via email. 

And here it works on Android Pie:

![image](https://user-images.githubusercontent.com/1038539/53736600-7e7c6000-3e8a-11e9-8d02-ae0ee4d45856.png)

**Comment by spi43984** [comment]
That's it. Thanks! Missed the bit to define the default VPN in the app itself too. Expected this in the Android system settings.
