### ISSUE TITLE
Process exited with exit value 11

### ISSUE THREAD

**Issue by v00t** [schwabe/ics-openvpn#1011]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version - 4.0.3
2. Android Vendor/Custom ROM - C00B219
3. Device - HuaweiU9200
4. Version of the app (version number/play store version/self-built) - 0.7.8
 
# Description of the issue

Suddenly, without any changes on the client and server sides,  OpenVPN For Android 0.7.8 has broke, with status "Process exited with exit value 11"

> 2019-03-07 09:14:04 Debug state info: CONNECTED  to WIFI , pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
> 2019-03-07 09:14:04 Debug state info: CONNECTED  to WIFI , pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
> 2019-03-07 09:14:05 Process exited with exit value 11

**Comment by schwabe** [comment]
do you have the possibility to get the adb logcat while it crashes?
