### ISSUE TITLE
[0.7.7] No access after Upgrade to Android 8.1

### ISSUE THREAD

**Issue by Af0x** [schwabe/ics-openvpn#1012]
Hello,
after upgrading from Lineage 14.1 to 15.1 I cannot access my network anymore.

The connection to the VPN-server is established successfully.

The routes I try to access are different from the IP of the device, for example the device has 10.10.10.100 and the IP I try to access is 10.10.0.100.

Before the upgrade it was all working fine.

I tried enabling OpenVPN 3 Core and other things to fix it but it does not work.

The option to get routes from server is checked.

Regards,

Af0x

**Comment by schwabe** [comment]
You provided no log so I have no idea what is going wrong. But in all fairness this sounds very much like a Lineage OS bug. The app has been tested on all Android versions and works fine.

**Comment by Af0x** [comment]
I opened an issue at their gitlab: https://gitlab.com/LineageOS/issues/android/issues/328

**Comment by Af0x** [comment]
hello, you were saying "log". What would be of interest in this case? I can try to get this information for debugging purpose.
Best regards

**Comment by schwabe** [comment]
log from the app. But in all fairness it will probably show that the app installed the correct VPNService routes.

**Comment by Af0x** [comment]
ok, I came closer to the issue.
The issue seems to be at the "Allowed apps" tab . My settings were "only allow for selected apps". But even if I select all available apps it is not possible to connect to my destinations. If I change to "allow for all apps except the selected ones" it is working!

**Comment by schwabe** [comment]
Yeah this hints even more at a Lineage OS problem that they messed up the allowed/disallowed APPs API.

**Comment by Af0x** [comment]
ok, thank you. I added this to the bugreport of LineageOS. Best regards
