### ISSUE TITLE
Question - Allowed app working ?

### ISSUE THREAD

**Issue by yuriw** [schwabe/ics-openvpn#1013]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version

7.0

2. Android Vendor/Custom ROM

Security Patch level
August 1, 2018
Kernel 3.10.79
Build BRAVIA_ATV_2UC-user 7.0

3. Device

Sony Bravia TV

4. Version of the app (version number/play store version/self-built)

0.6.65
 
# Description of the issue

I wanted to be able to connect OpenVPN only for one application, say Netflix
Selected it in Allowed Apps tab
However when I start Netflix, I don't see OpenVPN connection established.
Not sure if there is some trick how to make it work or it's a bug.

**Comment by cowst** [comment]
Most likely bug in fireOS:

https://forums.developer.amazon.com/questions/190891/android-vpnservice-class-addallowedapplication.html

**Comment by yuriw** [comment]
@cowst thx, looks like that's it.  Do you know how to report/see on this bug progress ?

**Comment by cowst** [comment]
Wait a second, I actually blindly answer the same thing recently, but I
don't think you have the same problem.
That is a problem with the fire tv stick 4k.
You have a bravia (and I have that as well), and in my case allowed apps
works.

**Comment by yuriw** [comment]
@cowst this is good to know.

So I selected my app in Allowed App, made sure OpenVPN is not running and started the app, and see no OpenVPN connection established.

How do you test this?  Maybe I am missing some option or step...

Thx!

**Comment by cowst** [comment]
How I test these things.
1 - check your ip on browser
2 - start vpn for all apps
3 - check browser again to see new ip
4 - start Netflix to see you are blocked (that happens with prime for me)
5 - allow Netflix and reconnect vpn
6 - test browser to see you still have the vpn ip
7 - see that now Netflix is working

**Comment by yuriw** [comment]
@cowst 
I want slightly different scenario:
VPN works ONLY for one app, say Netflix.

**Comment by cowst** [comment]
I think in that version of openvpn there is only one toggle to allow apps.
Select Netflix and toggle to be the only app in vpn.

The steps I mentioned should still be applicable to prove it works.

**Comment by yuriw** [comment]
Maybe you are right, thx for your help !

**Comment by schwabe** [comment]
Yeah, like the forum post and other bug reports, this a bug in the firmware of the Amaon devices that this app cannot workaround.
