### ISSUE TITLE
Thank you for creating, driving, and maintaining OpenVPN for Android 🎉

### ISSUE THREAD

**Issue by keywordnew** [schwabe/ics-openvpn#1014]
~To make issues more manageable, I would appreciate it if you fill out the following details as applicable:~

~# General information~
~1. Android Version~
...
 
# Description of the issue

I wanted to thank you for creating, driving, and actively maintaining an app that I and many others find super useful! Open source projects take time and effort; I want to call that out and say I really appreciate it.

I have no feature requests. I use it to connect through my OpenVPN setup. I find it light and easy to use. Something changed in v0.7.8 that made it so connections don't time out like they used to. I used to have to reconnect to get an active connection, but now it's persistent. Thank you :D

You're awesome, as are all the maintainers and contributors to this project 💯

(Feel free to close the issue at any point lol)

**Comment by schwabe** [comment]
Can you provide a log?

**Comment by keywordnew** [comment]
I should clarify: the time out that used to happen regularly _before_ 0.7.8 is not happening _after_ the update.

I opened this issue only to share gratitude!

Please feel free to close the issue at any point :)

**Comment by canary5** [comment]
Where to get 0.7.8? Fdroid 0.7.7 last

**Comment by schwabe** [comment]
@canary5 not sure why F-droid does not build the latest version
