### ISSUE TITLE
Android TV 7.0 crash on Sony Bravia after sleep

### ISSUE THREAD

**Issue by ukasru** [schwabe/ics-openvpn#1015]
1. Android Version: Android TV 7.0
2. Android Vendor/Custom ROM: Sony Bravia Android TV (stock 2018)
3. Device: Sony KDL-49WF804
4. Version of the app: 0.7.8
 
If any VPN is active when the TV is resuming from standby, a core Android service process crashes and the TV performs a full reboot rather than elegantly resuming from standby.

There is also a thread in the Sony forum that describes the issue further and although it has the title "Android 6.0.1 reboots after enabling VPN apps" I can confirm this also affects Android TV 7.0 on my Sony KDL-49WF804: https://community.sony.ie/t5/android-tv/bug-android-6-0-1-reboots-after-enabling-vpn-apps/td-p/2284371

I can also confirm that the TV resume from standby behaves normally when OpenVPN for Android is installed but any VPN connection is off which gives weight to the theory this issue is centered around VPN being active on standby resume.

Is there any hope that you can do a potential fix to this issue as suggested? The solution for this issue might be to pause/stop the VPN connection when the TV is going into standby (screen off) and then later resume the VPN when the TV is brought out of standby (screen on) while OpenVPN for Android is active.

**Comment by cowst** [comment]
I'd like that as well, but I am afraid this should be tackled by sony and
/or Android TV.
BTW oreo 8 had the same issue.
3 major versions suffer from it, I don't see it fixed any time soon.

**Comment by ukasru** [comment]
> this should be tackled by sony and/or Android TV.

I agree with you, but

> 3 major versions suffer from it, I don't see it fixed any time soon.

maybe we can implement some workaround in this particular app? I have no hope for Sony...

**Comment by cowst** [comment]
The hypothetical workaround should be optional because we cannot exclude
background traffic while it sleeps, and unprotected traffic cannot be
defaulted just because of this bug.

Also, it depends if the OS notifies sleep actions in a way the app can
capture.

But to be honest, it is a very specific workaround that I would not
implement in a general purpose app, and I am telling this against my
interest :)

**Comment by ukasru** [comment]
> The hypothetical workaround should be optional because we cannot exclude
background traffic while it sleeps

Actually, the app has already had an option like this (Pause VPN connection after screen off).
![ovpnfa](https://user-images.githubusercontent.com/25655491/54749202-e5b54680-4be4-11e9-903c-ba222e1886c1.png)

But this option does not help in my issue. Maybe we can use another one option "Close VPN connection after screen off"?

**Comment by schwabe** [comment]
I am open to including a workaround for Sony in the app. But since buying a Sony Bravia TV just develop this workaround goes way to far for a spare time app, someone else will have to develop it.

And pause VPN connection after screen off will close VPN if you are not using persistent tun.

**Comment by ukasru** [comment]
> I am open to including a workaround for Sony in the app. But since buying a Sony Bravia TV just develop this workaround goes way to far for a spare time app, someone else will have to develop it.

I can test it on my TV and provide any logs :)

> if you are not using persistent tun

I cannot check it right now. Is this option ON by default?
Maybe this option does not help because of this "and less than 64 kB transferred data in 60s"?

**Comment by ukasru** [comment]
> if you are not using persistent tun

I cannot check it right now. Is this option ON by default?

**Comment by schwabe** [comment]
No it is not on by default. But it is not even clear if there is a solution to that or if the app has any chance of doing anything for a workaround. I haven't read through all of the 10 pages of that Sony forum thread, after 2 pages I gave up since it is just a myrad of "me too" posts...

**Comment by cowst** [comment]
I didn't do android for years, but if you would have some time to point me to an approximate implementation I would work and test it on my TV. 

I use persistent tun, don't want to risk some kodi traffic without vpn, and I am not sure what happens when I pause it for too long while watching streaming.

**Comment by cowst** [comment]
I'll try to summarize the issue if I can.

**Comment by ukasru** [comment]
I have just checked that I use "Persistent tun" also... I should try to turn options "Persistent tun" off and  "Pause VPN connection after screen off" on. I will try to do this later today.

**Comment by schwabe** [comment]
@cowst you could in the DeviceStateListener hardcode to immediately disconnect on SCREEN_OFF and see if that helps. Or see if there is any other event that might help

**Comment by cowst** [comment]
But I think there is no real solution.
Disconnecting that has the effect of ignoring the persist tun.
For that, things might already work playing around with the existing
options.

I don't see what the app could do guarantee vpn coverage while the TV
sleeps and prevent the crash which is low in OS when it wakes and there was
a connection.

**Comment by ukasru** [comment]
> I have just checked that I use "Persistent tun" also... I should try to turn options "Persistent tun" off and "Pause VPN connection after screen off" on. I will try to do this later today.

I have tried this config:
"Persistent tun" off
"Pause VPN connection after screen off" on
everything without luck... TV anyway reboots after sleep if any VPN is active.

> in the DeviceStateListener hardcode to immediately disconnect on SCREEN_OFF

@schwabe I could not do it. I have tried to make a build from source files, but I have stuck with "Process 'command 'swig'' finished with non-zero exit value 1" error message in the end. I have used Android Studio on Windows.

**Comment by schwabe** [comment]
You need to install swig. Chocolatey should work for doing that.

**Comment by borislip** [comment]
Anyone can provide any updates on this? I've just started using VPN on my TV, for a single app, and has encountered this issue. I am currently working it around by using Tasker with an OpenVPN plugin (com.ffrog8.openVpnTaskerPlugin), disconnecting the VPN on dislpay-off and connecting it again on display-on, but couldn't an option be added to the OpenVPN client itself, that would do the same? Can confirm the "Pause VPN connection after screen off" not helping, either with or without persistent tun.

Side note: According to some Google searching, this issue has been carried over from the 6.0 ROMs, pretty much indicating there is very little chance Sony is going to actually fix it.

**Comment by schwabe** [comment]
Still the same from my side:

> I am open to including a workaround for Sony in the app. But since buying a Sony Bravia TV just develop this workaround goes way to far for a spare time app, someone else will have to develop it.

**Comment by borislip** [comment]
Well, obviously nobody expects you to buy such a device just to test it. I am currently trying to build it, after fixing the missing stuff on my Windows system, it is now 5% through the build, building natives. If i actually manage to build without spending days fighting gradle (which i am not familiar with), i'll definitely try to "to immediately disconnect on SCREEN_OFF". I'll report here if i actually manage make it work and tell what i did (although, i am very unlikely to actually do it "proper" and do a pull request). Anyway, thanks for being ready to introduce such a mod to begin from.

**Comment by schwabe** [comment]
@borislip if you have any showsteppers or need help with helping contact me. I am convinced that you are not trying to build a ripoff VPN service app :)

**Comment by borislip** [comment]
@schwabe lol, indeed i don't. Thanks!

**Comment by borislip** [comment]
Well, I've managed to build, and did a little testing...

- Pausing the VPN (mManagement.pause) immediately at screen off, with persistent tun off, didn't prevent the crash
- Stopping the VPN (mManagement.stopVPN) immediately at screen off **has prevented the TV from crashing**

Obviously, in the latter case it currently wouldn't restore the connection and i have yet to dive in and see how you the the profile manager etc to re-establish it (as opposed to resuming it, which is readily available), but i kinda hope you'll just provide us a little check-box yourself, something along the lines of "temporarily disconnect at screen off", on the official build ;-)

Attaching .patch files to show exactly what i did.
[test_patches.zip](https://github.com/schwabe/ics-openvpn/files/3608255/test_patches.zip)

Thanks in advance!
Boris.

**Comment by cowst** [comment]
I can help beta testing :)

**Comment by djjunge** [comment]
I can also help with testing. I think to have an option to close the vpn connection after turning of the screen should work + a delay to re-establish the connection after screen is turned on again.

**Comment by CiNcH83** [comment]
Looks like the issue is resolved with latest BRAVIA FW 6.6575. Can anybody confirm or deny?

**Comment by cowst** [comment]
Will try tonight hopefully.
Didn't even know there was an update, my TV never finds them even months later :/
Always usb :(

**Comment by CiNcH83** [comment]
Yeah. BRAVIA updates are typically flaky as hell. That's why OTA updates are being rolled out to smaller markets first.

**Comment by cowst** [comment]
Any consistent way to reproduce it?
I have up so long ago that I am not sure. 
I vpn for Android, and it can connect automatically. 
Is it enough to put the TV in standby and on again? 
Or it needs deep sleep? 
In that case can I force it somehow to speed up testing?

**Comment by CiNcH83** [comment]
I think it could also be reproduced by turning WiFi off and on. I actually tried everything, including waking up from deep sleep. Couldn't get it to crash anymore.

**Comment by cowst** [comment]
With the wifi trick and standby it didn't crash.
Now I give it some longer sleep time, but so far it looked surprisingly good. 
I would have never thought to see this fixed in the lifetime of this TV.

**Comment by cowst** [comment]
I made it crash and reboot.
But I am not sure about the reason. 
I turned it off and on a bit too fast (my eyes are bleeding reading this about a 4-digits € device...)

**Comment by CiNcH83** [comment]
Yeah. I could get it crash as well when quickly turning the BRAVIA off and on again even without VPN. BRAVIAs are a flaky mess...

**Comment by borislip** [comment]
Consider updating the TV to Android 8, which is currently available, and actually **fixes the issue**

**Comment by CiNcH83** [comment]
Android 8 has been out for almost two years. That's not the decisive factor. The problem only seems to be fixed for latest FW 6.6575. I don't know whether it is also fixed for more recent models which rely on another firmware.

**Comment by cowst** [comment]
In fact I noticed that the kernel seems updated, unlike what I remember
from previous updates.

**Comment by CiNcH83** [comment]
It is still a 3.10.79 though. I think that the kernel is re-built for every firmware release, hence the newer build date. But I may be wrong.

**Comment by schwabe** [comment]
Closing this issue since it is basically stale and nobody understand the problem well enough to come up with a solution
