### ISSUE TITLE
could I add builder.	addRoute after builder.establish()?

### ISSUE THREAD

**Issue by YumingMa** [schwabe/ics-openvpn#1016]
I parse DNS packets to get the destination addresses then add them into tun route. but it doesn't work! Could you have a good idea, please?

**Comment by schwabe** [comment]
This question is extremely specific and I have no clue what you are actually trying to achieve.

And your questions seems to be about [VPNService](https://developer.android.com/reference/android/net/VpnService.Builder#establish()) While the app uses it, this bug tracker is for the app and not for helping you build your own VPN app.
