### ISSUE TITLE
Profile selection from API

### ISSUE THREAD

**Issue by ZaxonXP** [schwabe/ics-openvpn#1017]
Trying to do some automation using Automate app, where you can select package and activity class like"de.blinkt.openvpn.api.ConnectVPN" then you have Action and DATA URI to specify.

I would like to give profile name to be selected but I do not know how to do it. Please help.

Kind regards,
Piotr

**Comment by schwabe** [comment]
There is a FAQ in doc/README.txt:

`Q: How do I start a VPN by name from an external app?`

**Comment by ZaxonXP** [comment]
Thank you!
