### ISSUE TITLE
Disabling LZO Compression blocks VPN traffic

### ISSUE THREAD

**Issue by Taomyn** [schwabe/ics-openvpn#1019]
# General information
1. Android Version 9.0.0
2. Android Vendor/Custom ROM Google
3. Device Pixel 3
4. Version of the app (version number/play store version/self-built) 0.7.8
 
# Description of the issue
Disabling LZO Compression blocks VPN traffic

My OpenVPN server (running on OPNSense firewall v19), is set-up for a DNS only VPN connection i.e. normal traffic is kept local to my phones WiFi/LTE connection, only traffic to my remote network goes over VPN. The server also has compression disabled. If I connect with LZO compression enabled in the profile, I see a warning about compression in the log, which btw goes away if I switch to OpenVPN Core 3. If I disable LZO compression in the profile, my Internet stops working as my remote DNS is no longer accessible - in fact, none of my VPN services are reachable,

Is this normal behaviour?

**Comment by schwabe** [comment]
Yes. Compression setting mismatch makes a connection unusable. Remove it also from the server config.

For more details see OpenVPN manpage/documentation/https://community.openvpn.net/openvpn/wiki/VORACLE

**Comment by Taomyn** [comment]
Thank-you - I added to my server:

```
--compress stub-v2
--push "compress stub-v2"
```

And it seems to be fine now - I will report the problem to OPNSense as it doesn't appear to be disabling LZO even though the main GUI option is set that way.
