### ISSUE TITLE
Offer dark theme

### ISSUE THREAD

**Issue by PanderMusubi** [schwabe/ics-openvpn#1020]
# General information
1. Android Version 9.0.4
2. Android Vendor/Custom ROM OxygenOS
3. Device One Plus 5R
4. Version of the app (version number/play store version/self-built) 0.7.7
 
# Description of the issue
Offer dark theme via settings. Theme should use dedault dark theme settings such as colors from OS.

**Comment by PanderMusubi** [comment]
Couldn't find the duplicate after some searches. Could you link to it please? I'm curious why a dark theme will not be added.

**Comment by PanderMusubi** [comment]
Found it, this one I think https://github.com/schwabe/ics-openvpn/issues/566

**Comment by schwabe** [comment]
Yes. It just something I will not invest time into it as I personally do not see the benefit.

**Comment by mikewesten** [comment]
> Yes. It just something I will not invest time into it as I personally do not see the benefit.

The user base sees the benefit of this. Dark mode settings are fairly standard these days, and highly appreciated. White screens are brutal on the eyes once you get accustomed to dark mode interfaces.

**Comment by schwabe** [comment]
The app already implement a dark mode and follows the system theme for dark/light theme.

**Comment by pandalatte** [comment]
I have the latest 0.7.37 but there's no Dark Theme on/off option anywhere in the settings.

I'm on MIUI ROM. If this option is applicable only to stock Android, could you at least add it to Settings please? Much appreciated !

**Comment by schwabe** [comment]
The app will still follow the system theme. If you enable dark mode in the system, the app will also use dark mode and will use light mode if the system uses light mode. I do not plan to offer an option that allows a different mode than the system  mode.
