### ISSUE TITLE
Editing profile name does not update widget name

### ISSUE THREAD

**Issue by PanderMusubi** [schwabe/ics-openvpn#1021]
When importing profiles, the name of the profile is set automatically. When creating a widget for this, the widget uses that name. If it turns out that the profile name is too long to be distinctive, editing the profile name does unfortunately not update the widget name. See screenshot below.

Could editing profile name please update the connected widget name?

![Screenshot_20190327-091619](https://user-images.githubusercontent.com/198964/55063103-8db09100-5077-11e9-85b5-bcd2d0dfb61c.jpg)

**Comment by schwabe** [comment]
I think that is not something the app can change at all.
