### ISSUE TITLE
Setting to hide icon in notification tray

### ISSUE THREAD

**Issue by PanderMusubi** [schwabe/ics-openvpn#1022]
When OpenVPN is running, both its icon is shown in the notification tray on the left and the Android key icon is shown on the right.

For minimal amount of icons in your screen, please add a setting to OpenVPN to hide its icon on the left of the notification tray.

That part of the tray is intended for application notifications and, for me, a vpn runnig or not is more something in the system part on the right, where it is already shown by Android. Hiding this icon should also hide the real-time OpenVPN stats in the expanded notification tray. For some users, it is not relevant to see all the time when using the notification tray what the up and down rates are. For that, also the app can be opened and the nice graphs can be seen too, providing more information.

Implementing this will improve user control of what is shown and, if the user wants, less icons representing the same functionality.

See also the screenshots

![Screenshot_20190327-0916192](https://user-images.githubusercontent.com/198964/55064133-c487a680-5079-11e9-917f-beb6b51344a1.jpg)

![Screenshot_20190327-101541](https://user-images.githubusercontent.com/198964/55064146-c81b2d80-5079-11e9-90a4-83b8e33dd570.jpg)

**Comment by schwabe** [comment]
See FAQ. The app needs this for the foreground service priority
