### ISSUE TITLE
Are there any tutorials?

### ISSUE THREAD

**Issue by liguangze** [schwabe/ics-openvpn#1027]
Are there any specific tutorials? After downloading, I don't know where to start, and I can't run normally.

**Comment by schwabe** [comment]
Yes, there are tons of OpenVPN tutorials on the Internet

**Comment by liguangze** [comment]
No, no, I'm talking about your project now. First, I can't compile and run after downloading. After downloading APK, I don't know how to configure it. Do you have a detailed tutorial about this?

**Comment by schwabe** [comment]
Yes. You seems to not even read the README.md of this repository.

**Comment by schwabe** [comment]
Also there are a lot of of issues already about compiling this project.
