### ISSUE TITLE
Cipher negotiation succeeds on server, fails on client

### ISSUE THREAD

**Issue by grnassar** [schwabe/ics-openvpn#1028]
v0.7.8, on Android 8.0(/LG V20); also replicated on stock Android 8.1 (Nexus 6P).

Issue is identical to OpenVPN #906:
https://community.openvpn.net/openvpn/ticket/906

**Comment by schwabe** [comment]
906 is closed as fixed, so it should also fixed here. So this is probbly samething different

**Comment by grnassar** [comment]
Client and server logs attached.
[client-err.txt](https://github.com/schwabe/ics-openvpn/files/3128754/client-err.txt)
[server-err.txt](https://github.com/schwabe/ics-openvpn/files/3128755/server-err.txt)

**Comment by grnassar** [comment]
Please let me know if I can provide anything else to help troubleshoot. Beyond providing the upstream issue it seemed related to, I don't really know what else it could be, but anything I can do to help wiser heads figure it out, I'm happy to.

**Comment by h1z1** [comment]
As per the log:
```2019-04-29 06:30:25 Local Options String (VER=3DV4): 'V4,dev-type tun,link-mtu 1558,tun-mtu 1500,proto UDPv4,comp-lzo,cipher AES-256-CBC,auth SHA1,keysize 256,key-method 2,tls-client'```

...

```2019-04-29 06:30:26 Error: pushed cipher not allowed - CAMELLIA-256-CBC not in AES-256-CBC or AES-256-GCM:AES-128-GCM```

You have compression enabled and restricted negociation to AES-256-GCM  / AES-128-GCM.  Server is trying to push CAMELLIA-256-CBC.  Not sure what you expected.

**Comment by schwabe** [comment]
Yeah, this is a user configuration error.

**Comment by grnassar** [comment]
Sorry, I should have been clearer.  I had hoped commenters would read #906.  The symptoms are identical. The problem is with negotiation failing.  I didn't restrict negotiation to AES, on the client or the server.

Relevant cipher string on server:
`ncp-ciphers CAMELLIA-256-CBC:AES-256-GCM:AES-256-CBC`
`cipher AES-256-CBC`

I had hoped this was obvious, since the server sees the connection as successful and established.  This was leaving multiple zombie connections on the server side, for each time the client restarted.  So as simple a solution as "ciphers don't match" wouldn't make sense to begin with, unless there's a server bug upstream that would have to be so big as to seem unlikely.

Edit: just for curiosity's sake, tried restricting the client to AES-256-CBC (since camellia isn't supported on the client, as far as I know). Still didn't work. Also turned off compression, since the commenter mentioned it - no idea why it was thought it would make a difference, but it didn't.

**Comment by schwabe** [comment]
@grnassar ncp does not work like you think it works. Currently the Server *always* pushes the first cipher from the cipher list to the client. If that is not supported by the client you are dead. Please reread the man page

**Comment by grnassar** [comment]
Are you then saying that the fact that the server thinks negotiation completed successfully and establishes a new tunnel every time the client restarts is an upstream bug?

I could not see anything in the man page that explained why negotiation wouldn't continue with the next cipher if the first cipher failed -- I had previously checked it multiple times as well, but the negotiation process is pretty ambiguous in man.  So I just changed the Android config again, removed the ncp-cipher string and used ncp-disable instead.  The client connects perfectly, with no other change needed.  So problem circumvented for now, I suppose.  But the server behavior seems difficult to explain with the line of reasoning in the comments above.  If you could shed some light on that it would be appreciated.

**Comment by TinCanTech** [comment]
@grnassar exactly what `--cipher` and `--ncp-cipher` settings does your client use ?

**Comment by grnassar** [comment]
@tincantech Originally the settings I was using on the Android client were the same as on the server but with Camellia removed:

`ncp-ciphers AES-256-GCM:AES-256-CBC
`cipher AES-256-CBC

Which should not connect, of course; as @schwabe mentioned above that's not how NCP works. Expected behavior would then be that the client and the server report a failed connection due to not being able to negotiate a cipher. What I'm seeing instead is that the client soft-fails (which, if I understand correctly, is what it should do) and the server treats the connection as established. Then, when the soft-failed client retries, the server establishes another new connection over and over for every subsequent retry.

I'm currently deciding to treat this as a server issue rather than a client issue and troubleshoot from there; I wasn't seeing this behavior with any other clients but it's possible there were config differences I didn't take into account, especially since the Android client adds other settings from its GUI into any imported .ovpn file (which I didn't realize before creating this ticket, and only recently discovered).  So while it seems like any situation where in a client-server application the client fails a connection but the server believes the connection is successful should be considered a bug, I want to be more confident about whether it is the client or the server causing this issue before moving forward with a more detailed bug report in the appropriate place.

**Comment by schwabe** [comment]
The current design of NCP is the fault. It always pushes the first cipher of the server list to the client. On your other client that cipher just happens to be supported and also in the ncp-cipher list.

**Comment by TinCanTech** [comment]
> The current design of NCP is the fault. It always pushes the first cipher of the server list to the client
https://community.openvpn.net/openvpn/ticket/1185#ticket
