### ISSUE TITLE
Question about you app.

### ISSUE THREAD

**Issue by yannled** [schwabe/ics-openvpn#1032]
Hello,

I'm doing my Bachelor project and I'm supposed to do an android app who use a VPN. 
My question is the following: Is it possible to use your application with the Aidl and bypass the popup who asking password and give the password by a function (My app is supposed to do all transaction transparent so the user doesn't have to type his password and I generate one manually)

If it's not possible, do you have documentation to help me to understand you app and implement only the VPN part in my own app ?

My project is for a university Bachelor so not for sale.

Thanks you in advance for your answer and for your useful Android application

**Comment by schwabe** [comment]
I already answered your questions via mail
