### ISSUE TITLE
could not execute external program

### ISSUE THREAD

**Issue by nnjun** [schwabe/ics-openvpn#1033]
Failed running command (--client-connect): could not execute external program

Whatever is in it is a failure to execute.

**Comment by schwabe** [comment]
External scripts are known not to work on android

**Comment by nnjun** [comment]
But this one is centos7, excluding permissions, coding, script errors and other factors.

**Comment by nnjun** [comment]
It's no use trying to switch to Ubuntu.I hope I can get help! Thanks very much @schwabe

**Comment by schwabe** [comment]
@nnjun then you are on the completely wrong issue tracker, this one is only for the Android App
