### ISSUE TITLE
 OpenVPN Connect gets stuck on the Connection request pop-up on the Verizon Note9

### ISSUE THREAD

**Issue by jdrch** [schwabe/ics-openvpn#1035]
# General information

1. Android Version: 9.0
2. Android Vendor/Custom ROM: Samsung OneUI
3. Device: Verizon Samsung Galaxy Note9
4. Version of the app (version number/play store version/self-built): 3.0.5
 
# Description of the issue

OpenVPN Connect gets stuck on the **Connection request** dialog on the Verizon Note9 when I'm trying to connect to my VPN. While I can tap **Cancel** in the screenshot below, I can't tap **OK**, even when I use a mouse:

![Screenshot_20190528-093311](https://user-images.githubusercontent.com/1056759/58488918-de07a600-812f-11e9-8c9c-8255d9d979b1.jpg)

I tried connecting to the same VPN using OpenVPN Connect on my Galaxy S5 running LOS 16.1 and it worked, so I'm pretty sure the problem lies with the Note9. Ideas?

**Comment by schwabe** [comment]
Wrong client. Off topic here but see my clients FAQ for that.
