### ISSUE TITLE
Add Device Admin setting to support Samsung devices

### ISSUE THREAD

**Issue by jdrch** [schwabe/ics-openvpn#1037]
**UPDATE:** [Solution](https://community.verizonwireless.com/t5/Samsung-Galaxy-Note/OpenVPN-Connect-gets-stuck-on-the-Connection-request-pop-up-on/m-p/1113513#M20993).

# General information
1. Android 9.0
2. Samsung/OneUI
3. Verizon Samsung Galaxy Note9
4. v0.7.8
 
# Description of the issue

OpenVPN apps can't connect on Note9. This is apparently because OpenVPN apps need to be device admins for their connections to work:

https://forum.xda-developers.com/showpost.php?p=79467666&postcount=24

https://eu.community.samsung.com/t5/Galaxy-S9-S9/VPN-is-broken-in-Galaxy-S9/td-p/707252/page/2

Kindly add this feature to the app. Thanks!

**Comment by schwabe** [comment]
Samsung being Samsung. Unfortunately, I don't have a Note9 and cannot test/implement this. So, unless someone else creates PR for this (or gifts me a Note 9 :P) I fear this bug will stay open.

**Comment by jdrch** [comment]
Fair enough. Would it be possible for you to build a test .apk with the Device Admin capability included? I'd be happy to test it for you and provide logs. OpenVPN functionality is critical to my workflow, so I'm very motivated to assist you :)
