### ISSUE TITLE
mbedutils does not contain a CMakeLists.txt file.

### ISSUE THREAD

**Issue by Scothosts** [schwabe/ics-openvpn#1040]
Android Studio 3.4.1

Installed everything you suggest including SWIG but cannot compile your code on Mac. Destination is Android 9 on Samsung S9. My error now is mbedtls does not contain a CMakeLists.txt file. 

I am new to Android development but have been developing in other languages for over 25 years. I do not want to put my code in the GitHub repository but I think I need the submodules you speak of. If you can offer any solution as to how I can get them or if indeed they relate to my error message at all I would be greatly appreciated. I have spent too long trying to get this code working using the help files or comments from other users and I am now completely stuck. I had your old version of openvpn working on my old s6 but it won't work on my new S9 due to updates on Android. Please help. Kind regards. 
<img width="692" alt="Screenshot 2019-06-04 at 11 43 02" src="https://user-images.githubusercontent.com/31768600/58873424-3dc8f880-86be-11e9-89c9-260c14a892ec.png">

**Comment by schwabe** [comment]
Yes, see the readme or git readme. That you are hiding the path name tells me that this contains the name of a commercial VPN software and you don't want me to know that.

**Comment by Scothosts** [comment]
I read the read me and it is not answering my question. I blanked my path as I am an ethical hacker and don't ever provide full path to anyone - even you. I still need help but I see you close off all the issues you don't want to answer.

**Comment by Scothosts** [comment]
I don't understand this:-
Fetch the git submodules (the default urls for the submodules work as
long as the main repo url is on github):

  git submodule init
  git submodule update

**Comment by schwabe** [comment]
The last blanked outed chars spell VPN. So I stand by my reason and just quote my FAQ:

```
Q: Why are you not answering my questions about modifying
   ics-openvpn/why do not help build my app on top of ics-openvpn? I
   thought this is open source.

A: There are many people building/wanting to build commercial VPN
   clients on top of my of my client. These client often do not even
   honour the license of my app or the license of OpenVPN. Even if
   these modified software do honour the license, I don't like doing
   unpaid work/giving advice for free to commercial software
   developers.
   
   If you have a legitimate non-commercial open source project, I will
   gladly help you, but please understand my initial reservations.
```

Sorry but I just fed up with commercial VPNs and if you make no real effort to dispell my doubts, then that all from me.

**Comment by Scothosts** [comment]
The app I am developing is free to our customers(of which there are not many) and so it is still within the GPL requirements. However I have spoken to my boss and he is asking how much you would charge to help. 

I do not use Github as a repository for this software as I said I am an Ethical Hacker and do not consider it as a suitable location to store the code.

I look forward to hearing from you and hope that we can come to an arrangement

Kind regards

Stefan

**Comment by schwabe** [comment]
learn how to use git submodules. That is not even specific to my project. Google for a tutorial.
