### ISSUE TITLE
openvpn config file parse error

### ISSUE THREAD

**Issue by xeciyu** [schwabe/ics-openvpn#1043]
# General information
1. 7.1 & 6
2.
3. 
4. 0.7.8
 
# Description of the issue

i have get this error when use default mss size (1450) & mtu (1500) over openvpn **3**

openvpn config file parse error: _option_error: option 'mssfix' must have at least 2 arguments_

--i changed mss size to 1460 or 1400 and don't get this error.
--don't get this error over openvpn 2 it is occured over openvpn **3** only

**Comment by canary5** [comment]
Can confirm this

**Comment by schwabe** [comment]
Please add more details. E.g. the config that fails to parse.

**Comment by xeciyu** [comment]
i have test different vpn service and get this error for example protonvpn
--attach proton config (austria server) on txt format!  
[at-03.protonvpn.com.udp.txt](https://github.com/schwabe/ics-openvpn/files/3265420/at-03.protonvpn.com.udp.txt)
