### ISSUE TITLE
Unable to find file 'src\main\cpp\openvpn3\javacli\ovpncli.i'

### ISSUE THREAD

**Issue by illwiz** [schwabe/ics-openvpn#1049]
Info
1. Windows 10 64 Bit
2. Swig Installed (checked by swig -version in cmd)
3. Tried this still doesn't work https://github.com/schwabe/ics-openvpn/issues/832#issuecomment-362062544
 
When i try to build the project with "gradle build" i got this error 
```
> Task :main:generateOpenVPN3Swig FAILED
Unable to find file 'src\main\cpp\openvpn3\javacli\ovpncli.i'.
```
![builderrror](https://user-images.githubusercontent.com/30684151/59563892-d02bad80-9069-11e9-8891-70324089b0ab.png)

Can i manually create the ovpncli.i file using swig, how to do it?

**Comment by schwabe** [comment]
you are probably missing the git submodules see README

**Comment by ajavafans** [comment]
Have same issue.
I have read the readme and installed swig, but this issue is occurring on my side.
I have been suing Android Studio 3.5.1 on Window 10
Please help me.
Thanks.
