### ISSUE TITLE
Menu item permanent disabled after first saving

### ISSUE THREAD

**Issue by pm-pm** [schwabe/ics-openvpn#1052]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 8.1
2. Motorola Stock
3. Motorola G5
4. Version of the app: 0.7.8
 
Menu item "IPv4/6 Address" and "Informationen abrufen" are disabled (locked) after saving.

Reproduce:
Tap: Add new profile
Enter Profile Name
Switch to static key
(At this point you _could_ enter IPv4 Address)
Leave config = save config

Enter config again and the points "IPv4/6 Address" and "Informationen abrufen" are locked after first saving. Is this the way it should work or a bug?

_To unlock (workaround):
Edit config
Switch to "Certificates"
Leave config = save config
Enter config again and you can edit IPv4 Address again.
Config your IPv4 Address
Switch back to "Static key"
Leave config = save config_

**Comment by schwabe** [comment]
Should be fixed in next version. As workaraound disable "Information abrufen" before changing to static keys.
