### ISSUE TITLE
Libretorrent over VPN not connecting

### ISSUE THREAD

**Issue by toomklang** [schwabe/ics-openvpn#1054]
Hello. I am trying to force torrent app Libretorrent to use the VPN and I can tell it is not working because no tracker connections are working. I have AFWall set to allow access to VPN interface for Libretorrent, excluding other access. Is it an issue with torrent app or OpenVPN? Android v7 LineageOS, app from f-droid.

https://gitlab.com/proninyaroslav/libretorrent/issues/247

**Comment by schwabe** [comment]
Might even be an AFWall issue that it cannot handle VPN apps properly. Or your VPN blocks torrent. Anyway, it is probably not a problem in OpenVPN, so I am closing this.
