### ISSUE TITLE
Please upgrade openvpn to 2.4.7

### ISSUE THREAD

**Issue by ruben-herold** [schwabe/ics-openvpn#1056]
hi,

I noticed that the openvpn version in your app is not the current. 
For example Support for redirect-gateway ipv6!ipv4 is missing.

For all new features look at:

https://github.com/OpenVPN/openvpn/blob/release/2.4/Changes.rst

**Comment by schwabe** [comment]
I have no idea how you come to this conclusion of my app using an old version. 

Your `redirect-gateway ipv6!ipv4` is missing a space between `ipv6` and `!ipv4`.
