### ISSUE TITLE
Allow explicity Network.bindSocket(Socket) to the VPN interface even when "Allow apps to bypass the VPN" is off

### ISSUE THREAD

**Issue by rhobison** [schwabe/ics-openvpn#1058]
# General information
1. Android Version
    Android 7.1.1
2. Android Vendor/Custom ROM
    Samsung
3. Device
    Galaxy Tab A (2017) - SM-T385M
4. Version of the app (version number/play store version/self-built)
   OpenVPN for Android 0.7.8
 
# Description of the issue
When my application tries to bind a socket to the "tun0" interface (VPN interface), I'm getting an 
"java.net.SocketException: Binding socket to network 514 failed: EPERM (Operation not permitted)".
The option "Allow apps to bypass the VPN" is off, but my understanding is that this operation should be allowed because I'm not trying to bypass the VPN, I'm just explicitly binding the socket (Network.bindSocket(Socket)).

I'm getting the same exception when I'm trying to bind to the "rmnet0" interface, but this is the right behavior because in this case, I'm trying to bypass the VPN.

Please, allow the explicit binding to the "tun0" interface without throwing the SocketException.
My application needs to do this explicit binding.

Thanks!

**Comment by schwabe** [comment]
I am not sure what else than setting the allow bypass vpn of the vpnservice I can do. The exception you are seeing is coming from Android not from me.

**Comment by rhobison** [comment]
Ok, so the interface in which the application is trying to bind to is not under your control?

Do you suggest anything that I can do to overcome this issue other than not doing the explicit binding?
I cannot rely on the configuration "Allow apps to bypass..." of the OpenVPN. The user can disable it, I don't have control over it.

Thanks!

Rhobison Alves Pereira

Em 5 de jul de 2019 18:37, Arne Schwabe <notifications@github.com> escreveu:

I am not sure what else than setting the allow bypass vpn of the vpnservice I can do. The exception you are seeing is coming from Android not from me.

**Comment by schwabe** [comment]
I use the VPNService API (https://developer.android.com/reference/android/net/VpnService.Builder.html).

And you are complaining that the option "allow other apps to bypass..." works as expected basically?

**Comment by rhobison** [comment]
No, I'm complaining that binding to the VPN network interface (tun0, in my case) is not the same as "bypass the VPN". If I'm binding to the VPN interface, I'm not breaking the rule. All data from my application would go through the VPN interface. So, this operation should be accepted even if the "Allow apps to bypass..." is not set.
Did you understand?
I'm not blaming you, I understood that Android does not provide the means for you to do that.
I'm just asking if you have some suggestion to overcome this issue because, probably, you have a lot more knowledge on this subject than I have.

Thanks!

**Comment by schwabe** [comment]
Actually I am not so familiar with the API to bind to direct interfaces. But other than setting a flag to allow or disallow it, there is nothing I can do from my app.

You are probably better off submitting a bug report to Google.

**Comment by rhobison** [comment]
Ok, no problem, thank you!

**Comment by sis-tangyuan** [comment]
> Ok, no problem, thank you!

can't bindsocket with any transportType(wifi/cellular/vpn) while vpn service no allow bypass. I encounter this problem too. Have you fixed it.

**Comment by rhobison** [comment]
> > Ok, no problem, thank you!
> 
> can't bindsocket with any transportType(wifi/cellular/vpn) while vpn service no allow bypass. I encounter this problem too. Have you fixed it.

Hi! It is a long time, but as far as I can remember, I could not overcome the issue. But I don't have access to the code anymore to check if I did anything else. Sorry!

**Comment by schwabe** [comment]
The allow no bypass option is exactly for controlling this. See Android docu https://developer.android.com/reference/android/net/VpnService.Builder#allowBypass()
