### ISSUE TITLE
Can we use this in React as a library?

### ISSUE THREAD

**Issue by pep1439** [schwabe/ics-openvpn#1060]
Hi,
Can we use this project as library in React?

Thanks.

**Comment by schwabe** [comment]
Provided you honour the license and do the glue layer yourself, of course you can.

**Comment by pep1439** [comment]
But seems no native support available
https://github.com/facebook/react-native/issues/19816

**Comment by schwabe** [comment]
Yes, that is why wrote that you need to do the glue layer yourself
