### ISSUE TITLE
MTU changes based on setting 'Block IPv6 (or IPv4) if not used by the VPN'

### ISSUE THREAD

**Issue by bro-helper** [schwabe/ics-openvpn#1061]
Hey there.

I have openvpn server without internet access, so it has no NAT, and the purpose is just to organize remote clients in one virtual network (obviously).

When I have openvpn client disconnected and go to any website that shows MTU, it shows one value. When I connect openvpn to my server and check MTU again - it changes.
If I use `mssfix` key in ovpn config it doesn't change anything.
If I use `mssfix` key for different ovpn server that has nat and I go to internet via it, then it works fine.

I was trying all the options and I've found out that when in ovpn connection settings I uncheck 'Block IPv6 (or IPv4) if not used by the VPN' setting, then MTU doesn't change after connection.

My goal was not to change MTU, so I've kind of achieved it, but I'm curious why does this happen? This setting doesn't add anything to ovpn config, it's just some internal thing.

Same issue I experience with official ovpn client, but there they don't have such option and I wasn't able to disable changing MTU using their client.

Maybe I miss some config value on client or on server side?

Would highly appreciate any ideas and thoughts, how this thing works. Thanks.

Looks like it's using this method under the hood of this client: https://developer.android.com/reference/android/net/VpnService.Builder.html#allowFamily(int)

keywords: mBlockUnusedAddressFamilies, mBlockUnusedAF, allowFamily, allowAllAFFamilies

**Comment by schwabe** [comment]
What MTU values are you seeing? And if you are using something like mssfix 1280 or mssfix 1350 you should definitively have an effect.

What Android exactly does under the hood when calling allowFamily, I cannot really say without digging through AOSP code but it is notthing the app can really influence.

**Comment by bro-helper** [comment]
Thanks for such rapid reply @schwabe 
Without VPN it's 1400 (LTE connection), with VPN it's 1392.
`mssfix` has no effect in my case, I've tried adding it to server and client configs with different values, it feels like it doesn't work if NAT is not active.
I use very typical openvpn server config, nothing special, just made it according to [the manual](https://www.digitalocean.com/community/tutorials/how-to-set-up-an-openvpn-server-on-ubuntu-16-04) but without NAT part.

**Comment by vijodvijay** [comment]
@schwabe please contact on my email id vijodvijay@gmail.com
Its for a business deal please contact as soon as possible.

**Comment by schwabe** [comment]
@vijodvijay just write me to arne@rfc2549.org

@nullday I have absolutely no clue what happening on your part and I have no idea how I would reproduce this.
