### ISSUE TITLE
Build error- Process 'command 'swig'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by puneetbahuguna** [schwabe/ics-openvpn#1062]
Hi When I am trying to build the app as per the document then I am facing this build error. Can you please help or any workaround for this.

**Process 'command 'swig'' finished with non-zero exit value 1**

I am using android studio 3.4.2

**Comment by schwabe** [comment]
Duplicate, see other closed issues

**Comment by fariya12** [comment]
i am facing the same error have you found the solution ??

**Comment by puneetbahuguna** [comment]
Yes. solved it. actually I had forgot to fetch sub-module from git which has been guided in doc. please first follow below commands in your android studio terminal and then again try to build your project.
  git submodule init
  git submodule update
