### ISSUE TITLE
Not able to run project

### ISSUE THREAD

**Issue by puneetbahuguna** [schwabe/ics-openvpn#1064]
I was able to build it in android studio 3.4.2 on windows. But I can not run it. When I am editing the run configuration then Its showing no module there. Its not able to load main module.
Can you please guide.

o make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

**Comment by schwabe** [comment]
I don’t use Windows as build platform so building on it is not officially supported. It may work or not. Patches to fix Windows are appreciated.

**Comment by puneetbahuguna** [comment]
Can I simply use some part of this project as a library which are needed for supporting open vpn, if I dont want to use or import whole project in my android studio.

**Comment by schwabe** [comment]
Sure, as long as you respect the GPL and have your project open source you can take part of this project for your own.
