### ISSUE TITLE
Help building project

### ISSUE THREAD

**Issue by BioZrod** [schwabe/ics-openvpn#1066]
# Description of the issue

I have installed the requirements specified in the readme. I am using Android Studio on MACOS 10.14.6
When trying to build project from Android Studio I get the following Error:

Build command failed.
Error while executing process /Users/biozrod/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/biozrod/Documents/Git Repositories/ics-openvpn/main/.externalNativeBuild/cmake/skeletonDebug/x86_64 --target opvpnutil}
[1/9] Linking C shared library "/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/build/intermediates/cmake/skeleton/debug/obj/x86_64/libopenvpn.so"
[2/9] cd "/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/.externalNativeBuild/cmake/skeletonDebug/x86_64" && /Users/biozrod/Library/Android/sdk/cmake/3.6.4111459/bin/cmake -E make_directory /Users/biozrod/Documents/Git\ Repositories/ics-openvpn/main/src/main/cpp/../../../build/ovpnassets
FAILED: : && /Users/biozrod/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/biozrod/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64 --sysroot=/Users/biozrod/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot -fPIC -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fno-addrsig -Wa,--noexecstack -Wformat -Werror=format-security  -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -shared -Wl,-soname,libopenvpn.so -o "/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/build/intermediates/cmake/skeleton/debug/obj/x86_64/libopenvpn.so" CMakeFiles/openvpn.dir/openvpn/src/compat/compat-basename.c.o CMakeFiles/openvpn.dir/openvpn/src/compat/compat-daemon.c.o CMakeFiles/openvpn.dir/openvpn/src/compat/compat-dirname.c.o CMakeFiles/openvpn.dir/openvpn/src/compat/compat-gettimeofday.c.o CMakeFiles/openvpn.dir/openvpn/src/compat/compat-inet_ntop.c.o CMakeFiles/openvpn.dir/openvpn/src/compat/compat-inet_pton.c.o CMakeFiles/openvpn.dir/openvpn/src/compat/compat-lz4.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/argv.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/base64.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/buffer.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/clinat.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/console.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/console_builtin.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/crypto.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/crypto_openssl.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/crypto_mbedtls.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/cryptoapi.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/dhcp.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/error.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/event.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/env_set.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/fdmisc.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/forward.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/fragment.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/gremlin.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/helper.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/httpdigest.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/init.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/interval.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/list.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/lladdr.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/lzo.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/manage.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/mbuf.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/misc.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/mroute.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/mss.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/mstats.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/mtcp.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/mtu.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/mudp.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/multi.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/ntlm.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/occ.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/openvpn.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/options.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/otime.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/packet_id.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/perf.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/pf.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/ping.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/pkcs11.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/pkcs11_openssl.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/platform.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/plugin.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/pool.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/proto.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/proxy.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/ps.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/push.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/reliable.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/route.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/run_command.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/schedule.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/session_id.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/shaper.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/sig.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/socket.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/socks.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/ssl.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/ssl_openssl.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/ssl_mbedtls.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/ssl_verify.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/ssl_verify_openssl.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/ssl_verify_mbedtls.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/status.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/tls_crypt.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/tun.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/comp-lz4.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/comp.c.o CMakeFiles/openvpn.dir/openvpn/src/openvpn/compstub.c.o  libcrypto.a libssl.a liblzo.a libcrypto.a -latomic -lm && :
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/crypto_openssl.c:775: error: undefined reference to 'EVP_CIPHER_CTX_init'
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/crypto_openssl.c:798: error: undefined reference to 'EVP_CIPHER_CTX_cleanup'
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/ssl_openssl.c:79: error: undefined reference to 'SSL_library_init'
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/ssl_openssl.c:81: error: undefined reference to 'SSL_load_error_strings'
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/ssl_openssl.c:83: error: undefined reference to 'OpenSSL_add_all_algorithms'
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/ssl_openssl.c:92: error: undefined reference to 'EVP_cleanup'
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/ssl_openssl.c:94: error: undefined reference to 'ERR_free_strings'
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/ssl_openssl.c:559: error: undefined reference to 'X509_get_notBefore'
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/ssl_openssl.c:569: error: undefined reference to 'X509_get_notAfter'
/Users/biozrod/Documents/Git Repositories/ics-openvpn/main/src/main/cpp/openvpn/src/openvpn/ssl_openssl.c:648: error: undefined reference to 'SSL_CTX_set_ecdh_auto'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

**Comment by schwabe** [comment]
Current master does not build out of box. Please to a released version if you don't want to fix it yourself.
