### ISSUE TITLE
A simple android vpn apk to channel all network traffic from one existing predefined app to our VPN server.

### ISSUE THREAD

**Issue by davemasters** [schwabe/ics-openvpn#1067]
We have a requirement for a simple android vpn apk to channel all network traffic from one existing predefined app to our VPN server. 
The existing app cannot be modified so we are using the vpn to route the app's network traffic to a different backend. 
This will be installed on 500 phones for non technical users. Therefore, ideally the vpn apk will be built with a preconfigured profile to connect to a fixed backend and restrict the vpn to the single application. 
Can you suggest how this would be done? 
Are you able to provide development resources or recommend a developer who is familiar with OpenVPN?

**Comment by sysxda** [comment]
check mail

**Comment by schwabe** [comment]
@coderzstas Please keep all conversation here on the issue tracker.

**Comment by schwabe** [comment]
Doing what you require is certainly something you can do when building upon this app. The single app requirement means that this would only work on Android 5.1+.

You can also contact me under arne@rfc2549.org
