### ISSUE TITLE
How to run on Android Phone

### ISSUE THREAD

**Issue by BioZrod** [schwabe/ics-openvpn#1071]
Hello, I am trying to learn how vpn connections work and I am fairly new to Android Studio.
I followed the documentation and I managed to build the project successfully, but then I tried to run the project on my phone and I am stuck here:

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/12672464/63473463-672a3280-c42a-11e9-8526-efa018b3b767.png">

I wonder if someone can point me on the right direction on how to be able to try the library to see how it works and how I could provide my own file to connect to a server.

**Comment by schwabe** [comment]
Probably gradle sync error, see Readme and other ticket (probably need to install swig)
