### ISSUE TITLE
Can't import .ovpn 

### ISSUE THREAD

**Issue by onselakin** [schwabe/ics-openvpn#1072]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
8.0.0 

2. Android Vendor/Custom ROM
Philips

3. Device
Philips Android TV

4. Version of the app (version number/play store version/self-built)
0.7.8
 
# Description of the issue
I can not select the .ovpn file from the import option. The file appears grayed out in file browser and I don't know if the format is broken or is there any other problem.
I downloaded the .ovpn file from my own OpenVPN server.

**Comment by schwabe** [comment]
Your server probably set a very weird mime type.

**Comment by onselakin** [comment]
I'm downloading the profile from the web interface as you can see on the screenshot.

![image](https://user-images.githubusercontent.com/10635384/63646788-f7b18d00-c720-11e9-8c65-74d32fee7eda.png)

Please note that this .ovpn file works fine with the Mac OS X client without problems.

**Comment by schwabe** [comment]
Hm, strange OpenVPN AS should set the right mime type.

What file browser you do you use? The internal one of the app or the Android system one?

**Comment by onselakin** [comment]
Ok, here's what I do in detail:

I downloaded the profile to my Mac as the default browser prevents me from opening the OpenVPN page because of the unverified SSL certificate. Couldn't try Chrome because Chrome works really weird on Android TV, you can't even type an address to navigate.

I transferred the ovpn from my Mac to the TV, opened OpenVPN for Android and chose Import option to get the file from the internal storage. The File Manager app opens, I navigate to the folder I stored the ovpn file but can't seem to select the file as the file is grayed out. So I thought there must be something wrong with the format of the file at first but now thinking afterwards, there must be some other problem and I don't know what actually.

**Comment by schwabe** [comment]
There is a setting under general setting that allows to choose the file manager. Please try toggling it.
