### ISSUE TITLE
how can exclude openvpn3.so from apk

### ISSUE THREAD

**Issue by cspannery** [schwabe/ics-openvpn#1073]
Hello , we don't use openvpn3 ,how can we exclude it's so file from apk ? it takes about 3MB.
Can we do that ?

**Comment by schwabe** [comment]
I feel that on modern phones 3MB should not be an issue.

**Comment by cspannery** [comment]
If we build universal apk with ABI's ("armebi-v7" , "armebi-v8a" ....) it will be duplicate on every ABI and not just single 3MB .so file 
Is there any way to exclude it safely ?
We don't need to publish on Google Play Store to Split apk's.

**Comment by schwabe** [comment]
@khaledayashy From my experience people who ask these kind of question ignore my GPL license and publish the app as closed source. You have to convince that this is not the case for you to get any help.

Sorry, but I have really bad experience in the past.

**Comment by cspannery** [comment]
please can you delete this issue.

**Comment by schwabe** [comment]
It is already closed.
