### ISSUE TITLE
Usage with Orbot?

### ISSUE THREAD

**Issue by cliff19** [schwabe/ics-openvpn#1074]
Is there an extra step intended for enabling orbot alongside my VPN? I have orbot running in the background and the radio button ticked however I see nothing in the log or config about TOR and my traffic is still only routed through the vpn(check.torproject.org confirms this). I have tried using orbot on its own and it works fine.

**Comment by schwabe** [comment]
Please include a log file.

**Comment by cliff19** [comment]
> Please include a log file.

Of what?

**Comment by schwabe** [comment]
Of the attempt trying to via orbot. If you use orbot only connect to the VPN server, it is correct that you see your VPN IP with checkip

**Comment by cliff19** [comment]
I think I misunderstand. Are you saying the design is to connect to tor before connecting to the VPN?

**Comment by schwabe** [comment]
yes.reaching the vpn server using tor.

**Comment by cliff19** [comment]
> yes.reaching the vpn server using tor.

What is the point in that? That defeats the purpose of tor. Is this because proper configuration is not possible on android?

**Comment by schwabe** [comment]
The point is to be able to reach your VPN server. Connection to that might also be blocked. It is a different use case from the one that you want.
