### ISSUE TITLE
Throughput to AWS Client VPN is extremely low

### ISSUE THREAD

**Issue by melan** [schwabe/ics-openvpn#1075]
# General information
Device 1:
1. Android Version: 8.1.0
2. Android Vendor/Custom ROM: Seems like standard Android
3. Device: Samsung SM-P580 
4. Version of the app (version number/play store version/self-built): The current play store version

Device 2:
Google Pixelbook. ChromeOS 76.0.3809.102. Arc version: 5768992
 
# Description of the issue
Speed test for VPN connection to AWS Client VPN from the devices shows 10-20 kbps

In all other cases the same test shows 50-100 Mbps:
* From the devices without VPN
* From the devices using OpenVPN for Android pointing to a different OpenVPN server
* From other devices (OS X and iOS) with OpenVPN client pointing to the AWS Client VPN endpoint.

ovpn file I used for the test:

```
client
dev tun
proto udp
remote cvpn-endpoint-#########.prod.clientvpn.us-west-2.amazonaws.com 443
remote-random-hostname
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-GCM
verb 3
<key>
-----BEGIN RSA PRIVATE KEY-----
MII...
-----END RSA PRIVATE KEY-----
</key>
<cert>
-----BEGIN CERTIFICATE-----
MII....
-----END CERTIFICATE-----
</cert>
<ca>
-----BEGIN CERTIFICATE-----
MII...
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MII...
-----END CERTIFICATE-----

</ca>

reneg-sec 0
```

Support in Google and Amazon are unable to come up with any reasonable suggestions. Logs don't show anything suspicious.

Thanks in advance for your help

**Comment by schwabe** [comment]
No mssfix, might be MTU related but this should not be related to the app itself. This issue does not really contain enough information to debug this kind of issue. But there is no general slowness of this client comared to  other platforms.
