### ISSUE TITLE
Excessive Battery Use Android 10 Pixel 2

### ISSUE THREAD

**Issue by lbossom** [schwabe/ics-openvpn#1078]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
Android 10
2. Android Vendor/Custom ROM
Stock android
3. Device
Pixel 2
4. Version of the app (version number/play store version/self-built). 
Version 0.7.8 from Play Store
 
# Description of the issue
I've been using Open VPN for Android for several months without any problems.  My phone installed OTA update to Android 10 a few days ago and now the app is draining my battery.   According to the system stats OpenVPN for Android is responsible for 146% of my battery usage since last charge with the next highest app using only 12%.  I'm not sure how the math works for something to use 146% but that's what it shows. 

Any help you can provide would be appreciated.  Thanks

![Screenshot_20190909-093927](https://user-images.githubusercontent.com/9169191/64540593-10f03700-d2e6-11e9-8b6d-8b58cb66cedd.png)

**Comment by schwabe** [comment]
This seem buggy. ANd this is by the operating system. Has the real world usage (battery drain) changed?

**Comment by lbossom** [comment]
Thanks for the quick response.  Yes, my actual battery drain while using
the app meshes with what the system is reporting.  Thanks again for your
assistance.  I appreciate it!

**Comment by schwabe** [comment]
You are saying that your actual consuptiom matches with OpenVPN using more than what the phone has as battery? That makes no sense, sorry.
