### ISSUE TITLE
Contact you

### ISSUE THREAD

**Issue by brattony** [schwabe/ics-openvpn#1080]
Hi @schwabe 
I found only this way to contact you. I want to use your client for my project. Please email me the paid license amount and process to pay for that.

Thanks
brat1994tony@gmail.com

**Comment by schwabe** [comment]
You were not looking very hard. Contact me under arne@rfc2549.org

**Comment by brattony** [comment]
Thank you for reply.

**Comment by brattony** [comment]
Hi @schwabe 

Hope you doing well
I have sent you email from brat1994tony@gmail.com. Please check your email. 

Thank you
