### ISSUE TITLE
Client disconnected successfully but server cant get message about client has disconnected !

### ISSUE THREAD

**Issue by cspannery** [schwabe/ics-openvpn#1083]
Hi.
when user disconnect his/her phone from VPN with disconnect button it's work correctly but server doesn't got  noticed about this action .
in OpenVpn we can see how many clients are connected to VPN with **status.log** file or managment interface .

with main (OpenVPN connect) i tested it and it's tell the server about disconnecting user from server.

with openvpn main app => server remove user connection log immediately
with ics-openvpn app => server remove user after timeout of keep alive action .(about 2min)

**Comment by cspannery** [comment]
we test with openvpn3 and problem fixed , please delete this issue .

**Comment by schwabe** [comment]
You probably are missing the exit notify option.
