### ISSUE TITLE
Need paid support

### ISSUE THREAD

**Issue by ajitjati** [schwabe/ics-openvpn#1085]
Hi Arne Schewable,

Hope you are doing well.

We are writing this to get official support from you regarding using ics-openvpn in our existing app. Can you please guide us help us in this process. How we can use the project/module in existing android app.

Please let us know the effort and cost from your side so that we can use ics-open vpn in our android app.

Looking forward to hear from you.
ajit.jati@oodlestechnologies.com

Thanks

**Comment by schwabe** [comment]
Please contact me via email arne@rfc2549.org
