### ISSUE TITLE
fails to build with unknown asm instruction .hidden

### ISSUE THREAD

**Issue by ruchikasharma09** [schwabe/ics-openvpn#1086]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. SYSTEM: MAC 
After building project using CMAKE we got MakeFile and while executing MakeFile we got this error. Please help this to resolve asap.
![Screenshot 2019-10-09 at 4 37 04 PM](https://user-images.githubusercontent.com/27682184/66477809-9d913f00-eab6-11e9-8d70-ebf20e465a47.png)

main/src/main/cpp/openssl/crypto/aes/asm/aes-x86_64.S:1379:1: error: unknown directive
.hidden asm_AES_cbc_encrypt

**Comment by schwabe** [comment]
I am using a mac too. So that is not the problem. Do you use an outdated ndk toolchain?

**Comment by ruchikasharma09** [comment]
Can you please help me to get NDK Toolchain version ?
I mean how can I find this ?

**Comment by schwabe** [comment]
See Android Studio help and documentation.
