### ISSUE TITLE
Conflicting type for basename

### ISSUE THREAD

**Issue by ruchikasharma09** [schwabe/ics-openvpn#1087]
![Screenshot from 2019-10-10 12-49-53](https://user-images.githubusercontent.com/27682184/66547761-92451e80-eb5d-11e9-83d0-901e89f7add3.png)
General information
1. Device: Ubuntu
While building this library using ANDROID_ABI=x86_64 in CMAKE and then after the following command: make -f Makefile. I got the following issue.

**Comment by schwabe** [comment]
I have the feeling you are using a wrong way to build the project. Building the project does not involve `make -f Makefile`. You should not need to invoke `cmake` manually.
