### ISSUE TITLE
Issues with Google Apps

### ISSUE THREAD

**Issue by error401de** [schwabe/ics-openvpn#1088]
# General information
1. Android Version
9
2. Android Vendor/Custom ROM
Samsung
3. Device
Galaxy S9
4. Version of the app (version number/play store version/self-built)
3.0.7.(3565)
 
# Description of the issue
I've got an OpenVPN server running for ages, it suddenly stopped working from Android.
I'm connected and it works for 3rd party Apps like Twitter, but all Google Apps (Chrome, Playstore, ...) don't get any connection. Just loading for ages.

I did not change anything but the app version as autoupdate is enabled

Can anybody help?

**Comment by schwabe** [comment]
This a MTU issue. See the mssfix option

**Comment by error401de** [comment]
mssfix is set and how can it be an MTU issue if all other apps (including other non-gooogle browsers) work?

**Comment by schwabe** [comment]
From experience your symptons are MTU related. Without deep analyse of your individual problem, no one can give you a defintive answer.
