### ISSUE TITLE
RemoteExample app not working

### ISSUE THREAD

**Issue by ruchikasharma09** [schwabe/ics-openvpn#1089]
1. Android Version: 9
3. Device: Pixel
RemoteExample runs successfully on the device but on press Add new Profile it crashes and also showing No status yet. See the attached screenshots for your reference. Please let me know further steps to make RemoteExample create VPN connection.

![Screenshot_20191011-113319](https://user-images.githubusercontent.com/27682184/66650392-2098cd80-ec4e-11e9-9034-017ed308a15d.png)
![Screenshot 2019-10-11 at 2 38 21 PM](https://user-images.githubusercontent.com/27682184/66650420-327a7080-ec4e-11e9-9c5d-a6876399df3f.png)

**Comment by schwabe** [comment]
The example is not written very fault tolerant. You probably do not have OpenVPN for ANdroid itself installed.

**Comment by ruchikasharma09** [comment]
I appreciate your prompt response. Thanks, but can you please guide me on the steps to connect this app to VPN.

**Comment by schwabe** [comment]
@ruchikasharma09 The remote example app shows how to control the Android for OpenVPN app remotely. It is mainly useful for developer that want to implement this into their own apps. Is that your goal?

**Comment by JitendraNandiya** [comment]
I want to add this ics-openvpn lib in my android application. and using AWS .ovpn files for multiple countries

**Comment by JitendraNandiya** [comment]
I want to add this ics-openvpn lib in my android application.
AWS server is used and for every country I have the .ovpn file.
Can you guide me how I can use library and use .ovpn file to make connection ?

**Comment by schwabe** [comment]
@JitendraNandiya 

FAQ

Q: Why are you not answering my questions about modifying
   ics-openvpn/why do not help build my app on top of ics-openvpn? I
   thought this is open source.

A: There are many people building/wanting to build commercial VPN
   clients on top of my of my client. These client often do not even
   honour the license of my app or the license of OpenVPN. Even if
   these modified software do honour the license, I don't like doing
   unpaid work/giving advice for free to commercial software
   developers.

**Comment by JitendraNandiya** [comment]
Thanks for your reply I also mailed you on email id arne-openvpn@rfc2549.org.
Can you check it please.
Thanks
