### ISSUE TITLE
Package Rename not working

### ISSUE THREAD

**Issue by puneetbahuguna** [schwabe/ics-openvpn#1090]
Hi schwabe,

Can we rename the package name  from de.blinkt.openvpn to some other name. when I did this then it was giving me error and I am not able to import aidl files in my activities.

**Comment by schwabe** [comment]
@puneetbahuguna Do you have the source available of your project online?

**Comment by puneetbahuguna** [comment]
No. I was just trying to rename your package name. @schwabe

**Comment by schwabe** [comment]
@puneetbahuguna See the first FAQ in doc/README. YOu need to convince that you are not just another of the devs that will take my source and does a closed source app that violates the license.

**Comment by puneetbahuguna** [comment]
Yes I read that. So you mean its not possible to change the package name of your source code. This can only work with your defined package name in the manifest, i.e de.blinkt.openvpn not with other. @schwabe

**Comment by schwabe** [comment]
@puneetbahuguna it is entirely possible to change the package name but I refuse to help people that are making a profit of my app and do not even have the decency to respect its license.

**Comment by puneetbahuguna** [comment]
@schwabe : No I would like to know what about the purchase of this license. and what after paid licence. will you be changing something on your server end also. does your source code has some dependency on any server side code.

**Comment by schwabe** [comment]
I don't understand that question. I feel you don't understand the license situation or why I am not willing to help.

**Comment by puneetbahuguna** [comment]
@schwabe  Is this source code has any dependency from some server backend managed by you?

**Comment by schwabe** [comment]
@puneetbahuguna I am closing this issue now. For now I am assuming you are one of the " devs that will take my source and does a closed source app that violates the license" and I refuse to spend more time on you.

**Comment by puneetbahuguna** [comment]
@schwabe  Thats what I wanted to know what If I want to create a replica of this. Obviously I respect the licencse. That what I was asking you is it possible to create another application from this or not? and if yes then Do I need to purchase the license from you.

**Comment by puneetbahuguna** [comment]
I want to use it for my personal use. But I was just trying to import in a new project which is obviously with a different package name. I was getting the error. thats why I asked you If We can change the package name. @schwabe

**Comment by schwabe** [comment]
@puneetbahuguna since your personal project needs to be open source and it is a personal project, you probably have no problem telling me what you are trying to do and also to share the source code on github.

PS: Also it is strange to talk of a personal project as "We"

**Comment by puneetbahuguna** [comment]
@schwabe  I only have your project with me. I have not placed it online. I was just trying to make it lightweight by removing unused dependency for me ,and changing package. But when I renamed package in the manifest file then I was not able to resolve aidl dependency in the source code.

**Comment by schwabe** [comment]
@puneetbahuguna you are still evading my question what the your project is.
