### ISSUE TITLE
android car stereo

### ISSUE THREAD

**Issue by melo77** [schwabe/ics-openvpn#1093]
the openvpn apk not work corretly whith some android car stereo because missing
background integration 

when another app is opened openvpn is closed while other vpn who have the integration work correctly example Touch VPN-Free 1.7.0

 for some car stereo android multitask is missing must use Floating Apps to work around the problem

**Comment by schwabe** [comment]
I don't have an android Auto device. And there is also no emulator. So there is no way for me to develop for Android Auto. So I have to close this since I simply cannot do anything about it.

**Comment by melo77** [comment]
just need to implement the baground function like for example https://github.com/BelledonneCommunications/linphone-android so that the app appears as a service and it is not closed by another app launched

**Comment by schwabe** [comment]
@melo77 Sorry. I don't know what "launched in the background" means in this context. The app already uses background services etc. 

And even if I knew what changes would need to be made I still have no way of testing it. I am afraid someone needs to develop this and send a PR.

**Comment by melo77** [comment]
I ask to implement the function "Show above other apps" Enable 

request "Drawing over other apps"

similary request when the application is launched for the first time
https://support.mobizen.com/hc/en-us/articles/232011627--Permission-What-is-Drawing-over-other-apps-permission-pop-up-

**Comment by schwabe** [comment]
> And even if I knew what changes would need to be made I still have no way of testing it. I am afraid someone needs to develop this and send a PR.

**Comment by melo77** [comment]
publishes the first patch to start building so I can test various devices including the stereo android

**Comment by melo77** [comment]
android.permission.SYSTEM_ALERT_WINDOW 
![patch](https://user-images.githubusercontent.com/20340529/68239409-314d2100-000b-11ea-95cc-0843603b6660.jpg)

**Comment by melo77** [comment]
Anywhere.java
public void onClick(View v) {
  Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION, 
                              Uri.parse(String.format("package:%s", getPackageName())));
  startActivityForResult(intent, DRAW_OVER_OTHER_APPS);
}

@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
  if (requestCode == DRAW_OVER_OTHER_APPS) {
    if (Settings.canDrawOverlays(this)) {
      //Freely draw over other apps
    }
  }

**Comment by melo77** [comment]
need fix gradle version to buil the project
