### ISSUE TITLE
Connection with VPN Local

### ISSUE THREAD

**Issue by ShashankBale** [schwabe/ics-openvpn#1094]
Is it possible to connect to VPN Local (eg. LocalVPN/NetBare/NetGuard) along with OpenVPN Server setup.

**Comment by schwabe** [comment]
No. The VPN API allows one app at a time.

**Comment by ShashankBale** [comment]
Is it limitation of android.net.VpnService, to connect Local & Server VPN at once?

**Comment by schwabe** [comment]
That is what I just said, yes.

**Comment by ShashankBale** [comment]
Thank you. I appreciate your quick response.

**Comment by ShashankBale** [comment]
> No. The VPN API allows one app at a time.

Is it possible to setup Multi-Hop VPNs to make sure the local VPN traffic goes from one into the other VPN Server

For eg. Configuring LocalVPN project in OpenVPN.
