### ISSUE TITLE
Configuration of Local VPN inside OpenVPN

### ISSUE THREAD

**Issue by ShashankBale** [schwabe/ics-openvpn#1095]
As per Arne sir's previous statement :
> No. The VPN API allows one app at a time. _https://github.com/schwabe/ics-openvpn/issues/1094#issuecomment-547818706_

Is it possible to setup Multi-Hop VPNs to make sure the local VPN traffic goes from one into the other VPN Server.

For eg. Configuring LocalVPN source code inside OpenVPN project's.

**Comment by schwabe** [comment]
Theoretically yes but someone needs to spend a lot of time to imlement this.
