### ISSUE TITLE
Building project on windows

### ISSUE THREAD

**Issue by eddysnjack** [schwabe/ics-openvpn#1096]
firstly i want to say i read the readme.txt. i follow the build instruction. here is what i try step by step:
- i install sdk,ndk and cmake in android studio
- install and add to path the swig
- install the perl
- clone the repo
- update submodules.
- open the project with android studio
- run the main gradle.build.kts as u mentioned (it took a while and cpu is freaked out.)

but after all of this journey i still cant start the main module because there is no default activity. as i see all of the activites mentinoed in main's manifest are under the ui folder. so app doesnt start. in build there is a configuration command "sourceSets" i didnt clearly understand but as i see it something including other part of the module to main. i think after the build they should be seen by the manifest but its not working. what am i missing, what am i doing wrong? any tip and help would be appreciated, thank you.

other details :
- operating system windows 10
- android studio i am using is version 3.5
- i have all api sdks installed api 19 through 29

if this is not the right place to ask help for something like this, just let me know and i am sorry.

**Comment by schwabe** [comment]
yeah you need to build run the ui variant. Android Studio has a selector for the variant being build. The variant without ui, is well without ui.

**Comment by eddysnjack** [comment]
thank you so much. didn't knew the variants. problem solved.

**Comment by oleksandrxxxxx** [comment]
> thank you so much. didn't knew the variants. problem solved.

Hi eddysnjack!
Did you choose build configuration "main" to solve your issue? Or some one else?
![1](https://user-images.githubusercontent.com/57718107/68773701-b3a19a80-0634-11ea-9720-06084da15b85.png)

**Comment by schwabe** [comment]
variant isn't the same as configuration.

**Comment by oleksandrxxxxx** [comment]
I have the same issue but on Ubuntu OS. Built apk has not UI. I am completely new in Andriod Studio. Could you tell me what I have to do to build right apk? Thanks foreward.

**Comment by eddysnjack** [comment]
> 
> 
> > thank you so much. didn't knew the variants. problem solved.
> 
> Hi eddysnjack!
> Did you choose build configuration "main" to solve your issue? Or some one else?
> ![1](https://user-images.githubusercontent.com/57718107/68773701-b3a19a80-0634-11ea-9720-06084da15b85.png)


build variants options in android studio
![build variants options in android studio](https://user-images.githubusercontent.com/38407276/68833388-60772880-06c4-11ea-88a5-0dc837a260df.png)

**Comment by oleksandrxxxxx** [comment]
Thanks Eddy for a guide... 
I choose uiDebug build variant,  but unfortunately catch another error like described on picture below. ![1](https://user-images.githubusercontent.com/57718107/68843444-cbc6f780-06d0-11ea-82f3-88972286346e.png)
