### ISSUE TITLE
fancy gradle errors

### ISSUE THREAD

**Issue by barron9** [schwabe/ics-openvpn#1100]
I am freshly pulled a version and got lots of errors on start
![image](https://user-images.githubusercontent.com/27488285/68269464-f7ac0280-006a-11ea-965c-23e95c717fe1.png)

**Comment by schwabe** [comment]
See doc/README, you don't have swig like the error says

**Comment by barron9** [comment]
whats the "command"

**Comment by barron9** [comment]
![image](https://user-images.githubusercontent.com/27488285/68298482-83914f00-00aa-11ea-85a5-45c644ac8c25.png)

**Comment by barron9** [comment]
![image](https://user-images.githubusercontent.com/27488285/68302805-c146a580-00b3-11ea-9ffa-cc6f443e2b9d.png)
there is no play button or module ..how can i run this
