### ISSUE TITLE
Battery drain on 4G/LTE even in idle

### ISSUE THREAD

**Issue by 123unix** [schwabe/ics-openvpn#1101]
# General information
1. Android Version 9.0
2. Android Vendor/Custom ROM Samsung
3. Device s10
4. Version of the app (version number/play store version/self-built)
 0.7.7
# Description of the issue

On idle use OpenVPN for Android consumes about 1% of battery in 10 hours on Wi-Fi and about 25% on LTE in the same time period.

Network usage is very low, perhaps under 10 MB in 10 hours.

Please note, this issue is not specific to OpenVPN for Android, as OpenVPN Connect exhibits similar behavior, but in an attempt to investigate the problem I'm asking you for any clues.

The problem is observed on two different LTE networks with good coverage. And there battery drain is very similar on Wi-Fi vs. LTE when not using OpenVPN.

Also, this excessive drain is similar on both TCP & UDP connections with small and large timeout values.

Tweaking Android VPN settings, like "Always-on VPN" and "Do not allow internet access without VPN" doesn't change anything.

Could that be due to different network designs or configurations? Or some obscure device settings?

**Comment by schwabe** [comment]
See the FAQ on battery consumption.

**Comment by 123unix** [comment]
The FAQ don't seem to be covering this issue. The battery drain keeps going on TCP transport with no frequent keepalive packets. And it stops when switching to Wi-Fi.

**Comment by schwabe** [comment]
FAQ tells you that that keepalive keeps the LTE modem in active state and talks about keepalive times.

**Comment by 123unix** [comment]
OK, let me put it this way:

If running OpenVPN in TCP mode, how can it be different from any other
TCP-based application, like IMAP or a weather widget on HTTPS/443, in
regards to keeping LTE modem in active state?

Why LTE modem goes sleeping OK with all the regular networking
activities (including dose with persistent connections) and stops
doing so as soon as OpenVPN/TCP is activated?

**Comment by schwabe** [comment]
because normally openvpn configs have keepalive in it and that keeps sending packets every x seconds.
