### ISSUE TITLE
Support of SOCKS5 and connecting with NetGuard

### ISSUE THREAD

**Issue by fw190d13** [schwabe/ics-openvpn#1106]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 9
2. Android Vendor/Custom ROM: stock
3. Device: Nokia
4. Version of the app (version number/play store version/self-built): Latest from F-droid
 
# Description of the issue

Without root there is currently no way to have a decent firewall. You have to use a bypass through a VPN. NetGuard does that very well and it works as expected but there is a glitch. You can't use a proper VPN. There is only an option to add socks5 and it is limited to IP of the server only and socks5 is unscure. I have asked the developer about this situation and he told me that to overcome this there would have to be a VPN app that: "supports SOCKS5 and connecting the two apps." Would it be possible to implement something like this?

**Comment by schwabe** [comment]
See the other closed tickets about NetGuard.
