### ISSUE TITLE
Open VPN for Android as a firewall?

### ISSUE THREAD

**Issue by fw190d13** [schwabe/ics-openvpn#1107]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 9
2. Android Vendor/Custom ROM: stock
3. Device: Nokia
4. Version of the app (version number/play store version/self-built): latest F=droid
 
# Description of the issue

Would it be possible to use the app as a firewall? 

In the Android settings we can set up two options: 
-always on VPN
-block connections without VPN

In the OpenVPN for Android in the VPN settings there is an option "allowed apps". If one would switch off the option that VPN is used by all apps and hand pick the apps that should use the VPN wouldn't it work like a firewall of sorts?

**Comment by schwabe** [comment]
Duplicate. Discussed already in many other tickets.
