### ISSUE TITLE
 ROUTE: vpn_gateway undefined

### ISSUE THREAD

**Issue by zyxs2018** [schwabe/ics-openvpn#1108]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version    Android 9
2. Android Vendor/Custom ROM  API28
3. Device        xiaomi6
4. Version of the app (version number/play store version/self-built)
 self-built
# Description of the issue
when ics-openvpn receive  server config "PUSH_REPLY,ping 3,ping-restart 10,topology subnet,ifconfig 1.1.0.100 255.255.0.0,route 11.0.0.0 255.255.0.0 vpn_gateway,route 1.1.0.0 255.255.0.0 vpn_gateway",  
After connect,logs can find ,
"ROUTE: vpn_gateway undefined"
"ROUTE: failed to parse/resolve route for host/network:1.1.0.0"
"ROUTE: vpn_gateway undefined"
"ROUTE: failed to parse/resolve route for host/network:11.0.0.0"

**Comment by schwabe** [comment]
This is rather a configuration problem of OpenVPN than an issue with OpenVPN for Android.
