### ISSUE TITLE
Provide hint to set default VPN when connect on boot is enabled

### ISSUE THREAD

**Issue by nikolayhg** [schwabe/ics-openvpn#1110]
# General information
1. Android Version: 8.0.0
2. Android Vendor/Custom ROM: Sony
3. Device: Sony Xperia
4. Version of the app (version number/play store version/self-built): 0.7.8 from PlayStore
 
# Description of the issue
The automatic "connect on boot" option worked well, but since few months it stopped working, no VPN connection after booting the phone.

**Comment by schwabe** [comment]
When did this stop working?

**Comment by nikolayhg** [comment]
few months ago. Can't remember if anything specific changed. Is there any helpful information I could share?

I tried both the Play Store and F-Droid versions: uninstall, install, enable "Connect on boot", restart and after the OS is booted, the VPN connection is not established automatically. The app is marked as "active" in the Settings->Developer Options->Inactive Apps menu (Without me starting it manually)

**Comment by nikolayhg** [comment]
After reboot and manual start of the app, the Log shows twice the following message:
"App restriction version (not set) does not match expected version 1"

The "connect on boot" options is enabled (saved correctly).
I have only one VPN profile, which works well when I manually start it.

**Comment by nikolayhg** [comment]
Solution found: had to select "Default VPN" and now it works! (I didn't have a default VPN selected before, I assumed it connects to the single existing one)

Improvement suggestions:

- on the "connect on boot" option replace the info text "OpenVPN will connect to the specified VPN ..." to "Connects to the default VPN ...".
- if no default VPN is selected when enabling the "connect on boot" option, show a warning in the app UI.
- if no default VPN is selected when enabling the "connect on boot" option, show a warning in the Log.

You can close the issue if you like.
