### ISSUE TITLE
Import config file does not work in 0.7.11

### ISSUE THREAD

**Issue by uipko** [schwabe/ics-openvpn#1114]
# General information
1. Android Version: 9
2. Android Vendor/Custom ROM: OnePlus
3. Device: 6T
4. Version of the app: 0.7.11 (self build based on tag 0.7.11)
 
Import config file does not work. On import screen stays empty. When I click save the button I get the following message in import log (and toast) 'Importing the config yielded an error, cannot save it'. I could not find any related extra info in logcat.

Self build 0.7.10 did not have this issue. To find the breaking commit I'll do a binary search on commits between 0.7.10 and 0.7.11 :)

**Comment by schwabe** [comment]
This is fixed in 0.7.12

**Comment by uipko** [comment]
Works like a charm, thanks.
