### ISSUE TITLE
Import config file crash OpenVPN client 0.7.12 - Fire TV Stick 4K

### ISSUE THREAD

**Issue by yuriw** [schwabe/ics-openvpn#1118]
This is true only for the latest Amazon Fire TV Stick 4K - OS Version 6.2.6.8 (NS6268/2315)
After OpenVPN client 0.7.12 the app has Storage Permissions set to Deny
Check options in OpenVPN client - Use internal file browser, that will set Storage Permissions set to Allow

However after selecting import config file the OpenVPN client 0.7.12 app crashes.

Any suggestions ?

**Comment by schwabe** [comment]
are you able to get a logcat with the stack trace? Otherwise I might check if my firetv dongle also has the same problem.

**Comment by yuriw** [comment]
@schwabe I don't see any log entries via OpenVNP UI, will be happy to look if there is a way via `adb` shell.  Is there a way ?

**Comment by yuriw** [comment]
Tested 
OpenVPN client 0.7.11
OpenVPN client 0.7.10

Similar issues, OpenVPN client 0.7.11 same crash
OpenVPN client 0.7.10 does not crash, but config file is not loaded, e.g. after select nothing happens.

**Comment by uipko** [comment]
On the command line you can do `adb logcat` (see:
https://developer.android.com/studio/command-line/logcat for more details)

Logcat in Android studio makes filtering a lot easier (EG: app specific log
messages)

**Comment by yuriw** [comment]
@uipko thx !
Here is the log:

adb logcat | grep -i OpenVPN
12-04 13:07:46.312   606   606 W PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package de.blinkt.openvpn because it was previously installed without
12-04 13:07:46.312   606   606 W PackageManager: Unknown permission android.permission.FOREGROUND_SERVICE in package de.blinkt.openvpn
12-04 13:07:48.293   606   650 W PackageManager: Not granting permission android.permission.READ_EXTERNAL_STORAGE to package de.blinkt.openvpn because it was previously installed without
12-04 13:07:48.293   606   650 W PackageManager: Unknown permission android.permission.FOREGROUND_SERVICE in package de.blinkt.openvpn
12-05 07:37:35.390   606  1074 I ActivityManager: Start proc 2718:de.blinkt.openvpn/u0a176 for broadcast de.blinkt.openvpn/.OnBootReceiver
12-05 07:37:35.562   606   616 I ActivityManager: Start proc 2735:de.blinkt.openvpn:openvpn/u0a176 for service de.blinkt.openvpn/.core.OpenVPNStatusService
12-05 07:37:46.374   606   850 I ActivityManager: Killing 2735:de.blinkt.openvpn:openvpn/u0a176 (adj 901): empty #17
12-05 07:37:46.445   606   616 W ActivityManager: Scheduling restart of crashed service de.blinkt.openvpn/.core.OpenVPNStatusService in 1000ms
12-05 07:37:47.457   606   619 I ActivityManager: Start proc 3511:de.blinkt.openvpn:openvpn/u0a176 for service de.blinkt.openvpn/.core.OpenVPNStatusService
12-05 07:37:55.277   606   791 I ActivityManager: Killing 3511:de.blinkt.openvpn:openvpn/u0a176 (adj 901): empty #17
12-05 07:37:55.474   606   791 W ActivityManager: Scheduling restart of crashed service de.blinkt.openvpn/.core.OpenVPNStatusService in 1000ms
12-05 07:37:56.503   606   619 I ActivityManager: Start proc 4125:de.blinkt.openvpn:openvpn/u0a176 for service de.blinkt.openvpn/.core.OpenVPNStatusService
12-05 07:38:06.909   606  3150 I ActivityManager: Killing 4125:de.blinkt.openvpn:openvpn/u0a176 (adj 901): empty #17
12-05 07:38:06.964   606  3150 W ActivityManager: Scheduling restart of crashed service de.blinkt.openvpn/.core.OpenVPNStatusService in 1000ms
12-05 07:38:07.977   606   619 I ActivityManager: Start proc 4609:de.blinkt.openvpn:openvpn/u0a176 for service de.blinkt.openvpn/.core.OpenVPNStatusService

12-05 07:38:26.399   606   791 I ActivityManager: Killing 4609:de.blinkt.openvpn:openvpn/u0a176 (adj 901): empty #17
12-05 07:38:26.474   606   791 W ActivityManager: Scheduling restart of crashed service de.blinkt.openvpn/.core.OpenVPNStatusService in 1000ms
12-05 07:38:27.487   606   619 I ActivityManager: Start proc 5318:de.blinkt.openvpn:openvpn/u0a176 for service de.blinkt.openvpn/.core.OpenVPNStatusService
12-05 07:38:39.229   606  4744 I ActivityManager: START u0 {act=android.intent.action.VIEW dat=amzns://apps/android?p=de.blinkt.openvpn flg=0x10000000 cmp=com.amazon.venezia/.pdi.AppLaunchActivity (has extras)} from uid 10113 on display 0
12-05 07:38:39.236   606  5479 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LEANBACK_LAUNCHER] flg=0x10000000 pkg=de.blinkt.openvpn cmp=de.blinkt.openvpn/.activities.MainActivity (has extras)} from uid 1000 on display 0
12-05 07:38:39.286   606   852 I PackageRecency: Queuing notification(s) to package for ActivityInfo{d337e8a de.blinkt.openvpn.activities.MainActivity}
12-05 07:38:39.287   606   626 V MouseModeService: packageName=de.blinkt.openvpn activityName= mouseModeEnabled=false
12-05 07:38:39.317  1134  1134 D AlexaFocusChannelSet: Target (de.blinkt.openvpn) has not reported an active namespace
12-05 07:38:39.317  1134  1629 D AppStateReporter:ApplicationStateReporter: application payload:{"foregroundApplication":{"id":"de.blinkt.openvpn","metadata":{"categories":["OTHER"],"isVisible":true},"type":"android","version":"164"}}
12-05 07:38:39.318  1134  1134 W AlexaFocusPackageManagerParser: Package (de.blinkt.openvpn) has not declared permission (amazon.speech.permission.SEND_DATA_TO_ALEXA) for implicit focus
12-05 07:38:39.319  1134  1134 D AlexaFocusChannelSet: Target (de.blinkt.openvpn) does not support any namespaces
12-05 07:38:39.322  1134  1134 W AlexaFocusVisualChannelSet: Package (de.blinkt.openvpn) has not registered a namespace; attempting clear
12-05 07:38:39.362   606   647 D AmazonWindowMetrics: On window event - Package de.blinkt.openvpn, isDreaming false, state 1, alexaMode 0
12-05 07:38:39.457  2718  2718 I art     :   at void de.blinkt.openvpn.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:37)
12-05 07:38:39.457  2718  2718 I art     : Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.View$OnUnhandledKeyEventListener" on path: DexPathList[[zip file "/system/priv-app/MetricsApi/MetricsApi.apk", zip file "/data/app/de.blinkt.openvpn-1/base.apk"],nativeLibraryDirectories=[/data/app/de.blinkt.openvpn-1/lib/arm, /data/app/de.blinkt.openvpn-1/base.apk!/lib/armeabi-v7a, /system/priv-app/MetricsApi/MetricsApi.apk!/lib/armeabi-v7a, /system/priv-app/MetricsApi/lib/arm, /system/priv-app/MetricsApi/MetricsApi.apk!/lib/armeabi, /system/lib, /vendor/lib]]
12-05 07:38:39.457  2718  2718 I art     :   at void de.blinkt.openvpn.activities.MainActivity.onCreate(android.os.Bundle) (MainActivity.java:37)
12-05 07:38:39.909   606   626 I ActivityManager: Displayed de.blinkt.openvpn/.activities.MainActivity: +634ms
12-05 07:38:39.911   606   647 D AmazonWindowMetrics: On window event - Package de.blinkt.openvpn, isDreaming false, state 1, alexaMode 0
12-05 07:38:49.635   606  1568 I ActivityManager: START u0 {cmp=de.blinkt.openvpn/.activities.FileSelect (has extras)} from uid 10176 on display 0
12-05 07:38:49.680   606   626 V MouseModeService: packageName=de.blinkt.openvpn activityName= mouseModeEnabled=false
12-05 07:38:49.692  1134  1134 D AlexaFocusChannelSet: Target (de.blinkt.openvpn) has not reported an active namespace
12-05 07:38:49.692  1134  1629 D AppStateReporter:ApplicationStateReporter: same package as last, packageName : de.blinkt.openvpn
12-05 07:38:49.693  1134  1134 W AlexaFocusPackageManagerParser: Package (de.blinkt.openvpn) has not declared permission (amazon.speech.permission.SEND_DATA_TO_ALEXA) for implicit focus
12-05 07:38:49.693  1134  1134 D AlexaFocusChannelSet: Target (de.blinkt.openvpn) does not support any namespaces
12-05 07:38:49.693  1134  1134 W AlexaFocusVisualChannelSet: Package (de.blinkt.openvpn) has not registered a namespace; attempting clear
12-05 07:38:49.728  2718  2718 W Bundle  : 	at de.blinkt.openvpn.activities.FileSelect.onCreate(FileSelect.java:68)
12-05 07:38:49.731  2718  2718 E AndroidRuntime: Process: de.blinkt.openvpn, PID: 2718
12-05 07:38:49.731  2718  2718 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{de.blinkt.openvpn/de.blinkt.openvpn.activities.FileSelect}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.ActionBar.setNavigationMode(int)' on a null object reference
12-05 07:38:49.731  2718  2718 E AndroidRuntime: 	at de.blinkt.openvpn.activities.FileSelect.onCreate(FileSelect.java:80)
12-05 07:38:49.775   606  4744 W ActivityManager:   Force finishing activity de.blinkt.openvpn/.activities.FileSelect
12-05 07:38:49.780   606  4744 W ActivityManager:   Force finishing activity de.blinkt.openvpn/.activities.MainActivity
12-05 07:38:49.809   606   627 I PackageRecency: Intent triggered to package: ComponentInfo{com.amazon.tv.launcher/com.amazon.tv.launcher.util.AppRecencyReceiver} for Intent { act=android.intent.action.MAIN cat=[android.intent.category.LEANBACK_LAUNCHER] flg=0x10000000 pkg=de.blinkt.openvpn cmp=de.blinkt.openvpn/.activities.MainActivity (has extras) }
12-05 07:38:49.821  1307  5497 D RecentRefreshManager: Recent App Package was: de.blinkt.openvpn
12-05 07:38:49.843  4818  5499 E AmazonAppstore.VeneziaCardMaker/VeneziaCardMaker: Could not find [de.blinkt.openvpn] to push to Recent for type [APP].
12-05 07:38:49.872   606   648 W InputDispatcher: channel '8263073 de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
12-05 07:38:49.873   606   648 E InputDispatcher: channel '8263073 de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
12-05 07:38:49.873   606  1074 I WindowManager: WIN DEATH: Window{58f5165 u0 de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity EXITING}
12-05 07:38:49.874   606  4164 I ActivityManager: Process de.blinkt.openvpn (pid 2718) has died
12-05 07:38:49.876   606   616 I WindowManager: WIN DEATH: Window{8263073 u0 de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity}
12-05 07:38:49.876   606   616 W InputDispatcher: Attempted to unregister already unregistered input channel '8263073 de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity (server)'
12-05 07:38:49.880  1307  1307 I CdaBasedRecentDataContr: FTV-CDA: replacing home @@ recents @@ de.blinkt.openvpn from recent cda items
12-05 07:38:49.880  1307  1307 I CdaBasedRecentDataContr:   card ID: home @@ recents @@ de.blinkt.openvpn
12-05 07:38:49.880  1307  1307 I CdaBasedRecentDataContr:   card ID: home @@ recents @@ de.blinkt.openvpn
12-05 07:38:49.881  1307  1307 I CdaBasedRecentDataContr:   card ID: home @@ recents @@ de.blinkt.openvpn
12-05 07:38:49.881  1307  1307 I CdaBasedRecentDataContr:   card ID: home @@ recents @@ de.blinkt.openvpn
12-05 07:38:49.884   606   690 W Eve     :   top=de.blinkt.openvpn/.activities.FileSelect launching=true
12-05 07:38:49.884   606   690 W Eve     :   prev=de.blinkt.openvpn/.activities.MainActivity screen_on=true thermal=0

**Comment by schwabe** [comment]
Yeah, that is something that I need to debug.

**Comment by yuriw** [comment]
Cool if that helped :)

**Comment by yuriw** [comment]
@schwabe any luck ?  Do you need anything from me?

**Comment by schwabe** [comment]
@yuriw no time yet to look at it.

**Comment by yuriw** [comment]
any updates ?

**Comment by schwabe** [comment]
No.

**Comment by schwabe** [comment]
Can you retest on the latest beta?

**Comment by yuriw** [comment]
Sure, link ?

**Comment by schwabe** [comment]
same as 0.7.12, via playstore

**Comment by schwabe** [comment]
To clarify 0.7.13 has some fixes in this area and I want to know if they also fix your problem

**Comment by yuriw** [comment]
I will test tomorrow 

We’re you able to reproduce the issue ?

**Comment by yuriw** [comment]
@schwabe 0.7.13 seems to be working ! Thx for fixing !
Maybe unrelated issue, I could not make to start OVPN profile on boot FYI

**Comment by yuriw** [comment]
I don't know how this issue got closed

**Comment by yuriw** [comment]
Load on boot works as well.
