### ISSUE TITLE
Session hung if server ip changes

### ISSUE THREAD

**Issue by jknockaert** [schwabe/ics-openvpn#1122]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
9
2. Android Vendor/Custom ROM
Motorola
3. Device
One Action
4. Version of the app (version number/play store version/self-built)
0.7.8
 
# Description of the issue
Once the client is connected to a VPN server, the client does not check dns records of the server and hence fails to reconnect when the ip adres of the server changes (e.g. because of a split-horizon dns).
A common scenario is where the client initialy connects over wifi to the server on a local network (where the dns resolves the server name to a 10.x.x.x address), and then later tries to reconnect over mobile data (where the dns resolves to the external address of the server).

**Comment by schwabe** [comment]
Can you send a complete logs/screenshot or some way to reproduce it?
