### ISSUE TITLE
could not parse netmask of route net_gateway

### ISSUE THREAD

**Issue by mborsetti** [schwabe/ics-openvpn#1124]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: Android 10 | Chrome OS 78.0.3904.106 (Official Build) (64-bit)
2. Android Vendor/Custom ROM: Google (stock) | Google (stock)
3. Device: Pixel 4 XL (stock) | Pixelbook (stock) 
4. Version of the app (version number/play store version/self-built): Play Store version 0.7.8
 
# Description of the issue
Newly chokes (a technical term!) with "could not parse netmask of route net_gateway" error when importing an *.ovpn profile containing the following directive:
`route 8.8.8.8 255.255.255.255 net_gateway`
(8.8.8.8 is an example)

The syntax is correct, works fine in linux distribution, and it is used to work on a previous version (~ 3-6 months ago).  Am getting the same error on Android 10, Android 9 and Chrome OS

**Comment by schwabe** [comment]
Hm. Did you screw up the example? This one imports fine and then has 8.8.8.8/32 in the excluded routes.

`route 8.8.8.8 net_gateway`, which is indeed invalid, gives the error that you reported.

**Comment by mborsetti** [comment]
Hm, unfortunately not. Here's the error fresh fresh. 

![Screenshot_20191225-204331](https://user-images.githubusercontent.com/26698111/71449925-d6f15680-2757-11ea-87a9-4322b1e693dc.png)


- This config works fine on both linux and windows but gives an import error in Android
- This config with the `route x.x.x.x 255.255.255.255` net_gateway removed (commented out) imports fine into Android, but not when these are kept into the file

**Comment by schwabe** [comment]
Could you actually send me your config file as I cannot reproduce that error. Also linux/windows might stil log an error during connect but then ignore that and continue.
