### ISSUE TITLE
No content provider using intent

### ISSUE THREAD

**Issue by Lynkz83** [schwabe/ics-openvpn#1126]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 9
2. Android Vendor/Custom/ROM: Huawei Official
3. Device: Huawei Mate 10 Pro
4. Version of the app (version number/play store version/self-built) Direct Download 0.7.13
 
# Description of the issue
Created send intent task in Tasker to send import intent, using following
Action: 
de.blinkt.openvpn.IMPORT_PROFILE
Data: 
content://com.android.documents/document/primary:ovpn_udp/ovpn.profile.config.ovp
Package: de.blinkt.openvpn
Class:
de.blinkt.openvpn.activities.ConfigConverter
Target: Activity

When running the task it opens OpenVPN for Android and log says
Importing config file from source content://com.android.documents/document/primary:ovpn_udp/ovpn.profile.config.ovp
2131755274: No content provider content://com.android.documents/document/primary:ovpn_udp/ovpn.profile.config.ovp

I am relatively new to intents, so idk if it's a bug within app or my task

**Comment by schwabe** [comment]
content://com.android.documents/document/primary:ovpn_udp/ovpn.profile.config.ovp

Is that a valid content url?

**Comment by Lynkz83** [comment]
when i imported another profile i pulled the path from logcat to use to create a task
`01-02 22:47:23.587 1087 5315 I ActivityManager: START u0 {act=de.blinkt.openvpn.IMPORT_PROFILE dat=content://com.android.externalstorage.documents/document/primary:ovpn_udp/au195.nordvpn.com.udp.ovpn cmp=de.blinkt.openvpn/.activities.ConfigConverter} from uid 10254`
so as far as i know yes, i just changed the name of the profile i was importing
actual path if i was to go via adb shell would be
/storage/emulated/0/ovpn_udp/

**Comment by schwabe** [comment]
Ah. Yeah that url is probably only valid when gerated from the com.android.externalstorage.documents app. The app does not like being tricked by crafted URLs

**Comment by Lynkz83** [comment]
even if I use 
`content://storage/emulated/0/ovpn_udp/br25.nordvpn.com.udp.ovpn`
or 
`content://sdcard/ovpn_udp/br25.nordvpn.com.udp.ovpn`
it still gives me the same error above

**Comment by Lynkz83** [comment]
[https://pastebin.com/Sci5Aq9r](url) 

This is a logcat of me trying to use all 3 of the content:// settings
and this is the order
1. `content://com.android.documents/document/primary:ovpn_udp/br25.nordvpn.com.udp.vpn`
2. `content://storage/emulated/0/ovpn_udp/br25.nordvpn.com.udp.vpn`
3. `content://sdcard/ovpn_udp/br25.nordvpn.com.udp.vpn`

**Comment by schwabe** [comment]
That is all not surprising. By design these url only work for the intended use.

**Comment by Lynkz83** [comment]
as long as it's not a bug, I'll have to figure out another way of doing it, I am able to pull the fastest VPN server using nordvpn API, now I'm trying to import the profile as needed automatically so I don't need to import 5k profiles
