### ISSUE TITLE
options to bypass VPN are puzzling

### ISSUE THREAD

**Issue by jknockaert** [schwabe/ics-openvpn#1137]
# General information
1. Android Version
9.0
2. Android Vendor/Custom ROM
Motorola
3. Device
One Action
4. Version of the app (version number/play store version/self-built)
0.7.8 

# Description of the issue
There is a number of settings that affect how apps can bypass the VPN, but it is sometimes puzzling what each setting is doing and how they interact. In the connection settings window there's a section with "allowed apps", where there is a switch to "Allow apps to bypass the VPN" (added in #958). The setup is a bit ambigious: shouldn't it suffice to select one or more apps to allow them to bypass the VPN? What does the switch actualy do?

Then there's in the Android settings two options: "Enable Always ON VPN, Enable Block Connections without VPN". From a discussion on Reddit I understand that they interact in a particular way with the bypass options; it is however unclear to me how that goes.

Perhaps the FAQ (which has a section on the android "killswitch") could be including some documenentation of the bypass functionality?

**Comment by schwabe** [comment]
It does exactly what the button says. When it is enabled apps can dedide on their own that they don't want to use the VPN via special APIs.
