### ISSUE TITLE
Network error message

### ISSUE THREAD

**Issue by zkab** [schwabe/ics-openvpn#1140]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version -- version 10
2. Android Vendor/Custom ROM
3. Device -- Google Pixel 3XL
4. Version of the app (version number/play store version/self-built) -- play store OpenVPN for Android 0.7.8
# Description of the issue
I run OpenVPN for Android on my mobile against an OpenVPN server and it works OK except I very often get an network error message for a short second before I get the website I demanded. So switching between websites works OK except for the annoying message (check the attachment).
The message is in swedish but it says:

Connection was disconnected
A network change was detected
ERR_NETWORK_CHANGED

I have tested a windows vpn client against the same vpn server and then I don't get the message.
Can this message be suppressed?

![vpn-error](https://user-images.githubusercontent.com/44944365/73546134-f6595e80-443c-11ea-8588-29cb8210353a.jpg)

**Comment by schwabe** [comment]
does your vpn reconnect? Attach a full log please

**Comment by zkab** [comment]
Yes - vpn will reconnect 0.5-1 second after the messages shows up.
Here is the log file when it happens ... I have replaced my dyn-dns address with: my-dyn-adress.com and my wan address with: 5.150.xx.xx in the log file.
Unfortunately text is in Swedish but I can translate the ones you are interested in.

Regards
/raivo

[vpn-log.txt](https://github.com/schwabe/ics-openvpn/files/4142557/vpn-log.txt)

**Comment by schwabe** [comment]
Yeah, you are switching between LTE and Wifi. And the way that android reports that to apps means taht they still see the network switch and react like Chrome.

**Comment by zkab** [comment]
OK ... but I like to reopen the case again.
I found that Wi-Fi scanning was enabled in my mobile ... now it is disabled.
There is no wifi in the latest log file as before ... but I still have the error message.

[vpn-log-latest.txt](https://github.com/schwabe/ics-openvpn/files/4143958/vpn-log-latest.txt)
