### ISSUE TITLE
"dhcp-option DNS" is ignored by client. (No DNS settings actually work at all)

### ISSUE THREAD

**Issue by BlessDeix92** [schwabe/ics-openvpn#1146]
I am on LineageOS 16(Android 9/P), current OpenVPN Settings client from Play store version 0.7.8.

I have observed that my server configuration options of 'push "dhcp-option DNS 8.8.4.4"' are being ignored by the client.

This issue is very well documented here: https://www.rudism.com/solving-openvpn-dns-issues-on-android-clients/

I have captured traffic and verified Android settings from getprop as documented in the post above. I actually did all of my testing before I found the above blog post, and I'm certain we are observing the same issue.

The result in my case is that DNS traffic is not transiting the tunnel like it should be, which for me is a very serious security problem.

There are quite a few other forum posts linking to that blog above. This seems to be a well known problem, but I didn't see a open bug on the issue. Maybe I missed it.

**Comment by BlessDeix92** [comment]
I also find that the client is completely ignoring all configuration made under "IP AND DNS" DNS section. Manually setting the server here isn't being applied either. Basically no DNS setting options are being applied at all.

**Comment by schwabe** [comment]
The net.dns prop setting are deprecated for a long time now and it is not the right API to get DNS anymore. So check if the DNS is set by other methods. I.e. seeing if the DNS is really used.

Also please include a full log  because DNS is normally working.

**Comment by lulol** [comment]
Just for reference for anyone stumbling upon this problem.

I found a similar issue with cheap chinese phones, that as some Samsung are buggy and won't set properly the dns pushed or provided unless it is within the ip range of the VPN as stated in the FAQ.

Once the dns was within the ip range of the VPN it worked fine but even then using the command line form a terminal

$ getprop net.dns1

didn't return the actual dns in use.

Check https://ics-openvpn.blinkt.de/FAQ.html#samsung_broken_title

**Comment by schwabe** [comment]
This is a not a Samsung problem. The net.dns1/net.dns2 were deprecated in Android 4.4 (or around that time) and you should not use that API anymore to check DNS. It is simply not set to the VPN DNS servers in *any* modern Android

**Comment by lulol** [comment]
I didn't say that the deprecated API was a Samsung problem. ;)

Just said that not only Samsung had the pushed-dns-being-ignored issue and that the deprecated API won't show the actual values in use.

**Comment by jm33-m0** [comment]
Hi, I found the same issue on Android 11, as DNS in China is polluted nation wide, I can easily notice that no DNS settings are applied.
With a connected VPN, doing a `dig @8.8.8.8 google.com` in termux and I get poisoned record instead the correct one, which indicates that the VPN isn't even routing properly

**Comment by mortee** [comment]
I can confirm this now, Galaxy A52 Android 11, no DNS settings are effective. Even if I made sure that the local DNS is in the VPN subnet. 

Any solution for this, which doesn't require root?
