### ISSUE TITLE
Connection issue (probably a compression thing)

### ISSUE THREAD

**Issue by eddysnjack** [schwabe/ics-openvpn#1147]
# General information
1. Android Version
              Android 7.0 - API 24 - (Emulator)
              Android 6.0 - API 23 -(Samsung s5)
2. Android Vendor/Custom ROM
              Google
              Samsung/ Google ?

3. Device
               Emulator - Pixel 2
               Samsung s5
4. Version of the app (version number/play store version/self-built)
               Self Built - 0.7.13
 
# Description of the issue
Hi,
I have a server openvpn installed . For server configuration i follow the file in here: 
https://github.com/angristan/openvpn-install

When I try to connect to the server, the startup process completes, but there is no internet connection.
I did some tests and check the server logs when I connect it with OpenVPNConnect and OpenVPN for Android. With OpenVPN for Android, server logs showing some compression options. I definitely don't have those options on the client-side. IDK why this is happening. Compression seems off in profile options. Other than that, I don't know how to turn off compression. 
By the way, I am still not sure if the server needs a configuration or not. Commercial client apps(both pc and android) working fine so I'm guessing it's a client-side problem.
Where should I look to identify the problem? Do you have a suggestion?

**Server Side Logs (ICS-OPENVPN)**

> Feb  7 10:23:38 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 TLS: Initial packet from [AF_INET]X.X.X.X:51752, sid=dc9ae332 ecc44f9d
> Feb  7 10:23:41 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 VERIFY OK: depth=1, CN=cn_Kmor2ILp8qLeKEsH
> Feb  7 10:23:41 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 VERIFY OK: depth=0, CN=testUser1
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_VER=2.5_master
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_PLAT=android
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_PROTO=2
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_NCP=2
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_CIPHERS=AES-256-GCM:AES-128-GCM
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_LZ4=1
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_LZ4v2=1
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_LZO=1
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_COMP_STUB=1
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_COMP_STUBv2=1
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_TCPNL=1
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_GUI_VER=de.blinkt.openvpn_0.7.13
> Feb  7 10:23:42 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 peer info: IV_SSO=openurl,crtext
> Feb  7 10:23:43 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 256 bit EC, curve: prime256v1
> Feb  7 10:23:43 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:51752 [testUser1] Peer Connection Initiated with [AF_INET]X.X.X.X:51752
> Feb  7 10:23:43 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:51752 MULTI_sva: pool returned IPv4=10.8.0.3, IPv6=(Not enabled)
> Feb  7 10:23:43 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:51752 MULTI: Learn: 10.8.0.3 -> testUser1/X.X.X.X:51752
> Feb  7 10:23:43 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:51752 MULTI: primary virtual IP for testUser1/X.X.X.X:51752: 10.8.0.3
> Feb  7 10:23:44 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:51752 PUSH: Received control message: 'PUSH_REQUEST'
> Feb  7 10:23:44 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:51752 SENT CONTROL [testUser1]: 'PUSH_REPLY,dhcp-option DNS 1.0.0.1,dhcp-option DNS 1.1.1.1,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.3 255.255.255.0,peer-id 1,cipher AES-128-GCM' (status=1)
> Feb  7 10:23:44 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:51752 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
> Feb  7 10:23:44 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:51752 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key

**Server Side (OpenVPN CONNECT)**

 

> Feb  7 07:05:25 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 TLS: Initial packet from [AF_INET]X.X.X.X:46895, sid=2b05414f fba990d1
> 
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 VERIFY OK: depth=1, CN=cn_Kmor2ILp8qLeKEsH
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 VERIFY OK: depth=0, CN=testUser1
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 peer info: IV_GUI_VER=OC30Android
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 peer info: IV_VER=3.git::728733ae:Release
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 peer info: IV_PLAT=android
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 peer info: IV_NCP=2
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 peer info: IV_TCPNL=1
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 peer info: IV_PROTO=2
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 peer info: IV_AUTO_SESS=1
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1549', remote='link-mtu 1521'
> Feb  7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 WARNING: 'auth' is used inconsistently, local='auth [null-digest]', remote='auth SHA256'
> Feb  7 07:05:27 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-ECDSA-AES128-GCM-SHA256, 256 bit EC, curve: prime256v1
> Feb  7 07:05:27 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 [testUser1] Peer Connection Initiated with [AF_INET]X.X.X.X:46895
> Feb  7 07:05:27 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:46895 MULTI_sva: pool returned IPv4=10.8.0.3, IPv6=(Not enabled)
> Feb  7 07:05:27 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:46895 MULTI: Learn: 10.8.0.3 -> testUser1/X.X.X.X:46895
> Feb  7 07:05:27 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:46895 MULTI: primary virtual IP for testUser1/X.X.X.X:46895: 10.8.0.3
> Feb  7 07:05:27 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:46895 PUSH: Received control message: 'PUSH_REQUEST'
> Feb  7 07:05:27 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:46895 SENT CONTROL [testUser1]: 'PUSH_REPLY,dhcp-option DNS 1.0.0.1,dhcp-option DNS 1.1.1.1,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.3 255.255.255.0,peer-id 1,cipher AES-128-GCM' (status=1)
> Feb  7 07:05:27 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:46895 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
> Feb  7 07:05:27 ip-172-31-41-12 ovpn-server[893]: testUser1/X.X.X.X:46895 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key

**Open VPN Android Logs**

> 2020-02-07 09:48:12 built by C=US,O=Android,CN=Android Debug 0.7.13 running on Android Android SDK built for x86_64 (unknown), Android 7.0 (NYC) API 24, ABI x86_64, (Android/sdk_google_phone_x86_64/generic_x86_64:7.0/NYC/5464646:userdebug/dev-keys)
> 
> 2020-02-07 09:48:21 Building configuration…
> 2020-02-07 09:48:21 started Socket Thread
> 2020-02-07 09:48:21 Network Status: CONNECTED LTE to MOBILE epc.tmobile.com
> 2020-02-07 09:48:21 Debug state info: CONNECTED LTE to MOBILE epc.tmobile.com, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
> 2020-02-07 09:48:21 Debug state info: CONNECTED LTE to MOBILE epc.tmobile.com, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
> 2020-02-07 09:48:21 Unrecognized option or missing or extra parameter(s) in /data/user/0/de.blinkt.openvpn/cache/android.conf:37: block-outside-dns (2.5_master)
> 2020-02-07 09:48:21 Current Parameter Settings:
> 2020-02-07 09:48:21   config = '/data/user/0/de.blinkt.openvpn/cache/android.conf'
> 2020-02-07 09:48:21   mode = 0
> 2020-02-07 09:48:21   show_ciphers = DISABLED
> 2020-02-07 09:48:21   show_digests = DISABLED
> 2020-02-07 09:48:21   show_engines = DISABLED
> 2020-02-07 09:48:21   genkey = DISABLED
> 2020-02-07 09:48:21   genkey_filename = '[UNDEF]'
> 2020-02-07 09:48:21   key_pass_file = '[UNDEF]'
> 2020-02-07 09:48:21   show_tls_ciphers = DISABLED
> 2020-02-07 09:48:21   connect_retry_max = 0
> 2020-02-07 09:48:21 Connection profiles [0]:
> 2020-02-07 09:48:21   proto = udp
> 2020-02-07 09:48:21   local = '[UNDEF]'
> 2020-02-07 09:48:21   local_port = '[UNDEF]'
> 2020-02-07 09:48:21   remote = 'X.X.X.X'
> 2020-02-07 09:48:21   remote_port = '1194'
> 2020-02-07 09:48:21   remote_float = DISABLED
> 2020-02-07 09:48:21   bind_defined = DISABLED
> 2020-02-07 09:48:21   bind_local = DISABLED
> 2020-02-07 09:48:21   bind_ipv6_only = DISABLED
> 2020-02-07 09:48:21   connect_retry_seconds = 2
> 2020-02-07 09:48:21   connect_timeout = 120
> 2020-02-07 09:48:21   socks_proxy_server = '[UNDEF]'
> 2020-02-07 09:48:21   socks_proxy_port = '[UNDEF]'
> 2020-02-07 09:48:21   tun_mtu = 1500
> 2020-02-07 09:48:21   tun_mtu_defined = ENABLED
> 2020-02-07 09:48:21   link_mtu = 1500
> 2020-02-07 09:48:21   link_mtu_defined = DISABLED
> 2020-02-07 09:48:21   tun_mtu_extra = 0
> 2020-02-07 09:48:21   tun_mtu_extra_defined = DISABLED
> 2020-02-07 09:48:21   mtu_discover_type = -1
> 2020-02-07 09:48:21   fragment = 0
> 2020-02-07 09:48:21   mssfix = 1450
> 2020-02-07 09:48:21   explicit_exit_notification = 0
> 2020-02-07 09:48:21   tls_auth_file = '[UNDEF]'
> 2020-02-07 09:48:21   key_direction = not set
> 2020-02-07 09:48:21   tls_crypt_file = '[[INLINE]]'
> 2020-02-07 09:48:21   tls_crypt_v2_file = '[UNDEF]'
> 2020-02-07 09:48:21 Connection profiles END
> 2020-02-07 09:48:21   remote_random = DISABLED
> 2020-02-07 09:48:21   ipchange = '[UNDEF]'
> 2020-02-07 09:48:21 Waiting 0s seconds between connection attempt
> 2020-02-07 09:48:21   dev = 'tun'
> 2020-02-07 09:48:21   dev_type = '[UNDEF]'
> 2020-02-07 09:48:21   dev_node = '[UNDEF]'
> 2020-02-07 09:48:21   lladdr = '[UNDEF]'
> 2020-02-07 09:48:21   topology = 1
> 2020-02-07 09:48:21   ifconfig_local = '[UNDEF]'
> 2020-02-07 09:48:21   ifconfig_remote_netmask = '[UNDEF]'
> 2020-02-07 09:48:21   ifconfig_noexec = DISABLED
> 2020-02-07 09:48:21   ifconfig_nowarn = ENABLED
> 2020-02-07 09:48:21   ifconfig_ipv6_local = '[UNDEF]'
> 2020-02-07 09:48:21   ifconfig_ipv6_netbits = 0
> 2020-02-07 09:48:21   ifconfig_ipv6_remote = '[UNDEF]'
> 2020-02-07 09:48:21   shaper = 0
> 2020-02-07 09:48:21   mtu_test = 0
> 2020-02-07 09:48:21   mlock = DISABLED
> 2020-02-07 09:48:21   keepalive_ping = 0
> 2020-02-07 09:48:21   keepalive_timeout = 0
> 2020-02-07 09:48:21   inactivity_timeout = 0
> 2020-02-07 09:48:21   ping_send_timeout = 0
> 2020-02-07 09:48:21   ping_rec_timeout = 0
> 2020-02-07 09:48:21   ping_rec_timeout_action = 0
> 2020-02-07 09:48:21   ping_timer_remote = DISABLED
> 2020-02-07 09:48:21   remap_sigusr1 = 0
> 2020-02-07 09:48:21   persist_tun = ENABLED
> 2020-02-07 09:48:21   persist_local_ip = DISABLED
> 2020-02-07 09:48:21   persist_remote_ip = DISABLED
> 2020-02-07 09:48:21   persist_key = DISABLED
> 2020-02-07 09:48:21   passtos = DISABLED
> 2020-02-07 09:48:21   resolve_retry_seconds = 1000000000
> 2020-02-07 09:48:21   resolve_in_advance = ENABLED
> 2020-02-07 09:48:21   username = '[UNDEF]'
> 2020-02-07 09:48:21   groupname = '[UNDEF]'
> 2020-02-07 09:48:21   chroot_dir = '[UNDEF]'
> 2020-02-07 09:48:21   cd_dir = '[UNDEF]'
> 2020-02-07 09:48:21   writepid = '[UNDEF]'
> 2020-02-07 09:48:21   up_script = '[UNDEF]'
> 2020-02-07 09:48:21   down_script = '[UNDEF]'
> 2020-02-07 09:48:21   down_pre = DISABLED
> 2020-02-07 09:48:21   up_restart = DISABLED
> 2020-02-07 09:48:21   up_delay = DISABLED
> 2020-02-07 09:48:21   daemon = DISABLED
> 2020-02-07 09:48:21   inetd = 0
> 2020-02-07 09:48:21   log = DISABLED
> 2020-02-07 09:48:21   suppress_timestamps = DISABLED
> 2020-02-07 09:48:21   machine_readable_output = ENABLED
> 2020-02-07 09:48:21   nice = 0
> 2020-02-07 09:48:21   verbosity = 4
> 2020-02-07 09:48:21   mute = 0
> 2020-02-07 09:48:21   gremlin = 0
> 2020-02-07 09:48:21   status_file = '[UNDEF]'
> 2020-02-07 09:48:21   status_file_version = 1
> 2020-02-07 09:48:21   status_file_update_freq = 60
> 2020-02-07 09:48:21   occ = ENABLED
> 2020-02-07 09:48:21   rcvbuf = 0
> 2020-02-07 09:48:21   sndbuf = 0
> 2020-02-07 09:48:21   sockflags = 0
> 2020-02-07 09:48:21   fast_io = DISABLED
> 2020-02-07 09:48:21   comp.alg = 0
> 2020-02-07 09:48:21   comp.flags = 0
> 2020-02-07 09:48:21   route_script = '[UNDEF]'
> 2020-02-07 09:48:21   route_default_gateway = '[UNDEF]'
> 2020-02-07 09:48:21   route_default_metric = 0
> 2020-02-07 09:48:21   route_noexec = DISABLED
> 2020-02-07 09:48:21   route_delay = 0
> 2020-02-07 09:48:21   route_delay_window = 30
> 2020-02-07 09:48:21   route_delay_defined = DISABLED
> 2020-02-07 09:48:21   route_nopull = DISABLED
> 2020-02-07 09:48:21   route_gateway_via_dhcp = DISABLED
> 2020-02-07 09:48:21   allow_pull_fqdn = DISABLED
> 2020-02-07 09:48:21   management_addr = '/data/user/0/de.blinkt.openvpn/cache/mgmtsocket'
> 2020-02-07 09:48:21   management_port = 'unix'
> 2020-02-07 09:48:21   management_user_pass = '[UNDEF]'
> 2020-02-07 09:48:21   management_log_history_cache = 250
> 2020-02-07 09:48:21   management_echo_buffer_size = 100
> 2020-02-07 09:48:21   management_write_peer_info_file = '[UNDEF]'
> 2020-02-07 09:48:21   management_client_user = '[UNDEF]'
> 2020-02-07 09:48:21   management_client_group = '[UNDEF]'
> 2020-02-07 09:48:21   management_flags = 16678
> 2020-02-07 09:48:21   shared_secret_file = '[UNDEF]'
> 2020-02-07 09:48:21   key_direction = not set
> 2020-02-07 09:48:21   ciphername = 'AES-128-GCM'
> 2020-02-07 09:48:21   ncp_enabled = ENABLED
> 2020-02-07 09:48:21   ncp_ciphers = 'AES-256-GCM:AES-128-GCM'
> 2020-02-07 09:48:21   authname = 'SHA256'
> 2020-02-07 09:48:21   prng_hash = 'SHA1'
> 2020-02-07 09:48:21   prng_nonce_secret_len = 16
> 2020-02-07 09:48:21   keysize = 0
> 2020-02-07 09:48:21   engine = DISABLED
> 2020-02-07 09:48:21   replay = ENABLED
> 2020-02-07 09:48:21   mute_replay_warnings = DISABLED
> 2020-02-07 09:48:21   replay_window = 64
> 2020-02-07 09:48:21   replay_time = 15
> 2020-02-07 09:48:21   packet_id_file = '[UNDEF]'
> 2020-02-07 09:48:21   test_crypto = DISABLED
> 2020-02-07 09:48:21   tls_server = DISABLED
> 2020-02-07 09:48:21   tls_client = ENABLED
> 2020-02-07 09:48:21   key_method = 2
> 2020-02-07 09:48:21   ca_file = '[[INLINE]]'
> 2020-02-07 09:48:21   ca_path = '[UNDEF]'
> 2020-02-07 09:48:21   dh_file = '[UNDEF]'
> 2020-02-07 09:48:21   cert_file = '[[INLINE]]'
> 2020-02-07 09:48:21   extra_certs_file = '[UNDEF]'
> 2020-02-07 09:48:21   priv_key_file = '[[INLINE]]'
> 2020-02-07 09:48:21   pkcs12_file = '[UNDEF]'
> 2020-02-07 09:48:21   cipher_list = 'TLS-ECDHE-ECDSA-WITH-AES-128-GCM-SHA256'
> 2020-02-07 09:48:21   cipher_list_tls13 = '[UNDEF]'
> 2020-02-07 09:48:21   tls_cert_profile = '[UNDEF]'
> 2020-02-07 09:48:21   tls_verify = '[UNDEF]'
> 2020-02-07 09:48:21   tls_export_cert = '[UNDEF]'
> 2020-02-07 09:48:21   verify_x509_type = 2
> 2020-02-07 09:48:21   verify_x509_name = 'server_Cv2GWlSMMTCDLiug'
> 2020-02-07 09:48:21   crl_file = '[UNDEF]'
> 2020-02-07 09:48:21   ns_cert_type = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 65535
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_ku[i] = 0
> 2020-02-07 09:48:21   remote_cert_eku = 'TLS Web Server Authentication'
> 2020-02-07 09:48:21   ssl_flags = 192
> 2020-02-07 09:48:21   tls_timeout = 2
> 2020-02-07 09:48:21   renegotiate_bytes = -1
> 2020-02-07 09:48:21   renegotiate_packets = 0
> 2020-02-07 09:48:21   renegotiate_seconds = 3600
> 2020-02-07 09:48:21   handshake_window = 60
> 2020-02-07 09:48:21   transition_window = 3600
> 2020-02-07 09:48:21   single_session = DISABLED
> 2020-02-07 09:48:21   push_peer_info = DISABLED
> 2020-02-07 09:48:21   tls_exit = DISABLED
> 2020-02-07 09:48:21   tls_crypt_v2_metadata = '[UNDEF]'
> 2020-02-07 09:48:21   client = ENABLED
> 2020-02-07 09:48:21   pull = ENABLED
> 2020-02-07 09:48:21   auth_user_pass_file = '[UNDEF]'
> 2020-02-07 09:48:21 OpenVPN 2.5-icsopenvpn [git:icsopenvpn/v0.7.13-0-gec686d6a] x86_64 [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Feb  4 2020
> 2020-02-07 09:48:21 library versions: OpenSSL 1.1.1d  10 Sep 2019, LZO 2.10
> 2020-02-07 09:48:21 MANAGEMENT: Connected to management server at /data/user/0/de.blinkt.openvpn/cache/mgmtsocket
> 2020-02-07 09:48:21 MANAGEMENT: CMD 'version 3'
> 2020-02-07 09:48:21 MANAGEMENT: CMD 'hold release'
> 2020-02-07 09:48:21 MANAGEMENT: CMD 'proxy NONE'
> 2020-02-07 09:48:21 MANAGEMENT: CMD 'bytecount 2'
> 2020-02-07 09:48:21 MANAGEMENT: CMD 'state on'
> 2020-02-07 09:48:22 MANAGEMENT: CMD 'password [...]'
> 2020-02-07 09:48:22 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> 2020-02-07 09:48:22 Outgoing Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> 2020-02-07 09:48:22 Outgoing Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> 2020-02-07 09:48:22 Incoming Control Channel Encryption: Cipher 'AES-256-CTR' initialized with 256 bit key
> 2020-02-07 09:48:22 Incoming Control Channel Encryption: Using 256 bit message hash 'SHA256' for HMAC authentication
> 2020-02-07 09:48:22 Control Channel MTU parms [ L:1621 D:1156 EF:94 EB:0 ET:0 EL:3 ]
> 2020-02-07 09:48:22 Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
> 2020-02-07 09:48:22 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1549,tun-mtu 1500,proto UDPv4,cipher AES-128-GCM,auth [null-digest],keysize 128,key-method 2,tls-client'
> 2020-02-07 09:48:22 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1549,tun-mtu 1500,proto UDPv4,cipher AES-128-GCM,auth [null-digest],keysize 128,key-method 2,tls-server'
> 2020-02-07 09:48:22 TCP/UDP: Preserving recently used remote address: [AF_INET]X.X.X.X:1194
> 2020-02-07 09:48:22 Socket Buffers: R=[212992->212992] S=[212992->212992]
> 2020-02-07 09:48:22 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
> 2020-02-07 09:48:22 UDP link local: (not bound)
> 2020-02-07 09:48:22 UDP link remote: [AF_INET]X.X.X.X:1194
> 2020-02-07 09:48:22 MANAGEMENT: >STATE:1581061702,WAIT,,,,,,
> 2020-02-07 09:48:22 MANAGEMENT: >STATE:1581061702,AUTH,,,,,,
> 2020-02-07 09:48:22 TLS: Initial packet from [AF_INET]X.X.X.X:1194, sid=2ed4438c ebf7c1a0
> 2020-02-07 09:48:24 VERIFY OK: depth=1, CN=cn_Kmor2ILp8qLeKEsH
> 2020-02-07 09:48:24 VERIFY KU OK
> 2020-02-07 09:48:24 Validating certificate extended key usage
> 2020-02-07 09:48:24 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
> 2020-02-07 09:48:24 VERIFY EKU OK
> 2020-02-07 09:48:24 VERIFY X509NAME OK: CN=server_Cv2GWlSMMTCDLiug
> 2020-02-07 09:48:24 VERIFY OK: depth=0, CN=server_Cv2GWlSMMTCDLiug
> 2020-02-07 09:48:26 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 256 bit EC, curve: prime256v1
> 2020-02-07 09:48:26 [server_Cv2GWlSMMTCDLiug] Peer Connection Initiated with [AF_INET]X.X.X.X:1194
> 2020-02-07 09:48:27 MANAGEMENT: >STATE:1581061707,GET_CONFIG,,,,,,
> 2020-02-07 09:48:27 SENT CONTROL [server_Cv2GWlSMMTCDLiug]: 'PUSH_REQUEST' (status=1)
> 2020-02-07 09:48:28 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 1.0.0.1,dhcp-option DNS 1.1.1.1,redirect-gateway def1 bypass-dhcp,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-128-GCM'
> 2020-02-07 09:48:28 OPTIONS IMPORT: timers and/or timeouts modified
> 2020-02-07 09:48:28 OPTIONS IMPORT: --ifconfig/up options modified
> 2020-02-07 09:48:28 OPTIONS IMPORT: route options modified
> 2020-02-07 09:48:28 OPTIONS IMPORT: route-related options modified
> 2020-02-07 09:48:28 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
> 2020-02-07 09:48:28 OPTIONS IMPORT: peer-id set
> 2020-02-07 09:48:28 OPTIONS IMPORT: adjusting link_mtu to 1624
> 2020-02-07 09:48:28 OPTIONS IMPORT: data channel crypto options modified
> 2020-02-07 09:48:28 Data Channel MTU parms [ L:1552 D:1450 EF:52 EB:406 ET:0 EL:3 ]
> 2020-02-07 09:48:28 Outgoing Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
> 2020-02-07 09:48:28 Incoming Data Channel: Cipher 'AES-128-GCM' initialized with 128 bit key
> 2020-02-07 09:48:28 ROUTE_GATEWAY 127.100.103.119 IFACE=android-gw
> 2020-02-07 09:48:28 do_ifconfig, ipv4=1, ipv6=0
> 2020-02-07 09:48:28 MANAGEMENT: >STATE:1581061708,ASSIGN_IP,,10.8.0.2,,,,
> 2020-02-07 09:48:28 MANAGEMENT: CMD 'needok 'IFCONFIG' ok'
> 2020-02-07 09:48:28 MANAGEMENT: CMD 'needok 'ROUTE' ok'
> 2020-02-07 09:48:28 MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
> 2020-02-07 09:48:28 MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
> 2020-02-07 09:48:28 MANAGEMENT: CMD 'needok 'PERSIST_TUN_ACTION' OPEN_BEFORE_CLOSE'
> 2020-02-07 09:48:28 Opening tun interface:
> 2020-02-07 09:48:28 Local IPv4: 10.8.0.2/24 IPv6: (not set) MTU: 1500
> 2020-02-07 09:48:28 DNS Server: 1.0.0.1, 1.1.1.1, Domain: null
> 2020-02-07 09:48:28 Routes: 0.0.0.0/0, 10.8.0.0/24 
> 2020-02-07 09:48:28 Routes excluded:  
> 2020-02-07 09:48:28 VpnService routes installed: 0.0.0.0/0 
> 2020-02-07 09:48:28 Disallowed VPN apps: 
> 2020-02-07 09:48:28 MANAGEMENT: CMD 'needok 'OPENTUN' ok'
> 2020-02-07 09:48:28 Initialization Sequence Completed
> 2020-02-07 09:48:28 MANAGEMENT: >STATE:1581061708,CONNECTED,SUCCESS,10.8.0.2,X.X.X.X,1194,,
> 2020-02-07 09:48:28 Debug state info: CONNECTED LTE to MOBILE epc.tmobile.com, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
> 
> 
> 
>

**Comment by schwabe** [comment]
> Feb 7 07:05:26 ip-172-31-41-12 ovpn-server[893]: X.X.X.X:46895 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1549', remote='link-mtu 1521'

There something else wrong. This sounds more like tap on server or something like that.

**Comment by eddysnjack** [comment]
it's becoming off topic but any suggestions on that?
I try to add:
tun-mtu 1500
mssfix 1400

and seems like nothings changed.

**Comment by eddysnjack** [comment]
interesting detail:
After I try to connect with ICS, the profile I used is becoming unusable even by the commercial apps. somehow server locking that profile.
