### ISSUE TITLE
multicast doesn't work

### ISSUE THREAD

**Issue by 532910** [schwabe/ics-openvpn#1149]
I'm trying to get Default Print Service mDNS-discovered via vpn.

To troubleshoot this I run [mdns-scan](https://github.com/alteholz/mdns-scan) in [termux](https://termux.com/). Without openvpn (via WiFi) all works fine. With openvpn connected it discovers nothing and I see no packages with `tcpdump -i any -s0 -vv net 224.0.0.0/4` or `tcpdump -anvi any udp port 5353` on the host where vpn server is runned.

Linux host connected to vpn server successfully discovers mDNS services.

I've tried core 3 and 2.v
version 0.7.8 from F-Droid, LineageOS 16.0, Android 9, OP3t

**Comment by schwabe** [comment]
This outside of the control of the VPN unfortunately. It seems just that Android treats tun devices always as point to point devices and does not want multicast on them.

**Comment by 532910** [comment]
Do you know, is it possible to add tap support or it's android limitation?
Native vpn service (l2tp/ipsec) should be L2.

**Comment by schwabe** [comment]
See FAQ.

**Comment by schwabe** [comment]
even with emulating tap support you still will not get multicast
