### ISSUE TITLE
Waiting for network

### ISSUE THREAD

**Issue by Dissociable** [schwabe/ics-openvpn#1152]
# General information
1. Android Version: 10
2. Android Vendor/Custom ROM: Xiaomi.eu 20.1.21
3. Device: Mi 8 Pro (UD)
4. Version of the app (version number/play store version/self-built): PlayStore - 0.7.14
 
# Description of the issue:
'Downloads' app issue, in MIUI Google Play uses the MIUI 'Downloads' app to download
But the problem is that the MIUI 'Downloads' app can't detect network!
It says "Waiting for network"... used TCP or UDP configs, OpenVPN 3 Core or 2, none working.
I can say that it's the 'OpenVPN for Android' bug, because the Official OpenVPN client works!

How to reproduce:
Within MIUI, Use 'OpenVPN for Android' app to Connect to a config, then open Google Play and try to install a random app!

I have to say that it just works in any other apps and browsers.

Not checked with any other ROM rather than MIUI

**Comment by schwabe** [comment]
Issues with google play store are usually MTU/VPN related. Contact your VPN provider.

**Comment by Dissociable** [comment]
> 
> 
> Issues with google play store are usually MTU/VPN related. Contact your VPN provider.

Not that, i have tested with the same configs in OpenVPN Official client, works in there.
Also i have both Torguard and NordVPN subscriptions but none of those configs fixed the issue.

Hint: In Config Settings > Allowed Apps: Checked 'VPN is used for all apps but exclude selected' AND marked MIUI 'Downloads' app, Then it's Working! Now it can download, but just that it's not downloading over VPN connection.

**Comment by schwabe** [comment]
If it works in the Connect client, please include logs from the client client and also logs from my app wiht OpenVPN3 core and OpenVPN2. Otherwise I have no way of understanding what the issue might be.

**Comment by Dissociable** [comment]
@schwabe 

[OpenVPN Connect logs](https://paste.ee/r/8vDNN/0)

[OpenVPN for Android logs (OpenVPN 3 Core)](https://paste.ee/r/FlSkK/0)

[OpenVPN for Android logs (OpenVPN 2)](https://paste.ee/r/Wntjh/0)

**Comment by schwabe** [comment]
Does openvpn3 in my app work?

**Comment by Dissociable** [comment]
> 
> 
> Does openvpn3 in my app work?

Unfortunately not.

**Comment by schwabe** [comment]
the only difference seem the exclude local networks that is selected in my app. does that make a difference?

**Comment by Dissociable** [comment]
Tried the options in images below but still the same issue

https://imgur.com/a/rohHODX
-------- Original Message --------

**Comment by schwabe** [comment]
I don't see any other difference or have idea idea why openvpn3 in my app and connect should behave different. The openvpn3 library is basically identical in both apps.

**Comment by Dissociable** [comment]
@schwabe YOU DID IT! You fixed it!
Updated to v0.7.15 and now everything is working!
Thanks alot.
