### ISSUE TITLE
'Verb 0' .ovpn client config file forcefully change to 'Verb 4', how to prevent this?

### ISSUE THREAD

**Issue by perfectpeach** [schwabe/ics-openvpn#1158]
Hiya,

I want to disable all logs on my VPS based OpenVPN, and part of this process involves setting 'Verb 0' in .ovpn client config file. But as soon as I import any .ovpn client config file, your android application force it to 'Verb 4', how shall I disable this?
Is there any option for preventing or setting 'Verb' option to 'Verb 0' in your application please?

Is there any other settings for disabling all logs and if there is could you please help me to disable them as well or at least change your app to a new one with disabling all logs and does not changing the 'Verb' to any parameter forcefully please?

Tnx and best of luck

**Comment by perfectpeach** [comment]
Update: I checked the OpenVPN official app, even the conservative official app never change this to anything other thant whats set on client profile, while your opensource app does change this? May please fix this? Also add option for disabling all logs would be great?

Tnx and best of luck

**Comment by schwabe** [comment]
Yes, the app uses verb 4 by default so the slider in the log window works. This is by design.

**Comment by schwabe** [comment]
OpenVPN Connect/OpenVPN3 completely ignore verb btw.

**Comment by perfectpeach** [comment]
> Yes, the app uses verb 4 by default so the slider in the log window works. This is by design.

Hiya,


Is there anyway to change the 'Verb 4' to 'Verb 0' to disable all logs on client side please?

Tnx and best of luck

**Comment by perfectpeach** [comment]
> OpenVPN Connect/OpenVPN3 completely ignore verb btw.

Hiya,


I'm not sure I'm getting you currently. Do you mean if in the OpenVPN-connect-official, I set the client profile to 'Verb 0'(whether connecting to VPS based OpenVPN personal server or any commercial OpenVPN provider)  do the app change it to anything else other than 0 or what?

e.g. 1) I set the 'Verb 0'(whether connecting to VPS based OpenVPN personal server or any commercial OpenVPN provider) in client profile in OpenVPN-connect-official app, does it change it to anything other than 'verb 0' ?
2) Does it log the connection IP, etc etc, beyond whether if I set the 'verb 0' to whatever number?
3) How shall I make the 'verb 0' work in your app please?


Tnx and best of luck

**Comment by perfectpeach** [comment]
4)  I want to leave no logs while using your app, what shall I do to keep 'verb 0' as 'verb 0'?

Tnx and best of luck

**Comment by schwabe** [comment]
OpenVPN3 library does not implement --verb at all and will always log the same amount, no matter what you specify.

Setting verb 0 is not supported in my app and I do not intend to implement it either as I do not see the benefit from it.

**Comment by perfectpeach** [comment]
> OpenVPN3 library does not implement --verb at all and will always log the same amount, no matter what you specify.

Thanks. Does this mean even not OpenVPN official app nor any app based on the OpenVPN3 library would be able to maintain the user's privacy by even enabling settings like 'verb 0', etc etc? Do you think as a fellow, can I recompile the official app and make a non logging version forked from it for my personal use only please?


> Setting verb 0 is not supported in my app and I do not intend to implement it either as I do not see the benefit from it.

Privacy enthusiasts will like to keeps logs off, your app is more interesting for me than official app, but I need to maintain privacy?
If you don't like to alter your official app for privacy concerns, do you allow me to compile your app for myself and would you be able to kindly help me change the verb to 0 for myself please? Ofcourse I keep your copyright on my personal app as well. :)

**Comment by schwabe** [comment]
I am not sure how privacy plays into this. What is the attack scenarios that you are trying to protect yourself from? Basically the scenario that you are trying to fix is where an attacker has access the whole app and looking through the profiles is okay but seeing a log is not?

**Comment by perfectpeach** [comment]
>I am not sure how privacy plays into this. What is the attack scenarios that you are trying to protect yourself from? Basically the scenario that you are trying to fix is where an attacker has access the whole app and looking through the profiles is okay but seeing a log is not?

Hiya @schwabe 



I'm sorry for the late reply. As a Journalist, there is the possibility that a mobile phone seized temporarily by Feds. Thus it's preferred to logs o not exist as all. I can protect the app by app-lock/abnormal-fingerprint/pattern/,... but its not possible to prevent the logs(in *.txt/,...) to be locked. Feds can copy the whole phone in a few minutes while you are in temporary arrest and then return the phone back to you, while by this, they have the logs and they see through all the connection logs,... If you know what I mean? Do you implement this privacy feature, please?

Tnx and best of luck

**Comment by schwabe** [comment]
You can probably add verb 0 as custom option. I have not tested if that breaks the app or not. But I think there will be still some messages in the logs from the communication from the OpenVPN binary with the app itself.
