### ISSUE TITLE
Can I add authentication based IP/Port proxy to openvpn config file that I'm using with your openvpn-for-android? {Updated: 6-3-2020} #882 {Reopening Reminder}

### ISSUE THREAD

**Issue by moonprogrammer** [schwabe/ics-openvpn#1159]
Dear Sir,

This is just a reminder on my initial issue that is closed. Unfortunately, I was extremely busy and I coulden't reply faster. May please reopen the issue ' Can I add authentication based IP/Port proxy to OpenVPN config file that I'm using with your OpenVPN-for-android? {Updated: 6-3-2020} #882' then you may close this as this is just a reminder?

Thanks ;)

**Comment by schwabe** [comment]
Please do not open new tickets for that.
