### ISSUE TITLE
x509-verify dialog setting misses ok/cancel buttons

### ISSUE THREAD

**Issue by vwugd97** [schwabe/ics-openvpn#1160]
# General information
1. Android Version: 10
2. Android Vendor/Custom ROM: Oxygen OS 10.0.4.GM21BA
3. Device: OnePlus 7 Pro
4. Version of the app (version number/play store version/self-built): 0.7.15
 
# Description of the issue
My setups requires a custom rdn (i.e. "*.hostname-local.example") and the setup dialogue for that seems to be broken.

![Screenshot_20200309-001614](https://user-images.githubusercontent.com/15200842/76172967-41ccfe00-619b-11ea-8239-5cf28f992edd.jpg)

It's impossible to set a value. In older versions (0.7.5 in this case) the dialogue looked like this and works as expected:

![Screenshot_20200309-002257](https://user-images.githubusercontent.com/15200842/76173052-2a424500-619c-11ea-8f38-047dc617896d.jpg)

I also checked all the available apks from http://plai.de/android/ and I think the dialogue is broken since version 0.7.11 and above:

![Screenshot_20200309-002725](https://user-images.githubusercontent.com/15200842/76173153-07646080-619d-11ea-8a04-85b82ecdbfe9.jpg)

**Comment by schwabe** [comment]
As a workaround you can put the option in the custom options
