### ISSUE TITLE
Google Authenticator MFA support

### ISSUE THREAD

**Issue by egoretz** [schwabe/ics-openvpn#1162]
# General information
1. Android 9 pkq1.190616.010
2. MIUI 11.0.5.0
3. Xiaomi Redmi Note 8T
4. 0.7.15 Play store

# Description of the issue
We have an OpenVPN AS instance with a Google Authenticator MFA enabled. OpenVPN Connect client prompts for a one-time code during authentication process, but it has other issue, which makes it's usage impossible in our case. Openvpn client for linux prompts for a one-time code when "auth-retry interact" option is given. We tried to add it as a user-defined option in ics-openvpn, but this doesn't help. Because it's actually an MFA, user has to enter **both** LDAP password and a one-time code, so it's not possible to enter just a code into a password field. Are there any chances that support for a Google MFA will be added in future releases? Thank you in advance.

[Log File ICS OpenVPN.txt](https://github.com/schwabe/ics-openvpn/files/4325044/Log.File.ICS.OpenVPN.txt)

**Comment by schwabe** [comment]
What AS version is this?

**Comment by egoretz** [comment]
That's current v2.7.5

**Comment by schwabe** [comment]
Ah okay, [AS 2.8.0](https://openvpn.net/vpn-server-resources/release-notes/) has a altnernative 2FA mode that also works with this app.

**Comment by egoretz** [comment]
Ah, my fault. Didn't notice that AS package is pinned to v2.7.5 in apt... Everything works like a charm after upgrade to 2.8.2, thank you for a hint!
