### ISSUE TITLE
Cannot load CA certificate file [[INLINE]]

### ISSUE THREAD

**Issue by reetp** [schwabe/ics-openvpn#1165]
# General information
1. Android Version
10

2. Android Vendor/Custom ROM
Samsung stock rom

3. Device
Samsung S9 SM-G960F

4. Version of the app (version number/play store version/self-built)
Play 0.7.15

Just trying to load a openvpn config on a phone and hit this error

> Connected to management server at /data/user/0/de.blinkt.openvpn/cache/mgmtsocket
> 2020-03-18 15:23:38 MANAGEMENT: CMD 'version 3'
> 2020-03-18 15:23:38 MANAGEMENT: CMD 'hold release'
> 2020-03-18 15:23:38 MANAGEMENT: CMD 'proxy NONE'
> 2020-03-18 15:23:38 MANAGEMENT: CMD 'bytecount 2'
> 2020-03-18 15:23:38 MANAGEMENT: CMD 'state on'
> 2020-03-18 15:23:39 OpenSSL: error:0908F066:PEM routines:get_header_and_data:bad end line
> 2020-03-18 15:23:39 MGMT: Got unrecognized command>FATAL:Cannot load CA certificate file [[INLINE]] (no entries were read)
> 2020-03-18 15:23:39 MANAGEMENT: Client disconnected
> 2020-03-18 15:23:39 Cannot load CA certificate file [[INLINE]] (no entries were read)
> 2020-03-18 15:23:39 Exiting due to fatal error

I thought it might have been related to: https://github.com/schwabe/ics-openvpn/issues/51 

But I don't think so as the generated config looks right.

The opnvpn file is formatted correctly as far as I'm aware (generated on linux) as I've used the same config layout for a while and it worked on iphones.

Copied straight from the file:

```
<ca>
-----BEGIN CERTIFICATE-----
MIIEYjCCA8ugAwIBAgIJAOqjIi2jlTFbMA0GCSqGSIb3DQEBBQUAMIHVMQswCQYD
VQQGEwJVSzEOMAwGA1UECBMFRXNzZXgxGjAYBgNVBAcTEUJ1cm5oYW0tb24tQ3Jv
..............
urMMYupkdjBCmE1vv59oxixYDqW4vrH2Mpe+5kdWLA7Crqtdlt+duZaIDkYq5dj/
2i6twhwNtJtBdyKGUuZfO31k6YF06A==
-----END CERTIFICATE-----
</ca>
```
If I manually select and add the CA crt all is well

**Comment by schwabe** [comment]
Without the config in question, I cannot really debug this but in gernal there is no problem with importing config with inline certificates.
