### ISSUE TITLE
Certificate verify errror

### ISSUE THREAD

**Issue by hoang-rio** [schwabe/ics-openvpn#1167]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 9
2. Android Vendor/Custom ROM: Samsung
3. Device: Samsung Galaxy Note Fan Edition
4. Version of the app (version number/play store version/self-built): Lastest on Google Play
 
# Description of the issue
When connect with OpenVPN profile from vpnagete.net project i got this error:
`VERIFY ERROR: depth=1, error=unable to get issuer certificate: C=GB, ST=Greater Manchester, L=Salford, O=Sectigo Limited, CN=Sectigo RSA Domain Validation Secure Server CA`

OpenVPN Connect is working with this profile.
[vpngate_public-vpn-119.opengw.net_tcp_443.ovpn.txt](https://github.com/schwabe/ics-openvpn/files/4364593/vpngate_public-vpn-119.opengw.net_tcp_443.ovpn.txt)

**Comment by schwabe** [comment]
Your VPN provider screwed up the certificates, contact them.
