### ISSUE TITLE
Vpn added with AppRestrictions have wrong user authentication type

### ISSUE THREAD

**Issue by LeGalAlexis** [schwabe/ics-openvpn#1168]
# General information
1. Android 8.0
2. Huawei
3. HUAWEI P20 Lite
4. 0.7.15 from store
 
# Description of the issue
Hello, I have some issues with VPN configuration via AppRestrictions.
I use Device Owner App to push a VPN profile on OpenVPN for android.

The VPN profile used for the test is the one found in test example for AIDL in this repository, encoded to Base64 with "openssl base64 -A -in" command.

The newly created profile appears on the device, however, it's authentication type is set on "certificate" no matter what I try, even with "username/password" ovpn files.
I can't edit this profile because it has been pushed by Appestriction (which is fine) and when I click to connect the profile the application display a "No user certificate" popup.

Thank you,
Sincerely,

_test ovpn :  

```
proto tcp
dev tun
topology subnet

remote openvpn.blinkt.de 2000
verify-x509-name  openvpn.blinkt.de name

<auth-user-pass>
wronguser
wrongpassword
</auth-user-pass>

comp-lzo
<ca>
-----BEGIN CERTIFICATE-----
MIIHPTCCBSWgAwIBAgIBADANBgkqhkiG9w0BAQQFADB5MRAwDgYDVQQKEwdSb290
IENBMR4wHAYDVQQLExVodHRwOi8vd3d3LmNhY2VydC5vcmcxIjAgBgNVBAMTGUNB
IENlcnQgU2lnbmluZyBBdXRob3JpdHkxITAfBgkqhkiG9w0BCQEWEnN1cHBvcnRA
Y2FjZXJ0Lm9yZzAeFw0wMzAzMzAxMjI5NDlaFw0zMzAzMjkxMjI5NDlaMHkxEDAO
BgNVBAoTB1Jvb3QgQ0ExHjAcBgNVBAsTFWh0dHA6Ly93d3cuY2FjZXJ0Lm9yZzEi
MCAGA1UEAxMZQ0EgQ2VydCBTaWduaW5nIEF1dGhvcml0eTEhMB8GCSqGSIb3DQEJ
ARYSc3VwcG9ydEBjYWNlcnQub3JnMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
CgKCAgEAziLA4kZ97DYoB1CW8qAzQIxL8TtmPzHlawI229Z89vGIj053NgVBlfkJ
8BLPRoZzYLdufujAWGSuzbCtRRcMY/pnCujW0r8+55jE8Ez64AO7NV1sId6eINm6
zWYyN3L69wj1x81YyY7nDl7qPv4coRQKFWyGhFtkZip6qUtTefWIonvuLwphK42y
fk1WpRPs6tqSnqxEQR5YYGUFZvjARL3LlPdCfgv3ZWiYUQXw8wWRBB0bF4LsyFe7
w2t6iPGwcswlWyCR7BYCEo8y6RcYSNDHBS4CMEK4JZwFaz+qOqfrU0j36NK2B5jc
G8Y0f3/JHIJ6BVgrCFvzOKKrF11myZjXnhCLotLddJr3cQxyYN/Nb5gznZY0dj4k
epKwDpUeb+agRThHqtdB7Uq3EvbXG4OKDy7YCbZZ16oE/9KTfWgu3YtLq1i6L43q
laegw1SJpfvbi1EinbLDvhG+LJGGi5Z4rSDTii8aP8bQUWWHIbEZAWV/RRyH9XzQ
QUxPKZgh/TMfdQwEUfoZd9vUFBzugcMd9Zi3aQaRIt0AUMyBMawSB3s42mhb5ivU
fslfrejrckzzAeVLIL+aplfKkQABi6F1ITe1Yw1nPkZPcCBnzsXWWdsC4PDSy826
YreQQejdIOQpvGQpQsgi3Hia/0PsmBsJUUtaWsJx8cTLc6nloQsCAwEAAaOCAc4w
ggHKMB0GA1UdDgQWBBQWtTIb1Mfz4OaO873SsDrusjkY0TCBowYDVR0jBIGbMIGY
gBQWtTIb1Mfz4OaO873SsDrusjkY0aF9pHsweTEQMA4GA1UEChMHUm9vdCBDQTEe
MBwGA1UECxMVaHR0cDovL3d3dy5jYWNlcnQub3JnMSIwIAYDVQQDExlDQSBDZXJ0
IFNpZ25pbmcgQXV0aG9yaXR5MSEwHwYJKoZIhvcNAQkBFhJzdXBwb3J0QGNhY2Vy
dC5vcmeCAQAwDwYDVR0TAQH/BAUwAwEB/zAyBgNVHR8EKzApMCegJaAjhiFodHRw
czovL3d3dy5jYWNlcnQub3JnL3Jldm9rZS5jcmwwMAYJYIZIAYb4QgEEBCMWIWh0
dHBzOi8vd3d3LmNhY2VydC5vcmcvcmV2b2tlLmNybDA0BglghkgBhvhCAQgEJxYl
aHR0cDovL3d3dy5jYWNlcnQub3JnL2luZGV4LnBocD9pZD0xMDBWBglghkgBhvhC
AQ0ESRZHVG8gZ2V0IHlvdXIgb3duIGNlcnRpZmljYXRlIGZvciBGUkVFIGhlYWQg
b3ZlciB0byBodHRwOi8vd3d3LmNhY2VydC5vcmcwDQYJKoZIhvcNAQEEBQADggIB
ACjH7pyCArpcgBLKNQodgW+JapnM8mgPf6fhjViVPr3yBsOQWqy1YPaZQwGjiHCc
nWKdpIevZ1gNMDY75q1I08t0AoZxPuIrA2jxNGJARjtT6ij0rPtmlVOKTV39O9lg
18p5aTuxZZKmxoGCXJzN600BiqXfEVWqFcofN8CCmHBh22p8lqOOLlQ+TyGpkO/c
gr/c6EWtTZBzCDyUZbAEmXZ/4rzCahWqlwQ3JNgelE5tDlG+1sSPypZt90Pf6DBl
Jzt7u0NDY8RD97LsaMzhGY4i+5jhe1o+ATc7iwiwovOVThrLm82asduycPAtStvY
sONvRUgzEv/+PDIqVPfE94rwiCPCR/5kenHA0R6mY7AHfqQv0wGP3J8rtsYIqQ+T
SCX8Ev2fQtzzxD72V7DX3WnRBnc0CkvSyqD/HMaMyRa+xMwyN2hzXwj7UfdJUzYF
CpUCTPJ5GhD22Dp1nPMd8aINcGeGG7MW9S/lpOt5hvk9C8JzC6WZrG/8Z7jlLwum
GCSNe9FINSkYQKyTYOGWhlC0elnYjyELn8+CkcY7v2vcB5G5l1YjqrZslMZIBjzk
zk6q5PYvCdxTby78dOs6Y5nCpqyJvKeyRKANihDjbPIky/qbn3BHLt4Ui9SyIAmW
omTxJBzcoTWcFbLUvFUufQb1nA5V9FrWk9p2rSVzTMVD
-----END CERTIFICATE-----
</ca>
verb 2
```

**Comment by schwabe** [comment]
The feature has note really seen much testing and fixing these bugs might take me a while since I don't have access to the MDM solution I used back then. I will need to come up with a way to reproduce the bug without getting/setting up a new MDM solution :/

**Comment by LeGalAlexis** [comment]
I work in an MDM software-editing company (Ibelem, we are producing an MDM software called PushManager). We are able to give you access to our solution for test purposes if you are interested. This feature really interest us :) and having a configurable OpenVPN app on the store would be nice, so we are ready to help.

**Comment by schwabe** [comment]
@LeGalAlexis that sounds good. That would acclerate my testing. C

**Comment by LeGalAlexis** [comment]
Good! All I need is an email address to configure your access and send you some documentation. You can send it to alg@itsibelem.com

**Comment by romanhawk** [comment]
@schwabe 
Just in case you need to test OpenVPN for Android Managed Configurations - feel free to give this code a try - https://github.com/romanhawk/ics-openvpn-restriction-enforcer

**Comment by schwabe** [comment]
@romanhawk I tried using that one and after fixing that the profile is overwritten in `onResume()` by the default `# Test` text setting a profile just works. Maybe you had the profile text in the android string ressource and somehow ended up with esacped `<cert>` text or something like that?

**Comment by romanhawk** [comment]
@schwabe 
Side-effect from initial sample, as they were storing SharedPrefs on every change, but in my case - only on submit.
Anyway, hopefully useful for other Managed Configuration related things.

**Comment by schwabe** [comment]
Are you still seeing the problem in the newest version (master)? I could not reproduce the problem

**Comment by romanhawk** [comment]
Probably this is question to @LeGalAlexis
