### ISSUE TITLE
[Feature request] Implement SOCKS proxy authentication

### ISSUE THREAD

**Issue by MarcRdC** [schwabe/ics-openvpn#1169]
Some SOCKS proxies require authentication, which OpenVPN supports thanks to an optional parameter passed to the `--socks-proxy` option:

> `--socks-proxy server [port] [authfile]`
> Connect to remote host through a Socks5 proxy at address `server` and port `port` (default=1080). `authfile` (optional) is a file containing a username and password on 2 lines, or “stdin” to prompt from console.

@schwabe Would you consider implementing this in your app? Thanks.

**Comment by Siddiquevpn** [comment]
--socks-proxy server [port] [authfile]
Connect to remote host through a Socks5 proxy at address server and port port (default=1080). authfile (optional) is a file containing a username and password on 2 lines, or “stdin” to prompt from console.

**Comment by maximko** [comment]
I found a temporary solution to this issue: if your android is rooted you can create credentials file inside /data/data/de.blinkt.openvpn/ and specify full path to that file.

**Comment by schwabe** [comment]
I feel for now socks user/pass is a corner case. I will not implement this. PR are welcome however.

**Comment by PsychodelEKS** [comment]
Faced the same problem recently, worked for me this way (in case google brings someone here):
1. connect the phone to the PC and from the desktop place the auth file under `/data/data/de.blinkt.openvpn/files/socks_auth.txt` (file name for example) on the phone
2. add proxy options in profile settings under Advanced -> Custom Options:
`socks-proxy %PROXY_ADDR% %PROXY_PORT% /storage/emulated/0/Android/data/de.blinkt.openvpn/files/socks_auth.txt` (the filename must be the same of course) 

I also gave "Access files" permission to the app through ADB, dunno if that was needed.
