### ISSUE TITLE
Error on android 10

### ISSUE THREAD

**Issue by mahmoodshahsavari** [schwabe/ics-openvpn#1170]
General information
1. Android 10
2. Galaxy Note9 9

Hi i give this error just on android 10 in logcat :
2020-03-31 00:31:43.752 7146-7557/com.vpnfree.approid I/OpenVPN: Starting openvpn
2020-03-31 00:31:43.765 7146-7557/com.vpnfree.approid E/OpenVPN: OpenVPNThread Got java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null object reference
2020-03-31 00:31:43.816 7146-7557/com.vpnfree.approid I/OpenVPN: Exiting

and vpn not connect 
but connect in other android version

**Comment by schwabe** [comment]
> com.vpnfree.approid

That looks like a different app than mine.

**Comment by mehroz1** [comment]
> 
> 
> General information
> 
>     1. Android 10
> 
>     2. Galaxy Note9 9
> 
> 
> Hi i give this error just on android 10 in logcat :
> 2020-03-31 00:31:43.752 7146-7557/com.vpnfree.approid I/OpenVPN: Starting openvpn
> 2020-03-31 00:31:43.765 7146-7557/com.vpnfree.approid E/OpenVPN: OpenVPNThread Got java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null object reference
> 2020-03-31 00:31:43.816 7146-7557/com.vpnfree.approid I/OpenVPN: Exiting
> 
> and vpn not connect
> but connect in other android version

@mahmoodshahsavari Please refer to this 

https://github.com/schwabe/ics-openvpn/issues/1179#issuecomment-709324457

or

https://stackoverflow.com/a/64373156/7173141
