### ISSUE TITLE
Excluding ADB over TCP

### ISSUE THREAD

**Issue by kgursu** [schwabe/ics-openvpn#1171]
How to exclude ADB over TCP on my connection? Which system app should I exclude? Are there any security risks by doing this?

1. Pie
2. COSP
3. Beryllium / Xiaomi Pocophone F1
4. ver. 0.7.15

**Comment by schwabe** [comment]
adb over tcp is something very special and only required for developers. It probably uses the the IP to your other computer, so excluding that IP or Android system should work.  In generall I avoid using Adb tcp when developing the app and only use USB to avoid the trouble with that.
