### ISSUE TITLE
Build on Windows failed

### ISSUE THREAD

**Issue by thiagopelikan** [schwabe/ics-openvpn#1172]
I'm trying to build it for Android on Windows but it fails.

I followed the steps from readme.txt that says install NDK, CMAKE and SWIG but it failed after gradlew build command with output:

`
FAILED: cmd.exe /C "cd . && D:\adt\sdk\ndk\21.0.6113669\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe --target=armv7-none-linux-androideabi16 --gcc-toolchain=D:/adt/sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64 --sysroot=D: /adt/sdk/ndk/21.0.6113669/toolchains/llvm/prebuilt/windows-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -march=armv7-a -mthumb -Wformat -Werror=format-sec urity -O0 -fno-limit-debug-info -Wl,--exclude-libs,libgcc_real.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,--gc-sections CMakeFiles/nopie_openvpn.a rmeabi-v7a.dir/minivpn/minivpn.c.o -o nopie_openvpn.armeabi-v7a D:/open-vpn/ics-openvpn/main/build/intermediates/cmake/skeletonDebug/obj/armeabi-v7a/libopenvpn.so libssl.a libcrypto.a liblzo.a -latomic -lm && cmd.exe /C "cd /D D:\open-vpn\ics-op envpn\main.cxx\cmake\skeletonDebug\armeabi-v7a && D:\adt\sdk\cmake\3.6.4111459\bin\cmake.exe -E copy /nopie_openvpn.armeabi-v7a D:/open-vpn/ics-openvpn/main/src/main/cpp/build/ovpnassets"" Error copying file "/nopie_openvpn.armeabi-v7a" to "D:/open-vpn/ics-openvpn/main/src/main/cpp/build/ovpnassets".
`
ninja: build stopped: subcommand failed.

Does anyone else have this problem or know how to fix it?

Tks,
Thiago

**Comment by nguyenhieu283** [comment]
May you should call "git submodule init" and "git submodule update" before build project
