### ISSUE TITLE
OpenVPN for Android crash with User/Passwd authentication

### ISSUE THREAD

**Issue by guinhas** [schwabe/ics-openvpn#1173]
# General information
1. Android 7.1.2
2. LineageOS 14.1
3. BQ Aquaris E5 4G
4. Version 0.7.15 from the Play Store
 
# Description of the issue
I use OpenVPN for Android with certificates and user password authentication. The auth-user-pass-verify script I used, for a year, hashed the password with md5 and everything was working fine. Last night I updated the script to use sha256 and OpenVPN for Android started crashing. I still get a connection in the background, so I just reopen the app and the vpn connection is working, but the app crashes immediately after entering the password. I'm working on getting the log, as soon as I have it, I'll post it here. Thank you very much for your work!

**Comment by schwabe** [comment]
Can you add the tracelog from the app or some steps to reproduce that? Otherwise I have no idea how to reproduce this.

**Comment by guinhas** [comment]
Thank you very much for your reply. The scripts used in auth-user-pass-verify are based on [these](https://wiki.dd-wrt.com/wiki/index.php/OpenVPN#Authentication_with_username_and_password), with a few changes, including changing the hash to sha256. I attached the crash log. Anything else I can do to help? Thank you very much for your help!
[logcat.txt](https://github.com/schwabe/ics-openvpn/files/4424047/logcat.txt)

**Comment by guinhas** [comment]
I solved the problem clearing all data and cache from OpenVPN for Android and reimporting the .ovpn file. I'm really sorry I bothered you with this, the problem could be related to an app upgrade and not the updated script. Again, sorry to bother and thank you very much for your work and help.
