### ISSUE TITLE
Minor GUI labeling issue: Port instead of timeout

### ISSUE THREAD

**Issue by Phlogi** [schwabe/ics-openvpn#1176]
Version: 4.1

See screenshot, the label seems to be "Port" in both cases. Could be misleading. It's actually the timeout in seconds. 

![WhatsApp Image 2020-04-08 at 22 16 08](https://user-images.githubusercontent.com/6451003/78829485-b7202e80-79e6-11ea-941f-b0cc2ffc8adc.jpeg)

**Comment by schwabe** [comment]
Amazing that nobody noticed this before.

**Comment by Phlogi** [comment]
I take that as a compliment :D
