### ISSUE TITLE
AIDL service not connected

### ISSUE THREAD

**Issue by nguyenhieu283** [schwabe/ics-openvpn#1177]
# General information
1. Android Version: 10
3. Version app: Self-built
 
# Description of the issue
When i run remoteExample, I always meet NPE with service which bind to AIDL. This error look like:
![Screenshot from 2020-04-11 16-18-04](https://user-images.githubusercontent.com/36096637/79040065-1614bc00-7c10-11ea-9d19-9088f9a7d096.png)
How can i fix this? Thanks you!!

**Comment by schwabe** [comment]
The remoeexample has bad error catching. Ensure that you the main app installed

**Comment by nguyenhieu283** [comment]
I can't run app on the main module because it does not have launcher
Activity. What should I do now?

**Comment by schwabe** [comment]
@nguyenhieu283 You need to select ui variant instead of sekeletonvariant.

But even installing the skeleton variant should work fine as it also includes the aidl service.

**Comment by nguyenhieu283** [comment]
Thank you for your response!
