### ISSUE TITLE
Can't get the CARoot certificate from the android keystore

### ISSUE THREAD

**Issue by dzrdmwjx** [schwabe/ics-openvpn#1178]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 9
2. Android Vendor/Custom ROM: Samsung stock ROM
3. Device: Galaxy S9
4. Version of the app (version number/play store version/self-built): 0.7.8/self-built
# Description of the issue

On the configuration screen, it's mentioned that:
"The CA cert is usually returned from the Android keystore"

However, my experience has been that even if the CA root certificate is in the, android keychain, the app is still unable to get it. It throws the following error: "No CA certificate returned while reading from the Androind keystore. Authentication will probably fail." I am having to download the root certificate on to the device and either include it inline in the profile or load it through the application GUI for it to work.

**Comment by schwabe** [comment]
Well in my experience it is returned from the keychain if the keychain knows about it. 

But I don't see anything that would improve the situation here. I could change the text to say "sometimes" instead of "usually" but I am not sure if that really improves anything.

**Comment by dzrdmwjx** [comment]
Hi there, thanks for your response.

I don't think there's any need to change the language of that text, but a better documentation of the expected behavior (within the application or even under FAQ on yor website) would be very helpful. Can you please explain when is the app able to pull the CA cert from the keychain and when it's not? Specifically, what's meant by "if the keychain knows about it"? 

In my case, the "ca" section is left out of the client config but the CA's distinguished-name and key-id are available when the server presents its certificate during the handshake. A determination can then be made if the corresponding CA cert is present in the keychain under "Trusted certification authorities" or not. But the app throws this error even before a handshake is initiated - so it seems it kind of wants to know beforehand what CA cert is to be used to validate the server cert. And that's fine too, but how exactly do I reference that CA cert so that the app can pull it from the Android keychain? I did not find any standard options in the openvpn config to do that - "ca" only accepts either the path to the CA cert or the cert ifself copied inline.

Of course including the CA cert in the client-config inline or even importing it from a file works, but it requires obtaining the Root CA cert that's already present in the trust-keychain and copying it either within the client config or on to the filesystem to be manually imported later on. So I'm really interested in knowing how were you able to make the app pull the right CA cert from the android keychain.

Note: Initially I thought it's not working for me because the CA cert that I was using was manually installed by me. Starting with Android Oreo, by default, the sites that an app is connecting to are not accorded trust by a CA certificate installed by the user (unless the app explicitly allows it). But I later found out that this is not even working for the system CA Root Certificates that come by default.

**Comment by schwabe** [comment]
The app just gets a number of certificates from the OS. Sometimes the OS returns the CA and somtimes not.

**Comment by dzrdmwjx** [comment]
Well, the OS will return whatever is requested of it and my question was how exactly are you requesting the right CA certificate upfront when there's no "ca" section in the client config at all.

But I think I got my answer looking through the code. When you request the client's private key bundle from the keystore, it may have the server's CA certificate included in it (especially, if it's the same CA that issued the client certificate). When that is the case, your app has the right CA certificate to validate the server.

However, it's very much possible that the CAs that isssued the client and the server certificates are not the same. Also, it's entirely okay for the client private-key bundle to not include any CA certificate at all. It doesn't even have to be present in the system keychain. If that's the case, the app cannot verify the server certificate because even if the server's CA cert is installed in the system keychain as a trusted authority, the app only has access to the certs that are part of the private-key-bundle that it retrieved from the OS. In such cases, the user must include the server's CA certificate either inline in the config or import it from a file.

Perhaps you can add this detail somewhere, so that there's a clear documentation of when a CA certificate may or may not be retrieved from the android keychain.

Thanks for your work on this app!

**Comment by schwabe** [comment]
https://developer.android.com/reference/android/security/KeyChain#getCertificateChain(android.content.Context,%20java.lang.String) is the method to get the bundle.
