### ISSUE TITLE
Note in app/log that if lockdown is enabled bypass features do not work

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#1180]
# General information
1. 10
2. OnePlus 
3. 7 pro
4. Latest Play Store
 
# Description of the issue
Bypass VPN for local traffic doesn't work for the Experimental C++ core. I stay connected via Tasker whenever I'm on WiFi so it interferes with my ability to use things like my wifi Roku remote

**Comment by schwabe** [comment]
please attach log from the app

**Comment by ghost** [comment]
I apologize for not responding, been a crazy week and missed the notification of your request for a log. 

Here is the log in question: https://pastebin.com/GxxzaDPQ

**Comment by schwabe** [comment]
hm that looks like the app does not detect the local network at all or the optino is disabled. Is it really working with OpenVPN2? A log with OpenVPN2 to compare if yes would be good.

**Comment by d-g** [comment]
> Is it really working with OpenVPN2?

No, it does not.

When I explicitly add the right subnets¹ to ‘excluded networks’, it solves the issue, though.

---
¹ For me, namely:

	192.168.0.0/16
	169.254.0.0/16
	224.0.0.0/24

**Comment by d-g** [comment]
To clarify.  It is working only if Settings / Network & Internet / VPN / OpenVPN for Android / Block connections without VPN is not enabled.  I am not sure, whether it is an intended behaviour.  Despite certainly being inconvenient for a user, perhaps it is.

**Comment by schwabe** [comment]
Yes if you enable the global "Block connections without VPN" then android will block anything wihtout VPN. Does not matter if the app tries to not route them via VPN, Android will then block them because they don't have VPN.

**Comment by schwabe** [comment]
https://developer.android.com/reference/android/net/VpnService#isLockdownEnabled()

**Comment by Blocked** [comment]
Device admin allows bypass 'per app' even when lockdown("Block connections without VPN") is enabled

https://developer.android.com/reference/android/app/admin/DevicePolicyManager#setAlwaysOnVpnPackage(android.content.ComponentName,%20java.lang.String,%20boolean,%20java.util.Set%3Cjava.lang.String%3E)

**Comment by schwabe** [comment]
While that is true that API seems not to exposed to users configuring it via settings or the VPN app
