### ISSUE TITLE
Tethering + Excluded Networks = Destination Net Unreachable

### ISSUE THREAD

**Issue by d-g** [schwabe/ics-openvpn#1183]
LineageOS 16.0 (*droid 9), f-droid.orgʼs build of de.blinkt.openvpn ver. 0.7.15.

# Steps to reproduce:

- Setup tethering and Settings / Network & Internet / Hotspot & tethering / Allow clients to use VPNs [✓]
- Setup some VPN, that pushes a default route (`redirect-gateway def1`) and add some network (e. g. 85.143.112.0/22) to ‘excluded networks’.
- Check that traffic that originates straight on the machine, where de.blinkt.openvpn is running, is routed as expected: as per ‘excluded networks’ — directly, otherwise — via tunnel.
- Check that traffic from other hosts on LAN is routed via tunnel, when it should:

	$ traceroute 8.8.8.8
	traceroute to 8.8.8.8 (8.8.8.8), 30 hops max, 60 byte packets
	 1  _gateway (192.168.43.133)  3.558 ms  3.422 ms  3.799 ms
	 2  10.8.1.1 (10.8.1.1)  95.958 ms  96.226 ms  105.221 ms
	^C

# Actual (problematic) behaviour

However, traffic from other hosts destined to ‘excluded networks’ is not going anywhere:

	$ ping 85.143.112.112
	PING 85.143.112.112 (85.143.112.112) 56(84) bytes of data.
	From 192.168.43.133 icmp_seq=1 Destination Net Unreachable
	^C

# Expected behaviour

Traffic originating on other hosts is routed in a same way as traffic originating on the gateway.

**Comment by schwabe** [comment]
This whole behaviour is OS driven, the "Allow clients to use VPN" seem to a Linage OS feature. Cyanogenmod in the past and now LinageOS have often broken VPN support etc. But there is also nothing that can be fixed about this behaviour. This depends entirely on the Android OS.

**Comment by d-g** [comment]
Arne Schwabe <notifications@github.com> wrote:
> But there is also nothing [in de.blinkt.openvpn] that can be fixed about this behaviour. This depends entirely on the Android OS.

Alas!  However, thank you for the quick answer.

> This whole behaviour is OS driven, the "Allow clients to use VPN" seem to a Linage OS feature. Cyanogenmod in the past and now LinageOS have often broken VPN support etc.

I would actually take a liberty to generalize: Android has broken routing.

I’m absolutely frustrated, how they manage to turn the simple and powerful subsystem into something so confusing. :-/

¿Could I make all the *droid rubbish irrelevant to be able to simply say something like:

	# ip route add default via $vpn_gw
	# ip route add 85.143.112.0/22 via $novpn_gw
	# iptables -t nat -A POSTROUTING -o tun+ -j MASQUERADE
	# iptables -t nat -A POSTROUTING -o rmnet_data+ -j MASQUERADE

Please forgive me for continuing the offtopic but I believe you can give the most competent answer off the top of your head.

**Comment by schwabe** [comment]
Well android can have different VPN per user and also the per app routing needs to be supported, so this makes it a lot more complicated. But since I don't have any rooted devices, so I never looked too deeply how it is exactly implemted

**Comment by d-g** [comment]
Arne Schwabe <notifications@github.com> wrote:
> Well android can have different VPN per user and also the per app routing needs to be supported, so this makes it a lot more complicated.

Well, for a good decade itʼs possible to get an independent set of network interfaces and routing table for any given process (or random group of processes, including grouped by user) by using only Linux® primitives.  Feature is called network_namespaces(7), and it is somewhat actively used in modern GNU systems for containerization.  But never mind.

> I never looked too deeply how it is exactly implemted

Okay, sorry.
