### ISSUE TITLE
Managed Configuration on Chrome OS

### ISSUE THREAD

**Issue by necopinus** [schwabe/ics-openvpn#1184]
I know that this isn't necessarily the appropriate forum to ask this question, but I haven't been able to find a valid email address or other channel. So, feel free to redirect me if there's a place I should be posting this.

* * *

**Android Version:** Chrome OS 81 (Android 9)  
**Android Vendor:** Google  
**Device:** Dell Chromebook 7310  
**App Version:** 0.7.15

I am working with an organization that's attempting to roll out a VPN to a number of managed Chromebooks. The OpenVPN configuration is a little more complex than Chrome OS's built-in client can handle, so we've followed [Google's suggestion to install this app](https://support.google.com/chromebook/answer/1282338). I'm now trying to push out a [managed configuration](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/res/xml/app_restrictions.xml) that will automatically define this VPN.

Unfortunately, the Chrome OS console in G Suite expects managed configurations to be provided as a JSON file, and I've been unable to find good documentation for what this file should look like, and am hoping that someone in the developer community can provide a template. I've tried both a simple file (which I'm now pretty sure is wrong):

```json
{
	"vpn_configuration_list": [ {
		"uuid": "7a7b1e2c-d5b8-4be0-b365-492a9af13777",
		"name": "Friendly VPN Name",
		"ovpn": "VPN file contents"
	} ]
}
```

As well as something that's modeled after the [Play EMM API](https://developers.google.com/android/work/play/emm-api/v1/devices) (which seems in line with the [most similar example I've been able to find online](https://docs.microsoft.com/en-us/mem/intune/apps/app-configuration-managed-home-screen-app)):

```json
{
	"productId": "de.blinkt.openvpn",
	"managedProperty": [ {
		"key": "vpn_configuration_list",
		"valueBundleArray": [ {
			"managedProperty": [
				{
					"key": "uuid",
					"valueString": "7a7b1e2c-d5b8-4be0-b365-492a9af13777"
				},
				{
					"key": "name",
					"valueString": "Friendly VPN Name"
				},
				{
					"key": "ovpn",
					"valueString": "VPN file contents"
				}
			]
		} ]
	} ]
}
```

In both cases, I've tried inserting the relevant OVPN file (which we've previously tested and know works) as a string using several different styles of escaping, as well as base64-encoded. In all cases the **OpenVPN for Android** app has not picked up on the managed configuration, nor are there any errors (and barely any events to speak of) in the app log.

What is the proper format for the managed configuration JSON file for this app on Chrome OS?

**Comment by schwabe** [comment]
I could not really test this since when I had implemented my trial with the device management ran  out and I could not properly test it, so I am not sure if the configuration currently really works or not.

But I think your json fragments are at least missing the version: 1 field.

**Comment by necopinus** [comment]
Thanks for the help. As an update, the following _almost_ works:

```
{
	"version": "1",
	"vpn_configuration_list": [ {
		"uuid": some-uuid",
		"name": "Friendly VPN Name",
		"ovpn": "BASE64_ENCODED_OVPN_FILE"
	} ]
}
```

I found that it was important for `version` to be a string and the `ovpn` string to be base64-encoded; otherwise, the profile would not import. But the above automatically creates a VPN profile as expected.

However, inline certificates don't seem to get imported when pushed this way; attempting to connect to the VPN results in an error stating that "[y]ou must select a User certificate". Attempting to do so within the profile reveals that no certificates are available. I know that the problem isn't the OVPN file itself, as it's the same file we initially tested without device management (and it imports and connects just fine). So it looks like there might be something about getting a provisioned profile that is causing the inline certs not to get imported.

Happy to help test things, generate logs, etc.
