### ISSUE TITLE
Error open .ovpn

### ISSUE THREAD

**Issue by Dazmed707** [schwabe/ics-openvpn#1191]
#540 General information
 Motorol G2, Android 5.1 - Xiaomi Redmi Note 8 PRO MUI 11
0.7.15 and 0.7.16
 
# Description of the issue

I am trying to open my .ovpn configuration but I am throwing this error

![imagen](https://user-images.githubusercontent.com/35184132/81356915-f601dc80-9097-11ea-843d-87b6bfd27c59.png)

With the official application I have no problems.
https://play.google.com/store/apps/details?id=net.openvpn.openvpn

**Comment by schwabe** [comment]
Yes http-proxy needs server and port. None of which are optional
