### ISSUE TITLE
openvpn crashed on android10

### ISSUE THREAD

**Issue by promanz** [schwabe/ics-openvpn#1193]
1. android 10

**when i debug you code:**

   private void startOpenVPNThreadArgs(String[] argv) {
        LinkedList<String> argvlist = new LinkedList<>();
        Collections.addAll(argvlist, argv);
        ProcessBuilder pb = new ProcessBuilder(argvlist);
        // Hack O rama
        String lbpath = genLibraryPath(argv, pb);
        pb.environment().put("LD_LIBRARY_PATH", lbpath);
        pb.redirectErrorStream(true);
        try {
            mProcess = pb.start();

 **it crashed at "mProcess = pb.start();":**

**then i run cmd in shell:**

export LD_LIBRARY_PATH=/data/app/com.wxy.vpn2018-aX0Q_eeddREDPqGw5HF7TA==/lib/arm/
./c_pie_openvpn.armeabi-v7a  --config android.conf

**see the log:**
1589335165.215563 1 OpenVPN 2.5-icsopenvpn [git:HEAD-9fa0b9a7e1240170] android-14-armeabi-v7a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Oct 21 2017
1589335165.215579 1 library versions: OpenSSL 1.1.0f  25 May 2017, LZO 2.10
1589335165.215899 1000021 MANAGEMENT: connect to unix socket /data/user/0/com.wxy.vpn2018/cache/mgmtsocket failed: Connection refused
1589335165.215925 40 Signal received from management interface, exiting

**can you help me ?**

**Comment by promanz** [comment]
can you send. the project develop configure to me?  I use  as3.5  can't build your last version code..

**Comment by schwabe** [comment]
https://play.google.com/store/apps/details?id=com.wxy.vpn2018&hl=gsw looks like a commercial app. Is it GPL compliant? I am not sure why I should debug other peoples app for free. See also the FAQ in the README
