### ISSUE TITLE
Question about the license

### ISSUE THREAD

**Issue by ZoriN89** [schwabe/ics-openvpn#1198]
Your VPN uses GPLv2 license. As I understand it, judging by the license file, before publishing the application to the play market, I need to publish the source code for the github. At the same time, are there any additional rules? May it be necessary to add text to the application stating that the application is based on your ics-openvpn or something else?

**Comment by schwabe** [comment]
If you include the openvpn3 component it becomes AGPL3+. You also need the full licenses displayed by the app itself like the about screen in my app.
