### ISSUE TITLE
Renaming de.blinkt.openvpn package leads to UnsatisfiedLinkError

### ISSUE THREAD

**Issue by wufufufu** [schwabe/ics-openvpn#12]
Why does this happen?

02-19 17:33:02.414  29737-30640/newpackagename.openvpn D/dalvikvm﹕ Trying to load lib /data/app-lib/newpackagename.openvpn-1/libstlport_shared.so 0x42a38c08
02-19 17:33:02.434  29737-30640/newpackagename.openvpn D/dalvikvm﹕ Added shared lib /data/app-lib/newpackagename.openvpn-1/libstlport_shared.so 0x42a38c08
02-19 17:33:02.434  29737-30640/newpackagename.openvpn D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/newpackagename.openvpn-1/libstlport_shared.so 0x42a38c08, skipping init
02-19 17:33:02.434  29737-30640/newpackagename.openvpn D/dalvikvm﹕ Trying to load lib /data/app-lib/newpackagename.openvpn-1/libopvpnutil.so 0x42a38c08
02-19 17:33:02.434  29737-30640/newpackagename.openvpn D/dalvikvm﹕ Added shared lib /data/app-lib/newpackagename.openvpn-1/libopvpnutil.so 0x42a38c08
02-19 17:33:02.444  29737-30640/newpackagename.openvpn W/dalvikvm﹕ No implementation found for native Ledu/gatech/gtisc/wei/openvpn/core/NativeUtils;.jniclose:(I)V
02-19 17:33:02.444  29737-30640/newpackagename.openvpn W/dalvikvm﹕ threadid=13: thread exiting with uncaught exception (group=0x417f3da0)
02-19 17:33:02.444  29737-30640/newpackagename.openvpn E/AndroidRuntime﹕ FATAL EXCEPTION: OpenVPNManagementThread
    Process: newpackagename.openvpn, PID: 29737
    java.lang.UnsatisfiedLinkError: Native method not found: newpackagename.openvpn.core.NativeUtils.jniclose:(I)V
            at newpackagename.openvpn.core.NativeUtils.jniclose(Native Method)
            at newpackagename.openvpn.core.OpenVpnManagementThread.protectFileDescriptor(OpenVpnManagementThread.java:184)
            at newpackagename.openvpn.core.OpenVpnManagementThread.processNeedCommand(OpenVpnManagementThread.java:396)
            at newpackagename.openvpn.core.OpenVpnManagementThread.processCommand(OpenVpnManagementThread.java:236)
            at newpackagename.openvpn.core.OpenVpnManagementThread.processInput(OpenVpnManagementThread.java:207)
            at newpackagename.openvpn.core.OpenVpnManagementThread.run(OpenVpnManagementThread.java:155)
            at java.lang.Thread.run(Thread.java:841)

**Comment by schwabe** [comment]
because the package name in the jni needs to match the one in java

**Comment by wufufufu** [comment]
You mean the files in main/jni/?

**Comment by wufufufu** [comment]
Couldn't find anything resembling package name in jni/ files. Found a few things that looked like de.blinkt.openvpn and changed them but things still aren't working.

**Comment by schwabe** [comment]
Yes the files in main/jni have the package name in them. Otherwise keep the de.blinkt.openvpn class name for the NativeUtils class

**Comment by wufufufu** [comment]
In main/jni I replaced everything that looks like de_blinkt_openvpn with newpackagename_openvpn, is this correct? I couldn't find any other instances of "blinkt" in main/jni/ files

**Comment by schwabe** [comment]
Yes. That are the references you are looking for.

**Comment by wufufufu** [comment]
Yes, I did that and it's still breaking. Do I need to run build-native.sh again?

    02-20 15:54:09.858  20840-20881/newpackagename.openvpn I/OpenVPN﹕ Starting openvpn
    02-20 15:54:11.088  20840-20880/newpackagename.openvpn D/dalvikvm﹕ Trying to load lib /data/app-lib/newpackagename.openvpn-2/libstlport_shared.so 0x42a39af0
    02-20 15:54:11.098  20840-20880/newpackagename.openvpn D/dalvikvm﹕ Added shared lib /data/app-lib/newpackagename.openvpn-2/libstlport_shared.so 0x42a39af0
    02-20 15:54:11.098  20840-20880/newpackagename.openvpn D/dalvikvm﹕ No JNI_OnLoad found in /data/app-lib/newpackagename.openvpn-2/libstlport_shared.so 0x42a39af0, skipping init
    02-20 15:54:11.098  20840-20880/newpackagename.openvpn D/dalvikvm﹕ Trying to load lib /data/app-lib/newpackagename.openvpn-2/libopvpnutil.so 0x42a39af0
    02-20 15:54:11.098  20840-20880/newpackagename.openvpn D/dalvikvm﹕ Added shared lib /data/app-lib/newpackagename.openvpn-2/libopvpnutil.so 0x42a39af0
    02-20 15:54:11.098  20840-20880/newpackagename.openvpn W/dalvikvm﹕ No implementation found for native Ledu/gatech/gtisc/wei/openvpn/core/NativeUtils;.jniclose:(I)V
    02-20 15:54:11.098  20840-20880/newpackagename.openvpn W/dalvikvm﹕ threadid=11: thread exiting with uncaught exception (group=0x417f3da0)
    02-20 15:54:11.108  20840-20880/newpackagename.openvpn E/AndroidRuntime﹕ FATAL EXCEPTION: OpenVPNManagementThread
        Process: newpackagename.openvpn, PID: 20840
        java.lang.UnsatisfiedLinkError: Native method not found: newpackagename.openvpn.core.NativeUtils.jniclose:(I)V
                at newpackagename.openvpn.core.NativeUtils.jniclose(Native Method)
                at newpackagename.openvpn.core.OpenVpnManagementThread.protectFileDescriptor(OpenVpnManagementThread.java:184)
                at newpackagename.openvpn.core.OpenVpnManagementThread.processNeedCommand(OpenVpnManagementThread.java:396)
                at newpackagename.openvpn.core.OpenVpnManagementThread.processCommand(OpenVpnManagementThread.java:236)
                at newpackagename.openvpn.core.OpenVpnManagementThread.processInput(OpenVpnManagementThread.java:207)
                at newpackagename.openvpn.core.OpenVpnManagementThread.run(OpenVpnManagementThread.java:155)
                at java.lang.Thread.run(Thread.java:841)

**Comment by schwabe** [comment]
Probably yes. Anyway, I would recommend against renaming de.blinkt.openvpn.core. I would just leave these classes as they are consider them a library if you use this in a forked project. This will also make importing new versions easier.

**Comment by wufufufu** [comment]
Running build-native.sh made it work. I am renaming the package because I want to be able to install multiple packages on my phone to test and I can't do it under one package name.

**Comment by schwabe** [comment]
Yes but don't need to rename the de.blinkt.openvpn.core classes to rename the package name

**Comment by wufufufu** [comment]
Really. So what would be an easier method? Should I move everything in activities, api, fragments, view to a new package and leave core?

Are you saying core is most likely what will be updated in your repo?

**Comment by schwabe** [comment]
I not sure what your goal is but yes, leaving core as it is the idea. if you want only very minor modifications you can also change only the package name.

In my repository everything will be updated
