### ISSUE TITLE
show which ciphers supported

### ISSUE THREAD

**Issue by thecurmudgeon** [schwabe/ics-openvpn#1201]
Hello, 

Moto Stylus G Android 10, playstore

How does one see which ciphers, digests, tls are available to use ? On computer versions, one has --show-ciphers etc. but I can't figure out how to see that on here.

Are any of the ChaCha or Samba20 family suported as these are meant to be more efficient in an ARM context?

**Comment by schwabe** [comment]
There is currently no way to show these. In general my app supports what current lates OpenSSL/OpenVPN supports.

> Are any of the ChaCha or Samba20 family suported as these are meant to be more efficient in an ARM context?

They are not, almost any modern Android phone has AES hw support. You can check yourself by comparing Chacha20-Poly1305 and AES-128-GCM in the OpenSSL Speed test under General setting.
