### ISSUE TITLE
Crashing when establishing connections (libosslspeedtest.so: Bad file descriptor)

### ISSUE THREAD

**Issue by samotar** [schwabe/ics-openvpn#1205]
Hello there,

I'm not sure if this is an issue of ics-openvpn or if the cause is on my end / OS. I'd appreciate if anyone were able to give me some pointers in regards to further debug this.

# General information
1. Android Version: 10
2. Android Vendor/Custom ROM: Xiaomi / HavocOS
3. Mi 9T
4. Version 0.7.15 (F-Droid) and 0.7.16 (Play Store)
 
# Description of the issue
App crashes when doing any of the following:
1) Establishing any VPN connection
2) Opening the "About" tab
3) Opening the "FAQ" tab

In other words, I guess: Whenever trying to establish any connection anywhere in the app.

I keep seeing this error message in logcat which I'm guessing may be pointing towards the root of the problem:
`06-10 20:15:26.802 E/AndroidRuntime(22161): Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: unable to stat file for the library "/data/app/de.blinkt.openvpn-Mcl6NSoTy4RvjVhyADRUPw==/lib/arm64/libosslspeedtest.so": Bad file descriptor`
[Entire log output: logcat.txt](https://github.com/schwabe/ics-openvpn/files/4760589/logcat.txt)

I have not had any issues establishing connections (VPN or otherwise) within other apps on this device.

**Comment by schwabe** [comment]
I have to be honest, this sounds like a bug in your custom ROM more than anything else.
