### ISSUE TITLE
missing IServiceStatus

### ISSUE THREAD

**Issue by brijagstu7** [schwabe/ics-openvpn#1206]
Pardon me for a somewhat dummy question:
There is `import de.blinkt.openvpn.core.IServiceStatus;` in LaunchVPN.java, but there is no such file, so the compilation failed;

**Comment by schwabe** [comment]
The file is an autogenerated file from the AIDL interface.

**Comment by brijagstu7** [comment]
> The file is an autogenerated file from the AIDL interface.

But the file is NOT generated after the build, as a contrast, module "remoteExample" doesn't report any error after the build. is that what supposed to be?

**Comment by schwabe** [comment]
I don't understand the question. The build process takes cares of generating the java file from the aidl file.

**Comment by caferyukseloglu** [comment]
This issue persist on RN 74.4 The files not auto generated

**Comment by schwabe** [comment]
@caferyukseloglu what is RN 74.4?
