### ISSUE TITLE
Is it possible to include .ovpn config file into the apk ?

### ISSUE THREAD

**Issue by sandonet13** [schwabe/ics-openvpn#1208]
Hi schwabe, i'm using your source code for connecting almost all my classmates to private network and it's works nice, but i'm wondering if we don't need to import the config file, so i just give them the .apk to install and my profile was already there. thank you.

**Comment by schwabe** [comment]
if you want an easy way to just provide profiles to classmates, I suggest to look at the RemoteExample project in this repository. It demostrates how a second app can install profiles into this app.
