### ISSUE TITLE
OpenVpnThread Null exception with SDK 29

### ISSUE THREAD

**Issue by MubashirMurtaza** [schwabe/ics-openvpn#1209]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

**Comment by MubashirMurtaza** [comment]
when we compile with sdk 29 the openVpnThread give us null exception, may be this is because of file system is changed in sdk 29 but i found another thing that sdk 29 will not allow .so file to execute,, may be this is the reaso i m getting null exception,, please help me.

**Comment by schwabe** [comment]
This app uses SDK 29 and I cannot reproduce the bug. When you say "we" I assume that you have the problem in a fork of this app and not this app itself?
