### ISSUE TITLE
IP Address Block

### ISSUE THREAD

**Issue by john7200** [schwabe/ics-openvpn#1211]
It's not really an issue to report, but a feature request. Would you mind to implement a simple IP address block in OpenVPN? Users can use OpenVPN and block certain IP address(es) they do not want to access when using a VPN server. Since we cannot use both OpenVPN and a firewall at the same time, at least for non-rooted mobile users, perhaps we can have the IP address block feature in OpenVPN?

Thank you very much for the hard work.

**Comment by schwabe** [comment]
If this gets implemented in upstream OpenVPN sure, but I will not adding a simple firewall to my app.
