### ISSUE TITLE
Nvidia Shield Allowed apps list - unable to tick apps

### ISSUE THREAD

**Issue by nickdiacre** [schwabe/ics-openvpn#1212]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

**Comment by nickdiacre** [comment]
Android Version 8.0.2
AndroidTV/Shield
Nvidia Shield
V0.7.15

I can’t seem to check apps on the allowed apps list. I have tried reinstalling the app. Also tried building a new profile. 

Any insight appreciated.

**Comment by hakmes** [comment]
I seem to have the exact same issue. Unable to tick an allowed app with keyboard or remote. On my phone it works fine, so it seems only to register touch input.

**Comment by schwabe** [comment]
use the beta

**Comment by nickdiacre** [comment]
cool will test this evening

**Comment by hakmes** [comment]
It works! Thanks!
