### ISSUE TITLE
What does "Use system proxy" do?

### ISSUE THREAD

**Issue by neekt** [schwabe/ics-openvpn#1213]
A rather dull question rather than an issue, I apologise, but I can't find any information about what the "Use system proxy" setting does anywhere (FAQ, etc.), other than that it uses the system wide configuration for HTTP/HTTPS proxies to connect. For a non-technical user like me, that doesn't mean much.

Are there any privacy or reliability advantages/disadvantages when this is enabled?

Thanks for maintaining this great app.

**Comment by schwabe** [comment]
Well. There is not really more to say then "it uses the system wide configuration for HTTP/HTTPS proxies to connect". If your system setup does not have a proxy it does not even make a difference.
