### ISSUE TITLE
Compiling on Latest android 2020 got error 

### ISSUE THREAD

**Issue by nijasec** [schwabe/ics-openvpn#1215]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version  Android Studio 4.0
2. Android Vendor/Custom ROM target version 28
3. Device emulator
4. Version of the app (version number/play store version/self-built) latest
 
# Description of the issue

C/C++ skeletonRelease|x86_64 : CMake Error at /home/diybynijas/Downloads/ics-openvpn-latest/ics-openvpn-master/main/src/main/cpp/CMakeLists.txt:29 (include):
  include could not find load file:

    openssl/openssl.cmake
Affected Modules: main
Sir,
Above is the error on linux platform

**Comment by schwabe** [comment]
See build instructions
