### ISSUE TITLE
How can I get non GPLv2 license for my project?

### ISSUE THREAD

**Issue by rivik** [schwabe/ics-openvpn#1216]
From [LICENSE.txt](https://github.com/schwabe/ics-openvpn/blob/master/doc/LICENSE.txt):
`If you need a non GPLv2 license of the source please contact me.`

My teammate (sha-sabir) had contacted you (arne-openvpn@rfc2549.org) month ago.
Could you please answer him back, we are ready to discuss the terms.

Or may be you can update your contact information somewhere.

Best regards,
Ilya

**Comment by schwabe** [comment]
That mail went into the spam folder.
