### ISSUE TITLE
connect with PRIVATE KEY 

### ISSUE THREAD

**Issue by sedghian** [schwabe/ics-openvpn#1217]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

Android 7.0
Medion
Lifetab E10513
PlayStore v0.7.8
 
# Description of the issue

hi . i thank you for this source code .
my problem is connecting with PRIVATE KEY in openvpn .
how to use "PRIVATE KEY" instead "user / password"?

**Comment by schwabe** [comment]
Select certificates instead user/pw
