### ISSUE TITLE
Feature Request: Support remote-specific proto usage

### ISSUE THREAD

**Issue by Drumstickx** [schwabe/ics-openvpn#1219]
# General information
1. Android Version: 10.0
2. Android Vendor/Custom ROM: Xiaomi
3. Device: Xiaomi Mi A2
4. Version of the app (version number/play store version/self-built): Version 3.2.2 (Google Play Store)
 
# Description of the issue

Currently it is possible to specify that all connections to all remotes are established using a specified IP version by appending a `proto` statement to the custom options (e.g., `proto udp4` or `proto udp6` for udp). However, as far as I know, it is not possible to specify this for specific remotes via `remote [host] [port] [proto]` as outlined by the OpenVPN reference. Currently, importing a configuration with such a declaration removes the IP version (e.g., `remote [host] [port] udp4` translates to `remote [host] [port] udp`). Therefore, to my knowledge, it is currently not possible to use one remote for IPv4 and one remote for IPv6 when there exist A and AAAA DNS records for both remotes.

Are there plans to support the of remote-specific usage of proto?

**Comment by schwabe** [comment]
No. There are no plan. Removing the udp4/udp6 is by design as there mobile networks with NAT46 and udp4 will not work in those instances. if the server has both A and AAAA but only supports of them that is in my book a server misconfiguration.
