### ISSUE TITLE
openvpn 3 error has not been fix after 1 year!

### ISSUE THREAD

**Issue by miranda1313** [schwabe/ics-openvpn#1220]
these issue occure still but you closed them and don't be fix! (android 7 , 8 , 9 ,10) i have test on all device

i can not connect to any server when openvpn 3 is enable, and recive error in below links. after error i can not disconnect and should force stop the app then back to openvpn 2 to work correctly again!

https://github.com/schwabe/ics-openvpn/issues/1043
https://github.com/schwabe/ics-openvpn/issues/1045

**Comment by schwabe** [comment]
The errors in those tickets should be fixed. Please also don't open a meta ticket. Please add information about this in the current version with current logs, thanks
