### ISSUE TITLE
The forked  app ID mess the main OpenVPN appID, auto updates!

### ISSUE THREAD

**Issue by solarelf** [schwabe/ics-openvpn#1222]
When this forked version is installed, Google Playmarket does not recognize it as a separate app and so when the original main app is updated, it tends to update this version and replace it with original version. Is it possible to change app ID SO that the Playmatket does not interfere?

**Comment by schwabe** [comment]
I am not sure what you asking. This is the original version and thee play store has the same version. Auto updates is a play store feature.
