### ISSUE TITLE
How can I start a connection from my own App

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#1223]
i would like to start a connection from my own Android/Java app. Is that possible via a shortcut? 

This code starts the app, but not the connection:
`Intent launchIntent = getPackageManager().getLaunchIntentForPackage("de.blinkt.openvpn");
if (launchIntent != null) { 
startActivity(launchIntent);
}`
The following doesn't work either:
"de.blinkt.openvpn/.LaunchVPN"
"de.blinkt.openvpn.shortcutProfileUUID=xxxxxxxx-xxxx-xxxx-adef-40b58e3bxxxxx"
What's the syntax for that?
I want to be able to start and stop the connection.

**Comment by schwabe** [comment]
Look at the README.me of this project.
