### ISSUE TITLE
Sudden increase in APK size

### ISSUE THREAD

**Issue by dzolnai** [schwabe/ics-openvpn#1225]
Hi,
We have just updated our ics-openvpn version from `0.7.15` to `0.7.17a` (currently the same as master).
We've noticed an increase quite radical increase in APK size, from 23 to 53Mb. 
On your list of downloadable apks per version, I see the same change from `0.7.16` to `0.7.17`: http://plai.de/android/
It's 23Mb again for the `0.7.17a` apk, but not for us. Is there perhaps a commit missing from this repo? Or do we need to change something in the IDE?

**Comment by schwabe** [comment]
I think with *we* you mean eduvpn right? There is an issue with the static vs dynamic and I think sometimes you end up shipping all libraries for the PIE and not non-PIE binaries. If you just target Android 4.1+, you can just drop non-PIE.

**Comment by dzolnai** [comment]
Yes I meant eduvpn. 
Thanks for the suggestion, I have commented out the nopie parts from the CMakelists.txt, it seems to work. 
If there's a cleaner way to do it, let me know :)

**Comment by dzolnai** [comment]
Sorry, I'm reopening this issue, because I think that we can do better. With the nopie parts removed, we got 40Mb, so we are still far from 23Mb. I've re-read your answer, and you said:

> There is an issue with the static vs dynamic 

Is that [this](https://github.com/schwabe/ics-openvpn/commit/81f9dffbb8bdfd6238e1ac9d7de4ab6be2ed65c7#diff-a75dbe95bf3eb3e65419227082bbc453R210) change?

Did you revert this between `0.7.17` and `0.7.17a`? I'm trying to understand why the latest APK you built is 23Mb and ours isn't.

For debugging purposes, I've compared our 2 APKs:

![Screenshot 2020-08-26 at 8 18 05](https://user-images.githubusercontent.com/3629582/91267953-b52bf180-e774-11ea-8c81-45cd2f3b8bb0.png)

As you can see, all `openvpn` binaries in the `assets/` increased in size from 7kB to 10Mb.

**Comment by schwabe** [comment]
Yes that is the change. You can try to revert the change but for me it didn't work without that. Maybe it is fixed by now.
