### ISSUE TITLE
Apps behave as if on mobile data despite being connected to wifi

### ISSUE THREAD

**Issue by ssnor** [schwabe/ics-openvpn#1227]
Hello and thank you for a great app!

I accidentally submitted my last issue and it got removed before I had the chance to edit, sorry about that.

General info:
Android version 10
LineageOS 17.1
Galaxy Note9 (SM-N960F)
Version 0.7.17a from F-droid

I have an issue where when the VPN is connected, all apps behave as if the phone is on a mobile network.
This happens despite being connected to wifi, or even if mobile data is disabled.

I don't get this issue when connecting with another VPN app, so I don't think it is an issue with Lineage.

Best regards
ssnor

**Comment by schwabe** [comment]
What are the "other" app? How did you determine that they behave like on mobile network? ANd Linage has broken VPN related things a number of times, so it might fail to automatically set the underlying network type.

**Comment by ssnor** [comment]
The other app is WireGuard.

AntennaPod will give me a warning that I'm on a mobile network when trying to download something, NewPipe and Slide will use lower quality when viewing videos.

Now that I look into it this might actually be a ROM problem, WireGuard uses it's own userspace backend since the kernel lacks support for wireguard.

**Comment by ssnor** [comment]
I tried a connection with Lineages built in VPN over PPTP and I didn't have this problem.

**Comment by schwabe** [comment]
So the wireguard app you don't have the same problem?

**Comment by ssnor** [comment]
Yes.
So far I have tried three VPN connections.
OpenVPN, Wireguard and the built in PPTP, OpenVPN is the only one I have this problem with.

**Comment by omomom666** [comment]
I have the same issue with official android 10 on Nokia 2.3. Antennapod, NewPipe and Slide all see OpenVPN as a mobile connection, even when wifi is used. Syncthing sees it as a metered wifi connection. Wireguard and wifi without VPN work out just fine.
