### ISSUE TITLE
When updating targetSdkVersion 28 to 29 It's crashing

### ISSUE THREAD

**Issue by kishansinghpanwar** [schwabe/ics-openvpn#1229]
Issue on :
Device - Android 10
Target SDK Version - 29

Hello, the app was working fine when the targetSdkVersion = 28
but If i'm updating the version to **29**,
I'm getting a crash -

```
Cannot run program "/data/user/0/de.blinkt.openvpn/cache/pie_openvpn.armeabi-v7a": error=13, Permission denied|java.io.IOException: Cannot run program "/data/user/0/de.blinkt.openvpn/cache/pie_openvpn.armeabi-v7a": error=13, Permission denied
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
        at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:126)
        at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:67)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.io.IOException: error=13, Permission denied
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
        at java.lang.ProcessImpl.start(ProcessImpl.java:141)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:126) 
        at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:67) 
        at java.lang.Thread.run(Thread.java:919) 
```

**Comment by schwabe** [comment]
The app already targets API level 30.

**Comment by kishansinghpanwar** [comment]
@schwabe i have old version of the app for personal use, I'm getting this issue in old source code, do you have any suggestion or if you want me to pay for solve this, I'll do.
but i don't want to update the whole code of app with new code.
is this possible?

**Comment by schwabe** [comment]
@kishansinghpanwar if it is just for personal use, just stick with the old target API.

**Comment by kishansinghpanwar** [comment]
@schwabe Yes but still i want to update targetSDKVersion, if you can.
because i just want the solution of this issue, not even in your code.
actually I'm facing this issue with FFmpeg-Android also.

**Comment by mehroz1** [comment]
> 
> 
> Issue on :
> Device - Android 10
> Target SDK Version - 29
> 
> Hello, the app was working fine when the targetSdkVersion = 28
> but If i'm updating the version to **29**,
> I'm getting a crash -
> 
> ```
> Cannot run program "/data/user/0/de.blinkt.openvpn/cache/pie_openvpn.armeabi-v7a": error=13, Permission denied|java.io.IOException: Cannot run program "/data/user/0/de.blinkt.openvpn/cache/pie_openvpn.armeabi-v7a": error=13, Permission denied
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1050)
>         at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:126)
>         at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:67)
>         at java.lang.Thread.run(Thread.java:919)
>      Caused by: java.io.IOException: error=13, Permission denied
>         at java.lang.UNIXProcess.forkAndExec(Native Method)
>         at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
>         at java.lang.ProcessImpl.start(ProcessImpl.java:141)
>         at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
>         at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:126) 
>         at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:67) 
>         at java.lang.Thread.run(Thread.java:919) 
> ```


@kishansinghpanwar  Please refer to this 

https://github.com/schwabe/ics-openvpn/issues/1179#issuecomment-709324457

or

https://stackoverflow.com/a/64373156/7173141

I hope this will solve your problem.
