### ISSUE TITLE
App uses old file explorer on Pixel 2 XL with SDK=30

### ISSUE THREAD

**Issue by richardlawley** [schwabe/ics-openvpn#1234]
# General information
1. Android Version: 11
2. Android Vendor/Custom ROM:  Stock 
3. Device: Google Pixel 2
4. Version of the app (version number/play store version/self-built): 0.7.19 from Play Store
 
# Description of the issue
When trying to import a profile, the file browser only shows media files (jpg,png etc), doesn't list other files.  When I view the App Permissions, under File and Media it shows as "Media", and going into this section the only options are "Allow access to media only" or "Denied".

It looks like permissions may have changed in Android 11, meaning that the app has to specifically request "All Files" rather than Media only.

The issue can be worked around temporarily by renaming the profile to be imported to have a media extension, such as .jpg.

**Comment by richardlawley** [comment]
Screenshot of permissions dialog:

![Screenshot_20200920-115010.png](https://user-images.githubusercontent.com/1608083/93709620-84eb2f00-fb37-11ea-8999-709c1f9d5329.png)

**Comment by schwabe** [comment]
on newer android version the app uses the the system file picker and should need to permission at all for that.

**Comment by schwabe** [comment]
https://developer.android.com/training/data-storage see the row with 'Storage Access Framework', permission needed are None

**Comment by richardlawley** [comment]
The version I reported this with does not use the system file picker, so something's not working as intended.

![Screenshot_20200920-124224.png](https://user-images.githubusercontent.com/1608083/93710454-da770a00-fb3e-11ea-9858-66bd8ce2f5af.png)

I'm not sure if the "File Explorer" line at the top is meant to be a button, as pressing it gives a button animation but nothing happens.

**Comment by schwabe** [comment]
that dialog should only be used with old version or as workaround if it is selected under general setting but I think that options is not even shown on newer android version.

What steps did you do to get that dialog and what ROM are you running?

**Comment by richardlawley** [comment]
I'm running completely stock Android 11 on a Pixel 2. All I did was open the app, and tap the import configuration file icon from the main screen.

I don't see any option in settings to enable an old file browser - it's certainly not something I've intentionally selected. I had openvpn installed before my phone updated to android 11.

**Comment by schwabe** [comment]
@richardlawley that shouldn't happen. I will double check with my pixel 2 xl
