### ISSUE TITLE
 Update 0.7.18 fails to connect to Synology VPN Server

### ISSUE THREAD

**Issue by jogaman** [schwabe/ics-openvpn#1237]
I can't connect to my Synology VPN Server since updating the app. I get

**20:56 OPTIONS ERROR: failed to negotiate cipher with server.  Add the server's cipher ('BF-CBC') to --data-ciphers (currently 'AES-256-GCM:AES-128-GCM') if you want to connect to this server.**

Synology doesn't seem to have the option for AES-128-GCM, only AES-128-CBC (gives same result). 

1. Android Version
10 

2. Android Vendor/Custom ROM
LineageOS 17.1

3. Device
Poco F1

4. Version of the app (version number/play store version/self-built)
0.7.18

**Comment by schwabe** [comment]
See https://github.com/OpenVPN/openvpn/blob/master/doc/man-sections/cipher-negotiation.rst. BF-CBC is disabled by default now. Switching to AES-128-CBC is also fine but you also need to allow that on the client side.

**Comment by jogaman** [comment]
thanks - adding --data-ciphers AES-128-CBC under custom options did the trick!
