### ISSUE TITLE
Only certain apps are listed in allowed apps on Android 11

### ISSUE THREAD

**Issue by JackieKu** [schwabe/ics-openvpn#1238]
# General information
1. Android Version
11

2. Android Vendor/Custom ROM
Google

3. Device
Pixel 4 XL

4. Version of the app (version number/play store version/self-built)
0.7.20 (Google Play) 

# Description of the issue
After upgraded to Android 11 via OTA, only this app and system apps are listed in **ALLOWED APPS** section. I think the cause is described in [this document](https://developer.android.com/training/basics/intents/package-visibility).

**Comment by schwabe** [comment]
You seem to be right. And it seem that I need `QUERY_ALL_PACKAGES` permission. Which seem to need manual approval from the Play store team.

The category of apps that are allowed to use that permission is strange: 
Launcher apps
Accessibility apps
Browsers
Peer-to-peer (P2P) sharing apps
Device management apps
Security apps

I will add the permission and hope that I fall under "security apps" and not get banned from the play store for using a dangerous permission...
