### ISSUE TITLE
What to fill in OPENVPN App for Android Enterprise

### ISSUE THREAD

**Issue by pflummy** [schwabe/ics-openvpn#1241]
Hello,

I am not 100% sure if this is an issue. I am trying following:
Using Openvpn For Android in MDM platform using Android enterprise.
I have to fill in three fields.

=>UUID
=>NAME
=>Config

I left UUID empty.
For NAME i filled in the certificates name e.g."test" also tried "test.ovpn" but didn`t worked.
I created the config in base 64 with this code and just pasted it inside the field:

openssl base64 -A in test.ovpn > phone

The certificate is not transferred to the devices.
Am i missing something, or is it not working at the moment?
Thanks in Advance!

**Comment by schwabe** [comment]
Don't leave uuid empty, use a tool like `uuidgen` to generate one. The name is just the name of profile. All the settings are explained in the documentation strings of the file. You will e.g. also need to fill out the configVersion variable.
