### ISSUE TITLE
Vpn over wifi not considered as wifi in Android 10

### ISSUE THREAD

**Issue by changemenemo** [schwabe/ics-openvpn#1247]
Hi,

I m using the fork from here https://github.com/IngoZenz/ics-openvpn

But as indicated in this [issue](https://github.com/nextcloud/android/issues/2839) of nextcloud  it seems a fix needed in every vpn app on Android to make it detect as on wifi again.
I would have reported this on the fork but there is no issue part of his repo.

**Comment by schwabe** [comment]
@boistordu I am sure what I should do here. I don't maintain that fork and this also the first I time I hear of that fork.

**Comment by changemenemo** [comment]
No problem with that but still did you look at the issue? Every vpn client has it on Android 10 seems to from the report we have.

**Comment by schwabe** [comment]
Yes, it is already fixed (#1227)

**Comment by changemenemo** [comment]
Thanks for that :) sorry to have disturbed you

**Comment by IngoZenz** [comment]
@schwabe  Btw. you should be aware of that fork - we talked about it by mail begin of the year I think. Still I would love if such feature could make it into the origin. Possibility to use local DNS Server on non default port (e.g. 5300) when connected to VPN.
My fork is pretty dirty,  kind of a hack ...

**Comment by schwabe** [comment]
@IngoZenz Over the years a lot of people promised to actually develop something, etc but basically nobody followed through, so I am actually surprised that you did all that work. That is good news.

**Comment by IngoZenz** [comment]
Thanks for recognizing that ... ;-)
Unfortunately I am not that good in the native coding part so hacked it in into the Java part  ;-)
However I think it would belong into the native C / C++ code when working on the ip packet streams.

What I am actually doing is 
- catch the dns request ip packets and redirect them to local ip and port 5300
- catch the dns response ip packets and redirect them back to the requestor

I think it shouldn't be a big effort to bring this into the native code - but we all know how it is going often in reality :-)
