### ISSUE TITLE
Want to buy closed source paid license and also contributor license agreement link not working

### ISSUE THREAD

**Issue by m2ahmed** [schwabe/ics-openvpn#1248]
Hello, Arne!
Hope you are good.
I found your Open-VPN very good and I want a closed source license of it. Please guide me the procedure of obtaining a closed source license for this library to use it in a commercial application. I have already tried the contributor license link and its not working.

**Comment by schwabe** [comment]
This is for bug tracking and issues. For business request please contact me privately on my email address.
