### ISSUE TITLE
AEAD Decrypt error when connecting to PIA servers

### ISSUE THREAD

**Issue by dot-gov** [schwabe/ics-openvpn#1249]
# General information
1. Android 9
2. LineageOS
3. N/A
4. 0.7.21
 
# Description of the issue
When connecting to privateinternetaccess servers using aes-256-gcm ciphers, the connection succeeds (logs say "Initialization Sequence Completed"), but there's no network access and "AEAD Decrypt error: cipher final failed" shows up in the logs. Eventually the ping restart kicks in and the connection is restarted. Downgrading to 0.7.18 results in the issue described in https://github.com/schwabe/ics-openvpn/issues/1236. Changing the ciphers to aes-256-cbc also fixes the issue, but requires ncp-disable to be set, otherwise it behaves similarly to 0.7.18.

**Comment by schwabe** [comment]
There are no general problems with AES-256-GCM. As PIA heavily patches their servers, this is very likely another issue on their end. Please contact their support for this problem.

**Comment by dot-gov** [comment]
>As PIA heavily patches their servers, this is very likely another issue on their end.

I should mention that aes-gcm works fine on 0.7.17a (confirmed via downgrade), so there must be a change on this side that led to this.

**Comment by schwabe** [comment]
@dot-gov yes. The whole cipher negotiation was revamped. This *only* happens with PIA. I don't have their server source code, so debugging this is going to be very painful. This is probably some side effect of assumptions that PIA's server code is making that are now no longer holding. If this bug can reproduced with some server that I have the source code and can run myself, I can look into it but currently it is just PIA's own problem/fault.
