### ISSUE TITLE
Please make shourcut icons adaptive

### ISSUE THREAD

**Issue by 532910** [schwabe/ics-openvpn#1250]
![image](https://user-images.githubusercontent.com/14617699/96518289-44d0b680-1273-11eb-9df8-45c73705ea8b.png)

Known apps with adaptive shortcut icons:
[Element](https://github.com/vector-im/element-android), [Orgzly](https://github.com/orgzly/orgzly-android), [Calendar](https://github.com/LineageOS/android_packages_apps_Etar), [SELinuxModeChanger](https://github.com/MrBIMC/SELinuxModeChanger), SoundCloud
![image](https://user-images.githubusercontent.com/14617699/96517260-4ef1b580-1271-11eb-8723-448ca6413dc2.png)

All of these shortcuts are created the same way, via long press from the main icon and dragging it to the desktop.

**Comment by schwabe** [comment]
This would require giving each VPN each own icon, which I am not implementing.

**Comment by 532910** [comment]
Nope, it doesn't require a personal icon for each VPN. Just a common one could be used for all, but adaptive.

**Comment by schwabe** [comment]
@532910 You lost me now. Please provide more details what you are actually requesting.

**Comment by 532910** [comment]
The same as described in #866 but for shortcut icons.

Something like this, for example:
![image](https://user-images.githubusercontent.com/14617699/96573957-7f6c3a80-12d7-11eb-886e-0521dc83d43b.png)

**Comment by schwabe** [comment]
So this ticket is just a duplicate of #866

**Comment by 532910** [comment]
Nope.
1. For the most apps that have a main adaptive icon, shortcuts icons are not adaptive.
2. While there are design diffucults with #866 this issue can be easily resolved.

**Comment by schwabe** [comment]
@532910 Please do not be annoying and tell me how to run my github issue tracker. Implementing adaptive icons is one task for me, so it gets one github issue.

**Comment by 532910** [comment]
Sorry! I didn't mean to annoy you.
