### ISSUE TITLE
Unable to install from Play Store

### ISSUE THREAD

**Issue by sylikc** [schwabe/ics-openvpn#1252]
# General information
1. Android 11
2. Stock ROM
3. Google Pixel 4
4. Any recent version from Play Store (even tried Beta version)
 
# Description of the issue

Hi, I am unable to install the Google Play version.  I actually had not tried to install it on the Pixel 4 before on Android 10 so I don't know if it worked then, but it certainly did on my old Galaxy S7.  When I try to install it, it just says **Can't install OpenVPN for Android** and has a Send feedback button, etc.

I tried looking at logs and couldn't see anything glaring.  It's a bit strange, as there's no version installed and I see a Logcat output that says "Error -505 while installing de.blinkt.openvpn: INSTALL_FAILED_UPDATE_INCOMPATIBLE:" and talking about mismatched signatures.

Any ideas?

**Comment by sylikc** [comment]
Update: I tried downloading the APK directly and the INSTALL_+FAILED_UPDATE_INCOMPATIBLE still came up.  I don't have a previously installed openvpn app, as it's stock android.  Am I doing something wrong?  Is there a conflict with a pre-installed app?

**Comment by sylikc** [comment]
After digging around here, I see this is related to #1230 .  I checked a titanium backup of version 0.7.15 from the Play Store, and I see that installed.  However no future Play store versions installed, even latest 0.7.21, even though it should have been fixed.

I was able to install the F-Droid version of 0.7.21 though

any ideas?

**Comment by schwabe** [comment]
If you could install a F-Droid version, then you probably have the F-Droid version. Since App store and F-droid version are signed by different keys, you have to uninstall the other version first before installing one of the other store.

**Comment by sylikc** [comment]
I had actually uninstalled and installed the Play store version from scratch and it was having issues.  I'm on the F-Droid version now though and it seems to ok, so we'll leave it at that.
