### ISSUE TITLE
PIN request

### ISSUE THREAD

**Issue by squromiv** [schwabe/ics-openvpn#1253]
I try to connect to a server, but app fails with error.
![screen_2020 10 31 001](https://user-images.githubusercontent.com/15985877/97789868-06bd8600-1bd5-11eb-835d-b088f791a8c9.png)
I don`t see any request of PIN. In native openvpn application there is no such a problem.

**Comment by schwabe** [comment]
This app already implements the more modern auth pending crtext method. I am not really interested in also implementing the old one.

**Comment by squromiv** [comment]
Ok. I use Pritunl openvpn-server and don`t see any option, connected with "crtext method" for a current user. I tried to search for this topic, but found nothing specific about it.
![screen_2020 11 01 001](https://user-images.githubusercontent.com/15985877/97910968-9b51f080-1d5b-11eb-8d14-7ea2a3d43524.png)
Can you describe, how to get an option similar to "PIN input" on server and client sides, in order to keep the same seсurity level?

**Comment by schwabe** [comment]
@squromiv they probably have not implemented crtext yet. Ask their support.
