### ISSUE TITLE
LEVEL_NONETWORK sometimes gets published when OpenVPNService starts

### ISSUE THREAD

**Issue by AfzalivE** [schwabe/ics-openvpn#1254]
# General information
1. Android Version: 11
2. Android Vendor/Custom ROM: Google
3. Device: Pixel 3
4. Version of the app (version number/play store version/self-built): Self-built.
 
# Description of the issue
It seems like there's a race condition in `startOpenVPN()` function of OpenVPNService between the time when `OpenVpnManagementThread` starts and DeviceStateReceiver is created.

It's possible that the `handleHold()` function of OpenVpnManagementThread executes _before_ DeviceStateReceiver calls `mManagement.setPauseCallback` which results in an incorrect `LEVEL_NONETWORK` state.

> Note: I can reach through private channels too (from SurfEasy) if you like.

**Comment by schwabe** [comment]
Yeah that sounds like a plausible problem.

**Comment by AfzalivE** [comment]
I'm trying to come up with a solution to create a pull request. So far, there's 

1. Separate the registering device state receiver code from the constructor, but then the handler cannot be created in DeviceStateReceiver's constructor.
2. Create a dummy deviceStateReceiver, which calls `setPauseCallback` immediately until the real one replaces it. (this sounds more like a hack)
