### ISSUE TITLE
Application stopped connecting with Mikrotik's TCP OpenVPN server

### ISSUE THREAD

**Issue by wonder-wanderer** [schwabe/ics-openvpn#1255]
# General information
1. Android 9
2. Android Vendor: Samsung (One UI 1.0)
3. Device: Samsung Galaxy Note 8 (SM-N950F)
4. Version of the app: 0.7.21 (play store version)
 
# Description of the issue
A couple of weeks ago my "OpenVPN for Android" app stopped connecting with any of Mikrotiks that I use with OpenVPN Server.  At least one person I know also seems to have stopped connecting with some Mikrotiks. So I suspect that something

The problem seems to exist for default 128 bit encryption, but probably not for other AES-256-GCM (all of them using SHA1 hash). I will confirm that, but default encryption for sure stopped working. 

So has there been any change in OpenVPN for Android? I am not sure if there is a new major version of OpenVPN mainstream, perhaps it introduces some change in this area, and perhaps OpenVPN for Android picks up from newest OpenVPN mainstream?

**Comment by schwabe** [comment]
You need to provide a lot more details like log files etc. See also the 2nd FAQ in the app titled 'failed to negotiate ...'
