### ISSUE TITLE
Feature request: Autoconnect on unknown WiFis

### ISSUE THREAD

**Issue by error401de** [schwabe/ics-openvpn#1256]
I would appreciate a feature that connects to unknown/insecure WiFis a lot (and does not autoconnect on whitelisted ones).
Is there any chance this feature could be considered?
Thanks!

**Comment by schwabe** [comment]
There is also no good way to implement to implement in a good/secure way. Android does not have an API to block connection on a WiFi before the VPN is connected. (Apart from always on VPN).
