### ISSUE TITLE
Allowed Apps > Exclusions Breaks Config

### ISSUE THREAD

**Issue by lazmo88** [schwabe/ics-openvpn#1259]
# General information
1/2. Stock Android 9 (Android TV) (Security patch 5 April 2020)
3. Xiaomi MIBOX4
4. 0.7.21
 
# Description of the issue
When you have VPN is used for all apps but selected option enabled under the Allowed Apps tab, and you exclude some apps from using VPN, it will break the config. The following error is given. 

Failed to open the tun interface. 
Error: getPackageUid: Neither user 10127 nor current process has android.permission.INTERACT_ACROSS_USERS.
ERROR: Cannot open TUN
Exiting due fatal error. 

As it looks the error related to permissions could be due to the family/restricted user feature we have enabled on the TV box.

**Comment by lazmo88** [comment]
Confirmed: Deleting the restricted profile fixed the issue on bypass rules. However, this should be looked into nevertheless. Could it be simple as adding the missing permissions to the apk manifest?

**Comment by schwabe** [comment]
INTERACT_ACROSS_USERS is a system level permission that normal apps can never have. This more a system/restrictive profile problem that hte app can unfortunately nothing do about. Sorry :(

**Comment by lazmo88** [comment]
@schwabe how about these?

https://stackoverflow.com/questions/54033879/how-to-give-permission-interact-across-users-to-normal-apps-and-handle-this-situ

https://android.stackexchange.com/questions/67038/can-somebody-explain-how-multi-user-is-implemented-in-android-4-4/67040#67040

Looks like you could add: 
<permission android:name="android.permission.INTERACT_ACROSS_USERS_FULL"
    android:protectionLevel="signature" />

To the manifest and it should be supported also on Android 9?

**Comment by schwabe** [comment]
@lazmo88 The permission CANNOT be added to a normal app manifest and it should also not be needed. The error appear when trying to establish a VPN connection with VPNService.  It seem that currently the VPNService API of Android just does not work very well with Restricted profiles. The **Android** code itself breaks on this _getPackageUid_ call, not my app.
