### ISSUE TITLE
Unresolved Reference setPath on setPath(File("${projectDir}/src/main/cpp/CMakeLists.txt"))

### ISSUE THREAD

**Issue by semw** [schwabe/ics-openvpn#1262]
**# General information**
1. Android Studio Version:4.1 
**# Description of the issue**
I am trying to build this project from source code. I have cloned the project and its giving a build error on setPath.
`e: /home/ndroidun/StudioProjects/ics-openvpn/main/build.gradle.kts:38:13: Unresolved reference: setPath`
and error is present on this line of code
`setPath(File("${projectDir}/src/main/cpp/CMakeLists.txt"))`

In build.gradle.kts file in gradle scripts

**Comment by abhishekdeshkar** [comment]
@semw  Don't update the gradle when asked.

**Comment by schwabe** [comment]
Closed by ff4d625d1ef0b8c6e2226dec171487ef2f20e742

**Comment by schwabe** [comment]
And as @abhishekdeshkar if you update the gradle version you might need to fix the gradle files.
