### ISSUE TITLE
setting HttpProxy for individual client-configurations

### ISSUE THREAD

**Issue by mgliewe** [schwabe/ics-openvpn#1263]
Hello, 
it would be very useful, if one could set a http proxy on the connection settings, and later on register this proxy on connect [1].

Right now, I'm doing this by setting a Proxy on the WLAN profile, which in turn gets delegated to the Apps, but that's more a workaround than a solution.

greets
Mario Gliewe

[1] https://developer.android.com/reference/android/net/VpnService.Builder#setHttpProxy(android.net.ProxyInfo)

**Comment by schwabe** [comment]
hm yeah. But openvpn also does not currently support setting a proxy in the configuration itself. I need to think what a good way to configure this would be.

**Comment by mgliewe** [comment]
>  But openvpn also does not currently support setting a proxy in the configuration itself.

true, but setting a proxy on Desktop is way more simple than it is on android; the Chrome browser for instance doesnt even have a setting for that (afaik, at least i didnt find a way)

>  I need to think what a good way to configure this would be.

I would propose an extra checkbox 'set Device HttpProxy' (and subsequent textfields for proxyhost/port) in the server list; also I would propose to export these settings in the generated config as a 'magic comment', something like ```'## x-ics-HttpPoxy host:port'``` to make these settings ex-/importable. 

While on that, similar 'magic comments' for other settings not covered by the openvpn config file format might be usefull as well? (such as 'allow vpn bypass', ext auth provider,  allowed apps and whatever)

**Comment by eht16** [comment]
I would love this feature!

Also using `## x-ics-HttpProxy` or such as a special export comment for these settings is a great idea!

**Comment by schwabe** [comment]
I am not a fan of special settings for just my app. So I don't think it is a great idea.
