### ISSUE TITLE
persistant TUN and Onion don't mix well

### ISSUE THREAD

**Issue by mgliewe** [schwabe/ics-openvpn#1264]
Hi,

I'm trying to establish a openvpn connection via Orbot to an onion address. This works fine, but I want to use 'always on', with non-vpn traffic blocked.

Unfortunately this does not seem to work, upon reboot the Orbot client won't be able to establish a connection to the onion network. I tried to put Orbot into the exclude list, but this does not seem to help.
Is there any way to get this configuration work?

As I understand, android will block any traffic, unless marked via vpnservice.protect() [1], which in turn cannot be done, since the socket is opened by Orbot, not the openvpn service..
I was thinking about including a tor client library into the openvpn app (tor-android [2] comes to mind) and dropping the need of Orbot beeing installed.. 

Any suggestions?

greets
Mario Gliewe

tested on ics/openvpn/v7.0.21 and Orbot 16.3.3-RC-1-tor-0.4.3.6 (both Playstore latest) 
on Pixel 3a (Android 10 latest)

[1] https://developer.android.com/reference/android/net/VpnService#protect(java.net.Socket)
[2] https://github.com/guardianproject/tor-android

**Comment by schwabe** [comment]
There is already a remote call for protect via AIDL but orbot would need to call that. 

Including tor/orbot into my project would work but I am not really interested in maintaing a tor implementation/dependency.
