### ISSUE TITLE
App click crash

### ISSUE THREAD

**Issue by bihuanhai** [schwabe/ics-openvpn#1266]
Die kompilierte Software wird auf dem Mobiltelefonsimulator ausgeführt und blinkt nach dem Klicken zurück. Das Problem wird im Debug-Modus ausgedruckt.
Umgebung: Windows 10, Android Studio 4.0

11/26 09:24:28: Launching 'main' on motorola AOSP on Shama.
$ adb shell am start -n "de.blinkt.openvpn/de.blinkt.openvpn.api.GrantPermissionsActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER -D
Waiting for application to come online: de.blinkt.openvpn | de.blinkt.openvpn.test
Waiting for application to come online: de.blinkt.openvpn | de.blinkt.openvpn.test
Connecting to de.blinkt.openvpn
Capturing and displaying logcat messages from application. This behavior can be disabled in the "Logcat output" section of the "Debugger" settings page.
W/ActivityThread: Application de.blinkt.openvpn is waiting for the debugger on port 8100...
I/System.out: Sending WAIT chunk
I/art: Debugger is active
I/System.out: Debugger has connected
    waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
Connected to the target VM, address: 'localhost:8601', transport: 'socket'
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: waiting for debugger to settle...
I/System.out: debugger has settled (1390)
W/linker: libopvpnutil.so: unused DT entry: type 0x6ffffef5 arg 0x5b0
    libopvpnutil.so: unused DT entry: type 0x6ffffffe arg 0x6fc
    libopvpnutil.so: unused DT entry: type 0x6fffffff arg 0x1
D/openvpn: Loading openvpn native library $id$ compiled on Nov 25 2020 17:31:08
I/art: Explicit concurrent mark sweep GC freed 115(19KB) AllocSpace objects, 0(0B) LOS objects, 25% free, 7MB/10MB, paused 586us total 61.563ms
I/art: Explicit concurrent mark sweep GC freed 19(632B) AllocSpace objects, 0(0B) LOS objects, 24% free, 7MB/10MB, paused 499us total 22.368ms
I/art: Explicit concurrent mark sweep GC freed 3(96B) AllocSpace objects, 0(0B) LOS objects, 24% free, 7MB/10MB, paused 604us total 28.323ms
E/StrictMode: class de.blinkt.openvpn.api.GrantPermissionsActivity; instances=2; limit=1
    android.os.StrictMode$InstanceCountViolation: class de.blinkt.openvpn.api.GrantPermissionsActivity; instances=2; limit=1
        at android.os.StrictMode.setClassInstanceLimit(StrictMode.java:1)
W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
I/Process: Sending signal. PID: 6859 SIG: 9
Disconnected from the target VM, address: 'localhost:8601', transport: 'socket'

**Comment by bihuanhai** [comment]
Now click to keep printing the log below, still can’t open the app

11-26 10:03:52.824 1483-1483/? E/EGL_emulation: tid 1483: eglCreateSyncKHR(1557): error 0x3004 (EGL_BAD_ATTRIBUTE)

**Comment by schwabe** [comment]
To be honest I have no idea what is happen there. Your non-standard way to start `GrantPermissionsActivity` might trigger that strict warning.
