### ISSUE TITLE
Warning: Default Activity not found

### ISSUE THREAD

**Issue by bihuanhai** [schwabe/ics-openvpn#1267]
I git the latest project to the local, and I tried to run the main which failed to run. I found that the entry of the APK is "name='de.blinkt.openvpn.activities.MainActivity'" but it is in the AndroidManifest.xml file in the UI directory in. I don’t know what I need to do to debug the project, thank you very much for your help

![image](https://user-images.githubusercontent.com/73467544/100422161-b7c81b00-30c4-11eb-91f0-a0cba9bfc078.png)

**Comment by bihuanhai** [comment]
Select Default Activity in RUN and prompt for the content
Warning: Default Activity not found

**Comment by schwabe** [comment]
That is a bug in Android that it doesn't see the main activity since it is another Manifest that will get merged.

**Comment by bihuanhai** [comment]
Thank you very much again for replying to my question
I checked "main/src/main/AndroidManifest.xml" in the latest version and did not see the main activity item.
But I saw it in main/src/ui/AndroidManifest.xml.
I tried adding "<category android:name="android.intent.category.LAUNCHER" />" in "main/src/main/AndroidManifest.xml" and it crashed directly in the emulator.
What do I need to run it?
thank you very much
Fans from China



bihuanhai@tyyunan.com
 
From: Arne Schwabe
Date: 2020-11-27 17:57
To: schwabe/ics-openvpn
CC: bihuanhai; Author
Subject: Re: [schwabe/ics-openvpn] Warning: Default Activity not found (#1267)
That is a bug in Android that it doesn't see the main activity since it is another Manifest that will get merged.

**Comment by abhishekdeshkar** [comment]
@bihuanhai How did you fix it ?

**Comment by fy8303** [comment]
How to solve this problem?

**Comment by dawulong** [comment]
How to solve this problem?
