### ISSUE TITLE
T-Mobile USA IPv6-only network causes IPv4 default gateway redirection failure

### ISSUE THREAD

**Issue by surlyhacker** [schwabe/ics-openvpn#1268]
# General information
1. Android Version: 11
2. Android Vendor/Custom ROM: stock pixel
3. Device: Pixel 2 XL
4. Version of the app: 0.7.21
 
# Description of the issue
T-Mobile USA [uses an IPv6 only network](https://www.internetsociety.org/resources/deploy360/2014/case-study-t-mobile-us-goes-ipv6-only-using-464xlat/) and [464XLAT](https://en.wikipedia.org/wiki/IPv6_transition_mechanism#464XLAT) to access IPv4 hosts.
So if a VPN server is configured to route only IPv4 traffic and only accept clients on IPv4, a device on T-Mobile USA can still connect to it of course but will use 464XLAT.  As a result, the client seems to think it is using IPv6 and reports the 464XLAT "fake" IPv6 address of the server.  Upon connecting, if the configuration is set to change the default (IPv4) gateway to the remote server, this does not work, and reports this error:
`NOTE: unable to redirect IPv4 default gateway -- Cannot obtain current remote host address`

And the result is indeed that IPv4 traffic from the client device does not in fact pass through the VPN, even though it shows as connected and is configured to route all IPv4 traffic through the VPN (and "block IPv6 if not used by the VPN").  So that's dangerous from a user expectations point of view.

**The workaround for me was to enable the OpenVPN 3 Core**, which does not have this issue. In other words it is only present using OpenVPN 2.  No VPN config file changes were needed.

Edit: selecting the "Use default Route" option under Routing->IPv4 on the client also serves as a workaround and seems to add this client-side config line: 
`route 0.0.0.0 0.0.0.0 vpn_gateway`
I already had the server-side "redirect-gateway" option which was not working as per the error above.

This appears to be a bug in OpenVPN with a patch here: https://community.openvpn.net/openvpn/ticket/1332

**Comment by tofurky** [comment]
i've also run into the same thing after upgrading to an android 11 device (pixel 5). using google fi (t-mobile).

per the suggested cause above, i tried switching to us cellular which worked.

i was seeing the following with t-mobile:
```
redfin:/ # tcpdump -eni v4-rmnet_data2                                                                                                                                                                                                       
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on v4-rmnet_data2, link-type RAW (Raw IP), capture size 262144 bytes
03:06:41.609298 ip: 192.0.0.4 > 10.0.0.103: ICMP echo request, id 38, seq 1, length 64
03:06:42.616230 ip: 192.0.0.4 > 10.0.0.103: ICMP echo request, id 39, seq 1, length 64
03:06:43.623599 ip: 192.0.0.4 > 10.0.0.103: ICMP echo request, id 40, seq 1, length 64
```

this is traffic that should've been going over tun0 with a 10.0.2.x source ip.

setting 'use default route' did not work for me when trying to use normal apps. i just have a couple lan subnets routes pushed, though. iirc i was able to ping from vpn phone -> lan pc as root with that setting enabled.

pinging from my lan pc -> vpn phone worked one way regardless of the "use default route".

i tried switching to openvpn 3 core, which kind of worked, but then started showing similar symptoms after closing/reopening an app being routed over vpn. i did not see traffic get sent out on one of the v4-rmnet_dataN interfaces when that happened.

**Comment by schwabe** [comment]
As a side note. You should not rely on XLAT464 and OpenVPN should also not use it if you use a DNS name, then you should connect to a IPv6 adress via DNS64/NAT64.

And please provide logs of openvpn2 not working. It is had to debug when I have neither the T-mobile US network nor a log to figure out what is happening.

**Comment by surlyhacker** [comment]
@schwabe thanks. do you want just the regular log that shows up in the app upon connection, or something more?  I can post it here.  Maybe I should also post some evidence showing it not working.

**Comment by schwabe** [comment]
The regular log would be a good start.

**Comment by surlyhacker** [comment]
Log is attached.  It has some information altered for privacy.
[ICS OpenVPN log file bug 1268.txt](https://github.com/schwabe/ics-openvpn/files/5646464/ICS.OpenVPN.log.file.bug.1268.txt)

**Comment by epi-techculture** [comment]
We are a small nonprofit with problem with calling and texting on t-mobile service.  While vpn is on, unable to send or receive calls or texts. else working fine for browsing. I imported the configuration from vpn provider.

To test, we are using a Samsung with 5.1.1
We don't wish to upgrade until we are fully funded.

For now, I handle our security even though not an expert. I want to give options for vpn setup on our Android phones.  Your advice is very appreciated.

Is it a configuration issue? do we need to change service providers? 

Are there any particular settings we need to check?  Do we need new equipment?

 Is there another expert you might recommend we contact as an advisor? even ongoing pay for service with you or another person?

**Comment by schwabe** [comment]
@epi-techculture is this probably a samsung bug that the IP traffic that is used for SMS/LTE VoIP is somehow messed up by running a VPN. I would try if that problem replicates on other phones.

**Comment by schwabe** [comment]
> 2020-12-04 22:09:04 NOTE: unable to redirect IPv4 default gateway -- Cannot obtain current remote host address

@surlyhacker this bug should be fixed in the latest version
