### ISSUE TITLE
'command 'swig'' error

### ISSUE THREAD

**Issue by parinexus** [schwabe/ics-openvpn#1270]
I encounter this error for the first time during the build of the project:

:main:generateOpenVPN3SwigskeletonDebug
A problem occurred starting process 'command 'swig''
The option 'android.enableUnitTestBinaryResources' is deprecated.
CreateProcess error=2, The system cannot find the file specified

please help me to run Project

**Comment by schwabe** [comment]
Please see the readme and the other closed ticket about this. You are missing swig.

**Comment by parinexus** [comment]
can you get me download link and install :
Install sdk, ndk, cmake (e.g. with Android studio), swig (3.0+), on
  Windows perl might be needed for mbedtls

**Comment by schwabe** [comment]
Sorry. I don't build my app on macOS. On macOS it can be installed with brew. Patch/PR to fix windows related build problem are welcome though.

**Comment by parinexus** [comment]
I want Build Android Project in Android Studio in Windows 10
can you help me run it?

**Comment by parinexus** [comment]
how install swig and run it?

**Comment by schwabe** [comment]
Sorry but no. I am not spending a lot of my spare time to install a whole development environment under windows for a random stranger. That is too much to ask, sorry.

**Comment by zhouxin1233** [comment]
> Sorry but no. I am not spending a lot of my spare time to install a whole development environment under windows for a random stranger. That is too much to ask, sorry.

my computer installed swig 4.0.2, but project build result also show "Execution failed for task ':main:generateOpenVPN3SwigskeletonDebug'.
> Process 'command 'swig'' finished with non-zero exit value 1 "
