### ISSUE TITLE
Could not determine NDK host architecture. None of the following directories exist: /path/to/ndk/21.0.6113669/prebuilt/linux-x86_64

### ISSUE THREAD

**Issue by ultra-deep** [schwabe/ics-openvpn#1273]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version = I test on (4.1.1, 4.0.0, 3.6)
2. NDK Version = 21.0.6113669
3. My Client OS = Linux (Ubuntu 18.0.4)
 
# Description of the issue
I Can not compile ics-open and I freeze on this error :  
Could not determine NDK host architecture. None of the following directories exist: /path/to/ndk/21.0.6113669/prebuilt/linux-x86_64

and **linux-x86_64** does not exist on this path:
/path/to/ndk/21.0.6113669/prebuilt/**linux-x86_64**

any idea?

**Comment by schwabe** [comment]
That sounds like a broken Android SDK/NDK install.

**Comment by ultra-deep** [comment]
> That sounds like a broken Android SDK/NDK install.

Thank you... this issue fixed by re-downloading NDK (in my case android-ndk-r21d-linux-x86_64.zip) and compiled successfully...
