### ISSUE TITLE
Error in building

### ISSUE THREAD

**Issue by FirstVoyager** [schwabe/ics-openvpn#1275]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

12/06 18:49:13: Launching 'tlsexternalcertprovider' on HUAWEI BLN-L21.
App restart successful without requiring a re-install.
Could not identify launch activity: Default Activity not found
Error while Launching activity

**Comment by abhishekdeshkar** [comment]
@FirstVoyager How did you fix it ?
