### ISSUE TITLE
In "Connection.java", the method  usesExtraProxyOptions looks like http proxy dedicated

### ISSUE THREAD

**Issue by cool-net** [schwabe/ics-openvpn#1276]
# General information
1. Android Version --- 10
2. Android Vendor --- huawei
3. Device --- mate 10
4. Version of the app --- 0.7.21 your pre-built .apk
 
# Description of the issue
**_"main/src/main/java/de/blinkt/openvpn/core/Connection.java"_**

public boolean **_usesExtraProxyOptions_**() {
return (mUseCustomConfig && mCustomConfiguration.contains("**_http-proxy-option_** "));
}

In **_getConnectionBlock_**, line 63, I saw "if (**_usesExtraProxyOptions()_** && mProxyType == ProxyType.**_SOCKS5_**)"

In .ovpn file, "http-proxy-option" can not be configured alone, it requires "http-proxy" option, but this option can not work together with "socks-proxy" option ... I have no time to dig it deeper, although it seems impossible, but surprisingly, the "socks-proxy" option works for me! what a surprise! I just don't know why. and, I find out that if you want to make the "socks-proxy" option to work, the "socks-proxy-retry" option must be configured.

BTW: if you just configure "socks-proxy-retry" and "socket-proxy" options in the .ovpn file which will be imported later, the generated config file displayed in UI will miss the "socks-proxy" option, I think it because the line 63 got a FALSE, so the statement "**_cfg+=String.format(Locale.US,"socks-proxy %s %s\n", mProxyName, mProxyPort);_**" would never get any chance. but if you configure "http-proxy-option", "socks-proxy-retry" and "socket-proxy" options, everything in the generated config file seems OK, except it just won't work.

I'm really not good at english, sorry for everyone.

**Comment by schwabe** [comment]
> everything in the generated config file seems OK, except it just won't work.

Can you give a step to step instruction how to reproduce and what doesn't work then?
