### ISSUE TITLE
Unrecognized option Scrambled

### ISSUE THREAD

**Issue by andytate1968** [schwabe/ics-openvpn#1277]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
OpenVPN for Android 0.7.21
Android TV Kernel 4.9.125
Sony Bravia VH1 Version 9
 
# Description of the issue
My server requires scramble obfuscate but if I add this to my configuration file and upload it to OpenVPN I get the following when I try to connect...
Option error: Unrecognized option or missing or extra parameter(s) i /data/user/0/de.blinkt.openvpn/cache/android.conf:44 scramble

**Comment by schwabe** [comment]
That is not an official OpenVPN option. Contact the one that gave you that file

**Comment by andytate1968** [comment]
Is obfuscation supported? If so, how would I code it in the configuration file?

**Comment by schwabe** [comment]
This app is following the official openvpn distribution/source and that does not have the scramble option. Adding the scramble patch/option to my app would need to get into the official openvpn code base first.

**Comment by andytate1968** [comment]
I appreciate that.  Just wondering why it didn't just pass through custom tags. So what is the purpose of showing custom ones?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by schwabe** [comment]
it is for options that are actually supported by OpenVPN. --scramble is not a valid option at all.
