### ISSUE TITLE
Could not identify launch activity: Default Activity not found

### ISSUE THREAD

**Issue by abhishekdeshkar** [schwabe/ics-openvpn#1278]
I'm getting this error even after setting "main" activity from the debug configuration.

Also I noticed, there are 2 androidmanifest files there in the manifests folder.

Can someone help ? @schwabe 

```Error  logs```
```
12/12 20:09:53: Launching 'main' on Pixel 3 API 28.
App restart successful without requiring a re-install.
Could not identify launch activity: Default Activity not found
Error while Launching activity
```

**Comment by dawulong** [comment]
怎么解决的啊？
