### ISSUE TITLE
Verizon G3100 router & OpenVPN for Android

### ISSUE THREAD

**Issue by blk1948** [schwabe/ics-openvpn#1282]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version  8.0
2. Android Vendor/Custom ROM  Samsung S7 kernel 3.18.71
3. Device  Samsung S7
4. Version of the app (version number/play store version/self-built)  play store 0.7.21
 
# Description of the issue
Have you heard of issues with the Verizon G3100 router?  I switched to Verizon a couple of weeks ago and cannot seem to connect using your app.  I have port forwarding set up but no connection.  Always get a "server poll timeout, restarting" error in the log.  I do not know if the connection attempt is being stopped by the router or the reply from the VPN server (a Synology NAS attached to the G3100 router with OpenVPN setup and enabled) is not getting out.

**Comment by schwabe** [comment]
Please include at least a complete log from the app. From your description I cannot infer anything.

**Comment by blk1948** [comment]
I left a reply yesterday, it does not seem to have been posted.  I have attached the log you requested.  Same issue with OpenVPN Connect.

[ICS OpenVPN log file.txt](https://github.com/schwabe/ics-openvpn/files/5751949/ICS.OpenVPN.log.file.txt)

**Comment by schwabe** [comment]
This seem to be a connection problem rather than a problem of the app
