### ISSUE TITLE
Disconnect on no connection

### ISSUE THREAD

**Issue by RunsetTech** [schwabe/ics-openvpn#1285]
> you can specify the number of connection attempts. After that the client disconnects

Exactly where ? I've searched a lot

_Originally posted by @RunsetTech in https://github.com/schwabe/ics-openvpn/issues/1284#issuecomment-753392123_

I've modifed VpnProfile class and changed mConnectRetryMam,mConnectRetryMaxTime,mConnectRetry properties but it didn't worked. please tell me exactly where i should set this option ?
Sorry for creating a new topic its because you closed the previous one.

**Comment by schwabe** [comment]
Do not open new issues for existing issues. You can still reply to old ones.
