### ISSUE TITLE
Open VPN and VPN survers is using to much data

### ISSUE THREAD

**Issue by Newpipeuser** [schwabe/ics-openvpn#1292]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android 10 Samsung one Ui 2.0
2. Android Vendor/Samsung
3. SM-S10DL
4. Version of the app latest
 
# Description of the issue
Vpn survers app for android is using to much data does anyone have suggestions to reduce the vpns data ussage?

**Comment by schwabe** [comment]
> Vpn survers app for android

This is even about this app?

**Comment by Newpipeuser** [comment]
yes

**Comment by schwabe** [comment]
The question is much to vague to answer it.
