### ISSUE TITLE
Please help update the translation for Traditional Chinese

### ISSUE THREAD

**Issue by lcy0321** [schwabe/ics-openvpn#1296]
Currently Traditional Chinese translation is terriable, most of them are machine translation.
I've submitted/voted many Traditional Chinese tranlations on Crowdin, it would be nice if they can be updated to the GitHub repository.
Thanks.

**Comment by schwabe** [comment]
Thanks for correcting the translations. I will update them in the next few days. I also gave you proofreader permission, so you can can pin the correct ones.

**Comment by lcy0321** [comment]
Thank you very much

**Comment by lcy0321** [comment]
Hi @schwabe,
Thank you for giving me the permission, I've fixed/approved/submitted all the translations in Traditional Chinese.
Now they are all ready to be updated into the GitHub repository :)

**Comment by schwabe** [comment]
Thank you!
