### ISSUE TITLE
Trying to avoid backups of keys to Google cloud

### ISSUE THREAD

**Issue by jakubklos77** [schwabe/ics-openvpn#1300]
Hello
first of all, great work on the app. Love it.

I was surprised OpenVPN backs up all data including private keys to Google cloud backups. I know there was another ticket about this and it was said by to be done by design. I still think allowBackup should be set to false in the manifest but that is another matter.

What I was trying to do was to specify the keys via file paths in the ovpn profile instead.
ie:
ca /sdcard/.ssh/ca.pem
or
ca /storage/emulated/0/.ssh/ca.pem

However, when establishing the VPN connection the log says:
Permission denied on the file (errNo=13)

The app has file storage permissions allowed.

Do you have any idea how to fix this or how not to include the keys in the backups?

Thank you
Jakub

**Comment by schwabe** [comment]
If you want secure key storage, I would suggest storing them into Android's internal keystore.

**Comment by jakubklos77** [comment]
Thank you, that is the right way to do it
