### ISSUE TITLE
How to import this project as a module to an empty project?

### ISSUE THREAD

**Issue by houmie** [schwabe/ics-openvpn#1302]
Is there any guide how to import this project as a module to an empty project and successfully build it?

In ```build.gradle.kts``` I get shown ```applicationVariants``` as red, hence not recognised.

```
android.applicationVariants.all(object : Action<ApplicationVariant> {
    override fun execute(variant: ApplicationVariant) {
        val sourceDir = registerGenTask(variant.name, variant.baseName.replace("-", "/"))
        val task = tasks.named("generateOpenVPN3Swig${variant.name}").get()

        variant.registerJavaGeneratingTask(task, sourceDir)
    }
})
```

Thanks,

**Comment by schwabe** [comment]
That is a known problem/bug that Android studios shows the kts file in red. It is the same for me:
![image](https://user-images.githubusercontent.com/1038539/112489249-90d1db00-8d7e-11eb-8efa-880eec27e3c7.png)

If I knew why this happens, I would fix it. But I really don't know what triggers this AS behaviour.

**Comment by houmie** [comment]
@schwabe I wished it was just that.

It doesn't let me build the project. It throws:

```
e: /Users/houmie/projects/myApp/vpnLib/build.gradle.kts:152:9: Unresolved reference: applicationVariants
```

Were you able to actually build it?

My steps:

1) Cloned the ics-openvpn repo (https://github.com/schwabe/ics-openvpn)
2) Opened MyApp in Android Studio
3) Clicked on File -> New -> import module and select main folder from ics-openvpn. Name it vpnLib
4) Built the project
5) Went to build.gradle for the openvpn module and change the following :
```id("com.android.application") to id("com.android.library")```
6) Copied this snippet that exists in build.gradle for the library and paste it in MyApp’s build.gradle inside android script:
```
flavorDimensions("implementation")

    productFlavors {
        create("ui") {
            setDimension("implementation")
            buildConfigField("boolean", "openvpn3", "true")
        }
        create("skeleton") {
            setDimension("implementation")
            buildConfigField("boolean", "openvpn3", "false")
        }
    }
```
7) Added the module in the dependency in MyApp’s build.gradle :
```implementation project(path: ':vpnLib')```

Did I miss anything?
Many Thanks

**Comment by schwabe** [comment]
I have no experience of tearing apart my app into different projects or converting it into a library. So there might dependencies to the gradle files in the projectr root. 

Since you are trying to use the project as library, keep in mind that will the resulting app open source under the GPL2/AGPL3

**Comment by houmie** [comment]
@schwabe 

I have emailed you about the license. I hope the email in your Github profile is valid.
