### ISSUE TITLE
OpenVpn3

### ISSUE THREAD

**Issue by SudoDios** [schwabe/ics-openvpn#1304]
Where is the net.openvpn.ovpn3 package?

**Comment by schwabe** [comment]
It is generated with swig during the build process.

**Comment by SudoDios** [comment]
Can't download its packages separately?

**Comment by SudoDios** [comment]
I have a project that I want to use openvpn 3 inside.
What should I do?
How to import openvpn 3?

**Comment by schwabe** [comment]
@SudoDios I don't really understand your question. Maybe if you explain a bit more what you are trying to achieve, I can answer you.

**Comment by SudoDios** [comment]
how to fix (A problem occurred starting process 'command 'swig'') ?
and Execution failed for task ':main:generateOpenVPN3SwigskeletonDebug'.

**Comment by schwabe** [comment]
@SudoDios please put at least some effort in. This is answered in the FAQ as well in several other closed tickets. You need swig installed.

**Comment by SudoDios** [comment]
> @SudoDios please put at least some effort in. This is answered in the FAQ as well in several other closed tickets. You need swig installed.

thank you.
excuse me
