### ISSUE TITLE
ovpn config and allowed apps option

### ISSUE THREAD

**Issue by ipertov04** [schwabe/ics-openvpn#1305]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android >9
2. Samsung
3. Any
4. Latest
 
# Description of the issue
There is an option at:
OpenVPN for Android → tap button with pencil icon on desired profile → swipe to ALLOWED APPS tab → select apps you want to exclude from using VPN → return to main screen → re/connect to VPN using this profile

Does these settings applied to *.ovpn profile or not? When i change this, i can't see any updated information in ovpn configuration file.

**Comment by schwabe** [comment]
They are not reflected in the profile itself. The app does this internally

**Comment by ipertov04** [comment]
@schwabe is it possible to make this adjustable via appconfig? (to be in ovpn settings)

**Comment by schwabe** [comment]
what do you mean with appconfig?

**Comment by ipertov04** [comment]
@schwabe with using android managed configurations

**Comment by schwabe** [comment]
So what you are actually asking to have a way for managed configuration to also specific a white/blacklist of allowed apps?

**Comment by wwei76922** [comment]
> To make issues more manageable, I would appreciate it if you fill out the following details as applicable:
> 
> # General information
> 1. Android >9
> 2. Samsung
> 3. Any
> 4. Latest
>  
> # Description of the issue
> There is an option at:
> OpenVPN for Android → tap button with pencil icon on desired profile → swipe to ALLOWED APPS tab → select apps you want to exclude from using VPN → return to main screen → re/connect to VPN using this profile
> 
> Does these settings applied to *.ovpn profile or not? When i change this, i can't see any updated information in ovpn configuration file.

3.Any

**Comment by schwabe** [comment]
That does not answer my question in the slightest. MDM is not device specific. I would better if you describe your use case rather than let me guess.

**Comment by wwei76922** [comment]
https://github.com/schwabe/ics-openvpn/issues/1305

**Comment by schwabe** [comment]
Just link backing to this issue with a broken link is a not helpful. I am closing this issue for now until I get a good describtion what you are trying to achieve.

**Comment by ipertov04** [comment]
> So what you are actually asking to have a way for managed configuration to also specific a white/blacklist of allowed apps?

yes. to be able to set remote configuration with a policy to make sure that the traffic from a single app, or a set of apps, is routed through VPN.

**Comment by schwabe** [comment]
What does "remote configuration" in this context mean?
