### ISSUE TITLE
Playstore version is 0.7.22 1 month old, F-Droid is 0.7.21 from 6 months, github has recent activity

### ISSUE THREAD

**Issue by subiol** [schwabe/ics-openvpn#1307]
Hi

I want to start thanking you for providing this version of OpenVPN.

I am wondering about the current in F-Droid. It is 6 months old, version 0.7.21, while there has been recent activity in this repository and the Goolag PlayStore version is 0.7.22 from a month ago. Also there has been activity here in this github repository recently.

So I am wondering if there is a reason why the F-Droid version has not been updated for 6 months and is behind one version from the PlayStore, or it has just been forgotten to update for F-Droid?

**Comment by schwabe** [comment]
F-Droid maintains their releases themselves. You have to open a ticket with them.

**Comment by subiol** [comment]
OK, I though F-Droid just automatically pulled from this repository every time you release a new tag, and since you have not set a new tag in 6 months that was the issue.
Can you confirm my understanding is wrong? Then I'll go talk to them.

**Comment by schwabe** [comment]
I think my app build process is more fragile than most apps so it breaks regularly on their side and needs manual intervention.
