### ISSUE TITLE
Is 0.7.22 released or not?

### ISSUE THREAD

**Issue by fossfann** [schwabe/ics-openvpn#1311]
Hi there,

I am seeing 0.7.22 version here (http://plai.de/android/) and there is no 0.7.22 version in the Github nor F-droid. Is that yours?

By the way i couldn't find GPG keys for verifying the APKs.

Thanks.

**Comment by schwabe** [comment]
Forgot to push the tag. There is no gpg key that I sign the apks but they are all signed with the same x509 certificate.

**Comment by fossfann** [comment]
> Forgot to push the tag. There is no gpg key that I sign the apks but they are all signed with the same x509 certificate.

Dear, could you please tell me how can i verify your x509 cert for your releases? I want to do that. Thanks

**Comment by schwabe** [comment]
See https://stackoverflow.com/questions/7104624/how-do-i-verify-that-an-android-apk-is-signed-with-a-release-certificate
