### ISSUE TITLE
Proguard Rules

### ISSUE THREAD

**Issue by SudoDios** [schwabe/ics-openvpn#1315]
Please write a Proguard Rules for this project.
Even famous projects have proguard rules.
Thanks.

**Comment by schwabe** [comment]
why would I want to obfuscate my code?

**Comment by SudoDios** [comment]
Well, this is an option.  Maybe I want to Proguard my project but I can't because of this.

**Comment by SudoDios** [comment]
Wouldn't you like the project to be complete?

**Comment by schwabe** [comment]
@SudoDios your project is also open source since if it is using this. (GPL license). I understand why proguard to obfuscate is needed in a project that is open source.

**Comment by SudoDios** [comment]
Well, maybe I added another option in my project that I do not want others to see.

**Comment by schwabe** [comment]
@SudoDios if your project is using this project you MUST make it open source.

**Comment by SudoDios** [comment]
So what if I have something other than this project in my plan?

**Comment by schwabe** [comment]
If you don't use this project then why you are asking for a proguard rule on this project?

**Comment by SudoDios** [comment]
I use this project but this project is part of my software.

**Comment by schwabe** [comment]
That also makes your software subject to the GPL and you need to opensource it.

**Comment by SudoDios** [comment]
Thank you

**Comment by dzboot02** [comment]
Proguard is not only for obfuscation, it also optimizes code execution and reduces its size.
