### ISSUE TITLE
[Build Error] No Default Activity

### ISSUE THREAD

**Issue by brijagstu7** [schwabe/ics-openvpn#1316]
I'm on macOS 10.14.6 with Android Studio 4.1.3 and Gradle v6.5 and SDK API 30.
My build steps:
ran
`git clone --recurse-submodules -j8 https://github.com/schwabe/ics-openvpn.git`
installed swig with
`brew install swig`
and made sure it's in $PATH.
After a while some new folders were generated, but the build failed writting
```
04/21 17:38:26: Launching 'main' on Pixel XL API 30.
Install successfully finished in 916 ms.
Could not identify launch activity: Default Activity not found
Error while Launching activity
```
Seems to be some problem of the source set of the `ui` package ( since`MainActivity` class cannot be identified, as the `R.layout.*` and `R.id.*` marked red)
I tried some 'workaround's(like change `ui` package name, move it elsewhere , add some more scripts in `build.gradle.kts` etc) but none worked as expected, but indeed, it is not supposed to need any more job to do and just run fine.

**Comment by schwabe** [comment]
You need to select ui also as flavour in Android studio. See the other closed issue on more details or google how to change the flavour in AS.
