### ISSUE TITLE
"Bad compression stub (swap)" when use openvpn core 3 with `compress <blank>` parameter

### ISSUE THREAD

**Issue by denchat** [schwabe/ics-openvpn#1322]
Version: `0.7.22` on play store
Android: `10 API 29, ABI arm64-v8a`
<hr>

When use compression with
```
allow-compression yes
compress lz4
```
openvpn core 3 (experimental) works fine.
<hr>

In contrast, when turn off compression with
```
compress 
```
openvpn core 3 (experimental) reports `Bad compression stub (swap)`.

It seems like the openvpn core 3 doesn't turn off compression on its side.

App `OpenVPN Connect`, which also uses openvpn core 3, doesn't affect with no compress option.
<hr>

However openvpn 2 option works fine with both compress and no compress.

**Comment by schwabe** [comment]
Can you also post configs and logs?

Note that `compress` without any parameter does NOT turn compression off. It still turns on compression v1 framing but not does actually compress.

**Comment by denchat** [comment]
```
Connected via tun
LZO init swap=0 asym=1
Comp-stub init swap=0
COMPRESSION_ENABLED: Asymmetric compression enabled. 
Server may send compressed data. This may be a potential security issue.
```

May I ask how can I make turn off the `COMPRESSION_ENABLED` ?
I already tried:
```
comp-lzo no
allow-compression no
compress
```
It seems still unaffected.

**Comment by schwabe** [comment]
The app always allows compression. But unless the server actually uses/pushes compression options, compression will not be used. If you don't trust the server you have bigger issues to worry about than the potential vulnerabitilities from VORACLE.

**Comment by denchat** [comment]
Okey, you may close this for now.

I'll wait until anyone else can confirm this or it might be the issue of core 3 lib not the caller.

**Comment by denchat** [comment]
Oh one more thing

With `compress lz4` on server, a warning is issued:
```
WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
```

With `compress` on server, that the warning is gone.

**Comment by schwabe** [comment]
Yes. that is expected. Like I said `compress` without parameter does not enable compression but adds compression framing. Compression framing should be avoided as well but is not a vulnerability. If you don't have matching `compress/comp-lzo` settings on server and client you will run into the `Bad compression` header warnings like you did. OpenVPN 2.6 will include `compress migrate` to allow moving away from all compression settings.

**Comment by denchat** [comment]
>
>   like you did.
>

I set both server pc and my `OpenVPN for Android` (with openvpn core 3 option) with
```
compress
```
I got the error: `Bad compression stub (swap)`
However, `OpenVPN Connect` works fine with this configuations.

<hr>

I set server pc with
```
compress
```
and my `OpenVPN for Android` (with openvpn core 3 option) with
```
compress lz4
```
Now `Bad compression stub (swap)` is gone.

So I opened this issue.

**Comment by schwabe** [comment]
Connect ignores the compress directive in its config unless you also enable compression in its setting page.

**Comment by denchat** [comment]
I just checked that:

> Tunnel compression options:  (selected) NO

My question is why do I have to `compress lz4` to workaround this issue on this app?

**Comment by schwabe** [comment]
Normally a server should look at the IV_ values and have a "push compress " something in its server config to match what the client is capable of. 

There is probably other happen in your case which makes the compress lz4 necessary. As said above please post logs+config so I can take a closer look what really happens.

**Comment by denchat** [comment]
May I ask what's the difference between those two? :
```
compress 
push "compress "
```
and
```
compress stub-v2
push "compress stub-v2"
```

The 'stub-v2" is recommended in v2.4 from this article

> VORACLE attack and OpenVPN
> https://community.openvpn.net/openvpn/wiki/VORACLE

I'm not sure whether it's still valid in v2.5.

**Comment by schwabe** [comment]
stub-v2 is basically the same as no compression framing since it only adds a header for IPv5. `compress` on the other hand always adds a header byte.
