### ISSUE TITLE
"Unable to Read Directory" on Android TV 10 AOSP

### ISSUE THREAD

**Issue by bobh-dazn** [schwabe/ics-openvpn#1325]
# General information
1. Android Version - Android TV 10
2. Android Vendor/Custom ROM - CommScope AOSP
3. Device - "Falcon STB" VIP7100
4. Version of the app (version number/play store version/self-built) - 0.7.22 pushed to device from OpenVPN build
 
# Description of the issue
Intending to use OVPN for internal testing purposes, not commercial distribution of the app. Opening OVPN on an Android TV AOSP STB refuses to open any files returning the string associated with "cant_read_folder". Tried with both USB device and internal storage, both get listed in the UI but selecting either of them returns the text of the error above. Other apps are able to navigate the file system (e.g. VPN Client Pro) without throwing this error, so it seems to be implementation specific.

CommScope support have suggested the issue might be with Android TV not having "Storage Access Framework": https://stackoverflow.com/questions/38705316/implementing-a-file-dialog-in-android-tv-leanback/38715569#38715569

**Comment by schwabe** [comment]
Yes. Other apps don't have the problem since they target older APIs that are still allowed to read without storage framework. My app doesn't. And yes storage access framework is missing on many Android TV devices. So the only workaround is to use an external file manager and open the ovpn profile from there and and then import it into openvpn for android.

**Comment by bobh-dazn** [comment]
Thanks,
I've tried several file explorers, X-plore and File Explorer 1.1.1, both of those refused to help. ES File Explorer would allow me to import an OVPN file but refuses to accept the ca.crt and key, it basically complains about not being able to open the file. ES allows two kinds of file selection "Android" and "File", but neither seems to help open the CA/key files, I am going to keep trying to see what I can do.

**Comment by bobh-dazn** [comment]
FYI, 
I've managed to get a configuration which worked by embedding the certs/keys into the config file using the following tags, the VPN seems to be working fine now. Importing still required ES File Explorer and when trying to use the OVPN "Import" option, which uses ES File Explorer, **the app crashes** when it tries to open the file. If I got to ES File Explorer directly and "Open With OpenVPN" it loads the config into OpenVPN for use, it's a work around but there's clearly issues when trying to import using the app's own route on Android TV.

```
<ca>
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
</ca>
<key>
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
</key>
<cert>
-----BEGIN CERTIFICATE-----
...
-----END CERTIFICATE-----
</cert>
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
...
-----END OpenVPN Static key V1-----
</tls-auth>
```

**Comment by schwabe** [comment]
The app should not crash, when exactly does it crash?

**Comment by bobh-dazn** [comment]
When I select "Import" it loads a dialogue from ES File Explorer, then I can select the file and it asks me what way I want to pass back the file (Android mode or File mode), when I select one of those I get kicked back to the STB home screen. 

My adb logs are very noisy as this is a debug box, I'll see if I can extract something.

**Comment by yoimbert** [comment]
I still had this problem on my androidtv when i want to load the profile from androidtv.

Importing Failed: Permission Denial

I went through ES Explorer and now all working. Thx.
