### ISSUE TITLE
log location?

### ISSUE THREAD

**Issue by Enigma3000** [schwabe/ics-openvpn#1328]
# General information
1. Android Version 9
2. Device: Shield Pro 2019

# Description of the issue
Two things: 
1. Is the current log accessible outside the app? I need it as a text file.  
2. Once connected it doesn't say the Country/City name. Is there a way to log for it?

Thank you!

**Comment by schwabe** [comment]
No the log is only internal to the app.

The app doesn't know about any city/country. It only knows about OpenVPN profiles

**Comment by Enigma3000** [comment]
Thank you for the quick reply. 

Would it be too much trouble for you to make a .log file accessible? It would really make things easier. 

And even in the internal app I don't read any profile name. Only the ip address.

Thank you!!

**Comment by schwabe** [comment]
It is not planned to make it avaiable via filesystem and the current design does not really allow it. You can request the log programmatically via the AIDL interface from another app.
