### ISSUE TITLE
"Connect on boot" does not work on Android 9/10

### ISSUE THREAD

**Issue by DeltaLima** [schwabe/ics-openvpn#1329]
# General information
1. Android Version
android 9 and android 10
2. Android Vendor/Custom ROM
Motorola Vendor Rom - all updates applied 
3. Device
Motorola g8 PowerLite and Motorola E7 Plus
4. Version of the app (version number/play store version/self-built)
Playstore 0.7.22
 
# Description of the issue
In my company (small healthcare service) we use OpenVPN for Android to grant access to our internal network for our healthcare employees. All employees does have an Android Phone from us (Motorola G4 Play / Android 7.1) where Connect on boot works as expected.

With our new phones (Motorola g8 PowerLite and Moto E7 Plus - Android 9 and Android 10) Connect on boot just don't work. On boot nothing happens - the OpenVPN for android app dont start. The Option "connect on boot" is ticked in the settings.

This happens on all our phones new phones. I guess it's an incompatibility with the new Android versions (?)

Starting the vpn connection manually works fine. :) 

Thanks and Best regards!

**Comment by schwabe** [comment]
Use always on VPN in System wide vpn settings instead. I need to update the app to point this out.

**Comment by DeltaLima** [comment]
thank's for your fast answer @schwabe ! I tried this out and it worked (tested on g8 power lite, android 10) for one reboot - after that android "forgot" this setting - it's not set anymore in the android settings (maybe an android bug?). so after a second reboot the vpn connection is not started automatically. Very confusing. Unfortunatelly no error message or something else appeared that would give me a hint what's the problem.

**Comment by schwabe** [comment]
That sounds like a bug in the OS or you do have any Admin/device owner MDM solution?

**Comment by DeltaLima** [comment]
Sorry for the late response @schwabe !

Yes, we are using Google Gsuites MDM 

Best regards!

**Comment by schwabe** [comment]
MDM have the ability to set and change these options. What you are seeing might be the MDM changing the state back to what it believes to be right.

**Comment by DeltaLima** [comment]
Thanks for the hint! I Checked the settings in the Gsuite's MDM and it looks good so far - The only setting i could found was "VPN-Access" and it's already set to "allow". 

I will try to grab a spare phone next days and set it up without any google account and see if it happens as well to figure out if it is a problem with the mdm settings. also i will contact gsuite support to ensure i haven't missed a seeting somewhere. :) 

thanks and best regards!

**Comment by olliepop777** [comment]
This is also an issue on Android TV. Specifically, I'm on Chromecast with Google TV. Everything else is working beautifully but I cannot find the setting to enable Always On VPN. Not sure if it's an option on the Chromecast. Is it possible to build a way to toggle this into a setting in the app?

**Comment by juliodee** [comment]
I came searching for same problem as mentioned by @olliepop777 above. LOVE that this app works really well on Chromecast with Android TV, except VPN Settings are not available on Chromecast with Android TV for "Connect On Boot" to work.  Hoping dev can find a method for auto connect to work independently from Android settings.

**Comment by pShota** [comment]
> This is also an issue on Android TV. Specifically, I'm on Chromecast with Google TV. Everything else is working beautifully but I cannot find the setting to enable Always On VPN. Not sure if it's an option on the Chromecast. Is it possible to build a way to toggle this into a setting in the app?

Hi, I experience exact problem on my sony tv, android 10, which is missing VPN setting in Setting Menu,
also the dialog after "connect on boot" cannot redirect to vpn page, any solution?

**Comment by DeltaLima** [comment]
Hi all and @schwabe 

I'm sorry that I havent wrote a comment for so long. 

For our smartphones with Android >= 10 I can confirm it works now as expected. I had to configure the  VPN in Gsuite as always on , as mentioned by @schwabe . Just as info that my problem got solved. Thank you very much for this!! :)

**Comment by schwabe** [comment]
@pShota no solution. My motivation to implement a Android TV specific workaround is also really low.

**Comment by pShota** [comment]
> @pShota no solution. My motivation to implement a Android TV specific workaround is also really low.

can add an option to connect default vpn upon app open please?
it can be used in all system.
Thanks
