### ISSUE TITLE
Document PrivateDNS system setting 

### ISSUE THREAD

**Issue by Blocked** [schwabe/ics-openvpn#1330]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 11
2. Android Vendor/Custom ROM No
3. Device OnePlus
4. Version of the app (version number/play store version/self-built) 0.7.22
 
# Description of the issue

When private DNS(DoT) is set to a  specific "DNS server" in Android  system settings, DNS resolution bypasses VPN TCP tunnel and resolves using  the set Private DNS.

If Private DNS in Android system settings is set to "off", DNS resolution takes place inside VPN TCP tunnel by the DNS server pushed by the VPN servers. 

Is this expected behavior? Could the effect of setting private DNS be documented somewhere?

**Comment by KonTiki1957** [comment]
Hi there, being on the same boat I would be more than happy to get specific information concerning this issue as I need to use a DNS server in the LAN when connected through the openvpn tunnel. Thank you for your effort.

**Comment by schwabe** [comment]
Ask Google not me. As a VPN app author I have no influence about that. If the VPN DNS servers are ignored that can be considered as bug in Android
