### ISSUE TITLE
VPN Not connecting after generating .aab bundle

### ISSUE THREAD

**Issue by pritampawade** [schwabe/ics-openvpn#1331]
I have successfully integrated OpenVpn in my application, VPN is working fine in debug and release APK builds. I had shared APK's for internal testing with my teammates and everyone has tested VPN successfully on their devices. but when I published the .aab file on google play VPN is not connecting, the thread dies after processing state (as per local notification). But when I sideload the release apk on the same device it just works fine.

Since this issue is causing only by the release .aab file I am unable to debug the code to find the exact root cause. I tried disabling proguard and shrinkresources but still no luck.

**Comment by schwabe** [comment]
Please share the source code of your app. Your app is under the GPLv2+ now since you integrated my app.

**Comment by pritampawade** [comment]
Ok, I can't share the source code with you, since VPN is just one module of my project and other stuff is very sensitive to share.

I have modified only Disconnect activity from your code, everything else is untouched. I am clueless about this kind of bug, any possible fix?

I can share the gradle.build file with you if needed

**Comment by schwabe** [comment]
@pritampawade You are legally required to share your source code. Inclduing any GPLv2 code in your software makes your software also GPLv2.

I am also not willing to help in any way  when someone violates the license of my software.

**Comment by pritampawade** [comment]
Can I share the activity from which I am calling the OpenVpn Service? Is that enough? since there is no change in your code

java.lang.Process.destroy()

2021-06-01 18:33:55.282 15736-16739/? I/OpenVPN: Starting openvpn
2021-06-01 18:33:55.285 15736-16739/? E/OpenVPN: OpenVPNThread Got java.lang.NullPointerException: Attempt to invoke virtual method 'void java.lang.Process.destroy()' on a null object reference
2021-06-01 18:33:55.302 15736-16739/? I/OpenVPN: Exiting

This is what log says

**Comment by schwabe** [comment]
@pritampawade No. The GPLv2 license is quite clear that you need to provide the full source code. No exception. Do not include software in your project if you don't understand the license. Unless you publically share your whole source we are done here.

**Comment by KaustubhPatange** [comment]
What is the status of this issue? Is there any solution available?

Edit: I Figured it out, so you need to add `android.bundle.enableUncompressedNativeLibs=false` in your `gradle.properties` & disable abi split in bundle options.

```groovy
android {
  bundle {
    abi { enableSplit = false } 
  }
}
```

**Comment by schwabe** [comment]
@KaustubhPatange that is interesting. If that works that is nice. On what Android versions did you test it?

**Comment by KaustubhPatange** [comment]
@schwabe Tested on Android 10, 11 (although I'm sure it would work pretty fine on lower API levels as well).

**Comment by 92sajid110** [comment]
in release it is not connecting. I tried all above mentioned

**Comment by schwabe** [comment]
@92sajid110 if you find a solution, post here. The offiical app will stay on apk for the foreseeable future, so it is not affected.
