### ISSUE TITLE
Windows compilation error with cmake 

### ISSUE THREAD

**Issue by jlorezz** [schwabe/ics-openvpn#1334]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue
I have been trying to compile the project to work but it just returns:
![image](https://user-images.githubusercontent.com/29343633/121922919-af6ebf00-cd3a-11eb-95b6-1425dae0e14e.png)

**Comment by jlorezz** [comment]
![image](https://user-images.githubusercontent.com/29343633/121944174-a7227e00-cd52-11eb-9e8a-9cb22b97a0be.png)
getting this error now after changing my drive to NTFS

**Comment by schwabe** [comment]
See other issues. I am not developing under windows. Patches are welcome but I cannot look into the issues.

**Comment by jlorezz** [comment]
so what are the exact requirements? like Linux related how can I connect etc.?
