### ISSUE TITLE
Unable to select vpn profile to import on Samsung S10 plus

### ISSUE THREAD

**Issue by dekipaunovic** [schwabe/ics-openvpn#1336]
# General information
1. Android Version - 11
2. Android Vendor/Custom ROM = Kernel version 4.14.113-21644994, Knox 3.7, Knox API level 33, (security level patch from June 1.2021)
3. Device = Samsung Galaxy S10 plus
4. App version = 0.7.22 (installed from google play store)
 
I have just installed OpenVPN for Android on my mobile phone device. I tried to import VPN profile files from device storage but  on the screen with "Select Item" title there is always message "No files". It is able to browse on internal storage as well as SD card. 
Do you have any idea what could be an issue?

**Comment by schwabe** [comment]
Can you add screenshots? I am not sure what it is happening here. Normally the app just call the system ROM file manager to select the file. What you describe sounds like the system does not allow selecting files?

**Comment by dochertp** [comment]
1.  Android Version - 10
2.  Vendor - Sony
3.  XH90
4. Tried both 0.7.24 and 0.7.27

I think I have the same issue.  My Android TV recently updated from Android v9 to v10.  Now I can't load a OVPN profile from a usb disk.  The app does have permission to access storage.  But neither local storage on the television, nor a USB disk seem to work.  I tried two different USB disks just to be sure.

Other apps on my TV don't have this issue (example is VLC).

Error when trying to access data on TV local storage
![IMG_20211007_193810](https://user-images.githubusercontent.com/71666087/136439058-1d1ad793-3afa-4de4-9bc6-eed033dbb75b.jpg)

Error when trying to access data on USB disk
![IMG_20211007_193806](https://user-images.githubusercontent.com/71666087/136439108-3e228c9f-1fab-4e6f-86f1-b153c4ddfd94.jpg)

**Comment by schwabe** [comment]
This app would need to require file manager permission to be abel to be a file manager, which it should not need. The best thing on Android TV is to install an external file manager.

**Comment by dochertp** [comment]
> This app would need to require file manager permission to be abel to be a file manager, which it should not need. The best thing on Android TV is to install an external file manager.

Good advice.  I installed FX File Explorer, and was then easily able to find and select the OVPN profile.  Again, many thanks... I'll just go and donate :)
