### ISSUE TITLE
Kill Swich

### ISSUE THREAD

**Issue by AMIRHOSEIN0082** [schwabe/ics-openvpn#1338]
Hi, I wanted to use the openvpn Kill switch in my application. What should I do? Is it defined in this library?

**Comment by schwabe** [comment]
Killswitch is explained in the FAQ.

**Comment by o0larrylurex0o** [comment]
Hello, the setting is not present anymore as it is described in the FAQ, how can we enable the kill swith again ? thx a lot

**Comment by schwabe** [comment]
Nothing has changed there in the last few years.
