### ISSUE TITLE
[Question] Is there a way to enable "allow bypass" option via inline config?

### ISSUE THREAD

**Issue by ntoskrnl** [schwabe/ics-openvpn#1341]
I am using AIDL to control VPN for my app. But I also need to allow some connections to bypass vpn (by binding sockets to certain networks).

When VPN profile is created via GUI or imported, I can enable "Allow bypass" option. But in my case I use inline config to start VPN. Is there a way to pass this flag in the inline config?

**Comment by schwabe** [comment]
Currently that is not implemented. The same goes for other settings that have no setting in the openvpn file like apps allowed/disallowed via VPN. I can definitively extend the API to have that or you  could make a PR to add that functionality.

**Comment by ntoskrnl** [comment]
I can try to add his into a ConfigParser and make a PR. What should be a proper name for the setting in the file?

**Comment by schwabe** [comment]
The openvpn config file should stay compatible with a normal configuration, so it is not a good idea to add that there.

It is probably better to extend the startVPN and addVPNProfile profile methods with an extra parameter (might need to add extended version to keep aidl compatible) to have an extra Bundle that contains the non VPN option configuration.

So basically you would do something like 

    Bundle extra = new Bundle ();
    extra.put("de.blinkt.openvpn.ALLOW_BYPASS", true);
    service.startVPN(inlinlineconfig, extra);

And then addNewVPNProfile would get a parse extras method that checks if the extra keys are present in the extra bundle and sets the flags on the VPN profile accordingly.

**Comment by ntoskrnl** [comment]
Oh, ok. Got it!

**Comment by ntoskrnl** [comment]
@schwabe Sorry for bothering you. I know there is no fixed timeline and you probably cannot provide ETAs but I have to ask anyway :)
When we could see the new release of the app with the latest changes?

**Comment by schwabe** [comment]
Not sure but I think in the next 2-3 weeks I will probably make another release.
