### ISSUE TITLE
the program does not understand the option "block-outside-dns"

### ISSUE THREAD

**Issue by OmlineEditor** [schwabe/ics-openvpn#1346]
General information:
1. Android Version: 9.0
2. Android Vendor/Custom ROM: native stock
3. Device: Redmi Note 7
4. Version of the app (version number/play store version/self-built) v0.7.22 f-droid
 

In the client settings, there is an option in the configuration "block-outside-dns":
`setenv opt block-outside-dns`

in the program logs I see that your program does not understand this option:
`Unrecognized option or missing or extra parameter(s) in /data/user/0/de.blinkt.openvpn/cache/android.conf:108: block-outside-dns (2.5_master)`

**Comment by schwabe** [comment]
`block-outside-dns`  is a windows only option.
