### ISSUE TITLE
How to have 2 or more simultanous connections on the Android version?

### ISSUE THREAD

**Issue by sm0tsc** [schwabe/ics-openvpn#1347]
How can I make two or more simultanous connections with different profiles on the Android verision.. On Windows it works

//Johan

**Comment by schwabe** [comment]
Android does not support more than one simultaneous connection

**Comment by sm0tsc** [comment]
Is there any plans for a native chromeos version? Or is it not possible
there either?

//Johan

Den tis 3 aug. 2021 kl 22:23 skrev Arne Schwabe ***@***.***>:

**Comment by schwabe** [comment]
I am not planning a native chrome OS version. That would need rewriting the whole app and this is a spare time project.
