### ISSUE TITLE
How to use OpenvpnForAndroid

### ISSUE THREAD

**Issue by MrMercedes** [schwabe/ics-openvpn#1348]
# General information
HUAWEI P10 Plus
Android version:7.0
OPENVPN 0.7.22（OpenVPN for Android）
 
# Description of the issue
With the help of my friends ，I built an openVPN server，and want to test the connect. I get some file like "ca.crt","ca.key",then I get the log: Cannot stat file 'ta.key',No such file or director.
How to configure correctly？

**Comment by schwabe** [comment]
This is only for issues/bugs in the client. Not to offer general openvpn configuration support, sorry!
