### ISSUE TITLE
network is unreachable

### ISSUE THREAD

**Issue by FlorinAndrei** [schwabe/ics-openvpn#1349]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 8.1.0
2. Android Vendor/Custom ROM RED Hydrogen H1A1000
3. Device
4. Version of the app (version number/play store version/self-built)  0.7.22
 
# Description of the issue

I'm on Google Fi 4G. When I try to connect, I get

`write UDP []: Network is unreachable (code=101)`

But the OpenVPN server works fine, I was able to connect to it from an Ubuntu 20.04 instance in AWS, using the exact same config and certificates.

Config file for the client:

```
client
dev tun
proto udp
remote X.Y.Z.K 21194
resolv-retry infinite
nobind
persist-key
persist-tun
ca ca.crt
cert my.crt
key my.key
remote-cert-tls server
tls-auth ta.key 1
verb 3
explicit-exit-notify
```

**Comment by schwabe** [comment]
Please provide a full log

**Comment by FlorinAndrei** [comment]
I've anonymized my IP address, but otherwise the log is unchanged. Here it is:

https://gist.github.com/FlorinAndrei/db751b47170bf73c67adde587d3d5f29

**Comment by schwabe** [comment]
From the log I looks like you have no network connectivity to your VPN server.

**Comment by FlorinAndrei** [comment]
I've replaced the plain IPv4 with the actual hostname of the VPN server and everything worked.

I'm guessing this has something to do with whatever the cell phone provider is doing with IPv6.

Anyway, clearly not an app issue. Thank you, and apologies for the time wasted.
