### ISSUE TITLE
Local networks not refreshed on network change

### ISSUE THREAD

**Issue by SingingFrog7** [schwabe/ics-openvpn#1352]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: Android 11
2. Android Vendor/Custom ROM: GrapheneOS
3. Device: Pixel 5
4. Version of the app (version number/play store version/self-built): 0.7.23 (F-Droid)
 
# Description of the issue
When using the "Bypass VPN for local networks" function along with "Reconnect on network change", the "local network" isn't re-detected/refreshed on network change.

For example :
1. I am home, on WiFi with network 192.168.1.0/24, I except this network to not go through the VPN  **This works**
2. I leave home (or disconnect the WiFi) so I am on LTE, it should remove the network from what is considered "local". **It is still trying to route 192.168.1.0/24 directly, but as it's not a local network anymore, it should go through the VPN**
3. I haven't tried it yet, but if I connect to a different WiFi with a different network, say 192.168.10.0/24, it will probably not consider the new "local network" and will try to pass it though the VPN

**Comment by schwabe** [comment]
Can you provide a log? I think on a reconnect it should change what is consider a local network but you might have reconnected since moving away from the wifi.
