### ISSUE TITLE
OpenVPN on Philips Android TV 55OLED805 does not work if ethernet port and not WIFI port is used of Android TV

### ISSUE THREAD

**Issue by pieland** [schwabe/ics-openvpn#1355]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
9.0 of Android TV. Kernel 4.9.125 16-7-2021, Android Security patch level 5 May 2021.

2. Android Vendor/Custom ROM
Philips

3. Device
Philips 55OLED805/12 Android TV. With its latest available version of the firmware.

4. Version of the app (version number/play store version/self-built)
Latest version available for Android TV on 20-8-2021. OpenVPN for Android 0.7.23.

# Description of the issue

OpenVPN on Android TV does not work if the ethernet port of the Android TV is used. It does work if I use the WIFI port of the Android TV. The point is that OpenVPN seems not prepared in case a device has both a WIFI port and an Ethernet port.

OpenVPN works perfect if I use WIFI. I also am convinced that with the ethernet port is nothing wrong, because I have WIFI of the Android TV disabled. 

If I use OpenVPN with the ethernet port of Android TV, the connection is established, but it immediately gets disconnected and does not work. So I have a connection and it gets dropped. This is the case with TCP protocol of OpenVPN. 
If I configure my OpenVPN server to use UDP instead, OpenVPN shows a 'connection', but after that immediately errors are shown that UDP can not send packets. 

In both cases the Android TV shows that the ethernet port has an error and can't be used. In the network status, it shows multiple 0.0.0.0 addresses e.g. for DNS server, gateway etc. 
After this, I need to switch off my Android TV (hard removing the mains power from the TV), as putting it to standby does not solve the problem.

For your information: I only have a problem with my Android TV if I use OpenVPN with the ethernet port and I always have this problem. Note that I always use my Android TV with ethernet connection without any problems.  So the TV works without any problems if I use ethernet port, when watching Netflix, Youtube etc. but I can't use OpenVPN via ethernet port of the Android TV. For me this problem is reproduceable.

My OpenVPN server is of Synology RT1900AC. 

Please contact me if more information is needed.
I hope you can fix it. Please let me know if I need to test whether your fix works.

**Comment by schwabe** [comment]
I cannot really debug this from my side. My shield and my Google Chromecast with Android TV + USB Ethernet adapter seem to work fine. The app normaly logs what it gets as report from the OS of active networks. what does it report when using Ethernet?

**Comment by pieland** [comment]
If I use OpenVPN via ethernet, it connects successful and then immediately indicates: "Waiting for a usable network".  Below are two links of two small movies that show the behavior: 
In case OpenVPN server has been configured with TCP protocol (2 files):        https://we.tl/b-UBpVV0TZYO 
In case OpenVPN server has been configured with UDP protocol (3 files):       https://we.tl/b-pskRGEkzbh
In both cases the behaviour is similar.
Please download all files and view them.

The Android TV afterwards shows: "Ethernet is not connected." 

Note that everything works perfect if I use WIFI.

Does this help?

**Comment by schwabe** [comment]
That sounds more like a bug in the firmware of the TV than anything else :(

Have you tried disabling the "Check for network changes" option in generic setting?

**Comment by pieland** [comment]
Thanks for the response.
I don't seem to have that setting. I looked to it everywhere. So I can't disable it.

I believe you that it might be a bug in the TV firmware. But I don't expect Philips to fix that.  Unfortunately. 

Thanks for your response.

**Comment by schwabe** [comment]
![image](https://user-images.githubusercontent.com/1038539/133002459-5eefafa3-74c3-4274-8539-10b9d64e6400.png)This setting  "Reconnect on network change"

**Comment by pieland** [comment]
OK, thanks. I was looking at the settings of the Android TV, but you meant OpenVPN for Android. 
Thanks for this response, I am going to check that and let you know the result.

**Comment by pieland** [comment]
I was able to change the setting thanks to your screendump.
Unfortunately the behavior of the TV remains the same and the problem remains. So unfortunately it did not have any effects, but thanks for the suggestion. If you would have anything else I could try, please let me know. Thanks!

**Comment by schwabe** [comment]
I am not actually sure this is something the software could work around :( It might be the TV getting confused and misconfiguring the whole network stack.

**Comment by schwabe** [comment]
Closing the issue since everything points to a bug in the device rather the app.
