### ISSUE TITLE
Feature request: Can 'OpenVPN for Android' also be created for iOS?

### ISSUE THREAD

**Issue by pieland** [schwabe/ics-openvpn#1356]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

Feature request: Can 'OpenVPN for Android' also be created for iOS?
I also use an iPhone. Are there any plans to implement your 'OpenVPN for Android' also for iOS? 
I would love that, because I hate the standard OpenVPN application which does not give any flexibility to configure it afterwards.

Please let me know if I need to test it, once a beta version becomes available? 
Thanks!

**Comment by schwabe** [comment]
There are no plans to port this app to any other platform.
