### ISSUE TITLE
Preventing DNS leak with OpenVPN?

### ISSUE THREAD

**Issue by Inrumpo** [schwabe/ics-openvpn#1359]
# General information
1. Android 11
2. CalyxOS 2.8.0
3. Google Pixel 4a
4. Version of the app:: 0.7.23
 
# Description of the issue
Android phones offer an option to change DNS system settings. It's at `Network and Internet` → `Advanced` → `Private DNS`.
I chose to set a custom `Private DNS provider hostname`.

OpenVPN for Android has an option to override those system DNS settings and to `use your own DNS Servers`. It's at [VPN profile] →  `IP and DNS` → `DNS` → `Override DNS Settings by Server`.

I found that my system DNS settings will not be overridden when I've set a `Private DNS provider hostname`, though I did expect it to do so. If I want OpenVPN for Android to actually override my system DNS setting, I have to set it to `Automatic` or `Off`.

## My goal

- I'm _not_ connected to a VPN via OpenVPN for Android → Use Private DNS provider hostname set within the Android settings
- I am connected to a VPN via OpenVPN for Android → Use DNS servers specified in OpenVPN DNS settings

**Comment by schwabe** [comment]
Check the log what it reports to use. Note that your system wide setting will never be changed but while connected to the VPN, Android will use the DNS server of the VPN.

**Comment by Inrumpo** [comment]
Thanks for your input. I did have a look at the log. It shows the DNS servers specified by me in the OpenVPN settings. ✅

_But:_ Doing a short check with [https://dnsleaktest.com](https://dnsleaktest.com) does show me a different hostname and ISP. That's why I initially thought the wrong DNS servers were used. Therefore I should be more precise: OpenVPN for Android isn't using the wrong DNS servers; I'm experiencing a **DNS leak** instead.

Anything I could do to prevent this?

**Comment by OfficialMuffin** [comment]
Add `block-outside-dns` to your ovpn config file if you are using one.

**Comment by schwabe** [comment]
@OfficialMuffin that is a windows only option. @Inrumpo you need to provide more logs and information to give me any idea what is happening.

**Comment by OfficialMuffin** [comment]
> @OfficialMuffin that is a windows only option. @Inrumpo you need to provide more logs and information to give me any idea what is happening. 

My mistake, sorry

**Comment by Inrumpo** [comment]
Here is my log connected to a VPN while originally on a LTE connection:

> 2021-09-06 21:34:21 F-Droid built and signed version 0.7.24 running on Android Pixel 4a (sunfish), Android 11 (RQ3A.210805.001.A1) API 30, ABI arm64-v8a, (Android/calyx_sunfish/sunfish:11/RQ3A.210805.001.A1/2.8.0:user/release-keys)
> 2021-09-06 21:34:21 Building configuration…
> 2021-09-06 21:34:21 started Socket Thread
> 2021-09-06 21:34:21 Network Status: CONNECTED LTE to MOBILE internet
> 2021-09-06 21:34:21 Debug state info: CONNECTED LTE to MOBILE internet, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED
> 2021-09-06 21:34:21 Debug state info: CONNECTED LTE to MOBILE internet, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED
> 2021-09-06 21:34:21 P:WARNING: linker: Warning: "/data/app/~~8EanPvS8Wr_6-xl1aMowyw==/de.blinkt.openvpn-P1jDGgPDny1RAieHAE0x3g==/lib/arm64/libovpnexec.so" is not a directory (ignoring)
> 2021-09-06 21:34:21 WARNING: Compression for receiving enabled. Compression has been used in the past to break encryption. Sent packets are not compressed unless "allow-compression yes" is also set.
> 2021-09-06 21:34:21 Current Parameter Settings:
> 2021-09-06 21:34:21 config = '/data/user/0/de.blinkt.openvpn/cache/android.conf'
> 2021-09-06 21:34:21 mode = 0
> 2021-09-06 21:34:21 show_ciphers = DISABLED
> 2021-09-06 21:34:21 show_digests = DISABLED
> 2021-09-06 21:34:21 show_engines = DISABLED
> 2021-09-06 21:34:21 genkey = DISABLED
> 2021-09-06 21:34:21 genkey_filename = '[UNDEF]'
> 2021-09-06 21:34:21 key_pass_file = '[UNDEF]'
> 2021-09-06 21:34:21 show_tls_ciphers = DISABLED
> 2021-09-06 21:34:21 connect_retry_max = 0
> 2021-09-06 21:34:21 Connection profiles [0]:
> 2021-09-06 21:34:21 proto = udp
> 2021-09-06 21:34:21 local = '[UNDEF]'
> 2021-09-06 21:34:21 local_port = '[UNDEF]'
> 2021-09-06 21:34:21 remote = '37.19.195.37'
> 2021-09-06 21:34:21 remote_port = '1194'
> 2021-09-06 21:34:21 remote_float = DISABLED
> 2021-09-06 21:34:21 bind_defined = DISABLED
> 2021-09-06 21:34:21 bind_local = DISABLED
> 2021-09-06 21:34:21 bind_ipv6_only = DISABLED
> 2021-09-06 21:34:21 connect_retry_seconds = 2
> 2021-09-06 21:34:21 connect_timeout = 120
> 2021-09-06 21:34:21 socks_proxy_server = '[UNDEF]'
> 2021-09-06 21:34:21 socks_proxy_port = '[UNDEF]'
> 2021-09-06 21:34:21 tun_mtu = 1500
> 2021-09-06 21:34:21 tun_mtu_defined = ENABLED
> 2021-09-06 21:34:21 link_mtu = 1500
> 2021-09-06 21:34:21 link_mtu_defined = DISABLED
> 2021-09-06 21:34:21 tun_mtu_extra = 0
> 2021-09-06 21:34:21 tun_mtu_extra_defined = DISABLED
> 2021-09-06 21:34:21 Waiting 0s seconds between connection attempt
> 2021-09-06 21:34:21 mtu_discover_type = -1
> 2021-09-06 21:34:21 fragment = 0
> 2021-09-06 21:34:21 mssfix = 1450
> 2021-09-06 21:34:21 explicit_exit_notification = 0
> 2021-09-06 21:34:21 tls_auth_file = '[INLINE]'
> 2021-09-06 21:34:21 key_direction = 1
> 2021-09-06 21:34:21 tls_crypt_file = '[UNDEF]'
> 2021-09-06 21:34:21 tls_crypt_v2_file = '[UNDEF]'
> 2021-09-06 21:34:21 Connection profiles END
> 2021-09-06 21:34:21 remote_random = DISABLED
> 2021-09-06 21:34:21 ipchange = '[UNDEF]'
> 2021-09-06 21:34:21 dev = 'tun'
> 2021-09-06 21:34:21 dev_type = '[UNDEF]'
> 2021-09-06 21:34:21 dev_node = '[UNDEF]'
> 2021-09-06 21:34:21 lladdr = '[UNDEF]'
> 2021-09-06 21:34:21 topology = 1
> 2021-09-06 21:34:21 ifconfig_local = '[UNDEF]'
> 2021-09-06 21:34:21 ifconfig_remote_netmask = '[UNDEF]'
> 2021-09-06 21:34:21 ifconfig_noexec = DISABLED
> 2021-09-06 21:34:21 ifconfig_nowarn = ENABLED
> 2021-09-06 21:34:21 ifconfig_ipv6_local = '[UNDEF]'
> 2021-09-06 21:34:21 ifconfig_ipv6_netbits = 0
> 2021-09-06 21:34:21 ifconfig_ipv6_remote = '[UNDEF]'
> 2021-09-06 21:34:21 shaper = 0
> 2021-09-06 21:34:21 mtu_test = 0
> 2021-09-06 21:34:21 mlock = DISABLED
> 2021-09-06 21:34:21 keepalive_ping = 0
> 2021-09-06 21:34:21 keepalive_timeout = 0
> 2021-09-06 21:34:21 inactivity_timeout = 0
> 2021-09-06 21:34:21 ping_send_timeout = 0
> 2021-09-06 21:34:21 ping_rec_timeout = 0
> 2021-09-06 21:34:21 ping_rec_timeout_action = 0
> 2021-09-06 21:34:21 ping_timer_remote = DISABLED
> 2021-09-06 21:34:21 remap_sigusr1 = 0
> 2021-09-06 21:34:21 persist_tun = ENABLED
> 2021-09-06 21:34:21 persist_local_ip = DISABLED
> 2021-09-06 21:34:21 persist_remote_ip = DISABLED
> 2021-09-06 21:34:21 persist_key = DISABLED
> 2021-09-06 21:34:21 passtos = DISABLED
> 2021-09-06 21:34:21 resolve_retry_seconds = 60
> 2021-09-06 21:34:21 resolve_in_advance = ENABLED
> 2021-09-06 21:34:21 username = '[UNDEF]'
> 2021-09-06 21:34:21 groupname = '[UNDEF]'
> 2021-09-06 21:34:21 chroot_dir = '[UNDEF]'
> 2021-09-06 21:34:21 cd_dir = '[UNDEF]'
> 2021-09-06 21:34:21 writepid = '[UNDEF]'
> 2021-09-06 21:34:21 up_script = '[UNDEF]'
> 2021-09-06 21:34:21 down_script = '[UNDEF]'
> 2021-09-06 21:34:21 down_pre = DISABLED
> 2021-09-06 21:34:21 up_restart = DISABLED
> 2021-09-06 21:34:21 up_delay = DISABLED
> 2021-09-06 21:34:21 daemon = DISABLED
> 2021-09-06 21:34:21 log = DISABLED
> 2021-09-06 21:34:21 suppress_timestamps = DISABLED
> 2021-09-06 21:34:21 machine_readable_output = ENABLED
> 2021-09-06 21:34:21 nice = 0
> 2021-09-06 21:34:21 verbosity = 4
> 2021-09-06 21:34:21 mute = 0
> 2021-09-06 21:34:21 gremlin = 0
> 2021-09-06 21:34:21 status_file = '[UNDEF]'
> 2021-09-06 21:34:21 status_file_version = 1
> 2021-09-06 21:34:21 status_file_update_freq = 60
> 2021-09-06 21:34:21 occ = ENABLED
> 2021-09-06 21:34:21 rcvbuf = 0
> 2021-09-06 21:34:21 sndbuf = 0
> 2021-09-06 21:34:21 sockflags = 0
> 2021-09-06 21:34:21 fast_io = DISABLED
> 2021-09-06 21:34:21 comp.alg = 2
> 2021-09-06 21:34:21 comp.flags = 1
> 2021-09-06 21:34:21 route_script = '[UNDEF]'
> 2021-09-06 21:34:21 route_default_gateway = '[UNDEF]'
> 2021-09-06 21:34:21 route_default_metric = 0
> 2021-09-06 21:34:21 route_noexec = DISABLED
> 2021-09-06 21:34:21 route_delay = 0
> 2021-09-06 21:34:21 route_delay_window = 30
> 2021-09-06 21:34:21 route_delay_defined = DISABLED
> 2021-09-06 21:34:21 route_nopull = DISABLED
> 2021-09-06 21:34:21 route_gateway_via_dhcp = DISABLED
> 2021-09-06 21:34:21 allow_pull_fqdn = DISABLED
> 2021-09-06 21:34:21 management_addr = '/data/user/0/de.blinkt.openvpn/cache/mgmtsocket'
> 2021-09-06 21:34:21 management_port = 'unix'
> 2021-09-06 21:34:21 management_user_pass = '[UNDEF]'
> 2021-09-06 21:34:21 management_log_history_cache = 250
> 2021-09-06 21:34:21 management_echo_buffer_size = 100
> 2021-09-06 21:34:21 management_write_peer_info_file = '[UNDEF]'
> 2021-09-06 21:34:21 management_client_user = '[UNDEF]'
> 2021-09-06 21:34:21 management_client_group = '[UNDEF]'
> 2021-09-06 21:34:21 management_flags = 294
> 2021-09-06 21:34:21 shared_secret_file = '[UNDEF]'
> 2021-09-06 21:34:21 key_direction = 1
> 2021-09-06 21:34:21 ciphername = 'AES-256-CBC'
> 2021-09-06 21:34:21 ncp_ciphers = 'AES-256-GCM:AES-128-GCM:AES-256-CBC'
> 2021-09-06 21:34:21 authname = 'SHA512'
> 2021-09-06 21:34:21 prng_hash = 'SHA1'
> 2021-09-06 21:34:21 prng_nonce_secret_len = 16
> 2021-09-06 21:34:21 engine = DISABLED
> 2021-09-06 21:34:21 replay = ENABLED
> 2021-09-06 21:34:21 mute_replay_warnings = DISABLED
> 2021-09-06 21:34:21 replay_window = 64
> 2021-09-06 21:34:21 replay_time = 15
> 2021-09-06 21:34:21 packet_id_file = '[UNDEF]'
> 2021-09-06 21:34:21 test_crypto = DISABLED
> 2021-09-06 21:34:21 tls_server = DISABLED
> 2021-09-06 21:34:21 tls_client = ENABLED
> 2021-09-06 21:34:21 ca_file = '[INLINE]'
> 2021-09-06 21:34:21 ca_path = '[UNDEF]'
> 2021-09-06 21:34:21 dh_file = '[UNDEF]'
> 2021-09-06 21:34:21 cert_file = '[UNDEF]'
> 2021-09-06 21:34:21 extra_certs_file = '[UNDEF]'
> 2021-09-06 21:34:21 priv_key_file = '[UNDEF]'
> 2021-09-06 21:34:21 pkcs12_file = '[UNDEF]'
> 2021-09-06 21:34:21 cipher_list = '[UNDEF]'
> 2021-09-06 21:34:21 cipher_list_tls13 = '[UNDEF]'
> 2021-09-06 21:34:21 tls_cert_profile = '[UNDEF]'
> 2021-09-06 21:34:21 tls_verify = '[UNDEF]'
> 2021-09-06 21:34:21 tls_export_cert = '[UNDEF]'
> 2021-09-06 21:34:21 verify_x509_type = 0
> 2021-09-06 21:34:21 verify_x509_name = '[UNDEF]'
> 2021-09-06 21:34:21 crl_file = '[UNDEF]'
> 2021-09-06 21:34:21 ns_cert_type = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 65535
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_ku[i] = 0
> 2021-09-06 21:34:21 remote_cert_eku = 'TLS Web Server Authentication'
> 2021-09-06 21:34:21 ssl_flags = 0
> 2021-09-06 21:34:21 tls_timeout = 2
> 2021-09-06 21:34:21 renegotiate_bytes = -1
> 2021-09-06 21:34:21 renegotiate_packets = 0
> 2021-09-06 21:34:21 renegotiate_seconds = 3600
> 2021-09-06 21:34:21 handshake_window = 60
> 2021-09-06 21:34:21 transition_window = 3600
> 2021-09-06 21:34:21 single_session = DISABLED
> 2021-09-06 21:34:21 push_peer_info = DISABLED
> 2021-09-06 21:34:21 tls_exit = DISABLED
> 2021-09-06 21:34:21 tls_crypt_v2_metadata = '[UNDEF]'
> 2021-09-06 21:34:21 server_network = 0.0.0.0
> 2021-09-06 21:34:21 server_netmask = 0.0.0.0
> 2021-09-06 21:34:21 server_network_ipv6 = ::
> 2021-09-06 21:34:21 server_netbits_ipv6 = 0
> 2021-09-06 21:34:21 server_bridge_ip = 0.0.0.0
> 2021-09-06 21:34:21 server_bridge_netmask = 0.0.0.0
> 2021-09-06 21:34:21 server_bridge_pool_start = 0.0.0.0
> 2021-09-06 21:34:21 server_bridge_pool_end = 0.0.0.0
> 2021-09-06 21:34:21 ifconfig_pool_defined = DISABLED
> 2021-09-06 21:34:21 ifconfig_pool_start = 0.0.0.0
> 2021-09-06 21:34:21 ifconfig_pool_end = 0.0.0.0
> 2021-09-06 21:34:21 ifconfig_pool_netmask = 0.0.0.0
> 2021-09-06 21:34:21 ifconfig_pool_persist_filename = '[UNDEF]'
> 2021-09-06 21:34:21 ifconfig_pool_persist_refresh_freq = 600
> 2021-09-06 21:34:21 ifconfig_ipv6_pool_defined = DISABLED
> 2021-09-06 21:34:21 ifconfig_ipv6_pool_base = ::
> 2021-09-06 21:34:21 ifconfig_ipv6_pool_netbits = 0
> 2021-09-06 21:34:21 n_bcast_buf = 256
> 2021-09-06 21:34:21 tcp_queue_limit = 64
> 2021-09-06 21:34:21 real_hash_size = 256
> 2021-09-06 21:34:21 virtual_hash_size = 256
> 2021-09-06 21:34:21 client_connect_script = '[UNDEF]'
> 2021-09-06 21:34:21 learn_address_script = '[UNDEF]'
> 2021-09-06 21:34:21 client_disconnect_script = '[UNDEF]'
> 2021-09-06 21:34:21 client_config_dir = '[UNDEF]'
> 2021-09-06 21:34:21 ccd_exclusive = DISABLED
> 2021-09-06 21:34:21 tmp_dir = '/data/data/de.blinkt.openvpn/cache'
> 2021-09-06 21:34:21 push_ifconfig_defined = DISABLED
> 2021-09-06 21:34:21 push_ifconfig_local = 0.0.0.0
> 2021-09-06 21:34:21 push_ifconfig_remote_netmask = 0.0.0.0
> 2021-09-06 21:34:21 push_ifconfig_ipv6_defined = DISABLED
> 2021-09-06 21:34:21 push_ifconfig_ipv6_local = ::/0
> 2021-09-06 21:34:21 push_ifconfig_ipv6_remote = ::
> 2021-09-06 21:34:21 enable_c2c = DISABLED
> 2021-09-06 21:34:21 duplicate_cn = DISABLED
> 2021-09-06 21:34:21 cf_max = 0
> 2021-09-06 21:34:21 cf_per = 0
> 2021-09-06 21:34:21 max_clients = 1024
> 2021-09-06 21:34:21 max_routes_per_client = 256
> 2021-09-06 21:34:21 auth_user_pass_verify_script = '[UNDEF]'
> 2021-09-06 21:34:21 auth_user_pass_verify_script_via_file = DISABLED
> 2021-09-06 21:34:21 auth_token_generate = DISABLED
> 2021-09-06 21:34:21 auth_token_lifetime = 0
> 2021-09-06 21:34:21 auth_token_secret_file = '[UNDEF]'
> 2021-09-06 21:34:21 port_share_host = '[UNDEF]'
> 2021-09-06 21:34:21 port_share_port = '[UNDEF]'
> 2021-09-06 21:34:21 vlan_tagging = DISABLED
> 2021-09-06 21:34:21 vlan_accept = all
> 2021-09-06 21:34:21 vlan_pvid = 1
> 2021-09-06 21:34:21 client = ENABLED
> 2021-09-06 21:34:21 pull = ENABLED
> 2021-09-06 21:34:21 auth_user_pass_file = 'stdin'
> 2021-09-06 21:34:21 OpenVPN 2.5-icsopenvpn [git:icsopenvpn/v0.7.24-0-g0c4b34fe] arm64-v8a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Sep 1 2021
> 2021-09-06 21:34:21 library versions: OpenSSL 1.1.1l 24 Aug 2021, LZO 2.10
> 2021-09-06 21:34:21 MANAGEMENT: Connected to management server at /data/user/0/de.blinkt.openvpn/cache/mgmtsocket
> 2021-09-06 21:34:21 MANAGEMENT: CMD 'version 3'
> 2021-09-06 21:34:21 MANAGEMENT: CMD 'hold release'
> 2021-09-06 21:34:21 MANAGEMENT: CMD 'bytecount 2'
> 2021-09-06 21:34:21 MANAGEMENT: CMD 'state on'
> 2021-09-06 21:34:21 MANAGEMENT: CMD 'username 'Auth' [Username redacted]'
> 2021-09-06 21:34:21 MANAGEMENT: CMD 'password [...]'
> 2021-09-06 21:34:21 Outgoing Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> 2021-09-06 21:34:21 Incoming Control Channel Authentication: Using 512 bit message hash 'SHA512' for HMAC authentication
> 2021-09-06 21:34:21 LZO compression initializing
> 2021-09-06 21:34:21 Control Channel MTU parms [ L:1622 D:1140 EF:110 EB:0 ET:0 EL:3 ]
> 2021-09-06 21:34:21 Data Channel MTU parms [ L:1622 D:1450 EF:122 EB:406 ET:0 EL:3 ]
> 2021-09-06 21:34:21 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1602,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 1,cipher AES-256-CBC,auth SHA512,keysize 256,tls-auth,key-method 2,tls-client'
> 2021-09-06 21:34:21 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1602,tun-mtu 1500,proto UDPv4,comp-lzo,keydir 0,cipher AES-256-CBC,auth SHA512,keysize 256,tls-auth,key-method 2,tls-server'
> 2021-09-06 21:34:21 TCP/UDP: Preserving recently used remote address: [AF_INET]37.19.195.37:1194
> 2021-09-06 21:34:21 Socket Buffers: R=[229376->229376] S=[229376->229376]
> 2021-09-06 21:34:21 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
> 2021-09-06 21:34:21 UDP link local: (not bound)
> 2021-09-06 21:34:21 UDP link remote: [AF_INET]37.19.195.37:1194
> 2021-09-06 21:34:21 MANAGEMENT: >STATE:1630956861,WAIT,,,,,,
> 2021-09-06 21:34:21 MANAGEMENT: >STATE:1630956861,AUTH,,,,,,
> 2021-09-06 21:34:21 TLS: Initial packet from [AF_INET]37.19.195.37:1194, sid=42cc691a 96e23be2
> 2021-09-06 21:34:21 VERIFY OK: depth=2, C=PA, O=NordVPN, CN=NordVPN Root CA
> 2021-09-06 21:34:21 VERIFY OK: depth=1, C=PA, O=NordVPN, CN=NordVPN CA6
> 2021-09-06 21:34:21 VERIFY KU OK
> 2021-09-06 21:34:21 Validating certificate extended key usage
> 2021-09-06 21:34:21 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
> 2021-09-06 21:34:21 VERIFY EKU OK
> 2021-09-06 21:34:21 VERIFY OK: depth=0, CN=at129.nordvpn.com
> 2021-09-06 21:34:22 WARNING: 'link-mtu' is used inconsistently, local='link-mtu 1602', remote='link-mtu 1634'
> 2021-09-06 21:34:22 WARNING: 'tun-mtu' is used inconsistently, local='tun-mtu 1500', remote='tun-mtu 1532'
> 2021-09-06 21:34:22 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, peer certificate: 4096 bit RSA, signature: RSA-SHA512
> 2021-09-06 21:34:22 [at129.nordvpn.com] Peer Connection Initiated with [AF_INET]37.19.195.37:1194
> 2021-09-06 21:34:23 MANAGEMENT: >STATE:1630956863,GET_CONFIG,,,,,,
> 2021-09-06 21:34:23 SENT CONTROL [at129.nordvpn.com]: 'PUSH_REQUEST' (status=1)
> 2021-09-06 21:34:23 PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 103.86.96.100,dhcp-option DNS 103.86.99.100,sndbuf 524288,rcvbuf 524288,explicit-exit-notify,comp-lzo no,route-gateway 10.8.0.1,topology subnet,ping 60,ping-restart 180,ifconfig 10.8.0.11 255.255.255.0,peer-id 9,cipher AES-256-GCM'
> 2021-09-06 21:34:23 OPTIONS IMPORT: timers and/or timeouts modified
> 2021-09-06 21:34:23 OPTIONS IMPORT: explicit notify parm(s) modified
> 2021-09-06 21:34:23 OPTIONS IMPORT: compression parms modified
> 2021-09-06 21:34:23 OPTIONS IMPORT: --sndbuf/--rcvbuf options modified
> 2021-09-06 21:34:23 Socket Buffers: R=[229376->1048576] S=[229376->1048576]
> 2021-09-06 21:34:23 OPTIONS IMPORT: --ifconfig/up options modified
> 2021-09-06 21:34:23 OPTIONS IMPORT: route options modified
> 2021-09-06 21:34:23 OPTIONS IMPORT: route-related options modified
> 2021-09-06 21:34:23 OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
> 2021-09-06 21:34:23 OPTIONS IMPORT: peer-id set
> 2021-09-06 21:34:23 OPTIONS IMPORT: adjusting link_mtu to 1625
> 2021-09-06 21:34:23 OPTIONS IMPORT: data channel crypto options modified
> 2021-09-06 21:34:23 Data Channel: using negotiated cipher 'AES-256-GCM'
> 2021-09-06 21:34:23 Data Channel MTU parms [ L:1553 D:1450 EF:53 EB:406 ET:0 EL:3 ]
> 2021-09-06 21:34:23 Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
> 2021-09-06 21:34:23 Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
> 2021-09-06 21:34:23 ROUTE_GATEWAY 127.100.103.119 IFACE=android-gw
> 2021-09-06 21:34:23 do_ifconfig, ipv4=1, ipv6=0
> 2021-09-06 21:34:23 MANAGEMENT: >STATE:1630956863,ASSIGN_IP,,10.8.0.11,,,,
> 2021-09-06 21:34:23 MANAGEMENT: CMD 'needok 'IFCONFIG' ok'
> 2021-09-06 21:34:23 MANAGEMENT: CMD 'needok 'ROUTE' ok'
> 2021-09-06 21:34:23 MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
> 2021-09-06 21:34:23 MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
> 2021-09-06 21:34:23 MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
> 2021-09-06 21:34:23 MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
> 2021-09-06 21:34:23 MANAGEMENT: CMD 'needok 'DNSDOMAIN' ok'
> 2021-09-06 21:34:23 MANAGEMENT: CMD 'needok 'PERSIST_TUN_ACTION' OPEN_BEFORE_CLOSE'
> 2021-09-06 21:34:23 Opening tun interface:
> 2021-09-06 21:34:23 Local IPv4: 10.8.0.11/24 IPv6: (not set) MTU: 1500
> 2021-09-06 21:34:23 DNS Server: 103.86.96.100, 103.86.99.100, 103.86.96.100, 103.86.99.100, Domain: blinkt.de
> 2021-09-06 21:34:23 Routes: 0.0.0.0/0, 10.8.0.0/24
> 2021-09-06 21:34:23 Routes excluded:
> 2021-09-06 21:34:23 VpnService routes installed: 0.0.0.0/0
> 2021-09-06 21:34:23 Disallowed VPN apps:
> 2021-09-06 21:34:23 MANAGEMENT: CMD 'needok 'OPENTUN' ok'
> 2021-09-06 21:34:23 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
> 2021-09-06 21:34:23 Initialization Sequence Completed
> 2021-09-06 21:34:23 MANAGEMENT: >STATE:1630956863,CONNECTED,SUCCESS,10.8.0.11,37.19.195.37,1194,,
> 2021-09-06 21:34:23 Debug state info: CONNECTED LTE to MOBILE internet, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED

---

DNS set in OpenVPN settings:

1. 103.86.96.100
2. 103.86.99.100

searchDomain: blinkt.de

`Override DNS Settings by Server` is ticked.

---

dnsleaktest.com with Private DNS turned off:

> IP: 37.19.195.38
> Hostname: unn-37-19-195-38.datapacket.com

Therefore: No DNS leak

---

dnsleaktest.com with Private DNS turned on: 

> IP: 185.95.216.116
> Hostname: res1.digitale-gesellschaft.ch

I'm seeing the DNS set as Private DNS in my Android options. I'm expecting to see a hostname/IP provided by my VPN service instead (same as above with Private DNS turned off).

**Comment by schwabe** [comment]
It looks like the client is working fine. For the dns configuration and issue with them of your VPN provider, I would advise to contact them directly. The client just does what it is told to do.

**Comment by Inrumpo** [comment]
> It looks like the client is working fine. For the dns configuration and issue with them of your VPN provider, I would advise to contact them directly. The client just does what it is told to do.

Is the OS just forcing the DNS set in Private DNS over everything else? That's a possible explanation for OpenVPN getting overridden.

**Comment by schwabe** [comment]
Might be the case but the VPN Service API does not have any way of configuring DNS other than I do. If there is a bug regarding private dns from system it is something this app cannot do anything about anyway. If you think that it is a bug you have to try to report that to Google.
