### ISSUE TITLE
Can't select an external server after import of a profile (.ovpn)

### ISSUE THREAD

**Issue by Wibout** [schwabe/ics-openvpn#1363]
# General information
1. Android Version: 9
2. Android Vendor/Custom ROM: Sony 
3. Device: Sony Bravia KD-43XD8305
4. Version of the app (version number/play store version/self-built): Version 0.7.24
 
# Description of the issue
After importing a profile from an .ovpn file I can't select an external server.

![IMG_20210906_233111](https://user-images.githubusercontent.com/8076948/132744768-9dff3173-c4d2-4a04-a92f-a24e8005fc13.jpg)

The .ovpn file works fine on other Android and Windows devices.

When I look in the log I see the message "Used x 11 tries to get current version (-1/0) of the profile".

**Comment by schwabe** [comment]
After an email exhcange with the submitter: The config examples that had the certificates and other info removed could not reproduce this issue and the submitter has found another solution.
