### ISSUE TITLE
Feature request: generate hardware certificate

### ISSUE THREAD

**Issue by djechelon** [schwabe/ics-openvpn#1366]
I'm opening this also for sake of discussion.

**Today**

I have to generate a primary key and certificate for my android device using openssl on a computer. It's my duty to shred the primary key file.

I can import the private key to hardware store (I successfully imported months ago, but now don't ask why the key was deleted from device)

**Desired**

Have openvpn generate a hardware key and export the public part, e.g. via openssl csr
And the openvpn server (based on openssl) can sign it.

What do you think? I like hardening security of apps, and I could contribute in the future if this feature is interesting.

**Comment by schwabe** [comment]
Yes that is something that could be done in the future. But it doesn't need to be in this app as the certificates/keys stored in the android key store are shared between all apps. So you have a dedicated app to manage these. And if there is a good open-source app available I could also just link to it from the VPN settings.

**Comment by schwabe** [comment]
Closing this because I think certificate generation/management is ultimatively outside of what this app should do.
