### ISSUE TITLE
Can't select software in insular

### ISSUE THREAD

**Issue by winterwolf45** [schwabe/ics-openvpn#1369]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version : 11
2. Android Vendor/Custom ROM : custom Rom kernel version: 4.14.190-MOCHI
3. Version of the app: 0.7.24
 
# Description of the issue
Hi i'm trying select Apps into insular for openvpn but i can't show names apps in allowd apps page openvpn for select .

**Comment by schwabe** [comment]
What is insular?

**Comment by winterwolf45** [comment]
“Insular” is a sandbox environment to clone selected apps and isolate them from accessing your personal data outside the sandbox (including call logs, contacts, photos and etc) even if related permissions are granted. Device-bound data (SMS, IMEI and etc) is still accessible.
https://secure-system.gitlab.io/Insular/

**Comment by schwabe** [comment]
Well this is more an isular issue than one of my app. If insular blocks my app from listing all other installed apps for privacy, then my app cannot magically show them. You probably you need to configure insular to allow it again.
