### ISSUE TITLE
Not working after update 0.7.25

### ISSUE THREAD

**Issue by fpavich** [schwabe/ics-openvpn#1371]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android version - I started on 8 and then I upgraded to 9 today in an effort to fix this issue
2. Android Vendor/Custom ROM - unknown
3. Device - Sony Bravia TV KD-55XE8096
4. Version of the app  - 0.7.25
 
# Description of the issue

OpenVPN no longer works on my Android TV as of today.  It seems that the app version updated yesterday and since then it either sits on “building configuration…” or I get error messages like the attached image. 

![4052D3CC-534F-4858-8FA8-44C4422B1005](https://user-images.githubusercontent.com/91983251/136094782-3a43c942-fef4-42e3-bc18-8d0148b11fcc.jpeg)

**Comment by schwabe** [comment]
Duplicate of #1370
