### ISSUE TITLE
0.7.25 cannot load inline certificate

### ISSUE THREAD

**Issue by deviatingchaos** [schwabe/ics-openvpn#1374]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version - 11, September security patch
2. Android Vendor/Custom ROM - Samsung/ATT
3. Device - S21 Ultra
4. Version of the app (version number/play store version/self-built) - 0.7.25
 
# Description of the issue
Since update cannot connect, error states:

04:30 OpenSSL: error:0A00018E:SSL routines::ca md too weak
04:30 OpenSSL reported a certificate with a weak hash, please the in app FAQ about weak hashes
04:30 Cannot load inline certificate file

I am not using MD5, rather SHA512. Reverting to 0.7.23 it functions fine. Everything on my end is up to date. Connecting using OpenVPN Connect works fine as well. I have seen one other report of this specific error on the OpenVPN sub on Reddit.

Thanks!

**Comment by schwabe** [comment]
Please do a `openssl x509 -noout -text -in cert.pem` on the ca and cert to ensure that your certs really do not use SHA1/MD5.
