### ISSUE TITLE
Android TV issue

### ISSUE THREAD

**Issue by AlfaSierra92** [schwabe/ics-openvpn#1377]
With latest application on Android TV, I cannot connect anymore to go due to java.io.EOFException.
I cannot copy log, so I attach a photo of it.
![PXL_20211006_220849642~2](https://user-images.githubusercontent.com/4050967/136276045-b905f1d5-fad6-49ab-ba37-944507038e7b.jpg)

**Comment by schwabe** [comment]
Duplicate of #1370
