### ISSUE TITLE
```

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#1378]
```
Looks like the 4.1.B.0.587 firmware update for Xperias solves the problem.
```

Original comment by `Glorify...@gmail.com` on 22 Oct 2012 at 3:07

_Originally posted by @GoogleCodeExporter in https://github.com/schwabe/ics-openvpn/issues/29#issuecomment-83529735_

**Comment by schwabe** [comment]
This seems to be nonsense copy&paste
