### ISSUE TITLE
[Request] DNS Over TLS

### ISSUE THREAD

**Issue by zero77** [schwabe/ics-openvpn#1383]
# General information
1. Android Version All
2. Android Vendor/Custom ROM 
3. Device all
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue
At the moment when you use a custom dns there is no option to use encryption. 
Which means all dns requests are made in plaintext while all other traffic is encrypted via the vpn connection.

Could you please add support for dns over tls so, dns requests stay encrypted like everything else.

**Comment by SilmorSenedlen** [comment]
@zero77 OpenVPN app itself doesn't contain DNS functionality.
In this case, the methods of interaction with DNS completely depend on the operating system.

**Comment by zero77** [comment]
@SilmorSenedlen 
With in each vpn profile under IP and dns there is an option to use a custom dns. 
I was referring to this not giving the option to use dns over tls.

**Comment by SilmorSenedlen** [comment]
I don't think the app can affect this.
This is just a network setting that indicates where the DNS service is located, and which method to access it is decided by OS, of which the DNS-client (with DNS over TLS support) is a part.
But let's see what the dev has to say.

**Comment by zero77** [comment]
I could be wrong but, i do know other apps like Adguard For Android provide support for custom dns over tls.
>  But let's see what the dev has to say.

Yes

**Comment by schwabe** [comment]
The VPN service API allows only to set normal regular DNS server (https://developer.android.com/reference/android/net/VpnService.Builder#addDnsServer(java.lang.String)). Adguard for Android probably implments a proxy that proxies normal DNS to DNS over TLS and sets the DNS server to localhost.

But I implementing a proxy like that is currently not something I am going to do.

And as for DNS being not encrypted. They are still encrypted via the VPN tunnel.

**Comment by zero77** [comment]
@schwabe 
Not sure how it's been implemented but, this app has dns over tls, see PR below:
https://github.com/blokadaorg/blokada/pull/558

To confirm, are you saying that if you use a custom dns, requests go through the vpn and not directly with out using the vpn.

**Comment by SilmorSenedlen** [comment]
> To confirm, are you saying that if you use a custom dns, requests go through the vpn and not directly with out using the vpn.

If network path to custom DNS server through vpn tunnel, then dns queries encrypted by OpenVPN.
For example, if both OpenVPN and DNS server are on the same host at the same time:
vpn gateway: 192.168.32.1
Custom DNS: 192.168.32.1
