### ISSUE TITLE
0.7.25 Cannot Connect

### ISSUE THREAD

**Issue by dochertp** [schwabe/ics-openvpn#1388]
# General information
1. Android Version
Version 10 / Android TV
2. Android Vendor/Custom ROM
Sony, stock firmware
3. Device
Sony Bravia XH90
4. Version of the app (version number/play store version/self-built)
0.7.25
 
# Description of the issue

Since 0.7.25 I cannot connect to my OVPN server.  I can't get a text extract of the log file, but I do have a photo of it.
![OVPN 0-7-25 issue](https://user-images.githubusercontent.com/71666087/136409784-88d56858-e885-4f74-958a-3343988b5532.jpg)

Sideloading 0.7.24 fixes this, but isn't a sustainable fix as Google Play will auto-update.  I can fix this by disabling auto-update, but this is a global setting, so isn't ideal.

**Comment by Quikfix73** [comment]
Download version 0.7.27 as it is now released that has fixed this issue.

**Comment by schwabe** [comment]
Duplicate of #1370

**Comment by dochertp** [comment]
0.7.27 has resolved this :).
