### ISSUE TITLE
v0.7.29 from Google Play - no Russian interface

### ISSUE THREAD

**Issue by Perlover** [schwabe/ics-openvpn#1406]
Hello,

The last version (v0.7.29) from Google Play shows only English interface but I have Russian language as main language in Android. Before I had Russian language interface. I think it's build bug?

Thanks for this software!

Best regards, Perlover

**Comment by schwabe** [comment]
No, it is not a bug. In the past people complained about various translations, so for translations where I do not have a trusted proofreader on crowd.in, the default is to show English instead. You can toggle this under general settings -> allow community translations.
