### ISSUE TITLE
Incorrect detection of BF-CBC profile

### ISSUE THREAD

**Issue by Marc05** [schwabe/ics-openvpn#1411]
Using OpenVPN for Android 0.7.29 on Android 11 with "OpenVPN 3 Core".

The generated profile config shows only `data-ciphers` and `data-ciphers-fallback` are used, neither of which use BF-CBC. Yet when OpenPVN 3 Core is checked, a warning shows on the profile which says "Profiles uses BF-CBC which depends on OpenSSL legacy provider (not enabled)."

**Comment by schwabe** [comment]
if --cipher is not defined openvpn3 core will fallback to BF-CBC, so for now,  this not a misdetection.

**Comment by alfureu** [comment]
can you tell me where can you define this in your app? I put it as custom option under Advanced and it does not help... am I missing something?
