### ISSUE TITLE
Starting with version 0.7.2.29, OpenSSL legacy option is enforced although BF-CBC shall not be used

### ISSUE THREAD

**Issue by Camillo111** [schwabe/ics-openvpn#1412]
Hello,

I have a self adminstrated OpenVPN Server (server under Win 10)/Android Client senario here.

Immediately when my OpenVN Android Client (under Android 9) App was updated to ver 0.7.2.29, error message "Profile uses BF-CBC which depends on OpenSSL legacy provider (not enabled)" displayed and the client did not connect any more, until I activated SSL legacy mode. Under that legacy setting, it works.

I have tried anything to disable the outdated BF-CBC Cipher and the connection is indeed finally has beeen established using AES-256-CTR as control cipher and CHACHA20-POLY1305 as data cipher (using TLS ver 1.3) .

But it seems that BF-CBC is still offered by the client during the handshake and is therefore regarded as mandatory.

Before I upload all configs and logs here, is there eventually an easy fix for that? 

It seems to basically work already with the legacy SSL setting as mentioned, but it would be nice if also the current lib could be used.

Thanks in advance, 
Joachim

**Comment by schwabe** [comment]
is this is using OpenVPN3 core?

**Comment by Camillo111** [comment]
Yes.

**Comment by Camillo111** [comment]
I must admit that after adding the cipher settings from this article 

[https://blog.securityevaluators.com/hardening-openvpn-in-2020-1672c3c4135a](url)

both to server and client config, the problem disappeared, so the problem seems obsolete.

Thanks anyway, Joachim
