### ISSUE TITLE
TLS Auth File not editable

### ISSUE THREAD

**Issue by sebschub** [schwabe/ics-openvpn#1417]
# General information
1. Android Version: 12
2. Android Vendor: Google official ROM
3. Device: Pixel 6 Pro
4. Version of the app: 0.7.29 from Play store
 
# Description of the issue

I cannot edit the `TLS Auth File`. After activating `Use TLS Authentication`, `TLS Auth File` is activated, however, there is now way to select the file. Clicking on `TLS Auth File`, nothing happens.

**Comment by schwabe** [comment]
Fixed in c2620d7171633697c541ebc8a154098bcb03c542

**Comment by sebschub** [comment]
Thanks for the fix. Do you plan a release soon?

**Comment by schwabe** [comment]
Yes. Tommorrow. There is an OpenSSL 3.0 security update coming for tommorrow and I want to update the library then.
