### ISSUE TITLE
Addition of mandatory tls-cert-profile setting breaks static key configurations

### ISSUE THREAD

**Issue by VA1DER** [schwabe/ics-openvpn#1419]
# General information
1. Android Version: 10
2. Android Vendor/Custom ROM: /e/ OS
3. Device: Fairphone FP3
4. Version of the app (version number/play store version/self-built): 0.7.28 via F-Droid
 
# Description of the issue
Version 0.7.28 of the app adds a mandatory setting "TLS Security Profile" under Authentication/Encryption.  This causes the OpenVPN config option "tls-cert-profile" to be generated which breaks configurations that rely on static key mode.  You cannot have a "tls-cert-profile" setting in a static key configuration and trying to connect will fail.

If a person has upgraded from an earlier version, this breakage won't happen immediately.  One must first try and configure a profile that uses static key, visit the Authentication/Encryption tab, and select the TLS Security Profile setting.  Once this is done, even tapping "cancel" will cause the "tls-cert-profile" setting to be added to the configuration forever with no way to remove it.

It is true that static keys are deprecated, however they are still supported and should not be broken by mandatory incompatible settings in the generated config.

**Comment by schwabe** [comment]
Fixed in 1e791c969df77a424d5d1561cd839aee5b6f00a0 and will be fixed in the next version
