### ISSUE TITLE
Manual selection of the application language

### ISSUE THREAD

**Issue by OmlineEditor** [schwabe/ics-openvpn#1420]
# General information
1. Android Version 9
2. Version of the app 0.7.29 (f-droid)
 
# Description of the issue
Feature Request. Please add the language selection of the application to the settings.
I want to choose the language of the application by myself

**Comment by schwabe** [comment]
The app already allows you have either it localised or in English. What are you missing?

**Comment by OmlineEditor** [comment]
> The app already allows you have either it localised or in English. What are you missing?

the ability to select the interface language in manual mode. you can't switch the interface now. There is no menu for the language right now

**Comment by schwabe** [comment]
What is "manual mode"? I am not really sure what you requesting. 

There is the "Settings" => "Allow community contributed translations". What else do you want/need?

**Comment by OmlineEditor** [comment]
how do I switch the translation to another one?
now the interface of the program is English, I want to switch it to French or Japanese. how do I do this if there is no menu to switch the language?
add a setting to the menu for manually switching the interface language

**Comment by schwabe** [comment]
No, you can also select basically English as official language of the app or the language that matches your android settings. In what use case do you need to select a language that is different from these?

**Comment by OmlineEditor** [comment]
I want to switch between the interface languages in the app. in all applications there is such an opportunity for flexibility.

you can add a new item to the menu so that you can choose any other interface language yourself?

**Comment by QiangNy** [comment]
您好，谢谢你的邮件，我已收到。

**Comment by schwabe** [comment]
@OmlineEditor I don't see a compelling reason for such an option. The argument [others do it](https://en.wikipedia.org/wiki/Tu_quoque) is not a compelling reason.

**Comment by OmlineEditor** [comment]
if other programs make such settings, then they are in demand. the translation is not always correct. sometimes you need to switch the translation and change it to make it clear. Not all users will help with translation. Moreover, it is impossible to correct the translation if it is not possible to switch to another translation. I am guided by simple logic. it's easy to make a menu for choosing a language, and it will be more convenient to use the program.

**Comment by OmlineEditor** [comment]
Russian russian is my interface language in android right now, but your program is in English. I want to switch the language to Russian, but I can't do it. before that, in previous versions, the Russian language was automatically enabled. 

make it possible to switch the interface language

**Comment by schwabe** [comment]
That is still possible.

**Comment by OmlineEditor** [comment]
what is possible? switch the interface in the current version to Russian, or is it possible that you will add to the settings the ability to manually switch the interface language?

**Comment by schwabe** [comment]
Switch between English and the language for your Android OS is possible.

**Comment by OmlineEditor** [comment]
no. now there is a Russian language in the android system and in order to change it, I need to reset all settings to factory settings, I will not do this because I will lose all settings.

**Comment by schwabe** [comment]
@OmlineEditor what you say makes no sense, sorry. You said that the older version had Russian. And the new version allows you to keep the same behaviour as the old version if you tick the "allow community translation" under General settings.

**Comment by OmlineEditor** [comment]
the problem is solved now the program has become in Russian. thanks for the help

**Comment by OmlineEditor** [comment]
please update 3 files from the site:
https://crowdin.com/project/ics-openvpn/ru
and move these files to your project at the specified path:
\main\src\ui\res\values-ru\
