### ISSUE TITLE
Process 'command 'swig'' finished with non-zero exit value 1

### ISSUE THREAD

**Issue by hyzchina** [schwabe/ics-openvpn#1425]
I have a new problem. I installed swig according to the instructions, but Execution failed for task':main:generateOpenVPN3SwigskeletonDebug' appears when I run it.
> Process'command'swig'' finished with non-zero exit value 1

**Comment by zhouxin1233** [comment]
> I have a new problem. I installed swig according to the instructions, but Execution failed for task':main:generateOpenVPN3SwigskeletonDebug' appears when I run it.
> 
> > Process'command'swig'' finished with non-zero exit value 1

我也遇到相同问题, 老哥怎么解决的
