### ISSUE TITLE
openssl/openssl.cmake

### ISSUE THREAD

**Issue by hyzchina** [schwabe/ics-openvpn#1426]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 12
3. Device win7 
 
# Description of the issue
I don’t know if I can run this on win7. I installed the required software according to the instructions, but I encountered this problem. Can you help me solve it? include could not find load file:
       openssl/openssl.cmake

**Comment by schwabe** [comment]
I don't test or support building on Windows platforms. But I suspect you haven't checked the submodules as well

**Comment by schwabe** [comment]
Also Windows 7 is old and not supported by Microsoft anymore anyway.

**Comment by zhouxin1233** [comment]
@schwabe  i have same problems on win11
