### ISSUE TITLE
Feature request: store certificate password

### ISSUE THREAD

**Issue by danielvandenberg95** [schwabe/ics-openvpn#1430]
I'm using a certificate with password. It would be nice if I wouldn't have to re-enter the password every time I reconnect the VPN.

There should probably be a big "storing this password makes it less secure" warning, but I would personally be fine taking that risk, it's still better than transferring an unsecured certificate.

**Comment by schwabe** [comment]
The app already allows that. Are you sure that you are not confusing my app with OpenVPN Connect?

**Comment by danielvandenberg95** [comment]
I came here through the FAQ, so I'm quite sure I'm not confusing apps ;)

Ahh, I just found the field. I have been looking for it but couldn't find it, just read over it. Perhaps hint to it in the password dialog? Or leave it as is, one person being unable to find it shouldn't mean you have to change anything...

Thanks!
