### ISSUE TITLE
Auto-connect not working on Android TV 11

### ISSUE THREAD

**Issue by poneli** [schwabe/ics-openvpn#1439]
# General information
1. Android Version 11
2. Android Vendor/Custom ROM Shield Experience Upgrade 9.0
3. Device nVidia Shield TV Pro
4. Version of the app (version number/play store version/self-built)
 0.7.29
# Description of the issue
Since upgrade to Android 11 from 9 on the nvidia shield tv pro it no longer seems to auto connect on start.

I've checked the box multiple times but it refuses to stick/save/store that option.

**Comment by schwabe** [comment]
Yes. That is expected. The old autostart method does not work on newer Android versions. The Always on VPN has replaced this feature. But Android TV might not allow you to set this one.
