### ISSUE TITLE
[schwabe/ics-openvpn] FATAL Assertion failed at ctx->hmac after upgrade to 0.7.32

### ISSUE THREAD

**Issue by SalvioHyps** [schwabe/ics-openvpn#1440]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 11
2. Android Vendor/Custom ROM: sm6150
3. Device: Redmi Note 10
4. Version of the app (version number/play store version/self-built): 0.7.32/FDROID 
 
# Description of the issue
Backend reject hmac value of "SHA512".

# Configuration file
/data/user/0/de.blinkt.openvpn/cache/config
...
auth SHA512
...

```
add the contents of the configuration file if applicable
be careful to not post private keys
```

**Comment by SalvioHyps** [comment]
Workaround:

If the value of parameter auth is set to SHA256 or SHA384, everything is fine.

**Comment by schwabe** [comment]
Duplicate of #1437
