### ISSUE TITLE
OpenVPN 0.7.33 Broken lzo encryption

### ISSUE THREAD

**Issue by keremers** [schwabe/ics-openvpn#1444]
Hi,

I was using Toshiba TV with Android 6 until today. Today I decided to buy Mi Box S. I've installed OpenVPN, Transferred my VPN config file from the TV. My Server is 4000+ km far away and I don't want to change the, now obsolete, lzo setting. So LZO must stay on for this time. When I installed the OpenVPN for android and transferred and edited the configuration. It complains LZO module can not be activated. I checked my TV and saw the version I am using there is 0.7.29 when. But the new box has 0.7.33. I have uninstalled version .33 and manually installed .29. Once I downgraded the server it worked like a charm. If it didn't I would suspect the android libraries. But it seems that the issue is the software itself. Can you check it? 

The error I got is:
MGMT: Got unrecognized command FATAL:Assertion failed at /Users/arne/software/icsopenvpn/lzo.c:165(buf_safe(&work, ps + COMP_EXTRA_BUFFER(ps)))

Since it is a fatal error the connection attempt fails. 

To reproduce this your server must require lzo. The client settings need to enable lzo and set compression on with these commands:

comp-lzo
allow-compression no

I hope this helps. There must be something broken between version .29 and .33...

If you need more info please let me know.

**Comment by schwabe** [comment]
Will be fixed in next update
