### ISSUE TITLE
OpenSSL 3.0 rejects SHA1 and MD5 certificates

### ISSUE THREAD

**Issue by devilspork** [schwabe/ics-openvpn#1446]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information - connection is failing
1. Android Version - 12
2. Android Vendor/Custom ROM - Google
3. Device - Pixel 3XL
4. Version of the app (version number/play store version/self-built) - 0.7.33/play store
 
# Description of the issue - "Cannot load inline certificate file"

# Log (if applicable) - attached.

```
log contents
```

# Configuration file - Attached.

```
add the contents of the configuration file if applicable
be careful to not post private keys - scrubbed.
```
[server.ovpn.txt](https://github.com/schwabe/ics-openvpn/files/7954004/server.ovpn.txt)
[Log.txt](https://github.com/schwabe/ics-openvpn/files/7954014/Log.txt)

**Comment by schwabe** [comment]
From your log.

> 2022-01-27 15:46:01 OpenSSL: error:0A00018E:SSL routines::ca md too weak
> 2022-01-27 15:46:01 OpenSSL reported a certificate with a weak hash, please see the in app FAQ about weak hashes.
