### ISSUE TITLE
Feature request:  Expose "Pause VPN after screen off" via intents/shortcuts

### ISSUE THREAD

**Issue by Blocked** [schwabe/ics-openvpn#1460]
Requesting "Pause VPN after screen off" functionality be exposed via intents

**Comment by schwabe** [comment]
Do you want to enable/disable that setting while the VPN is running or what is the goal here?

**Comment by Blocked** [comment]
Yes, I want to disable/enable that setting, while the VPN is running. Say, manually or automatically(through intents/shortcuts) at specified times. It helps battery.  (Personally, any allowance of customization on that setting would be helpful. 60s is low. I think hard limits like 64kb  within 60s is arbitrary)

**Comment by schwabe** [comment]
The limits are arbitrary. But I don't intend to offer a any customisation on that feature. The 64KB in 60s is mainly to not always immediately kill the VPN connection when the screen goes blank.  Most times this feature is also a workaround for some other problem like a bad VPN configuration that drains battery.

**Comment by Blocked** [comment]
That's fine. But consider exposing "Pause VPN after screen off" or at least the "Pause VPN"  itself through intents. I can see open intents for connect and disconnect, but not for pausing.
