### ISSUE TITLE
minivpn/minivpn.c is empty hence not executable!

### ISSUE THREAD

**Issue by CRINOL** [schwabe/ics-openvpn#1470]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android 11
3. Stock ROM
4. TECNO SPARK 7 PRO
5. Version of the app (version number/play store version/self-built)
 
# Description of the issue
The libopenvpnexec.so is not a directory but an empty file since even the minivpn.c is empty hence cannot be execute
when starting the process, it cannot start since the libopenvpnexec.so linker file is ignored. Fix this please.
# Log (if applicable)
2022-03-18 00:12:12.415 23999-25274/com.kratos.alX0025 I/OpenVPN: WARNING: linker: Warning: "/data/app/~~sE3paad6RSPJTmbJb19Ffg==/com.kratos.alX0025-dRHrEhSjTCIGLYD061ewRQ==/lib/arm64/libovpnexec.so" is not a directory (ignoring)

```
log contents
```2022-03-18 00:12:12.415 23999-25274/com.kratos.alX0025 I/OpenVPN: WARNING: linker: Warning: "/data/app/~~sE3paad6RSPJTmbJb19Ffg==/com.kratos.alX0025-dRHrEhSjTCIGLYD061ewRQ==/lib/arm64/libovpnexec.so" is not a directory (ignoring)

# Configuration file
the config file is not the issue here
```
add the contents of the configuration file if applicable
be careful to not post private keys

**Comment by schwabe** [comment]
>  `com.kratos.al`

This is not my app.

**Comment by CRINOL** [comment]
I examined the source code and found some issues...
It works though
Am still looking into it
