### ISSUE TITLE
Is thia a real application? (AppGallery)

### ISSUE THREAD

**Issue by melianmiko** [schwabe/ics-openvpn#1474]
Some application with this package name was published in AppGallery as a paid app. Is this a real app, or is someone impersonating you?

https://appgallery.cloud.huawei.com/ag/n/app/C105619503

**Comment by schwabe** [comment]
I did not publish it there, so it is probably someone else that uploaded it to that store. I have no idea if that app is free of malware or not or anything else about it.

**Comment by melianmiko** [comment]
Fine, then I will ignore it.

Might be worth adding a warning about this to README?B ecause the app store might, in theory, offer to update your app to that dubious version.
Or will someone buy it by mistake, wanting to make a donation.

**Comment by schwabe** [comment]
Huawei seems to have removed the app.
