### ISSUE TITLE
No description provided.

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#1476]

**Comment by schwabe** [comment]
That is a system setting. Sounds like you have a broken system ROM.

**Comment by fastcat001** [comment]
no @schwabe , unfortunately, that's not true.

I tried wireguard's official android app and killswitch works,
I tried native vpn app killswitch, they work

**Comment by schwabe** [comment]
Are we talking about the same thing? I am talking about the setting in android system. The app itself does not implement a killswitch. It would also be good to say what device you are using.

**Comment by fastcat001** [comment]
hi @schwabe , yes, we are talking about the same thing.

Even if I turn on Android system's **always-on VPN** & **Block connections without VPN**,
data and IP still leak when connection fails using OpenVPN app.

Again, this problem does not occur when I turn on Android system's **always-on VPN** & **Block connections without
using wireguard's official android app or any reputable vpn provider's native app (ProtonVPN, Mullvad...)

I am using LineageOS Custom Rom 18.1, based on Android 11.

**Comment by schwabe** [comment]
How are you determining the IP leaks? Maybe there is something that my app does different. But overall this should not happne.

**Comment by fastcat001** [comment]
Hi @schwabe , I was able to access website when openvpn connection was down, but wifi connection was up.

**Comment by schwabe** [comment]
@fastcat001 so the problem is there is absolutely nothing that the app can do about the exact behaviour of the always on VPN implemented by operating system. So you need to provide more details on how:
- how you determined that the VPN is not running
- that the website you were acessing is really using your WiFI and not the wifi
