### ISSUE TITLE
Some native Libs missing canary flag (-fstack-protector-strong), failing Google security audit 

### ISSUE THREAD

**Issue by eladlevin** [schwabe/ics-openvpn#1478]
My app was just audited by Google using one of their partner labs. They are using [OWASP](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05i-Testing-Code-Quality-and-Build-Settings.md) guidelines for the audit.
They have informed me that some of the native libs do not have the canary flag (aka `-fstack-protector-strong` GCC flag) and is therefore failing [MSTG-CODE-9](https://github.com/OWASP/owasp-mstg/blob/master/Document/0x05i-Testing-Code-Quality-and-Build-Settings.md), "Make Sure That Free Security Features Are Activated".

They are testing using Radare2

I tried to add the following
```
add_compile_options("-fstack-protector-strong")
add_compile_options("-frecord-gcc-switches")
```
to the root-level CMakeLists.txt file, but this does not solve the issue.

Here are the affected libs:
```
merged_native_libs\skeletonDebug\out\lib\arm64-v8a\libjbcrypto.so
merged_native_libs\skeletonDebug\out\lib\arm64-v8a\libovpnexec.so
merged_native_libs\skeletonDebug\out\lib\armeabi-v7a\libovpnexec.so
merged_native_libs\skeletonDebug\out\lib\x86_64\libjbcrypto.so
merged_native_libs\skeletonDebug\out\lib\x86_64\libovpnexec.so
merged_native_libs\skeletonRelease\out\lib\arm64-v8a\libjbcrypto.so
merged_native_libs\skeletonRelease\out\lib\arm64-v8a\libovpnexec.so
merged_native_libs\skeletonRelease\out\lib\armeabi-v7a\libovpnexec.so
merged_native_libs\skeletonRelease\out\lib\x86_64\libjbcrypto.so
merged_native_libs\skeletonRelease\out\lib\x86_64\libovpnexec.so
```
Is there any way to force this flag on all libraries? Why would these 2 libs specifically have this flag disabled?

Thanks !

**Comment by schwabe** [comment]
What is your app and can give a copy of that report so I can have a look?

**Comment by eladlevin** [comment]
Let me check what is and is not confidential, I'll probably email it to you at the address on your github profile.

**Comment by YuriiLukiianchuk** [comment]
Hi. So, here it is for libs, listed in initial message
<img width="1206" alt="image" src="https://github.com/user-attachments/assets/54b47798-7e98-4d46-b64d-16c7cf92b586">

**Comment by schwabe** [comment]
Probably false positive.
