### ISSUE TITLE
packet drop

### ISSUE THREAD

**Issue by zaeem-code** [schwabe/ics-openvpn#1479]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version.  11
3. Device.  MI note 11
log error
I am now getting: rWRSat Mar 26 12:02:29 2022 us=375234 client-de0/119.160.99.137:1082 MULTI: bad source address from client [10.13.142.19], packet dropped
now connection successfully connected but it drop after 2 or 3 minutes and having Error MULTI: bad source address from client

**Comment by schwabe** [comment]
This i intended/normal behaviour when your phone tries to use its Wifi/mobile network IP over the VPN.

**Comment by zaeem-code** [comment]
basically on mobile data it drop the packet and error multi bad source but on WiFi it work fine so basically I can't understand what is the issue on mobile network
