### ISSUE TITLE
Indonesian should be id not in

### ISSUE THREAD

**Issue by KwadroNaut** [schwabe/ics-openvpn#1481]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
3. Tried with Android 9 and 10
4. Version: latest master branch: main/src/ui/res/values-in/strings.xml
 
# Description of the issue

There are Indonesian (Bahasa) translations, but they're not shown in the interface. They should be in values-id instead. You can replicate by switching your system preferred languages.

**Comment by schwabe** [comment]
Have enabled custom translations under general settings? 

Android screwed up the language code for Indonesian, so I think the values-in is correct.

**Comment by schwabe** [comment]
See also here: https://stackoverflow.com/questions/13291578/how-to-localize-an-android-app-in-indonesian-language

**Comment by KwadroNaut** [comment]
I wasn't aware of the language switch in the settings, thanks. I wasn't aware that Java did this wrong a long time ago: api level 1: https://web.archive.org/web/20160215064626/http://developer.android.com/reference/java/util/Locale.html Sorry for the noise.
