### ISSUE TITLE
Latest version, silent crash without error in log, not compression related

### ISSUE THREAD

**Issue by sebastiannielsen** [schwabe/ics-openvpn#1482]
Silent crash ("This app has an bug") regardless of if allow-compression is set to yes or not.

no error in log.

![Screenshot_20220504-233544_Device care.png](https://user-images.githubusercontent.com/1034930/166830059-35960e36-fa19-4273-b5a1-01b8f4e10174.png)

**Comment by schwabe** [comment]
Fixed by 1a5648cbdde

**Comment by sebastiannielsen** [comment]
Fix reintroduced the compression error: https://github.com/schwabe/ics-openvpn/issues/1442
