### ISSUE TITLE
Optionally disable "Cancel Confirmation" Dialog

### ISSUE THREAD

**Issue by MarthinusBosman** [schwabe/ics-openvpn#1487]
# General information
1. Android Version: 12
2. Android Vendor: Samsung
3. Device: Samsung Galaxy Note10
4. Version of the app: 0.7.37
 
# Description of the issue

When trying to use the app with Bixby Routines, I'm trying to connect and disconnect to my VPN automatically, but when using the Disconnect app action, a popup comes up for "Cancel Confirmation" which makes the automation useless.

Is it possible to silence this dialog popup in the configuration? And if not, I feel an optional flag should be added to disable the confirmation dialog.

**Comment by schwabe** [comment]
There already intents that are designed to be used in automation.

**Comment by MarthinusBosman** [comment]
@schwabe I'm using those intents, what I'm saying is that the disconnect intent causes a popup dialog to show up to confirm, which doesn't make it useful as an automation, the disconnect intent should either not have the popup show up or it should be configurable per VPN profile.

Adding screenshots to show what I mean, this is the automation rule:
<img src="https://user-images.githubusercontent.com/38855581/168812996-d4a34c01-feae-47ff-b106-aeb9e5309acf.jpeg" width="200"/>

And this is the popup that shows up when it's triggered:
<img src="https://user-images.githubusercontent.com/38855581/168813052-d816f41e-d668-471e-8f8f-cb94928c0f7f.jpeg" width="200"/>

**Comment by schwabe** [comment]
Those are the shortcuts. The intent are different are documented here: https://github.com/schwabe/ics-openvpn#controlling-from-external-apps

So this is already supported and used by other automation apps like Tasker. What you are seeing there are the shortcuts that you get when you long an app icon in a normal launcher. They are meant to be used by an interactive user and not by a automation app.

**Comment by MarthinusBosman** [comment]
I see, but it seems bixby doesn't support these intents, so for my case this would still be a feature request.

Apart from just my use case, would it not be appropriate to have a flag to disable/override the popup anyway?

Even when disconnecting from the notification manually, I don't necessarily want to have to press disconnect again.

**Comment by schwabe** [comment]
@MarthinusBosman that is a design/user experience decision that I made. And a lot of people want the confirmation. So basically the question is only if it should be configurable and currently I don't see a compelling reason for that.

With flag. If you mean a flag in the intent, you could just use the normal intent. But a configuration flag for that? No, that requires extra testing, extra code etc and basically also duplicating the already existing intents that other automation software is able to use just fine.

And for Samsung. I am quite annoyed/fed up with their broken Android stuff and software, so adding an extra hack just for their broken Bixby stuff is quite low on my motivation list.

**Comment by MarthinusBosman** [comment]
That's fair, I'll try and create a PR for it though.
