### ISSUE TITLE
Key public

### ISSUE THREAD

**Issue by Taloxer** [schwabe/ics-openvpn#1489]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue
yes
# Log (if applicable)
yes
```
log contents
```yes

# Configuration file
Yes
```
add the contents of the configuration file if applicable
be careful to not post private keys
```yes

**Comment by schwabe** [comment]
This bug report has no information in it.
