### ISSUE TITLE
Trouble with latest versions

### ISSUE THREAD

**Issue by frispete** [schwabe/ics-openvpn#1495]
# General information
1. Android Version: 12
2. Android Vendor/Custom ROM: Samsung
3. Device: Galaxy S20 
4. Version of the app (version number/play store version/self-built):
 0.7.37 from Play Store
# Description of the issue
I suffer from some authentication issues with the latest version(s). In order to exclude update regressions, I attempted to downgrade to one of the older packages  provided here, but then, after allowing to install 3rd party apks, it first asks for updating the package, and then declines with stating an error about an obvious?! invalid apk (freely translated). Any idea?

The underlying problem might be related to an IP6 routing issue, because the openvpn server is behind two cascaded routers. I also tried to disable IPv6 on the client side already, but that failed so far.

**Comment by schwabe** [comment]
The older packages here on github as the same that I upload to the Google play store. 

Have you openend an issue for the authentication issues that you are having with the latest version?

**Comment by frispete** [comment]
> The older packages here on github as the same that I upload to the Google play store.

Okay, thanks. The culprit was attempting to downgrade, which results in the silly error, quoted above.
Hence a downgrade requires deinstall the package beforehand. @others getting here: the best way to keep the config is switching to "Generated Config" tab, tap on "Share" and "Copy", create a file with your favorite tool using a .ovpn extension, and paste the config there for all your vpns. The "Save as" share target does not work with the FX-File Manager at least. Now you're able to deinstall and install a lower version of this package without much fuzz.

@schwabe the downgade behaves identical.

> Have you openend an issue for the authentication issues that you are having with the latest version?

Not yet, I'm on holiday, and not sure, if I manage to prepare the logs properly from here.

Here's my current theory of malfunctioning in certain environments:
The local router here (in France: Provider Orange) assigns both an IPv4 and IPv6 address to my devices via Wifi. For some reason, openvpn connects to my home, using a IPv4 address (that is resolved from a IPv4 only dyndns provider), but the data arrives via IPv6 (as seen on the server). That server resides behind a router cascade, that probably doesn't get the IPv6 routing right. With other routers (and other providers), this does not happen.  
This could be the result of some RNAT or CGN (Carrier Grade NAT).

So, I'm proably barking at the wrong tree here.If you think, that Openvpn for Android should get this managed correctly, let me know. I will try to prepare the neccesary data properly on both sides. 

Want me to open another issue for this?

**Comment by schwabe** [comment]
If you find something that is actually related to my app and not some broken netwok that I cannot do anything about anyway but so far the IPv6 support of my app has been working.

PS: you can do a downgrade with keeping the data if you force it via adb.

**Comment by frispete** [comment]
Hey, after returning home, I rrestarted the routers because of other issues appearing, and guess what, issue resolved..

Sorry for the fuzz, and thank you for your great app! I'm using it since a couple of years now and suggesting it to colleagues and friends on a regular basis!
