### ISSUE TITLE
Compile latest ics-openvpn with FIPS compliant open-ssl 

### ISSUE THREAD

**Issue by daouddexter** [schwabe/ics-openvpn#1498]
Currently code here uses Open SSL from here: https://github.com/schwabe/platform_external_openssl/tree/53592d395ea6721b5099254ba1ca7aefbc26c8c6

Instead,I want to use FIPS compliant version of OPEN SSL(1.0.2). 
I have crypto.so, crypto.a, ssl.so, ssl.a and include files but not sure how to add them in this project.
Need help here

**Comment by schwabe** [comment]
It is a long time that I compiled the app with OpenSSL 1.0.2. And I never tried compiling it with a FIPS version. Building this app with that version requires deeper knowledge of building OpenSSL and is not going to be trivial. Can I ask why you want to do that?

**Comment by daouddexter** [comment]
This is for adherence to compliance we want to use the FIPS version else our app will not be passed for release.

**Comment by schwabe** [comment]
@daouddexter Please note that if you have your own app that is based on this app, it is automatically GPL2 as well. Building my app with an OpenSSL FIPS release is probably possible but is nothing I implement for free as normal users do not have this requirement.
