### ISSUE TITLE
please upload the system flow 

### ISSUE THREAD

**Issue by Deepanshusuman** [schwabe/ics-openvpn#1509]
i will file a case against you for not letting users to how the flow is or how it is working if you need money simply write i need some special amount to write a code for you or simply say this is none of my bussiness and write the code / mess with the code untill and unless you broke the production

**Comment by schwabe** [comment]
@Deepanshusuman good luck with that. This is open source and you are entitled to nothing. This is my hobby/spare time project. Expecting any kind of professional support is just not how this works. I have done paid consultancy work with OpenVPN in the past but that is also nothing I need to offer to you or anyone else.

**Comment by Deepanshusuman** [comment]
i am sorry
