### ISSUE TITLE
Dark mode or different coloring scheme

### ISSUE THREAD

**Issue by SimpleJack01** [schwabe/ics-openvpn#1519]
I'd apreciate a dark mode or different coloring scheme.

Current white/grey selection schrne nay work well enough  for android phones/tablets, but not fro Android TVs where the grey highlight/selection is barely noticeable. It is workable but not noticeable for people with some vision issues.

**Comment by schwabe** [comment]
the app already implements dark mode.

**Comment by SimpleJack01** [comment]
Sorry,  my bad, then I just don't know how to turn it on on Chromecast with Google TV device with Android 10... Bummer.
Android app does, however, follow the system wide setting. It would be nice if this dark mode  option was user controlled in settings.
