### ISSUE TITLE
Android TV Compatibility request

### ISSUE THREAD

**Issue by SimpleJack01** [schwabe/ics-openvpn#1520]
Currently the app is workable for android TV but has its quirks:

- hard to operate by a remote, not all fields are directly accessible in a row by using d-pad remote arrows unless using a special combination of up/down/left/right/go back/return buttons.
- the "back" button doesn't always work reliably i  certain menu contexts. 
- best would be to design the menu order selection sequence with chromecast with Google TV remote in mind (i am using it there, but teaching some of my family members how to operate it is a major pain) 
- white/grey field selection coloring makes it hard to see which menu option is currently selected,  especially for people with vision issues. Dark mode would be preferred. 
- app lacks an easily accessible on/off toggle(s) for saved configurations or ever a main start/stop toggle for for default connection that can be jumped to easily by using the remote from the main app screen (on andrioud phone/tabket this feature is relatively well accomplished  with 5he use of quick panel buttons, however android TV like Chromecast with Google TV (what a mouthful!)  doesn't have such feature. Hence the need for some connection toggles in the main app screen)

Those are just couple of suggestions, as your VON client is practically the only OpenVPN app one allowing to watch remote region-restricted content on Android TVs AND ONE THAT WORKS WITH CHROMECAST CASTING FEATURE 
(still quirky, but I was able to make it work by making both Android phone and chromecast dongle connect to the VPN server and specify to Routing/IPv4/Exclude Network“ to ignore local network on the Chromecast Google TV dongle running Android 10). Interestingly, somehow "Routing/Bypass VPN for local networks" option doesn't seem to work for chromecast at all - is this a bug?).

**Comment by schwabe** [comment]
Duplicate see the other tickets for Android TV support. Short answer: this is a spare time project and Android TV support is not very on my priority and I spend the time I have to spend to on the app on other things.
