### ISSUE TITLE
Notifications off on android 13

### ISSUE THREAD

**Issue by canary5** [schwabe/ics-openvpn#1521]
# General information
1. Android 13
2. Graphene OS
3. Pixel 6A
4. 0.7.39
 
# after upgrading to android 13 notifications are off and greyed out. Cant enable in main settings as well. Clearing storage or reinstalling doesnt help

**Comment by schwabe** [comment]
Fixed in 017b3f39c2368a41012c0c6a1f000858b305b1d3.

**Comment by schwabe** [comment]
Use the non beta version 0.7.38 to avoid that issue.
