### ISSUE TITLE
option error : UNKNOWN/UNSUPPORTED OPTIONS

### ISSUE THREAD

**Issue by amirm20** [schwabe/ics-openvpn#1529]
# General information
1. ics-openvpn Version : 0.7.41
2. Android version : Android 11
3. Device Xiaomi 
 
# Description of the issue
When connecting start, it gives a connection error and Openvpn3 thread finished. My config file works very well in "OpenVPN Connect" android app.

# Log (if applicable)
20:46 connect() error: : option_error: sorry, unsupported options present in configuration: UNKNOWN/UNSUPPORTED OPTIONS

# Configuration file

```
client
dev tun
proto udp
remote 102.129.145.98 1198
resolv-retry infinite
nobind
persist-key
persist-tun
cipher aes-128-gcm
ncp-disable
tls-client
remote-cert-tls server
auth-user-pass
compress
verb 1
reneg-sec 0
<crl-verify>
-----BEGIN X509 CRL-----
MIICWDCCAUAwDQYJKoZIhv.......(Summarized)
-----END X509 CRL-----
</crl-verify>

<ca>
-----BEGIN CERTIFICATE-----
MIIFqzCCBJOgAwIBAgIJ............(Summarized)
-----END CERTIFICATE-----
</ca>

disable-occ

```

**Comment by schwabe** [comment]
If you look at the full output you will see;

```
Tue Sep 13 23:28:05.468 2022 Unsupported option (ignored)
Tue Sep 13 23:28:05.468 2022 4 [resolv-retry] [infinite]
Tue Sep 13 23:28:05.468 2022 6 [persist-key]
Tue Sep 13 23:28:05.468 2022 7 [persist-tun]
Tue Sep 13 23:28:05.468 2022 17 [disable-occ]
Tue Sep 13 23:28:05.468 2022 UNKNOWN/UNSUPPORTED OPTIONS
Tue Sep 13 23:28:05.468 2022 9 [ncp-disable]
```

`ncp-disable` was debug option in OpenVPN 2.4 that has also been removed from OpenVPN 2.x (see also https://github.com/OpenVPN/openvpn/blob/master/Changes.rst) 

So the behaviour you are seeing is intended and correct behaviour.

**Comment by amirm20** [comment]
> If you look at the full output you will see;
> 
> ```
> Tue Sep 13 23:28:05.468 2022 Unsupported option (ignored)
> Tue Sep 13 23:28:05.468 2022 4 [resolv-retry] [infinite]
> Tue Sep 13 23:28:05.468 2022 6 [persist-key]
> Tue Sep 13 23:28:05.468 2022 7 [persist-tun]
> Tue Sep 13 23:28:05.468 2022 17 [disable-occ]
> Tue Sep 13 23:28:05.468 2022 UNKNOWN/UNSUPPORTED OPTIONS
> Tue Sep 13 23:28:05.468 2022 9 [ncp-disable]
> ```
> 
> `ncp-disable` was debug option in OpenVPN 2.4 that has also been removed from OpenVPN 2.x (see also https://github.com/OpenVPN/openvpn/blob/master/Changes.rst)
> 
> So the behaviour you are seeing is intended and correct behaviour.

yes, that's right. thank you
