### ISSUE TITLE
bindService always returns false

### ISSUE THREAD

**Issue by gityms123** [schwabe/ics-openvpn#1533]
private void bindService() {

        Intent icsopenvpnService = new Intent(IOpenVPNAPIService.class.getName());
        icsopenvpnService.setPackage("de.blinkt.openvpn");

        bindService(icsopenvpnService, mConnection, Context.BIND_AUTO_CREATE);
    }

The above method always returns false when running remoteExample
, the binding can be successful only when the openvpn official apk is running

**Comment by schwabe** [comment]
Yes. The remote example is an example to control the app. So the app needs to be installed. The code to check if the app is installed would probably be there in a real application but the remoteExample does not use that code to be simple.
