### ISSUE TITLE
vpn for Summoners war game

### ISSUE THREAD

**Issue by Gambiarralivre** [schwabe/ics-openvpn#1537]
hello i hope you read this email and can answer me. I'm not a developer, just a user I would like to create a vpn for my game "Summoners war" where my characters get stronger but I don't know how to do it, I've looked in every way possible. I recently bought a vpn like this with a duration of a week but I didn't want to pay for it since you guys make this system available for free so can you help me with this project?

**Comment by schwabe** [comment]
I cannot help you with that, please as the one you bought the VPN from for support.
