### ISSUE TITLE
Openvpn refuses to operate when wifi & mobile broadband are both switched off

### ISSUE THREAD

**Issue by bruceleerabbit** [schwabe/ics-openvpn#1540]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 5.1.1
2. Android Vendor/Custom ROM stock
3. Device obscure
4. Version of the app (version number/play store version/self-built) fdroid/0.7.41
 
# Description of the issue
Openvpn assumes that if there is no wifi connection & no mobile broadband connection, then there must be no connection at all. When in fact an internet uplink can go over USB. It is described in the 2016 [guide on reverse tethering over USB using openvpn](http://salutepc.altervista.org/usb-reverse-tethering-no-root-no-adb-android-all-versions-linux-quick-mode.html).  Because of that limitation, users are forced to establish a fake connection using either wifi or an unwanted connection to mobile broadband.

**Comment by schwabe** [comment]
You can toggle the behaviour to listen to network state events in the general settings.

**Comment by bruceleerabbit** [comment]
> You can toggle the behaviour to listen to network state events in the general settings.

Do you mean the “Reconnect on network change” option under “settings» Application behaviour”?  I already have that unticked (as instructed by the reverse tethering guide). And with that unticked, I 1st attempted to connect with wifi disabled and openvpn would not even attempt it. I had to enable a bogus wifi connection to make any progress.

**Comment by pantgr** [comment]
Classic error i have see this error on lot china box like x96 air etc ,  wen get connected disconnect the Ethernet and looping , not a single error on log ,connected successfully and the box Ethernet reset , this problem exist in years .... If connect any wifi network works as expected

**Comment by schwabe** [comment]
@pantgr I don't have anything that misreports Ethernet status. Both my Nvidia Shield and my Google TV with Ethernet adapter reprots the Ethernet status correctly.

**Comment by pantgr** [comment]
@schwabe  go on settings > network... , and check the lan ip address , disappear for 1 sec and then cam back, is not a hardware reset i thing

**Comment by schwabe** [comment]
@pantgr no idea about that device, sorry. My devices don't exhibit that behaviour
