### ISSUE TITLE
Replace github

### ISSUE THREAD

**Issue by bruceleerabbit** [schwabe/ics-openvpn#1542]
# Description of the issue
A large part of the openVPN userbase are those who value privacy. Microsoft is an adversary of the free world & privacy activists should not be forced into a walled-garden of MS assets in order to report bugs on tools that provide privacy. There are [copious privacy and ethical problems](https://git.sdf.org/humanacollaborator/humanacollabora/src/branch/master/github.md) with MS Github. Please consider migrating to a less controversial alternative. Have a look at the [list](https://git.sdf.org/humanacollaborator/humanacollabora/src/branch/master/forge_comparison.md) of alternatives.

**Comment by schwabe** [comment]
You can still reach me via email if you really want to avoid Github. Otherwise, Since this is a spare time  where my time is limited I rather spend my time developing the software than spending on trying to figure out how to change to a different platform.
