### ISSUE TITLE
not supported in Android 13

### ISSUE THREAD

**Issue by ajithkumar78** [schwabe/ics-openvpn#1547]
Hi,
I am used to this library not supported by Android version 11,12,13 Error On Service Class Any one fix this issue
Thanks 
Ajithkumar
![Screenshot (1)](https://user-images.githubusercontent.com/88201741/196427529-9e5715b0-f560-40cc-870f-1adf3b8ee22b.png)

**Comment by schwabe** [comment]
com.pakistan.vpn.free is not my app. And this is an app and not a library. Did you publish the source code of that app?

**Comment by ajithkumar78** [comment]
no

**Comment by schwabe** [comment]
@ajithkumar78 I request that you publish the source code of that app. My app is under the GPL, which means that your app is now also under the GPL.
