### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by bubuleur** [schwabe/ics-openvpn#1550]
Hello,
I come to you about the French translation of your application (OpenVpn for android) I downloaded the latest version and there are a lot of untranslated words in the applications, I looked on crowdin and the sentences are translated why are they not in the application?
Thank you in advance for your answer

_Originally posted by @bubuleur in https://github.com/schwabe/ics-openvpn/discussions/1549_

**Comment by schwabe** [comment]
please don't spam. the project.
