### ISSUE TITLE
Defective OpenSSL Version (OpenSSL 1.1.1g) 

### ISSUE THREAD

**Issue by Prithivi001** [schwabe/ics-openvpn#1553]
Defective OpenSSL Version (OpenSSL 1.1.1g) 

![194045849-63ec0d81-fa72-49bb-bfef-5c4e43126da2](https://user-images.githubusercontent.com/99128537/198815404-6c212925-ef4d-4a83-8916-e0ca92af469c.png)

I have this error on the Google Play Console. Does anyone know how to update the OpenSSL Version?

**Comment by schwabe** [comment]
That has nothing to do with my project.

**Comment by voliothonh** [comment]
@Prithivi001 Your issue is resolve?

**Comment by Prithivi001** [comment]
What kind of app you have ? Send me link.

**Comment by Prithivi001** [comment]
yes bro. its resolve. thank you
