### ISSUE TITLE
Unable to update openssl submodule to specified commit

### ISSUE THREAD

**Issue by syphyr** [schwabe/ics-openvpn#1556]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. 7.1
2. LineageOS
3. T813
4. self-built
 
# Description of the issue

Commit 10f15bcb601aa200a9162ea984b7030cfb6ed1e4 fails to update openssl submodule to ebef1f3e1bac24605353ecb171e24ac9a9fc5bb1

It appears the latest changes to the openssl submodule still need to be pushed.

fatal: reference is not a tree: ebef1f3e1bac24605353ecb171e24ac9a9fc5bb1

# Log (if applicable)

```
fatal: remote error: upload-pack: not our ref ebef1f3e1bac24605353ecb171e24ac9a9fc5bb1
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'main/src/main/cpp/openssl', but it did not contain ebef1f3e1bac24605353ecb171e24ac9a9fc5bb1. Direct fetching of that commit failed.
```

# Configuration file

```
add the contents of the configuration file if applicable
be careful to not post private keys
```

**Comment by licaon-kter** [comment]
Seeing the same on F-Droid: https://gitlab.com/fdroid/fdroiddata/-/jobs/3262495103#L214

/LE: https://gitlab.com/fdroid/fdroiddata/-/commit/0d0237a2d18e8be24f14cc90aac686ff05a870df

**Comment by schwabe** [comment]
should be fixed now

**Comment by licaon-kter** [comment]
Confirmed, thanks https://gitlab.com/fdroid/fdroiddata/-/commit/4b3432b1a6eb307726e6ec4a88ded8c555a33f4b

**Comment by licaon-kter** [comment]
seeing this again https://gitlab.com/fdroid/checkupdates-bot-fdroiddata/-/jobs/11655534265#L455

**Comment by schwabe** [comment]
I pushed the sub repos a bit later. It should work now, the failing commit is there on Github: https://github.com/schwabe/openvpn/commit/9d0489465dd2c42453232587b977e75477b56f8c 

can you just retry the build?
