### ISSUE TITLE
Defective OpenSSL Version (OpenSSL 1.1.1g)

### ISSUE THREAD

**Issue by mostafizurmaruf** [schwabe/ics-openvpn#1560]
Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.

**Comment by schwabe** [comment]
Can you be more specific? Where are you seeing this error message. And why do you have OpenSSL 1.1.1g in the title of the issue. The app has been not using that version since two years.
