### ISSUE TITLE
Android 11's VPN button only opens the app

### ISSUE THREAD

**Issue by EmiliaTheGoddess** [schwabe/ics-openvpn#1566]
Using the button from the top menu only opens the app as if I opened it from the launcher and doesn't actually connect to the VPN itself. I've set the default VPN from settings. Turning off an already existing connection works as intended though. Isn't this button supposed to act like how wifi and bluetooth does and just enable the VPN in background or am I missing something? I'm not very knowledged about Android 11.

![Screenshot_20221212-015339_GitHub.png](https://user-images.githubusercontent.com/43678100/206933811-6148df21-732e-489d-93a2-8c1bbd2aa6ae.png)

**Comment by schwabe** [comment]
I am not sure how to get that VPN Quicktile. The quick tile from my own app has the icon of my own app. Is that maybe a quick tile for a VPN configured via Android's own VPNs?

**Comment by EmiliaTheGoddess** [comment]
I didn't notice the app added another tile, I though the name quick tile in settings was referencing this. Your tile works just as I wanted. Thanks for the help and sorry for wasting your time.

**Comment by ChrisPHL** [comment]
I encountered exactly the same problem since I upgraded from Android 10 to Android 11. While the "original" VPN button (showing just a key)  works as @EmiliaTheGoddess  intended, it does not for Android 11 anymore.
The workaround using OVPN's very own quick settings tile is sufficient though.
