### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by Nishantbish** [schwabe/ics-openvpn#1579]
![Screenshot_2023-02-04-16-33-15-220_com.offsec.nethunter.store.jpg](https://user-images.githubusercontent.com/108564417/216763583-8e6f6015-db65-4df7-8b9e-bbfd9e1afe7a.jpg)

**Comment by schwabe** [comment]
I am not sure what you are using there. The icon looks completely wrong and the last updated is also wrong. What kind of store is this?
