### ISSUE TITLE
IV_HWADDR not received by server

### ISSUE THREAD

**Issue by flucas1** [schwabe/ics-openvpn#1584]
Hello,

The mobile app does not transmit/set IV_HWADDR even if "setenv IV_HWADDR" line is assigned.

The desktop version of openvpn properly pushes IV_HWADDR to the server.

**Comment by schwabe** [comment]
That is not a bug. The app generates the HWADDR itself.

**Comment by flucas1** [comment]
Yes, the app generates the HWADDR value in the config file... but the server does not receive it.
Also, as per specification, setenv IF_<value> should be transferred, but it is not happening.

**Comment by schwabe** [comment]
you need push-peer-info for that.

**Comment by flucas1** [comment]
that flag is used, and this is why I raise this as a bug

**Comment by schwabe** [comment]
This address is only used if the app can get a hardware ID from the OS. What Android version and device are you using?

**Comment by flucas1** [comment]
I edited teh HWADDR


# Config for OpenVPN 2.x
# Enables connection to GUI
management /data/user/0/de.blinkt.openvpn/cache/mgmtsocket unix
management-client
management-query-passwords
management-hold

setenv IV_GUI_VER "de.blinkt.openvpn 0.7.43"
setenv IV_SSO openurl,webauth,crtext
setenv IV_PLAT_VER "33 13 arm64-v8a Xiaomi lisa 2109119DG"
setenv IV_HWADDR XX:XX:XX:XX:XX:XX:XX
tls-cert-profile preferred
machine-readable-output

**Comment by schwabe** [comment]
The feature currently only works if you select OpenVPN 3 core under general settings. The `setenv IW_HWADDR` is ignored by OpenVPN 2.x
