### ISSUE TITLE
Logs are not shown

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#1585]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android 13
2. ASUS
3. Zenfone 9
4. 0.7.43
 
# Description of the issue

At "PROFILES" screen, when touch the profile, start connecting but logs are not shown.

# Log (if applicable)

```
```

# Configuration file

```
```

**Comment by schwabe** [comment]
The log is available as extra window. And you can toggle if that window is shown by default under general settings.
