### ISSUE TITLE
Files are not shown with the X-plore app when connect

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#1586]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android 13
2. ASUS
3. Zenfone 9
4. 0.7.43
 
# Description of the issue

After connected to LAN via OpenVPN for Android, to seek the SMB sharing files I start X-plore app, but files are not shown.

# Log (if applicable)

```
```

# Configuration file

```
```

**Comment by schwabe** [comment]
that is a problem of the other app or the VPN configuration.
