### ISSUE TITLE
Defective OpenSSL Version 1.1.1d in lib/x86/libopenvpn.so

### ISSUE THREAD

**Issue by Sari-Belouni** [schwabe/ics-openvpn#1587]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
4. Version of the app (version number/play store version/self-built)
0.7.13

# Description of the issue

Google play showing this error after 
Defective OpenSSL Version
Your app uses a defective version of the OpenSSL library, which can cause your app to crash. Update to a fixed version of OpenSSL.

Defective versions:
OpenSSL 1.1.1d in lib/x86/libopenvpn.so

Google play suggest to update the openssl to OpenSSL 1.1.1i or higher
https://support.google.com/faqs/answer/12576638

![openssl error](https://user-images.githubusercontent.com/47521579/222957854-9f7cbc46-d3cc-4aa6-af17-e20b7eac3c77.PNG)

I searched is solved issues but couldn't find relative issues and if it has been fixed or not in later version I know the version I have at the moment is quit old please let me know if you have fixed it or need the issue still present in the latest version.

**Comment by schwabe** [comment]
sorry but what app is that and where is the source code of it? I don't think that is my app.

**Comment by Sari-Belouni** [comment]
I have create an free vpn application and used your app as module, your app version is used as module in my app is version 0.7.13, that why I posted it here

**Comment by schwabe** [comment]
@Sari-Belouni can you please share the source code of your app? Your App needs to comply with the GPL2.
