### ISSUE TITLE
Configuration file not found

### ISSUE THREAD

**Issue by likeSnake** [schwabe/ics-openvpn#1592]
# Description of the issue
I downloaded the source code from GitHub and ran it directly on Android Studio, and it prompted me：

“CMake Error at CMakeLists.txt:31 (include):
include could not find load file:
openssl/openssl.cmake”

I don't really know what this file does. I looked for configuration tutorials on the OpenVPN website, but due to my stupidity, I didn't find how to develop using OpenVPN source code in Android. I'm a college student and I want to learn more and write small projects in my spare time, and I would appreciate it if you knew what the problem was, or if you could tell me the address of the relevant tutorial

# Log 

```
![image](https://user-images.githubusercontent.com/86227653/224920709-623887da-70aa-447c-8f7b-6491e3853045.png)
```

**Comment by schwabe** [comment]
you failed to also clone the submodules
