### ISSUE TITLE
Unrecognized option or missing or extra parameter(s) in stdin:98: block-outside-dns (2.7_master)

### ISSUE THREAD

**Issue by SoNic1967** [schwabe/ics-openvpn#1598]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 13
2. Android Vendor/Custom ROM One UI 5.1
3. Device Galaxy S22+ , SM-S906U1
4. Version of the app (version number/play store version/self-built)
 Google Play
# Description of the issue

# Log (if applicable)

```
Unrecognized option or missing or extra parameter(s) in stdin:98: block-outside-dns (2.7_master)
```

# Configuration file

```
add the contents of the configuration file if applicable
be careful to not post private keys
```

**Comment by schwabe** [comment]
This is a windows only option. So the Android app (or any other platform that is not windows) does not support it.
