### ISSUE TITLE
specialUse is incompatible with attribute foregroundServiceType

### ISSUE THREAD

**Issue by syphyr** [schwabe/ics-openvpn#1607]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: Nougat
2. Custom ROM: LineageOS 14.1
3. Device: T813
4. Version of the app: v0.7.44-1-g82695133
 
# Description of the issue

Build failure on Master branch from 6871a5a4734890e7b5e01040a38fb34b0a05a9fc

# Log (if applicable)

```
Execution failed for task ':main:processSkeletonReleaseResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     /media/delta/T5/android/openvpn/ics-openvpn/main/build/intermediates/packaged_manifests/skeletonRelease/universal/AndroidManifest.xml:70: error: 'specialUse' is incompatible with attribute foregroundServiceType (attr) flags [camera=64, connectedDevice=16, dataSync=1, location=8, mediaPlayback=2, mediaProjection=32, microphone=128, phoneCall=4].
     error: failed processing manifest.
```

# Configuration file

```
NA
```

**Comment by schwabe** [comment]
Yes the commited code is already for upsidedowncake api. It currently does not build with lower version APIs anymore for that reason.

**Comment by syphyr** [comment]
What is the new minimum api?

**Comment by schwabe** [comment]
mimimum API stays the same, just the target API I am currently testing with is upsidedowncake (Android 14)
