### ISSUE TITLE
Grant external app access to control OpenVPN without showing the permission dialog

### ISSUE THREAD

**Issue by usfaa444** [schwabe/ics-openvpn#1610]
# General information
1. Android Version: 11
2. Device: Custom device built by a vendor, running Android On it
3. Version of the app: 0.7.0 (seems to be the only version working with our devices so far)
 
# Description of the issue
So we have our devices already installed on client side, and our app on these devices doesn't have access to control OpenVPN externally via AIDL. We need to grant our app access to be able to do so, but without showing the dialog that is requesting permission to grant external app access, because we do not want a manual click on the UI for this process because the client devices are many of them and we have to connect a keyboard or mouse to each of them and grant the permission manually. 
Is there a way to give our app permission to control OpenVPN externally viad AIDL without showing any dialog to requests the permission? without having to interact with the UI ?

**Comment by schwabe** [comment]
The reason that a permission is shown is to protect from other apps. I don't want random apps to be able to control my app without the user's consent. If there is some way that is safe, e.g. like reading from a system service or some other way to get "system allowed" remote apps that can be certainly be implemented. Also providing a list of allowed AIDL apps by app restrictions would work.

**Comment by usfaa444** [comment]
I get your point, but sorry I'm not sure I understood what you said when you are talking about reading from system service or way to get "system allowed" remote apps, could you clarify it a bit more please ?

**Comment by schwabe** [comment]
If you are running a custom rom or similar you might be provide a way to tell the app that you allow remote access that would normally not possible without such a rom. Might be also to check if an app holds some permission that is only granted to high privilege apps like device owner/mdm apps.

**Comment by usfaa444** [comment]
So what you're saying is that if I have a custom rom then I can have a way to tell the OpenVPN that I allow remote access without having to face a permissions fialog popping out?

**Comment by schwabe** [comment]
That would certainly doable. Or app restrictions/MDM would also work.

**Comment by usfaa444** [comment]
I just took a look at application restrictions you mentioned, I had no knowledge of that but with that, one can change an app settings or configuration. 
I have also checked and seems that application restrictions is not implemented in the OpenVPN version 0.7.0,  only in the latest version, which is also not supported by our application unfortunately. 

So my only option is the first one you mentioned, do yoy have any clue on that option? How can I achieve that if I have a custom rom?

**Comment by schwabe** [comment]
All the options I mentioned would require a new version of the app since none of that is already implemented. Keep in mind that 0.7.0 is really old and contains a vulnerable OpenSSL version as well. It is probably a good idea to figure out why newer versions fail on your devices.

**Comment by usfaa444** [comment]
Yes, I think this shoul be the right thing to do.
Thank you for all the valuable information you provided, I will try to figure out why the recent version doesn't work with our devices and try to correct that, this way I will be able to use application restrictions. 
Thank you for your precious time. Really appreciate it.
