### ISSUE TITLE
Release 0.7.48 apk does not support managed config

### ISSUE THREAD

**Issue by M1-K** [schwabe/ics-openvpn#1630]
I'm using MDM/EMM tool Soti Mobicontrol that supports managed config even for "private" apps and when I've tried to use latest version it didn't show any options for "managed config" - previous version 0.7.46 works as expected and I wasn't able test managed Google Play yet as I see only old version (0.7.43) there.

P.S: thank you for great work

**Comment by schwabe** [comment]
How did you install the app? When trying on my test deviced with the TESTDPC app it works just fine:

![Screenshot_20230802_104424](https://github.com/schwabe/ics-openvpn/assets/1038539/b5a892bd-a55e-4efa-9033-b943e912bcee)
