### ISSUE TITLE
TunnelCrack

### ISSUE THREAD

**Issue by Minalinsky007** [schwabe/ics-openvpn#1632]
It is somehow affect your app? Sorry for dumb question I'm not super tech man

**Comment by schwabe** [comment]
If you enable to not block local network if you are affected. Otherwise not.

**Comment by Minalinsky007** [comment]
> If you enable to not block local network if you are affected. Otherwise not.

"Bypass VPN for local network" I should disable this setting to not being affected, right?

**Comment by schwabe** [comment]
yes
