### ISSUE TITLE
How to install the library in my project 

### ISSUE THREAD

**Issue by navneetkumarpal** [schwabe/ics-openvpn#1633]
I am trying to install library main as a module in my project but I am getting run time error please can someone tell me what are dependencies required and what are the steps to import it as a module.

**Comment by schwabe** [comment]
This is NOT a library. This is an app that provides OpenVPN for Android. Trying to use another app as module will naturally not work.

**Comment by navneetkumarpal** [comment]
Is there any official library available of openvpn which I can use in my project in Android studio

**Comment by schwabe** [comment]
No. The OpenVPN project does not offer any official Android library. Even this app is only close to being an official app. It is maintained by me, an OpenVPN developer. But it is not maintained by the open source project itself.
