### ISSUE TITLE
Large App size during app bundle reease

### ISSUE THREAD

**Issue by Arunachalamkalimuthu** [schwabe/ics-openvpn#1641]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

1. Android Version 33

 
# Description of the issue

build configuration

```

  externalNativeBuild {
            cmake {

            }
        }
        ndk {
            abiFilters += listOf("x86", "x86_64", "armeabi-v7a", "arm64-v8a")
        }
        packagingOptions {
            jniLibs {
                useLegacyPackaging = true
            }
        }

```

Bundle configuration
```
  bundle {
        language {
            enableSplit = true
        }
        density {
            enableSplit = true
        }
        abi {
            enableSplit = true
        }
    }

```

<img width="1323" alt="Screenshot 2023-09-03 at 1 53 55 PM" src="https://github.com/schwabe/ics-openvpn/assets/43308215/7090a677-3427-4689-aa9e-104c277753a5">
lt)

<img width="1323" alt="Screenshot 2023-09-03 at 1 54 36 PM" src="https://github.com/schwabe/ics-openvpn/assets/43308215/7859f00e-71c4-4726-ad1b-113ca4042a6f">

**Comment by schwabe** [comment]
What is the actual problem here? These settings are already true by default. See also https://developer.android.com/guide/app-bundle/configure-base

Apart from language but enabling that won't make much difference and also break language switching.

**Comment by Arunachalamkalimuthu** [comment]
Its 35 MB app size, i wanted to reduce it, please help me on this

**Comment by schwabe** [comment]
That is what my app is in size. I don't plan to do anything about that.
