### ISSUE TITLE
GET_CONFIG TO Connected use 1min

### ISSUE THREAD

**Issue by tt2nn** [schwabe/ics-openvpn#1647]
Hi，When I Connected Server
Sometimes Process at GET_CONFIG Then 1min Can Connected 
------------------------
Client Log:
...
Aession si ACTIVE
Sending PUSH_REQUEST to Server...
EVENT：GET_CONFIG
Sending PUSH_REQUEST to Server...
Sending PUSH_REQUEST to Server...
Sending PUSH_REQUEST to Server...
... 
---------------------
Server Log:
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 UDPv4 READ [1206] from [AF_INET]203.145.95.23:39837: P_CONTROL_V1 kid=0 [ ] pid=1637 DATA len=1192
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 VERIFY OK: depth=1, CN=DO-VPN CA
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 VERIFY OK: depth=0, CN=00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 UDPv4 WRITE [224] to [AF_INET]203.145.95.23:39837: P_CONTROL_V1 kid=0 [ ] pid=1893 DATA len=210
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 UDPv4 READ [463] from [AF_INET]203.145.95.23:39837: P_CONTROL_V1 kid=0 [ ] pid=1893 DATA len=449
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_VER=2.7_master
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_PLAT=android
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_TCPNL=1
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_MTU=1600
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_NCP=2
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_CIPHERS=AES-256-GCM:AES-128-GCM:CHACHA20-POLY1305
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_PROTO=470
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_LZO_STUB=1
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_COMP_STUB=1
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_COMP_STUBv2=1
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_GUI_VER=com.demo.lht.openvpn2_1.0
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 peer info: IV_SSO=openurl,webauth,crtext
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 WARNING: 'cipher' is present in local config but missing in remote config, local='cipher AES-256-CBC'
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 UDPv4 WRITE [287] to [AF_INET]203.145.95.23:39837: P_CONTROL_V1 kid=0 [ ] pid=2149 DATA len=273
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 UDPv4 READ [78] from [AF_INET]203.145.95.23:39837: P_ACK_V1 kid=0 [ ]
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 UDPv4 READ [82] from [AF_INET]203.145.95.23:39837: P_ACK_V1 kid=0 [ ]
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 Control Channel: TLSv1.3, cipher TLSv1.3 TLS_AES_256_GCM_SHA384, 2048 bit RSA
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 203.145.95.23:39837 [00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7] Peer Connection Initiated with [AF_INET]203.145.95.23:39837
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837 MULTI_sva: pool returned IPv4=10.8.0.2, IPv6=(Not enabled)
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: date: extra operand '%H:%M:%S'
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: Try 'date --help' for more information.
Sep 21 06:52:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837 OPTIONS IMPORT: reading client specific options from: /tmp/openvpn_cc_3da5e5f930c86e95330aeb161dbdc384.tmp
Sep 21 06:52:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837 MULTI: Learn: 10.8.0.2 -> 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837
Sep 21 06:52:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837 MULTI: primary virtual IP for 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837: 10.8.0.2
Sep 21 06:52:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837 UDPv4 READ [113] from [AF_INET]203.145.95.23:39837: P_CONTROL_V1 kid=0 [ ] pid=2661 DATA len=99
Sep 21 06:52:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837 PUSH: Received control message: 'PUSH_REQUEST'
Sep 21 06:52:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837 SENT CONTROL [00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7]: 'PUSH_REPLY,redirect-gateway def1 bypass-dhcp,dhcp-option DNS 8.8.8.8,dhcp-option DNS 8.8.4.4,block-outside-dns,route-gateway 10.8.0.1,topology subnet,ping 10,ping-restart 120,ifconfig 10.8.0.2 255.255.255.0,peer-id 0,cipher AES-256-GCM' (status=1)
Sep 21 06:52:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837 Data Channel: using negotiated cipher 'AES-256-GCM'
-------------------------------------
there use 1min，but without any log.
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: date: extra operand '%H:%M:%S'
Sep 21 06:51:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: Try 'date --help' for more information.
Sep 21 06:52:19 openvpn-node-test-us-west2-c-2 openvpn[28755]: 00000000-2b1c-0c4c-ffff-ffffef05ac4a63eb3f0815e2d2b7/203.145.95.23:39837 OPTIONS IMPORT: reading client specific options from: /tmp/openvpn_cc_3da5e5f930c86e95330aeb161dbdc384.tmp

----------------------------------------
this problem about networks？or other reason？

Thinks

**Comment by schwabe** [comment]
This sounds like a server side script that hangs.

**Comment by schwabe** [comment]
Also this is not about my app. The client identifies itself as `com.demo.lht.openvpn`
