### ISSUE TITLE
NDK - ABI Filters

### ISSUE THREAD

**Issue by Arunachalamkalimuthu** [schwabe/ics-openvpn#1649]
Why do we need to mention the abi filters of "x86", and "x86_64" in the gradle file? since all mobile architecture supports only the following abis "armeabi-v7a", "arm64-v8a"?

**Comment by schwabe** [comment]
I still want to continue to support those platforms even if it is a niche.

**Comment by Arunachalamkalimuthu** [comment]
@schwabe Can you confirm whether App will still work if I remove those nbi filters which doesn't belong to mobile architecture

**Comment by schwabe** [comment]
I never tested that.
