### ISSUE TITLE
VPN won't start form 'Quick Menu' button

### ISSUE THREAD

**Issue by xJib** [schwabe/ics-openvpn#1652]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version = 14
2. Android Vendor/Custom ROM = Google
3. Device = Pixel 5
4. Version of the app (version number/play store version/self-built) = 0.7.49
 
# Description of the issue
I've just upgraded my Pixel 5 to Android 14 and I'm getting the following issue.

If I press on the 'Connect to [VPN Name]' in the Quick Menu the button doesn't start the VPN. 

If I long press and open the app then it works as expected with the VPN connection and function as expected.

Thanks

**Comment by schwabe** [comment]
Yes. I can reproduce this:

`
10-05 12:46:08.518  1714  5520 W ActivityTaskManager: Background activity launch blocked [callingPackage: de.blinkt.openvpn; callingUid: 10395; appSwitchState: 2; callingUidHasAnyVisibleWindow: false; callingUidProcState: CACHED_EMPTY; isCallingUidPersistentSystemProcess: false; balAllowedByPiSender: BackgroundStartPrivileges[allowsBackgroundActivityStarts=false, allowsBackgroundForegroundServiceStarts=true, originatingToken=null]; realCallingPackage: de.blinkt.openvpn; realCallingUid: 10395; realCallingUidHasAnyVisibleWindow: false; realCallingUidProcState: CACHED_EMPTY; isRealCallingUidPersistentSystemProcess: false; originatingPendingIntent: null; backgroundStartPrivileges: BackgroundStartPrivileges[allowsBackgroundActivityStarts=false, allowsBackgroundForegroundServiceStarts=false, originatingToken=null]; intent: Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=de.blinkt.openvpn/.LaunchVPN (has extras) }; callerApp: ProcessRecord{f4c85f5 16298:de.blinkt.openvpn/u0a395}; inVisibleTask: false]
`
