### ISSUE TITLE
WebView not using new IP from VPN

### ISSUE THREAD

**Issue by einsze** [schwabe/ics-openvpn#1656]
anyone know why WebView not using new IP from VPN ? on other apps like google chrome etc its working fine.. but on webview its not using new IP from VPN... i've no clue at all about this,, i really appreciated for the answer...

**Comment by schwabe** [comment]
What do you mean with WebView? A webview is part of an app, so it should use it like anything else from the app. There is nothing special about it.

**Comment by einsze** [comment]
omg.. thankyou for answering me sir... i mean that WebView still using original IP even the VPN is already activated i dont know why this happen... there's no error log... i check it on 'whatsmyip' and it still using original IP... thankyou for answering me sir schwabe.... i hope you understand what im talking about.. im so sorry my english really messed up...

**Comment by schwabe** [comment]
You need to provide more details. Webview of what app?

**Comment by einsze** [comment]
yes sir.. the project is my own android client VPN browser using openVPN.. and im using webview for rendering the website.. and VPN connection is already working fine on external browsers... the case is on my webview, the connection on webview is working fine but when i check 'whatsmyip' its still using original IP, so thats mean my VPN Browsers application still using original IP on webview right?... why its not like on external browsers because when VPN is active, its using new IP from the VPN.. i tried asking my friend and my friend answer is webview dont have some config for doin that so the problem is i need to reconfig all connection on android that comes from VPN ?.. thankyou verymuch sir schwabe for helping me... >.< any suggestion sir..?

**Comment by schwabe** [comment]
That is then not my app but a different project/app. Have you opensourced that project? If it is based on my app, then your project needs to be under the GPL2 as well as per the license of my app.

**Comment by einsze** [comment]
ah.. okay sir.. thankyou for your advice.. ^^

**Comment by Khadijaikram** [comment]
how this is issue solved ?

**Comment by schwabe** [comment]
This never was an issue in this project.
