### ISSUE TITLE
Need to implement client to client communication from one android to another android device using vpn network

### ISSUE THREAD

**Issue by saad3344555** [schwabe/ics-openvpn#1662]
I would like to enquire about creating server configuration in android device using your opensource repo. Following are some questions regarding the possibility of the this use case.

1. Is it possible to integrate server configuration file and establish a server on android device on which different clients will be connected?

2. Can we create a socket on vpn connections to listen to the data receive from another client app?

3. Can we communicate between the clients that are connected to the same vpn by means of sockets or anything?

If yes then please explain with any helpful material. Note we cant buy vpn server to achieve this. We need vpn configurations.

We are using ics-openvpn for android

**Comment by schwabe** [comment]
No the Android API for VPN (VPNService) does not allow you to build a VPN server. Best thing you can hope to achieve is a mesh like VPN like Wireguard does. But OpenVPN currently does not implement mesh functionality.
