### ISSUE TITLE
Becomes inactive while in background on some devices

### ISSUE THREAD

**Issue by staydry** [schwabe/ics-openvpn#1664]
Hi!

There are some devices known for freezing all apps in the background. Itel A25 phone is one of those (Android 9 Go). On that device OpenVPN app becomes inactive in the background in few minutes, regardless of whether connection is on and whether traffic goes through it or not.

Power management has nothing to do with that as supposed: all related settings have no influence. That is intended for reducing RAM or CPU consumption probably.

Meanwhile there are apps like media players and antivirus agents that stay active in the background for a long while even on such devices. So there is potentially a way to run your OpenVPN app with same permissions or something in order to keep it alive in the background in any case.

It is not an app itself issue but it would be great if you could dig this: may be small modification could solve above problem for the involved owners. Thanks!

**Comment by schwabe** [comment]
Unless you have any more information how to achieve that, there is nothing I can do about that. I do not have access to these devices and also do not know of any ways that I could do to achieve those. Note that some devices have whitelists of apps that they do not kill. Check also https://dontkillmyapp.com/
