### ISSUE TITLE
how to import and build openvpn as a module in android studio

### ISSUE THREAD

**Issue by mrahnama1370** [schwabe/ics-openvpn#1667]
how can I use OpenVPN in my app? I couldn't use this project as a module in my app.
please describe how to add it as a module and build my project in Android Studio

**Comment by schwabe** [comment]
This is an app and not a module to be used in another app. It is not intended to be used in another app. Also please read the https://github.com/schwabe/ics-openvpn/blob/master/doc/README.txt
