### ISSUE TITLE
Open VPN library for Android

### ISSUE THREAD

**Issue by taher7001120** [schwabe/ics-openvpn#1668]
Can someone explain to me or give me an educational document?  I have an open VPN server and a VPN app.  I searched for a long time on the Internet for the Open VPN library for Android and did not find anything or even an article that taught you how to add and use it.

**Comment by schwabe** [comment]
This is no library. This an app. There are people that forked this app legally and illegally to create another app but this is not a library to build your own app. See the other issues that want a library ad the doc/README as well.

**Comment by taher7001120** [comment]
> هذه ليست مكتبة. هذا التطبيق. هناك أشخاص قاموا بتقسيم هذا التطبيق بشكل قانوني وغير قانوني لإنشاء تطبيق آخر ولكن هذه ليست مكتبة لإنشاء تطبيقك الخاص. راجع المشكلات الأخرى التي تريد أن تعلن المكتبة عن المستند/README أيضًا.



> This is no library. This an app. There are people that forked this app legally and illegally to create another app but this is not a library to build your own app. See the other issues that want a library ad the doc/README as well.

Yes, I saw the Cake vpn project and took the library from it and it works well, but I want to use ics-openvpn because it is updated, but it is different. I still have a question: Are AIDL API classes sufficient to establish a connection from an external application?  Without the CPP folder because it causes me a lot of problems when building
