### ISSUE TITLE
Run on boot independent from Android features?

### ISSUE THREAD

**Issue by frmariam** [schwabe/ics-openvpn#1671]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android 9 (TV ; latest version, July 5, 2020)
2. Android Vendor
3. Device MiTV-MSSP3
4. Version of the app (version number/play store version/self-built) 0.7.50, github release
 
# Description of the issue
My TV Android versions displays no options relating to VPN in Network & Internet settings.
I'd like to connect to my VPN on boot, but the way OpenVPN for Android enables this doesn't work on my device -  I can't enable Always-On.
My VPN provider app also doesn't allow this (at least not if connecting via LAN cable).
Can run on boot be implemented from OS limitations.

VPN working properly if manually enabled in OpenVPN for Android

# Log (if applicable)

```
log contents
```

# Configuration file

```
add the contents of the configuration file if applicable
be careful to not post private keys
```

**Comment by schwabe** [comment]
The current method that I use that is enabled is the best way that I figured would work on Android devices. The OnBootReceiver *should* work. It works on my test Android devies. I don't really have any wacky Android TV devices that I can test on. The only ones that I have are Shield TV and and a chromecast with GOogle TV and both are running fairly recent Android versions (12 or 13 iirc). It works with those devices. If someone contribute code to make on boot work with other devies via pull request I am happy to include that code but I am not able to work on that myself.

**Comment by frmariam** [comment]
Understandable.
Unfortunately My Xiaomi TV is on Android 9 and the settings options are quite lacking...

Thank you for the app!
