### ISSUE TITLE
I do not get the Managed App Config running

### ISSUE THREAD

**Issue by andreashandlerleadit** [schwabe/ics-openvpn#1672]
# General information
1. 13
2. Samsung
3. Ultra 20 5G
4. Current Play Managed Google Play Store Version
 
# Description of the issue
First i took the .OVPN File as Config and excluded the CA in a Certificate file, i deployed to the Device
No matter how i change the UUID, it always says, "You need to fine and enabe at least one remote Server"

Can i also avoid the need of deploying the CA File separatly

Tried several Times. .ovpn File is working using it directly

# Log (if applicable)

```
log contents
```

# Configuration file

<img width="1354" alt="image" src="https://github.com/schwabe/ics-openvpn/assets/44256711/fab5f8e6-325f-490d-9e06-26954c497e6c">

**Comment by schwabe** [comment]
That config files looks like it lost all or most of its newlines in that config editor. 

I do not know your device management system but the (i) button should probably say the description of that field:

 Content of the OpenVPN configuration file. These files are usually have the extension .ovpn (sometimes also .conf) and are plain text multi line configuration files. If your MDM does not support multiline configuration entries, you can also use a base64 encoded string here. A text file can be converted to base64 using openssl base64 -A -in

**Comment by andreashandlerleadit** [comment]
Thanks alt, that has been the issue.
