### ISSUE TITLE
 OpenVPN for Android 0.7.50 and later breaks static key mode

### ISSUE THREAD

**Issue by wico** [schwabe/ics-openvpn#1678]
Just a litte note: Since 0.7.50+, one cannot use the (deprecated) static key mode anymore. This is because the process terminates with an exit 1 when using a config with static key:

`DEPRECATED OPTION: The option --secret is deprecated.`
`DEPRECATION: No tls-client or tls-server option in configuration detected. OpenVPN 2.8 will remove the functionality to run a VPN without TLS. See the examples section in the manual page for examples of a similar quick setup with peer-fingerprint.`
`Use --help for more information.`
`Process exited with exit value 1`

That error is expected ([see openvpn deprecated options](https://community.openvpn.net/openvpn/wiki/DeprecatedOptions#Option:--secretStatus:Deprecatedpendingremoval)) but there is a command-line parameter to re-enable this deprecated feature: `--allow-deprecated-insecure-static-crypto`. 

However, and that is the problem: There is no way to set this option in the android app (and without noodling around with `am` etc.). Or did I miss something? For now, it looks like the last version with static key support is 0.7.49. Newer versions technically would still support static key if there would be a way to pass the above mentioned parameter to the openvpn-process. If I understood it right. :)

**Comment by schwabe** [comment]
You can add the option as custom option under Advanced in an VPN Profile

**Comment by wico** [comment]
Indeed! That works. I dont know why I have not tried it before ... hmmm.

Time for christmas. :)
