### ISSUE TITLE
Do not force VPN when connected to a specific WiFi

### ISSUE THREAD

**Issue by ryosoftware** [schwabe/ics-openvpn#1679]
Hello,
I'm using OpenVPN to connect to my house to access my services: Home Assistant, NextCloud, etc.
But I don't need to use the VPN tunnel  when I'm at my house and connected to my WiFi network.
Is there any chance to add some WiFi networks that disables auto-connect?
Thanks in advance

**Comment by schwabe** [comment]
This is unlikely to come as there is no way for me currently to implement this is a satisfactory way. See also #370

**Comment by ryosoftware** [comment]
Thanks anyway
