### ISSUE TITLE
[help] block connections without vpn & lan connections

### ISSUE THREAD

**Issue by spice42** [schwabe/ics-openvpn#1686]
im unable to connect to lan when i switch on block connections without vpn, i understand this is how it is supposed to work even if i allow lan connections in openvpn

is there a setting in openvpn to allow lan ip connections, when block connections without vpn is turned on, for example specifying a route/subnet

thanks

**Comment by schwabe** [comment]
Are you talking about the system always on vpn setting and the block connection without VPN? If yes, then there is no way around that system wide setting.

**Comment by spice42** [comment]
yes, I was reffering to that, thank you for replying and for your work
