### ISSUE TITLE
Cannot open a Fortinet Compliant VPN

### ISSUE THREAD

**Issue by fedora-mahdi** [schwabe/ics-openvpn#1687]
# General information
1. Android Version: 11
2. Android Vendor: Lenovo (no mod)
3. Device: Lenovo Tab P11 Plus
4. Version of the app (version 0.7.48 f-droid)
 
# Description of the issue
I need to connect to a server (17x.xxx.xxx) on port PPP using a FortiNet compliant protocol through a VPN tunnel.
It requires a user login (USER) and password (PWD)
No user certificate is required.
The server certificate can be ignored, as it happens during connection with the free version of the proprietary FortiClient VPN App

With the credentials above, and without any configuration file, I can put those credentials and connect with ease:
- on the GUI FortiClient VPN app (Windows, Android) 
- or using a command line (Linux: openfortivpn SERVER:PPP -u USER -p PWD) 

With OpenVPN app it always fails with connection error and sometimes certificate errors

I do not understand:
- what I am doing wrong
- or what settings to use and tried to look into any available documentation

If there is any need for a configuration file please indicate how to build and format it

Thank you for help, hints or advices...

**Comment by schwabe** [comment]
My app only supports OpenVPN based servers. Fortinet is not OpenVPN based.
