### ISSUE TITLE
Cannot save changes to profile (no save button)

### ISSUE THREAD

**Issue by derek-shnosh** [schwabe/ics-openvpn#1693]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: **14**
2. Android Vendor/Custom ROM: **Samsung OneUI 6.0**
3. Device: **Samsung S22 Ultra**
4. Version of the app (version number/play store version/self-built): **Play Store 0.7.51**
 
# Description of the issue

I am trying to change the "Connect Timeout" to "0" (was "120") to match my server's settings (no renegotiate), but there is no SAVE button after moving the slider all the way to the left or typing "0" in the text field; see screenshot below.

# Screenshot

![image](https://github.com/schwabe/ics-openvpn/assets/21090563/1fcb7bf8-3b6d-4f31-86eb-b29b262a28d9)

# Log (if applicable)

Log not applicable here.

# Configuration file

Config file not applicable here.

**Comment by schwabe** [comment]
THe app automatically saves changes. The is no save button by design

**Comment by derek-shnosh** [comment]
@schwabe - the changes are not saving automatically for me. I change the value to 0, gesture swipe to the previous screen, click "Edit" again and the timeout is still 120.
