### ISSUE TITLE
Disconnect confirmation

### ISSUE THREAD

**Issue by chiragkrishna** [schwabe/ics-openvpn#1695]
# General information
1. Android Version: Andoird 14
2. Android Vendor/Custom ROM: Samsung OneUI 6.0
3. Device: Galaxy S22+
4. Version of the app: play store: 0.7.51
 
# Description of the issue
Disconnect button on notifications tray is intended to disconnect but results in asking for confirmation, this behaviour is not seen in the quick settings tray.

# Disconnecting from notification panel
![disconnect_notify](https://github.com/schwabe/ics-openvpn/assets/2405186/12067921-c548-45b0-bc2a-09ce18999d1a)

# Results in confirmation pop up
![dissconnect_confirm](https://github.com/schwabe/ics-openvpn/assets/2405186/ffdbcd71-e309-4ab2-a184-95dbb9718f87)

# Disconnecting from notification quick panel works perfectly without any confirmation
![disconnect_quick](https://github.com/schwabe/ics-openvpn/assets/2405186/0973b9e1-e495-4393-9e1b-13afc1318a6a)

**Comment by Mick-Mi** [comment]
yeah I think we don't need the confirmation prompt.

**Comment by schwabe** [comment]
I will keep the confirmation. The extra click should not be that problematic and it has like this forever.

**Comment by chiragkrishna** [comment]
yes, its not problematic, but is a headache for automation. wouldn't hurt to add a dont ask again option though.
