### ISSUE TITLE
Query About licensing

### ISSUE THREAD

**Issue by anshm-2166** [schwabe/ics-openvpn#1698]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
We'd like to know how can we respect the GPL3 license of this repo. 

What are we required to do?
* Should we opensource our modified fork of the library?
* Should we opensource our modified fork of the library along with the implementation in our program.

Also, is there an option to negotiate for licensing in exchange for a fee? Let us know...

**Comment by anshm-2166** [comment]
![image](https://github.com/schwabe/ics-openvpn/assets/149814863/2fdd667c-785e-49d7-9254-8bec0586ceee)
Also, contributor license agreement url is broken

**Comment by schwabe** [comment]
Contact me via email if you want a different license., But yes if you go with GPLv2/GPLv3 you need to have your software also under the GPL which is also means providing the source code of the whole app.

**Comment by anshm-2166** [comment]
> Contact me via email if you want a different license., But yes if you go with GPLv2/GPLv3 you need to have your software also under the GPL which is also means providing the source code of the whole app.

Thank you for your reply. We've emailed you. Kindly check and let us know.

Thank you for this awesome library.
