### ISSUE TITLE
Ability to redriect traffic to server side proxy

### ISSUE THREAD

**Issue by scruel** [schwabe/ics-openvpn#1704]
We setup an OpenVPN server and a local proxy server on two machines in the same ethernetA, for our client devices which outer ethernetA, will need to connect to our OpenVPN server to get access to ethernetA, and want to have some apps' traffic goes to socks5 proxy server meanwhile:
Client -> OpenVPN -> ethernetA -> other machines
Client -> PAC rules umatched/selected apps -> Internet
Client -> PAC rules matched/unselected & system apps -> OpenVPN -> ethernetA -> socks5 proxy (DNS resolve through proxy, IPv4 only) -> internet

Currently, with android global proxy settings, we will be able to redirect all traffic with HTTP proxy protocol, meanwhile all ethernet machines are still accessable:
Client -> OpenVPN -> ethernetA -> other machines
Client -> OpenVPN -> ethernetA -> HTT proxy -> internet

But as you can see above, we will route all traffic including unnecessary traffic into our server, which will slow the network and cause some issues, also, android only support HTTP proxy protocol on its own.
Another solution is to unset global proxy, then set proxies inside the app itself, if its support to do so, however many apps won't provide built-in proxy support at all...

**Comment by scruel** [comment]
If #1705 is a bug and can be resolved, then have an option to allow selected apps bypass the global HTTP proxy should be fine for our scenario for now, though socks5 proxy support would be much more nicer.
Thanks!

**Comment by scruel** [comment]
Or I don't know whether it will be possible to have an option which allows selected apps bypass the global HTTP proxy, this option should be enough for our scenario for now (if VPN stop routing checked apps, then they obviously won't be able to connect to the ethernet proxy which set globally on the device client side, e.g., 192.168.3.100:8080), though it would be better to have socks5 proxy supported.
Thanks!

**Comment by schwabe** [comment]
I am afraid the flexibility you want in terms of HTTP proxy support is just not supported by Android itself, so the app cannot provide what you are looking for.
