### ISSUE TITLE
 Apps may bypass VPN not works

### ISSUE THREAD

**Issue by scruel** [schwabe/ics-openvpn#1706]
On Allow app page:
- Set disallow VPN app (apply all except selected)
- uncheck Apps may bypass VPN option
- Check one app which you can use directly before VPN connected 
- After VPN connected, app still can access the network

Vesion 0.7.51
Android 13

**Comment by schwabe** [comment]
I am not sure what you expect. This only controls if apps can you use the VPN or use normal Internet connection. Of course it can sstill use Internet if you have connectivity.

**Comment by scruel** [comment]
Shouldn't "Apps may bypass VPN option" will prevent apps bypass the VPN? And since I disallowed apps to go through VPN, why they still can use normal connection?
App -x> VPN (disallowed)
App -?> Internet (can't by pass)
I don't think I understand the meaning of this option, "can't bypass" means have to go though VPN?

**Comment by schwabe** [comment]
That option only allows an App that is routed over the VPN to not use the VPN. See also https://developer.android.com/reference/android/net/VpnService.Builder#allowBypass() and issue #1702
