### ISSUE TITLE
Problem with different app exiting

### ISSUE THREAD

**Issue by hummasyousuf** [schwabe/ics-openvpn#1712]
-

**Comment by schwabe** [comment]
Please provide a complete log.

**Comment by schwabe** [comment]
That is not my app but some different app (com.ice.vpn.app)

**Comment by hummasyousuf** [comment]
-

**Comment by schwabe** [comment]
Please share your whole repository and it open-source under the GPL2/3 first and exploain what kind of modifications you are making to my app to give me some motivation to help you.

**Comment by MuhammadNihal** [comment]
**### FILE LINK:**

`https://we.tl/t-xeaNsYL2If`

**### LOGS:**

![Log](https://github.com/schwabe/ics-openvpn/assets/94975559/4b291e2c-60c0-46d3-a20e-d97aaa1481c2)
