### ISSUE TITLE
OpenVPN Progress Exit Issue

### ISSUE THREAD

**Issue by hummasyousuf** [schwabe/ics-openvpn#1714]
### **FILE LINK:**

`https://we.tl/t-xeaNsYL2If`

### **LOGS:**

![Log](https://github.com/schwabe/ics-openvpn/assets/94975559/4b291e2c-60c0-46d3-a20e-d97aaa1481c2)

**Is there a way to check if a config file is valid or not using code?**

**Comment by schwabe** [comment]
Closing this issue. You also edited your last issue to remove all content  and posted a new issue with identical content.

**Comment by hummasyousuf** [comment]
I have informed you of the issue, but you are not solving it and are closing it.

**Comment by schwabe** [comment]
You are trying to build a different app and trying me to get you to help building that different app for free. I don't work for free. And also this github repostitory is only about my app and not about other apps. So anything about other apps will just be closed.

**Comment by hummasyousuf** [comment]
I'm not creating an app; I'm using your app. However, when I upload any .ovpn file, this error occurs
I've provided a screenshot above; it's from your app.

**Comment by schwabe** [comment]
Contact your server provider. This is an authentication failure and not a problem of the app itself.

**Comment by hummasyousuf** [comment]
It's alright, it means the configuration file isn't correct.

**Comment by hummasyousuf** [comment]
Set a condition so that it can be determined whether the data in the ovpn file is valid or not.

**Comment by schwabe** [comment]
@MuhammadNihal you get an auth failed. That is a failed login. The configuration file is valid.
