### ISSUE TITLE
How to build `miniopenvpn` used in `debug-openvpn.sh`?

### ISSUE THREAD

**Issue by scruel** [schwabe/ics-openvpn#1718]
Hi, I want to build openvpn binaries on Android, however I couldn't find anything related in both [OpenVPN3 official repo](https://github.com/OpenVPN/openvpn3) or here.

I can only find related usages about `miniopenvpn`, but not build instructions:
https://github.com/schwabe/ics-openvpn/blob/4473ad1f1bc49c166fb8ab92ee7a7b91c608135e/main/misc/prepareovpn3.sh
https://github.com/schwabe/ics-openvpn/blob/4473ad1f1bc49c166fb8ab92ee7a7b91c608135e/misc/debug-openvpn.sh

Couldn't find `miniopenvpn` on my phone:
```shell
/data/data/de.blinkt.openvpn/cache $ ls
logcache.dat  mgmtsocket
```
And related file is just empty:
https://github.com/schwabe/ics-openvpn/blob/4473ad1f1bc49c166fb8ab92ee7a7b91c608135e/main/src/main/cpp/minivpn/minivpn.c

@schwabe All related android build issues are pointed to your repo by yourself, so hope you can help a little bit more! Thanks!

**Comment by schwabe** [comment]
I have not used that debug-openvpn.sh script in years. It used to work but I don't think it still works. Current binaries are build using cmake and using the CmakeLists.txt in the cpp directolry.
