### ISSUE TITLE
Keep Connected All Time

### ISSUE THREAD

**Issue by ibahnasy** [schwabe/ics-openvpn#1720]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version `12`
2. Android Vendor/Custom ROM `Google Pixel ROM`
3. Device `Google Pixel 3 XL`
4. Version of the app (version number/play store version/self-built) `0.7.51`
 
# Description of the issue
I set this VPN app to be always connected however after locking the screen for a while, it gets disconnected, though it automatically re-connects on wake up.

I also have `ping 5` in the configuration file.

**Comment by schwabe** [comment]
Please provide the log from the app itself.

**Comment by ibahnasy** [comment]
[vpn.log](https://github.com/user-attachments/files/15919940/vpn.log)

**Comment by schwabe** [comment]
The log seems to be truncated. Also when did you turn off the screen in that log?

**Comment by ibahnasy** [comment]
I opened the log window in the app and chose "send to file" and copied the text.

I turned the screen on/off  many times during a whole day of usage.

**Comment by schwabe** [comment]
Your ping timeout might be just too aggressive. You have 10s of ping timeout. That is awfully short. Try using something like a minute or two and see if that solves your problem.

**Comment by ibahnasy** [comment]
I increased the timeout to 15 which is higher than the `ping-restart` time but this behavior is still happening:

```
ping 5
ping-restart 10
connect-timeout 15
```

BTW, using the same OpenVPN config on Linux laptop is working fine and never disconnects on it's own.

**Comment by schwabe** [comment]
a laptop does not typically put apps to sleep. `connect-timeout` also has nothing to do with ping timeout. Please increase the ping-restart to something like 60 or 120 seconds on server and client and see if that makes a different.

**Comment by ibahnasy** [comment]
Yes this solved the issue, thanks.
