### ISSUE TITLE
I need to understand more about licensing

### ISSUE THREAD

**Issue by smctaher** [schwabe/ics-openvpn#1721]
I used ics-openvpn to connect and disconnect in a free application that contains ads. What should I do so that I do not get into a problem? Should I publish the source code or remove ics-openvpn? I searched a lot on the Internet and did not find an answer.

I created a new GUI and my own servers. I just used ics-openvpn to connect and disconnect.

**Comment by schwabe** [comment]
So if your app contains ics-openvpn code, then the GPLv2/GPLv3 applies to your code too and you need to publish your app also under the GPLv2/v3. You can otherwise modify the code however you want, including adding adds and so. See also this FAQ on the GPL: https://www.gnu.org/licenses/gpl-faq.html
