### ISSUE TITLE
OpenVPN tries to connect to old IP

### ISSUE THREAD

**Issue by kvmgithub** [schwabe/ics-openvpn#1722]
I don't know if a comment in the closed issue triggers a notification, so I' m referencing it here.
https://github.com/schwabe/ics-openvpn/issues/993#issuecomment-2123880469

**Comment by kvmgithub** [comment]
Bump? Still not sure if closed issues trigger a notification.

**Comment by schwabe** [comment]
Please do not open meta tickets. They just clutter the issue tracker.
