### ISSUE TITLE
OpenVPN for Android disconnects if phone is locked

### ISSUE THREAD

**Issue by ibahnasy** [schwabe/ics-openvpn#1725]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: `12`
2. Android Vendor/Custom ROM: `Google`
3. Device: `Pixel 3 XL`
4. Version of the app (version number/play store version/self-built): `0.7.51`
 
# Description of the issue
VPN tunnel disconnects if the phone is locked even though it's configured to be always connected.

**Comment by schwabe** [comment]
Please provide logs.

**Comment by ibahnasy** [comment]
[ICS OpenVPN log file.txt](https://github.com/user-attachments/files/15550697/ICS.OpenVPN.log.file.txt)

**Comment by ibahnasy** [comment]
Solved in #1720
