### ISSUE TITLE
Is socks-proxy config option still supported ? [a question more than an issue]

### ISSUE THREAD

**Issue by LindaFerum** [schwabe/ics-openvpn#1727]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 13
2. Android Vendor/Custom ROM Stock, Calyx or Graphene
3. Device Pixel 8 
4. Version of the app (version number/play store version/self-built)
  0.7.51 
 
Basically, I'm picking OpenVPN android client for a little side-project and noticed that a certain resource claims that socks-proxy function is no longer operational on this app. (see: https://www.perfect-privacy.com/en/manuals/android_openvpn_stealth_socks ) but it seems to be claiming a later version than the one available.

Thus questions:
Is the socks-proxy directive currently supported?
Will it be supported in the future versions of ics-openvpn for android ?

**Comment by schwabe** [comment]
The linked website talks about OpneVPN Connect which is a completely different app.
