### ISSUE TITLE
How Does the OpenVPN Work: in general and in this repo?

### ISSUE THREAD

**Issue by yuriiShmal** [schwabe/ics-openvpn#1728]
I'm a college student trying to make a small VPN Android app mostly to get some experience developing for android/working with networks (supporting up to 5 connections to the (only) server total at any time, so not commerical). 

I've spent 2 weeks trying to figure out how to use OpenVPN in my app so this repository eventually caught my interest. 

I set up a server (the config files work with available openvpn apps) but I am still confused with what exactly the client-side is doing with the .ovpn files. What courses/approaches/readings/books would you recommend, or is it just puzzling out the openvpn repo? 

I don't want to just make a derivative of the work in this repo, as it seems to me that it would trivialize the most interesting part of the summer project (I can _probably_ make a derivative if it comes down to it, as I don't mind licensing under GPL2/GPL3 and making it open source).

Edit: I don't know enough about openSSL or openvpn protocols to do this stuff. I'll just make a derivative. Tips on where to learn would still be very appreciated though.

**Comment by schwabe** [comment]
Most people learned by using derived software and making small changes first and then maybe bigger one later. That is part of the learning process. So go ahead with that and good luck to you!
