### ISSUE TITLE
Can the disconnection confirmation dialog be disabled?

### ISSUE THREAD

**Issue by llima27** [schwabe/ics-openvpn#1732]
1. Android 14
2. Samsung
3. Samsung S23+
4. 0.7.51
 
I'm able to create a routine to connect to a certain VPN server when I connect to a certain wi-fi network. I'm also able to create a routine to trigger a disconnect from the VPN server when I disconnect from that wi-fi network, but the action gets stuck in the "are you sure you want to disconnect" dialog. Is it possible to disable this?

I'm aware that it's possible to avoid this problem with Tasker with or without the OpenVPN plugin. I do this successfully in other devices including a TV. However, I was hoping to use the built in automation functionality of this phone instead.

Thanks.

**Comment by schwabe** [comment]
Duplicate of other issues. And I do not own a Samsung device and I am not going to buy one to figure out what kind of properitary stuff and (ab)use of other stuff they are doing. I understand that this stuff is trying to reuse some parts of my app that are meant to be used by normal user interaction and that fails. So no big surprise here.

**Comment by llima27** [comment]
@schwabe Apologies for the duplication. I searched and didn't get results from the keywords I searched. Happy to help if I can. Thanks for the reply.
