### ISSUE TITLE
Alternative distribution channel for Android (e.g. via GitHubReleases).

### ISSUE THREAD

**Issue by jayb-g** [schwabe/ics-openvpn#1736]
# General information
1. Android Version - N/A
2. Android Vendor/Custom ROM - N/A
3. Device - N/A
4. Version of the app (version number/play store version/self-built) - N/A
 
# Description of the issue
The app is released only on Google Play and not on F-Droid or as direct apk through openvpn website. It is impossible to get the official release without using Google Play.

It would be much easier for people to find official release apks on GitHubReleases at least, if not on F-droid.

**Comment by schwabe** [comment]
It is on F-droid and there are also apk on plai.de/android as well here on Github in the releases. Even the overview page (https://github.com/schwabe/ics-openvpn) links to F-Droid.

**Comment by jayb-g** [comment]
Sorry I posted this on wrong repo

**Comment by jayb-g** [comment]
@schwabe I can't find the official openvpn android repo. Can you please share where this repo is forked from?

OpenVPN Connect and OpenVPN for Android seems to be two different apps on Google Play.

I'm looking for openvpn connect(android) repo.

Thanks

**Comment by schwabe** [comment]
OpenVPN Connect is a closed source app. There is no publicly available repository. You can go to support.openvpn.net.

**Comment by DwainZwerg** [comment]
@schwabe Isn't [that](https://github.com/OpenVPN/openvpn) the repo? Or is the source code only for Windows and MacOS?

**Comment by schwabe** [comment]
No. The library is available under https://github.com/openvpn/openvpn3 but the whole UI and other parts of OpenVPN Connect are not open-source.

**Comment by jayb-g** [comment]
Got it. So seems like this is the unofficial openvpn client for Android

**Comment by DwainZwerg** [comment]
I wrote the same thing to you: "There is only [this **port** of OpenVPN](https://github.com/schwabe/ics-openvpn/releases)" and (because I didn't realize that the original client is closed source: "You can open an [issue](https://github.com/OpenVPN/openvpn/issues/new/choose) by requesting an alternative distribution channel for Android (e.g. via GitHubReleases)")

**Comment by jayb-g** [comment]
@DwainZwerg thanks
