### ISSUE TITLE
Solid black (optional) for background

### ISSUE THREAD

**Issue by Korb** [schwabe/ics-openvpn#1737]
OpenVPN for Android currently uses the non-black color `#303030` as its dark theme background. Here's how application developers argue for using `#000` as a background color:

Google Android 14:

> Dark Theme Screen / On some screens, Dark theme will use a solid black background which will help extend your battery life. After scheduling, Dark theme will be enabled when your screen is off.

Catima:

> Pure black background for dark theme (reduces battery usage on OLED displays).

F-Droid:

> Use pure black background in dark theme. Recommended only for OLED screens.

**Comment by schwabe** [comment]
I don't think the app gets enough screen time that it makes sense to make this a configurable option in order to save some tiny amount of battery. The app is already using the normal dark theme of Android. Even a nearly black grey saves already a lot of power compared to white.
