### ISSUE TITLE
build failed

### ISSUE THREAD

**Issue by li66666666666** [schwabe/ics-openvpn#1739]
I'm new to this, and I'm currently developing an Android app using Android Studio.
My build file configuration is correct, and I want to configure the ics-openvpn library through JitPack. I used this code: `implementation("com.github.schwabe:ics-openvpn:v0.7.51")`
It reports an error:
`Failed to resolve: com.github.schwabe:ics-openvpn:v0.7.51`
`<a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>`
`Affected Modules: <a href="openFile:D:/test2/app/build.gradle.kts">app</a>`
When I search in my browser for `https://www.jitpack.io/com/github/schwabe/ics-openvpn/v0.7.51/ics-openvpn-v0.7.51.pom`, it shows
`Build failed. See the log at jitpack.io`
When I search for `https://www.jitpack.io/com/github/schwabe/ics-openvpn/v0.7.51`, it shows
`build.log`
When I search for `https://www.jitpack.io/com/github/schwabe/ics-openvpn/`, it shows
`v0.6.64/`
`v0.6.63-production/`
`v0.6.73-production/`
`v0.7.6/`
`v0.7.5-production/`
`v0.7.5/`
`v0.7.4/`
`0.6.64/`
`0.7.7/`
`0.7.8/`
`v0.6.73/`
`0.7.10/`
`v0.7.10/`
`v0.7.8/`
`v0.7.7/`
`0.7.11/`
`0.7.13/`
`v0.7.13/`
`v0.7.12/`
`v0.7.0/`
`v0.7.3/`
`0.7.3/`
`v0.6.71/`
`0.7.15-production/`
`v0.7.15-production/`
`v0.7.15/`
`0.7.17a/`
`v0.7.16-production/`
`v0.7.16/`
`v0.7.17a/`
`master/`
`0.7.18/`
`0.7.20/`
`0.7.21/`
`v0.7.21/`
`v0.7.20/`
`bce3b9436a/`
`154fee81f6/`
`46bb34fa95/`
`v0.7.19/`
`v0.7.18/`
`v0.6.10/`
`v0.5.5/`
`v0.7.14/`
`v0.6.9/`
`v0.5.5a/`
`v0.5.6/`
`v0.5.7/`
`v0.5.8/`
`v0.5.17/`
`v0.5.20/`
`v0.5.24/`
`v0.6.68/`
`v0.6.65/`
`v0.6.35/`
`0.5.5/`
`0.5.10/`
`0.5.30/`
`0.7.16/`
`0.6.73/`
`0.7.22/`
`v0.7.22/`
`0.7.12/`
`-v0.7.16-ge4597ec-46/`
`0.7.23/`
`v0.7.23/`
`master-v0.7.16-g4c2abd8-54/`
`9048473a35/`
`-v0.7.16-g4c2abd8-54/`
`0.7.16-production/`
`0.7.24/`
`v0.7.24/`
`0d9aefb1b8/`
`0.7.25/`
`0.7.27/`
`0.7.28/`
`0.7.29/`
`v0.5.9/`
`v0.5.18/`
`v0.5.21/`
`v0.5.40/`
`v0.7.29/`
`v0.6.70/`
`v0.6.66/`
`v0.7.28/`
`v0.7.27/`
`0.7.30/`
`0.7.31/`
`v0.7.31/`
`v0.7.30/`
`0.7.32/`
`0.7.33/`
`v0.7.33/`
`v0.7.11/`
`v0.7.26/`
`v0.7.32/`
`master-v0.7.16-g97546b9-157/`
`0.7.34/`
`v0.7.34/`
`v0.7.33-production/`
`0.7.36/`
`0.7.37/`
`v0.7.37/`
`v0.7.36/`
`0.7.38/`
`0.6.73-production/`
`v0.7.38/`
`0.7.39/`
`0.7.41/`
`v0.7.41/`
`ffa1cca854/`
`v0.7.40/`
`0.7.40/`
`v0.7.39/`
`master-v0.7.33-production-g3647868-54/`
`fba254e725/`
`0.7.42/`
`v0.7.42/`
`0.7.43/`
`v0.7.43/`
`master-v0.7.33-production-gf07066d-67/`
`v0.7.25/`
`v0.7.1/`
`0.7.44/`
`v0.7.44/`
`0.7.1/`
`0.6.44/`
`0.6.63/`
`0.6.70/`
`0.6.43/`
`master-v0.7.33-production-g8bb986f-85/`
`0.7.46/`
`v0.7.46/`
`0.7.45/`
`v0.7.45/`
`0.7.48/`
`0.7.49/`
`v0.7.49/`
`0.7.50/`
`v0.7.50/`
`v0.7.47/`
`v0.7.48/`
`v0.6.43/`
`0.7.51/`
`v0.7.51/`
`0.7.47/`
`master-v0.7.33-production-g4473ad1-150/`
`4ef3bb1f0b/`
`gh-pages-a506c989e7-1/`
`27b7d34e56/`
`externaltls-v0.7.5-gf05eb58-13/`
`279dc0a51c/`
`0.5.33/`
`remoteExample/`
`vpndialogxposed/`

**Comment by schwabe** [comment]
This is not a library. So using it as library will not work. This is a standalone app.

**Comment by li66666666666** [comment]
> This is not a library. So using it as library will not work. This is a standalone app.

Sure, thank you so much. So, may I ask if I can personalize the compilation of this software on the Android Studio platform?
