### ISSUE TITLE
I need to integrate OQS-provider and liboqs

### ISSUE THREAD

**Issue by josephjw** [schwabe/ics-openvpn#1744]
### Discussed in https://github.com/schwabe/ics-openvpn/discussions/1742

<div type='discussions-op-text'>

<sup>Originally posted by **josephjw** July 25, 2024</sup>
hello,

can you give me brief idea of integrating liboqs and oqs-provider through openssl.cmake file . or any other integration technics please help me out here. 

Thanks you</div>

**Comment by schwabe** [comment]
Please do not open duplicate issues/discussions.
