### ISSUE TITLE
Why there is no good documentation about how to use this library/module ? 

### ISSUE THREAD

**Issue by MageNavneet** [schwabe/ics-openvpn#1748]

**Comment by schwabe** [comment]
Because this is not a library. It is a standalone app. Therefore there is no documentation how to use this as library.

**Comment by MageNavneet** [comment]
So where is the library ? I have seen many projects using it as a module.

**Comment by schwabe** [comment]
I am not providing or building a library. I don't know what these people are doing. Ask them for a copy of their source code. This project is GPL, so anything that uses parts of this project is also under GPL as well and therefore also open source.
