### ISSUE TITLE
F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [schwabe/ics-openvpn#1751]
it first complained about the NDK: https://gitlab.com/fdroid/fdroiddata/-/jobs/7505386176#L1580

so I update it but: https://gitlab.com/fdroid/fdroiddata/-/jobs/7505620397#L1584

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/1cfe54e826e0bb6a3d7ba0aadd355a101ce6cbf4

**Comment by schwabe** [comment]
the first two links give a me a 500  http error.

The github actions are fine, so at least it not only buildable on my machine: https://github.com/schwabe/ics-openvpn/actions/runs/10236209040

**Comment by licaon-kter** [comment]
> the first two links give a me a 500 http error.

network glitches, retry, they work fine for me

**Comment by schwabe** [comment]
No, they continue to be 500. Maybe you need to be logged in or similar but I cannot access the links. So it would be helpful if you could provide an a log or error message here in the ticket.

**Comment by licaon-kter** [comment]
At first
```
1: Task failed with an exception.

-----------

* What went wrong:

A problem occurred configuring project ':main'.

> [CXX1104] NDK from ndk.dir at /opt/android-sdk/ndk/26.1.10909125 had version [26.1.10909125] which disagrees with android.ndkVersion [26.3.11579264]
```

And after 
```
> Task :main:mergeDexUiOvpn23Release

> Task :main:compileUiOvpn23ReleaseArtProfile

> Task :main:packageUiOvpn23Release FAILED

> Task :main:lintVitalAnalyzeUiOvpn23Release

FAILURE: Build failed with an exception.

* What went wrong:

Execution failed for task ':main:packageUiOvpn23Release'.

> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
``` 

Also seen here: https://monitor.f-droid.org/builds/log/de.blinkt.openvpn/207#site-footer 

/PS: indeed, those links will 500 unless logged in, odd :(

**Comment by schwabe** [comment]
This problem with the ndk version seems more a fdroid build problem than a problem with the source code itself. The offending version (26.1.10909125) is not referenced anywhere in the proejct itself (apart from runcoverity.sh but that is a script to run coverity and not related here)

**Comment by licaon-kter** [comment]
>  The offending version (26.1.10909125) is not referenced anywhere in the proejct itself 

On autoupdate the previous version block is copied in the new version block, `26.1` **is** in your source code, for [0.7.51](https://github.com/schwabe/ics-openvpn/blob/v0.7.51/main/build.gradle.kts#L24)

But that's not the issue, as said already, [I've fixed](https://gitlab.com/fdroid/fdroiddata/-/commit/e9d18e96b1a5d6e24b90dc3fe39eae81e6461686) that "fdroid build problem".

Can we now focus on the next problem? log: https://monitor.f-droid.org/builds/log/de.blinkt.openvpn/207#site-footer

**Comment by schwabe** [comment]
@licaon-kter I only see `Exception while marshalling /opt/android-sdk/platforms/android-33/package.xml. Probably the SDK is read-only` as error in that log. Otherwise I don't see any problems. And please stay friendly when you asking me to debug your build problems.

**Comment by licaon-kter** [comment]
I'm staying friendly, but maybe we are lost in translation? :)

Each of your posts seems to avoid the actual fail reason written in the logs:
```
Execution failed for task ':main:packageUiOvpn23Release'.

> A failure occurred while executing com.android.build.gradle.tasks.PackageAndroidArtifact$IncrementalSplitterRunnable
```

**Comment by schwabe** [comment]
That error message is not helpful. That is just saying that a step in the build process failed. That is like `make` complaining that the target `openvpn` failed to build. It does not give any useful information to go on with. Try building with more verbosity or try to figure out what is different between your build process and the github actions that also build OpenVPN for Android automated

**Comment by licaon-kter** [comment]
funny how it worked fine with --stacktrace :shrug: 

anyway, after several --debug runs one said `java heap space` so I bumped that in https://gitlab.com/fdroid/fdroiddata/-/commit/cbb3b7fff27700712082b3c2cfa841493dd2094e and it worked locally

thanks
