### ISSUE TITLE
Viewing/Editing a profile's config crashes the app

### ISSUE THREAD

**Issue by 1-eric** [schwabe/ics-openvpn#1754]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: `Android 10`
2. Android Vendor/Custom ROM: `Stock ROM`
3. Device: `Xiaomi Mi-A3`
4. Version of the app (version number/play store version/self-built): `v0.7.53 from github`
 
# Description of the issue
Let's say I want to view or edit the routing of a profile.

This will crash the app:
1. Press the edit button (pencil symbol) on the right side of a profile
2. The view will now show the `BASIC` tab of this profile's config
3. Press the `ROUTING` tab (3 tabs away from the `BASIC` tab)
4. The app will crash

However, this will not crash the app:
1. Same as above
2. Same as above
3. Press or swipe to the `SERVER LIST` tab
4. Press or swipe to the `IP AND DNS` tab
5. Press or swipe to the `ROUTING` tab
6. No crash

It looks like the app will crash when I skip more than 2 tabs in the profile's config.

This is maybe related:
1. Start the app (force stop the app first if needed)
2. The app will now be in the `PROFILES` tab
3. Press the `FAQ` tab (3 tabs away from the `PROFILES` tab)
4. The app will not crash, but the view will be empty

**Comment by schwabe** [comment]
Should be fixed now
