### ISSUE TITLE
Only 0.7.51 available at Google play store.

### ISSUE THREAD

**Issue by agiUnderground** [schwabe/ics-openvpn#1756]
# Description of the issue
0.7.53 not available at Google play store. It shows "Last updated Dec 3, 2023".

Available version 0.7.51

**Comment by agiUnderground** [comment]
Web version of the Google play store shows "Updated on Aug 19, 2024" but android app installs 0.7.51

**Comment by schwabe** [comment]
Yes. This is a staged rollout and is by design.
