### ISSUE TITLE
Openvpn connect problem with socksv5, Shadowsocks

### ISSUE THREAD

**Issue by lahitomic** [schwabe/ics-openvpn#1760]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
14

2. Android Vendor/Custom ROM
Google, Samsung

3. Device
SM-A528N

7. Version of the app (version number/play store version/self-built)
0.7.53
 
# Description of the issue
Hello. I tried to connecting vpn with my customed file and socksv5 proxy, Shadowsocks. I added excluding Shadowsocks application during connecting the vpn. This file can run on the other devices, but the only one, my SM-A528N, cannot run this .ovpn file. And That returned under this log. Please solve this problem.

# Log (if applicable)

1:31 PM Error reading from output of OpenVPN process: OpenVpn process was killed form java code

java.lang.InterruptedException: OpenVpn process was killed form java code
	at de.blinkt.openvpn.core.OpenVPNThread.startOpenVPNThreadArgs(OpenVPNThread.java:179)
	at de.blinkt.openvpn.core.OpenVPNThread.run(OpenVPNThread.java:76)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by schwabe** [comment]
Please provide more information of how the configuration file and your setup looks like to be able to reproduce it.
