### ISSUE TITLE
Disable disconnect confirmation dialog

### ISSUE THREAD

**Issue by Shulyaka** [schwabe/ics-openvpn#1762]
First of all, great app!

But please add a configuration option to skip the confirmation dialog on VPN disconnect. 
I have set up my phone to automatically connect to my home VPN when I am disconnected from my home network, and disconnect back when I am reconnected. However what I get is that whenever I come back home, this confirmation dialog pops up.

**Comment by schwabe** [comment]
There are already intents that allow you to skip the confirmation dialog designed for automation. Please use these.

**Comment by Shulyaka** [comment]
That's what I use (I think), but it does require confirmation.

**Comment by schwabe** [comment]
Please double check: 

https://github.com/schwabe/ics-openvpn?tab=readme-ov-file#controlling-from-external-apps

are the ones you should be using

**Comment by Shulyaka** [comment]
I am using what One UI calls [routines](https://www.samsung.com/us/support/answer/ANS00083201/), I am not sure if they use AIDL API internally or not. There are 3 actions to chose:  Launch OpenVPN fro Android, Disconnect, and one more action named after my profile name. When I chose Disconnect as an action and trigger the routine, it shows me the confirmation dialog.

**Comment by Shulyaka** [comment]
I think they are using shortcuts...

**Comment by schwabe** [comment]
Shortcuts are designed for Launcher and not automasation. I don't have a Samsung phone to test these and I am not buying one to figure out what they are doing there, sorry.

**Comment by Shulyaka** [comment]
Thank you, have a great weekend!
