### ISSUE TITLE
DNS requires VPN connection, not fixed in 2 years

### ISSUE THREAD

**Issue by woodholly** [schwabe/ics-openvpn#1763]
1. Android Version 11-14
2. Android Vendor/Custom ROM LOS
4. Version of the app: all versions for the last 2 years
 
# Description of the issue
I am struggling with this issue for 2 years, please help! Bug first appeared in android 11.
Filtering VPN data in application settings turns off domain name resolutions, even if VPN is not default and does not change DNS.

How to reproduce:
1) Create openvpn connection, disable default route to vpn, disable pull of DNS settings by adding these custom options:
```
 # TWO spaces before DNS:
pull-filter ignore "dhcp-option  DNS"
pull-filter ignore "block-outside-dns"
```
2) Start vpn
3) Open any app with internet access that requires DNS (not firefox because it uses it's own https-dns service). For example - youtube. Result: youtube works, DNS resolution works.
4) Disable VPN traffic inside youtube app (long click youtube icon - about - traffic settings - VPN data - disable). Result: youtube fails to resolve domain names despite the fact that openvpn DNSs are not used and vpn connection is not set as default route. (but youtube can connect anywhere by IP)

What blocks youtube DNS requests? DNS servers are from WIFI connection, not VPN and should work as usual regardless of whether VPN is on or off. But if I start openvpn, youtube stops working. Why starting openvpn changes how applications resolve domain names ?

**Comment by schwabe** [comment]
This sounds like a bug in your custom ROM. If a VPN is stopped the netd and VPNservice should stop the VPN. The app does not even have the rights to set/modify DNS outside of the VPN tunnel.

**Comment by woodholly** [comment]
Thank you for your answer. I think you misunderstood me so I updated the issue to be more clear.
When VPN is stopped, applications work as usual. Problem arises only with active openvpn connection.

**Comment by schwabe** [comment]
Can you provide the full log of the VPN connection. You might be usign a VPN configuration that just does not provide a working DNS setup.

**Comment by woodholly** [comment]
Of course my vpn configuration does not provide working DNS setup and it is intended. I don't want openvpn to change anything related to DNS and used configuration filters to do that.

**Comment by schwabe** [comment]
For now I have to assume a misconfiguration without you providing any more details. Not providing a DNS server with a VPN tunnel can lead to various reasons why DNS is not working, including but not limited to:

- certain ROMs disabling DNS if not provided by VPN
- other ROMs always forwarding DNS via VPN
- routing DNS via VPN and the DNS server is refusing answers to the DNS from the new IP.
