### ISSUE TITLE
The dependency on android studio implementation 'de.blinkt:openvpn:0.7.53' isn't importing

### ISSUE THREAD

**Issue by saidismailanik** [schwabe/ics-openvpn#1764]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

# Log (if applicable)

```
log contents
```

# Configuration file

```
add the contents of the configuration file if applicable
be careful to not post private keys
```

**Comment by schwabe** [comment]
See other issues. This is not a library and cannot be used as one. This is an app.
