### ISSUE TITLE
Don't show input window for challenge/response protocol (crv1)

### ISSUE THREAD

**Issue by ikreb7** [schwabe/ics-openvpn#1765]
# General information
1. 12
2. GrapheneOS
3. Pixel 3a
4. de.blinkt.openvpn_0.7.51

# Description of the issue
I want to use OpenVPN with MFA, but your app don't show a window to enter a MFA code. It works with all other clients, e.g. Windows OpenVPN client, Tunnelblick or OpenVPN Connect.

# Log

```
[...]
2024-10-07 18:05:39 TLS: move_session: dest=TM_ACTIVE src=TM_INITIAL reinit_src=1
2024-10-07 18:05:39 TLS: tls_multi_process: initial untrusted session promoted to trusted
2024-10-07 18:05:40 MANAGEMENT: >STATE:1728317140,GET_CONFIG,,,,,,
2024-10-07 18:05:40 SENT CONTROL [openvpn-server]: 'PUSH_REQUEST' (status=1)
2024-10-07 18:05:40 AUTH: Received control message: AUTH_FAILED,CRV1:R,E:e828ef252524f26f8d34:dGVzdHVzZXIK:Please enter your TOTP Code
2024-10-07 18:05:40 TCP/UDP: Closing socket
2024-10-07 18:05:40 SIGTERM[soft,auth-failure] received, process exiting
2024-10-07 18:05:40 MANAGEMENT: >STATE:1728317140,EXITING,auth-failure,,,,,
2024-10-07 18:05:40 Unscheduling VPN keep alive
```

If you need any more information, I could give more logs or details.

**Comment by schwabe** [comment]
What server are you connecting against? It seem to only support the old CRV1 method and not the modern CR_TEXT method.

**Comment by ikreb7** [comment]
Yes, this is right. I use the CRV1 method. But I think, you still support CRV1.

https://github.com/schwabe/ics-openvpn/blob/2af49fc272d8108b9557735bf843465e52559917/main/src/ui/java/de/blinkt/openvpn/fragments/ImportRemoteConfig.kt#L303

**Comment by schwabe** [comment]
Only for config imports from Access Server. That is not a VPN support. For VPN support CRV1 is not implemented and also currently not planned.

**Comment by ikreb7** [comment]
You are right. What is the reason, that CRV1 for VPN won't be supported? :'(

**Comment by schwabe** [comment]
There is already a better method called crtext/CR_TEXT that allows MFA without having to go through a disconnect/reconnect cycle. 

Implementing the old CRV1 method is not quite as trivial as the app needs to learn that sometimes when a connection ended it did not really end but needs to be restarted in a weird way after getting user input.

What server do you connect to?

**Comment by ikreb7** [comment]
> What server do you connect to?

It is our own openvpn cluster.

**Comment by schwabe** [comment]
As in your own implementation? Then just implement CRTEXT as well.

**Comment by jayb-g** [comment]
I have the same issue connecting to on-prem openvpn server. Showing auth_failed, CRV1. Meaning I also expected it to prompt for an otp every time I want to connect, even through quick tiles. But it does not. And works by appending otp to password. 

> As in your own implementation? Then just implement CRTEXT as well.

Does it mean enabling CRTEXT for two factor on the server? Will it enable otp prompts in OpenVPN for Android app?

**Comment by schwabe** [comment]
Yes. There are two MFA methods in OpenVPN. The old CRV1 that is not supported by this app and the newer CR_TEXT that is supported by the app.

**Comment by schwabe** [comment]
I am closing this issue as I will not work on implementing CRV1

**Comment by jayb-g** [comment]
> Yes. There are two MFA methods in OpenVPN. The old CRV1 that is not supported by this app and the newer CR_TEXT that is supported by the app.

@schwabe can you please share some references on what it is and how to change it to use CR_TEXT?

**Comment by schwabe** [comment]
See the management.txt of OpenVPN for more detail about the method. That documents both the old and the new 2FA variant. I don't know what server you are running, so I cannot help you with that.

**Comment by jayb-g** [comment]
> Yes. There are two MFA methods in OpenVPN. The old CRV1 that is not supported by this app and the newer CR_TEXT that is supported by the app.

I'm still confused by this.
The old CRV1 works with this app by just appending the OTP to the password, but of course it's inconvenient to do so everytime you want to connect in android.

The newer CRTEXT is claimed to be supported but there's no public documentation regarding how to check/enable it on openvpn server.

I can't find anything useful related to it in the [management.txt](https://github.com/OpenVPN/openvpn/blob/master/doc/management-notes.txt) of openvpn. Can you please clarify if I'm looking at the correct file or share correct reference?

**Comment by schwabe** [comment]
@jayb-g no that is not the CRV1 method, it is a bit more complicated than that. The CRV1 methods work by using a special AUTH_FAILED message that the client needs to parse.

What information are you missing for CR_TEXT in management.txt? 

Note that there is even a sample script if you don't want to use management interface to implement TOTP: https://github.com/OpenVPN/openvpn/blob/master/sample/sample-scripts/totpauth.py

**Comment by jayb-g** [comment]
> What information are you missing for CR_TEXT in management.txt

Specifically, how to enable CRTEXT support? Using _openvpn_ as server with pritunl. 

For Linux client, we have already managed to append totp to the password using bash script but I guess that's only required if server supports CRV1 but not CRTEXT?

The problem is for android where OpenVPN for Android supports OTP prompt only if server uses CRTEXT right? So I can't find instructions on how to enable CRTEXT on openvpn server. Also can you please share screenshots of how this app prompts for otp ?

**Comment by schwabe** [comment]
@jayb-g I think you need to need to talk to pritunl to implement CR_TEXT support.

**Comment by jayb-g** [comment]
Got it. What if I'm just using openvpn as server and not pritunl ?

**Comment by schwabe** [comment]
OpenVPN server itself does not implement 2FA. You always need to implement via management/script or plugin. And for a script the totpauth.py gives an example how to implement crtext.

**Comment by jayb-g** [comment]
I didn't know that.! Thanks.

So this is basically saying its only third-party or custom scripts that do the handling of 2FA codes and responses from server side. openvpn just allows for that by putting it in server config.

So if I'm using [this](https://github.com/zaheerahmad33/OpenVPN-2FA-GoogleAuth) I think it uses [Google PAM module](https://github.com/google/google-authenticator-libpam) , or if any other script such as python script shared by you, how to know if it uses CRV1 or CRTEXT for 2FA?

**Comment by jayb-g** [comment]
> There is already a better method called crtext/CR_TEXT that allows MFA without having to go through a disconnect/reconnect cycle.
> 
> Implementing the old CRV1 method is not quite as trivial as the app needs to learn that sometimes when a connection ended it did not really end but needs to be restarted in a weird way after getting user input.
> 

@schwabe can you please elaborate this more? Or share some references where this is clarified as in any official/unofficial documentation on same ? I tried to search but couldn't find anything.

I'm just using openvpn as server and client

**Comment by schwabe** [comment]
Via management:

https://github.com/OpenVPN/openvpn/blob/master/doc/management-notes.txt#L741

example script using script functionality:

https://github.com/OpenVPN/openvpn/blob/master/sample/sample-scripts/totpauth.py

**Comment by jayb-g** [comment]
👍 got it. I know this is not a forum to ask for help but I don't know how to configure the openvpn server so that it uses this.

What minimal pam.d/openvpn or server.conf configurations are required for this to work?

I'm trying to use pam_google_authenticator.so, that seems to be the only option for 2FA, are there any other alternatives? 

I'm trying to create a client bash wrapper that handles all the auth(normal/2fa - using expect or management script), up script, dynamically out of the box

So that it works on Linux and android as well(using your OpenVPN for Android) app

**Comment by jayb-g** [comment]
> Implementing the old CRV1 method is not quite as trivial as the app needs to learn that sometimes when a connection ended it did not really end but needs to be restarted in a weird way after getting user input.

Theoretically, how to identify such a case? I seem to be experiencing same, after sending otp to the server, mgt script sees auth failed and exits. 
Do you mean these auth failed are different and can be captured separately than the real auth failed ?

**Comment by schwabe** [comment]
> What minimal pam.d/openvpn or server.conf configurations are required for this to work?

the totpauth.py script has usage instructions in its comments in the top.

**Comment by schwabe** [comment]
> Theoretically, how to identify such a case? I seem to be experiencing same, after sending otp to the server, mgt script sees auth failed and exits.
> Do you mean these auth failed are different and can be captured separately than the real auth failed ?

you can read about the CRV1 protocol and how it works in management.txt in the openvpn repo.

**Comment by jayb-g** [comment]
So basically there's everything needed to know in management txt and the python sample. Let me go through those and get back after testing.

Thanks
