### ISSUE TITLE
Add Small Window feature

### ISSUE THREAD

**Issue by Korb** [schwabe/ics-openvpn#1770]
# General information
1. Android Version: Funtouch OS 14
2. Android Vendor/Custom ROM: Vivo
3. Device: T1 (4G, V2153)
4. Version of the app (version number/play store version/self-built): 0.7.53 (208) [f-droid](https://f-droid.org/en/packages/de.blinkt.openvpn/) (Aug 15, 2024)
 
# Description of the issue

The Small Window (aka **picture-in-picture** mode) feature allows you to display a window overlaying other apps and pin it to the edge of the screen as an always-on small label. The label can be freely moved along the side edges of the screen.

More details: Android Developers / Develop / Core areas / UI / Guides / [Support multi-window mode](https://developer.android.com/develop/ui/compose/layouts/adaptive/support-multi-window-mode)

**Comment by schwabe** [comment]
I know and understand what the picture in picture mode is but I fail to see a use-case for OpenVPN for Android.

**Comment by Korb** [comment]
In my country most international social networks and independent media are blocked, and VPNs are partially blocked. Current VPNs are unstable, and I need to have an indicator in front of me that this or that app or site is not working because there is no internet on the device due to a VPN' kill switch, or because the problems are not related to my network connection.

In `Small Window` mode (not `Mini window`, in which the widget becomes non-interactive), I will be able to change the connected VPN profile without the app manager.

**Comment by schwabe** [comment]
I am closing this bug because I see that status bar icon/notification as good enough indicator if VPN is working or not. Also this is not a feature that I will spend time one since I don't think it is a really important enough for to spend time on. Patches are welcome but I will not invest dev time myself.
