### ISSUE TITLE
"Block IPv6 (or IPv4) if not used by the VPN" doesn't seem to block IPv6

### ISSUE THREAD

**Issue by ValdikSS** [schwabe/ics-openvpn#1774]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: **10**
2. Android Vendor/Custom ROM: **Stock OS from LG**
3. Device: **LG V50**
4. Version of the app (version number/play store version/self-built): **0.7.53 f-droid**
 
# Description of the issue

I have VPN configuration file, where server assigns both IPv4 and IPv6, and also default routes over IPv4 and IPv6.
I want to use IPv4 (and default route over VPN's IPv4) only.

For this, I set:

1. Routing - Ignore pushed routes
2. Routing - Block IPv6 (or IPv4) if not used by the VPN
3. Routing - IPv4 - Use default route
4. and **NOT set** Routing - IPv6 - Use default route

All my IPv4 traffic is routed over VPN, **but IPv6 is routed over regular ISP (Wi-Fi connection)**.

If I understand "Block IPv6 (or IPv4) if not used by the VPN", it should block IPv6 traffic (neither redirect it over VPN nor allow it over ISP), but it does not.

# Configuration file

```
nobind
client

remote-cert-tls server

dev tun
proto tcp

resolv-retry infinite
persist-key
persist-tun

# Block outside DNS servers
setenv opt block-outside-dns

# OpenVPN 2.5 compatibility
setenv opt data-ciphers AES-128-GCM:AES-256-GCM

# Remote connections
remote-random
server-poll-timeout 15
connect-retry-max 20

<connection>
remote nl12.pvpn.pw 23
</connection>
<connection>
remote nl12.pvpn.pw 43
</connection>
<connection>
remote nl12.pvpn.pw 495
</connection>

<ca>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</ca>

<cert>
-----BEGIN CERTIFICATE-----
-----END CERTIFICATE-----
</cert>

<key>
-----BEGIN PRIVATE KEY-----
-----END PRIVATE KEY-----
</key>

```

The server pushes:

```
2024-12-04 18:32:11 us=822315 PUSH: Received control message: 'PUSH_REPLY,dhcp-option DNS 192.168.101.1,route-ipv6 2000::/3,redirect-gateway def1 bypass-dhcp,redirect-gateway ipv6,tun-ipv6,route-gateway 192.168.101.1,topology subnet,ping 35,ping-restart 180,ifconfig-ipv6 2002:c37b:dadd:1::2d/112 2002:c37b:dadd:1::1,ifconfig 192.168.101.45 255.255.255.0,peer-id 7,cipher AES-128-GCM'

```

**Comment by schwabe** [comment]
Your VPN uses IPv6, so the option to block IPv6 if the VPN does not use IPv6 is behaving like expected. Please read also the explaination under the option and not just the option name:

> This option instructs Android to not allow protocols (IPv4/IPv6) if the VPN does not set any IPv4 or IPv6 addresses.

Your VPN sets an IPv4 and IPv6 address, so this option does nothing in your case.

**Comment by ValdikSS** [comment]
So, is there any way to achieve what I want, without disabling "pull settings" for IP address and assigning it manually?
Is there any option to disable both IPv6 routes and IPv6 pushed address?

**Comment by schwabe** [comment]
you can always add pull-filter ignore ipconfig-ipv6 as custom options.
