### ISSUE TITLE
VPN getting disconnected and OpenVPNService getting ended after sometime

### ISSUE THREAD

**Issue by saadaq79** [schwabe/ics-openvpn#1778]
I want to keep the vpn and service running for more than days. Boot up is handled by the open vpn service but after one day vpn service gets terminated. I have written work manager to periodically monitor OpenVPNService but it doesnt restarts. It starts but some how management thread is null and then it ends service. 
Note that I have not written any server side pinging mechanism. So I want to stick with android solution. Let me know if im going or thinking in right direction. Also provide solutions to keep vpn connected no matter what and if gets terminated by OS then it should open again and make vpn connected. Thanks

**Comment by schwabe** [comment]
The app already has mechansim to ensure that it stays connected. What the log of the app sya?

**Comment by mitariq1984** [comment]
Does it stays connected in the state of background and also when the app is killed?

**Comment by saadaq79** [comment]
According to our logs, the service restarted by work manager but it didn't survive and ended up immediately. So the vpn stayed disconnected and the service ended as well. What we are trying is to revive the service of OpenVPN by monitoring with work manager periodically. Work manager r
uns according to logs, service also starts  and it shows notification OpenVPN along with no process running but it gets in the management thread [check](url) which is always null and eventually service ends. For reference im attaching vpn  logs here and notification reference image here
[logcache.txt](https://github.com/user-attachments/files/18237138/logcache.txt)
![vpn_disconnect](https://github.com/user-attachments/assets/cdfe92b3-5e28-45ce-b8d0-a7c96fed67a6)

**Comment by saadaq79** [comment]
Can we achieve always on feature without navigating to Android System UI? It works for always on feature but we need to enable it by default for open vpn app.

**Comment by schwabe** [comment]
You seem to want to hide your app's name. I have to assume that you have a good reason for doing that and that the reason is that you are violating the GPL. Unless you point out your app name and link to the software, we are done here.
