### ISSUE TITLE
"Trust this application" can't be checked on Android 4.3

### ISSUE THREAD

**Issue by GoogleCodeExporter** [schwabe/ics-openvpn#185]
```
What steps will reproduce the problem?
1. Upgrade an Android device to JellyBean 4.3
2. Try to use OpenVPN for Android to connect to a VPN
3. Note that the checkbox for "trust this application" in the popup is not 
greyed out, but cannot be checked (using the touchscreen).

What is the expected output? What do you see instead?
Behavior should be the same on 4.3 as on 4.2.2.

What mobile phone are you using?
Google/ASUS Nexus 7 (2011)

Which Android Version and stock ROM or aftermarket like cyanogenmod?
JellyBean 4.3, stock ROM.

Please provide any additional information below.

I am able to navigate to the "trust this application" checkbox using a 
Bluetooth keyboard, and check it with the enter key. From that point on, the 
application performs correctly.

This problem also occurs with other VPN apps on 4.3 (e.g. official OpenVPN), so 
it's not literally a bug in ics-openvpn. It's either a bug in 4.3, or an API 
change that all VPN apps will have to be changed  deal with. I'm posting this 
here in case it's the latter.
```

Original issue reported on code.google.com by `jfmcbra...@gmail.com` on 31 Jul 2013 at 1:41

**Comment by pnvmvk** [comment]
I am unable to navigate to the "trust this application" checkbox of psiphon app in micromax a120 with android 4.4

Solution please?

Could not achieve it with the above answers

**Comment by xDragonZ** [comment]
This is for OpenVPN not Psiphon.

You can't click the chrckbox because there's some app using overlay, please disable apps such app screen tint, battery saver app, or reboot your device and try again.

**Comment by jfrverdasca** [comment]
If you have some program like Twilight, flux or similar you cant check the "trust this application". Try disable your blue color filter application first and then try again.

It solve the "trust this application" problem for me!

**Comment by nutwut1** [comment]
> ```
> Open the Lux Dash and tap the settings icon. Tap "Advanced". Tap "Sleep List". 
> Tap "Add". Scroll down the list until you get to VPNDialogs, check the box by 
> it, then tap "Add".
> ```
> 
> Original comment by `jfmcbra...@gmail.com` on 13 Aug 2013 at 6:34

**Comment by Gavel1** [comment]
> ```
> What steps will reproduce the problem?
> 1. Upgrade an Android device to JellyBean 4.3
> 2. Try to use OpenVPN for Android to connect to a VPN
> 3. Note that the checkbox for "trust this application" in the popup is not 
> greyed out, but cannot be checked (using the touchscreen).
> 
> What is the expected output? What do you see instead?
> Behavior should be the same on 4.3 as on 4.2.2.
> 
> What mobile phone are you using?
> Google/ASUS Nexus 7 (2011)
> 
> Which Android Version and stock ROM or aftermarket like cyanogenmod?
> JellyBean 4.3, stock ROM.
> 
> Please provide any additional information below.
> 
> I am able to navigate to the "trust this application" checkbox using a 
> Bluetooth keyboard, and check it with the enter key. From that point on, the 
> application performs correctly.
> 
> This problem also occurs with other VPN apps on 4.3 (e.g. official OpenVPN), so 
> it's not literally a bug in ics-openvpn. It's either a bug in 4.3, or an API 
> change that all VPN apps will have to be changed  deal with. I'm posting this 
> here in case it's the latter.
> ```
> 
> Original issue reported on code.google.com by `jfmcbra...@gmail.com` on 31 Jul 2013 at 1:41
