### ISSUE TITLE
latest version breaks stuff

### ISSUE THREAD

**Issue by GoogleCodeExporter** [schwabe/ics-openvpn#196]
```
after last update i get this error
tls error unroutable control packet received from (si=3 op=p_control_v1)
restore backup works fine.

```

Original issue reported on code.google.com by `iamborg...@gmail.com` on 25 Aug 2013 at 6:23

**Comment by j796160836** [comment]
Thanks for your suggestion.
My router same as ASUS RT-N16 use is firmware
**Tomato Firmware v1.28.7501 MIPSR2Toastman-RT K26 USB VLAN-VPN**
also have the same problem. It wastes me tons of time....

Just update the firmware and problem solved.
I use 
**K26USB-1.28.AT-RT-N5x-MIPSR2-3.2-137-AIO.trx** 
works fine.
