### ISSUE TITLE
No routing on Cyanogenmod

### ISSUE THREAD

**Issue by GoogleCodeExporter** [schwabe/ics-openvpn#241]
```
I use Cyanogenmod version 3.4.10 (4.4.2), unfortunately it looks like the 
routing/ip setting does not work. Once connected I can not reach/ping any host 
(VPN or not) regardless of default routing enabled or not. It worked on 
original firmware once.
I don't know if it is related to Cyanogenmod or Android version, are you aware 
on any issues with Cyanogenmod.
Attached is the connection logfile.
```

Original issue reported on code.google.com by `thomas.h...@gmail.com` on 30 Mar 2014 at 12:30

Attachments:
- [htc.log](https://storage.googleapis.com/google-code-attachments/ics-openvpn/issue-241/comment-0/htc.log)

**Comment by schumi2004** [comment]
My apologies for commenting on a old issue but currently i'm experiencing the same behaviour as initially reported.

Once i make use of a ccd file all routes you push are just ignored/excluded.
Once i remove the ccd with content ifconfig-push 10.1.2.92 10.1.2.91 all is fine.

I'm running version 0.6.63 on CM14.1

**Comment by schwabe** [comment]
What does OpenVPN for Android report as installed routes?

Or can you provide a log to see if it is a bug in my APP or in cyanogenmod.

**Comment by schumi2004** [comment]
It should be in your mailbox ;)
