### ISSUE TITLE
Does --passtos works on android Client

### ISSUE THREAD

**Issue by TKR-US** [schwabe/ics-openvpn#336]
Hi,

When i mark a packet with a DSCP value, i have my value outside the vpn, but i can't find this value in openvpn encrypted packet, with android openvpn and linux server openvpn.

I put on Android Client just the option "--passtos"
Is openvpn android client really write the DSCP value in encrypted packets?

Regards

**Comment by schwabe** [comment]
Without root you cannot set dscp value so your observation is correct.
