### ISSUE TITLE
Gitter channel for the project

### ISSUE THREAD

**Issue by AlmogBaku** [schwabe/ics-openvpn#337]
## Following the discussion at https://github.com/schwabe/ics-openvpn/issues/226#issuecomment-92679146

Gitter allows us to chat about the project.. it's like an IRC channel for github, and it's free for OpenSource.
It's very popular and really nice (and increase the contribution from my experience at http://github.com/linnovate/meanio)

http://www.gitter.com

**Comment by schwabe** [comment]
I don't think this is necessary. This is my personal project with only me as developer. And I am on the generic openvpn channels on freenode.
