### ISSUE TITLE
Shortcut title not retain after reboot

### ISSUE THREAD

**Issue by NicolaF** [schwabe/ics-openvpn#342]
Hi Arne, 

When adding a VPN shortcut to the home screen (lollipop/CM 12.1), it it correctly created with the VPN configuration name as title. However, after rebooting device, all VPN shortcuts revert back to a fixed string, apparently activity name (vpn_launch_title).

Kind regards,
NicolaF

![screenshot_2015-04-27-11-12-56](https://cloud.githubusercontent.com/assets/147832/7344779/2b2c0dbc-eccf-11e4-828d-17803ecd27a9.png)

**Comment by schwabe** [comment]
Is that with the stock launcher or some third party launcher?

**Comment by NicolaF** [comment]
HI Arne,

It's Trebuchet from CM 12.1 (yesterday's nightly).

Cheers,
NicolaF

**Comment by schwabe** [comment]
I cannot reproduce this with Nova Launcher and the stock launcher on my Nexus 7. This sounds like a bug in Trebuchet

**Comment by NicolaF** [comment]
sad :( I'll wait for the next CM M build to report it.

Cheers!

NicolaF

**Comment by schwabe** [comment]
Closed since it is likely to be a bug in the launcher
