### ISSUE TITLE
segmentation fault when using pievpn directly

### ISSUE THREAD

**Issue by Hoeze** [schwabe/ics-openvpn#344]
I'm using Cyanogenmod12/Android 5.0.2 and tried to install the openvpn binary to /system/xbin:
I moved:
- libopenvpn.so/libopenvpnutil.so/libstlport_shared.so => /system/lib/
- pievpn => /system/xbin/openvpn

Result:

Sat May  2 16:15:50 2015 OpenVPN 2.4-icsopenvpn [git:HEAD-7aaf01766f971837] android-14-armeabi-v7a [SSL (OpenSSL)] [LZO] [SNAPPY] [LZ4] [EPOLL] [MH] [IPv6] built on May  2 2015
Sat May  2 16:15:50 2015 library versions: OpenSSL 1.0.1l 15 Jan 2015, LZO 2.07
...
Sat May  2 16:15:50 2015 Socket Buffers: R=[163840->131072] S=[163840->131072]
Sat May  2 16:15:50 2015 Protecting socket fd 4
Segmentation fault 

I'd need to use it directly for tap networking...

**Comment by schwabe** [comment]
although segfaulting is not nice, the binary does not work without the UI. Installing libstlport_shared.so to system/lib might be a really bad idea.

**Comment by schwabe** [comment]
Try these binaries: http://plai.de/android/standalone-binaries.tar

They are build with target linux and should work standalone.

**Comment by Hoeze** [comment]
Worked like a charm until today (thanks for that), but I've got a problem:
For any reason the standalone binaries ignore "dev tap"; they always use tun adapters.
How can I fix this?

**Comment by schwabe** [comment]
Hm, openvpn should not ignore an option. It should either give an or something else. Have you checked the log?

**Comment by Hoeze** [comment]
Yes... The problem was that /dev/net/tun did not exist... I symlinked the tun device to /dev/net/tun and now it's working...

I was confused because I did not use the tun device, but it seems like openvpn needs the tun device to work, independently from the chosen device type.

**Comment by jonpolak** [comment]
Hi @schwabe 
Using a barebones ROM (xtrestolite) which has no vpn-service; are the standalone binaries you provided in the repo sufficient? If so, does ics-openvpn look for them in /system/xbin?

**Comment by schwabe** [comment]
The standalone binaries are standalone. My app really only works with the VPN Services. OpenVPN settings might work with them (I never tested or used OpenVPN Settings)

**Comment by jonpolak** [comment]
Thank you for clarifying. Where is the standalone library repo? Is it
actively maintained?

**Comment by schwabe** [comment]
@jonpolak the standalone binaries were build from my android branch, there is a patch file in there that has to be aplied to the android makefiles to build static standalone binaries.

Not they are not maintained. I build them for people who wanted them and test native openvpn. I do not think that with Android 4.4+ complex routing infrastructure running OpenVPN directly is a good idea.
