### ISSUE TITLE
Name resolutions stops working after connecting to VPN

### ISSUE THREAD

**Issue by dmelo** [schwabe/ics-openvpn#345]
I have just bought a Samsung Galaxy S5. Running stock Android 5.0.

I have imported an UDP VPN that allows me to access my office's network. This credentials works fine on my old Galaxy S3. But I'm having trouble with the new phone.

Before connect to the VPN, the Internet works just fine. After connected. I can still ping local network, Internet IPs (like 4.2.2.1) and IPs from my office.

The trouble is that I can no longer resolve names. ping google.com returns "unknown host google.com".

I have tried with and without the option "Override DNS Settings by Server". Still no results.

**Comment by schwabe** [comment]
You are probably hitting a bug in Samsung's Android. See https://plus.google.com/117315704597472009168/posts/g78bZLWmqgD 
and the error message coming up in the version:

"Warning Samsung Android 5.0+ devices ignore DNS servers outside the VPN range. To enable DNS add a custom route to your DNS Server (%s) or change to a DNS inside your VPN range"

**Comment by dmelo** [comment]
Thank you for the advice. I will try this tonight.

**Comment by schwabe** [comment]
Closing for no reply and issue understood.
