### ISSUE TITLE
Add tls-version-min support

### ISSUE THREAD

**Issue by gec75** [schwabe/ics-openvpn#348]
I have problems connecting to RouterOS openvpn, and I need tls-version-min option.
Other people have similar problems, see here:
https://community.openvpn.net/openvpn/ticket/401

**Comment by schwabe** [comment]
No. Your problem is a different one. See http://ics-openvpn.blinkt.de/FAQ.html
Connections fails with SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure

Btw. ics-openvpn is master and suports the tls-min-version option already.

**Comment by gec75** [comment]
I haven't found that FAQ!
The official OpenVPN could connect and it has explicit tls-version-min option, so I thought that was it; but it does not support p2p topology, the only supported by mikrotik.
Unfortunately there are other mikrotik limitations, but that's another story.
Thanks again for the hint!
