### ISSUE TITLE
Android 5.1 force close

### ISSUE THREAD

**Issue by SplitR** [schwabe/ics-openvpn#349]
Force close in CyanogenMod 12.1 (Android 5.1.1)

**Comment by SplitR** [comment]
AutoVPN Dialog Confirm forces close in Android 5.1.1 (or at least the CyanogenMod version)

**Comment by SplitR** [comment]
AutoVPN Dialog Confirm forces close in Android 5.1.1 (or at least the CyanogenMod version)

**Comment by schwabe** [comment]
The auto confirm xposed hack is not needed in 5.0+ anymore since your decision is saved in Android.
