### ISSUE TITLE
support proguard

### ISSUE THREAD

**Issue by w7849516230** [schwabe/ics-openvpn#350]
will it support proguard in the future?

**Comment by schwabe** [comment]
I see no use for source code obfuscation in an open source project.

**Comment by schwabe** [comment]
Close since the original issue submitter did not respond back.

**Comment by ozgurrgul** [comment]
A lot of users from third-party countries are using VPN's with low featured devices, and every MB in their disk is important, proguard would help them to gain some disk space.

**Comment by schwabe** [comment]
The part of the app that is java is relatively small and most of the size of the apk comes from the native libraries, so I consider that not worth spending time on. If you disagree and have a working proguard configuration that makes an actual improvement, feel free to submit a pull request.

**Comment by tomty89** [comment]
If space is the concern probably having different builds available (2/3/2+3) would do us more good.

**Comment by schwabe** [comment]
Yeah, but so far there hasn't been any request for a smaller build. You can already build only 2/3 or 2+3 but I prefer not to spend my spare time in managing multiple play store entries, builds etc.
