### ISSUE TITLE
no dns and acces to router via wifi

### ISSUE THREAD

**Issue by hyperman75** [schwabe/ics-openvpn#351]
Hi

My openvpn server shutdown automatic do time schedule, and this has been working fine, whit openvpn.
i did have all trafic routed over vpn, and auto conect after reboot.
but, when I tried to get internet whit out openvpn, I cound not get normaly internet acces.
openvpn did crash, reboot of samsung notepro 12.2 lte, sm-p905 android 4.4.2 it is not rooted.
from console I can ping 8.8.8.8, but dns server is same as my default gw 192.168.0.1, and I cant get acces to my router from browser.

I did google a bit, my routes from tablet:
disconnected from openvpn:
~$ ip route show
default via 192.168.0.1 dev wlan0
default via 192.168.0.1 dev wlan0  metric 323
192.168.0.0/24 dev wlan0  scope link
192.168.0.0/24 dev wlan0  proto kernel  scope link  src 192.168.0.16  metric 323
192.168.0.1 dev wlan0  scope link

When connected to vpn, I do get this line also:
10.8.0.4/30 dev tun0  proto kernel  scope link  src 10.8.0.6

I think that the vpn routes is active when boot and there should only be one set of  default route.
how to remove?

Best regards
Jesper

**Comment by hyperman75** [comment]
Sorry, my router did forward packets and dns to other units, but no web interface.
reboot of router and I have webinterface, internet whit out vpn again and of course whit vpn.
I cant figure why I did not have dns on this unit and did on other.

**Comment by rcs1965** [comment]
Ok

**Comment by rcs1965** [comment]
Fuck you people. I am going to the police as I know about the root serveilance on my cell phone
 I have record of everything you guys did.
