### ISSUE TITLE
nothing happens after ---  mSocket = mServerSocket.accept(); 

### ISSUE THREAD

**Issue by youngmob** [schwabe/ics-openvpn#352]
For some devices, after calling below code from OpenVPNManagementThread.java

```
 mSocket = mServerSocket.accept();
```

it just fails with no exception. This happens mostly on Samsung Galaxy with Lollipop (devices). But not always.. any idea?

**Comment by schwabe** [comment]
I need more information. Are you using a custom build version? What is the log saying? I never have heard any report that sounds like this.

**Comment by youngmob** [comment]
sorry it was bad on my side.. 64 bit device was getting the library for 32 bit, so was crashing.
