### ISSUE TITLE
Remove socket files when app is not running

### ISSUE THREAD

**Issue by mase76** [schwabe/ics-openvpn#353]
Hi!
There are problems with this app and Oandbackup. The file
/data/data/de.blinkt.openvpn/cache/mgmtsocket is not copyable.
I get a message, "no such file or directory". I filed a bug to
Oandbackup, to stop running apps before backing them up.
But the above file should be removed, when the app is not
running. I think, it is only needed when running and can be
recreated then.

**Comment by schwabe** [comment]
that is clearly a bug in Oandbackup. It should recognize special files like sockets by using stat and try not to read them.
