### ISSUE TITLE
Android client needs ability to change default directory from "sdcard"

### ISSUE THREAD

**Issue by tcreek** [schwabe/ics-openvpn#358]
This is being brought over from:

https://community.openvpn.net/openvpn/ticket/448

From last comment I am not sure how it is "notabug" when in fact I have verified the software does not look for the certificates in the same directory as the ovpn file.

**Comment by schwabe** [comment]
Can you give the import log?

**Comment by tcreek** [comment]
I am going to mark this as resoled. It seems in the newest version it was fixed, and setup is much easier now.
