### ISSUE TITLE
Hi, if I want to use a higher openvpn version, like 2.3.6, how should I modify it? 

### ISSUE THREAD

**Issue by parsons-smith** [schwabe/ics-openvpn#360]

**Comment by schwabe** [comment]
Note that ics-openvpn uses OpenVPN -master, which is newer/has more features than 2.3.6.

Of course you can backport the changes needed for ics-openvpn to 2.3.6 and replace that. See the icsopenvpn branches in the openvpn repository

**Comment by rockstore** [comment]
I wonder if I want to use higher or lower openvpn version,can I just replace the openvpn folder of the project,If not ,which files I need to modify,thank you very much

**Comment by schwabe** [comment]
No. The version openvpn needs to match the version OpenVPN for Android expects or better it needs to provide the APIs OpenVPN for Android uses.

While not being difficult to change the openvpn version in OpenVPN for ANdroid, there should be no need to do this. If something does not work with OpenVPN for ANdroid's OpenVPN version that is a bug that needs to be fixed.

**Comment by rockstore** [comment]
Now , I want to give openvpn a  traffic-obsfucate-patch,the patch matchs openvpn 2.3.6,however,after   I put this patch for openvpn for android and enable it,it can not work, just tell me no process.Can you  give me some advice about how can I give this patch for openvpn for android

**Comment by schwabe** [comment]
the error is probably a different one. Look through your log why it does not start openvpn.
