### ISSUE TITLE
slow to connect (compare to openvpn connect)

### ISSUE THREAD

**Issue by youngmob** [schwabe/ics-openvpn#361]
Is there anything that can be done to increase speed to connect vpn?
with the same profile OpenVPN connect is much faster.

**Comment by schwabe** [comment]
The reason why OpenVPN connect connects faster is not understood so I have no idea what is happening. Also I do not experience this with my own server so I cannot test/fix/diagnose the problem myself.

**Comment by youngmob** [comment]
it's taking about 10 - 13 seconds to connect to our server using Openvpn for Android. Any suggestions? Is there any server side configuration changes needed for faster connection?

**Comment by schwabe** [comment]
If you can provide a tcpdump pcap of a connect with openvpn connect vs one with openvpn for android that could help diagnosing the problem. As I said, I am not what the problem is and where openvpn spends its time.

**Comment by ozexpert** [comment]
Thanks anyways for your kind response.

**Comment by youngmob** [comment]
Thanks anyways for your kind response.

**Comment by schwabe** [comment]
Can you try this version and see if it makes a differences? http://plai.de/android/ics-openvpn-0.6.30-min-mtu-1280.apk. Also can you send me a log of the connection attempt with that version and with the normal version?

**Comment by AlmogBaku** [comment]
I can verify this issue on my devices too...

**Comment by AlmogBaku** [comment]
About the new version you attached- it doesn't even connect to my server.. the log says "Failed to open tun interface"

**Comment by schwabe** [comment]
@AlmogBaku without any log there not much I can do.

**Comment by ozexpert** [comment]
Hi, I was looking at the code and found out that in OpenVpnManagementThread.java, there's a code block inside openManagementInterface() function. with 8 tries of sleep.

looking at the log, most of the times it tries for 8 times then moving forward doing nothing. 
I tried removing this part out and tried and it reduces around 3 seconds of connecting VPN. 

however, seems without this code, pause -> resume process became buggy. Sometimes, it hanged. 
can you explain why there's this sleep(300)?

**Comment by schwabe** [comment]
@ozexpert The code in OpenVPNMangement thread blocks but also runs in extra thread. 

The number of tries should not matter since it binding should work on the first try. The 300ms sleep and retrying is busy waiting if an old openvpn process needs time to die which exactly is what happens on stop/start of a VPN.

**Comment by schwabe** [comment]
Commit 649e1ac59bd174d65e5a4fb442e39e2a5968226c should make connecting faster

**Comment by AlmogBaku** [comment]
@schwabe this is still not solved, It takes 9s to establish connection.
logs of server & client: https://gist.github.com/AlmogBaku/3406929abb600808274b

Also, you mention pcap files can help.. do you want a client or a server pcap file?

**Comment by xDragonZ** [comment]
I have tested the latest commit too, looks like it's not resolved. Compare to OpenVPN connect, the time in connection compare to OpenVPN for android is quite different.

**Comment by schwabe** [comment]
@AlmogBaku Your log shows
 [Jul 10, 16:21:29] [INFO] OpenVPN 2.4-icsopenvpn [git:HEAD-24e617229f654555] android-14-armeabi-v7a [SSL (OpenSSL)] [LZO] [SNAPPY] [LZ4] [EPOLL] [MH] [IPv6] built on Jul  7 2015

Which is a different Git version from the head of the openvpn module, also built on Jul 7 indicated that it is older than my commit :)

**Comment by AlmogBaku** [comment]
Yeha, its just on my fork. I'll try later again to test it on master and
will update the logs accordingly

On Friday, July 10, 2015, Arne Schwabe notifications@github.com wrote:

> @AlmogBaku https://github.com/AlmogBaku Your log shows
> [Jul 10, 16:21:29] [INFO] OpenVPN 2.4-icsopenvpn
> [git:HEAD-24e617229f654555] android-14-armeabi-v7a [SSL (OpenSSL)] [LZO]
> [SNAPPY] [LZ4] [EPOLL] [MH] [IPv6] built on Jul 7 2015
> 
> Which is a different Git version from the head of the openvpn module, also
> built on Jul 7 indicated that it is older than my commit :)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/schwabe/ics-openvpn/issues/361#issuecomment-120503204
> .

## 

---

Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by schwabe** [comment]
Yeah, still even with your fork the build date should be Jul 10 :)

**Comment by AlmogBaku** [comment]
hahaha, my bad...
Anyway.. your update indeed improved the time to connect speed! But unfortunately, it's still quite  slow(improved from 9s to 7s) compared to the commercial version.

I also notice that the server logging the requests after about 3s from the click..

Attached updated logs + ovpn file:
https://gist.github.com/AlmogBaku/4f9a8965088ee0fc7ae4

**Comment by ghost** [comment]
Might I suggest that this ticket be re-opened? For OpenVpn is still slow to connect - some nine seconds (on a quad-core i7) and more (perhaps up to twenty seconds) when the system is booting. Compare Wireguard, on a similar processor: < 3 seconds, and not much more on boot (though admittedly I am comparing OpenVpn on Windows 8.1 to Wireguard on Linux).

**Comment by schwabe** [comment]
@CottonEaster I am pretty sure there is no android phone with a quad core i7. So you are wrong here.

**Comment by ghost** [comment]
@schwabe 

Apologies: I had thought that this was the bugtracker for openVpn as such, including the Windows version (and it was the Windows version of which I spoke).
