### ISSUE TITLE
IPV6 not supported for server IP?

### ISSUE THREAD

**Issue by inducer** [schwabe/ics-openvpn#364]
Connecting to my VPN would take multiple minutes. What solved this for me was replacing the server FQDN with a static IPV4 address. The phone has working V6 connectivity, and the server has a V6 address in DNS, but it seems that the connection does not get established until the V6 connection times out.

If these observations are correct, might it not make sense to prevent resolving V6 addresses in the first place? (I'm on CM12.1 on a "klte" (Samsung Galaxy S5) phone, nightly build from 6/21.)
#361 may be related.

**Comment by schwabe** [comment]
No, 361 is probably not related. 361 is probably caused by too small packet and too many roundtrips. And IPv6 generally works well. Ideally, you should include a log.

**Comment by inducer** [comment]
Log: https://gist.github.com/inducer/190ca8ed4c2fce1e6b3a

FWIW, I've checked, and my phone's ipv6 connectivity is otherwise fine, at least for HTTP.

**Comment by schwabe** [comment]
I did my own tests and I fear this is yet another "Samsung" bug. On my Nexus 7 and Sony Z1c it perfectly connect over IPv6 LTE (T-mobile.de) and IPv6 WiFi.

**Comment by schwabe** [comment]
Just another note, are you sure your OpenVPN server listens on IPv6? Check with ss and make sure that your server configuration has proto udp6 in it.

**Comment by inducer** [comment]
Whoops. You're totally right. I was missing `proto udp6`. Sorry for the noise.
