### ISSUE TITLE
Remote Example project

### ISSUE THREAD

**Issue by noman-noor** [schwabe/ics-openvpn#366]
Will remote example project works without openvpn Android application or not?
I have deleted main openvpn android app and run Remote Example project is getting crash and said 

 Attempt to invoke interface method 'android.content.Intent de.blinkt.openvpn.api.IOpenVPNAPIService.prepareVPNService()' on a null object reference
            at de.blinkt.openvpn.remote.MainFragment.prepareStartProfile(MainFragment.java:272)

**Comment by schwabe** [comment]
No, the OpenVPN for Android app is required for the remote example project. The example could be probably extend to warn if OpenVPN for Android is not installed.
