### ISSUE TITLE
Submodule `openvpn` reference `6b4fee2f` is broken

### ISSUE THREAD

**Issue by AlmogBaku** [schwabe/ics-openvpn#371]
@schwabe this revision is broken, it's always throws:

```
fatal: reference is not a tree: 87743102dcff9d9beef0f6b3788da21a6b4fee2f
```

(even on separate cloning of the submodule)

Please use this instead:

```
87743102dcff9d9beef0f6b3788da21a6b4fee2f
```

**Comment by seyymon** [comment]
i have same problem.  Fail in command "git submodules update":
Cloning into 'main/openvpn'...
remote: Counting objects: 14220, done.
remote: Compressing objects: 100% (48/48), done.
remote: Total 14220 (delta 31), reused 0 (delta 0), pack-reused 14172
Receiving objects: 100% (14220/14220), 8.45 MiB | 948 KiB/s, done.
Resolving deltas: 100% (10633/10633), done.
fatal: reference is not a tree: 87743102dcff9d9beef0f6b3788da21a6b4fee2f
Unable to checkout '87743102dcff9d9beef0f6b3788da21a6b4fee2f' in submodule path 'main/openvpn'
