### ISSUE TITLE
use gradle instead of hardcoded libs

### ISSUE THREAD

**Issue by AlmogBaku** [schwabe/ics-openvpn#372]
we can use:

```
    compile 'com.madgag.spongycastle:core:1.51.0.0'
```

and android-supportlibraries gradles instead of the hardecoded files

**Comment by schwabe** [comment]
For spongycastle that is probably true. For Android support libraries not really. 

The files are not only copied but also modified to use the Fragment instead of CompatFragment. Long story short: PreferenceFragment (which is heavily used) is incompatible with the support library.

**Comment by AlmogBaku** [comment]
can we reopen it for spongycastle?

**Comment by schwabe** [comment]
Yeah. But I am wary using the full spongycastle library as dependency. The project uses just a tiny part of spongycastle that has been well tested on many Android platform. I do not want to introduce new bugs by depending on the library.

**Comment by AlmogBaku** [comment]
I'm using it over than 6 months on my environment.. it works great

**Comment by maniac103** [comment]
@schwabe No sure whether you're aware yet, but there is a preference support library which includes PreferenceFragment now.

**Comment by schwabe** [comment]
@maniac103 Yes, I noticed that. I haven't had time to really look into this. Still on my todo list

**Comment by schwabe** [comment]
Will look into it when I have time.
