### ISSUE TITLE
Re-install Issue

### ISSUE THREAD

**Issue by harold-hernandez30** [schwabe/ics-openvpn#373]
Device: Samsung Galaxy S4 (GT-I9505)
OS: 5.0.1
ics-openvpn version: v0.6.26
(Edit: also tried on latest version)

I have an issue with a certain use-case: When I first install the app (ics-openvpn), and add my own opvn imported file and click on the item for that profile, all is okay. I get the dialog by Android that says "this app is requesting permission to set up a VPN connection..." Click on OK and all is well. I get a connected status. 

I know you'll get the dialog the first time when you startActivityForResult() on the VpnService.prepare(context), and I know that you'll get null the second time. 

Issue:
The problem is when I re-install the app, I try to load the profile again, I get the following error log:

2015-07-09 22:18:24 Disallowed VPN apps: 
2015-07-09 22:18:24 No DNS servers being used. Name resolution may not work. Consider setting custom DNS Servers. Please also note that Android will keep using your proxy settings specified for your mobile/Wi-Fi connection when no DNS servers are set.
2015-07-09 22:18:24 MANAGEMENT: CMD 'needok 'OPENTUN' cancel'
2015-07-09 22:18:24 MANAGEMENT: Client disconnected
2015-07-09 22:18:24 ERROR: Cannot open TUN
2015-07-09 22:18:24 MGMT: Got unrecognized command>FATAL:ERROR: Cannot open TUN
2015-07-09 22:18:24 Exiting due to fatal error
2015-07-09 22:18:24 Process exited with exit value 1

(Note: I think you can also replicate this on the latest version, but what I get is 
OpenSSL: error:14077410,routines:SSL23_GET_SERVER_HELLO:sslv3 )

The issue is fixed when:
- Restarting the phone, and I would get the dialog for the Android VPN permission
- Starting a different app that would start the VpnService.prepare(context), which according to the Android documentation, should revoke the the ics-openvpn app's access to the vpn service. If I start the ics-openvpn app again, and tap on the profile, I get the dialog, and all is okay again. (Edit 2: only works when re-installing the app)

Edit 3:
I'm getting a "Error: broken pipe" after I try the "Starting a different app that would start the VpnService.prepare(context)" solution.  Here's the log:

07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: Local Options hash (VER=V4): 'db02a8f8'
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: Expected Remote Options hash (VER=V4): '7e068940'
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: TCP/UDP: Preserving recently used remote address: [AF_INET]72.13.231.243:443
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: Socket Buffers: R=[1048576->131072] S=[1048576->131072]
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: Attempting to establish TCP connection with [AF_INET]72.13.231.243:443 [nonblock]
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: MANAGEMENT: >STATE:1436545962,TCP_CONNECT,,,
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: Protecting socket fd 4
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: MANAGEMENT: CMD 'signal SIGINT'
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: Protecting socket fd 4
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: MANAGEMENT: TCP send error: Broken pipe
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: MANAGEMENT: Client disconnected
07-11 00:32:43.109    3170-7684/com.csipsimple D/OpenVPNLog﹕ log status: VERBOSE, message: MANAGEMENT: Triggering management exit

Edit 4:
Please disregard the Edit 3 issue, it was due to multiple calls to LaunchVPN(). But the issue still remains for the ERROR: Cannot open TUN

**Comment by schwabe** [comment]
Yes that is a known bug in Android 5. See the FAQ.

**Comment by harold-hernandez30** [comment]
Thanks for confirming. Didn't read the FAQ, sorry. Appreciate the reply, though.

**Comment by schwabe** [comment]
No problem, the nice thing of a FAQ that you can point users to it :)

**Comment by schwabe** [comment]
@harold-hernandez30 Your project seems not have an issue tracker so I try it this way.

It would be nice (and confornming to the license) if you could add the copyright dialog into your app stating that your software is GPL and incoperates my code. Thanks!

**Comment by harold-hernandez30** [comment]
Will do! Though I have to look into how to do that yet. Kind of new to licensing stuff. :)

**Comment by schwabe** [comment]
@harold-hernandez30 if you have questions about license just write me an email.

**Comment by harold-hernandez30** [comment]
@schwabe - will do. As soon as I find out where you're email is. :) Currently trying to look for it. Sorry, I'm half-awake. :)

**Comment by schwabe** [comment]
arne-openvpn@rfc2549.org
