### ISSUE TITLE
Start apk on succesful connect (Lack of Doku? not possible?)

### ISSUE THREAD

**Issue by ozett** [schwabe/ics-openvpn#374]
hi, sorry for bothering in here, but as i read the whole faq and most issues here, i dont know where to go next to ask this question:

 is it possible to start another app on my android (5) phone after a succesful connection? must this be done with android intends? tasker-apk? llama-apk? vpn-config? i didnt found a clue...

or is this not possible?

wonderful apk, very helpful, thanks a lot,
regards, toz

**Comment by schwabe** [comment]
No, it is not implemented in openvpn for android itself. But there is a 3rd party tasker plugin that should work.
