### ISSUE TITLE
OpenVPN fails to connect after Anroid 4.4.2 has been rooted

### ISSUE THREAD

**Issue by rdarioc** [schwabe/ics-openvpn#376]
I need your help on how to upload all the relevant logs useful to fix this issue.

**Comment by rdarioc** [comment]
I will follow the following instructions to upload the verbose log:

> The OpenVPN for Android has not the permission to write on the SD Card. Using 
> log /data/data/de.blinkt.openvpn/cache/openvpn.log will work but you need root 
> to access it

**Comment by schwabe** [comment]
You could first start to simply share the in app log.

**Comment by rdarioc** [comment]
I haven't forgotten. I am trying hard to get those logs as promised!

In the meanwhile, the VPN provider is hide.me, the protocol used is, of course, OpenVPN, the encryption is AES 256 over tcp and port 53. 

The provider provides a certificate which is, correctly, included in the configuration file.

This certificate is authenticated by a certification authority.

Now, just speculating, could it be that after rooting the certificates are removed AND OpenVPN fails to authenticate the certificate? If so, could I add manually the certificate (file .pem) provided by the VPN provider into the list of trusted certificates to by-pass the issue?

Again, just speculation, before being finally able to upload the log and I apologize in advance if I just said a bunch of non-sense.

**Comment by rdarioc** [comment]
Here I am with a first log. 
I just cut the part that reports the error in the authentication:

---

2015-07-22 08:19:33 ++ Certificate has EKU (str) TLS Web Server Authentication, expects TLS Web Server Authentication
2015-07-22 08:19:33 VERIFY EKU OK
2015-07-22 08:19:33 VERIFY X509NAME ERROR: C=MY, ST=Wilayah Persekutuan, L=Labuan, O=eVenture Limited, CN=*.hide.me, must be nl.hide.me
2015-07-22 08:19:33 OpenSSL: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

---

Any idea?

Thank you in advance for your support

**Comment by schwabe** [comment]
Better ask the hide.me support. That sounds like their ovpn config file
are broken.

**Comment by rdarioc** [comment]
Well, the thing is that with the very same ovpn config file, sometimes it works, sometimes it doesn't.

I am contacting the hide.me guys now but, for me to understand, i believe the X509 information is kept within the .pem file, right? And it seems like they give a certificate that has as CN=*.hide.me while instead it should be nl.hide.me?

Is in any way OpenVPN involved in the verification of the X509? If so, how can it be instructed in order to accept as valid a name like nl.hide.me against an X509 that reports CN=*.hide.me ?

Your help will allow me to be more specific with those people at hide.me

Thank you in advance

**Comment by schwabe** [comment]
I think OpenVPN never supported wildcard CNs. The config file probably has an entry that specifies that OpenVPN should verify the certificate again nl.hide.me.

The verification option of the config is simply not matching the certificate.

**Comment by rdarioc** [comment]
Solved. By mistake in the OpenVPN tab Authentication/Encryption I must have checked the Certificate Hostname check. By removing this check it connected without problems.

Sorry for this inconvenience an my compliments to your great job.
