### ISSUE TITLE
App crashes on import of OVPN profile

### ISSUE THREAD

**Issue by nickolasclarke** [schwabe/ics-openvpn#382]
I have an Meizu MX5 and when I try to import an ovpn profile file, the app simply freezes and requires a forced shutdown. This may be an issue with the latest update to flymeOS from meizu, as I know I have successfully imported a ovpn profile file in the past, but that was some time ago and it is possible that changes in the app itself may have caused the issue. If someone is willing to work with me, I am more than willing to help debug this.

**Comment by schwabe** [comment]
You could share the ovpn profile with me I can see if the same crash happens for me too.

**Comment by aminbolehvpn** [comment]
I had quite a similar issue but the version I'm having was compiled with SDK 5.0.1. Recompiling with latest SDK 5.1.1 resolves it. 
Before this, SDK 5.0.1 will work with previous Android versions but crashed on 5.1.1.

**Comment by schwabe** [comment]
@aminbolehvpn Change of sdk should not lead to crashes. 

I am closing the ticket since the problem is unclear and information is too sparse. Feel free to reply and add the required information to reopen the ticket.

**Comment by nickolasclarke** [comment]
@schawbe sorry I thought I had replied to this but apparently not. I can share the profile with you, though it is possible it was simply a bad copy. I pulled it down again from my server and I could import properly, albeit the workflow was slightly different. I simply tried to open the file from my download manager and it suggested the app to handle the file. If you want to chase this further, please let me know how you would like the profile to be sent to you.

**Comment by schwabe** [comment]
If you cannot reproduce the crash is unlikely that I can reproduce it.
