### ISSUE TITLE
Hide option to send config/generated config.

### ISSUE THREAD

**Issue by bpvelandy** [schwabe/ics-openvpn#384]
I have developed a application to handle ICS OpenVPN Android application to start the VPN connection as  remotely. But When the user is connected it shows the VPN log and the configuration details. Is there any option to disable or hide configuration details and its sharing option? Since this seems to be an issue because  the developer should be given an option to make the config private or public.

**Comment by schwabe** [comment]
Could you describe the use case in which you would benefit from hiding the configuration?

**Comment by bpvelandy** [comment]
When companies provide VPN only to specific devices , the end user who using the VPN can copy the config to different device without the permission of VPN Provider.So if the VPN Provider is given an option to disable the copy or misuse more VPN Provider will use OpenVPN than Private VPN as the security level is increased.

**Comment by schwabe** [comment]
Well. You cannot really protect against the user copying the information from the device (adb backup, rooted device etc,...). Also most of the genreated configuration is also contained in the log itself.  I also like to have a little transparency in the app.

What parts of the configuration do you think need to be protected? I think not displaying the private key in the generated configuration should be enough to stop users from copying the profile.
