### ISSUE TITLE
auth-nocache not imported

### ISSUE THREAD

**Issue by RuiSantos76** [schwabe/ics-openvpn#385]
Hi,

Just to report that, when importing an .ovpn file with auth-nocache inside, OpenVPN for Android will not import it to Advanced -> Custom Options.
I'm using a relative standard .ovpn configuration, with these extra settings:
- pkcs12 inline (with password)
- verify-x509-name <CN>
- remote-cert-tls server
- tls-auth inline (with key-direction 1)
- cipher AES-256-CBC
- auth SHA256
- comp-lzo
- verb 3

In my case, specifically, it doesn't bother me too much, but it might for others.

If you require any extra help on debugging and or testing this issue, please do let me know.

Regards,
Rui

**Comment by schwabe** [comment]
auth-nocache is not imported on purpose. The app does not work without the option. Asking a password on demand is simply not implemented.
