### ISSUE TITLE
openssl 1.0.1l is used which has known security flaws

### ISSUE THREAD

**Issue by acdmail** [schwabe/ics-openvpn#387]
hi,
It seems that openvpn is linked to old buggy openssl version 1.0.1l
Could this be fixed please

Thanks

**Comment by acdmail** [comment]
Hello,
Could you advise please if there are any plans to fix this in the near future.
Thanks in advance

**Comment by schwabe** [comment]
Yeah. Lack of time currently. But there is not really a critical bug that is fixed that affects OpenVPN. Android itself (5.1.1) uses exactly the same OpenSSL library.

**Comment by acdmail** [comment]
hi Arne,
Thanks for your response.
Agree with your point that it is not so critical, however there are two points in here:
- Google Play already stopped to accept the updates to the packages with mentioned OpenSSL library as result it will be impossible to publish ICS OpenVPN in Google Play and for sure all the other apps based on OpenVPN libraries you provide will have the same issues
- people are a bit paranoiac nowadays this is why many use vpn software  and would prefer to have at least the known issues to be fixed

Thank you for great app

**Comment by schwabe** [comment]
@acdmail When did that happen?

Problem with a new version is that Google has stopped porting OpenSSL libraries to Android. Before I could just import the newest version. Now it seems I have to do it on my own.

**Comment by acdmail** [comment]
It happened recently can't say the exact date, but the warning regarding the statically linked openssl libraries was in place for pretty much time then suddenly they stopped to accept the apps updates with something like:
"Your app submission has been rejected for using a version of OpenSSL that has multiple security vulnerabilities for users. This is a violation of our dangerous products policy. If this APK was an app update, the previous version is still available on Google Play. Please review the OpenSSL Security Advisory, upgrade OpenSSL to versions 1.0.1h, 1.0.0m, 0.9.8za, or higher and submit your app again. To confirm you’ve upgraded correctly, submit the updated version of the app(s) to the Developer Console and check back after five hours. Additional details have been emailed to the account owner."
