### ISSUE TITLE
failed to connect after upgrade to 0.6.35

### ISSUE THREAD

**Issue by seanlis** [schwabe/ics-openvpn#389]
After upgrading to 0.6.35 from google play, it always got the following error:

```
Options error: Unrecognized option or missing or extra parameter(s) in /data/data/de.blinkt.openvpn/cache/android.conf:18:ifconfig (2.4_master)
```

**Comment by schwabe** [comment]
0.6.35 has a stricter config check. Your ifconfig line probably has extra argument. If you share your config with me I can take a look.

**Comment by seanlis** [comment]
Hi, 

the ifconfig line is

```
ifconfig 10.82.0.2 10.82.0.1 255.255.255.255
```

I'm using a static key.

I've tested with other previous versions. The last working version is 0.6.30. All newer versions would encounter error.

**Comment by schwabe** [comment]
Yes, previous version did not do check for extra arguments. Ifocnfig takes only 2 arguments. The 255.255.255.255 argument is an error.

**Comment by seanlis** [comment]
The 255.255.255.255 argument was auto generated. How to remove it with the GUI? 
My device is unrooted, I can't modify it manually.

**Comment by schwabe** [comment]
The UI should not autogenerated this. Unless you give the UI the wrong input.

**Comment by seanlis** [comment]
OK. Thank you for the help. 
I'll see to the UI options later.
