### ISSUE TITLE
Error while writing minivpn binary

### ISSUE THREAD

**Issue by bkshukla** [schwabe/ics-openvpn#392]
While running the app it gives me an error :
Error while writing minivpn binary.

And the logs are below :
               Failed getting assets for archicture armeabi-v7a
               Failed getting assets for archicture armeabi
               Error writing minivpn binary

When I am trying to build the code as suggested the .so files are not being generated.
Below mentioned are the steps that I am following :
Step 1:
          /Desktop/NEW/ONE/ics-openvpn/main/lzo$ autoreconf -vi
then I can see
         autoreconf: Entering directory `.'
         autoreconf: configure.ac: not using Gettext
         autoreconf: running: aclocal -I m4
         autoreconf: configure.ac: tracing
         autoreconf: running: libtoolize --copy
         autoreconf: running: /usr/bin/autoconf
         autoreconf: running: /usr/bin/autoheader
         autoreconf: running: automake --add-missing --copy --no-force
         autoreconf: Leaving directory`.'

Step 2:
        /Desktop/NEW/ONE/ics-openvpn/main/lzo$ ./configure

Step 3: 
        /Desktop/NEW/ONE/ics-openvpn/main/lzo$ make
then it gives me
       make  all-am
       make[1]: Entering directory `/home/user/Desktop/NEW/ONE/ics-openvpn/main/lzo'
       make[1]: Leaving directory`/home/user/Desktop/NEW/ONE/ics-openvpn/main/lzo'

Besides I have added 
ACLOCAL_AMFLAGS = -I m4
in Makefile.am and:

AC_CONFIG_MACRO_DIR([m4])
in configure.ac 
as mentioned here : http://stackoverflow.com/questions/16657991/glibtoolize-on-macos-tells-me-to-consider-adding-i-m4-to-aclocal-amflags-but

can you please tell me what is wrong with the process that I am following ?

**Comment by schwabe** [comment]
Your process is really wrong. THere is a readme that tells you how to build the app.
