### ISSUE TITLE
Remote App Removed- But the connection is on in the ICS OpenVPN

### ISSUE THREAD

**Issue by bpvelandy** [schwabe/ics-openvpn#394]
Hi,

Please provide a option to disconnect the vpn when the remote app is uninstalled from the device. Where remote application used IPC to establish the connection and connection will not be terminated when the app is uninstalled.

Regards
Bijesh

**Comment by schwabe** [comment]
I am trying to understand the use case before implementing anything that is overkill. 

I am assuming that is for profiles that are using "public void startVPN(String inlineConfig) ", i.e. a temporary profile, right?
