### ISSUE TITLE
NEXUS PLAYER:  Missing setup buttons following ATV 5.1.x update

### ISSUE THREAD

**Issue by SpinControl** [schwabe/ics-openvpn#399]
For the Nexus Player (NP), OpenVPN is now missing the ADD and IMPORT buttons in the upper right following the ATV 5.1.x update.

If a fix is not available for 5.1.x, is OpenVPN supported in Android M for NP?

**Comment by schwabe** [comment]
I am aware of the issue.

Unfortunately, menus are not supported on Android TV. Fixing this means that I need to design extra code/activities/layout for Android TV.

**Comment by SpinControl** [comment]
Thanks, Arne.
A suggestion:  If you make it a pay app (e.g. "OpenVPN for AndroidTV"), I'd pay for it and your time.  
I'm sure others would as well.  With the enhancements coming to ATV, I don't want to get stuck on Android TV 5.0.

If you chose not to do that, but would rather update the current app, count me in as one who will gladly donate to you.

Thank you for your time.
