### ISSUE TITLE
BUILD FAILED - Could not resolve all dependencies (com.android.support:*)

### ISSUE THREAD

**Issue by mdPlusPlus** [schwabe/ics-openvpn#404]
running `gradle build` results in   

> FAILURE: Build failed with an exception.
> 
> \* What went wrong:
> A problem occurred configuring project ':main'.
> > Could not resolve all dependencies for configuration ':main:_normalDebugCompile'.
>    > Could not find com.android.support:support-annotations:23.0.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.pom
>          https://repo1.maven.org/maven2/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.jar
>      Required by:
>          ics-openvpn:main:unspecified
>    > Could not find com.android.support:cardview-v7:23.0.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.0.1/cardview-v7-23.0.1.pom
>          https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.0.1/cardview-v7-23.0.1.jar
>      Required by:
>          ics-openvpn:main:unspecified
>    > Could not find com.android.support:recyclerview-v7:23.0.1.
>      Searched in the following locations:
>          https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom
>          https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar
>      Required by:
>          ics-openvpn:main:unspecified

Adding `--info` gives the following additional information:   

> Resource missing. [HTTP GET: https://repo1.maven.org/maven2/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.pom]
> Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/com/android/support/support-annotations/23.0.1/support-annotations-23.0.1.jar]
> Resource missing. [HTTP GET: https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.0.1/cardview-v7-23.0.1.pom]
> Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/com/android/support/cardview-v7/23.0.1/cardview-v7-23.0.1.jar]
> Resource missing. [HTTP GET: https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.pom]
> Resource missing. [HTTP HEAD: https://repo1.maven.org/maven2/com/android/support/recyclerview-v7/23.0.1/recyclerview-v7-23.0.1.jar]

**Comment by schwabe** [comment]
You need to install the support library repository.

**Comment by mdPlusPlus** [comment]
~~And how would I do that? The build script is looking for non-existing files on repo1.maven.org. I've installed Android Support Library in the SDK already.~~

Edit: nevermind, I only had the library, not the repository installed.
P.S.: Why does the build script ask for target 23 AND 22?

**Comment by schwabe** [comment]
the other apps (the remote example and the xposed module) might be on older APIs
