### ISSUE TITLE
No process running

### ISSUE THREAD

**Issue by syed-rafiul-hussain** [schwabe/ics-openvpn#405]
The app installed from the play store runs on Nexus 5 without any problem.

However, I built the app according to your instruction and got into the following problem: 

Here is the log status from the app:

no process running.

PM ERROR: ENDtag </ca> missing 
Process exited with exit value 1

The detail log file is here:

10-16 14:41:30.202 789-858/? I/ActivityManager: Displayed de.blinkt.openvpn/.activities.MainActivity: +449ms
10-16 14:41:30.210 31492-31492/? I/Keyboard.Facilitator: onFinishInput()
10-16 14:41:31.057 187-886/? D/audio_hw_primary: out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=2
10-16 14:41:31.068 789-1407/? I/ActivityManager: START u0 {act=android.intent.action.MAIN cmp=de.blinkt.openvpn/.LaunchVPN (has extras)} from uid 10132 on display 0
10-16 14:41:31.071 789-1407/? V/WindowManager: addAppToken: AppWindowToken{333eea53 token=Token{355f4a42 ActivityRecord{9ec888d u0 de.blinkt.openvpn/.LaunchVPN t766}}} to stack=1 task=766 at 1
10-16 14:41:31.092 789-1310/? I/ActivityManager: START u0 {flg=0x20000 cmp=de.blinkt.openvpn/.activities.LogWindow} from uid 10132 on display 0
10-16 14:41:31.097 789-1310/? V/WindowManager: addAppToken: AppWindowToken{11bc88e token=Token{20262089 ActivityRecord{c613f90 u0 de.blinkt.openvpn/.activities.LogWindow t766}}} to stack=1 task=766 at 2
10-16 14:41:31.101 26907-26964/? I/OpenVPN: Building configuratuin...
10-16 14:41:31.109 789-1281/? V/WindowManager: Adding window Window{4c2c4bc u0 de.blinkt.openvpn/de.blinkt.openvpn.LaunchVPN} at 4 of 11 (after Window{2c84b978 u0 de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity})
10-16 14:41:31.189 789-1282/? V/WindowManager: Adding window Window{1cff50cb u0 de.blinkt.openvpn/de.blinkt.openvpn.activities.LogWindow} at 5 of 12 (after Window{4c2c4bc u0 de.blinkt.openvpn/de.blinkt.openvpn.LaunchVPN})
10-16 14:41:33.329 26907-26968/? I/OpenVPN: Starting openvpn
10-16 14:41:33.329 26907-26968/? I/OpenVPN: Giving up
10-16 14:41:33.349 26907-26907/? I/Choreographer: Skipped 129 frames!  The application may be doing too much work on its main thread.
10-16 14:41:33.392 26907-26968/? I/OpenVPN: Exiting
10-16 14:41:33.446 789-858/? I/ActivityManager: Displayed de.blinkt.openvpn/.activities.LogWindow: +2s324ms (total +2s370ms)
10-16 14:41:33.472 31492-31492/? I/Keyboard.Facilitator: onFinishInput()
10-16 14:41:33.490 31492-31492/? I/Keyboard.Facilitator: onFinishInput()
10-16 14:41:34.217 187-886/? D/audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback
10-16 14:41:34.217 187-886/? D/audio_hw_primary: disable_snd_device: snd_device(2: speaker)
10-16 14:41:35.810 789-879/? E/WifiStateMachine: WifiStateMachine CMD_START_SCAN source -2 txSuccessRate=0.00 rxSuccessRate=0.00 targetRoamBSSID=28:b2:bd:f2:22:2c RSSI=-40
10-16 14:41:35.810 789-879/? E/WifiStateMachine: WifiStateMachine starting scan for "myhotspot"WPA_PSK with 2412
10-16 14:41:44.671 1068-1628/? I/art: Explicit concurrent mark sweep GC freed 36579(1755KB) AllocSpace objects, 4(338KB) LOS objects, 40% free, 21MB/36MB, paused 1.737ms total 25.298ms

**Comment by schwabe** [comment]
The latest beta on the play store and the source code here are identical and this bug has already been fixed.
