### ISSUE TITLE
Option to load custom routes / exclude list from file

### ISSUE THREAD

**Issue by PeterCxy** [schwabe/ics-openvpn#407]
For us users using OpenVPN to bypass network censoring, we will need a large range of bypass / route list to exclude those IPs that are not blocked or visits faster without VPN. Copy-pasting such large data will cause the UI to stick or crash. So it may be a better option to load them from file.

**Comment by schwabe** [comment]
If the ui crashes or does not respond please send a log. 

Importing an openvpn profile from file should work. Again, if there are error please report them.

**Comment by PeterCxy** [comment]
@schwable I did not mean the OpenVPN crashes, but meant that most text viewers on Android will not be able to open and copy large route files.

**Comment by schwabe** [comment]
@PeterCxy Yeah. That is one way. I never tested a large routing list with OpenVPN and VPNService API. 

My guess would be that people who try to use the large routing list, prepare a ovpn file with all the routes in it and then import that ovpn file directly into the app.

**Comment by PeterCxy** [comment]
@schwable There's no problem with VpnService and OpenVPN. I imported a profile with the full routing list and tried, it is working just fine. So I opened this issue to suggest that there might be a better way to import the routing list without creating an ovpn file manually, just as how certificates are imported.

**Comment by schwabe** [comment]
@PeterCxy I have no idea in what format these routing list are, so it is hard for me to write support for them.

**Comment by PeterCxy** [comment]
@schwable It's just in the CIDR format as in the current config interface. I mean loading file instead of copy-pasting them into the app.
