### ISSUE TITLE
Multiple On/Off Crash ICS OpenVPN 

### ISSUE THREAD

**Issue by bpvelandy** [schwabe/ics-openvpn#408]
When multiple on/off request is placed  using remote app to ICS OpenVPN the ICS OpenVPN App crashed .

**Comment by schwabe** [comment]
Please also attach a adb logcat or the stacktrace. That makes debugging for me much easier.

**Comment by bpvelandy** [comment]
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime: FATAL EXCEPTION: main
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime: java.lang.RuntimeException: Unable to start service de.blinkt.openvpn.core.OpenVPNService@5282b280 with Intent { cmp=de.blinkt.openvpn/.core.OpenVPNService (has extras) }: java.lang.NullPointerException
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2721)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.access$1900(ActivityThread.java:141)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5103)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:525)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:  Caused by: java.lang.NullPointerException
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at de.blinkt.openvpn.core.OpenVPNService.onStartCommand(OpenVPNService.java:346)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:2704)
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.access$1900(ActivityThread.java:141) 
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1353) 
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99) 
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137) 
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5103) 
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:525) 
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
10-21 00:27:18.937 1942-1942/de.blinkt.openvpn E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method) 
10-21 00:27:20.269 1942-1961/de.blinkt.openvpn D/dalvikvm: GC_FOR_ALLOC freed 393K, 15% free 4610K/5396K, paused 9ms, total 10ms
10-21 00:27:20.269 1942-1956/de.blinkt.openvpn E/System: Uncaught exception thrown by finalizer
10-21 00:27:20.317 1942-1956/de.blinkt.openvpn E/System: java.io.IOException: Bad file number
10-21 00:27:20.317 1942-1956/de.blinkt.openvpn E/System:     at android.net.LocalSocketImpl.close_native(Native Method)
10-21 00:27:20.317 1942-1956/de.blinkt.openvpn E/System:     at android.net.LocalSocketImpl.close(LocalSocketImpl.java:245)
10-21 00:27:20.317 1942-1956/de.blinkt.openvpn E/System:     at android.net.LocalSocketImpl.finalize(LocalSocketImpl.java:507)
10-21 00:27:20.317 1942-1956/de.blinkt.openvpn E/System:     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
10-21 00:27:20.317 1942-1956/de.blinkt.openvpn E/System:     at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
10-21 00:27:20.317 1942-1956/de.blinkt.openvpn E/System:     at java.lang.Thread.run(Thread.java:841)

**Comment by schwabe** [comment]
Thank you. What version of ics-openvpn are you running? The line numbers do not seem to match the ones in the current version.

**Comment by bpvelandy** [comment]
Issue has occurred in OpenVPN for Android 0.6.35

**Comment by schwabe** [comment]
I think that issue does no longer exist in more modern version. If it does, feel free to repoen the bug.
