### ISSUE TITLE
Switching network to network is unstable

### ISSUE THREAD

**Issue by bpvelandy** [schwabe/ics-openvpn#409]
When switching the network one wifi to another wifi or wifi to mobile network or a mobile network to another mobile network or vise versa ,ICS Open VPN is unable to get the vpn connection in these cases.

**Comment by schwabe** [comment]
Please provide a log of the app when you see this.

**Comment by bpvelandy** [comment]
There is no crash but VPN is unable get the connection using the new network

**Comment by schwabe** [comment]
Yes, please provide the log of the app as in using share in the log window.

**Comment by schwabe** [comment]
Also please test the beta version of the app. There have been some recent fixes.

**Comment by craftyguy** [comment]
I also experience this. It doesn't happen every time, but it does happen often. 
I've noticed that it seems to occur when the network switch happens and the screen is off. I've tried to get it to happen by manually toggling wifi and mobile network but I've been unable to get it to happen then.. I've uploaded the log to here: 
https://gist.github.com/craftyguy/f5ac8104b065249403f7

.

**Comment by schwabe** [comment]
@craftyguy that log show your phone successfully switching from WiFI to LTE

**Comment by craftyguy** [comment]
Yes, the connection is "successful" but no data is being transmitted or received until I force a reconnect

**Comment by craftyguy** [comment]
Sorry, my issue may be unrelated to the one posted here originally.. I'll open a new ticket
