### ISSUE TITLE
No data connection after switching networks automatically

### ISSUE THREAD

**Issue by craftyguy** [schwabe/ics-openvpn#411]
OS: Cyanogenmod 12.1 (based on Android 5.1.1)
Phone: MotoX 2014
ics-openvpn version: 0.6.43 

I have persistent tun enabled, and "reconnect on network change." The log seems to indicate that the reconnection was successful, however I am not able to sent/receive data over the connection. The notification shows "0 bit/s" receiving. The only way to restore the connection to my openvpn server is to disconnect the client and reconnect. 

This problem seems to happen when the network switch/openvpn occurs when the screen is off. I've tried to manually toggle networks and trigger the reconnection many times and have been unable to get the problem to occur.

Log here: https://gist.github.com/craftyguy/f5ac8104b065249403f7

Please let me know if I can provide any more information to help, as this issue makes this app fairly unusable for me since I have to force a reconnection quite a few times per day as I wander through Wifi and mobile networks.

**Comment by craftyguy** [comment]
Here's a new log file with verbosity turned way up and taken right after I noticed that the issue occurred.

https://gist.github.com/craftyguy/f2e30e09c1accd32c759

**Comment by craftyguy** [comment]
I'm not sure why, but this occurs very frequently for me. One possible (and hackish) solution might be to perform a ping test when the device display is activated and reconnect if it fails, since I've noticed that a simple ping (to, for example Google.com) will fail after this issue occurs. That would make the behavior similar to the "suspend connection on sleep" option when the problem occurs... Which isn't ideal but it would stop me from having to manually disconnect and reconnect just about every time I move from WiFi to data connection when the display is off..

**Comment by schwabe** [comment]
I finally got time to check this but unfortenately the logs are gone now :(
