### ISSUE TITLE
Couldn't load opvpnutil

### ISSUE THREAD

**Issue by 7tenzo** [schwabe/ics-openvpn#412]
Hello,

I imported your last build on my android studio.

When I launch the application there is no problem but when I import the ovpn files and click on it, then the application crash.

You can find below the error :

10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime: FATAL EXCEPTION: main
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime: Process: de.blinkt.openvpn, PID: 28974
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime: java.lang.UnsatisfiedLinkError: Couldn't load opvpnutil from loader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/de.blinkt.openvpn-2.apk"],nativeLibraryDirectories=[/data/app-lib/de.blinkt.openvpn-2, /vendor/lib, /system/lib]]]: findLibrary returned null
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at java.lang.Runtime.loadLibrary(Runtime.java:358)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at java.lang.System.loadLibrary(System.java:526)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at de.blinkt.openvpn.core.NativeUtils.<clinit>(NativeUtils.java:22)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at de.blinkt.openvpn.core.VpnStatus.logInformation(VpnStatus.java:341)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at de.blinkt.openvpn.core.VpnStatus.<clinit>(VpnStatus.java:135)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at de.blinkt.openvpn.LaunchVPN.onStart(LaunchVPN.java:99)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1171)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at android.app.Activity.performStart(Activity.java:5241)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2157)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2233)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.access$800(ActivityThread.java:135)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:136)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5001)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
10-29 19:59:34.736 28974-28974/de.blinkt.openvpn E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

Thanks for your reply

**Comment by xDragonZ** [comment]
This is not an issue related to the app/code, learn how to read before opening an issue.

**Comment by schwabe** [comment]
As @xDragonZ  says: Read the README first.

**Comment by kirtich** [comment]
Hello 7Tenzo/schwabe

I am new for Android NDK, I don't have more idea about it, I am also facing same issue while trying to run ics-openvpn , I have gone through with the readme file as well, As per read me instruction I created a ovpnlibs folder in main and then place libs and assets folder whatever I extracted from apk file, but I am facing issue of "Error writting minivpn binary". Kindly assist me where I am doing wrong?
Thanks in advance!
schwabe Kindly assist me.

Thanks & regards
Kirti Hudda

**Comment by schwabe** [comment]
Folder structure should look like this:

find ovpnlibs 
ovpnlibs
ovpnlibs/assets
ovpnlibs/assets/nopie_openvpn.arm64-v8a
ovpnlibs/assets/nopie_openvpn.armeabi
ovpnlibs/assets/nopie_openvpn.armeabi-v7a
ovpnlibs/assets/nopie_openvpn.mips
ovpnlibs/assets/nopie_openvpn.x86
ovpnlibs/assets/nopie_openvpn.x86_64
ovpnlibs/assets/pie_openvpn.arm64-v8a
ovpnlibs/assets/pie_openvpn.armeabi
ovpnlibs/assets/pie_openvpn.armeabi-v7a
ovpnlibs/assets/pie_openvpn.mips
ovpnlibs/assets/pie_openvpn.x86
ovpnlibs/assets/pie_openvpn.x86_64
ovpnlibs/jniLibs
ovpnlibs/jniLibs/arm64-v8a
ovpnlibs/jniLibs/arm64-v8a/libjbcrypto.so
ovpnlibs/jniLibs/arm64-v8a/libopenvpn.so
ovpnlibs/jniLibs/arm64-v8a/libopvpnutil.so
ovpnlibs/jniLibs/armeabi
ovpnlibs/jniLibs/armeabi/libjbcrypto.so
ovpnlibs/jniLibs/armeabi/libopenvpn.so
ovpnlibs/jniLibs/armeabi/libopvpnutil.so
ovpnlibs/jniLibs/armeabi-v7a
ovpnlibs/jniLibs/armeabi-v7a/libjbcrypto.so
ovpnlibs/jniLibs/armeabi-v7a/libopenvpn.so
ovpnlibs/jniLibs/armeabi-v7a/libopvpnutil.so
ovpnlibs/jniLibs/mips
ovpnlibs/jniLibs/mips/libjbcrypto.so
ovpnlibs/jniLibs/mips/libopenvpn.so
ovpnlibs/jniLibs/mips/libopvpnutil.so
ovpnlibs/jniLibs/x86
ovpnlibs/jniLibs/x86/libjbcrypto.so
ovpnlibs/jniLibs/x86/libopenvpn.so
ovpnlibs/jniLibs/x86/libopvpnutil.so
ovpnlibs/jniLibs/x86_64
ovpnlibs/jniLibs/x86_64/libjbcrypto.so
ovpnlibs/jniLibs/x86_64/libopenvpn.so
ovpnlibs/jniLibs/x86_64/libopvpnutil.so
[14:02]arne@styx:...e/icsopenvpn/main%

**Comment by akkichaudhary29** [comment]
Hello Schwabe,

I imported your last build on my android studio successfully.
and my project's structure is looking like your defined structure above , but i am getting some error when i import a .ovpn file from sd card then i click on it then it ask user name and password, after enter the user name and password when i click on ok button then i am getting some errors that are:
Failed getting assets for archicture x86, Failed getting assets for archicture armeabi-v7a, Failed getting assets for architure armeabi and Error writing minivpn binary.
I am attaching the screenshots of my problem, please see them and assist me , i will be very highly thankful  to you.
Thanks in Advance..! 
![screenshot_2016-01-06-15-08-18](https://cloud.githubusercontent.com/assets/10954910/12139747/7d6860c2-b488-11e5-97d6-cd4339bf2529.jpg)
![screenshot_2016-01-06-15-09-23](https://cloud.githubusercontent.com/assets/10954910/12139762/935ad536-b488-11e5-9a7d-f2d72d68f04e.jpg)
![screenshot_2016-01-06-15-09-31](https://cloud.githubusercontent.com/assets/10954910/12139766/9585459e-b488-11e5-8435-ca7a64b8171f.jpg)

**Comment by schwabe** [comment]
Double check that the assets from the native binaries are also in the apk. (Use zip to open apk)

**Comment by akkichaudhary29** [comment]
Thank you so much  for your reply. I just have to used assets from apk.

**Comment by akkichaudhary29** [comment]
@schwabe  i tried it many times but no success. Schwabe is it possible can you mail me the complete setup code. if yes then it would be very helpful for me, i am really very stuck in this, please help me.
my email id is akkichaudhary29@gmail.com

Thank you so much..!

**Comment by schwabe** [comment]
@akkichaudhary29 My own setup is what is what you get by using git clone. I don't see any benefit in zipping and emailing a git checkout.

**Comment by akkichaudhary29** [comment]
it's okay or is it possible can you check my code on my system where am i going wrong by using Skype or Teamviewer?

**Comment by schwabe** [comment]
@akkichaudhary29 Requesting hands on support is going beyond normal support of this opensource project and would have to billed as consulting work (with the respective fees)

**Comment by akkichaudhary29** [comment]
Okay I am ready for that what would be your fees? let's discuss over the skype. My skype name is ankkitsingh.

Thanks..!

**Comment by ghost** [comment]
@akkichaudhary29 - Where you able to get the project running? What was missing?

Thanks!

**Comment by woshka** [comment]
> @akkichaudhary29 Requesting hands on support is going beyond normal support of this opensource project and would have to billed as consulting work (with the respective fees)

hello schwabe
I want to have a custom development let me know how to contact with you and to discuss the pricing
thx

**Comment by schwabe** [comment]
Contact me directly via email (arne@rfc2549.org)

**Comment by woshka** [comment]
sent an email to you from voshkan At gmail
