### ISSUE TITLE
[Feature Request] What would it need for TAP-based adapters?

### ISSUE THREAD

**Issue by Hoeze** [schwabe/ics-openvpn#413]
Hi,
you recently created some openvpn binaries for android.
I'm using these with the very old OpenVPN Settings app, but i had to do some very ugly iptables hacks, for example to achieve reliable DNS redirection.

I dont know how much effort this would take, but it would be great, if you would provide support for devices with openvpn binaries in /system, since this app already has great openvpn android integration :)

**Comment by schwabe** [comment]
All the DNS, routing etc is all handled by the VPNService API in my app. Implemeting support for /system binaries would need implementing all the stuff again. Implementing a tap emulation on tun is probably less work and a lot more reliable.

**Comment by schwabe** [comment]
Closing the issue for now. It is already answered in the FAQ
