### ISSUE TITLE
Changes for Android 6.0

### ISSUE THREAD

**Issue by arun2** [schwabe/ics-openvpn#416]
Hi Team,
Can you please point here few main changes for made for Android 6.0 our quick knowledge  .

Thanks
Hapi

**Comment by schwabe** [comment]
Please use the issue tracker for real issues. And there almost no changes for 6.0 apart from the sd card read permission.

**Comment by arun2** [comment]
Thanks

**Comment by arun2** [comment]
Hi, Thanks for reply.  Wanted to know one thing . As Android M  has moved from  OpenSSL   to BoringSSL . I was wondering how  same  ICSOPENVPN  APK  running  in   Android M and earlier Android version.  For old apk to run in Android M one needs to copy  libssl.so and libcrypto.so inside APK.. But doing so increasing the APK size by 3-4 times.  How ICSOPENVPN handling it ... If  we disable  polarSSL   will it work in Android M?  Thank you

**Comment by schwabe** [comment]
OpenVPN is statically linked against OpenSSL. And PolarSSL is disabled by default anwyay.
