### ISSUE TITLE
OpenSSL issue in Android 6.0

### ISSUE THREAD

**Issue by arun2** [schwabe/ics-openvpn#417]
Team- Can you please tell em why this error is coming in Android 6.0  MOTOROLA

P:CANNOT LINK EXECUTABLE: cannot locate symbol "DES_is_weak_key" referenced by "../lib/arm/libopenvpn.so"...

Thanks

**Comment by schwabe** [comment]
Which version are you running? And can you show the whole log? I find it highly unlikely that some modern 6.0 device is running plain arm (not v7a oder 64bit)

**Comment by schwabe** [comment]
No response
