### ISSUE TITLE
[Inquiry] UX frustrations in non-touch environment

### ISSUE THREAD

**Issue by RoxKilly** [schwabe/ics-openvpn#419]
I discovered this fantastic tool today, after becoming frustrated with [OpenVPN Connect](https://play.google.com/store/apps/details?id=net.openvpn.openvpn) because it would send all packets, including LAN packets, through the VPN, making it impossible for me to communicate with other devices on the LAN while using the VPN.

My particular use case is a streaming box (Amazon Fire TV, similar to Roku or AppleTV) where my only input is a remote (no touch, no mouse) and where I have no notification bar on screen.  The biggest challenge I run into is that I cannot tell when I open the app, whether I'm connected to the VPN, and there is no easy way for me to connect since I can't use touch input. Also when I click on a listing to connect, I have no way to tell from the `Profiles` tab whether the connection was successful.  Finally there is no way to disconnect from the `Profiles` tab.

I think it would be a great UX improvement to add just one button to each listing on the `Profiles` tab, to the left of the `Edit` button.  The button could display `Connect`, `Connecting` or `Disconnect` (or corresponding icons) depending on the current connection state.  If the buttons are added to the UI in the right sequence, an added bonus would be ease of navigation with a remote.  Currently, to go from one listing to the next and connect, instead of pressing `down` once with the remote, I have to go `right` to the edit button, then `down` to the next edit button, then `left` to the next listing, then press `Select` on the remote to initiate a connection.

As a sidenote, on the log screen, pressing `Disconnect` should probably change that button to `Connect` so it can work as an on/off switch.  It currently doesn't change upon being pressed.

Thanks for sharing this tool with us!

**Comment by schwabe** [comment]
Yes. Usuability on Android TV and similar devices is suboptimal. I am trying to improve it bit by bit, but as a spare time project it takes some time.

For the status, I will integrate a status on the main page of the app. However I have no idea how to communicate the status outside the app. I just asked SO if anyone else has an idea. (http://stackoverflow.com/questions/34656098/ongoing-status-for-android-tv-apps-what-to-use-instead-of-notification-bar-on)

**Comment by RoxKilly** [comment]
Just my 2 cents. I would not make communicating status outside the app a high priority.  For regular Android devices, the notification bar already does this. For Android TV, I would limit such communication to a system notification upon disconnection.  Any attempt to provide constant on-screen feedback of status on Android TV would be counter-productive in my opinion for the same reason there is no notification bar: that platform is about watching tv or playing games full-screen.

**Comment by schwabe** [comment]
I am more about showing the status in the Android TV hub.

**Comment by RoxKilly** [comment]
ah ok; I misunderstood. Can't help you there. I use Amazon FireTV which runs a skin of Lollipop not genuine Android TV.

**Comment by RoxKilly** [comment]
0.6.46 and 0.6.47 have improved usability. Thanks for starting to address this. The updates made a noticeable difference.

**Comment by schwabe** [comment]
I am closing this meta issue now. That does not mean that everything is working well. If you run into problem with Android TV/non touch, please just open specific issues.
