### ISSUE TITLE
Traffic not going over the VPN connection.

### ISSUE THREAD

**Issue by fuqqer** [schwabe/ics-openvpn#422]
I have a Blackberry priv running Lollipop 5.1.1.  I installed openvpn for android and imported my working .ovpn file from my linux laptop. I start the connection and see in the log that the "initialization sequence completed".  I am still unable to pass traffic over the VPN to the hosts on my LAN. I tried manually adding a route (172.16.1.0/24), I also tried checking the box to direct all traffic over the VPN and see in the log  "VpnService routes installed: 0.0.0.0/0".  I am still unable to get traffic to go over my VPN.

Anyone have suggestions on how to get openVPN for android working or what I could do to troubleshoot?

Thanks.

**Comment by schwabe** [comment]
From the app perspective everything is working fine. 

You could check adb logcat if you install developer tools if there is any indication there. But this sounds like a firmware bug.

**Comment by fuqqer** [comment]
I just installed the OpenVPN for Android client.  It works, so I doubt this is a firmware bug.

**Comment by schwabe** [comment]
@fuqqer Yes, if it works what is the problem?
