### ISSUE TITLE
For Samsung Android 5.0+ devices ignore DNS servers

### ISSUE THREAD

**Issue by LucaSakketti** [schwabe/ics-openvpn#424]
Hello!
i'm Luca,
i have a Samsung galaxy Tab 10 with Android 5.0.2
and i have problem to setting up a VPN Connection, i don't be able to navigate over the VPN.
Downloading your Project i see this warning:

"Warning Samsung Android 5.0+ devices ignore DNS servers outside the VPN range. To enable DNS add a custom route to your DNS Server (%s) or change to a DNS inside your VPN range"

How Can i add a custom route to my DNS Server that isn't in the VPN Range?

Thanks.

PS. Excuse me for my English!

**Comment by schwabe** [comment]
Just add the IP of your DNS server under custom routes.
