### ISSUE TITLE
Feature request: force restart when network change between 2G/3G/4G

### ISSUE THREAD

**Issue by zhsj** [schwabe/ics-openvpn#425]
I'm using Nexus 6 and Android 6.0.1. I find the openvpn will lost connection when the mobile network changes from LTE to 2G. It will restart when reaches the ping-restart time which is 120 seconds by default.
Could you plz add a option to force it to restart when the network changes between 2G/3G/4G not only between Wifi and mobile network.

**Comment by schwabe** [comment]
There is no such option because so far I never encountered a mobile network that does not keep the current IP address when switching network technology. In my personal experience the network technology changes very often. 

Could provide a few more details about your network provider?

**Comment by zhsj** [comment]
@schwabe my network provider is CMCC(China Mobile). I can only use 2G or 4G on my nexus 6. And it seems that when switch between 2G and 4G, the ip address will change.

I test it by enforcing the network and the result is

```
shell@shamu:/ $ ifconfig rmnet_data0                                           
rmnet_data0 Link encap:UNSPEC  
          inet addr:10.85.52.130  Mask:255.255.255.252 
          inet6 addr: fe80::d351:bf07:20eb:dd85/64 Scope: Link
          UP RUNNING  MTU:1500  Metric:1
          RX packets:759827 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:804927 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:573579912 TX bytes:154630120 
```

After switching from LTE to EDGE

```
shell@shamu:/ $ ifconfig rmnet_data0                                           
rmnet_data0 Link encap:UNSPEC  
          inet addr:10.142.86.60  Mask:255.255.255.248 
          inet6 addr: fe80::2bf5:ba16:7275:6675/64 Scope: Link
          UP RUNNING  MTU:1500  Metric:1
          RX packets:759858 errors:0 dropped:0 overruns:0 frame:0 
          TX packets:804979 errors:0 dropped:0 overruns:0 carrier:0 
          collisions:0 txqueuelen:1000 
          RX bytes:573586566 TX bytes:154635736 

```

**Comment by schwabe** [comment]
@zhsj Enforcing the network type may trigger a complete reconnect of the network. It does on my phone. Do you have access to the server? Can you check if after a network switch the packets are really coming from a new address?

Side note: Upgrading the server to -master (going to be 2.4) will also fix the problem because of the peer-id float mechanism.

**Comment by zhsj** [comment]
@schwabe I checked on the server. It received packages from a new address. Even behind a NAT(10.x.x.x), it will lead me to a different gateway. I don't know whether it is the same if the network type is changed automatically rather than I enforce it(hard to find such test environment).

I need some time to try the master branch and the peer-id float mechanism is really good.

**Comment by zhsj** [comment]
@schwabe I test the peer-id float, and it works! Thanks for the note and I think this issue can be closed.
