### ISSUE TITLE
"CA certificate" doesn't support multiple CAs?

### ISSUE THREAD

**Issue by jhaar** [schwabe/ics-openvpn#426]
Hi there

We have openvpn clients on Windows/Mac/Linux successfully configured with their "--ca" setting pointing to a single file containing our two CA public keys. However, ics-openvpn seems to only support referring to one? ie it works when pointing to a CA file that matches the CA used to sign our openvpn server cert, but doesn't work (verify error) when pointing at a file containing the two CA  PEM files (with the "good" one at the bottom) [and it's the same file that Mac/Linux/Windows successfully use]

Does ics-openvpn look for "END CERT" and miss the second cert?

**Comment by schwabe** [comment]
Did you check the generated config?

**Comment by jhaar** [comment]
What seems to have happened is the second CA cert has ended up in "extra-certs". However, we have a combination of clientcert-CA1, clientcert-CA2 and servercert-CA1 and servercert-CA2 - so both CA1 and CA2 need to be in "ca". What I have is clientcert-CA1 and servercert-CA1, but "ca" only contains CA2 and "extra-certs" contains CA1 - but that doesn't work. We also have some clientcert-CA2 - but they will also not like servercert-CA1 if "ca" only refers to CA2

...I didn't even know about "extra-certs" until this event - I think it's use-case is rarer than what I'm doing? (which is all about migrating from sha1 CA1 to sha2 CA2)

**Comment by schwabe** [comment]
I will have to look into that.

extra-certs is more common from my experience if you have intermediated certificates.

**Comment by schwabe** [comment]
I looked into this and the only way that my app uses extra-certs is if the user is using the android internal keystore for his/her certificate. What configuration are you using on the device?

**Comment by jhaar** [comment]
yes: our users already have valid corporate client certs for their browser, so the idea was to create a .ovpn file which contained everything except for the client cert. That enables that file to be generic: linkable from a website. The .ovpn file contained both our old and new CA public keys in the "<ca>" section, but I guess your import tool splits them into "<ca>" and "<extra-certs>"

**Comment by schwabe** [comment]
What else do you have the config file? Could give me an example?

From the code <ca> should contain whatever was in the imorted ovpn file. And extra-certs should contain  the certificates from the keystore.

**Comment by jhaar** [comment]
sure thing
[example-ovpn.txt](https://github.com/schwabe/ics-openvpn/files/89574/example-ovpn.txt)

**Comment by schwabe** [comment]
@jhaar If that is the generated config from the app everything is in order? It has two certs in the <ca> section.

**Comment by jhaar** [comment]
no - that's the config that is imported. After it's imported, ics-openvpn splits the two CA certs into "<ca>" and "<extra-certs>". If I make sure the one that the server is signed with matches the "<ca>" one, it all works, but if the server is signed with the CA under "extra-certs" - then it fails (as it would). Hence they both need to be in the "<ca>" section
