### ISSUE TITLE
Submodule mapping not found main/breakpad

### ISSUE THREAD

**Issue by smarek** [schwabe/ics-openvpn#428]
I think that something gone wrong on 838f5b838484e12626a2a06762d7ae11442a19d4 with `main/breakpad` submodule.

Resetting into previous commit 876f2017c44752522441133021931d04292c0bc1 and doing `git submodule init && git submodule update --recursive` is working fine

Since 838f5b838484e12626a2a06762d7ae11442a19d4 going with `git submodule init` will result in error: 

```
> git submodule init
No submodule mapping found in .gitmodules for path 'main/breakpad' 
```

This also prevents `git submodule update` from proceeding.

From said commit, it appears repository https://chromium.googlesource.com/breakpad/breakpad in revision https://chromium.googlesource.com/breakpad/breakpad/+/4da1cfbad248e846b6e0b4429b4eb639bb2d1970 should be what we want, is it?

**Comment by schwabe** [comment]
That breakpad support is more less broken anyway. Best compile with USE_BREAKPAD=NO

**Comment by smarek** [comment]
Can do, however due to this bug, it's now impossible to use `git submodule` command over this repository, please either fix or remove the subproject reference, up to your decision, thank you :+1:
