### ISSUE TITLE
Unable to connect via openVPN on Android 6

### ISSUE THREAD

**Issue by rpederson** [schwabe/ics-openvpn#430]
We have built an Android app that uses ics-openvpn, has worked well the past ~2 years, for Android 4/5, but we are unable to get a VPN connection when using an LG Nexus 5 that is running Android 6.0.  I am debugging via Eclipse, saw the following error message, have been unable to figure what it means, or how to resolve the issue.  Seems odd that it referencing ".../lib/arm" here, I would expect a Nexus 5 to be using arm64???
[des_is_weak_key.txt](https://github.com/schwabe/ics-openvpn/files/79238/des_is_weak_key.txt)

P:CANNOT LINK EXECUTABLE: cannot locate symbol "DES_is_weak_key" referenced by "/data/app/com.luth.client-2/lib/arm/libopenvpn.so"...

**Comment by schwabe** [comment]
Does the official client work? Your client is probably build upon a very outdated codebase.

Also googling for com.luth.client hints at closed source clients that are probably violating the GPL. Please read the doc/README.txt or

**Comment by rpederson** [comment]
Thanks, I'll try the official client.  Will also have another look at the GPL, last time our legal team reviewed it we felt we were in compliance.  Where would we go for latest source?

Also your last sentence cut off, did you mean to do that?

**Comment by schwabe** [comment]
@rpederson If your app (UI) includes source code of my app  and does not use an ancient version then you are popropably using the GPL. In short 
- Have GPL notice and copyright of original author in the about
- Give access to the full source code of the program on request.

The latest source code is on github.

**Comment by rpederson** [comment]
Thanks, I did confirm the official client does indeed work, so will work on updating to the latest source; we will also revisit our Android app wrt GPL compliance.
