### ISSUE TITLE
VPN is connected, but traffic is not tunneled

### ISSUE THREAD

**Issue by AlmogBaku** [schwabe/ics-openvpn#436]
The VPN connection was established, but for some reason the traffic is not tunneled through the VPN (nor with full VPN and per-app).

Notes:
1. The problem started after I pulled from master.
2. VpnStatus shows nothing
3. I can't even receive the packets in the server(tcpdump)

**Comment by schwabe** [comment]
What device are you using? Is that a Samsung device by chance?

**Comment by AlmogBaku** [comment]
It's happening in all of my devices: oneplus one, oneplus 2, lg nexus 4, samsung galaxy s6

**Comment by AlmogBaku** [comment]
I also did  `git submodules update` and rebuilt the natives.. i guess it comes from there

**Comment by schwabe** [comment]
Hm, only thing I changed for building natives is the removal of breakpad in the default configuration. The native sources themselves haven't changed in the last month. Did you clean the native source? (ndk-build clean)

**Comment by AlmogBaku** [comment]
I found it, something was corrupted with my lzo files... sorry for wasting your time :-(
