### ISSUE TITLE
License Query

### ISSUE THREAD

**Issue by Olaoyejel** [schwabe/ics-openvpn#438]
Dear Developer : Can you please check your email  a__@rfc__49.org and complete our ongoing activity. Mail sent from  olaoy*******@gmail.com.

Thank you

**Comment by natsihitt** [comment]
I don't understand really!! 
What the heck is that email add and which form have I been fill that funny address

**Comment by Olaoyejel** [comment]
Ya...We were communicating there ..But  I am not getting reply for over a month..Can you please check 
Email -> 
arne-openvpn  at rfc2549 dot org,  arne  at rfc2549 dot org

I sent mail today also from my email  id   ( hiding last few digits  ) =
olaoyej****@gmail dot com.

It is very important.

Thanks
Ola

**Comment by Olaoyejel** [comment]
Dear Arne Schwabe,

Can you please check your email sent from  "olaoyejel123  at  gmail.com".   Few tasks are pending for a long time . I have already paid. 

Thanks
Ola
