### ISSUE TITLE
How to setup the Vpn

### ISSUE THREAD

**Issue by KensNote2** [schwabe/ics-openvpn#440]
How to setup the VPN on my Android Note 2(6.0.1)Resurrection Remix. I readed in the notes I have to download a file to setup the VPN as I taught I would just type in certain codes in serring/VPN? Any help would be much appreciated and  thank you for your work guys.

**Comment by schwabe** [comment]
It still boils down to what the FAQ says. Get a OpenVPN config file from someone how runs an openvpn server or setup your OpenVPN server.
