### ISSUE TITLE
Explain the difference between OpenVPN android apps on play store site

### ISSUE THREAD

**Issue by julienschmidt** [schwabe/ics-openvpn#441]
For new users the choice between the different OpenVPN apps offered in the play store is confusing.
I guess most will eventually decide for OpenVPN Connect as it is published by OpenVPN.

It would probably be a good idea to summarize the differences or just link to http://ics-openvpn.blinkt.de/FAQ.html#faq_androids_clients_title on the play store site to help new users decide.

**Comment by schwabe** [comment]
Good idea. I added it to the description of my app
