### ISSUE TITLE
Compile matter

### ISSUE THREAD

**Issue by iryna7** [schwabe/ics-openvpn#442]
hi, as soon as i downloaded and compile it based on the README procedure, i comes following errors. 

`iryna7@iryna7-desktop:~/work/ics-openvpn$ git submodule init`

> Submodule 'main/openssl' (git@github.com:schwabe/platform_external_openssl.git) registered for path 'main/openssl'
> Submodule 'main/openvpn' (git@github.com:schwabe/openvpn.git) registered for path 'main/openvpn'

`iryna7@iryna7-desktop:~/work/ics-openvpn$ git submodule update`

> Cloning into 'main/openssl'...
> Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> Clone of 'git@github.com:schwabe/platform_external_openssl.git' into submodule path 'main/openssl' failed

all above message comes from git hub repository things, i guess. so, i downloaded from android ssl as follow.

git clone https://github.com/android/platform_external_openssl.git
git clone https://github.com/schwabe/openvpn.git

`iryna7@iryna7-desktop:~/work/ics-openvpn/main$ ./misc/build-native.sh`

> replacing config-version.h
> openssl/Crypto.mk:75: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-static-library.mk: No such file or directory
> openssl/Apps.mk:26: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-executable.mk: No such file or directory
> jni/Android.mk:39: openvpn/Android.mk: No such file or directory
> openssl/Crypto.mk:75: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-static-library.mk: No such file or directory
> openssl/Apps.mk:26: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-executable.mk: No such file or directory
> jni/Android.mk:39: openvpn/Android.mk: No such file or directory
> openssl/Crypto.mk:75: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-static-library.mk: No such file or directory
> openssl/Apps.mk:26: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-executable.mk: No such file or directory
> jni/Android.mk:39: openvpn/Android.mk: No such file or directory
> openssl/Crypto.mk:75: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-static-library.mk: No such file or directory
> openssl/Apps.mk:26: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-executable.mk: No such file or directory
> jni/Android.mk:39: openvpn/Android.mk: No such file or directory
> openssl/Crypto.mk:75: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-static-library.mk: No such file or directory
> openssl/Apps.mk:26: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-executable.mk: No such file or directory
> jni/Android.mk:39: openvpn/Android.mk: No such file or directory
> openssl/Crypto.mk:75: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-static-library.mk: No such file or directory
> openssl/Apps.mk:26: /home/iryna7/Android/Sdk/ndk-bundle/build/core/build-host-executable.mk: No such file or directory
> jni/Android.mk:39: openvpn/Android.mk: No such file or directory
> make: **\* No rule to make target `openvpn/Android.mk'.  Stop.

please give an advice whatever you got, any comment would be nice and welcome. thanks in advance.

Regards.

**Comment by schwabe** [comment]
Either change the paths to https in the .gitmodules (or similar filename) which require no authentication or setup git ssh keys. If you clone the subrepos manually you also need to pick the right commit. git submodule update _might_ do that for you.

**Comment by iryna7** [comment]
so, openssl module is the broken link on your git rep. right ? and then do i need to download from [https://github.com/android/platform_external_openssl.git](https://github.com/android/platform_external_openssl.git) ?

**Comment by schwabe** [comment]
No. it is not broken. If you setup ssh for git (https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) everything is fine.
