### ISSUE TITLE
Username is truncated 

### ISSUE THREAD

**Issue by topmotiveret** [schwabe/ics-openvpn#445]
Look like there is a limit on username length. Its an issue with token based vpns. Mbe increase to 128 or 256.

**Comment by schwabe** [comment]
The restriction is probably in OpenVPN itself. Unless you have an indication that the Android client has a smaller username length I would close the ticket.

**Comment by topmotiveret** [comment]
Well no matter the cause: no longer an issue with 0.6.47. Closing.

**Comment by mohsen60** [comment]
Hi
