### ISSUE TITLE
Include a Changelog Link, within the F-Droid App', on Info' Page, 0.6.47.

### ISSUE THREAD

**Issue by locutis-of-borg-1999** [schwabe/ics-openvpn#448]
Include a Changelog Link, within the F-Droid App', on Info' Page.  Not present, as of: 0.6.47.

**Comment by schwabe** [comment]
There is not really a changelog that I could link to.

**Comment by locutis-of-borg-1999** [comment]
It could be as simple as a text file, listing the release changes.  

https://f-droid.org/manual/html_node/Changelog.html#Changelog

**Comment by fazlerabbi37** [comment]
A changelog can really help users like us who have less time to go through the commit message. It is not that tough to do. Maybe take a look at this: https://medium.com/@lowcarbrob/android-pro-tip-generating-your-apps-changelog-from-git-inside-build-gradle-19a07533eec4

**Comment by schwabe** [comment]
@fazlerabbi37 a changelog from git doesn't really fit the garanularity or the technical level that most users using the app would understand.

**Comment by fazlerabbi37** [comment]
sure but if you craft the commit message properly it would give you and us a starting point. We can at least understand what is getting added or removed and you can edit them to make a proper CHANGELOG.md file.

**Comment by schwabe** [comment]
The commit message are crafted properly but on a technical level for developer to understand and not for users.

**Comment by fazlerabbi37** [comment]
then what do you suggest for us, the enthusiast user, who likes to know what is going on with one of their most used app?
