### ISSUE TITLE
"Missing CA certificate" regression in 0.6.48

### ISSUE THREAD

**Issue by cmaion** [schwabe/ics-openvpn#453]
Hi there,

Last version in play store (0.6.48) just broke my configurations.

I now get "Missing CA certificate" messages when I try to connect.

I use the PKCS12 format to provide OpenVPN with the key & certs. It's generated as follow:

`openssl pkcs12 -export -in xxx.crt -inkey xxx.key -certfile ca.crt -out xxx.p12`

So it should be able to find the CA, but it needs to look into `<pkcs12>...</pkcs12>` too ;)

**Comment by schwabe** [comment]
Apk if you want to test: http://plai.de/android/ics-openvpn-0.6.49pre.apk

**Comment by cmaion** [comment]
Wow, that was quick :)
Just tested this Apk: works perfectly again!

Thanks!
