### ISSUE TITLE
0.6.47 is latest version on Google Play

### ISSUE THREAD

**Issue by untitaker** [schwabe/ics-openvpn#454]
I noticed that F-Droid carries newer versions of this app than Google Play. Is this intentional or an oversight?

Thanks for the great app.

**Comment by schwabe** [comment]
No, when I push a version to the play store I tag it as vx.xx-production which f-droid then takes as new version for itself. Since I used staggered rollout, usually beginning with 5% and then increasing if no problems are detected, you often see an older version.

**Comment by thioshp** [comment]
Thank you for such a great app.

**Comment by mimi89999** [comment]
@schwabe Should F-Droid still look only at -PRODUCTION tags or at all tags?

**Comment by schwabe** [comment]
@mimi89999 I still use these tags to tag version that everyone gets, why are you asking?

**Comment by mimi89999** [comment]
@schwabe To know if we should continue using those for F-Droid.

**Comment by schwabe** [comment]
yes, and v0.6.70 and v0.6.71 also have their production tag.
