### ISSUE TITLE
Issue while connecting 5.1.1. and marshmallow

### ISSUE THREAD

**Issue by ratzsam** [schwabe/ics-openvpn#456]
Same library working for other android version except 5.1.1. and marshmallow.
See the logs below

03-07 12:01:39.170: I/Vpn(775): Switched from com.vpn to com.vpn
03-07 12:01:39.172: D/Vpn(775): setting state=IDLE, reason=prepare
03-07 12:01:39.233: D/OpenGLRenderer(4293): endAllStagingAnimators on 0x55972aeb70 (RippleDrawable) with handle 0x55972ad270
03-07 12:01:39.234: I/System.out(3421): outside showConfigErrorDialog
**03-07 12:01:39.253: W/System.err(3421): java.io.FileNotFoundException: minivpn.**
03-07 12:01:39.262: I/Timeline(3421): Timeline: Activity_idle id: android.os.BinderProxy@214ead3b time:62181029
03-07 12:01:39.267: W/System.err(3421):     at android.content.res.AssetManager.openAsset(Native Method)
03-07 12:01:39.267: W/System.err(3421):     at android.content.res.AssetManager.open(AssetManager.java:331)
03-07 12:01:39.267: W/System.err(3421):     at android.content.res.AssetManager.open(AssetManager.java:305)
03-07 12:01:39.267: W/System.err(3421):     at com.tngrnow.vpn.core.VPNLaunchHelper.writeMiniVPN(VPNLaunchHelper.java:35)
03-07 12:01:39.267: W/System.err(3421):     at com.tngrnow.vpn.core.VPNLaunchHelper.startOpenVpn(VPNLaunchHelper.java:69)
03-07 12:01:39.267: W/System.err(3421):     at com.tngrnow.vpn2.LaunchVPNManager$startOpenVpnThread.run(LaunchVPNManager.java:288)
03-07 12:01:39.268: I/MSM-irqbalance(280): Decided to move IRQ130 from CPU5 to CPU6
03-07 12:01:39.739: W/ActivityManager(775): getRunningAppProcesses: caller 10056 does not hold REAL_GET_TASKS; limiting output
03-07 12:01:39.743: W/ActivityManager(775): getRunningAppProcesses: caller 10056 does not hold REAL_GET_TASKS; limiting output
03-07 12:01:39.746: W/ActivityManager(775): getRunningAppProcesses: caller 10056 does not hold REAL_GET_TASKS; limiting output
03-07 12:01:40.725: W/ActivityManager(775): getRunningAppProcesses: caller 10056 does not hold REAL_GET_TASKS; limiting output
03-07 12:01:40.728: W/ActivityManager(775): getRunningAppProcesses: caller 10056 does not hold REAL_GET_TASKS; limiting output
03-07 12:01:40.740: W/ActivityManager(775): getRunningAppProcesses: caller 10056 does not hold REAL_GET_TASKS; limiting output
03-07 12:01:41.736: W/ActivityManager(775): getRunningAppProcesses: caller 10056 does not hold REAL_GET_TASKS; limiting output
03-07 12:01:41.753: W/ActivityManager(775): getRunningAppProcesses: caller 10056 does not hold REAL_GET_TASKS; limiting output
03-07 12:01:41.757: W/ActivityManager(775): getRunningAppProcesses: caller 10056 does not hold REAL_GET_TASKS; limiting output
03-07 12:01:41.955: I/ActivityManager(775): Start proc 4324:com.instagram.android/u0a126 for broadcast com.instagram.android/com.instagram.common.analytics.AnalyticsUploadAlarmReceiver
03-07 12:01:41.989: I/ActivityManager(775): Process com.boxer.email (pid 2234) has died
03-07 12:01:41.990: W/ActivityManager(775): Scheduling restart of crashed service com.boxer.email/com.boxer.exchange.service.EmailSyncAdapterService in 1000ms
03-07 12:01:41.990: W/ActivityManager(775): Scheduling restart of crashed service com.boxer.email/.service.ImapPopWorkerService in 11000ms
03-07 12:01:41.990: W/ActivityManager(775): Scheduling restart of crashed service com.boxer.email/.service.ImapSyncAdapterService in 21000ms
03-07 12:01:41.991: E/lowmemorykiller(273): Error writing /proc/3574/oom_score_adj; errno=22
03-07 12:01:41.992: E/lowmemorykiller(273): Error writing /proc/2854/oom_score_adj; errno=22
03-07 12:01:42.011: E/lowmemorykiller(273): Error writing /proc/3574/oom_score_adj; errno=22
03-07 12:01:42.011: E/lowmemorykiller(273): Error writing /proc/2854/oom_score_adj; errno=22
03-07 12:01:42.027: W/ResourcesManager(4324): Asset path '/system/framework/com.google.android.maps.jar' does not exist or contains no resources.
03-07 12:01:42.032: I/ActivityManager(775): Process com.google.android.googlequicksearchbox:search (pid 3574) has died
03-07 12:01:42.033: D/WifiService(775): Client connection lost with reason: 4
03-07 12:01:42.034: E/lowmemorykiller(273): Error writing /proc/2854/oom_score_adj; errno=22
03-07 12:01:42.046: E/JavaBinder(775): !!! FAILED BINDER TRANSACTION !!!
03-07 12:01:42.064: I/ActivityManager(775): Process com.android.vending (pid 2854) has died
03-07 12:01:42.104: I/LoadedApk(4324): No resource references to update in package common
03-07 12:01:42.104: I/LoadedApk(4324): No resource references to update in package com.cyngn.yu
03-07 12:01:42.105: I/LoadedApk(4324): No resource references to update in package com.cyngn.yu
03-07 12:01:42.113: D/a(4324): ACRA is enabled for com.instagram.android, intializing...

**Comment by schwabe** [comment]
**com.tngrnow.vpn2** That is not my app.

**Comment by saaserp** [comment]
how to solve
