### ISSUE TITLE
A problem occurred configuring root project 'ics-openvpn-master

### ISSUE THREAD

**Issue by ebayan** [schwabe/ics-openvpn#458]
Error:A problem occurred configuring root project 'ics-openvpn-master'.

> Could not resolve all dependencies for configuration ':classpath'.
> Could not resolve com.android.tools.build:gradle:2.0.0-beta6.
>      Required by:
>          :ics-openvpn-master:unspecified
>       > Could not resolve com.android.tools.build:gradle:2.0.0-beta6.
>          > Could not get resource 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.0.0-beta6/gradle-2.0.0-beta6.pom'.
>             > Could not GET 'https://jcenter.bintray.com/com/android/tools/build/gradle/2.0.0-beta6/gradle-2.0.0-beta6.pom'.
>                > Connection to https://jcenter.bintray.com refused

**Comment by schwabe** [comment]
Connection to https://jcenter.bintray.com refused

Check your internet connection
