### ISSUE TITLE
Blocking inputstream.read()

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#462]
From within my app

If openvpn is re-connecting, because the wifi was tuned off and on, it is possible for my app's `Socket.connect()` to succeed before the vpn connection is established. It appears as if openvpn is allowing to send a packet through the previous ip route but deletes these routes during re-connection. Preventing the ack message from being received and blocking the following `inputStream().read()` indefinitely.

`Socket.setSoTimeout()` is not an option.

Questions:
- Is the previous ip route saved in any way?
- When is the previous ip route deleted or changed?
- Should, my `Socket.connect()` not fail during a re-connect?

Edit:
After reviewing the code, the `openTun()` method clears the in memory routes and adds them to the VPN builder. But `Socket.connect()` will still succeed if attempted while openvpn is connecting.

**Comment by schwabe** [comment]
The persist-tun option does not allow network traffic to flow while the app is reconnecting.
