### ISSUE TITLE
Communication occurring without full connection

### ISSUE THREAD

**Issue by alexfournier** [schwabe/ics-openvpn#464]
It is possible to establish server communication without being fully connected through ics-openvpn.

While debugging I have noticed that my call to `Socket.connect()` will succeed even before ics-openvpn adds its routes.

This is tested by turning the wifi off/on (waiting for vpn to disconnect before turning back on) and attempting to communicate with a server while the vpn connection is being established. My `Socket.connect()` will succeed but any of my future calls to `Socket.getInputStream.read()` will block indefinitely.

**Comment by schwabe** [comment]
Sounds like a duplicate of #462.

**Comment by alexfournier** [comment]
Is the persist-tun the "Pause VPN connection after screen is off" setting?

**Comment by alexfournier** [comment]
Will test. Thanks for the response.

**Comment by alexfournier** [comment]
While reading and writing from the socket, if the wifi is turned off for more than 20 seconds, the socket remains open and blocks indefinitely.

My intended functionality is to close the socket if network is lost and prevent network traffic while reconnecting. Can openvpn close the open socket once network is lost?

**Comment by schwabe** [comment]
OpenVPN does not generate fake TCP reset packets. If you want to react to network event you should register a redeiver in your own app for Network changes.

**Comment by alexfournier** [comment]
Regarding  [#462](https://github.com/schwabe/ics-openvpn/issues/462). The persist-tun option is already enabled.

**Comment by schwabe** [comment]
but what is the question left you are asking?

**Comment by alexfournier** [comment]
The blocking `Socket.getInputStream.read()` was seen with the persist-tun option enabled. Are you saying it should be turned off?

**Comment by schwabe** [comment]
No, I am saying that is just normal network behaviour. On every system you also get blocking read() behaviour if the network is down.

**Comment by alexfournier** [comment]
I understand but how does my `Socket.connect()` succeed before openVPN is fully connected? 

I have been able to reproduce a situation that allows reading and writing to the socket before or while openVPN adds its routes. Once the connection is established, and the new VPN instance is created, my application will block on the next read() call.

**Comment by schwabe** [comment]
It connects using your old non VPN IP.  And that connection does not work over the VPN anymore. And you are using blocking read so the read will block until new data is available or the system detects that the connection is borken (can take minutes). That is how TCP/IP stacks work. That is nothing specific to my VPN app.

**Comment by alexfournier** [comment]
Sorry I've confused 2 issues. This is a similar issue to #195. Correct me if I misunderstood something.

**What steps will reproduce the problem?**
1. Enable WiFi and connect to VPN;
2. Disable WiFi (to force the VPN to reconnect) and, after mobile network is 
connected and while openVPN is reconnecting, begin communications with a remote server;
3. Socket read and write will work;
4. OpenVPN will report "connected";
5. The next read() will block

**What is the expected output? What do you see instead?**
It is supposed to prevent network access when reconnecting and 
"persistent tun" is enabled

Thank you again for your time.

**Comment by schwabe** [comment]
@alexfournier please provide an inapp log of that.
