### ISSUE TITLE
Feature Request: Support for static-challenge

### ISSUE THREAD

**Issue by splattner** [schwabe/ics-openvpn#467]
It would be nice to support:

`static-challenge "Enter Google Authenticator Code" 1`

used by an OpenVPN Access Server

**Comment by schwabe** [comment]
My problem with that is that I currently have no server to test that feature against.

**Comment by quentins** [comment]
@schwabe I have a test server set up that you can use, I'll reach out to you with login information.

**Comment by quentins** [comment]
@schwabe I haven't gotten any response from my email. are you interested in using the test server that I set up?

**Comment by jhopay** [comment]
Yes..i want to try..please?

**Comment by schwabe** [comment]
Sorry @quentins. My email program tells me that I sent you a reply. I will just copy&paste it here:

Thanks for setting a test server for me. I can however not really when I have time to look into that. It is still a spare time project for me (with occasional consulting). And at the moment I quite busy with other stuff. From first quick look it does not look like an easy 5 minute change to support this.

Arne

**Comment by quentins** [comment]
That's understandable, thanks for taking a look. I'm going to shutdown the test server for the time being, but let me know if it would ever be helpful again in the future.

**Comment by schwabe** [comment]
I think I will implement dynamic passsword query for a completely different reason over next 2-3 weeks. If you still have that test server lying around it would be good to be able to use it

**Comment by quentins** [comment]
Unfortunately I don't have that test server any more. I believe this AWS Marketplace image is a fast starting place to set up another test server though, and you can use up to 2 connections on OpenVPN for testing without any licenses.

https://aws.amazon.com/marketplace/pp/B00MI40CAE?ref=cns_srchrow

**Comment by panny-P** [comment]
Does openvpn support this feature yet?

**Comment by schwabe** [comment]
OpenVPN itself has supported that for ages. This client however does not.

**Comment by afrimberger** [comment]
According to https://openvpn.net/community-resources/management-interface/ (search for "static-challenge") the logic seems to be pretty straight forward to implement.
Ask the user for the pin/token, encode it base64 and send it via the "Auth" directive in the following format: `SCRV1:base64(password):base64(pin/token)`

Seems like this feature is not too hard to implement. Would be pretty nice if you could work on it in the "near" future, because its lack forces me to use the proprietary OpenVPN client :anguished: .

**Comment by schwabe** [comment]
I know how it works. The static challenge is ugly since it sends a AUTH_FAILED and the VPN connection stops. So supporting this, connection stopped but not really stopped needs a bit more refactoring :(

**Comment by schwabe** [comment]
For this app, I will continue supporting the modern crtext support but have little motivation/interest to implment the legacy options.

**Comment by regs01** [comment]
> My problem with that is that I currently have no server to test that feature against.

You can install OPNsense into virtual machine. It allows easy setup with dual and triple factor authentications.

**Comment by schwabe** [comment]
That comment was made over 8 years ago. But yes. The modern crtext is supported and I don't plan to implement `static-challenge` support any time soon.

**Comment by jazzl0ver** [comment]
hi. i've just sent you a PR with SCRV1 auth feature implementation. works good. please, merge
