### ISSUE TITLE
Security Alert from Google Play : OpenSSL security vulnerability

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#468]
Hello,

I received this message on Google Play Developer Console :

```

Security alert

Your app is using a version of OpenSSL containing a security vulnerability. Please see this Google Help Center article for details, including the deadline for fixing the vulnerability.
```

Any idea how to fix this?

Thank you.

**Comment by schwabe** [comment]
What does that have do with my app?

**Comment by ghost** [comment]
Does OpenVPN use SSL?

**Comment by schwabe** [comment]
First Google hit: SSL/TLS based user-space VPN. 

To make this clear: This is the bug tracker for OpenVPN for Android. Not for helping developer with random apps that use outdated OpenSSL versions.

**Comment by iceberg1369** [comment]
according the email sent to developers.
"Please migrate your app(s) to OpenSSL 1.02f/1.01r or higher as soon as possible and increment the version number of the upgraded APK"
I think ics-openvpn uses OpenSSL 1.0.2g and hence it should be OK
[check this commit](https://github.com/schwabe/platform_external_openssl/commit/f6da7c53fd01990e8e039dbfd5e9ea87e50d1d44)

**Comment by ghost** [comment]
I already fix this. I extract the latest OpenVPN for Android APK, get the Bin and Asset folder, and replace it on my existing project.

Thanks.

**Comment by ghost** [comment]
@schwabe This is related to OpenVPN for Android. It's ok already fix this my own.

TQ

**Comment by schwabe** [comment]
@neviel47 No it is not related to OpenVPN for Android. My app itself does not have the problem. Most app that are forked from my app are commercial illegal forks (violating the GPL). I have no desire support these.
