### ISSUE TITLE
could not read... 0/0

### ISSUE THREAD

**Issue by frostydoom** [schwabe/ics-openvpn#469]
Often on connection the log no matter the verbosity or date style fills screen 20:1 with error:

could not read log item from file: 0/0:

connection is successful despite error

v 0 6 49
android 444
root

**Comment by frostydoom** [comment]
It appears to write other items to list, but after logging stops flowing past they are unfindable scrolling. Only the stickied line atop the log is other than this error.

**Comment by schwabe** [comment]
Duplicate of #455, please use 0.6.50 to avoid the endless loop
