### ISSUE TITLE
Options error: Unrecognized option or missing or extra parameter(s)

### ISSUE THREAD

**Issue by Coehill** [schwabe/ics-openvpn#475]
My configuration in OpenVPN had been working until recently, it had stopped working.  When I tapped my configuration to begin running the VPN, it would not connect.  I tried reinstalling, and importing the config again, but had the same results.  Here is the log:

ICS OpenVPN log file
2016-04-16 21:43:50 F-Droid built and signed version 0.6.49 running on samsung SM-G920W8 (universal7420), Android 5.1.1 (LMY47X) API 22, ABI arm64-v8a, (samsung/zerofltebmc/zerofltebmc:5.1.1/LMY47X/G920W8VLU3BOJ7:user/release-keys)
2016-04-16 21:44:11 Building configuration…
2016-04-16 21:44:11 started Socket Thread
2016-04-16 21:44:11 Options error: Unrecognized option or missing or extra parameter(s) in /data/data/de.blinkt.openvpn/cache/android.conf:33: MIIBgTCB6zANBgkqhkiG9w0BAQ0FADCBpTELMAkGA1UEBhMCVVMxCzAJBgNVBAgT (2.4_master)
2016-04-16 21:44:11 Use --help for more information.
2016-04-16 21:44:11 Process exited with exit value 1

**Comment by schwabe** [comment]
There is to be something gone wrong in in the import process. I looks like part of a certificate became an option. Can you send me your original configuration file?

**Comment by Coehill** [comment]
Here is the original configuration file:

client
dev tun
remote ca-toronto.privateinternetaccess.com 1194 udp
remote ca-toronto.privateinternetaccess.com 53 udp
remote ca-toronto.privateinternetaccess.com 443 tcp
resolv-retry infinite
nobind
persist-key
persist-tun
setenv CLIENT_CERT 0

<ca>
-----BEGIN CERTIFICATE-----
MIID2jCCA0OgAwIBAgIJAOtqMkR2JSXrMA0GCSqGSIb3DQEBBQUAMIGlMQswCQYD
VQQGEwJVUzELMAkGA1UECBMCT0gxETAPBgNVBAcTCENvbHVtYnVzMSAwHgYDVQQK
ExdQcml2YXRlIEludGVybmV0IEFjY2VzczEjMCEGA1UEAxMaUHJpdmF0ZSBJbnRl
cm5ldCBBY2Nlc3MgQ0ExLzAtBgkqhkiG9w0BCQEWIHNlY3VyZUBwcml2YXRlaW50
ZXJuZXRhY2Nlc3MuY29tMB4XDTEwMDgyMTE4MjU1NFoXDTIwMDgxODE4MjU1NFow
gaUxCzAJBgNVBAYTAlVTMQswCQYDVQQIEwJPSDERMA8GA1UEBxMIQ29sdW1idXMx
IDAeBgNVBAoTF1ByaXZhdGUgSW50ZXJuZXQgQWNjZXNzMSMwIQYDVQQDExpQcml2
YXRlIEludGVybmV0IEFjY2VzcyBDQTEvMC0GCSqGSIb3DQEJARYgc2VjdXJlQHBy
aXZhdGVpbnRlcm5ldGFjY2Vzcy5jb20wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJ
AoGBAOlVlkHcxfN5HAswpryG7AN9CvcvVzcXvSEo91qAl/IE8H0knKZkIAhe/z3m
hz0t91dBHh5yfqwrXlGiyilplVB9tfZohvcikGF3G6FFC9j40GKP0/d22JfR2vJt
4/5JKRBlQc9wllswHZGmPVidQbU0YgoZl00bAySvkX/u1005AgMBAAGjggEOMIIB
CjAdBgNVHQ4EFgQUl8qwY2t+GN0pa/wfq+YODsxgVQkwgdoGA1UdIwSB0jCBz4AU
l8qwY2t+GN0pa/wfq+YODsxgVQmhgaukgagwgaUxCzAJBgNVBAYTAlVTMQswCQYD
VQQIEwJPSDERMA8GA1UEBxMIQ29sdW1idXMxIDAeBgNVBAoTF1ByaXZhdGUgSW50
ZXJuZXQgQWNjZXNzMSMwIQYDVQQDExpQcml2YXRlIEludGVybmV0IEFjY2VzcyBD
QTEvMC0GCSqGSIb3DQEJARYgc2VjdXJlQHByaXZhdGVpbnRlcm5ldGFjY2Vzcy5j
b22CCQDrajJEdiUl6zAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBBQUAA4GBAByH
atXgZzjFO6qctQWwV31P4qLelZzYndoZ7olY8ANPxl7jlP3YmbE1RzSnWtID9Gge
fsKHi1jAS9tNP2E+DCZiWcM/5Y7/XKS/6KvrPQT90nM5klK9LfNvS+kFabMmMBe2
llQlzAzFiIfabACTQn84QLeLOActKhK8hFJy2Gy6
-----END CERTIFICATE-----
</ca>

tls-client
remote-cert-tls server
auth-user-pass
comp-lzo
verb 1
reneg-sec 0

<crl-verify>
-----BEGIN X509 CRL-----
MIIBgTCB6zANBgkqhkiG9w0BAQ0FADCBpTELMAkGA1UEBhMCVVMxCzAJBgNVBAgT
Ak9IMREwDwYDVQQHEwhDb2x1bWJ1czEgMB4GA1UEChMXUHJpdmF0ZSBJbnRlcm5l
dCBBY2Nlc3MxIzAhBgNVBAMTGlByaXZhdGUgSW50ZXJuZXQgQWNjZXNzIENBMS8w
LQYJKoZIhvcNAQkBFiBzZWN1cmVAcHJpdmF0ZWludGVybmV0YWNjZXNzLmNvbRcN
MTQwNTA3MTgwOTE5WhcNMjQwNTA3MTgwOTE5WjAUMBICAQEXDTE0MDQyODIyMDMy
NVowDQYJKoZIhvcNAQENBQADgYEA4EA2wjio+BxYFui1mBj5gmypxUQyA7xQJ3Vo
cwWSllQKHpfmQ7fwyTL22uc21W9hM4geD1FwoXDUEraQjfyBJOxJwc6GOhTN2wHv
3vplKjdbXmxxAfjduBvlIB0a6qSz1L6hwZJrZUGimlWS9NQrmYaKLbtG07n2UyA+
mqz5bEc=
-----END X509 CRL-----
</crl-verify>

**Comment by Coehill** [comment]
It can be found at 

https://www.privateinternetaccess.com/pages/openvpn-ios

As per the instructions here:

https://www.privateinternetaccess.com/pages/client-support/android-openvpn-connect

Hopefully this helps.
