### ISSUE TITLE
ovpnlibs folder not created or found

### ISSUE THREAD

**Issue by robinbestvpn** [schwabe/ics-openvpn#476]
My Code

sourceSets {
        main {
            assets.srcDirs = ['src/main/assets', 'ovpnlibs/assets']
            jniLibs.srcDirs = ['ovpnlibs/jniLibs']
            jni.srcDirs = [] //disable automatic ndk-build

```
    }

    ovpn3 {

    }

    debug {

    }

    release {

    }
}
```

The ovpnslibs is not present in the folder

**Comment by schwabe** [comment]
See doc/README
