### ISSUE TITLE
Include of Apache v2 library that is not compatible with GPLv2.

### ISSUE THREAD

**Issue by roshakorost** [schwabe/ics-openvpn#477]
Android support library is distributed under the Apache License, Version 2.0.

Apache License, Version 2.0 **is not compatible** with GPLv2 License, according to the [GNU site](http://www.gnu.org/licenses/license-list.en.html#apache2.)

**Comment by schwabe** [comment]
Hm, while that is not a problem for my app, it is a problem for everyone who forks the app. But the license of my app is actually GPLv2 and later, so it should not be a problem for other users as well. 

But plenty of Android project are using the Android library and are GPLv2, so not many people seem to noitce that.
