### ISSUE TITLE
Performance improvement of AsyncTask.execute

### ISSUE THREAD

**Issue by LiliWeiSE** [schwabe/ics-openvpn#480]
Developers of OpenVPN for Android,

Hi, I've found that on line 37 of FaqViewAdapter, `AsyncTask.execute()` is used. However, using this API became slower on devices with OS version newer than 3.0. After 3.0, `AsyncTask.execute()` scheduled tasks to be executed serially on a single background thread. (As stated in the [API guide](http://developer.android.com/intl/zh-cn/reference/android/os/AsyncTask.html#execute%28Params...%29))
This influence the performance of FAQ as multiple FAQ entries have to be loaded (if I didn't misunderstand your code :)).
This can be improved by using `executeOnExecutor` instead to make them executed in real multi-thread.

Thanks.

**Comment by schwabe** [comment]
What you say is true, however that asynctask does very little work to begin with. It is just doing some string modification. So I find it doubious with parallel execution helps that.

**Comment by LiliWeiSE** [comment]
Thanks for your explanation.
