### ISSUE TITLE
[Question] file extension for cert files?

### ISSUE THREAD

**Issue by TheTechmage** [schwabe/ics-openvpn#481]
Hello,

I'm trying to figure out how to add my certificate files via Google drive. When I add a key, Google drive appears to filter on .key extension based files and I can do that. When I'm trying to add the certificates however, it appears to be filtering on something other than .CRT as I cannot add my certificates. :( What format are certificates supposed to be in? What file extension so they need to have in order to be added manually?

Thanks very much! :)

**Comment by schwabe** [comment]
The selection works on file mime type. I hacked together a small app that shows the mime type:

plai.de/.tmp/cursor.apk

Can you try to find what mime type your crt files have?

**Comment by TheTechmage** [comment]
Awesome little app, thank you! Here is the info:

| key | value |
| --- | --- |
| _id | acc=1;doc=7406 |
| document_id | acc=1;doc=7406 |
| _display_name | nexus6.crt |
| _size | 5447 |
| mime_type | application/pkix-cert |
| flags | 263 |
| ... | ... |

Certificates and keys created on Gentoo using [the Arch Wiki key generation tutorial](https://wiki.archlinux.org/index.php/Easy-rsa).
