### ISSUE TITLE
RemoteExample not connecting

### ISSUE THREAD

**Issue by aneeshATgithub** [schwabe/ics-openvpn#482]
While clicking "Start embedded profile" button in RemoteExample project,  I am getting the following logs and not connecting, I used Android Version 4.2.2

de.blinkt.openvpn.remote D/dalvikvm: GC_CONCURRENT freed 2390K, 45% free 4883K/8824K, paused 2ms+3ms, total 30ms

de.blinkt.openvpn.remote D/dalvikvm: WAIT_FOR_CONCURRENT_GC blocked 27ms

de.blinkt.openvpn.remote E/dalvikvm: adjustAdaptiveCoef max=4194304, min=1048576, ut=568

**Comment by schwabe** [comment]
That logcat is just usual android/java memory management. What does the OpenVPN for Android log say?

**Comment by schwabe** [comment]
Tested on Android 6.0 and 4.0, I cannot reproduce this.
