### ISSUE TITLE
Cannot connect with Android N

### ISSUE THREAD

**Issue by sshaikh** [schwabe/ics-openvpn#488]
I'm having trouble connecting to a VPN using the same OVPN file after upgrading to Android N. 

The logs indicate a timeout during TLS negotiation.

Any idea how I can diagnose the issue?

**Comment by schwabe** [comment]
Are you that this Android N related? Running tcpdump on the server is a good idea.

**Comment by sshaikh** [comment]
This is against a Tomato router. I'll figure out how to run tcpdump but in the meantime I see these logs there:

May 15 12:14:17 router daemon.err openvpn[4564]: Authenticate/Decrypt packet error: packet HMAC authentication failed
May 15 12:14:17 router daemon.err openvpn[4564]: TLS Error: incoming packet authentication failed from [AF_INET]<ip>

**Comment by schwabe** [comment]
That sounds more like a VPN misconfiguration and not something to do with Android N. OpenVPN runs fine with Android N preview here.

**Comment by sshaikh** [comment]
Okay. Perhaps something went wrong in the upgrade. I can start again - do you have a recommended source to generating settings etc?

**Comment by schwabe** [comment]
Import a working ovpn config and openvpn tutorial.

**Comment by sshaikh** [comment]
This config was working correctly before upgrading to N. I'll see if it continues to work on my MM devices. Thanks for the help.
