### ISSUE TITLE
how to to fill "Corporate Contributor Information" in CLA

### ISSUE THREAD

**Issue by luoqii** [schwabe/ics-openvpn#490]
how to fill in "Corporate Contributor Information" on signing CLA

**Comment by luoqii** [comment]
aa error occur :
"We're sorry, but something went wrong."

**Comment by schwabe** [comment]
Hm. That is annoying that the website does not work. I hope that gets fixed. As last alternative you can always print/scan/send via email that agreement.

**Comment by luoqii** [comment]
Is indeed need for a strict CLA?

**Comment by schwabe** [comment]
For my right to relicense unfortenately I fear so. You can still open a pull request and I can give some feedback on it or see what the problem was and commit my own solution.

**Comment by luoqii** [comment]
Ok, i understand .

Thx
