### ISSUE TITLE
guidelines for contributing

### ISSUE THREAD

**Issue by syam86** [schwabe/ics-openvpn#494]
To make issues more managable, I would appriciate if you fill out the details if applicable
# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
# Description of the issue

**Comment by schwabe** [comment]
Iusse without any text.

**Comment by syam86** [comment]
Android version

**Comment by schwabe** [comment]
@syam86 ?
