### ISSUE TITLE
Feature request: force forbidden the 2G/3G/4G when the openvpn disconnected

### ISSUE THREAD

**Issue by zhangguoqing** [schwabe/ics-openvpn#495]
I'm always using openvpn with 4G on my Android. I want to achieve that force forbidden or stop the 4G mobile network immediately when the openvpn client is disconnected whatever reasons.

**Comment by zhangguoqing** [comment]
If it hard to stopping the 4G mobile network immediately, could openvpn give a prompt  windows whatever the scenes(eg. full screen) user in.

**Comment by zhangweiqwe** [comment]
你是中国人吗

**Comment by zhangweiqwe** [comment]
请问有没openlibs，就是需要linux便宜的库

**Comment by zhangweiqwe** [comment]
857899299这是我qq，方便说一下你的联系方式吗，遇到个中国的不容易

**Comment by tonsimple** [comment]
@zhangguoqing 
If your device is rooted and supports initd you could achieve a very "close to cigar" effect via iptables rules.
Without good initd support things might get tricky (you could load iptables rules by, say, automagic4android's script calling a .sh script, but there will be a moment at device start when leakiness is possible)

I don't have my "bottled up" tablet with me now, so can't post my own iptables rules right away.

I suggest you read up on iptables and write your own.

BTW, when writing the iptables rules bear in mind that you need to let ics-openvpn "out" of filtering or VPN won't connect.
Also you need to allow DNS traffic out (or use DNSCrypt and allow DNSCrypt traffic out)

**Comment by schwabe** [comment]
This is just not achievable with the VPN api
