### ISSUE TITLE
Use VPN password in Remote App

### ISSUE THREAD

**Issue by Graphicscore** [schwabe/ics-openvpn#496]
Hello, 
I am currently trying to implement the OpenVPN aidl api into my app.
I successfully adapted the Remote Example and was able to use my openvpn profile, is there a good way to automatically pass a password ? Because right now it's always asking for the password for the profile.

**Comment by schwabe** [comment]
Do you need only for importing a profile? If yes you can simply use:

```
<auth-user-pass>
user
pass
</auth-user-pass>
```

for the imported profile.

**Comment by Graphicscore** [comment]
@schwabe , Well , currently I am using the IOpenVPNAPIService.startVPN function to load a vpn config from a file, but it asks for a password. I want to start the vpn profile without the password dialog(e.g provide a password in code)

**Comment by schwabe** [comment]
@Graphicscore Yes specifying that `<auth-user-pass>` section in the String/file you use as paramter should work. If not or if your usecase requires something else, I need a bit more details.

**Comment by Graphicscore** [comment]
@schwabe The thing is, I have the password for the openvpn profile but not the user, it's not specified in the openvpn config, as far as I can see. And if I load the openvpn config only the password is asked.

_Edit_ : Seems like I have the username. 

But it seems like it's not working

I double checked my code, the 'problem' is that the openvpn config is autogenerated from a server and does not contain these auth information.

I'm using this method to start the vpn profile : 

```
private void startVPN(File configFile, boolean addNew)
    {
        try {
            FileInputStream conf = new FileInputStream(configFile);
            InputStreamReader isr = new InputStreamReader(conf);
            BufferedReader br = new BufferedReader(isr);
            String config = "";
            config += "<auth-user-pass>\n" +
                    "mySuperSecretUsername\n" +
                    "mySuperSecretPassword\n" +
                    "</auth-user-pass>\n";

            String line;
            while (true) {
                line = br.readLine();
                if (line == null)
                    break;
                config += line + "\n";
            }


            br.readLine();

            if (addNew) {
                mService.addNewVPNProfile("nonEditable", false, config);
            } else {
                mService.startVPN(config);
            }
        }catch (Exception e){
            e.printStackTrace();
        }
    }
```

**Comment by schwabe** [comment]
The config from the server might have a auth-user-file in it you need to drop/remove that. (Double the line does not work).

The default config (test.conf) of the remoteExample also has this auth-user-pass in it and it works (you will get an auth failed with it but it does not ask for the pw/user)

**Comment by Graphicscore** [comment]
@schwabe 
I checked my config there are no auth-user =).

I did a little research , maybe I am just stupid ....

I spend quite a lot time reading your source code.
I think I could track down my specific issue quite well, and now I am going to try to explain what I think might be the problem.

My apps calls the [startVPN(String inlineConfing) ](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java#L179)function.

Your [ConfigParser](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java#L182) reads the auth information [from the inlineConfig](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java#L184) ,[creates an VPNProfile](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java#L185) object and saves the username into mUsername and the password into mPassword [(Line 810)](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/core/ConfigParser.java#L810)

Now my vpn profile gets routed through various methods and handlers until it's finally attempting to start.

The function [needUserPWInput](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/VpnProfile.java#L950) is called to determ if a password promt is needed.
I run into 
`if (mAuthenticationType == TYPE_CERTIFICATES || mAuthenticationType == TYPE_USERPASS_CERTIFICATES)`
which leads into checking wether mTransientPCKS12PW and / our mKeyPassword are equal to null.
Which they are due to the fact that the ConfigParser just sets mPassword on the VPNProfile.

I forked your resposity and locally set `mPKCS12Password` , `mPassword` and `mKeyPassword` to the same statical value (for testing purposes) and was able to connect without issues.

```
vpnProfile.mPKCS12Password = "test";
vpnProfile.mPassword = "test";
vpnProfile.mKeyPassword = "test";

```

**Comment by schwabe** [comment]
What password are you being asked for? The password for user? Or the password for the certificate? I you post your VPN (or email me it via email) I could take a look

**Comment by Graphicscore** [comment]
@schwabe How do I know which password is requested, I am not that advanced with OpenVPN profiles. :o

I can say for sure that the 
mAuthenticationType of my VpnProfile is either `TYPE_CERTIFICATES` or `TYPE_USERPASS_CERTIFICATES`.

Which leads to returning [`R.string.private_key_password`](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/VpnProfile.java#L960)

Now if the VPN is launched and it looks for the password [LaunchVPN.askForPW()](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/LaunchVPN.java#L119) he creates a singline line dialog asking for [`mTransientPCKS12PW`](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/java/de/blinkt/openvpn/LaunchVPN.java#L167) since the type is not eqal to `R.string.password`

**Comment by schwabe** [comment]
Oh, you do not have user and password authentification, you have an encrypted key file. The easiest way would to deencrypt that file in your app and then use the decrypted file inside the `<key>` statement.

**Comment by Graphicscore** [comment]
So you mean I have to decrypt the String that's between `<key>xXxXXXXxXxXXxXX</key>`?
It's RSA encrypted if I am right ? How do I properly decrypt this on Android with a password ? 
I'm sorry that I am so annoying.

**Comment by schwabe** [comment]
http://stackoverflow.com/questions/10517930/how-to-encrypt-decrypt-with-rsa-keys-in-java

That should get you started. I can also look into an API that takes a password for the private file but decrypting it yourself should work in any way.

**Comment by Graphicscore** [comment]
Alright, I'll try that out and let you know if it works or not , Thanks !

**Comment by schwabe** [comment]
I am closing this since I assumed it works as tehre are no followups
