### ISSUE TITLE
is socks-proxy directive supported? [question]

### ISSUE THREAD

**Issue by tonsimple** [schwabe/ics-openvpn#499]
After successfully tunneling OpenVPN over shadowsocks on desktop (Chinese woes, works remarkably better than just openvpn or openvpn over obfsproxy) I decided to try it on android, but I need a client that supports socks-proxy directive (shadowsocks is very okay with udp traffic, at least on desktop)

Does ics-openvpn support the socks-proxy directive ?

**Comment by schwabe** [comment]
Yes. Although you to specify it as custom option.
