### ISSUE TITLE
 Bad encapsulated packet length from peer (15464), which must be > 0 and <= 1547 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]

### ISSUE THREAD

**Issue by yuanquan8** [schwabe/ics-openvpn#502]
10:22 WARNING: Bad encapsulated packet length from peer (15464), which must be > 0 and <= 1547 -- please ensure that --tun-mtu or --link-mtu is equal on both peers -- this condition could also indicate a possible active attack on the TCP link -- [Attempting restart...]

Excuse me, how to solve, thank you

**Comment by yuanquan8** [comment]
## 使用wap接入点进行连接的时候，提示这个，使用Net就没有问题，请问这是什么原因呢？

When using wap access point to connect, suggesting that, using.net, there is no problem, what reason is this excuse me?

**Comment by schwabe** [comment]
That issue is OpenVPN generic. It is better to raise and discuss it on openvpn-devel
