### ISSUE TITLE
Building openvpn and openssl libraries in Android Studio using gradle

### ISSUE THREAD

**Issue by nanditasuri** [schwabe/ics-openvpn#504]
Description of the issue:
Trying to compile the ics-openvpn code in Android Studio 2.2
Motive is to debug the app and understand the code flow. Want to step into C/C++ code from Java .
Is this possible with ics-openvpn code ?

**Comment by schwabe** [comment]
never tried that. And since openvpn itself is running in a different task you probably need to get a setup working with ndk-gdb and so on. 

If you just want to debug openvpn it is easier to run openvpn on a pc and debug it there. That is how I debug all of the openvpn problem. Fortenately I never needed to debug openvpn itself on Android.

**Comment by nanditasuri** [comment]
Thank you Schwabe for quick reply. I have a question : Is there any document about the android app (ics-openvpn) design or interaction with openvpn process?
I guess that would give a better perspective of how ManagementInterface is getting commands from openvpn.
can you please help me out.

**Comment by schwabe** [comment]
the management interface is described in doc/management.txt of OpenVPN itself

**Comment by nanditasuri** [comment]
Yes, i have seen that. 
But, is there any document about android app design and interaction between components such as openvepn server, client, managemnet interface, vpnservice?

**Comment by schwabe** [comment]
@nanditasuri No, there isn't. It is just a one man spare time opensource project. I don't do design documents in my spare time :P

**Comment by nanditasuri** [comment]
hmm.. what you said is a fair point. Thanks !

**Comment by schwabe** [comment]
Most of the communication with OpenVPN is hte OpenVPNmanagement class (or similar). Communication with VPNService is in OpenVPNService

**Comment by nanditasuri** [comment]
Thank you schwabe.  one more quick question . I am trying to use misc/debug-openvpn.sh ?  does this script debug openvpn ? does this work.

**Comment by schwabe** [comment]
no that script never worked.

**Comment by nanditasuri** [comment]
@schwabe  how do you debug openvpn on laptop as you mentioned earlier in your comment.
Do you have any steps to do that ?
I am trying to run openvpn on my mac laptop, but it fails to connect to server.
Thanks heaps!

**Comment by schwabe** [comment]
@nanditasuri just the good old git clone;build and then using gdb (or lldb on a mac).

**Comment by nanditasuri** [comment]
Thanks schwabe. I am doing the same.. 
I did a git clone.  build and installed on mac.
when i run openvpn --config mac.conf (attaching the conf file) -> i get socket error as i have management command in the conf file. I got this conf file from ics-openvpn when the app is installed on the android device.
so, not sure how would it work on mac. Could you please share the conf file or the way you run the openvpn command to connect to the server?
Am i doing something wrong here ?

**Comment by nanditasuri** [comment]
[mac.conf.zip](https://github.com/schwabe/ics-openvpn/files/332593/mac.conf.zip)

**Comment by schwabe** [comment]
when running that way you should remove the management lines.

**Comment by schwabe** [comment]
Btw. I almost forget. There is also this docu: https://github.com/OpenVPN/openvpn/blob/master/doc/android.txt

**Comment by nanditasuri** [comment]
Thanks for the link @schwabe .

 I was going through the change log in https://github.com/schwabe/openvpn/blob/b89b098fc66488b921729cf7e83016962ccd9d2e/ChangeLog
and realized that the version of openvpn used is 2.3 beta.
Is it not updated to 2.3 release version ? can you please confirm.

If we have to use the latest openvpn 2.3 release code for the android openvpn application, what changed are needed?

**Comment by schwabe** [comment]
No it is neither. It is the current OpenVPN development version (master). You looked in an extremely old branch.

**Comment by nanditasuri** [comment]
@schwabe , i some times get 
MGMT: Got unrecognized command>FATAL:UDP: Cannot create UDP/UDP6 socket: Too many open files (errno=24)
when openvpn tries to reconnect to the vpn server after network changes on device.
Why does this happen ? Is this a known issue.

**Comment by schwabe** [comment]
@nanditasuri you need provide details than that one line.
