### ISSUE TITLE
Cannot find .git directory in openvpn, aborting

### ISSUE THREAD

**Issue by zhangweiqwe** [schwabe/ics-openvpn#507]
如下面

Such as the following

[root@localhost main]# svn co http://google-breakpad.googlecode.com/svn/trunk/ google-breakpad
svn: E175002: Unable to connect to a repository at URL 'http://google-breakpad.googlecode.com/svn/trunk'

[root@localhost main]# ./misc/build-native.sh USE_BREAKPAD=0
Cannot find .git directory in openvpn, aborting

I spend a lot of attention to this import this project, but I won't be many things, I only ask you, talk to me is to rely on translation.

Today, I installed the Linux system configuration of all the development environment, I really want to import.

I haven't met before these errors may be the cause of the NDK

centos 7.0  profile
# set NDK env

NDKROOT=/home/wsgwz/zhuomian/android-ndk-r10d

export PATH=$NDKROOT:$PATH
# jdk

export JAVA_HOME=/home/wsgwz/zhuomian/jdk1.8.0_91  
export JRE_HOME=/home/wsgwz/zhuomian/jdk1.8.0_91/jre  
export PATH=$PATH:/home/wsgwz/zhuomian/jdk1.8.0_91/jre/bin 
export CLASSPATH=./:/home/wsgwz/zhuomian/jdk1.8.0_91/lib:/home/wsgwz/zhuomian/jdk1.8.0_91/jre/lib
# sdk

SDKROOT=/home/wsgwz/Android/Sdk
export PATH=$SDKROOT:$PATH
export PATH=${PATH}:SDKROOT:/home/wsgwz/Android/Sdk/tools

我为了这个导入这个项目花了不少心思，但许多东西我不会，我只有问你们，我说话都是依靠翻译。
就今天，我装了linux系统配置了所有的开发环境，我非常希望能导入。
这些错误之前我没遇到可能是ndk的原因吧

希望有个中国的

**Comment by schwabe** [comment]
You are still missing steps from the readme (git submodle part). Btw. the README states that breakpad is optional.

And please stop opening a new issue for every problem you encounter. Replying to old/closed is fine.

**Comment by boynicholas** [comment]
Hi，很高兴能够帮助到你。

你需要按照ReadMe中的提示进行。使用git clone将该项目导入下来。然后在主目录执行：git submodle init。
