### ISSUE TITLE
git submodule init

### ISSUE THREAD

**Issue by zhangweiqwe** [schwabe/ics-openvpn#508]
schwabe : excuse me, thank you for your answer my question, although this problem is a Childish question 

Fetch the git submodules (the default urls for the submoles use ssh,
setup your own github ssh key or change the url to http in .gitmodules):
git submodule init
git submodule update

What is default urls？
 is http://google-breakpad.googlecode.com/svn/trunk/ google-breakpad?
Unable to connect the site in China，The government didn't allow Google 

[wsgwz@localhost ~]$ svn co http://google-breakpad.googlecode.com/svn/trunk/
svn: E175002: Unable to connect to a repository at URL 'http://google-breakpad.googlecode.com/svn/trunk'

I don't quite understand the meaning of this step, how to do 

Readme.txt have to see the more than 20 times 

I am really very attentively, but there are many do not understand, friends just know lot, rarely used. Spend a lot of time reading English 

Feel very silly

**Comment by schwabe** [comment]
I cannot really tell you more than: setup your own github ssh key or change the url to http in .gitmodules

**Comment by zhangweiqwe** [comment]
[root@localhost ics-openvpn]# git submodule init
子模组 'main/openssl' (git@github.com:schwabe/platform_external_openssl.git) 已为路径 'main/openssl' 注册
子模组 'main/openvpn' (git@github.com:schwabe/openvpn.git) 已为路径 'main/openvpn' 注册

[root@localhost main]# ./misc/build-native.sh
Cannot find .git directory in openvpn, aborting

**Comment by zhangweiqwe** [comment]
/mian/openvpn need     exec  git init?

**Comment by schwabe** [comment]
> git submodule update

**Comment by zhangweiqwe** [comment]
[wsgwz@localhost ~]$ cd /home/wsgwz/zhuomian/me2studio/ics-openvpn
[wsgwz@localhost ics-openvpn]$ git submodule init
子模组 'main/openssl' (git@github.com:schwabe/platform_external_openssl.git) 已为路径 'main/openssl' 注册
子模组 'main/openvpn' (git@github.com:schwabe/openvpn.git) 已为路径 'main/openvpn' 注册
[wsgwz@localhost ics-openvpn]$ git submodule update
正克隆到 'main/openssl'...
The authenticity of host 'github.com (192.30.252.129)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.129' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
无法克隆 'git@github.com:schwabe/platform_external_openssl.git' 到子模组路径 'main/openssl'

**Comment by zhangweiqwe** [comment]
I have to work overtime for two hours, if again a little later the bus went out, the rest of the tomorrow I continue to get, thank you for your reply and help

**Comment by zhangweiqwe** [comment]
I am so get project 
git clone https://github.com/schwabe/ics-openvpn.git

**Comment by schwabe** [comment]
@zhangweiqwe https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by zhangweiqwe** [comment]
Thank you, now I'll try

**Comment by zhangweiqwe** [comment]
I've compiled library, thank you very much ，but build project 20 minutes already，

**Comment by zhangweiqwe** [comment]
I have already run successfully

But after import the configuration file to run an error
12:00:49
我思故我在 2016/6/24 12:00:49
2016-06-24 12:00:22 由 C=US,O=Android,CN=Android Debug 构建 0.6.56 running on Meizu MX4 Pro (mx4pro), Android 5.1.1 (LMY48W) API 22, ABI armeabi-v7a, (Meizu/meizu_mx4pro/mx4pro:5.1.1/LMY48W/1463710457:user/release-keys)
2016-06-24 12:00:22 正在生成配置
2016-06-24 12:00:22 started Socket Thread
2016-06-24 12:00:22 Options warning: Bad backslash ('\') usage in /data/data/de.blinkt.openvpn/cache/android.conf:33: remember that backslashes are treated as shell-escapes and if you need to pass backslash characters as part of a Windows filename, you should use double backslashes such as "c:\openvpn\static.key"
2016-06-24 12:00:22 Use --help for more information.
2016-06-24 12:00:22 Process exited with exit value 1

**Comment by zhangweiqwe** [comment]
setenv IV_GUI_VER "de.blinkt.openvpn 0.6.17" 
machine-readable-output
client
dev tun
connect-retry-max 5
connect-retry 5
resolv-retry 60
http-proxy-option EXT1 "POST http://wap.cmvideo.cn"
http-proxy-option EXT1 "GET http://wap.cmvideo.cn"
http-proxy-option EXT1 "X-Online-Host: wap.cmvideo.cn"
http-proxy-option EXT1 "POST http://wap.cmvideo.cn"
http-proxy-option EXT1 "X-Online-Host: wap.cmvideo.cn"
http-proxy-option EXT1 "POST http://wap.cmvideo.cn"
http-proxy-option EXT1 "Host: wap.cmvideo.cn"
http-proxy-option EXT1 "GET http://wap.cmvideo.cn"
http-proxy-option EXT1 "Host: wap.cmvideo.cn"
http-proxy 117.169.17.247 80

<http-proxy-user-pass>
sbwml2016
admin
</http-proxy-user-pass>

remote 117.169.17.247 443 tcp-client
resolv-retry infinite
nobind
persist-key
persist-tun
push route 114.114.114.114 114.114.115.115

<ca>
-----BEGIN CERTIFICATE-----
MIIE6DCCA9CgAwIBAgIJAONNYXbiYVI2MA0GCSqGSIb3DQEBCwUAMIGoMQswCQYD
VQQGEwJDTjESMBAGA1UECBMJR3VhbmdEb25nMRIwEAYDVQQHEwlHdWFuZ1pob3Ux
FTATBgNVBAoTDHd3dy5zYndtbC5jbjEPMA0GA1UECxMGaVBob25lMRgwFgYDVQQD
Ew93d3cuc2J3bWwuY24gQ0ExEDAOBgNVBCkTB09wZW5WUE4xHTAbBgkqhkiG9w0B
CQEWDlRELUxURUBZVU4uQ09NMB4XDTE2MDYxNDEzMjc1M1oXDTI2MDYxMjEzMjc1
M1owgagxCzAJBgNVBAYTAkNOMRIwEAYDVQQIEwlHdWFuZ0RvbmcxEjAQBgNVBAcT
CUd1YW5nWmhvdTEVMBMGA1UEChMMd3d3LnNid21sLmNuMQ8wDQYDVQQLEwZpUGhv
bmUxGDAWBgNVBAMTD3d3dy5zYndtbC5jbiBDQTEQMA4GA1UEKRMHT3BlblZQTjEd
MBsGCSqGSIb3DQEJARYOVEQtTFRFQFlVTi5DT00wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDBqr0VRPhskAySYZEGrSpHGPbgoTJN3DTpU69YjikCQgAM
IiqyuvQbG8TwoMvOG2nuQjTnaU36D7prwVxSowWmx2rALJQPcab2XppBEAimG3L8
I7R1a9Wt56vz9Zqr2Jh1vPPSTqANwkilxGoUQdFrS8+NmJ0oU/tMugJAJgnBsgOR
HVEqCKSeNBpyOacM2XmyrXw6DqgLcGGQqnOBy7S4Uqt+tIbFWLYkieSCKrFEnUWa
9VBPtaoZddDTyQbJ+wi7i9TCX/hXd7zlngOQv9QigcyEREYGZqihE3QBFXtJWW5d
0qHnwYsmc9cZ+SBYLmMhDcNKRwPgBR6YupGiNtvhAgMBAAGjggERMIIBDTAdBgNV
HQ4EFgQUnPlDUCc4xc453FYqyIilyzn79Pswgd0GA1UdIwSB1TCB0oAUnPlDUCc4
xc453FYqyIilyzn79Puhga6kgaswgagxCzAJBgNVBAYTAkNOMRIwEAYDVQQIEwlH
dWFuZ0RvbmcxEjAQBgNVBAcTCUd1YW5nWmhvdTEVMBMGA1UEChMMd3d3LnNid21s
LmNuMQ8wDQYDVQQLEwZpUGhvbmUxGDAWBgNVBAMTD3d3dy5zYndtbC5jbiBDQTEQ
MA4GA1UEKRMHT3BlblZQTjEdMBsGCSqGSIb3DQEJARYOVEQtTFRFQFlVTi5DT02C
CQDjTWF24mFSNjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQA2fno0
1qAFegI7euHv35d3pR5wpGTSw8MAo+MqznsogTncZNAoPxLJctluxtP7VSsyZaGp
B26+YhWGfTSt50UvevhdMiPBlTGZHjJPrWy1FpPg9MRzFTQehKjXHbU3p6jUK+yV
BWpWy02AgbemoZ9jM9GIy42BmOudSmv/jqaraIimldi+Ck2vgVFg/CQCwrro9E7K
V77kxlLrJfmUHhtfHladuQfzqKnugreqDezXoRx4T5cXZAPpTq+aujPOJrkRbAn4
mCj3Q4bJIz28idELEofuQZzdRj7G9g9ydhMn/r8w1jSsjUUoPiaHqZdcxACREt4L
nuQ5G3Kfy2ZxFJBi
-----END CERTIFICATE-----
</ca>
key-direction 1
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
cd7dccda2890c6eae58f31eeb9355f1e
c33a437268cc90cc767978b0330d122a
22c02300c4999ec4cfd2aac1f713d478
7123109053bca82bf683b2466d4a42bd
3e4407a13205aca7442236a39dd1a2fd
2e6da51d6de5816a818d26c809b78b6d
4861ae56d159535c9a0073d4d454312c
ab26fd2c21c5877f2d056ac8c9f12869
24b439df6c0cead359ba91011aff8c8e
fc9c8fadc8d31a042a78267abce29dbb
926478828090fe79c8edfe04698f62fd
3a8d847025b8466b340ca134d9bc7f3e
42009707ba5ce302e904c119e30eaa61
6d74f9207a7853553280befe1c86c9cd
8f13f4a240a1120a902de13e821e15c6
f625d5f9030b25590523b0a7021cc937
-----END OpenVPN Static key V1-----
</tls-auth>
auth-user-pass
ns-cert-type server
comp-lzo
verb 3

**Comment by schwabe** [comment]
Posting private keys on the internet is a bad idea. And the error message does not match the pasted config

**Comment by zhangweiqwe** [comment]
# Enables connection to GUI
management /data/data/de.blinkt.openvpn/cache/mgmtsocket unix
management-client
management-query-passwords
management-hold

setenv IV_GUI_VER "de.blinkt.openvpn 0.6.56" 
setenv IV_PLAT_VER "22 5.1.1 armeabi-v7a Meizu mx4pro MX4 Pro"
machine-readable-output
ifconfig-nowarn
client
verb 4
connect-retry-max 5
connect-retry 5
resolv-retry 60
dev tun
remote 117.169.17.247 443 tcp-client
auth-user-pass
<ca>
-----BEGIN CERTIFICATE-----
MIIE6DCCA9CgAwIBAgIJAONNYXbiYVI2MA0GCSqGSIb3DQEBCwUAMIGoMQswCQYD
VQQGEwJDTjESMBAGA1UECBMJR3VhbmdEb25nMRIwEAYDVQQHEwlHdWFuZ1pob3Ux
FTATBgNVBAoTDHd3dy5zYndtbC5jbjEPMA0GA1UECxMGaVBob25lMRgwFgYDVQQD
Ew93d3cuc2J3bWwuY24gQ0ExEDAOBgNVBCkTB09wZW5WUE4xHTAbBgkqhkiG9w0B
CQEWDlRELUxURUBZVU4uQ09NMB4XDTE2MDYxNDEzMjc1M1oXDTI2MDYxMjEzMjc1
M1owgagxCzAJBgNVBAYTAkNOMRIwEAYDVQQIEwlHdWFuZ0RvbmcxEjAQBgNVBAcT
CUd1YW5nWmhvdTEVMBMGA1UEChMMd3d3LnNid21sLmNuMQ8wDQYDVQQLEwZpUGhv
bmUxGDAWBgNVBAMTD3d3dy5zYndtbC5jbiBDQTEQMA4GA1UEKRMHT3BlblZQTjEd
MBsGCSqGSIb3DQEJARYOVEQtTFRFQFlVTi5DT00wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDBqr0VRPhskAySYZEGrSpHGPbgoTJN3DTpU69YjikCQgAM
IiqyuvQbG8TwoMvOG2nuQjTnaU36D7prwVxSowWmx2rALJQPcab2XppBEAimG3L8
I7R1a9Wt56vz9Zqr2Jh1vPPSTqANwkilxGoUQdFrS8+NmJ0oU/tMugJAJgnBsgOR
HVEqCKSeNBpyOacM2XmyrXw6DqgLcGGQqnOBy7S4Uqt+tIbFWLYkieSCKrFEnUWa
9VBPtaoZddDTyQbJ+wi7i9TCX/hXd7zlngOQv9QigcyEREYGZqihE3QBFXtJWW5d
0qHnwYsmc9cZ+SBYLmMhDcNKRwPgBR6YupGiNtvhAgMBAAGjggERMIIBDTAdBgNV
HQ4EFgQUnPlDUCc4xc453FYqyIilyzn79Pswgd0GA1UdIwSB1TCB0oAUnPlDUCc4
xc453FYqyIilyzn79Puhga6kgaswgagxCzAJBgNVBAYTAkNOMRIwEAYDVQQIEwlH
dWFuZ0RvbmcxEjAQBgNVBAcTCUd1YW5nWmhvdTEVMBMGA1UEChMMd3d3LnNid21s
LmNuMQ8wDQYDVQQLEwZpUGhvbmUxGDAWBgNVBAMTD3d3dy5zYndtbC5jbiBDQTEQ
MA4GA1UEKRMHT3BlblZQTjEdMBsGCSqGSIb3DQEJARYOVEQtTFRFQFlVTi5DT02C
CQDjTWF24mFSNjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQA2fno0
1qAFegI7euHv35d3pR5wpGTSw8MAo+MqznsogTncZNAoPxLJctluxtP7VSsyZaGp
B26+YhWGfTSt50UvevhdMiPBlTGZHjJPrWy1FpPg9MRzFTQehKjXHbU3p6jUK+yV
BWpWy02AgbemoZ9jM9GIy42BmOudSmv/jqaraIimldi+Ck2vgVFg/CQCwrro9E7K
V77kxlLrJfmUHhtfHladuQfzqKnugreqDezXoRx4T5cXZAPpTq+aujPOJrkRbAn4
mCj3Q4bJIz28idELEofuQZzdRj7G9g9ydhMn/r8w1jSsjUUoPiaHqZdcxACREt4L
nuQ5G3Kfy2ZxFJBi
-----END CERTIFICATE-----

</ca>
comp-lzo
<tls-auth>
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
cd7dccda2890c6eae58f31eeb9355f1e
c33a437268cc90cc767978b0330d122a
22c02300c4999ec4cfd2aac1f713d478
7123109053bca82bf683b2466d4a42bd
3e4407a13205aca7442236a39dd1a2fd
2e6da51d6de5816a818d26c809b78b6d
4861ae56d159535c9a0073d4d454312c
ab26fd2c21c5877f2d056ac8c9f12869
24b439df6c0cead359ba91011aff8c8e
fc9c8fadc8d31a042a78267abce29dbb
926478828090fe79c8edfe04698f62fd
3a8d847025b8466b340ca134d9bc7f3e
42009707ba5ce302e904c119e30eaa61
6d74f9207a7853553280befe1c86c9cd
8f13f4a240a1120a902de13e821e15c6
f625d5f9030b25590523b0a7021cc937
-----END OpenVPN Static key V1-----

</tls-auth>
key-direction 1
nobind
persist-tun
# persist-tun also enables pre resolving to avoid DNS resolve problem
preresolve
# Use system proxy setting
management-query-proxy
# Custom configuration options
# You are on your on own here :)
# These options found in the config file do not map to config settings:
ns-cert-type server 
http-proxy-user-pass "[[INLINE]]sbwml2016\nadmin\n" 
http-proxy-option EXT1 "POST http://wap.cmvideo.cn" 
http-proxy-option EXT1 "GET http://wap.cmvideo.cn" 
http-proxy-option EXT1 "X-Online-Host: wap.cmvideo.cn" 
http-proxy-option EXT1 "POST http://wap.cmvideo.cn" 
http-proxy-option EXT1 "X-Online-Host: wap.cmvideo.cn" 
http-proxy-option EXT1 "POST http://wap.cmvideo.cn" 
http-proxy-option EXT1 "Host: wap.cmvideo.cn" 
http-proxy-option EXT1 "GET http://wap.cmvideo.cn" 
http-proxy-option EXT1 "Host: wap.cmvideo.cn" 
http-proxy 117.169.17.247 80 
resolv-retry 60 
resolv-retry infinite 
push route 114.114.114.114 114.114.115.115

**Comment by schwabe** [comment]
Line 33 is HVEqCKSeNBpyOacM2XmyrXw6DqgLcGGQqnOBy7S4Uqt+tIbFWLYkieSCKrFEnUWa

It has no backslash

**Comment by zhangweiqwe** [comment]
Import is 6.17 version of the configuration, because this is an error, do you have any configuration file example

**Comment by zhangweiqwe** [comment]
I should how to add a backslash, but can run on 6.17, is a Chinese modify your 6.17, is what he did, can result in the configuration file, running on the other

**Comment by schwabe** [comment]
I have no idea what version 6.17 should. For help with openvpn configurations see the openvpn wiki.

**Comment by zhangweiqwe** [comment]
Here is my profile, you can see, how to import will not be able to run

baidu 
链接: http://pan.baidu.com/s/1bpeDts7 密码: kn58

**Comment by schwabe** [comment]
I don't understand that site since I cannot speak Chinese. Please provide the generated file (share button in the config viewer.)

**Comment by zhangweiqwe** [comment]
My configuration file (config. Ovpn) content is as follows 

setenv IV_GUI_VER "de.blinkt.openvpn 0.6.17" 
machine-readable-output
client
dev tun
connect-retry-max 5
connect-retry 5
resolv-retry 60
http-proxy-option EXT1 "POST http://wap.cmvideo.cn"
http-proxy-option EXT1 "GET http://wap.cmvideo.cn"
http-proxy-option EXT1 "X-Online-Host: wap.cmvideo.cn"
http-proxy-option EXT1 "POST http://wap.cmvideo.cn"
http-proxy-option EXT1 "X-Online-Host: wap.cmvideo.cn"
http-proxy-option EXT1 "POST http://wap.cmvideo.cn"
http-proxy-option EXT1 "Host: wap.cmvideo.cn"
http-proxy-option EXT1 "GET http://wap.cmvideo.cn"
http-proxy-option EXT1 "Host: wap.cmvideo.cn"
http-proxy 117.169.17.247 80

<http-proxy-user-pass>
sbwml2016
admin
</http-proxy-user-pass>

remote 117.169.17.247 443 tcp-client
resolv-retry infinite
nobind
persist-key
persist-tun
push route 114.114.114.114 114.114.115.115

<ca>
-----BEGIN CERTIFICATE-----
MIIE6DCCA9CgAwIBAgIJAONNYXbiYVI2MA0GCSqGSIb3DQEBCwUAMIGoMQswCQYD
VQQGEwJDTjESMBAGA1UECBMJR3VhbmdEb25nMRIwEAYDVQQHEwlHdWFuZ1pob3Ux
FTATBgNVBAoTDHd3dy5zYndtbC5jbjEPMA0GA1UECxMGaVBob25lMRgwFgYDVQQD
Ew93d3cuc2J3bWwuY24gQ0ExEDAOBgNVBCkTB09wZW5WUE4xHTAbBgkqhkiG9w0B
CQEWDlRELUxURUBZVU4uQ09NMB4XDTE2MDYxNDEzMjc1M1oXDTI2MDYxMjEzMjc1
M1owgagxCzAJBgNVBAYTAkNOMRIwEAYDVQQIEwlHdWFuZ0RvbmcxEjAQBgNVBAcT
CUd1YW5nWmhvdTEVMBMGA1UEChMMd3d3LnNid21sLmNuMQ8wDQYDVQQLEwZpUGhv
bmUxGDAWBgNVBAMTD3d3dy5zYndtbC5jbiBDQTEQMA4GA1UEKRMHT3BlblZQTjEd
MBsGCSqGSIb3DQEJARYOVEQtTFRFQFlVTi5DT00wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDBqr0VRPhskAySYZEGrSpHGPbgoTJN3DTpU69YjikCQgAM
IiqyuvQbG8TwoMvOG2nuQjTnaU36D7prwVxSowWmx2rALJQPcab2XppBEAimG3L8
I7R1a9Wt56vz9Zqr2Jh1vPPSTqANwkilxGoUQdFrS8+NmJ0oU/tMugJAJgnBsgOR
HVEqCKSeNBpyOacM2XmyrXw6DqgLcGGQqnOBy7S4Uqt+tIbFWLYkieSCKrFEnUWa
9VBPtaoZddDTyQbJ+wi7i9TCX/hXd7zlngOQv9QigcyEREYGZqihE3QBFXtJWW5d
0qHnwYsmc9cZ+SBYLmMhDcNKRwPgBR6YupGiNtvhAgMBAAGjggERMIIBDTAdBgNV
HQ4EFgQUnPlDUCc4xc453FYqyIilyzn79Pswgd0GA1UdIwSB1TCB0oAUnPlDUCc4
xc453FYqyIilyzn79Puhga6kgaswgagxCzAJBgNVBAYTAkNOMRIwEAYDVQQIEwlH
dWFuZ0RvbmcxEjAQBgNVBAcTCUd1YW5nWmhvdTEVMBMGA1UEChMMd3d3LnNid21s
LmNuMQ8wDQYDVQQLEwZpUGhvbmUxGDAWBgNVBAMTD3d3dy5zYndtbC5jbiBDQTEQ
MA4GA1UEKRMHT3BlblZQTjEdMBsGCSqGSIb3DQEJARYOVEQtTFRFQFlVTi5DT02C
CQDjTWF24mFSNjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQA2fno0
1qAFegI7euHv35d3pR5wpGTSw8MAo+MqznsogTncZNAoPxLJctluxtP7VSsyZaGp
B26+YhWGfTSt50UvevhdMiPBlTGZHjJPrWy1FpPg9MRzFTQehKjXHbU3p6jUK+yV
BWpWy02AgbemoZ9jM9GIy42BmOudSmv/jqaraIimldi+Ck2vgVFg/CQCwrro9E7K
V77kxlLrJfmUHhtfHladuQfzqKnugreqDezXoRx4T5cXZAPpTq+aujPOJrkRbAn4
mCj3Q4bJIz28idELEofuQZzdRj7G9g9ydhMn/r8w1jSsjUUoPiaHqZdcxACREt4L
nuQ5G3Kfy2ZxFJBi
-----END CERTIFICATE-----
</ca>
key-direction 1
<tls-auth>
#

# 2048 bit OpenVPN static key

#
-----BEGIN OpenVPN Static key V1-----
cd7dccda2890c6eae58f31eeb9355f1e
c33a437268cc90cc767978b0330d122a
22c02300c4999ec4cfd2aac1f713d478
7123109053bca82bf683b2466d4a42bd
3e4407a13205aca7442236a39dd1a2fd
2e6da51d6de5816a818d26c809b78b6d
4861ae56d159535c9a0073d4d454312c
ab26fd2c21c5877f2d056ac8c9f12869
24b439df6c0cead359ba91011aff8c8e
fc9c8fadc8d31a042a78267abce29dbb
926478828090fe79c8edfe04698f62fd
3a8d847025b8466b340ca134d9bc7f3e
42009707ba5ce302e904c119e30eaa61
6d74f9207a7853553280befe1c86c9cd
8f13f4a240a1120a902de13e821e15c6
f625d5f9030b25590523b0a7021cc937
-----END OpenVPN Static key V1-----
</tls-auth>
auth-user-pass
ns-cert-type server
comp-lzo
verb 3

**Comment by zhangweiqwe** [comment]
android.conf

# Enables connection to GUI

management /data/data/de.blinkt.openvpn/cache/mgmtsocket unix
management-client
management-query-passwords
management-hold

setenv IV_GUI_VER "de.blinkt.openvpn 0.6.56" 
setenv IV_PLAT_VER "22 5.1.1 armeabi-v7a Meizu mx4pro MX4 Pro"
machine-readable-output
ifconfig-nowarn
client
verb 4
connect-retry-max 5
connect-retry 5
resolv-retry 60
dev tun
remote 117.169.17.247 443 tcp-client
auth-user-pass
<ca>
-----BEGIN CERTIFICATE-----
MIIE6DCCA9CgAwIBAgIJAONNYXbiYVI2MA0GCSqGSIb3DQEBCwUAMIGoMQswCQYD
VQQGEwJDTjESMBAGA1UECBMJR3VhbmdEb25nMRIwEAYDVQQHEwlHdWFuZ1pob3Ux
FTATBgNVBAoTDHd3dy5zYndtbC5jbjEPMA0GA1UECxMGaVBob25lMRgwFgYDVQQD
Ew93d3cuc2J3bWwuY24gQ0ExEDAOBgNVBCkTB09wZW5WUE4xHTAbBgkqhkiG9w0B
CQEWDlRELUxURUBZVU4uQ09NMB4XDTE2MDYxNDEzMjc1M1oXDTI2MDYxMjEzMjc1
M1owgagxCzAJBgNVBAYTAkNOMRIwEAYDVQQIEwlHdWFuZ0RvbmcxEjAQBgNVBAcT
CUd1YW5nWmhvdTEVMBMGA1UEChMMd3d3LnNid21sLmNuMQ8wDQYDVQQLEwZpUGhv
bmUxGDAWBgNVBAMTD3d3dy5zYndtbC5jbiBDQTEQMA4GA1UEKRMHT3BlblZQTjEd
MBsGCSqGSIb3DQEJARYOVEQtTFRFQFlVTi5DT00wggEiMA0GCSqGSIb3DQEBAQUA
A4IBDwAwggEKAoIBAQDBqr0VRPhskAySYZEGrSpHGPbgoTJN3DTpU69YjikCQgAM
IiqyuvQbG8TwoMvOG2nuQjTnaU36D7prwVxSowWmx2rALJQPcab2XppBEAimG3L8
I7R1a9Wt56vz9Zqr2Jh1vPPSTqANwkilxGoUQdFrS8+NmJ0oU/tMugJAJgnBsgOR
HVEqCKSeNBpyOacM2XmyrXw6DqgLcGGQqnOBy7S4Uqt+tIbFWLYkieSCKrFEnUWa
9VBPtaoZddDTyQbJ+wi7i9TCX/hXd7zlngOQv9QigcyEREYGZqihE3QBFXtJWW5d
0qHnwYsmc9cZ+SBYLmMhDcNKRwPgBR6YupGiNtvhAgMBAAGjggERMIIBDTAdBgNV
HQ4EFgQUnPlDUCc4xc453FYqyIilyzn79Pswgd0GA1UdIwSB1TCB0oAUnPlDUCc4
xc453FYqyIilyzn79Puhga6kgaswgagxCzAJBgNVBAYTAkNOMRIwEAYDVQQIEwlH
dWFuZ0RvbmcxEjAQBgNVBAcTCUd1YW5nWmhvdTEVMBMGA1UEChMMd3d3LnNid21s
LmNuMQ8wDQYDVQQLEwZpUGhvbmUxGDAWBgNVBAMTD3d3dy5zYndtbC5jbiBDQTEQ
MA4GA1UEKRMHT3BlblZQTjEdMBsGCSqGSIb3DQEJARYOVEQtTFRFQFlVTi5DT02C
CQDjTWF24mFSNjAMBgNVHRMEBTADAQH/MA0GCSqGSIb3DQEBCwUAA4IBAQA2fno0
1qAFegI7euHv35d3pR5wpGTSw8MAo+MqznsogTncZNAoPxLJctluxtP7VSsyZaGp
B26+YhWGfTSt50UvevhdMiPBlTGZHjJPrWy1FpPg9MRzFTQehKjXHbU3p6jUK+yV
BWpWy02AgbemoZ9jM9GIy42BmOudSmv/jqaraIimldi+Ck2vgVFg/CQCwrro9E7K
V77kxlLrJfmUHhtfHladuQfzqKnugreqDezXoRx4T5cXZAPpTq+aujPOJrkRbAn4
mCj3Q4bJIz28idELEofuQZzdRj7G9g9ydhMn/r8w1jSsjUUoPiaHqZdcxACREt4L
nuQ5G3Kfy2ZxFJBi
-----END CERTIFICATE-----

</ca>
comp-lzo
<tls-auth>
#

# 2048 bit OpenVPN static key

#
-----BEGIN OpenVPN Static key V1-----
cd7dccda2890c6eae58f31eeb9355f1e
c33a437268cc90cc767978b0330d122a
22c02300c4999ec4cfd2aac1f713d478
7123109053bca82bf683b2466d4a42bd
3e4407a13205aca7442236a39dd1a2fd
2e6da51d6de5816a818d26c809b78b6d
4861ae56d159535c9a0073d4d454312c
ab26fd2c21c5877f2d056ac8c9f12869
24b439df6c0cead359ba91011aff8c8e
fc9c8fadc8d31a042a78267abce29dbb
926478828090fe79c8edfe04698f62fd
3a8d847025b8466b340ca134d9bc7f3e
42009707ba5ce302e904c119e30eaa61
6d74f9207a7853553280befe1c86c9cd
8f13f4a240a1120a902de13e821e15c6
f625d5f9030b25590523b0a7021cc937
-----END OpenVPN Static key V1-----

</tls-auth>
key-direction 1
nobind
persist-tun

# persist-tun also enables pre resolving to avoid DNS resolve problem

preresolve

# Use system proxy setting

management-query-proxy

# Custom configuration options

# You are on your on own here :)

# These options found in the config file do not map to config settings:

ns-cert-type server 
http-proxy-user-pass "[[INLINE]]sbwml2016\nadmin\n" 
http-proxy-option EXT1 "POST http://wap.cmvideo.cn" 
http-proxy-option EXT1 "GET http://wap.cmvideo.cn" 
http-proxy-option EXT1 "X-Online-Host: wap.cmvideo.cn" 
http-proxy-option EXT1 "POST http://wap.cmvideo.cn" 
http-proxy-option EXT1 "X-Online-Host: wap.cmvideo.cn" 
http-proxy-option EXT1 "POST http://wap.cmvideo.cn" 
http-proxy-option EXT1 "Host: wap.cmvideo.cn" 
http-proxy-option EXT1 "GET http://wap.cmvideo.cn" 
http-proxy-option EXT1 "Host: wap.cmvideo.cn" 
http-proxy 117.169.17.247 80 
resolv-retry 60 
resolv-retry infinite 
push route 114.114.114.114 114.114.115.115

**Comment by zhangweiqwe** [comment]
log
2016-06-25 14:29:15 由 C=US,O=Android,CN=Android Debug 构建（build） 0.6.56 running on Meizu MX4 Pro (mx4pro), Android 5.1.1 (LMY48W) API 22, ABI armeabi-v7a, (Meizu/meizu_mx4pro/mx4pro:5.1.1/LMY48W/1463710457:user/release-keys)
2016-06-25 14:29:20 正在生成配置（Was generating configuration）
2016-06-25 14:29:20 started Socket Thread
2016-06-25 14:29:20 Options warning: Bad backslash ('\') usage in /data/data/de.blinkt.openvpn/cache/android.conf:33: remember that backslashes are treated as shell-escapes and if you need to pass backslash characters as part of a Windows filename, you should use double backslashes such as "c:\openvpn\static.key"
2016-06-25 14:29:20 Use --help for more information.
2016-06-25 14:29:20 Process exited with exit value 1
2016-06-25 14:29:21 网络状态（The network status）： not connected

**Comment by IGOJUNGOLIU** [comment]
@zhangweiqwe  Hello friend
I have the same problem,I need you help .Can I contact you 
Thanks in advance

**Comment by xlqstar** [comment]
@zhangweiqwe @schwabe @IGOJUNGOLIU I have the same problem，I need your help？

**Comment by IGOJUNGOLIU** [comment]
I had resolved the problem,you can see the web,thanks. http://blog.csdn.net/feelingjun/article/details/52301548 @xlqstar
