### ISSUE TITLE
Cannot find .git directory in openvpn, aborting

### ISSUE THREAD

**Issue by giorizzotti** [schwabe/ics-openvpn#509]
Hello, I'm trying to compile your source on OS X and I did the following:
- git clone https://github.com/schwabe/ics-openvpn.git
- cd ics-openvpn
- Edited the submodule url, from SSH to HTTPS
- git submodule init
- git submodule update
- ./main/misc/build-native.sh

The git submodule was fetched, but when I executed the last command, I obtained the following error: "Cannot find .git directory in openvpn, aborting".

Thank you in advance.

**Comment by zhangweiqwe** [comment]
you can exec: git init

**Comment by zhangweiqwe** [comment]
or:  git colone https://github.com/schwabe/ics-openvpn.git

**Comment by zhangweiqwe** [comment]
cd mian
./misc/build-native.sh

**Comment by schwabe** [comment]
The readme states to execute the script in the main directory

**Comment by IGOJUNGOLIU** [comment]
I had the same problem,I do not know how to deal with the issue.Have you deal with it?
