### ISSUE TITLE
need a configuration files

### ISSUE THREAD

**Issue by zhangweiqwe** [schwabe/ics-openvpn#511]
Schwabe we now this is the night, I guess you that is the day, I need is a 0.6.56 configuration file, you can send a link to you, because I can't import the configuration file, I need a example

**Comment by schwabe** [comment]
OpenVPN for Android should work with all valid OpenVPN files. If it does not, please send me the non. working none. BUt since you insist, take the example config files: https://github.com/OpenVPN/openvpn/tree/master/sample/sample-config-files

**Comment by zhangweiqwe** [comment]
But which one should I under

**Comment by schwabe** [comment]
The configuration should match your server.

**Comment by zhangweiqwe** [comment]
But I tried, the other one is called (openvpn connection) software, the import is the same configuration file, there is no problem, enter the password after the connection is successful

**Comment by zhangweiqwe** [comment]
I'll take a few laps, exercise the body, I hope you help me to solve the problem, I also sent before the configuration file, in the post.

**Comment by zhangweiqwe** [comment]
![Uploading S60625-222812.jpg…]()
![Uploading S60625-223207.jpg…]()
![Uploading S60625-223238.jpg…]()
![Uploading S60625-223241.jpg…]()

**Comment by zhangweiqwe** [comment]
I have some screenshots, but I don't know how to send you, English is not good is not good

**Comment by schwabe** [comment]
The config file using the http-proxy-password option which OpenVPN does not yet support. It will be included in future versions but currently it is not supported.

**Comment by zhangweiqwe** [comment]
How long the support, by the way do you know the web site of the android open source project, for example (openvpn connection) of the source code, like (openvpn connection) is not open source, to tell the truth you of this project is quite good.

**Comment by zhangweiqwe** [comment]
I will remove 

<http-proxy-user-pass>
sbwml2016
admin
</http-proxy-user-pass>

The server password is set to null

**Comment by zhangweiqwe** [comment]
I will remove 
`<http-proxy-user-pass>
sbwml2016
admin
</http-proxy-user-pass>`
and
The server password is set to null

**Comment by zhangweiqwe** [comment]
but still error
2016-06-26 13:54:52 由 C=US,O=Android,CN=Android Debug 构建 0.6.56 running on Meizu MX4 Pro (mx4pro), Android 5.1.1 (LMY48W) API 22, ABI armeabi-v7a, (Meizu/meizu_mx4pro/mx4pro:5.1.1/LMY48W/1463710457:user/release-keys)
2016-06-26 13:54:52 正在生成配置
2016-06-26 13:54:52 started Socket Thread
2016-06-26 13:54:52 Options error: Unrecognized option or missing or extra parameter(s) in /data/data/de.blinkt.openvpn/cache/android.conf:45: push (2.4_master)
2016-06-26 13:54:52 Use --help for more information.
2016-06-26 13:54:52 Process exited with exit value 1

**Comment by zhangweiqwe** [comment]
I did this, remove `<http-proxy-user-pass> sbwml2016 admin </http-proxy-user-pass>` directly ，And the server password is set to null

**Comment by zhangweiqwe** [comment]
Can you give me a string form of the configuration file (XXXXX. Ovpn), the last time you hair I don't know which one

**Comment by schwabe** [comment]
push is also invalid in the client configuration. The configuration file has to match your server. A random configuration will not work.

**Comment by zhangweiqwe** [comment]
What should I do, how long will support password function

**Comment by schwabe** [comment]
http proxy password are already support, just not embedded in the config file. I don't have time at the moment to look into it. But a patch for http-proxy-password is on the mailing and you can patch openvpn yourself to support it.

**Comment by zhangweiqwe** [comment]
So, you give me a configuration file (XXX) ovpn), or a string, I try to modify in your configuration file

**Comment by schwabe** [comment]
I already did. Every one of the client files of the sample is fine for the client.

**Comment by zhangweiqwe** [comment]
ok
