### ISSUE TITLE
Cannot find .git directory in openvpn, aborting

### ISSUE THREAD

**Issue by IGOJUNGOLIU** [schwabe/ics-openvpn#512]
To make issues more managable, I would appriciate if you fill out the details if applicable
# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
# Description of the issue

I want to compile project  on android studio,but I can not do it well.I do not know how to deal with it now.I read the doc/readme.txt for so many times,it seems to hard to understand for me .When i do:./misc/build-native.sh. It prompts:Cannot find .git directory in openvpn,aborting.This project I have worked for three months has not compiled,I need help or guide me what to do.
Thanks.

**Comment by schwabe** [comment]
Please see the other closed bugs with eaxtly the same problem

**Comment by zoopolitic** [comment]
For everyone struggling with this problem. Do exactly what readme says. I've spent an hour trying to fix this problem, I've inited and updated submodules and was trying to execute ./build-native.ssh manually and was getting this error. Then I've executed "cd main;./misc/build-native.sh" and it worked.
