### ISSUE TITLE
[two questions] 1) "manually" reproducing excluded routes by using a .sh script ? 2) excluding root (uid 0) traffic from going over the VPN ?

### ISSUE THREAD

**Issue by tonsimple** [schwabe/ics-openvpn#514]
# General information
1. Android Version
5.0
2. Android Vendor/Custom ROM
Sicmosh AOSP for Xiaomi Redmi Note 3
ROOTED.
3. Device
Xiaomi Redmi Note 3
4. Version of the app (version number/play store version/self built)
 play store most recent
# Description of the issue

There is no issue with the app per se. I am trying to figure out how to tunnel OpenVPN over Shadowsocks in android and have a few questions.

Shadowsocks server IP is, let's say. 107.183.14.53

ss-local client is started from a .sh script as Root by automagic4android and listens on port 2090

socks-proxy for connection set to 127.0.0.1:2090

excluded routes for connection is set to 107.183.14.53/32

Surprisingly, the VPN connection works (as long as UDP is used)

However, due to to shadowsocks IP occasionally changing, I'd like to be able to change the "excluded route" on the fly (There's a way for me to learn what the new IP will be from a .sh script)

It works fine for me on desktop , but on android that involves manually shutting down VPN connection, changing the excluded network and then re-connecting

So,  
1)

I'd like to be able to change the excluded route manually.
I don't know all that much about android's vpnservice, but as far as my googling seems to suggest, it relies heavily on policy routing.

My device is rooted, so I should be able to do
ip rule add [something]

However, so far, I'm not able to figure out what exactly should I add to "manually" replicate the effect of exluded route being set from the app (and if that is even possible :-( )

2)
I'd also like to make all traffic belonging to root user excluded from VPN and routed over naked connection (analogously to how one could set an app to be excluded from VPN)

Specific usecase - sending DNSCrypt's traffic over vanilla connection while everything else is sent over the VPN

**Comment by schwabe** [comment]
yes, VPNService relies heavily on policy routing. Root may be excluded from the VPN if you add the system services (or similar) as excluded app. I would probably start by only allowing one app like Chrome and see if that works and then gradually change to the desired config. Adding your own policy routes may work but it is going to be challenging to understand the routes.

IIrc you can also set a dns name instead of a ip to be excluded from the VPN. (Use route in custom settings if the ui does not like hostnames)

OpenVPN for Android has special remote API to exclude a socket from the VPNService but teaching DNSCrypt to use it without wrapping it into an app is probably not that easy.

**Comment by tonsimple** [comment]
Hi!
System Services run as UID 1000 and thus root doesn't end up excluded when I exclude them

I have managed to exclude Root on another VPN solution by manually adding UID 0 to its config in its respective folder in /data/data

However, as far as I can tell from reading stuff in OpenVPN's data folder, it references apps to exclude by their package name (com.google.foo etc.) which makes excluding root tricky (excluding SuperSu does not cut it, as it isn't really registered as UID0 I assume)
Any ideas as to how to trick it into excluding root? (I have an alternate approach for DNSCrypt if this fails, it basically amounts to "add every single DNSCrypt server IP as excluded route, but that's kinda ugly)

As to using DNS names in exclusion routes instead of IPs... Would the route proper be "fixed" at VPN startup and maintained till restart, or updated dynamically?

Which is to say, if I add foobar.com to excluded list, will OpenVPN resolve foobar.com every single time packets might be sent there _(and thus respond to change of foobar.com's IP as soon as DNS server gets updated)_ or will OpenVPN require a restart to accommodate those changes?

**Comment by schwabe** [comment]
The route will be fixed and not updated dymanically.

**Comment by tonsimple** [comment]
Thanks!
