### ISSUE TITLE
I found in the two paragraphs, will go wrong 

### ISSUE THREAD

**Issue by zhangweiqwe** [schwabe/ics-openvpn#515]
android phone config(xxxxx.ovpn)

`<http-proxy-user-pass>`
`admin`
`xxxxxx`
`</http-proxy-user-pass>`

and

`key-direction 1`
`<tls-auth>`
`#`
`# 2048 bit OpenVPN static key`
`#`
`-----BEGIN OpenVPN Static key V1-----`

`-----END OpenVPN Static key V1-----`
`</tls-auth>`

Why is this? This configuration file can be used in other software

**Comment by schwabe** [comment]
OpenVPN does not yet support http-proxy-user-pass as OpenVPN does, as I already explained to you. Support will come eventually but annoying me and asking for it over and over again, will rather make delay import a new OpenVPN version than acclerating it. Your spamming of the issue tracker is really annoying.
