### ISSUE TITLE
[question] avoiding connection teardown on network type change / 3G-2G handover / other disruption

### ISSUE THREAD

**Issue by tonsimple** [schwabe/ics-openvpn#516]
# General information
1. Android Version
5.0
2. Android Vendor/Custom ROM
Sicmosh AOSP for Xiaomi Redmi Note 3
ROOTED.
3. Device
Xiaomi Redmi Note 3
4. Version of the app (version number/play store version/self built)
 play store most recent
# Description of the issue

This isn't an issue per se, just one more question, but sufficiently different that it's worth its own issue IMHO

When tunneling OpenVPN over Shadowsocks on desktop, the connection easily survives home network IP change (ISP forcibly changes IP every 48 hours) and connection disruption (simulated by pulling out the wifi router's WAN cable, then re-connecting ).
By "survives" I mean "no new openVPN connection has to be established (according both to observed behavior/apparent IP and logs).

I suspect that's due to the fact that even in case of IP change, the Shadowsock's IP address remains the same so "nothing changes" for the VPN server.

Is there a way to reproduce this behavior on Android, or is observed desktop behavior some lucky fluke and I'd have to wait till OpenVPN 2.4 and it's _"peer-id"_ thing for this to happen on Android ?

Rationale:
On poor 2G/3G connections IP changes often, and re-establishing OpenVPN connection can take a lot of time / multiple retries.

If re-re-re-establishing a connection can be avoided by tunneling it over Shadowsocks (which seems to happen "out of the box" for me on desktop) that would be great.

P.S.:
StrongSwan based android VPNs survive connection teardowns and even going from Wifi to 3G to 2G and back almost completely seamlessly (thanks to MOBIKE, I presume), so android's vpnservice does not seem to limit such behavior "in principle"

**Comment by schwabe** [comment]
It is already implemented and yes it needs the master branch (what is becoming 2.4) on the server, too. OpenVPN for Android has always been following the master branch.

**Comment by tonsimple** [comment]
That's great! 

Does it negotiate this automatically if server capability is present, or do I need to have some option specified in my  VPN config on the android device to make peer-id / userside "float" work ?

I suppose I'd have to disable "reconnect on network change" option ... anything else worth putting in config (or selecting in options) on the android side ?

**Comment by schwabe** [comment]
No it is automatically dected. And even with peer-id you need reconnect on network change, since the client needs to rebind the socket to the new interface.

**Comment by tonsimple** [comment]
@schwabe 

> And even with peer-id you need reconnect on network change, since the client needs to rebind the socket to the new interface.

Well, I guess if that only happens on things like wifi/mobile transition and not 2G/3G transitions I should be mostly fine....

BTW, if I may ask, how do other VPN apps (strongswan based Hideme, Shadowsocks-android's own tun2socks based android VPN implementation) manage to go from wifi to mobile with no appreciable delay (SS) or very little delay (hideme/strongswan)?
What's their "catch" so to say ?

**Comment by schwabe** [comment]
I have not looked but probably something very similar to the peer id in OpenVPN 2.4. Some session id embeded in the packets.

**Comment by tonsimple** [comment]
@schwabe 

So with peer-id on, when going from wifi to 3G and back, I could still expect a speedup in reconnection speed? Would be very good :)

**Comment by schwabe** [comment]
Yes. Currently it breaks if you switch protocol families (i.e. going from a Ipv6 network to a ipv4 network) but otherwise the other just recognizes the packet with the new IP as packets of the old connection and will just update its peer IP.
