### ISSUE TITLE
FR: please implement --x509-username-field, at least --x509-username-field ext:subjectAltName

### ISSUE THREAD

**Issue by beelze** [schwabe/ics-openvpn#519]
When I trying to connect to host («cert hostname check» is on) whose name is not Subject CN but listed in Subject Alt Name, I got an expected error. To allow connection I need to manually put hostname to «Remote cert subject» in options. 
To avoid this and to complete «hostname check» functionality, we need an option for --x509-username-field, at least toggle for --x509-username-field ext:subjectAltName.

**Comment by schwabe** [comment]
You can always have these options as custom options. OpenVPN for Android just does not support specyifing with a nice UI textfiled.

**Comment by beelze** [comment]
Of course, I can. The question is different – we have an UI option for --verify-x509-name (nice combo/text), but no UI for --x509-username-field, which is very closely related to --verify-x509-name, so «cert hostname check» is implemented _partially_. It is something like to be able to copy file in file manager but not be able to chmod it ibid.

**Comment by ssten** [comment]
For now setting hostname in CommonName certificate field is going obsolete.
So, application should provide interface to X509v3 Subject Alternative Name not only in CLI, but also in GUI.
