### ISSUE TITLE
The version number (openvpn) minimum support 

### ISSUE THREAD

**Issue by zhangweiqwe** [schwabe/ics-openvpn#521]
Default is (21), I can down? Will there be wrong, after all, 70% of China use (19)

**Comment by schwabe** [comment]
I have no idea what you are talking about.

**Comment by zhangweiqwe** [comment]
Whether to support (android 4.4)

**Comment by schwabe** [comment]
Everything > 4.0 is supported

**Comment by zhangweiqwe** [comment]
ok thank you

**Comment by xDragonZ** [comment]
You are so annoying, please use search engine next time
