### ISSUE TITLE
config-version.h no exist

### ISSUE THREAD

**Issue by songlongkuan** [schwabe/ics-openvpn#522]
Compile JNI Error :

 openvpn//src/openvpn/options.c:37:28: fatal error: config-version.h: No su
e or directory
 #include "config-version.h"
                            ^
compilation terminated.
make: **\* [obj/local/arm64-v8a/objs/openvpn/src/openvpn/options.o] Error 1

How to do it?

**Comment by schwabe** [comment]
You are not following the steps of the README.
