### ISSUE TITLE
./misc/build-native.sh error

### ISSUE THREAD

**Issue by 298068845** [schwabe/ics-openvpn#523]
<command-line>:0:12: error: expected ',' or ';' berfore 'android'
openvpn/android-config/config.h:493:22: note; in expansion of macro 'TARGET_ABI'
# define TARGET_ALIAS TARGET_ABI

```
                                ^
```

openvpn//src/openvpn/options.c:69:7: note: in expansion of macro 'TARGET_ALIAS'
 " " TARGET_ALIAS
     ^
make.exe:**_[obj/local.arm64-v8a/objs/openvpn/src/openvpn/options.o] Error 1
make.exe:**_ Waitting for unfinished jobs....

i have been try build it in ubuntu and window,but it show me the same error

**Comment by schwabe** [comment]
Building under windows does not work. Building unter Ubuntu works if you use the method that is described in the README

**Comment by 298068845** [comment]
i read the readme ,every step i done but  ignore the "svn co http://google-breakpad.googlecode.com/svn/trunk/ google-breakpad",what should i do when i get the google-breakpad?

**Comment by 298068845** [comment]
i don't know what is 'call build-native.sh with USE_BREAKPAD=0 ',how to do that??

**Comment by 298068845** [comment]
http://google-breakpad.googlecode.com/svn/trunk this address is 404,i can't check out...

**Comment by schwabe** [comment]
Your problem has nothing to with breakpad.

**Comment by 298068845** [comment]
I install sdk and ndk, ndk-build is in my build path,clone this project,git submodule init and git submodule update suceed.
cd  main ./misc/build-native.sh ,my error will be showed after compile the platform.c ,and then complile the plugin.c is the end...i have try so many times..

**Comment by schwabe** [comment]
Pasting a complete build log would be a first step.

**Comment by 298068845** [comment]
[log.txt](https://github.com/schwabe/ics-openvpn/files/375028/log.txt)

**Comment by schwabe** [comment]
Sorry no idea what goes there.

**Comment by IGOJUNGOLIU** [comment]
hello friend
Can you tell me how you execute to this step in detail?You can send the process to my email.Thank.

**Comment by schwabe** [comment]
It is already in the README. No need to send it via email

**Comment by 298068845** [comment]
I think my problem is .mk can't ignore the TARGET_ABI,but my ubuntu has been installed GNU MAKE
