### ISSUE TITLE
Connection does not resume on reboot

### ISSUE THREAD

**Issue by RoxKilly** [schwabe/ics-openvpn#525]
All versions since about `0.6.51`
Android `5.1` and `5.1.1`

The behavior used to be that if there were an active connection on shutdown, the VPN would be reestablished on reboot.  The latest version where I know this to be working is `0.6.47`.  For the last few versions, the app no longer reconnects on reboot.

**Comment by schwabe** [comment]
Yeah, I noticed that too. The last version changes this to an uncodinal connect on boot with a selected profile since the older approach was either too fragile (and/or) not well enough understood by users. Can you try with the latest version again?

**Comment by RoxKilly** [comment]
today I updated for the first time in a while because I noticed the `lots of bug fixes` notes on the Play Store.  I had stopped updating at `0.6.47` because of this issue (was worried about forgetting to turn VPN on after reboot).  Anyway I came here after noticing that the problem still occurs for me.
1.  Open the app and connect. Confirm `Connected: SUCCESS` message
2. Go to `ipaddress.com` for good measure and confirm that public IP is VPN exit node
3.  Without disconnecting, fully power off the device.
4.  Power on the device. With `0.6.47` (on another device), I get notification of VPN on. Not with `0.6.57`
5.  Open the app.  No live connection on first screen; Vpn status `Not running` on log screen.

App version: `0.6.57`
Device: Nexus 7 (2013) running Android `5.1.1` (build `LMY48l`)

**Comment by schwabe** [comment]
Did you go into the setting and set a VPN that should be used on boot?

**Comment by RoxKilly** [comment]
Didn't know there was such a setting. Don't remember doing it for `0.6.47`.  Are we talking Android OS settings or app settings?

**Comment by schwabe** [comment]
App settings. As I said, the logic was replaced in latest version (also to accomandate Android N's Always ON VPN)

**Comment by RoxKilly** [comment]
Ok I've enabled `VPN used on boot for Always-On` and `Connect on boot`. I can see that an attempt to connect is made. Typically when I connect the last couple of lines in the log are:
- Peer Connection initiated with...
- do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
- Initialization Sequence Completed

On reboot, the connection seems to be established briefly (I see some quick notifications and the `key` icon in the notification bar lights up for less than 1 second. When I open the app the log shows connection attempt, and the last couple of lines are:
- Same lines as above, then...
- Sorry, deleting routes on Android is not possible. The VpnServie API allows routes to be set on connect only.
- (last line repeats)
- SIGNING[hard,] received, process exiting

The entire log happens within the same second

**Comment by schwabe** [comment]
Can you share the whole of connect on boot. I guess there is a reason that the connection is terminated in there

**Comment by RoxKilly** [comment]
- OpenVPN 2.4-icsopenvpn [git:...] android-14-armeabi-v7a [SS (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH] [IPv6] built on Jul 6 2016
- library versions: OpenSSL 1.0.2h 3 May 2016, LZO 2.09
- TCP/UDP: Preserving recently used remote address: [AF_INET] {{ip_address}}:{{port}}
- UDP link local: (not bound)
- UDP link remote: [AF_INET] {{ip_address}}:{{port}}
- WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
- [4d26bde...] Peer Connection initiated with [AF_INET] {{ip_address}}:{{port}}
- do_ifconfig, tt->ipv6=0, tt->did_ifconfig_ipv6_setup=0
- Initialization Sequence Completed
- Sorry, deleting routes on Android is not possible. The VpnServie API allows routes to be set on connect only.
- Sorry, deleting routes on Android is not possible. The VpnServie API allows routes to be set on connect only. (yes, again)
- SIGNING[hard,] received, process exiting

**Comment by schwabe** [comment]
@RoxKilly mind sharing the full log (with the share option in the log screen)? You can also share privately per email if you want but the log with the reduced verbosity does not help me do see why OpenVPN is shutting down (you can increase the verbosity with the silder in the log window, the exported log is always full verbosity)

**Comment by RoxKilly** [comment]
This is going to sound stupid but: none of my share options actually work.  If you know where the file is stored on disk, in the future I can use a file explorer to get it.

Good news is that your tip about verbosity got me somewhere. Once I turned it up, one of the messages I saw was:
- VPN permission revoked by OS (e.g. other VPN program started), stopping VPN

I in fact have another app that uses the VPN Api (`Netguard`, which we discussed in #418 ).  It's set to start on boot, but it doesn't actually connect (otherwise I'd have the key icon in notifications). I guess just launching it is enough for the OS to revoke VPN permission.  Anyway, once I set `Netguard` to no longer start on boot, the VPN connection worked like a charm.

**Comment by schwabe** [comment]
I had the same Problem with NetGuard. I think NetGuard starts its Service which then does nothing and quits. But starting that service is enough to signal Android that this app wants to use the VPN API now. There nothing OpenVPN for Android can do about that. I will increase the log level of that revoke message though.

**Comment by RoxKilly** [comment]
Good idea.  Want to take the opportunity to thank you for making the app more remote friendly over the last year.  I know we're always pulling at you to do this or that, but since I first complained about it, it has gotten a lot easier to use on my media box.

Feel free to close the issue.
