### ISSUE TITLE
未在 .gitmodules 中发现路径 'main/openssl/platform_external_openssl' 的子模组映射

### ISSUE THREAD

**Issue by IGOJUNGOLIU** [schwabe/ics-openvpn#528]
To make issues more managable, I would appriciate if you fill out the details if applicable
# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
# Description of the issue

Hi friend
I have my own github ssh key from the https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

Now I execute the following instructions:git submudule init.
The result like this:未在 .gitmodules 中发现路径 'main/openssl/platform_external_openssl' 的子模组映射
I don`t know how to do now .Can you tell the reason or tell me where something is wrong?

Thank in advance

**Comment by schwabe** [comment]
Sorry, I cannot read chinese error messages nor am I willing to explain git in this issue tracker.
