### ISSUE TITLE
submodule: openvpn b89b098fc66488b921729cf7e83016962ccd9d2e

### ISSUE THREAD

**Issue by xcolwell** [schwabe/ics-openvpn#529]
Hi,

I'm trying to build the latest. Looks like I need an openvpn version that supports two args `connect-retry a b`. The `openvpn` submodule points to b89b098fc66488b921729cf7e83016962ccd9d2e but this is not in the branch. I see it in the repo but I'm not able to check out the submodule at that commit using `git submodule init; git submodule update`. The output is

```
fatal: reference is not a tree: b89b098fc66488b921729cf7e83016962ccd9d2e
Unable to checkout 'b89b098fc66488b921729cf7e83016962ccd9d2e' in submodule path 'openvpn'
```

I think it could just be an issue with pushing a branch to `openvpn`.

Thanks for considering. Really awesome project.

Brien

**Comment by schwabe** [comment]
> Hi,
> 
> I'm trying to build the latest. Looks like I need an openvpn version
> that supports two args |connect-retry a b|. The |openvpn| submodule
> points to b89b098fc66488b921729cf7e83016962ccd9d2e but this is not in
> the branch. I see it in the repo but I'm not able to check out the
> submodule at that commit using |git submodule init; git submodule
> update|. The output is
> 
> |fatal: reference is not a tree:
> b89b098fc66488b921729cf7e83016962ccd9d2e Unable to checkout
> 'b89b098fc66488b921729cf7e83016962ccd9d2e' in submodule path 'openvpn' |
> 
> I think it could just be an issue with pushing a branch to |openvpn|.
> 
> Thanks for considering. Really awesome project.

Yepp I think I forgot to push the tags:

[14:03]arne@pluto:...nvpn/main/openvpn% git tag --contain
b89b098fc66488b921729cf7e83016962ccd9d2e
icsopenvpn_657
[14:04]arne@pluto:...nvpn/main/openvpn% git push --tags
Counting objects: 49, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (49/49), done.
Writing objects: 100% (49/49), 8.06 KiB | 0 bytes/s, done.
Total 49 (delta 42), reused 0 (delta 0)
To git@github.com:schwabe/openvpn.git
- [new tag]         icsopenvpn_657 -> icsopenvpn_657

**Comment by TrueBers** [comment]
Hi!
Same here, at openvpn @ 3009f02
Thanks in advance!
