### ISSUE TITLE
Error importing the Profile

### ISSUE THREAD

**Issue by wahoonie76** [schwabe/ics-openvpn#532]
To make issues more managable, I would appriciate if you fill out the details if applicable
# General information
1. Android Version: 5.1.1
2. Android Vendor/Custom ROM: Stock, rooted
3. Device: Nexus 4
4. Version of the app (version number/play store version/self built): 0.6.57 from play store)
# Description of the issue

Hello,

I set up my own OpenVPN Server at home and generate the keys and certs - I think - correctly.

Merged all nesessary client-files into one profile (ovpn) an imported it in OpenVPN App an my phone, tried to connect, but exited with this "log":

> 2016-07-28 14:05:54 offizielle Version 0.6.57 läuft auf google Nexus 4 (MAKO), Android 5.1.1 (LMY48T) API 22, ABI armeabi-v7a, (google/occam/mako:5.1.1/LMY48T/2237560:user/release-keys)
> 2016-07-28 14:05:54 Generiere OpenVPN-Konfiguration…
> 2016-07-28 14:05:54 started Socket Thread
> 2016-07-28 14:05:54 P:WARNING: linker: /data/data/de.blinkt.openvpn/cache/pie_openvpn.armeabi-v7a: unused DT entry: type 0x6ffffffe arg 0x2ac
> 2016-07-28 14:05:54 P:WARNING: linker: /data/data/de.blinkt.openvpn/cache/pie_openvpn.armeabi-v7a: unused DT entry: type 0x6fffffff arg 0x1
> 2016-07-28 14:05:54 P:WARNING: linker: libopenvpn.so: unused DT entry: type 0x6ffffffe arg 0x364d0 ni
> 2016-07-28 14:05:54 P:WARNING: linker: libopenvpn.so: unused DT entry: type 0x6fffffff arg 0x2
> 2016-07-28 14:05:54 Options error: In /data/data/de.blinkt.openvpn/cache/android.conf:34: Maximum optione line length (256) exceeded, line starts with ta "[[INLINE]]#\n# 2048 bit OpenVPN static key\n#\n-----BEGIN OpenVPN Static key V1-----
> .
> .
> .
> 2016-07-28 14:05:54 Use --help for more information.
> 2016-07-28 14:05:54 Process exited with exit value 1

What did wrong?

**Comment by schwabe** [comment]
Probably something wrong with the imported config. Can you send me a copy of that? There seems something wrong near your ta option (which openvpn does not have).

**Comment by wahoonie76** [comment]
Hello, 

sorry for my question (I'new to github): is there a PN-function or should I post my config file here? (Only because of keeping my keys secret....)

Greets

**Comment by schwabe** [comment]
I don't think Github has a privet message functionality. You can send me the config via email

**Comment by wahoonie76** [comment]
Hello,

thanks for your quick reply.

I attached my config file (the Numbers ans letters from certs and keys I have overwritten in Notepad++). I renamed it as txt.

Greetings

Mathias Hartwig
[NexusWahoonie(XXX).ovpn.txt](https://github.com/schwabe/ics-openvpn/files/388855/NexusWahoonie.XXX.ovpn.txt)

**Comment by schwabe** [comment]
The `<ta>` option is just wrong. OpenVPN has tls-auth but not ta

**Comment by wahoonie76** [comment]
Thank you for your help!
