### ISSUE TITLE
Feature Request: Proxy Front Inject

### ISSUE THREAD

**Issue by R4to0** [schwabe/ics-openvpn#533]
Currently we can send host header and such over a proxy connection after "CONNECT" payload. It works nice as well!

But what if we can send something to proxy server before CONNECT? Like 'POST http://localdomain.hotspot/restricted.asp' or GET/HEAD/TRACE and such, so we can bypass some hotspot network restrictions (or even ISPs?).

Something like 'http-proxy-option EXT1 POST http://localdomain.hotspot/restricted.asp HTTP/1.1' to send before CONNECT.

Thanks in advance, and thank you for making this app!

-Rafael.

**Comment by schwabe** [comment]
I have no interesent in these hacks. If you write a patch for the upstream openvpn and/or explain on openvpn-devel why this patch is needed, that is fine but I won't implement something in ics-openvpn that has chance of getting to upstream.

**Comment by R4to0** [comment]
No problem, I know that would open a hole for carrier bypassers unfortunately. Sorry for bothering you about this.

-Rafael.
