### ISSUE TITLE
CANNOT LINK EXECUTABLE

### ISSUE THREAD

**Issue by 298068845** [schwabe/ics-openvpn#534]
I use the "userName and Password" mode to connect and show me this log.
i copy log from logfragment:
Log (no context) resid 2131231107Coolpad 5892|MSM8226|Coolpad|18|armeabi-v7a|4.3|JLS36C|Coolpad/Coolpad5892/Coolpad5892:4.3/JLS36C/4.3.089.P2.160115.5892:user/release-keys||
Log (no context) resid 2131230731
started Socket Thread
P:CANNOT LINK EXECUTABLE: could not load library "libopenvpn.so" needed by "/data/data/de.blinkt.openvpn/cache/pie_openvpn.armeabi-v7a"; caused by cannot locate symbol "srandom" referenced by "libopenvpn.so"...
Process exited with exit value 1

**Comment by 298068845** [comment]
I have the same problem as #288,but i still don't know how to resolve it

**Comment by schwabe** [comment]
You are probably using a terrible old NDK.

**Comment by 298068845** [comment]
I am using NDK64bit-r10b

**Comment by schwabe** [comment]
You are using a terrible old NDK
