### ISSUE TITLE
Static config without files

### ISSUE THREAD

**Issue by harishvishwakarma** [schwabe/ics-openvpn#535]
Hi Schwabe,
I have just one set of configuration for ovpn and need to use just 3 files all the time, ovpn, ca and key. Is there a way I could directly embed those files in the project and not use the file selection screen?

Thanks

**Comment by schwabe** [comment]
Please see the first FAQ here:

https://github.com/schwabe/ics-openvpn/blob/master/doc/README.txt

**Comment by harishvishwakarma** [comment]
Okay schwabe. I respect you reservations. :) I will try to find out myself. This is a good resource btw!
