### ISSUE TITLE
"exit value 11" error on connection

### ISSUE THREAD

**Issue by Timvrakas** [schwabe/ics-openvpn#536]
Tested OS's
Android 6.0.1 (Nexus and CM)
(i will add more as I test more)
Devices: GalaxyS5 and Nexus 6P (will add more)
App Version: 0.6.57 Play Store (note: at one point everything was working with this configuration)

Info: Client fails to connect, throws exit code 11 (what is this?). The same server and ovpn config works on desktop client, Linux, and "OpenVPN Connect". So I can only assume its an app issue. It was working fine at the start of June 2016, but now is not. See log: [pastebin](http://pastebin.com/TRTmDLga)

Is this my config? What can I do?

Thanks
Tim

~~EDIT~~ 
Did more testing, and the issue appears with v0.6.56 (from the apk downloads). So one of thoes june 16 commits you made for android N must be have broken something. Great App by the way!

**Comment by R4to0** [comment]
I'm getting this aswell, when using 'cipher none' right after 'OPTIONS IMPORT --ip-win32 and/or --dhcp-option options modified' process exited with exit value 11.

Setting back to some cipher (eg. AES) works as expected.

0.6.57 PS on Moto X 2014 Android 6.0 Stock

**Comment by schwabe** [comment]
Hi, could you run this version and send me the crashdump?

http://plai.de/android/ics-openvpn-0.6.57-breakpad.apk

**Comment by R4to0** [comment]
It says "App is not installed" when installing your APK. I uninstalled previous versions aswell, reboot phone but didn't work.

If this is for OP, sorry :(

**Comment by Timvrakas** [comment]
Same on my device (I am on 6.0.1 not 7)

It will not install but I assumed it was an issue on my end.

**Comment by schwabe** [comment]
@R4to0, @Timvrakas The first version was arm64 only. Can you try again? I updated that apk to include the other archs aswell.

**Comment by Timvrakas** [comment]
Yep that works for me. Here is a log. There is some warning "7:33 PM GDG:
SIOCGIFHWADDR(lo) failed" but I assume that is not important.

Thanks for all the help!

**Comment by R4to0** [comment]
Yeah that works now, thank you!

Here is full log in any case you need it: https://gist.github.com/R4to0/6b4eeac817355ba11344edc5a39cd324
