### ISSUE TITLE
Feature Suggestion: Add App Password for Parental Control Puposes

### ISSUE THREAD

**Issue by Ozzy555** [schwabe/ics-openvpn#537]
Awesome app. Works great with the OpenDNS server I set up on my new ASUS router. 

I am not programmer and don't know much about such projects... so I hope the suggestion makes sense...

I set up the client to auto start, auto connect, and work for both mobile data and wifi. I set it up on my teenagers' phones so they are always going through my home router, which has a "family control" DNS server (OpenDNS) and logging capabilities.  Works great. What is missing to make this a viable solution is an app password that would prevent opening the app (to stop connection or change settings) and to prevent uninstall. 

I have been testing parental control apps for weeks... most don't work well, are to heavy, and/or are too invasive to the kids' privacy.  A safer router (to prevent accidental access to inappropriate websites and a good talk (periodically) is all I would like todo and most parents should do, I believe. The is no bullet prof software solution. The above feature would bring a new OpenVPN for Android a whole new user base. The app already supports everything else (force data through vpn, auto start, works for wifi and mobile data, etc., and even works when I switch to the router's internal wifi network (all other openvpn apps don't do work when I connect to the router's wifi that is serving the VPN). 

Love the app either way and I am curious about your comments.

**Comment by schwabe** [comment]
That is nothing that the app can really do about unsintalling. And app password give a false sense of security that I don't want to give and implement, sorry.
