### ISSUE TITLE
Connection w/o certificate 

### ISSUE THREAD

**Issue by zoopolitic** [schwabe/ics-openvpn#538]
# General information
1. 6.0.1
2. Google
3. Nexus 5
4. 0.6.57
# Description of the issue

I'm trying to connect using just username/password w/o certificate and always getting error:
"Options error: Unrecognized option or missing extra parameter(s) in /data/user/0/de.blinkt.openvpn/cache/android.conf:18: ca (2.4_master"

So the question is: can I connect with only username/password ?

**Comment by schwabe** [comment]
OpenVPN does not support connecting without CA certificate as TLS without it would inherently insecure.

**Comment by zoopolitic** [comment]
Thanks for quick reply. How can I obtain CA certificate ?

**Comment by schwabe** [comment]
Just google for a guides how to setup a OpenVPN server. They include the necessary information.

**Comment by zoopolitic** [comment]
thank you
