### ISSUE TITLE
Feature Request: Pin/Fingerprint lock app/certain connections

### ISSUE THREAD

**Issue by CaptInsano** [schwabe/ics-openvpn#539]
Would it be possible to add a thin layer of security by Pin/Fingerprint locking the app or even certain connections (both in app and homescreen shortcuts) using the pin/fingerprint API of android?

It would mean that I could save the long password of my VPN server within the connection settings and authorise via fingerprint when loading that connection.

(I completely understand that fingerprint/pin locking is not without its gaping security risks but I would be interested in it just to stop people who pick up my phone from clicking on the icons on my homescreen and launching a VPN connection!!)

Much thanks for your work on this!!

**Comment by schwabe** [comment]
That is not planned as it gives a wrong sense of security. The Android security seems to be that if someone has unlocked the phone he/she is not further restricted. I don't want to deviate from that with my app.
