### ISSUE TITLE
Unable to find explicit activity ConfirmDialog

### ISSUE THREAD

**Issue by xiguapi2015** [schwabe/ics-openvpn#541]
To make issues more managable, I would appriciate if you fill out the details if applicable
# General information
1. Android 6.0
2. Android Vendor/Custom ROM
3. Device nubia z11

when I call "VpnService.prepare",the error happend below:
Unable to start activity ComponentInfo{net.chitu.chitujsq/net.chitu.chitujsq.openvpn.OpenVpnLauncher}: android.content.ActivityNotFoundException: Unable to find explicit activity class {com.android.vpndialogs/com.android.vpndialogs.ConfirmDialog}

I do'nt know what's the problem,can help me.Thanks very much.

**Comment by schwabe** [comment]
The problem is the custom rom here.That activity needs to be in Android.
