### ISSUE TITLE
why？profile is ok。I run it on openvpn app is ok

### ISSUE THREAD

**Issue by cnsms** [schwabe/ics-openvpn#546]
09-06 16:03:53.917 16769-16853/de.blinkt.openvpn D/OpenGLRenderer: endAllStagingAnimators on 0xb8bf6d68 (RippleDrawable) with handle 0xb8b2b0f8
09-06 16:03:53.987 16769-20244/de.blinkt.openvpn I/OpenVPN: Starting openvpn
09-06 16:03:54.037 16769-16769/de.blinkt.openvpn I/System.out: VPN_GENERATE_CONFIG
09-06 16:03:54.127 16769-20244/de.blinkt.openvpn I/OpenVPN: Giving up
09-06 16:03:54.147 16769-16769/de.blinkt.openvpn I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@7494f51 time:12479228
09-06 16:03:54.187 16769-16769/de.blinkt.openvpn I/System.out: NOPROCESS
09-06 16:03:54.197 16769-20244/de.blinkt.openvpn I/OpenVPN: Exiting

**Comment by schwabe** [comment]
Look in the OpenVPN log.

**Comment by cnsms** [comment]
You answer so quickly

**Comment by schwabe** [comment]
Because the issues are always the same...

**Comment by cnsms** [comment]
2016-09-06 16:13:55 Options error: Unrecognized option or missing or extra parameter(s) in /data/data/de.blinkt.openvpn/cache/android.conf:40: push (2.4_master)

**Comment by schwabe** [comment]
@cnsms yeah, there is your error. push is not a valid client configuration option.

**Comment by cnsms** [comment]
你认识中文吗？

**Comment by cnsms** [comment]
1.but，I can run it on openvpn app.
2.now I can't find the error

**Comment by schwabe** [comment]
I already told you what your error is. The openvpn connect app ignores push in client config. This app doesn't.

**Comment by cnsms** [comment]
I'm sorry, but I'm still not clear about that point

**Comment by schwabe** [comment]
I will repeat myself a last time that "push" is not a valid client configuration option and your client config is broken. I don't care if openvpn connect accepts it or not.

**Comment by cnsms** [comment]
client
dev tun
proto tcp
remote 123.252.212.20 80
http-proxy 123.22.29.16 8080
http-proxy-option EXT1 xlgmll 127.0.0.1:443
http-proxy-option EXT1 "GET http://wap.google.cn/ HTTP/1.1"
http-proxy-option EXT1 "CONNECT wap.google.cn"
http-proxy-option EXT1 "Host: wap.google.cn"
resolv-retry infinite
nobind
persist-key
persist-tun
push route 114.114.114.144 114.114.115.115
machine-readable-output
connect-retry-max 5
connect-retry 5
resolv-retry 60
auth-user-pass
ns-cert-type server
comp-lzo
verb 3

<ca>
-----BEGIN CERTIFICATE-----
MIIE9zCCA9+gAwIBAgIJALiOhVw5iEFJMA0GCSqGSIb3DQEBCwUAMIGtMQswCQYD
-----END CERTIFICATE-----
</ca>
key-direction 1
<tls-auth>
-----BEGIN OpenVPN Static key V1-----
6ec7d1939f80fa0d173249d1fe4c65ef
-----END OpenVPN Static key V1-----
</tls-auth>

**Comment by schwabe** [comment]
> push route 114.114.114.144 114.114.115.115

...

And your config does (probably illegal) tricks to work over wap. You will get no help from me for that.

**Comment by cnsms** [comment]
Thank you very much.
My problem is solved.
Thank you
Thanks very much
Okami

**Comment by cnsms** [comment]
Welcome to China！

**Comment by cnsms** [comment]
How speed limit？
