### ISSUE TITLE
Validate VPN permission without touchscreen

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#547]
# General information
1. Android Version : 4.3
2. Android Vendor/Custom ROM : Ingenic / mips build
3. Device : Some Smart glass without touchscreen
4. Version of the app (version number/play store version/self built) : OpenVPN 0.6.57
# Description of the issue

 Hello Arne, first, thank you for sharing OpenVPN for Android with everyone.

I'm actually trying to use it on some smart glasses running Android 4.3 with a MIPS build.
The main problem of thoses glasses is that it doesn't have any touchscreen abilities, but i can make the user start an app with buttons: So I give it a look at the remote example and try to make it fully automatic to start the VPN.

To be clear : everything works, but i can't check the VPN permission checkbox. I know the code works because i could emulate touch inputs through the ADB, but it's terribly painful to have to do this manually at every boot.

I'm searching for help to skip this checkbox. Either by placing a file somewhere or anything requiring root access.

Before coming here looking for help, i tried to make the remote example to use shell commands to emulate touch inputs, but it requires a special permission, only granted with firmware signature, which i don't have...

Thank you for any tips you'll have for that matter. :)

**Comment by schwabe** [comment]
Well, see also the FAQ. In short, I have no control over that permission dialog. Android 5.0+ remembers the choice after reboots but with <4.4 you have to confirm the permissions after every boot. I have written an Xposed module for Android that autoconfirms that. Not sure if you want to go that route.

**Comment by schwabe** [comment]
As for the signing permission, iirc the usual reqirement is systemorsignature. Meaning that if you have root you can also install your app as system app and get that right.

And last but no least you can get the Android sources. Patch VPNDialogs.apk's source code to automatically allow the VPN you want to connect. (Basically what the xposed hack does without that xposed framework.)

**Comment by ghost** [comment]
Thank you for the super quick response.
Already read the FAQ and tested the Xposed module, but despite the checkbox is check, it still ask permission every time...
I did carefully check, on this system, it's signature and not systemorsignature. :'(
Looks like i'm stuck there then. Damn.

Thank you again for the support !

**Comment by ghost** [comment]
Hi Arne,

I successfully recovered my VpnDialogs.apk, unzipped, converted to smali, analyzed, modified, reconverted to .dex, rezipped, resigned the apk and re-installed it.
Now VpnDialogs immediately accept without any dialog. :)

For anyone interested in the modification, just request it and i'll answer my best where needed.

Thank you Arne

**Comment by ricardojlrufino** [comment]
@JinnZ How i can do that ?

**Comment by ghost** [comment]
You have to elaborate a little more on what "Doing that" is exactly about for i can help on something.

**Comment by ricardojlrufino** [comment]
I tried APK Studio (uses apktool ) .
I tried to just decompile and compile and came back but it gives error, even without making any changes.

**Comment by ricardojlrufino** [comment]
> For anyone interested in the modification, just request it and i'll answer my best where needed.

I was referring to this ...

**Comment by schwabe** [comment]
You can also get VPNDialogs from AOSP

**Comment by ghost** [comment]
So, from what I remember, i coudn't run my recompiled code the first time too. Even without any changes.
That is, decompiling and recompiling will still have minor difference because of the tool used and their version. So the signature of the binary don't match anymore. What you need to do and to properly resigned it.

**Comment by ricardojlrufino** [comment]
> You can also get VPNDialogs from AOSP

I found the sources, but it depends on some dependencies.
Can i do the build without needing all the AOSP?

**Comment by schwabe** [comment]
@ricardojlrufino I have not looked at it nor do I plan to do, sorry.

**Comment by ghost** [comment]
I took a few notes concerning resigning a modified apk : 

> // cd /path/to/android/root/project/to/recompile
			keytool -genkeypair -alias androiddebugkey -dname "CN=Android Debug,O=Android,C=US" -keystore ./debug.keystore -keyalg RSA -validity 10000
			rmdir META-INF
			// Zip the folder in STORE, name: out-unaligned.apk
			jarsigner -sigalg MD5withRSA -digestalg SHA1 -keystore ./debug.keystore out-unaligned.apk androiddebugkey
			C:\SDK\build-tools\24.0.2\zipalign.exe 4 out-unaligned.apk out.apk
			keytool -printcert -jarfile out.apk
			adb install out.apk

You can indeed directly get VpnDialogs source instead, but the modification i did in the smali was VERY little, just had to swap two registers in one function call.

**Comment by ricardojlrufino** [comment]
Hi,
I understand how to make the modification.
It was giving error to make buil because it was not using the original framework-res ...
And the other one lacked the signature, as you said.
I worked thank you

By coincidence I did not need to do the zipalign.
And I was able to run both in /priv-app, and in /data/app

**Comment by ricardojlrufino** [comment]
> @ricardojlrufino I have not looked at it nor do I plan to do, sorry.

OK no problems.
I did not find much information about that.
I found it easier to decompile
