### ISSUE TITLE
load ovpn files with an adb command

### ISSUE THREAD

**Issue by egarim** [schwabe/ics-openvpn#548]
To make issues more managable, I would appriciate if you fill out the details if applicable
# General information
1. Android Version
   4.1.1 to 4.4.2
2. Android Vendor/Custom ROM
   sony (phone manufacture)
3. Device
   Sony Xperia XA
4. Version of the app (version number/play store version/self built)
# Description of the issue

 Hi I have been using your vpn client to do api test from physical devices and android emulators , everything works perfect. 

I copy the ovpn files using the adb, and i save the in the download folder, right now I manually load the profieles and connect to the vpn using the adb command you  wrote on the readme file. My question is 

1) can the command be modify to accept the route of the ovpn file so I dont need to manually load it before I use it.

2) can i create my own adb command to load the profiles without using the U.I

all suggestions are welcome

**Comment by schwabe** [comment]
You can use adb backup/restore to backup the whole app including profiles. Don't know if that helps you.

There is an API (see the remoteexample) to programmatically add profiles to the app. that still would require a bit of programming.

It might work to create an intent with a file:// URL that starts the import activity of openvpn and then simulate the touching checkmark with adb.

**Comment by egarim** [comment]
Hi 
I try to use the adb back and restore everything works correctly but when I restore the applications it does not include the profiles i have load before.

regarding the 2 other options that you told me before which one would you think that would be the easiest one.

maybe there is a way to include the profiles when I compile the apk from the source?

**Comment by egarim** [comment]
Hi Arne
i was reading the source to import the ovpn profiles it looks like i need to modify remote example on the MainFragment.java there is a method called startEmbeddedProfile which looks the be the code for import the opvn profiles programmatically. is this the correct method to take a base to achieve my task?

in your previous answer you also mention this that i can create an intent with a file:// URL and load the profiles there. can you please tell me what is the name of the import activity? im having a hard time locating that code

**Comment by schwabe** [comment]
Yes the remote example can do that. Using file:// should work on platforms < 6.0. There isn't an activity you are starting. You are interacting with a bound service (and AIDL).
