### ISSUE TITLE
Import project as module?

### ISSUE THREAD

**Issue by giorizzotti** [schwabe/ics-openvpn#549]
Hello, I'm trying to create a test project in which there is a button that should run your app.
I created a new Android Studio project, next clicked on File/New/Import Module and selected all your source code (after the ndk compilation).
Next, in the **build.gradle (app)** file, added a row in the _dependencies_ section:
`compile project(':openvpn')`
As already said, I just want to launch your application from a button in a activity of my project.
I'm trying to create a new intent with:
`Intent intent = new Intent(this, de.blinkt.openvpn.activities.MainActivity)`
but the activity is not recognized by Android Studio.
How to procede? Thank you in advance.

**Comment by schwabe** [comment]
Just keep them seperate. You don't need them in the same workshop for that intent to work (or even compile yourself)

**Comment by giorizzotti** [comment]
Hi schwabe, I would like to realize, if it's possible, a single package instead of installing two separate application (yours and mine). Is there a way to do it?

**Comment by schwabe** [comment]
@giorizzotti Please the doc/README.me on that, especially on licenses.

**Comment by giorizzotti** [comment]
@schwabe the project that I'm trying to realize is for a Master's Degree Thesis and it will be released as open source. Can't I do it?

**Comment by schwabe** [comment]
Sure that is possible. 

The easiest way is probably to modify the app itself. Turning ics-openvpn is probably a lot more work.

**Comment by giorizzotti** [comment]
So it's not possible to integrate your app as a module of another app and start your MainActivity from a button of my MainActivity?

**Comment by schwabe** [comment]
I have no idea, I never done combining gradle modules, sorry.

**Comment by giorizzotti** [comment]
If I edit the app itself, can I choose a different name and package name for it or your license doesn't allow me to do that?

**Comment by schwabe** [comment]
You can do that just fine as long as you publish the source code with its license.
