### ISSUE TITLE
Cannot find de.blinkt.openvpn.core.OpenVPNService

### ISSUE THREAD

**Issue by nickapos** [schwabe/ics-openvpn#550]
Hello,

I have just downloaded openvpn on my kindle fire 7 tablet. It installed succesfully, but when i am trying to connect to my vpn, i am getting a failure.

The log says:

Failed to open the tun interface
Error:Cannot find de.blinkt.openvpn.core.OpenVPNService

and so on

I am not sure if there is anything missing on the amazon fire os distribution?

**Comment by schwabe** [comment]
which kindle fire tablet is it and what android version is running on it?

**Comment by nickapos** [comment]
Hello,
 it is the Kindle Fire 7 and it has the Fire OS 5.3.1.0

**Comment by schwabe** [comment]
what version of th app are you running?

**Comment by nickapos** [comment]
It is version 0.6.55

**Comment by schwabe** [comment]
Can you provide me with a full log inside the app?

**Comment by nickapos** [comment]
Hello, I tried to reconnect in order to obtain the log and it worked this time.
As far as I can tell nothing has changed since th last time.
I apologise for the false alarm

**Comment by rajpatel0335** [comment]
hi i am tried this and working in debug app but not working in live app

**Comment by schwabe** [comment]
@rajpatel0335 what do you mean with live app? The one from amazon app store?
