### ISSUE TITLE
google-messaging-service blocked by suspend@inactivity

### ISSUE THREAD

**Issue by gaga9999** [schwabe/ics-openvpn#552]
Hy,
Android Client 0.6.57:
I use the function "Suspend at inactivity" with a persistent tun device. Issue is, that the Google-play-messaging-service does not get updates (messages being sent to me). I think it is because the threshold of 64kbytes might be too high for those messages. Affected are Google Hangouts and Signal Messenger, which receive messages only after I wake up the smartphone.

Maybe it would be possible to make the parameters of "suspend at inactivity" configurable? Or maybe just a time-slot (i.e. all x minutes wake up for 1 minute)?
Thx!

**Comment by schwabe** [comment]
waking up every x minutes for 1 minutes will not work since the other services have no idea that the net is there again.

But basically if you want background services to work, maybe then disabling background VPN is not for you.

**Comment by gaga9999** [comment]
thx. i have the feeling, that websocket-ajax connections  actively rebuilt connection upon wakeup, so the apps might make an connection attempt themselves after net comes up again - they do so after manuallly waking up, so i think there is some kind of signal going to the apps or the apps are constantly checking: connection up?

**Comment by schwabe** [comment]
You get events when the screen is unlocked which also my app uses. But still the feature is intended that your phone looses its connectivity when going into suspend but not to disrupt ongoing transmissions. Loosing your google play messaging service is part of that.

**Comment by gaga9999** [comment]
ok, i got it. so i would need an app issuing a wake-lock periodically. do you maybe know one?

**Comment by schwabe** [comment]
I have no idea.
