### ISSUE TITLE
vpndialogxposed

### ISSUE THREAD

**Issue by egarim** [schwabe/ics-openvpn#558]
To make issues more managable, I would appriciate if you fill out the details if applicable
# General information
1. Android Version 4.4.4
2. Android Vendor/Custom ROM HTC, ZTE , LG
3. Device
4. Version of the app (version number/play store version/self built) self built
# Description of the issue

 Hi I have been trying to use the vpndialogxposed to try to make devices remember the decision of allow vpn traffic but it vpndialogxposed does not work in any of the devices i have tried maybe im not compiling it on the correct way, is there a place where I can download a compiled version just to check if my build process is wrong

**Comment by schwabe** [comment]
I haven't look into that xposed stuff in years. I don't even know if compiles/works with modern SDK. The module is available from the xposed repo: http://repo.xposed.info/module/de.blinkt.vpndialogxposed

**Comment by egarim** [comment]
Hi Arne I try the module from the link with the OpenVPN for Android 0.6.60 and did not work it did not remember the  desicion  and ask confirmation after reboot. Maybe a it would work using a different version of the client? 

I'm using android 4.4.4 in a asus transforme 101. any suggestions are welcome

Thankss

**Comment by schwabe** [comment]
you have to select which vpn are instantenously allowed in the settings of the module.

**Comment by egarim** [comment]
yes the vpn clients are selected in the module screen but the client still prompt for confirmation

**Comment by egarim** [comment]
Here is a link with a video of what is happening

https://drive.google.com/open?id=0B4ZzvLQGiFRgdkpFUWE4MUw0eGVZeTdBRXJJXy1QWmNTb1Jz

**Comment by schwabe** [comment]
Err, I have no idea. Sorry.

**Comment by schwabe** [comment]
Closing that issue. I won't look into xposed any time soon and will probably delete subproject from the repo
