### ISSUE TITLE
java.lang.ExceptionInInitializerError

### ISSUE THREAD

**Issue by juliejohn** [schwabe/ics-openvpn#559]
Hi Sir,

My app got rejected from the google playstore due to security vulnerabilities(openssl issue) since I use opnvpn as my project module. How could I resolve this issue? Please help....
I downloaded  the updated openvpn from github and it is giving me"java.lang.ExceptionInInitializerError" and "java.lang.UnsatisfiedLinkError: Couldn't load opvpnutil: findLibrary returned null".

**Comment by schwabe** [comment]
Please see the first FAQ in doc/README. What you describe sounds like another of these GPL violating forks of my app. I have no interest in helping unless you convince that your app is not one these GPL violating ones.
