### ISSUE TITLE
Error Switching vpn connections

### ISSUE THREAD

**Issue by egarim** [schwabe/ics-openvpn#561]
Android Version 4.4.4
Android Vendor/Custom ROM HTC, ZTE , LG
Device
Version of the app (version number/play store version/self built) self built

Hi I have 5 vpn profiles loaded on my device , i connect using the adb command 
am start -a android.intent.action.MAIN -n de.blinkt.openvpn/.LaunchVPN -e de.blinkt.openvpn.shortcutProfileName [Name of the profile]

if I run the command again to connect to a different location i got error resolving hostnames in the log

do I have to somehow disconnect before I switch vpn profile

**Comment by schwabe** [comment]
Disconnecting should be automatically when a new VPN is established. You might run into some bizzare race condidition. Is the resolving problem permant or just on the first connecting try?
