### ISSUE TITLE
Building with Clang

### ISSUE THREAD

**Issue by lkorth** [schwabe/ics-openvpn#563]
With r13 of the NDK, GCC is no longer supported and Clang is used for builds. Was there a resolution to android-ndk/ndk#144 that allows the app to be built with r13 and Clang?

**Comment by schwabe** [comment]
Not yet. Honestly compiling OpenSSL is a mess. The perl scripts that generate the assembler files need to run the target CC in order to generate the right code.

**Comment by lkorth** [comment]
That did the trick, thanks!

**Comment by lkorth** [comment]
Clearing things out and doing a fresh compile with r13 and Clang looks like it still has a few issues. It compiles fine with a few warnings, but running OpenVPN fails to find `BF-CBC`.

```
MGMT: Got unrecognized command>FATAL:Cipher algorithm 'BF-CBC' not found
MANAGEMENT: Client disconnected
Cipher algorithm 'BF-CBC' not found
Exiting due to fatal error
OpenVPN exited
Process exited with exit value 1
```

I'll probably stick with r12 for now.

**Comment by schwabe** [comment]
What library version does your build print? Mine seems even worse and did not do the static linking and prints BoringSSL and then segfaults.

**Comment by lkorth** [comment]
I cloned `ics-openvpn` to try and build master, however I was unable to update the openvpn submodule.

> Fetched in submodule path 'openvpn', but it did not contain 9d8801b6185d7453b4268a2767d5d63118bbb5d6. Direct fetching of that commit failed.

Trying to run `build-native.sh` anyway blows up with a bunch of errors.

```
error: undefined reference to 'query_user_exec_builtin'
```

The build that results in `BF-CBC` not found when using r13 is in https://github.com/lkorth/auto-fi using your openssl fork at `6c59e3226d34bd911e800c4b1daea25047234ef1` and your openvpn fork at `c441a5eaf092c48e89fbb44cc51f5d3a3a3e1d5c`

**Comment by schwabe** [comment]
Yeah. Probably your version also links against the platform ssl library (instead of the static linking) which your case (Probabably Android <6.0) still happens to be OpenSSL but is probably build without BF-CBC support. What does OpenVPN print as OpenSSL library version when it starts?

**Comment by lkorth** [comment]
On a working version compiled with r12 and GCC:

```
OpenVPN 2.4-icsopenvpn [git:HEAD-c441a5eaf092c48e] android-19-armeabi-v7a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [IPv6] built on Oct  7 2016
library versions: OpenSSL 1.0.2j  26 Sep 2016, LZO 2.09
```

On a version failing to find `BF-CBC` cleanly compiled with r13 and Clang:

```
OpenVPN 2.4-icsopenvpn [git:HEAD-c441a5eaf092c48e] android-21-arm64-v8a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [IPv6] built on Oct 18 2016
library versions: BoringSSL, LZO 2.09
```

So it is using BoringSSL on API 21.

**Comment by schwabe** [comment]
As I suspected. Static linking isn't working for some non obvious reason. But is tracable to the NDK itself. So something with BUILD_STATIC_LIBRARY is probably broken

readelf -d libs/x86/libopenvpn.so  |grep NEEDED also confirms that.

**Comment by thecodeflash** [comment]
Hello,

I checked the PlayStore [app](https://play.google.com/store/apps/details?id=de.blinkt.openvpn&hl=en) is able to connect in Android 6.0 and greater. It used OpenSSL but when I tries to connect using app built from this repository it uses Boring SSL. 

What could be the issue that using PlayStore App we are able to connect but using app built from repository we are not able to connect in Android version 6.0 and greater.

**Comment by schwabe** [comment]
@VJ-Vicky just look at my last post ...

**Comment by thecodeflash** [comment]
@schwabe I don't understand why it is not working in app built from repository while it is working in app from PlayStore. What is the reason for such an issue? Is it because of NDK version?

**Comment by schwabe** [comment]
@VJ-Vicky the information why this happens is all here in this issue

**Comment by schin1207** [comment]
i am also facing same problem as @VJ-Vicky please solve the issue

**Comment by schwabe** [comment]
@schin1207 making demands does not work with spare time projects. How about you looking into this and solving this?

**Comment by thecodeflash** [comment]
@schwabe Sir, I was able to build the application using r12, before it gave error but then I cloned your repository again and ran the built command it worked. 

Thank You for you support and fast response really appreciate it.  😄 👍

**Comment by thecodeflash** [comment]
@schin1207  Please try to build the app using r12 it works. And try to be polite he is doing such a great work for free and giving his precious time to the society.
