### ISSUE TITLE
Used breakpad binaries

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#565]
F-Droid's scanner complains about the following binaries from upstream breakpad. Which of them are actually used? I'd say I can safely remove windows and mac stuff?

```
ERROR: Found static library at main/breakpad/src/third_party/linux/lib/glog/libglog.a
ERROR: Found static library at main/breakpad/src/third_party/linux/lib/gflags/libgflags.a
ERROR: Found binary at main/breakpad/src/client/mac/handler/testcases/testdata/dump_syms_dwarf_data
ERROR: Found binary at main/breakpad/src/client/mac/testapp/crashInMain
ERROR: Found binary at main/breakpad/src/client/mac/testapp/crashduringload
ERROR: Found static library at main/breakpad/src/client/mac/gcov/libgcov.a
ERROR: Found binary at main/breakpad/src/tools/windows/binaries/symupload.exe
ERROR: Found binary at main/breakpad/src/tools/windows/binaries/dump_syms.exe
```

**Comment by schwabe** [comment]
Actually I would have to test test but considering that the libraries aren't build for 6 architerures OpenVPN is compiled it is safe to assume that they are not used.

**Comment by schwabe** [comment]
You can also disable breakpad alltogether by calling build-native.sh with USE_BREAKPAD=0 and just remove that sub git repo
