### ISSUE TITLE
Black theme AMOLED

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#566]
Is possible add a black theme "AMOLED" for save the battery?

**Comment by schwabe** [comment]
I don't  think that OpenVPN for Android is visible long enough on the screen to make any difference

**Comment by PanderMusubi** [comment]
Well, a reason to add it is also to *save* your eyes. When you have 95% of your apps in dark mode (even without having amoled screen), the one app that is not in dark mode is very intense to look at and temporarily not good for your night vision. Please, reconsider this issue as an enhancement. It could even be funded via BountySource.

**Comment by mikewesten** [comment]
+1 for native dark mode options.
