### ISSUE TITLE
All cipher types are either not supported or not found

### ISSUE THREAD

**Issue by nathan-fiscaletti** [schwabe/ics-openvpn#569]
To make issues more manageable, I would appreciate if you fill out the details if applicable
# General information
1. 7.0 - Nougat - API Level 24
2. ?
3. Galaxy Nexus Emulator
4. self built
# Description of the issue

 I'm trying to use the remote build to simply connect to my vpn server. 

 My vpn server is configured properly, however for some reason no matter which i choose ics-openvpn remote example will tell me that all ciphers are either 'not found' or 'not supported'. 

Am I missing something somewhere?

Example message: 
`de.blinkt.openvpn I/openvpn: Got unrecognized command>FATAL:Cipher 'AES-128-CBC' mode not supported`

`de.blinkt.openvpn I/openvpn: Got unrecognized command>FATAL:Cipher algorithm 'BF-CBC' not found`

**Comment by schwabe** [comment]
Building current master with ndk 13 does not work. Use the store version with the remote app or build last published version with ndk 12 or set the cc to gcc.

**Comment by nathan-fiscaletti** [comment]
I tried recompiling using NDK 12 and got the same result, but I was able to run it on a phone using API Level 22. The issue still persists if i'm using a phone with API Level 24.

**Comment by schwabe** [comment]
Yes, that sounds like the same problem as #563
