### ISSUE TITLE
Feature request: Start OpenVPN when a certain app is launched

### ISSUE THREAD

**Issue by dolphinkite** [schwabe/ics-openvpn#571]
Hi,

I'm not even sure this is possible, but many of the apps I use will only work when connected to my home network. Specifically, amongst others, the Synology apps (DS Photo, DS Video, DS File) and the Ubiquiti apps (UniFi and UniFi Video). Additionally, for at least one app (UniFi Video), if I start it before the VPN connection is established, not only will it not connect (obviously), but it will also fail to connect even after the VPN is established. I need to close the app and restart it.

For me (and others I'm sure), it would be great if when launching an app, the launcher (?) would know that this app has been configured to ONLY work with a VPN connection, and will first launch OpenVPN, and once the connection is established, will launch the initial app.

Perhaps this is a feature request for Android.. (?).. but I'm wondering if it could be done at the app level... detecting certain apps are launched and lauch the VPN..?

I don't have high hopes for this one, but it would save me so many clicks.

Just a suggestion.

Thanks

**Comment by schwabe** [comment]
Doing something like this is more for automation software like tasker.
