### ISSUE TITLE
Unable to run UP script

### ISSUE THREAD

**Issue by rajil** [schwabe/ics-openvpn#575]
To make issues more manageable, I would appreciate if you fill out the details if applicable
# General information
1. Android Version:6.0.1
2. Android Vendor/Custom ROM:Samsung Stock
3. Device:Note4 N910T
4. Version of the app (version number/play store version/self built): 0.6.60
# Description of the issue

 I want to run up/down script to modify net.dns1/net.dns2 parameters. My vpn config looks like this:

```
# Enables connection to GUI
management /data/user/0/de.blinkt.openvpn/cache/mgmtsocket unix
management-client
management-query-passwords
management-hold

setenv IV_GUI_VER "de.blinkt.openvpn 0.6.60"
setenv IV_PLAT_VER "23 6.0.1 armeabi-v7a samsung APQ8084 SM-N910T"
machine-readable-output
ifconfig-nowarn
client
verb 4
connect-retry 2 300
resolv-retry 60
dev tun
remote xxx 1194 udp

key-direction 1
verify-x509-name LanVPNServer name
cipher AES-256-CBC
auth SHA256
persist-tun
# persist-tun also enables pre resolving to avoid DNS resolve problem
preresolve
# Use system proxy setting
management-query-proxy
# Custom configuration options
# You are on your on own here :)
# These options found in the config file do not map to config settings:
script-security 2
up /vpn/updns.sh
down /vpn/down.sh
ns-cert-type server
lport 0 
```

Unfortunately, i get an error on

```
Options error: --up script fails with '/vpn/updns.sh': Permission denied
```

I have verified that the up script has execute permissions and has the following contents.

```
root@trltetmo:/vpn # cat updns.sh                                              
#!/system/bin/sh
getprop net.dns1 >/storage/743A-C6DD/vpn/dns1.txt
getprop net.dns2 >/storage/743A-C6DD/vpn/dns2.txt
setprop net.dns1 10.8.10.1 
setprop net.dns2 10.8.10.1 

root@trltetmo:/vpn # ls -la updns.sh                                           
-rwxr-xr-x root     root          173 2016-10-26 05:43 updns.sh
```

Any idea what could be wrong?

**Comment by schwabe** [comment]
there might be some other things that prevent executing scripts in random directory. Since you have already root try putting it next to openvpn for android own executable ovpn_pie in the cache dir of the app.

**Comment by rajil** [comment]
Ok, putting the script in the cache directory and changing permissions helped.

```
root@trltetmo:/data/data/de.blinkt.openvpn/cache # ls -l
-rw------- u0_a244  u0_a244      6398 2016-10-26 06:16 android.conf
-rwx------ u0_a244  u0_a244       270 2016-10-26 06:07 down.sh
-rw------- u0_a244  u0_a244     17403 2016-10-26 06:16 logcache.dat
srwx------ u0_a244  u0_a244           2016-10-26 06:16 mgmtsocket
-rwx------ u0_a244  u0_a244      5392 2016-07-31 15:23 pie_openvpn.armeabi-v7a
-rwx------ u0_a244  u0_a244       141 2016-10-26 06:18 updns.sh
```

I simplified the updns.sh script to the following and removed the 'down' script from the config:

```
#cat updns.sh
#!/system/bin/sh
getprop net.dns1 >/data/data/de.blinkt.openvpn/cache/dns1.txt
getprop net.dns2 >/data/data/de.blinkt.openvpn/cache/dns2.txt
```

But I get another error:

```
6:20 AM OpenVPN 2.4-icsopenvpn [git:HEAD-9d8801b6185d7453] android-14-armeabi-v7a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [IPv6] built on Oct  9 2016 
6:20 AM library versions: OpenSSL 1.0.2j  26 Sep 2016, LZO 2.09 
6:20 AM NOTE: the current --script-security setting may allow this configuration to call user-defined scripts 
6:20 AM TCP/UDP: Preserving recently used remote address: [AF_INET]xx.yy.xx.yy:1194 
6:20 AM UDP link local (bound): [AF_INET][undef]:0 
6:20 AM UDP link remote: [AF_INET]xx.yy.xx.yy:1194 
6:20 AM [LanVPNServer] Peer Connection Initiated with [AF_INET]xx.yy.xx.yy:1194 
6:20 AM GDG: SIOCGIFHWADDR(lo) failed 
6:20 AM do_ifconfig, tt->did_ifconfig_ipv6_setup=0 
6:20 AM /data/data/de.blinkt.openvpn/cache/updns.sh vpnservice-tun 1500 1569 10.8.10.2 255.255.255.0 init 
6:20 AM WARNING: Failed running command (--up/--down): could not execute external program 
6:20 AM Exiting due to fatal error 
6:20 AM MGMT: Got unrecognized command>FATAL:WARNING: Failed running command (--up/--down): could not execute external program 
6:20 AM Process exited with exit value 1
```

**Comment by schwabe** [comment]
You need to set script-security to at least 2

**Comment by rajil** [comment]
Yes, i do have script-security 2 set in the config as shown in the first post and also the warning shows it:

```
6:20 AM NOTE: the current --script-security setting may allow this configuration to call user-defined scripts 
```

**Comment by schwabe** [comment]
Sorry I have no idea. Maybe Android does not like exeucting scripts that use sh. Try to copy ifconfig or something else there and see if that works. Also increase the verbosity of the log by using that slider in the log window. It might give you more messages.

**Comment by rajil** [comment]
Modified updns.sh

```
root@trltetmo:/data/data/de.blinkt.openvpn/cache # cat updns.sh                
ifconfig
```

gives the same error

```
 Failed running command (--up/--down): could not execute external program 
```

**Comment by schwabe** [comment]
I meant:

cp ifconfig cache 

up /path/to/ifconfig

**Comment by rajil** [comment]
Ok, did that and change permissions of ifconfig to match openvpn binary, but got the same error :(

**Comment by rajil** [comment]
I used tasker to set the net.dns1 and net.dns2 variables following this blog [post](https://codeword.xyz/2016/09/08/solving-openvpn-dns-issues-on-android-clients/)

**Comment by blackwind** [comment]
Could you take a look at the underlying issue here, @schwabe? DNS servers pushed by the OpenVPN server should be applied on connect, then reverted on disconnect. The current behavior is a major privacy issue.

**Comment by schwabe** [comment]
The underlying issue is that net.dns1 and net.dns2 are obsolete and any app that uses them is wrong. The VPNService API since 5.0 or 6.0 does not set these anymore. (There is another close issue about this).

**Comment by blackwind** [comment]
Gotcha, good to know. Cheers!

**Comment by rajil** [comment]
My up script magically started to work. I did a system update to get the latest security patch(October) on 6.0.1, and did a factory reset.

This is what the directory looks like with the script called updns.sh
```
ls -la /data/data/de.blinkt.openvpn/cache                                      <
-rw------- u0_a252  u0_a252      6446 2016-12-10 21:35 android.conf
-rw------- u0_a252  u0_a252     14701 2016-12-10 21:35 logcache.dat
srwx------ u0_a252  u0_a252           2016-12-10 21:35 mgmtsocket
-rwx------ u0_a252  u0_a252      5384 2016-12-10 21:23 pie_openvpn.armeabi-v7a
-rwx------ u0_a252  u0_a252        72 2016-12-10 21:16 updns.sh

cat updns.sh                                                                   <
#!/system/bin/sh
setprop net.dns1 10.8.10.1
setprop net.dns2 10.8.10.1
```
 Custom configuration parameters are
```
ns-cert-type server 
script-security 2
up /data/data/de.blinkt.openvpn/cache/updns.sh
```

**Comment by craigphicks** [comment]
It is Feb 2019, with Android 8, OpenVPN 2.3.10, with

    push "redirect-gateway def1 bypass-dhcp"

set in the server.conf file.

On the OpenVPN for Android settings "Bypass VPN for local networks" is off, although it doesn't seem to make a difference.

Logging DNS packets on the server I can see them passing through the FORWARD table.. e.g. -

    Feb 03 19:15:21 *** kernel: [VPN fwd 53] IN=tun0 OUT=eth0 MAC= SRC=10.8.0.10 DST=9.9.9.9 LEN=64 TOS=0x00 PREC=0x00 TTL=63 ID=9319 DF PROTO=UDP SPT=27955 DPT=53 LEN=44

When the Android is on the home wifi I try monitoring DNS packets leaking out there but nothing was detected. 

I also used dnsleaktest.com on the Android to check for leaks. Set up the home network to use different nameservers than the VPN. The dnsleaktest showed only the VPN servers.   (On the home network all outgoing DNS traffic is DNAT'd to the specified servers.)

Although this is not absolute proof that Android could *never* bypasses VPN with DNS - e.g. that there is no switch to change Androids behavior,  it's as good as it gets.

My conclusion is that DNS is going through the VPN correctly.
