### ISSUE TITLE
Mask device informations?

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#577]
Hi! Given the extreme versatility of the app, I would propose to add another function (I hope it is not a idiotic thing or not relevant for the operations of the app): the ability to change (Root?) Or mask the identity device (Xposed module?) .. and, therefore, MAC Address, IMEI, Model ... in short, all the details available in the Settings + anything else useful to identify the device.

As I wrote, it might be idiotic or useless thing .. but I wanted to offer it the same because the app would become further polyvalent (and necessary!)

**Comment by schwabe** [comment]
I don't think that this belongs in a VPN app
