### ISSUE TITLE
XOR/scramble feature

### ISSUE THREAD

**Issue by windclimb** [schwabe/ics-openvpn#578]
Hello. Can you add support of XOR/scramble feature? Because it's so hard to connect to the VPN in some countries (China, Iran etc.). Please don't say no, it's not so hard and it would be very helpful for a lot of people. Thank you very much.

**Comment by schwabe** [comment]
No, see the other issues closed for that. Or look into tls-crypt patches on the ML, they will be integrated and better than scramble

**Comment by windclimb** [comment]
So when will be tls-crypt integrated? Please believe me, it's so hard to live with DPI blocking.

**Comment by schwabe** [comment]
When it is done
