### ISSUE TITLE
VPN is not offered as always-on option

### ISSUE THREAD

**Issue by Strubbl** [schwabe/ics-openvpn#585]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version: 6.0.1
2. Android Vendor/Custom ROM: stock
3. Device: sony xperia z5c
4. Version of the app (version number/play store version/self built): f-droid version
 
# Description of the issue
 
In the VPN menu (Settings -> More -> VPN) there is the option to enable always-on VPN. Unfortunately, the OpenVPN for Android is not listed here. Is it possible from app-side to add itself to that list?

**Comment by schwabe** [comment]
I think you need to connect one time to get it listed there. It is listed on my phone (a yellow z5c :p)

**Comment by Strubbl** [comment]
No, that does not change the described error. I was already connected successfully and several times to my OpenVPN, but it is not listed here. 

Maybe i did not clearly state what is my issue. I have listed the my VPN in in the main VPN list of that menu. But if i go to the menu and select enable always-on VPN, my VPN is not listed in that popup. 

I have attached a screenshot of that behaviour. It is in German, if you need an English screenshot, i can provide one.
![screenshot_20161111-091839](https://cloud.githubusercontent.com/assets/97055/20356292/5dced982-ac24-11e6-9652-5cfc10e96e9c.png)

**Comment by schwabe** [comment]
Oh you need 7.0 for the always on feature of VPN apps

**Comment by Strubbl** [comment]
May i know how you installed 7.0 on your z5c? I have the stock Android installed, where the latest Android version is not offered yet. Which ROM are you using?

**Comment by schwabe** [comment]
Sorry I confused the issue first. My z5c is still on 6.0.1

**Comment by Strubbl** [comment]
Can you please shortly state why you closed this issue?

**Comment by schwabe** [comment]
Always on VPN for VPN apps is not available for Android < 7.0.

**Comment by Strubbl** [comment]
Thanks for clarification.

Just for reference later on: https://developer.android.com/about/versions/nougat/android-7.0.html#always_on_vpn
