### ISSUE TITLE
Failed to compile this code.

### ISSUE THREAD

**Issue by lucifinilsu** [schwabe/ics-openvpn#586]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
 
# Description of the issue
 hi
I tried to use Android Studio to compile this project,but the message window of Android Studio print error log:

Information:Gradle tasks [:main:generateModernDebugSources, :main:generateModernDebugAndroidTestSources, :main:prepareModernDebugUnitTestDependencies, :main:mockableAndroidJar, :main:compileModernDebugSources, :main:compileModernDebugAndroidTestSources, :main:compileModernDebugUnitTestSources, :remoteExample:generateDebugSources, :remoteExample:mockableAndroidJar, :remoteExample:prepareDebugUnitTestDependencies, :remoteExample:generateDebugAndroidTestSources, :remoteExample:compileDebugSources, :remoteExample:compileDebugUnitTestSources, :remoteExample:compileDebugAndroidTestSources, :vpndialogxposed:generateDebugSources, :vpndialogxposed:generateDebugAndroidTestSources, :vpndialogxposed:mockableAndroidJar, :vpndialogxposed:prepareDebugUnitTestDependencies, :vpndialogxposed:compileDebugSources, :vpndialogxposed:compileDebugAndroidTestSources, :vpndialogxposed:compileDebugUnitTestSources]
Warning:warning: passing 'volatile int *' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
Error:error: unable to execute command: program not executable
Error:error: assembler command failed with exit code 1 (use -v to see invocation)
Warning:warning: passing 'volatile int *' to parameter of type 'void *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
Information:note: passing argument to parameter 'ptr' here
Information:BUILD FAILED
Information:Total time: 7.985 secs
Information:2 errors
Information:2 warnings
Information:See complete output in console

**Comment by schwabe** [comment]
no idea what you are doing but AS isn't used to compile the ndk part. See doc/README
