### ISSUE TITLE
Notification in status bar missing even Android VPN icon (key) is visible

### ISSUE THREAD

**Issue by godfuture** [schwabe/ics-openvpn#588]
# General information
1. Android Version
6.0.1
2. Android Vendor/Custom ROM
Cyanogenmod
3. Device
Samsung GT9195
4. Version of the app (version number/play store version/self built)
0.6.60
# Description of the issue
Most of the times, establishing a VPN connection ends with a notification shown in the Android notification bar. This notification allows to view the log, restart or stop the connection. But this notification in the Android notification bar, does not always show up, even the Android VPN icon is displayed. Without the notification, I cannot use the shotcuts that are normally available.

**Comment by schwabe** [comment]
Can you send me the log when this happens?

**Comment by godfuture** [comment]
I am still aware of your request, but it is not easy to reproduce it. Lets see...

**Comment by godfuture** [comment]
Well, the situation occured again. As the UI is not available, I do not know how to gather the logs.
Are the current logs somehow persisted on SD or internal storage? I guess when closing openVPN, they are lost...
![openvpn_no_noti2](https://cloud.githubusercontent.com/assets/4669278/21055495/d10f21ee-be31-11e6-88cc-15988d59741a.png)
I think this issue occurs, when I execute the widget twice without closing the application before.

**Comment by Johanboy** [comment]
My Amazon Fire tablet running Fire OS 5.3.2.1 has the same problem. When a VPN is running in Open VPN with status "connected" there is no indication of this in the status bar. It is desirable that the key icon be displayed.

**Comment by schwabe** [comment]
@Johanboy the key icon is entirely controlled by Android. That might be a bug in Fire OS. I can check with my fire tablet how it behaves.

@godfuture the app will automatically save/restore the log.

**Comment by shewfig** [comment]
I'm seeing this on CyanogenOS 13.1.2 (Android 6.0.1) on my OnePlus One.  Which logs do you want the next time it happens?  FYI I just signed up for beta via Play Store.

**Comment by schwabe** [comment]
The in app log in the log window, use the share icon to export

**Comment by schwabe** [comment]
No response

**Comment by nthorne** [comment]
This one happens for me all the time now, seems to have started after Tasker got a major version update (I use tasker for connecting VPN).

Edit: sent the logs via mail. Also, running cyanogen os on my oneplus one.

**Comment by naddel81** [comment]
same here on MIUI 9.5

**Comment by schwabe** [comment]
I yet have to receive a log for this that tells me what could be going on.

**Comment by Dangerboyy** [comment]
In my red mi note 4 MIUI 9.5 when my VPN is on , their is  no key symbol or VPN symbol is showing in my status bar  
,Can I know the solution

**Comment by steve-s1w** [comment]
Also on MiUI 9.5 same problem on Redmi Note 3 pro android 6.0.1.

**Comment by PeterMcGr** [comment]
Confront your cheating spouse with evidence, i was able to spy on my cheating ex phone without finding out.....it really helped me during my divorce ...you can contact (syproblast666@gmail.com) for spying and hacking social networks, school servers, icloud and much more, viber chats hack, Facebook messages and yahoo messenger, calls log and spy call recording, monitoring SMS text messages remotely, cell phone GPS location tracking, spy on Whats app Messages, his services are AFFORDABLE .................................... ONLY GOD CAN THANK HIM FOR ME

**Comment by Rorschached99** [comment]
Yes. I have same irritation. No key icon when VPN active. Samsung A5 Android 8.0.0.

**Comment by schwabe** [comment]
Samsung decided to rather show a notification like Android 4.0 instead of the key icon that all other Android variants use since 5.0
