### ISSUE TITLE
Missing 'config-version.h'?

### ISSUE THREAD

**Issue by anaktas** [schwabe/ics-openvpn#589]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version 4.1.1
2. Android Vendor/Custom ROM
3. Device TCT Vodafone 975
4. Version of the app (version number/play store version/self built)
 
# Description of the issue

I am trying to run the ndk-build script and I am receiving this error:
openvpn/src/openvpn/options.c:37:10: fatal error: 'config-version.h' file not found

I've look into the folder and it seems that it is indeed missing. 
https://github.com/schwabe/openvpn/tree/icsopenvpn/src/openvpn

Am I using the wrong branch? Because I think that it is missing in any available branch. Is it save to remove this header file from the incudes of the options.c file?

**Comment by schwabe** [comment]
If you want to build it see the README or the countless other tickets ...
