### ISSUE TITLE
Unable to import OpenVPN profile (application/octet-stream)

### ISSUE THREAD

**Issue by depler** [schwabe/ics-openvpn#590]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android 6.0.1
2. MIUI 8.0.5 Global Stable
3. Xiaomi Mi 5
4. Version 0.6.60 from play store
 
Can't import OpenVPN profile file from local storage (I've tried both .ovpn and .conf extensions) - it just don't see any files in folder. So I had to create profile manually and import each cert file separetely plus edit some settings. Can you fix this?

P.S. I have theory that this is firmware bug, when file explorer cannot filter extensions with 4 symbols. In that case it would be nice to remove filter at all to see all files.

**Comment by schwabe** [comment]
or it might assign a complety wrong mime type. Can you run plai.de/.tmp/cursor.apk and see what that small util returns?

Also opening ovpn from a file explorer program works too.

**Comment by depler** [comment]
cursor.apk shows all files with any extension.  Opening ovpn file directly works despite the fact that file explorer suggest some categories first (like images, audio etc) - I can choose any category and then select OpenVPN app to open and import profile. Strange world...

**Comment by schwabe** [comment]
what mime_type does cursor report if you try to open a ovpn file?

That file type is probably an oddity of the file explorer you are using.

**Comment by depler** [comment]
mime_type is "application/octet-stream". Is it correct?

**Comment by TurnOffNOD** [comment]
@depler The problem is that the ics-openvpn app only recognize .txt extension. Your can copy your openvpn configure file foobar.ovpn and rename to foobar.txt.

**Comment by schwabe** [comment]
You can now always use the app internal's file browser to workaround this issue (select under settings).

**Comment by lundq** [comment]
@schwabe does this also apply for android TV App? I cannot access the internal storage although the App has the right permission. Where would it be possible to use the internal file explorer under settings? I know this works since it works on certificate revoke options, but on import profile the Standard Android Browser does not let me browse files? Thanks for any guidance.

**Comment by schwabe** [comment]
@lundq yes. There is a setting in the general setting of the app "Use internal filebrowser" or similar.

**Comment by lundq** [comment]
@schwabe Sorry but I can't find anything there, should it be listed under "Application behaviour"? Im using Version 0.7.5 on a Nvidia Shield Android TV. Maybe there is a bug on my system. Really appreciate your help.

**Comment by lundq** [comment]
Here is what I have listed under settings:
Application behaviour:
  Show log window
  OpenVPN 3 Core
  Default VPN
  Connect on boot
  Clear allowed external apps
VPN behaviour:
  Use System proxy
  Reconnect on network change
  Pause VPN connection after screen off
  OpenSSL Crypto Speed test

No "use internal browser" unfortunately.

**Comment by lundq** [comment]
I was able to work around this issue by open the ovpn profile file from a file browser instead. Thanks for your work!

**Comment by http600** [comment]
> @lundq yes. There is a setting in the general setting of the app "Use internal filebrowser" or similar.

The same here, Latest version there is no such thing like 'Use Internal File Browser' or something, So the options are dynamically depends on System, right?

**Comment by schwabe** [comment]
With modern Android systems, implementing an internal file browser just does not work anymore, so this workaround is no longer available.
