### ISSUE TITLE
Automation of DisconnectVPN activity

### ISSUE THREAD

**Issue by cooperaj** [schwabe/ics-openvpn#591]
# General information
1. Android Version
6.0.1
2. Android Vendor/Custom ROM
Samsung
3. Device
S6 Edge+
4. Version of the app (version number/play store version/self built)
0.6.60 (play store)
 
# Description of the issue
 I've been playing around with 'Automate' from the app store. It's essentially a system automation tool with a really nice flowchart based UI. I followed the doc instructions to add a task that starts the VPN when certain conditions are met. It works brilliantly.

I figured I could just browse to the Disconnect activity and have that work for the opposite use case of my automation but when running I'm getting a "not exported for UID" error from Android. Is there a reason it's like this? Is it possible to open that activity up to 3rd party usage?

Thanks
Adam

**Comment by cooperaj** [comment]
I guess this is partially (all?) covered by #81

**Comment by schwabe** [comment]
No a widget would not use exposed activities. The reason for no function like that is that I don't want to allow arbitrary apps to control the vpn as it is a security risk.

**Comment by cooperaj** [comment]
Mmm, I guess I can see that. Unfortunately a network that I regularly connect to blocks the openvpn port (1194). I can kill the connection manually but then that defeats the point of automating my device. 

Is there a way to capture the originating application of a disconnect request? That way an app could be allowed to make changes?

**Comment by Zerqz** [comment]
I'm working on the same thing, making an Automate script that checks if I'm connected to my home WiFi, if I am, disables vpn, if I'm not, enables the vpn. 

I have the enable vpn part working by checking wifi ssid, then running shell command "am start -a android.intent.action.MAIN -n de.blinkt.openvpn/.LaunchVPN -e de.blinkt.openvpn.shortcutProfileName *MyProfileName*"

But I cant seem to find the shell command to disable the vpn, tried things like "de.blinkt.openvpn.shortcutDisconnect", "de.blinkt.openvpn.disconnect", ect, but can't seem to find one that works. 

Maybe a dev could let us know the command and that would resolve this issue? 

Edit: I should specify, for the time being I get around this issue by using the command "Kill App" = "OpenVPN for Android" It's a pretty sloppy way of handling it. But it has been working perfectly fine so far.

**Comment by schwabe** [comment]
Done by f014940abd99c372004e227f2e68f31820162731
