### ISSUE TITLE
 error: conflicting types for 'query_user_add'

### ISSUE THREAD

**Issue by toonvanstrijp** [schwabe/ics-openvpn#592]
Im following the instructions of the README.md but I get an error while compiling. (I'm using macOS Sierra) Hope you can help me to solve this issue

cc1plus: warning: command line option '-std=c99' is valid for C/ObjC but not for C++
[arm64-v8a] Compile        : openvpn <= compat-daemon.c
[arm64-v8a] Compile        : openvpn <= compat-dirname.c
[arm64-v8a] Compile        : openvpn <= compat-gettimeofday.c
[arm64-v8a] Compile        : openvpn <= compat-inet_ntop.c
[arm64-v8a] Compile        : openvpn <= compat-inet_pton.c
[arm64-v8a] Compile        : openvpn <= compat-lz4.c
[arm64-v8a] Compile        : openvpn <= base64.c
[arm64-v8a] Compile        : openvpn <= buffer.c
[arm64-v8a] Compile        : openvpn <= clinat.c
[arm64-v8a] Compile        : openvpn <= console.c
openvpn//src/openvpn/console.c:57:6: error: conflicting types for 'query_user_add'
 void query_user_add(char *prompt, size_t prompt_len,
      ^
In file included from openvpn//src/openvpn/console.c:34:0:
openvpn//src/openvpn/console.h:63:6: note: previous declaration of 'query_user_add' was here
 void query_user_add (char *prompt, size_t prompt_len,
      ^
make: *** [obj/local/arm64-v8a/objs/openvpn/src/openvpn/console.o] Error 1
make: *** Waiting for unfinished jobs....
bash-3.2$

**Comment by schwabe** [comment]
fixed by https://github.com/OpenVPN/openvpn/commit/35be7e0d556a6b76e30f1e7348319e9dedf829aa
