### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by toonvanstrijp** [schwabe/ics-openvpn#593]
I'm getting this when I try to compile it. I'm using the last version of the android NDK and a MacOS Sierra machine

openvpn//src/openvpn/init.c:1352: error: undefined reference to 'argv_new'
openvpn//src/openvpn/init.c:1354: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/init.c:1356: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/init.c:2243: error: undefined reference to 'tls_crypt_init_key'
openvpn//src/openvpn/init.c:2447: error: undefined reference to 'tls_crypt_adjust_frame_parameters'
openvpn//src/openvpn/lladdr.c:18: error: undefined reference to 'argv_new'
openvpn//src/openvpn/misc.c:120: error: undefined reference to 'argv_new'
openvpn//src/openvpn/misc.c:123: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/misc.c:124: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/misc.c:126: error: undefined reference to 'argv_msg'
openvpn//src/openvpn/misc.c:128: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/options.c:2837: error: undefined reference to 'argv_new'
openvpn//src/openvpn/options.c:2838: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/options.c:2854: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/options.c:2854: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/socket.c:2027: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/socket.c:2028: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/ssl.c:1374: error: undefined reference to 'tls_crypt_unwrap'
openvpn//src/openvpn/ssl.c:1326: error: undefined reference to 'tls_crypt_wrap'
openvpn//src/openvpn/ssl_verify.c:520: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/ssl_verify.c:522: error: undefined reference to 'argv_msg_prefix'
openvpn//src/openvpn/ssl_verify.c:991: error: undefined reference to 'argv_printf_cat'
[x86_64] Install        : libcrypto.so => libs/x86_64/libcrypto.so
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/options.o: In function `check_cmd_access':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/options.c:2837: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/options.c:2838: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/options.c:2854: undefined reference to `argv_reset'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/options.c:2854: undefined reference to `argv_reset'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/init.o: In function `do_init_crypto_tls':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:2447: undefined reference to `tls_crypt_adjust_frame_parameters'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/init.o: In function `do_init_crypto_tls_c1':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:2243: undefined reference to `tls_crypt_init_key'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/init.o: In function `do_route':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:1352: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:1354: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:1356: undefined reference to `argv_reset'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/lladdr.o: In function `set_lladdr':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/lladdr.c:18: undefined reference to `argv_new'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/misc.o: In function `run_up_down':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:120: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:123: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:124: undefined reference to `argv_printf_cat'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:126: undefined reference to `argv_msg'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:128: undefined reference to `argv_reset'
[x86_64] SharedLibrary  : libjbcrypto.so
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/route.o: In function `delete_route':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1945: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:2111: undefined reference to `argv_reset'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/route.o: In function `add_route':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1409: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1656: undefined reference to `argv_reset'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/route.o: In function `add_route_ipv6':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1684: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1933: undefined reference to `argv_reset'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/route.o: In function `delete_route_ipv6':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:2119: undefined reference to `argv_new'
[x86_64] SharedLibrary  : libopenvpn.so
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/socket.o: In function `link_socket_connection_initiated':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/socket.c:2073: undefined reference to `argv_new'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/socket.o: In function `ipchange_fmt':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/socket.c:2027: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/socket.c:2028: undefined reference to `argv_printf_cat'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/socket.o: In function `link_socket_connection_initiated':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/socket.c:2077: undefined reference to `argv_reset'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/ssl.o: In function `write_control_auth':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl.c:1326: undefined reference to `tls_crypt_wrap'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/ssl.o: In function `read_control_auth':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl.c:1374: undefined reference to `tls_crypt_unwrap'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/ssl_verify.o: In function `verify_cert_call_command':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:507: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:519: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:520: undefined reference to `argv_printf_cat'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:522: undefined reference to `argv_msg_prefix'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:532: undefined reference to `argv_reset'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:519: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:520: undefined reference to `argv_printf_cat'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:522: undefined reference to `argv_msg_prefix'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/ssl_verify.o: In function `verify_user_pass_script':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:947: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:990: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:991: undefined reference to `argv_printf_cat'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:1009: undefined reference to `argv_reset'
openvpn//src/openvpn/init.c:1352: error: undefined reference to 'argv_new'
openvpn//src/openvpn/init.c:1354: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/init.c:1356: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/init.c:2243: error: undefined reference to 'tls_crypt_init_key'
[x86_64] Install        : libopvpnutil.so => libs/x86_64/libopvpnutil.so
openvpn//src/openvpn/init.c:2447: error: undefined reference to 'tls_crypt_adjust_frame_parameters'
./obj/local/arm64-v8a/objs/openvpn/src/openvpn/tun.o: In function `do_ifconfig':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/tun.c:755: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/tun.c:1399: undefined reference to `argv_reset'
openvpn//src/openvpn/lladdr.c:18: error: undefined reference to 'argv_new'
openvpn//src/openvpn/misc.c:120: error: undefined reference to 'argv_new'
openvpn//src/openvpn/misc.c:123: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/misc.c:124: error: undefi[armeabi] Install        : libjbcrypto.so => libs/armeabi/libjbcrypto.so
ned reference to 'argv_printf_cat'
openvpn//src/openvpn/misc.c:126: error: undefined reference to 'argv_msg'
openvpn//src/openvpn/misc.c:128: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/options.c:2837: error: undefined reference to 'argv_new'
openvpn//src/openvpn/options.c:2838: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/options.c:2854: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/options.c:2854: error: undefined reference to 'argv_reset'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi/libopenvpn.so] Error 1
make: *** Waiting for unfinished jobs....
openvpn//src/openvpn/init.c:1352: error: undefined reference to 'argv_new'
openvpn//src/openvpn/init.c:1354: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/init.c:1356: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/init.c:2243: error: undefined reference to 'tls_crypt_init_key'
openvpn//src/openvpn/socket.c:2027: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/init.c:2447: error: undefined reference to 'tls_crypt_adjust_frame_parameters'
openvpn//src/openvpn/socket.c:2028: error: undefined reference to 'argv_printf_cat'
openvpopenvpn//src/openvpn/ssl.c:1374: error: undefined reference to 'tls_crypt_unwrap'
n//src/openvpn/lladdr.c:18: error: undefined reference to 'argv_new'
openvpn//src/openvpn/ssl.c:1326: error: undefined reference to 'tls_crypt_wrap'
openvpn//src/openvpn/misc.c:120: error: undefined reference to 'argv_new'
openvpn//src/openvpn/misc.c:123: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/misc.c:124: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/misc.c:126: error: undefined reference to 'argv_msg'
openvpn//src/openvpn/misc.c:128: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/ssl_verify.c:520: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/ssl_verify.c:522: error: undefined reference to 'argv_msg_prefix'
openvpn//src/openvpn/ssl_verify.c:991: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/options.c:2837: error: undefined reference to 'argv_new'
openvpn//src/openvpn/options.c:2838: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/options.c:2854: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/options.c:2854: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/socket.c:2027: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/socket.c:2028: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/ssl.c:1374: error: undefined reference to 'tls_crypt_unwrap'
openvpn//src/openvpn/ssl.c:1326: error: undefined reference to 'tls_crypt_wrap'
openvpn//src/openvpn/ssl_verify.c:520: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/ssl_verify.c:522: error: undefined reference to 'argv_msg_prefix'
openvpn//src/openvpn/ssl_verify.c:991: error: undefined reference to 'argv_printf_cat'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/x86/libopenvpn.so] Error 1
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/armeabi-v7a/libopenvpn.so] Error 1
openvpn//src/openvpn/init.c:1352: error: undefined reference to 'argv_new'
openvpn//src/openvpn/init.c:1354: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/init.c:1356: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/init.c:2243: error: undefined reference to 'tls_crypt_init_key'
openvpn//src/openvpn/init.c:2447: error: undefined reference to 'tls_crypt_adjust_frame_parameters'
openvpn//src/openvpn/lladdr.c:18: error: undefined reference to 'argv_new'
openvpn//src/openvpn/misc.c:120: error: undefined reference to 'argv_new'
openvpn//src/openvpn/misc.c:123: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/misc.c:124: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/misc.c:126: error: undefined reference to 'argv_msg'
openvpn//src/openvpn/misc.c:128: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/options.c:2837: error: undefined reference to 'argv_new'
openvpn//src/openvpn/options.c:2838: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/options.c:2854: error: undefined reference to 'argv_reset'
openvpn//src/openvpn/options.c:2854: error: undefined reference to 'argv_reset'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
openvpn//src/openvpn/socket.c:2027: error: undefined reference to 'argv_parse_cmd'
openvpn//src/openvpn/socket.c:2028: error: undefined reference to 'argv_printf_cat'
make: *** [obj/local/arm64-v8a/libopenvpn.so] Error 1
openvpn//src/openvpn/ssl.c:1374: error: undefined reference to 'tls_crypt_unwrap'
openvpn//src/openvpn/ssl.c:1326: error: undefined reference to 'tls_crypt_wrap'
openvpn//src/openvpn/ssl_verify.c:520: error: undefined reference to 'argv_printf_cat'
openvpn//src/openvpn/ssl_verify.c:522: error: undefined reference to 'argv_msg_prefix'
openvpn//src/openvpn/ssl_verify.c:991: error: undefined reference to 'argv_printf_cat'
./obj/local/mips/objs/openvpn/src/openvpn/init.o: In function `do_route':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:1352: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:1354: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:1356: undefined reference to `argv_reset'
./obj/local/mips/objs/openvpn/src/openvpn/init.o: In function `do_init_crypto_tls_c1':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:2243: undefined reference to `tls_crypt_init_key'
./obj/local/mips/objs/openvpn/src/openvpn/init.o: In function `do_init_crypto_tls':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/init.c:2447: undefined reference to `tls_crypt_adjust_frame_parameters'
./obj/local/mips/objs/openvpn/src/openvpn/lladdr.o: In function `set_lladdr':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/lladdr.c:18: undefined reference to `argv_new'
./obj/local/mips/objs/openvpn/src/openvpn/misc.o: In function `run_up_down':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:120: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:123: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:124: undefined reference to `argv_printf_cat'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:126: undefined reference to `argv_msg'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/misc.c:128: undefined reference to `argv_reset'
./obj/local/mips/objs/openvpn/src/openvpn/options.o: In function `check_cmd_access':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/options.c:2837: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/options.c:2838: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/options.c:2854: undefined reference to `argv_reset'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/options.c:2854: undefined reference to `argv_reset'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/options.c:2854: undefined reference to `argv_reset'
./obj/local/mips/objs/openvpn/src/openvpn/route.o: In function `delete_route':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1945: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:2111: undefined reference to `argv_reset'
./obj/local/mips/objs/openvpn/src/openvpn/route.o: In function `add_route':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1409: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1656: undefined reference to `argv_reset'
./obj/local/mips/objs/openvpn/src/openvpn/route.o: In function `delete_route_ipv6':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:2119: undefined reference to `argv_new'
./obj/local/mips/objs/openvpn/src/openvpn/route.o: In function `add_route_ipv6':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1684: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/route.c:1933: undefined reference to `argv_reset'
./obj/local/mips/objs/openvpn/src/openvpn/socket.o: In function `link_socket_connection_initiated':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/socket.c:2073: undefined reference to `argv_new'
./obj/local/mips/objs/openvpn/src/openvpn/socket.o: In function `ipchange_fmt':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/socket.c:2027: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/socket.c:2028: undefined reference to `argv_printf_cat'
./obj/local/mips/objs/openvpn/src/openvpn/socket.o: In function `link_socket_connection_initiated':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/socket.c:2077: undefined reference to `argv_reset'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
./obj/local/mips/objs/openvpn/src/openvpn/ssl.o: In function `read_control_auth':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl.c:1374: undefined reference to `tls_crypt_unwrap'
./obj/local/mips/objs/openvpn/src/openvpn/ssl.o: In function `write_control_auth':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl.c:1326: undefined reference to `tls_crypt_wrap'
make: *** [obj/local/x86_64/libopenvpn.so] Error 1
./obj/local/mips/objs/openvpn/src/openvpn/ssl_verify.o: In function `verify_cert_call_command':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:507: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:519: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:520: undefined reference to `argv_printf_cat'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:522: undefined reference to `argv_msg_prefix'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:532: undefined reference to `argv_reset'
./obj/local/mips/objs/openvpn/src/openvpn/ssl_verify.o: In function `verify_user_pass_script':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:947: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:990: undefined reference to `argv_parse_cmd'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:991: undefined reference to `argv_printf_cat'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/ssl_verify.c:1009: undefined reference to `argv_reset'
./obj/local/mips/objs/openvpn/src/openvpn/tun.o: In function `do_ifconfig':
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/tun.c:755: undefined reference to `argv_new'
/Users/toonvanstrijp/Desktop/ics-openvpn-master/main/openvpn//src/openvpn/tun.c:1399: undefined reference to `argv_reset'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/mips/libopenvpn.so] Error 1
bash-3.2$

**Comment by schwabe** [comment]
If you modify openvpn version yourself also modify the build files. Current master is also experimental code. For something stable go back to the last tagged version and android ndk r12.

**Comment by toonvanstrijp** [comment]
I'm using now the ndk r12 and also the last tagged version but still getting this error:

`openssl/crypto/arm64cpuid.S:4:1: error: unknown directive
.arch armv8-a+crypto
^
openssl/crypto/arm64cpuid.S:24:2: error: instruction requires: crypto
 aese v0.16b, v0.16b
 ^
openssl/crypto/arm64cpuid.S:31:2: error: instruction requires: crypto
 sha1h s0, s0
 ^
openssl/crypto/arm64cpuid.S:38:2: error: instruction requires: crypto
 sha256su0 v0.4s, v0.4s
 ^
openssl/crypto/arm64cpuid.S:44:2: error: instruction requires: crypto
 pmull v0.1q, v0.1d, v0.1d
 ^
make: *** [obj/local/arm64-v8a/objs/crypto/crypto/arm64cpuid.o] Error 1
make: *** Waiting for unfinished jobs....
`

**Comment by schwabe** [comment]
that still looks like you trying to compile with clang. ndk r12 has gcc as default.

**Comment by toonvanstrijp** [comment]
@schwabe how can I set it to gcc? Cause what I do now is download the r12 NDK en place it in the ~/Android/sdk/ndk-bundle folder

**Comment by schwabe** [comment]
The application.mk should automatically do that. If you leave adventorous and want to compile with ndk13/clang you can also use the latest icsopenvpn branch in my openvpn repo
