### ISSUE TITLE
OpenVPN Stopped

### ISSUE THREAD

**Issue by saaiful** [schwabe/ics-openvpn#594]
# General information
1. 6.0.1
2. CM 13.1.2
3. Oneplus One
4. Version of the app (self built)
 
# Description of the issue
I build 'ics-OpenVPN'' using Android studio, after installing while I try to connect using '.ovpn' file it shows "Unfortunately, OpenVPN for Android has stopped." I tried installing apk from readme , It works, But my build is not working, why it's happing and how to make it work ?

**Comment by schwabe** [comment]
See the other closed issues
