### ISSUE TITLE
Can't select TLS Auth file on USB storage

### ISSUE THREAD

**Issue by mvglasow** [schwabe/ics-openvpn#595]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
6.0.1

2. Android Vendor/Custom ROM
Cyanogenmod 13.0-20160819-SNAPSHOT-ZNH5YAO0IN-bacon

3. Device
OnePlus One

4. Version of the app (version number/play store version/self built)
0.6.60, installed via F-Droid
 
# Description of the issue
My OpenVPN gateway uses TLS Authentication, for which I need a TLS Auth file in addition to the certificate chain. I placed that file (named statickey.pem) on a USB stick and plugged it into my phone. Then, in the connection settings, under Authentication/Encryption, I tapped TLS Auth File and chose USB storage, bringing up the native Android file manager UI. However, the file containing the static key was grayed out and I could not select it. Using a different file manager also didn't work because regular apps (including 3rd party file managers) can't access USB storage, and I didn't find a way to give the file picker root access.

My workaround was to copy the file from the USB stick to shared storage (using Cynogenmod's File Manager as root) and select it with a regular file manager app. After that (and once I figured out the other settings I needed), the connection worked.

IMHO, the bug is that a perfectly good static key file is not selectable in the on-board file UI. Relaxing the criteria for acceptable files would probably help here.

Apart from that, thanks for a much-needed app!

**Comment by schwabe** [comment]
It probably has the wrong mime type.

**Comment by mvglasow** [comment]
The file is on a FAT formatted device, which AFAIK has no support for MIME types in the metadata. Unless I’m missing something, all would thus depend on Android determining the file type correctly—or can I influence that in any way?

What MIME type does the OpenVPN app expect/request from the file picker?
