### ISSUE TITLE
(self built) app freeze  first time run but work ok  after reopen

### ISSUE THREAD

**Issue by lr2bmail** [schwabe/ics-openvpn#596]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
4.4-6.0-7.1
2. Android Vendor/Custom ROM
emulated -Samsung
3. Device
emulated  , s6  and  i9070 
4. Version of the app (version number/play store version/self built)
 0.6.60 (self built)

# Description of the issue

 (self built) android Studio 2.2.2  + win7 

i built apk  but after install  and run  app freeze  with empty screen   and if i touch the screen i get 
 

```
I/art: Thread[3,tid=11310,WaitingInMainSignalCatcherLoop,Thread*=0x9e149e00,peer=0x12c9a8b0,"Signal Catcher"]: reacting to signal 3
I/art: Wrote stack traces to '/data/anr/traces.txt'
```
i close it and open again and it work ok 

* if i edit ".core.ICSOpenVPNApplication" and remove "mStatus.init(getApplicationContext());" app do not freeze  with first run

* i try http://plai.de/android/ics-openvpn-0.6.60.apk  it work without problem 

Do you have any idea what could be causing this problem in my built ?

**Comment by schwabe** [comment]
the current master is unstable and in middle of refactoring and that is expected to be broken. Use tag 0.6.60 for now. The method you mentioned does not exist in 0.6.60
