### ISSUE TITLE
how to start OpenVPN for Android via SSH command line

### ISSUE THREAD

**Issue by jamaroney** [schwabe/ics-openvpn#597]
1. Android Version - 5.1.1
2. Android Vendor/Custom ROM - ??
3. Device - MXQ Pro Media Player
4. Version of the app - 0.6.60
 
I have the app set to auto-start on boot up. However, on rare occasion, the VPN connection drops out. Is there a simple command I can use to get it (re)started via SSH?

I tried "su am start -a android.intent.action.MAIN -n de.blinkt.openvpn/.LaunchVPN -e de.blinkt.openvpn.shortcutProfileName Home" with no luck

**Comment by jamaroney** [comment]
Figured it out on my own. Instead of "Home" at the end of the command, I had enter my config title (for me, it's "openvpn-us").

Also, I had to enter "su" first, and then the rest of the command. Putting both together in one command did nothing.

**Comment by NaZavtrack** [comment]
> 
> 1. Android Version - 5.1.1
> 2. Android Vendor/Custom ROM - ??
> 3. Device - MXQ Pro Media Player
> 4. Version of the app - 0.6.60
>  
> I have the app set to auto-start on boot up. However, on rare occasion, the VPN connection drops out. Is there a simple command I can use to get it (re)started via SSH?
> 
> I tried "su am start -a android.intent.action.MAIN -n de.blinkt.openvpn/.LaunchVPN -e de.blinkt.openvpn.shortcutProfileName Home" with no luck
>  
>  
>  
>

**Comment by schwabe** [comment]
See README.md
