### ISSUE TITLE
Unrecognised option or missing or extra parameters (...)

### ISSUE THREAD

**Issue by giacecco** [schwabe/ics-openvpn#599]
# General information
1. Android Version
6.0.1

2. Android Vendor/Custom ROM
Samsung , build no. MMB29K.G935FXXU1BPJG

3. Device
Samsung S7 Edge

4. Version of the app (version number/play store version/self built)
 0.6.60

# Description of the issue
Whatever settings I try, the app always gives me the error in the screenshot below:

![screenshot_20161213-092812](https://cloud.githubusercontent.com/assets/303693/21134655/ca841798-c116-11e6-8bf7-844921a02776.png)

**Comment by schwabe** [comment]
Your config file is probably wrong. Either fix it or if you think that is file is indeed okay forward a copy to me so I can take a look
