### ISSUE TITLE
OpenVPN won't connect in Android v6.0.1

### ISSUE THREAD

**Issue by thecodeflash** [schwabe/ics-openvpn#600]
OpenVPN won't connect on Android v6.0.1

# General information
1. Android Version - Android v6.0.1
2. Android Vendor/Custom ROM - Android Stock ROM (Samsung)
3. Device - Samsung Note 5
4. Version of the app (version number/play store version/self built) - Tested on built from source code and from PlayStore both
 
# Description of the issue
 
Whenever I try to connect it wouldn't connect in android v6.0.1 but it was working in other versions of Android.

Please help me out Sir.

Thank You.
 
Regards,
Vishwajeet Srivastava

**Comment by schwabe** [comment]
Can you provide the logfile from the app?

**Comment by StuartIanNaylor** [comment]
OpenVPN for Android connects for me with v6.0.1
