### ISSUE TITLE
Build NDK on windows -- failed

### ISSUE THREAD

**Issue by bibleboy** [schwabe/ics-openvpn#601]
This project is not support to build ndk on windows.
I try to build ndk on windows (Android Studio 2.2.2) but failed with error: make (e=206): The filename or extension is too long.
I guess the root cause is "Windows command length limit", but I don't know how to fix this or it can not be fixed actually. Is anyone could give some tips/suggestions?

**Comment by schwabe** [comment]
I never managed building the ndk part on windows. Just copy it from a Unix box or from my apks

**Comment by bibleboy** [comment]
I am trying to build on Linux. thanks!

**Comment by bibleboy** [comment]
I am trying to build on Linux. thanks!
