### ISSUE TITLE
App not excluded from vpn

### ISSUE THREAD

**Issue by StuartIanNaylor** [schwabe/ics-openvpn#602]
1. Android Version 6.01
2. Android Vendor/Custom ROM Freaktab rom
3. Device Beelink GT1
4. Version of the app (version number/play store version/self built) .0.6.63
 
# Description of the issue

Droidmote server is excluded but as soon as the VPN is connected the IP shifts from local subnet to VPN assigned of the Tun.

Just wondering as Chromecast and things must be the same, if you want them to be excluded and still be part of the dhcp subnet what settings do you need.

PS I enabled LZO compression but that just gave errors in the log, wich I disabled but thought would mention it whilst here.

Cheers Arne, great bit of software and prob the issue is me :)

**Comment by schwabe** [comment]
there is an option to exclude local subnets. How did you really test that the app is not excluded? What the app displays itself might be wrong.

**Comment by StuartIanNaylor** [comment]
Yeah I tried that and also selected that app to be excluded, soon as the VPN is run the IP switches to the Tun IP so droidmote clients can not find the server.
You lose connection as well as the visible display of IP change.

https://developer.android.com/reference/android/net/VpnService.Builder.html#addDisallowedApplication(java.lang.String)

Yeah I expected it to be simple where you just exclude it, but the setting seems to not make any difference.

I turned up the logging and can see the dissallowedapplication entry so its wither 6.01 or my Rom, so going to post on the forums at freaktab.com as they are far ahead of the manufacturers bee-link and see if they can come up with anthing as it would seem to be the framework.

**Comment by StuartIanNaylor** [comment]
Arne ignore me as got it working and it was just me with the dhcp giving me another ip, droid mote shows the tun address but listens on all devices and when I finally checked the current ip settings all went well.

I have been using slickvpn with your excellent offering and ipvanish and there inferior client offering so things all got a bit muddled.

Apols for the bum steer.
