### ISSUE TITLE
Openvpn licence for commercial use + steps to build ndk in Lunix

### ISSUE THREAD

**Issue by ZaherZohbi** [schwabe/ics-openvpn#603]
# General information
1. Android Version
**Any version**
2. Android Vendor/Custom ROM

3. Device
**Any Device**
4. Version of the app (version number/play store version/self built)
 **Version 0.6.63**

# Description of the issue

Hello,

We are a seeking to open a commercial company and we are seeking to integrate OpenVPN in our application.
Is there any licence needed or agreement to be done in order to be legitimate for using your open source code?

How to build the ndk in Lunix? and how to Fetch the git submodules  (git submodule init,  git submodule update) mentioned in the readme? in fact where are the git submodules located?

**Comment by schwabe** [comment]
If you opensource your application to the terms of the GPL2 you need no extra license. If you don't want to opensource it, contact me via email for a commercial license.

fetchting the git submouldes is standard git stuff. The ndk is something you download from google.

**Comment by ZaherZohbi** [comment]
kindly could you provide me your email
my email is zaher.zohbi@hotmail.com

**Comment by schwabe** [comment]
arne@rfc2549.org (it is not hard to find)
