### ISSUE TITLE
Error on running

### ISSUE THREAD

**Issue by vutrulavotann** [schwabe/ics-openvpn#605]
Hi Schwabe,

Thank you for your work on ics-openvpn.
I get your code and try to run but I got NativeUtils.getNativeAPI() is not implemented.
Please tell me what's wrong with me.
I use Android 6.0.1 on samsung galaxy S7

Kind regards,
Son

**Comment by schwabe** [comment]
Duplicate of other issues. You need to compile native like described in doc/README.

**Comment by vutrulavotann** [comment]
Thanks, I use windows so I extract openvpnlibs from apk then copied to main folder. But I still got that message. Please tell me what should I do

**Comment by schwabe** [comment]
then you probably copied them to the wrong folder. should look like this

```
main/ovpnlibs
main/ovpnlibs/assets
main/ovpnlibs/assets/nopie_openvpn.arm64-v8a
main/ovpnlibs/assets/nopie_openvpn.armeabi
main/ovpnlibs/assets/nopie_openvpn.armeabi-v7a
main/ovpnlibs/assets/nopie_openvpn.mips
main/ovpnlibs/assets/nopie_openvpn.x86
main/ovpnlibs/assets/nopie_openvpn.x86_64
main/ovpnlibs/assets/pie_openvpn.arm64-v8a
main/ovpnlibs/assets/pie_openvpn.armeabi
main/ovpnlibs/assets/pie_openvpn.armeabi-v7a
main/ovpnlibs/assets/pie_openvpn.mips
main/ovpnlibs/assets/pie_openvpn.x86
main/ovpnlibs/assets/pie_openvpn.x86_64
main/ovpnlibs/jniLibs
main/ovpnlibs/jniLibs/arm64-v8a
main/ovpnlibs/jniLibs/arm64-v8a/libjbcrypto.so
main/ovpnlibs/jniLibs/arm64-v8a/libopenvpn.so
main/ovpnlibs/jniLibs/arm64-v8a/libopvpnutil.so
main/ovpnlibs/jniLibs/armeabi
main/ovpnlibs/jniLibs/armeabi/libjbcrypto.so
main/ovpnlibs/jniLibs/armeabi/libopenvpn.so
main/ovpnlibs/jniLibs/armeabi/libopvpnutil.so
main/ovpnlibs/jniLibs/armeabi-v7a
main/ovpnlibs/jniLibs/armeabi-v7a/libjbcrypto.so
main/ovpnlibs/jniLibs/armeabi-v7a/libopenvpn.so
main/ovpnlibs/jniLibs/armeabi-v7a/libopvpnutil.so
main/ovpnlibs/jniLibs/mips
main/ovpnlibs/jniLibs/mips/libjbcrypto.so
main/ovpnlibs/jniLibs/mips/libopenvpn.so
main/ovpnlibs/jniLibs/mips/libopvpnutil.so
main/ovpnlibs/jniLibs/x86
main/ovpnlibs/jniLibs/x86/libjbcrypto.so
main/ovpnlibs/jniLibs/x86/libopenvpn.so
main/ovpnlibs/jniLibs/x86/libopvpnutil.so
main/ovpnlibs/jniLibs/x86_64
main/ovpnlibs/jniLibs/x86_64/libjbcrypto.so
main/ovpnlibs/jniLibs/x86_64/libopenvpn.so
main/ovpnlibs/jniLibs/x86_64/libopvpnutil.so
```

**Comment by vutrulavotann** [comment]
Thank you, let's me check

**Comment by vutrulavotann** [comment]
Thank you, it works 👍

**Comment by codemajor247** [comment]
dear 

> then you probably copied them to the wrong folder. should look like this
> 
> ```
> main/ovpnlibs
> main/ovpnlibs/assets
> main/ovpnlibs/assets/nopie_openvpn.arm64-v8a
> main/ovpnlibs/assets/nopie_openvpn.armeabi
> main/ovpnlibs/assets/nopie_openvpn.armeabi-v7a
> main/ovpnlibs/assets/nopie_openvpn.mips
> main/ovpnlibs/assets/nopie_openvpn.x86
> main/ovpnlibs/assets/nopie_openvpn.x86_64
> main/ovpnlibs/assets/pie_openvpn.arm64-v8a
> main/ovpnlibs/assets/pie_openvpn.armeabi
> main/ovpnlibs/assets/pie_openvpn.armeabi-v7a
> main/ovpnlibs/assets/pie_openvpn.mips
> main/ovpnlibs/assets/pie_openvpn.x86
> main/ovpnlibs/assets/pie_openvpn.x86_64
> main/ovpnlibs/jniLibs
> main/ovpnlibs/jniLibs/arm64-v8a
> main/ovpnlibs/jniLibs/arm64-v8a/libjbcrypto.so
> main/ovpnlibs/jniLibs/arm64-v8a/libopenvpn.so
> main/ovpnlibs/jniLibs/arm64-v8a/libopvpnutil.so
> main/ovpnlibs/jniLibs/armeabi
> main/ovpnlibs/jniLibs/armeabi/libjbcrypto.so
> main/ovpnlibs/jniLibs/armeabi/libopenvpn.so
> main/ovpnlibs/jniLibs/armeabi/libopvpnutil.so
> main/ovpnlibs/jniLibs/armeabi-v7a
> main/ovpnlibs/jniLibs/armeabi-v7a/libjbcrypto.so
> main/ovpnlibs/jniLibs/armeabi-v7a/libopenvpn.so
> main/ovpnlibs/jniLibs/armeabi-v7a/libopvpnutil.so
> main/ovpnlibs/jniLibs/mips
> main/ovpnlibs/jniLibs/mips/libjbcrypto.so
> main/ovpnlibs/jniLibs/mips/libopenvpn.so
> main/ovpnlibs/jniLibs/mips/libopvpnutil.so
> main/ovpnlibs/jniLibs/x86
> main/ovpnlibs/jniLibs/x86/libjbcrypto.so
> main/ovpnlibs/jniLibs/x86/libopenvpn.so
> main/ovpnlibs/jniLibs/x86/libopvpnutil.so
> main/ovpnlibs/jniLibs/x86_64
> main/ovpnlibs/jniLibs/x86_64/libjbcrypto.so
> main/ovpnlibs/jniLibs/x86_64/libopenvpn.so
> main/ovpnlibs/jniLibs/x86_64/libopvpnutil.so
> ```

dear schwabe

where is forlders ? how can find this files to copy ?
