### ISSUE TITLE
Can't configure quick settings tile

### ISSUE THREAD

**Issue by raku-cat** [schwabe/ics-openvpn#606]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. 7.1.1
2. OctOS-N
3. Nexus 6P
4. 0.6.63
 
# Description of the issue
 
The quick settings tile just stays as "no VPN selected" and you can't chose the profile it toggles.

**Comment by schwabe** [comment]
You can configure it under general settings of the app.

**Comment by raku-cat** [comment]
Not finding that anywhere https://puu.sh/taRWl/66b7bffc7e.png

**Comment by schwabe** [comment]
hm I might need to change the title. It is the always on and boot vpn profile setting

**Comment by raku-cat** [comment]
That setting does it, thanks. I'll leave this open I guess.

**Comment by raku-cat** [comment]
Hmm, the selected profile clears out, I can't find much pattern but every I'd say half hour it clears the selected profile.

**Comment by schwabe** [comment]
That bug should be fixed now. Please report if it isn't
