### ISSUE TITLE
Getting OpenVPN profile list / Disconnect intent

### ISSUE THREAD

**Issue by DavidVentura** [schwabe/ics-openvpn#607]
Hi, I'm developing a free software 'Tasker', I'd like to be able to get OpenVPN profile list in some way, as I need the profile name to actually start the vpn from the exposed intent.

Also, I've noticed on an old issue (#81) that you don't want to expose th 'Disconnect' functionality. Why? Tasker with the OpenVPN plugin can already stop the VPN connection, I don't see how this would expose 'more'

**Comment by schwabe** [comment]
I don't want random apps to be able to disconnect the VPN. I don't know Tasker and how it works. OpenVPN for Android currently has a full remote control API with AIDL  (https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/aidl/de/blinkt/openvpn/api/IOpenVPNAPIService.aidl) and also an example how to use it (https://github.com/schwabe/ics-openvpn/tree/master/remoteExample)

I don't know if that is something that tasker can use

**Comment by DavidVentura** [comment]
I can make this work, thanks, I don't know how I missed it

**Comment by DavidVentura** [comment]
Before doing this, as I've seen mentioned on multiple places the 'need' for this feature, would you consider adding the intent to disconnect / list vpns, but only enabled behind an 'unsafe' switch (disabled by default)? So there's no way it'd affect people who don't need it, to automate this (and develop a free alternative) I had to end up using a closed source app + plugin (tasker, openvpn tasker plugin), which are the only closed source apps on my phone. This seems like a better alternative

**Comment by jonathantelling** [comment]
@schwabe I have to agree with @DavidVentura that this would be a nice feature. I like to automate my phone and disconnecting the VPN when I'm on a trusted WIFI would be nice. 
Correct me if I'm wrong, but do you need root access to use OpenVPN's API?

**Comment by mesterj** [comment]
+1 for disconnect intent

**Comment by trial-n-error** [comment]
Important feature for me too.

**Comment by schwabe** [comment]
Duplicate of #591
