### ISSUE TITLE
IPV6 DNS fails on networks without native IPV6

### ISSUE THREAD

**Issue by epilsits** [schwabe/ics-openvpn#609]
# General information
1. Android Version - 7.1.1
2. Android Vendor/Custom ROM - stock, no root
3. Device - Pixel on AT&T
4. Version of the app (version number/play store version/self built) - 0.6.63
 
# Description of the issue
I'll start by saying my configuration was working on previous versions of OpenVPN for Android, and it works currently when connected over LTE data.

What I'm seeing is a failure on IPV6 test sites ipv6-test.com and test-ipv6.com in Chrome (I have DISabled Data Saver so there's no Google proxy), when connected to WiFi at work. Specifically, test-ipv6.com says "IPv6 connections work, but connections using DNS names do not use IPv6. We detected that you are able to connect to IPv6 sites, by numerical address specifically. However, connections using DNS either failed, or preferred IPv4." These same test sites work correctly when I'm connected to LTE.

One difference I can think of is that my WiFi at work does NOT have native IPV6 (only link local), while LTE data does. Perhaps this has something to do with the introduction of IPV6 DNS support? My server is setup to only issue an IPV4 DNS server, but the server supports both IPV4 and IPV6 name resolution (as evidenced by successful tests over LTE). This might even be a bug in OpenVPN itself...

Here's my server config if it helps:
```
lport xxx
proto udp

dev tun
dh /etc/openvpn/dh2048.pem
ca /etc/openvpn/ca.crt
cert /etc/openvpn/server.crt
key /etc/openvpn/server.key
tls-auth /etc/openvpn/ta.key 0

topology subnet
server 192.168.xxx.xxx 255.255.255.240
ifconfig-pool-persist /etc/openvpn/ipp_2
push "route 192.168.xxx.xxx 255.255.255.0"
push "redirect-gateway def1 bypass-dhcp"
push "dhcp-option DNS 192.168.xxx.xxx"
push "dhcp-option WINS 192.168.xxx.yyy"
push "dhcp-option DOMAIN home.lan"
client-to-client
keepalive 60 120

server-ipv6 xxxx:yyyy:zzzz:aaaa:bbbb:cccc:d::/112
push "route-ipv6 2000::/3"

cipher AES-128-CBC
tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA
comp-lzo adaptive
max-clients 10

persist-key
persist-tun
verb 3
mute-replay-warnings
mute 5
```

Just to reiterate, this used to work perfectly on my work WiFi. I had full IPV6 connectivity over the tunnel, even though there is no IPV6 support on our network. I tried pushing a DNS6 server as a test, but that did not work.

Please let me know if you need any further information.

**Comment by schwabe** [comment]
Can you also provide a log from the app?

**Comment by epilsits** [comment]
I will send a log when I'm back at work tomorrow.

Is there any way to privately send you a password for the log file archive, so I don't have to redact it all?

**Comment by aminbolehvpn** [comment]
This is the same issue that I am having but client is OSX. It seems that
the dhcp option DNS6 is working on windows client only. In
Linux/OSX/Android, dns lookup will fail if only dns6 is push from the
server. Should I raise this issue in the main openvpn?

Thank you.

**Comment by schwabe** [comment]
DNS6 is working fine on my Android device. For OSX/Linux the resolvconf/whatever script needs to be adapted to also pick up DNS6 options. No need to file a issue with openvpn itself

You can send the logfile to arne-openvpn@rfc2549.org

**Comment by aminbolehvpn** [comment]
After further testing, this is what I can summarized and correct me if I am
wrong:

Client (Non-Windows) requirement.
1. All Client MUST have a valid IPv6 addressed configured by their ISP
(manually configured if you are not able to get the IP from your router) on
the public NIC (en0, eth0 etc) connecting to the server
2. If you meet the above criteria (1) then IPv6 DNS push by the server will
be retained and used by the browsers.
3. If you do not meet criteria 1, the DNS6 will not be used by the browsers
and you will fail the ipv6 test. Visiting RIPE at ripe.com will revert to
your IPv4 address.

You can repeat this test by removing your IPv6 addresses given by your ISP.

Thank you

**Comment by schwabe** [comment]
My Pixel C/Android 7.1.1 works with IPv4 native and dual stack IPv4/IPv6 OpenVPN + DNS6 just fine. Older/other Android might be more buggy in the regard of IPv6 DNS server.

**Comment by aminbolehvpn** [comment]
As I said, this is the same behavior I am facing on OSX or Linux. After
further testing, DNS6 will fail the ipv6 test on safari and firefox but
passed the test on Chrome. So this maybe a false positive due different
support of the browser. I will be opening my dual stack server for beta
testing to my users and will provide update on the different OS and browser
combination.

Thank you Arne

**Comment by schwabe** [comment]
Behaviour of Android itself might be  a bit erratic. Sometimes my devices prefer v4 dns for no appearent reason but I don't think that the app can do anything else than setting the DNS server. 

"IPv6 connections work, but connections using DNS names do not use IPv6" sound like a DNS server issue that the DNS is not returning AAAA addresses.

**Comment by epilsits** [comment]
My situation is a bit different. Success of the tests depends on the network I'm connected to before connecting to OpenVPN. If the network gives me an IPv6 address, like LTE, then the tests succeed on my dual stack OpenVPN server. If I do not get an IPv6 address, like my work wifi, then the tests fail.

Previous version of OpenVPN for Android did not have this problem. Unfortunately I haven't been able to roll back to test, as all the APKs I've tried say "corrupt package" when trying to install.

I'll get those logs for you a bit later this morning.

**Comment by epilsits** [comment]
And this all used to work successfully without a DNS6 server at all, only an IPv4 DNS address. My DNS server, local Unbound server, returns AAAA records from its IPv4 interface.

**Comment by schwabe** [comment]
@epilsits The current version is the first version that actually use DNS6. With previous version you never got an DNS6 server since it never set a DNS6 server.

So the new version's ability to set a DNS6 server is probably exposing same weird Android bug.

**Comment by epilsits** [comment]
Logs sent.

**Comment by schwabe** [comment]
Discussion ocntinued via email. This is a bug of Android 7.0+

**Comment by lsowen** [comment]
@schwabe I think I'm running into the same issue, so I'm curious what was the outcome of this investigation?  Is there a workaround (eg with some strange configuration either on the device or the DNS server), or are we out of luck?

**Comment by schwabe** [comment]
Wait for google to fix this: https://issuetracker.google.com/issues/36504585
