### ISSUE TITLE
Unauthorized OpenVPN API Caller after update

### ISSUE THREAD

**Issue by macdonaldj** [schwabe/ics-openvpn#610]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. 6.0
3. nexus 5
4. 0.6.63
 
# Description of the issue
After getting the prompt to confirm permissions, I am getting the error "Unauthorized OpenVPN API Caller". After I get the result_ok from the confirm dialog, I go to register the callback service for status and get the unauthorized error. After the error, I check the allowed apps and see my app in the list. This used to work.. I even uninstalled the app and reinstalled. Thoughts? 

This started happening after the latest update.

**Comment by schwabe** [comment]
No need to report that twice. I already replied to your last message (Fixed in 0.6.64)

**Comment by macdonaldj** [comment]
ahh.,  missed that! thanks!
