### ISSUE TITLE
Android 7 Issue

### ISSUE THREAD

**Issue by arun2** [schwabe/ics-openvpn#617]
Dear Developer:  In Android 7 devices I am getting following Error messages. There is no error message in log ..But This message is coming from  Android OS itself  in popup box. Though VPN working fine.

Android showing this message: 

> libopvpnutil.so unauthorized access to libcrypto.so

 ( It is statically linked though  ).  Can you please focus some light on it .

Thank you

**Comment by schwabe** [comment]
I need more information. What device. Did you build it yourself? Maybe a screenshot of the message box.

**Comment by arun2** [comment]
Ya..  I  have built it . Output contains " 2 files libopenvpn.so  and libopvpnutil.so" ( OpenSSL statically linked ). Working in all versions of Android starting from 4.   I am using Nexus 6P  ( Android N latest ) and working fine but the message box is coming 
Please check this image. Thanks
![oa](https://cloud.githubusercontent.com/assets/5250840/22407577/f2f14526-e61d-11e6-87c8-e5fe8ad3bc6e.png)

**Comment by schwabe** [comment]
@arun2 is that current master? Or what version is that?

I think I know the reason for this. My hypothesis that you forked my source code a long time ago and now seeing bugs that got fixed a long time but only now with 7.1 the system gives you a warning about that.

**Comment by andiwulan** [comment]
Thank you for master schwabe and master @arun2...please forgif me if make two master come very busy cause of what i need to do.
But now I will learn about this more and more...
LET ME FOLLOW what will happened yet with your two master give for what should I must to do.
Thanx bro

**Comment by arun2** [comment]
Thanks.Yes. It is very old code base.. I will try latest code ..If  issue not fixed I will message here. Thank you
