### ISSUE TITLE
iOS App Consulting 

### ISSUE THREAD

**Issue by yegors** [schwabe/ics-openvpn#621]
Hi Arne, 

Sorry to post this here but I failed to find your direct email address. 

Are you available to do some consulting work to implement OpenVPN in an iOS app? If so, can you contact me at yegor@windscribe.com or provide me your email address?

Thanks

**Comment by schwabe** [comment]
Implementing OpenVPN for iOS is major thing, see also https://github.com/OpenVPN/openvpn3/issues/1
