### ISSUE TITLE
NDK build doesn't work. Missing file build-host-executable.mk

### ISSUE THREAD

**Issue by TrueBers** [schwabe/ics-openvpn#622]
After cloning the repo, updating the modules and running `./misc/build-native.sh` I get an error:  `openssl/Apps.mk:22: /home/bers/Android/Sdk/ndk-bundle/build/core/build-host-executable.mk: No such file or directory`
`make: *** No rule to make target '/home/bers/Android/Sdk/ndk-bundle/build/core/build-host-executable.mk'.  Stop.`

It seems there is no such file in the NDK directory.

Platform version is 25
Build tools: 25.0.2
NDK: 13.1.3345770
Studio: 2.2.3

So current NDK is not compatible? Which version should one use to build it?

**Comment by schwabe** [comment]
I am using NDK 13b which is the latest stable ndk from the download site.

**Comment by TrueBers** [comment]
Yes, I'm using the same version and it doesn't contain this file. I have also found [similar issue](https://marc.info/?l=strongswan-announce&m=141740030614953&w=1), [another one](https://github.com/cSploit/android/issues/37#issuecomment-143133034) and a [question](http://stackoverflow.com/questions/34609816/android-ndk-build-host-executable-mk-no-such-file-or-directory) on SO.

Maybe something else could cause such an error?

**Comment by schwabe** [comment]
The build files are not even using the build host directive. I am not sure where you are getting that error from.
