### ISSUE TITLE
option to vpn not todisconnecting on sleep

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#625]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version 5
2. Android Vendor/Custom ROM asus
3. Device asus zenfone 2
4. Version of the app (version number/play store version/self built) f-droid latest stable
 
# Description of the issue
 
 I have my energy policy set to have networking on while in sleep (normal and default) yet when screen goes off, vpn disconnects while network does not, I have to switch off the vpn to have networking working while screen is off.

**Comment by schwabe** [comment]
Please provide a logfile
