### ISSUE TITLE
Battery drains explanation

### ISSUE THREAD

**Issue by Almtesh** [schwabe/ics-openvpn#626]
A lot of users noticed that this application were on the top on battery consumsion.
I recommend you to put something clear about that somewhere people will see quickly.

I was surprised myself too, but I noticed something else, all the apps on my phone that can use VPN use less power than before.

**Comment by brunnre8** [comment]
It's in the faqs...

**Comment by schwabe** [comment]
yeah. I will just close this.

**Comment by Almtesh** [comment]
Sorry, was it already in the faq or did you just added it?

**Comment by schwabe** [comment]
has been there for over 2 years or longer.
