### ISSUE TITLE
Unable to reconnect to server if server IP has changed since last connection was established

### ISSUE THREAD

**Issue by craftyguy** [schwabe/ics-openvpn#627]
# General information
1. Android Version

7.1.1

2. Android Vendor/Custom ROM

CopperheadOS 

3. Device

Nexus5x

4. Version of the app (version number/play store version/self built)
 
0.6.64

# Description of the issue
 
 I have to rely on dynamic dns to map a domain name to my vpn server's (constantly) changing IP address. When I have been disconnected from said server, for example by a network change (wifi->cell, etc), the openvpn client will use the last IP that my domain name resolved to and does not query DNS for a new IP. This means that if the server's IP has changed, then the client will not succeed. If I hit "reconnect' or manually disconnect and then connect, it queries DNS and uses the correct IP.

**Comment by code-chicken** [comment]
I am having excactly the same problem:
Android Version: 7.1.1 (with all patches, original OS from Google)
Device: Nexus 5X

Just hitting "reconnect" retrieves the new IP and results in a successful connection. 

Wouldn't it make sense to have an option of an automatic reconnect after - let's say - 10 unsuccessfull connection retries or maybe some time like 3 minutes? Maybe there is already a similar option and I just can't find it.

**Comment by schwabe** [comment]
the client will only cache dns if persitent-tun is enabled. Otherwise it should query DNS on every connect, do you have persitent tun enabled?

**Comment by craftyguy** [comment]
I had persistent tun enabled, so I disabled it. It only sort of seems to work, and by that I mean that it'll fail to connect, the log fills with "connection refused" messages for a few minutes until "inactivity timeout" (due to --ping-restart), then it resolves the new IP and connects.

**Comment by PriceChild** [comment]
@schwabe Is it possible to disable DNS caching without disabling persistent-tun?

**Comment by schwabe** [comment]
No it is not possible since the client cannot do dns resolution when persist-tun is active.
