### ISSUE TITLE
Android7.0 has something wrong

### ISSUE THREAD

**Issue by Lyoona** [schwabe/ics-openvpn#630]
i find if the Android version is later than 7.0， the vpn with ipv6 can`t use a domain to get some data from a interface but IP，is there something wrong or i mistake something? Please take time to reply to me! very thanks

**Comment by schwabe** [comment]
THat seems to be a bug in android 7.0+ IPv6 works if your native connection also has ipv6 otherwise ipv6 is fishy and sometimes works and sometimes not.

**Comment by moviuro** [comment]
The issue seems to have been reported [upstream](https://issuetracker.google.com/issues/37135588) ([Among many other things](https://issuetracker.google.com/issues?q=IPv6%20VPN)).

It's frustrating :sob: no IPv6 internet on my device!

**Comment by schwabe** [comment]
Upstream bug, closing the issue.
