### ISSUE TITLE
application does not stay open in the background

### ISSUE THREAD

**Issue by bluedoo** [schwabe/ics-openvpn#631]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version: 5.0.1
2. Android Vendor/Custom ROM: Factory
3. Device: Huawei P8 Lite
4. Version of the app (version number/play store version/self built): 0.6.65 from Play Store with default settings, using Mullvad VPN factory imported settings
 
The application closes in various scenarios

1. When you press the square and swipe to close all apps, it closes the app in the background as well (Other background applications i.e. 3G watchdog stay open though)

2. If you connect and then click the button to make the phone sleep then return after about an hour, the application automatically closes and stops running in the background

3. If you connect and just leave the application to run in the background it automatically closes after some time of usage

**Comment by Babar-Bashir** [comment]
Settings (Battery Manager > Protected Apps) this allows elected apps to keep running after the screen is turned off.

**Comment by schwabe** [comment]
Please provide adb logcat or soemthing else. The application runs a foreground service and it should be closed and never seen this behaviour before.
