### ISSUE TITLE
Hi,how can i get a commercial  license of your source code?

### ISSUE THREAD

**Issue by MaskerJ** [schwabe/ics-openvpn#632]
Hello, I am a developer of Android, this time i want to develop a APP based on your openvpn code,but i found some problems when i use your no-commercial code.  I want to get a commercial  license, can you give me your email in order that we can chat  more clearly.By the way ,how much should I pay for you if I want to modify your code to build my own app?  
Thks a lot O(∩_∩)O

**Comment by schwabe** [comment]
contact me at arne-openvpn@rfc2549.org
