### ISSUE TITLE
SHA512 password missing one character on server

### ISSUE THREAD

**Issue by Bradley168** [schwabe/ics-openvpn#633]
The SHA512 password that the VPN App sends seems to be missing the last character. It should be 128 character long but only 127 characters are received by the openvpn server.

Is there a limit to the password length?

**Comment by Bradley168** [comment]
@schwabe i did it on Android.

**Comment by schwabe** [comment]
Yes, OpenVPN defines password length to be a maximum of 128 
#define USER_PASS_LEN 128

**Comment by Bradley168** [comment]
Thank you so much.
