### ISSUE TITLE
Can only see empty folders on Android 6.0.1 (MIUI Global 8.1)

### ISSUE THREAD

**Issue by wildeskraut** [schwabe/ics-openvpn#634]
I just tried to import a OVPN profile on my handset, but all I can see is the folder structure.
No contents.

All permissions to the USB memory of the phone are granted to this app, but all folders contain 0 files.
I created a new folder (with OpenVPN for Android) and copied the OpenVPN files there with a file explorer - same result, content is not visible.

**Comment by schwabe** [comment]
Phone/Android version etc?

**Comment by wildeskraut** [comment]
Phone: Redmi Note 3 Pro
Android version: Android 6.0.1 (MIUI Global 8.1)

**Comment by wildeskraut** [comment]
This is the end of the discussion?

**Comment by ro011110ot** [comment]
Same here 
Redmi Note 4 with Miui 8.2 show Folders but no files. 
Maybe it is possible to add a function that we can chose another explorer to import our files. 
Maybe Storage Access Framework (SAF).

**Comment by Yidadaa** [comment]
same issue on MIUI9.1 (Andriod 7.1).

**Comment by casper** [comment]
Same issue MIUI 8.5 Android 6.0.1. 

The interesting part is that the file dialog for "Certificate Revoke List" in the profile settings is different than all the other ones. That dialog does not look like the normal system dialog, and it also shows all files. 

All the other dialogs only show folders, and no files are available for selection in any of them.

**Comment by casper** [comment]
I was able to get around this problem by changing the import code for the conf file to this:

```
          case OVPN_CONFIG:
                supportedMimeTypes.add("application/x-pkcs7-crl");
                supportedMimeTypes.add("application/pkix-crl");
                extensions.add("crl");
```

As unintuitive as it seems, this one opens up the alternate file dialog, and I was able to import my conf file.

**Comment by casper** [comment]
Better solution:

Rename `.conf` or `.ovpn` file to `.txt`. Now OpenVPN can see the file.

**Comment by schwabe** [comment]
yeah, for some reason your android reports that it cannot show a file selection dialog for crl so the app falls back to its own crude dialog
