### ISSUE TITLE
How to get error message on connection failed?

### ISSUE THREAD

**Issue by Kimpav** [schwabe/ics-openvpn#635]
When connection to VPN failed. Is there any method give me the reason that make the connection failed?
For example, Host not reachable, Couldn't make connection to port 1234, Invalid CA Certificate, Invalid Username/Password, etc.

Thanks in advanced.

**Comment by schwabe** [comment]
there is a whole log window

**Comment by Bradley168** [comment]
@schwabe Thank you for your fast answer.
Could you give me an example to show the log window?

**Comment by schwabe** [comment]
There is a button in the main view to show the log window.
