### ISSUE TITLE
"comp-lzo no" directive not respected

### ISSUE THREAD

**Issue by liamdennehy** [schwabe/ics-openvpn#636]
OpenVPN for Android 0.6.6(3/4) doesn't respect "comp-lzo no" directive.

- Leaving "LZO compression" unticked in UI causes no "comp-lzo" to appear in the Local Options string summary for a connection - as expected
- Omitting any "comp-lzo" custom directive causes no "comp-lzo" to appear in the Local Options string summary for a connection - as expected
- Adding "comp-lzo <yes|adaptive>" as a custom directive to the config file, or ticking "LZO Compression" in the UI, results in "comp-lzo" appearing in the local option string summary for a connection - as expected
- Adding "comp-lzo no" as a custom directive to the config file results in "comp-lzo" appearing in the local option string summary for a connection - opposite to expectation
- OVPN server PUSHing "comp-lzo no" similarly seems to enable compression, though the log is not informative (decompression errors are logged) - opposite to expectation

Note that the final comment of issue #56 states this should work explicitly

Android 7.1.1 (Nexus 9 Stock) w/OVPNAndroid 0.6.64 and 0.6.63
and
LineageOS 14.1 Nightlies (Android 7.1.1) w/OVPNAndroid 0.6.64 and 0.6.63

**Comment by schwabe** [comment]
The ui and import is not ideal. But for more modern openvpn versions (2.4+) all compression options can be pushed unlike 2.3 or earlier where only comp-lzo could be pushed if comp-lzo no was in the config.

Please note that comp-lzo no is not the same as no "comp-lzo" at all since also comp-lzo no enables comp-lzo framing and the client expects comp-lzo framed packets.

**Comment by liamdennehy** [comment]
> "comp-lzo no" is not the same as no "comp-lzo"

This makes my head explode, but the explanation makes sense.
I have a feeling the server is pushing "comp-lzo no" but doesn't have its' own local "comp-lzo" directive at all, which matches your explanation on framing, since I had presumed the opposite of what you state above. Will give that a test.

**Comment by schwabe** [comment]
Yes it is confusing. the newer compress option in 2.4 should be better understandable.

**Comment by liamdennehy** [comment]
Thanks, this resolved it. Server was assuming a lack of directive on its' end is the same as an explicit no on the client.
Thanks also for your rapid reaction, much appreciate your work!
