### ISSUE TITLE
dhcp-option DNS with IPv6

### ISSUE THREAD

**Issue by tsumaru720** [schwabe/ics-openvpn#637]
# General information
1. Android Version - 7.1.1
2. Android Vendor/Custom ROM - Google
3. Device - Google Pixel
4. Version of the app (version number/play store version/self built) - Play Store / 0.6.65
 
# Description of the issue
 
When providing IPv6 addresses as DNS options, the client errors with the following:

```
2017-03-19 13:22:25 Options error: dhcp-option parameter DNS '2a03:b2XX' must be an IP address
2017-03-19 13:22:25 Options error: dhcp-option parameter DNS '2001:1bXX' must be an IP address
```

Whilst OpenVPN 2.4 should be adding DNS6 option, it might be nice if there was some kind of check to verify if the value of DNS pushed is IPv6 before erroring.

**Comment by schwabe** [comment]
the server never checks push commands and the client already gives you an error, so what else do you want?

**Comment by tsumaru720** [comment]
@schwabe 
The server PUSHES for example
```
dhcp-option DNS 8.8.8.8
dhcp-option DNS 2001:4860:4860::8888
dhcp-option DNS 1.2:3
```

Client CURRENTLY does:

1. Use 8.8.8.8 for DNS as its valid IPv4
2. Errors on 2001:4860:4860::8888 because it says not valid IP
3. Errors on 1.2:3 because it says not valid IP

Expected behaviour:

1. Use 8.8.8.8 for DNS as its valid IPv4
2. Use 2001:4860:4860::8888 for DNS as its valid IPv6
3. Errors on 1.2:3 because it says not valid IP

**Comment by schwabe** [comment]
OPenVPN 2.4 has already add that as dhcp-option DNS6 as you wrote in your first post. If you think that ipv6 ips should be as argument of DNS dhcp-option please take that to the openvpn-devel mailing list.

**Comment by hamedm69** [comment]
With connect to wifi my device   not  work in DCPT  and write ip  ober but put the static and input manual

**Comment by hamedm69** [comment]
My device for connecting the network with wifi in DCHP mod not connecting to net oberting ip maSege shown but when chang to static  mod and input manual ip connect to net. Please help me.
