### ISSUE TITLE
AIDL.startVPN(String inlineConfig) causes "Profile specified in shortcut not found" error

### ISSUE THREAD

**Issue by xasmwasm** [schwabe/ics-openvpn#639]
# General information
1. Android 6.0.1
2. Vendor: Samsung
3. Device: SM-G900H
4. Version of the app: 0.6.64 (self built)
 
# Description of the issue
Hi. 
I guess, there is a bug in [ExternalOpenVPNService.java](https://github.com/schwabe/ics-openvpn/blob/1eac1f1a6e4dbc70db1cd7ec0555a7fd1996374d/main/src/main/java/de/blinkt/openvpn/api/ExternalOpenVPNService.java#L182):

1. External app calls `startVPN(String inlineConfig) `method over AIDL.
Argument `inlineConfig` has option `auth-user-pass`, but `user `and `pass ` are not set.
2. `inlineConfig` successfully converts to `VpnProfile vp`
3. ProfileManager saves `vp` to static variable `ProfileManager.tmpprofile`
```java
ProfileManager.setTemporaryProfile(vp);    //ProfileManager.tmpprofile = vp;
```
4. In `startProfile(VpnProfile vp) ` condition `neddPassword != 0` is true.
5. `startActivity(shortVPNIntent)` performs with flag `Intent.FLAG_ACTIVITY_NEW_TASK`
6. But `ProfileManager.tmpprofile` not initialized in new task and equals to `null`.
7. So, `LaunchVPN.startVpnFromIntent()` cannot find profile by UUID and logs "Profile specified in shortcut not found" error.

```java
public void startVPN(String inlineConfig) throws RemoteException {
            //...
            ProfileManager.setTemporaryProfile(vp);    //ProfileManager.tmpprofile = vp;
            startProfile(vp);
            //...
}

private void startProfile(VpnProfile vp) {
            int neddPassword = vp.needUserPWInput(null, null);

            if(vpnPermissionIntent != null || neddPassword != 0){
                Intent shortVPNIntent = new Intent(Intent.ACTION_MAIN);
                shortVPNIntent.setClass(getBaseContext(), de.blinkt.openvpn.LaunchVPN.class);
                shortVPNIntent.putExtra(de.blinkt.openvpn.LaunchVPN.EXTRA_KEY, vp.getUUIDString());
                shortVPNIntent.putExtra(de.blinkt.openvpn.LaunchVPN.EXTRA_HIDELOG, true);
                shortVPNIntent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(shortVPNIntent);
            } else {
                VPNLaunchHelper.startOpenVpn(vp, getBaseContext());
            }
        }
}
```

**Comment by schwabe** [comment]
Starting VPN remote without embedded user/pass have always been problematic as the callback for password is still missing.

**Comment by schwabe** [comment]
I added something that should make this use case better

**Comment by LQG24** [comment]
how to deal with this problem ?
