### ISSUE TITLE
Need help regarding PPTP protocol

### ISSUE THREAD

**Issue by anmol1410** [schwabe/ics-openvpn#640]
# General information
1.android version: above 5.0
 
# Need help regarding PPTP protocol.
Is it possible to use PPTP, without having the root access?
I am currently stuck on MTPD daemon access. 
Any help would be appreciated.

**Comment by schwabe** [comment]
Sure you can implement pptp as user daemon just as openvpn  however that is a non trivial task.

**Comment by anmol1410** [comment]
To use the PPTP protocol, I am trying to start "MTPD daemon" using the command "ctl.start", by using native C-function calls, which are now not permitted by android.
Can you please suggest me any other alternative for this?

**Comment by schwabe** [comment]
I have no idea how the mtpd daemon works. Native C code is supported by the Android ndk.

**Comment by anmol1410** [comment]
Ok thanks for your prompt responses :)
