### ISSUE TITLE
IPv6 Support

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#641]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version : **7.1.1**
2. Android Vendor/Custom ROM : **onmi7.1.1**
3. Device : **OnePlus 3**
4. Version of the app (version number/play store version/self built) : **0.6.65**
 
# Description of the issue
A VPN I'm using handles IPv6 leaks by "the client adding additional routes such that IPv6 traffic is effectively rerouted to a 'black hole' within the device". This works with [OpenVPN Connect](https://play.google.com/store/apps/details?id=net.openvpn.openvpn) but not this app. I'm not sure to what extent they implement support on their servers or if somehow in the config file alone they manage to do this. In any case, if it can be done with OpenVPN Connect, I don't see why it can't be done with this app, which is why I'm assuming it's a bug related to something not being implemented properly.

For reference, here is a config file for the VPN that does prevent IPv6 leaks:
```
client
dev tun
proto tcp
remote {vpn.server.ip.address} 443
resolv-retry infinite
remote-random
nobind
tun-mtu 1500
tun-mtu-extra 32
mssfix 1450
persist-key
persist-tun
ping 15
ping-restart 0
ping-timer-rem
reneg-sec 0

remote-cert-tls server

#mute 10000
auth-user-pass

comp-lzo
verb 3
pull
fast-io
cipher AES-256-CBC

<ca>
{key contents}
</ca>
key-direction 1
<tls-auth>
#
# 2048 bit OpenVPN static key
#
{key contents}
</tls-auth>
```
 
and here is a config file for the VPN that does **not** prevent IPv6 leaks:
```
client
remote {vpn.server.ip.address} 636
proto tcp
dev tun
cipher AES-256-CBC
auth SHA256
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name tarpaulin.whippet name
tls-version-min 1.2
comp-lzo
key-direction 1
verb 3
route {vpn.server.ip.address} 255.255.255.255 net_gateway

<ca>
{key contents}
</ca>

<cert>
{key contents}
</cert>

<key>
{key contents}
</key>

<tls-auth>
#
# 2048 bit OpenVPN static key
#
{key contents}
</tls-auth>
```
this is the case whether or not the option for "IPv6 Use default Route" is check

**Comment by ghost** [comment]
I would give you log files too, but I can't figure out how to export the log file for OpenVPN Connect.

**Comment by schwabe** [comment]
Without a log from my app or any indication what openvpn-connect does different I have no idea what exactly is the difference. Post screenshots of the log if you cannot export them from OpenVPN connect.

**Comment by ghost** [comment]
I actually am unable to test this right now but if/when I can I'll re-open the issue with said logs.
