### ISSUE TITLE
Error while NDK-build on Linux

### ISSUE THREAD

**Issue by anmol1410** [schwabe/ics-openvpn#642]
Hi,
I am getting error while trying NDK-build on Linux,

Error is:
openssl/crypto/bn/asm/bn-mips.S:2:1: error: unknown directive
.rdata
^
openssl/crypto/bn/asm/mips-mont.S:28:15: error: '(' expected
 sw $30,(14-1)*4($29)
              ^

Any help would be appreciated..

**Comment by schwabe** [comment]
either disable mips or downgrade to ndk 13.

**Comment by anmol1410** [comment]
Thanks for your help :) :)

**Comment by jcampbell05** [comment]
Uncommenting `NDK_TOOLCHAIN_VERSION=4.9` allows it to work on the most recent NDK

**Comment by schwabe** [comment]
mips is now disabled
