### ISSUE TITLE
[Request] Random Selection

### ISSUE THREAD

**Issue by zero77** [schwabe/ics-openvpn#643]
When open vpn starts theres an option to automatically select which vpn profile to use, can you please add an additional option to select a random one.

Also, if one fails can you get it to automatically try a different one, if this isn't already the case.
Thanks

**Comment by schwabe** [comment]
OpenVPN can do this with multiple servers in one config.

**Comment by zero77** [comment]
Which part, random profile selection at start up or try another when one fails or do both work with one profile.

Also, would it be possible to add management to the gui instead of in the configs because, it would be easier and more officiant to manage all profiles from one place and also it can be easier when fixing problems instead of having to go through all the configs.

Thanks

**Comment by schwabe** [comment]
multiple server  inside one profile
