### ISSUE TITLE
Implementing VPN in App

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#645]
Is their an example of using the VPN inside of an app ? I'm not wanting to build a client but I am wondering if there is a good example of using the code as a VPN library for an app.

I am building this for a IOT project I am working on at home which needs a VPN for reliable connection.

How would I control and embed this within my app ?

**Comment by schwabe** [comment]
there is the remote example app.

If you include this source code in your app you will need to opensource your app (or buy a license from me)
