### ISSUE TITLE
TLS Error: TLS Handshake failed while trying to connect to a remote server

### ISSUE THREAD

**Issue by saisasanksunkavalli** [schwabe/ics-openvpn#647]
Below is .ovpn profile file used in my Android mobile for connecting to OpenVpn Server . 

**client
dev tun
proto udp
remote serverIp 1194
port 1194
resolv-retry infinite
nobind
user nobody
group nobody
persist-key
persist-tun
verb 3
<ca>
Certificate goes here
</ca>**

Im using the Username/Password way to connect to a server.  Whenever Im trying to connect to server , it is trying to reconnect in multiples of 2 square.

Below is the OPenVPN Log

> 2017-04-01 06:42:45 WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
> 2017-04-01 06:42:45 Control Channel MTU parms [ L:1621 D:1212 EF:38 EB:0 ET:0 EL:3 ]
> 2017-04-01 06:42:45 Data Channel MTU parms [ L:1621 D:1450 EF:121 EB:406 ET:0 EL:3 ]
> 2017-04-01 06:42:45 Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1541,tun-mtu 1500,proto UDPv4,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-client'
> 2017-04-01 06:42:45 New OpenVPN Status (WAIT->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): ,,,,,
> 2017-04-01 06:42:45 New OpenVPN Status (WAIT->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): ,,,,,
> 2017-04-01 06:42:45 Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1541,tun-mtu 1500,proto UDPv4,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-server'
> 2017-04-01 06:42:45 TCP/UDP: Preserving recently used remote address: [AF_INET]**ServerIp:Port**
> 2017-04-01 06:42:45 Socket Buffers: R=[212992->212992] S=[212992->212992]
> 2017-04-01 06:42:45 MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
> 2017-04-01 06:42:45 UDP link local: (not bound)
> 2017-04-01 06:42:45 UDP link remote: [AF_INET]**ServerIp:Port**
> 2017-04-01 06:42:45 MANAGEMENT: >STATE:1491009165,WAIT,,,,,,
> 2017-04-01 06:42:45 New OpenVPN Status (AUTH->LEVEL_CONNECTING_SERVER_REPLIED): ,,,,,
> 2017-04-01 06:42:45 New OpenVPN Status (AUTH->LEVEL_CONNECTING_SERVER_REPLIED): ,,,,,
> 2017-04-01 06:42:45 MANAGEMENT: >STATE:1491009165,AUTH,,,,,,
> 2017-04-01 06:42:45 TLS: Initial packet from [AF_INET]**serverip:port**, sid=aa65856f 4239bc3b
> 2017-04-01 06:42:45 VERIFY ERROR: depth=0, error=self signed certificate: CN=172.31.30.195, O=172.31.30.195, OU=172.31.30.195, C=US
> 2017-04-01 06:42:45 New OpenVPN Status (RECONNECTING->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): tls-error,,,,,
> 2017-04-01 06:42:45 New OpenVPN Status (RECONNECTING->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): tls-error,,,,,
> 2017-04-01 06:42:45 OpenSSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
> 2017-04-01 06:42:45 New OpenVPN Status (CONNECTRETRY->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): 128
> 2017-04-01 06:42:45 New OpenVPN Status (CONNECTRETRY->LEVEL_CONNECTING_NO_SERVER_REPLY_YET): 128
> 2017-04-01 06:42:45 TLS_ERROR: BIO read tls_read_plaintext error
> 2017-04-01 06:42:45 Waiting 128s seconds between connection attempt
> 2017-04-01 06:42:45 TLS Error: TLS object -> incoming plaintext read error
> 2017-04-01 06:42:45 TLS Error: TLS handshake failed
> 2017-04-01 06:42:45 TCP/UDP: Closing socket
> 2017-04-01 06:42:45 SIGUSR1[soft,tls-error] received, process restarting
> 2017-04-01 06:42:45 MANAGEMENT: >STATE:1491009165,RECONNECTING,tls-error,,,,,
> 2017-04-01 06:44:53 MANAGEMENT: CMD 'hold release'
> 2017-04-01 06:44:53 MANAGEMENT: CMD 'proxy NONE'
> 2017-04-01 06:44:53 MANAGEMENT: CMD 'bytecount 2'
> 2017-04-01 06:44:53 MANAGEMENT: CMD 'state on'

Same error log is getting printed on every reconnect attempt.

**Comment by schwabe** [comment]
Wrong ca certificate selected.
