### ISSUE TITLE
Fails to build in NDK under Clang

### ISSUE THREAD

**Issue by jcampbell05** [schwabe/ics-openvpn#648]
Unless I enable the NDK to use GCC via `NDK_TOOLCHAIN_VERSION=4.9` then it will fail to build OpenSSL for Mibs under Clang.

This seems related to https://github.com/openssl/openssl/pull/2229

We need to document this somehow.

**Comment by schwabe** [comment]
Duplicate of #642, I haven't had time to look into these issues.
