### ISSUE TITLE
Options error using remote-cert-tls server

### ISSUE THREAD

**Issue by longusername789** [schwabe/ics-openvpn#650]
# General information
1. Android Version - 4.4.4
2. Android Vendor/Custom ROM - T-Mobile (?)
3. Device - ZTE ZMax
4. Version of the app - play store version, 0.6.65
 
# Description of the issue
I am unable to connect using an .opvn file with this app, but was able to do so using the OpenVPN Client Free app. I believe the error occurs with the "remote-cert-tls server" option, which is on line 15 of the .opvn file (I'm unable to view the android.conf file to confirm, though). I've copied the full error message from the log below. Thanks for your help.

12:50 PM Options error: Unrecognized option or missing or extra parameter(s) in /data/data/de.blinkt.openvpn/cache/android.conf:15 300 (2.5_master)

**Comment by schwabe** [comment]
This option has been removed in OpenVPN 2.4.

**Comment by longusername789** [comment]
Ok. Is there a workaround? I'd much rather use this app than the ad-ware alternative.

BTW, I'm not sure this is the official manual, but [here's](https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage) what I found on openvpn.net's documentation:

`--ns-cert-type client|server (DEPRECATED)
    This option is deprecated. Use the more modern equivalent --remote-cert-tls instead. This option will be removed in OpenVPN 2.5. `

From what I found above and elsewhere on the page, only the ns-cert-type option is going to be removed. The remote-cert-tls appears to be the favored option that will continue to be supported.

**Comment by schwabe** [comment]
sorry confused that with remote-tls. remote-cert-tls should be supported. Could  you send me your config so I can try to reproduce this error?

**Comment by longusername678** [comment]
Sure thing. Please let me know if you need any other details (I've removed the in-line certs):

client
dev tun
proto udp
remote america.vpn.airdns.org 443
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
cipher AES-256-CBC
comp-lzo no
verb 3
explicit-exit-notify 5
<ca>
