### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by LQG24** [schwabe/ics-openvpn#652]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1、Android 6.0.1
2、Vendor: Samsung
3、Device: SM-G900H
4、Version of the app: 0.6.65 (self built)
 
# Description of the issue
 
2017-04-10 20:16:15 Options error: Unrecognized option or missing or extra parameter(s) in /data/user/0/de.blinkt.openvpn/cache/android.conf:19: ca (2.5_master)
2017-04-10 20:16:15 Use --help for more information.
2017-04-10 20:16:15 Process exited with exit value 1
2017-04-10 20:16:15 New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
2017-04-10 20:16:15 New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.

**Comment by schwabe** [comment]
Probably broken config imported.

**Comment by LQG24** [comment]
@schwabe the apk is no problem from google play ,why?

**Comment by schwabe** [comment]
I have no idea how you screwed this up. My source code that I built the apk is identical to what is in Github. You haven't given much details anyway.

**Comment by LQG24** [comment]
can you give me the code with so files? I doubt that is  a problem

**Comment by schwabe** [comment]
the source code is in this repo (or the linked submodules)

**Comment by LQG24** [comment]
I am trying to build the ics-openvpn library on windows. Due to the .bat file not working, I've decompiled another app (include original app, ics-openvpn) on PlayStore, got their binary file after a build, and copied it to my project. I have done this:
copy their lib folder. include armabi armabi-7a mips x86 folder. in each folder contains : libopenvpn.so libopenvpnutil.so libstlport_shared.so.
After that. I have done this:
Copy minivpn.armeabi minivpn.armeabi-7a minivpn.mip minivpn.x86 into assets folder.
When I run it and try to import an ovpn file and run this, I get this error:

No process runningProcess exited with exit value 1I don't know maybe I have a problem with my configuration? Because when I tried to test this config file with the original app, everything worked fine. Or in source code, do I need to build or modify something else? I read the README file, but I didn't see this mentioned.

**Comment by schwabe** [comment]
It is mentioned in the README:

The ndk fails to build on Windows currently. As a workaround build on
Linux and copy the ovpnlibs directory over to Windows or downlaod a
released version (e.g. from plai.de/android) and extract the libs and
assets directory and place them into main/ovpnlibs/
