### ISSUE TITLE
Installation failed with message Failed to finalize session : INSTALL_FAILED_TEST_ONLY:

### ISSUE THREAD

**Issue by billalantaal** [schwabe/ics-openvpn#653]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
 
# Description of the issue
 Installation failed with message Failed to finalize session : INSTALL_FAILED_TEST_ONLY: installPackageLI.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.

WARNING: Uninstalling will remove the application data!

Do you want to uninstall the existing application?

after press ok
Commands :
$ adb shell pm uninstall de.blinkt.openvpn.remote
DELETE_FAILED_INTERNAL_ERROR
Error while Installing APKs

**Comment by Lyoona** [comment]
provider auth ，change it will be ok

**Comment by schwabe** [comment]
Installing what apks. What are you trying to do?

**Comment by Lyoona** [comment]
check your gradle,if it`s alpha,beta...maybe this wrong.

**Comment by Moussawi90** [comment]
Thank you Lyoona
The cause is due to gradle version set  in build.gradle of the app which is alpha version

**Comment by sosososo** [comment]
and how to fix it?
