### ISSUE TITLE
NativeUtils Class Usage

### ISSUE THREAD

**Issue by bilalcaliskan** [schwabe/ics-openvpn#658]
Hi there, 

I've been working on a project which enables user to connect hired openvpn server from DigitalOcean. Server is ready but there is something which confuses me. Is it really neccessary to use NativeUtils class? In that class, you write binaries and then use these binaries. My question is, is it possible to connect Openvpn server without using any binaries just like normal vpn applications? I mean, just like ToyVpnClient? Take the information and then create a VpnService.Builder? Thanks for your work, by the way. 

Best Regards.

**Comment by bilalcaliskan** [comment]
By the way, here is the ToyVpnClient's link = https://android.googlesource.com/platform/development/+/master/samples/ToyVpn/src/com/example/android/toyvpn

**Comment by schwabe** [comment]
Hey,

no I really need the binaries since I use the original openvpn client. Also please note that your application needs to be fully opensource if you use my code unless you buy a license.

**Comment by bilalcaliskan** [comment]
If I even use a piece of your code, is it neccessary to be opensource?

Thanks.

2017-04-21 13:03 GMT+03:00 Arne Schwabe <notifications@github.com>:

**Comment by schwabe** [comment]
Yes, the GPL license if very clear about this.

**Comment by bilalcaliskan** [comment]
Ok i got it. Thanks for your quick replies. 

Best Regards.
