### ISSUE TITLE
Disable permission alerts/acknowledgments

### ISSUE THREAD

**Issue by ricardojlrufino** [schwabe/ics-openvpn#659]
I'm developing an RFID access control system using android.
And for remote management I chose to use a VPN.

I was able to do the integration via "AIDL", and the connection is initiated remotely via a command sent by the firebase.

The problem is that every time a confirmation message appears. Is it possible to prevent this?
The devices are ROOTED!

**Comment by schwabe** [comment]
Are you talking about the Android VPN confirmation? Then see FAQ and other posts here. There one issue in particular that talks about modifying VPNDialogs.apk to ignore that confirmation.

**Comment by ricardojlrufino** [comment]
The solutions are
1. use Android 5 (for me it does not)
2. use XPosed? (Lots of equipment and lots of manual work)
3. Use a cracked APK (this seems to be the best for me)

Confirm me if I'm wrong.

I created a second solution, generate keyboard events to make the confirmation

**confirm_vpn.sh**
```
input keyevent 61
input keyevent 66
input keyevent 61
input keyevent 61
input keyevent 66
```
https://gist.github.com/ricardojlrufino/61dbc1e9a8120862791e71287b17fef8
```java
        Handler handler = new Handler();
        handler.postDelayed(new Runnable(){
            @Override
            public void run(){
                try {
                    Resources res = getResources();
                    Shell.execScript(res.openRawResource(R.raw.confirm_vpn));
                } catch (IOException e) {
                    e.printStackTrace();
                }
            }
        }, 2000);
```

I do not know if at all android they will be in the same sequence. Or if on android 5 + this will change

**Comment by schwabe** [comment]
@ricardojlrufino Basically yes.
