### ISSUE TITLE
Is there any cordova plugin using this code?

### ISSUE THREAD

**Issue by pallaviMN** [schwabe/ics-openvpn#663]
I want to use this code, in our cordova app. So just wanted to know if there is any cordova plugin for this?

**Comment by schwabe** [comment]
I don't know Cordava so I have no idea about that. But generally either install my app use the AIDL interface, use my code directly and opensource the app or buy a license from me. 

Integration in Cordova is probably possible but doing that integration would be paid consulting work. (Contact me privately if you are really interested in that)
