### ISSUE TITLE
Always-On VPN is disabled by default

### ISSUE THREAD

**Issue by Bradley168** [schwabe/ics-openvpn#665]
How to enable Always-On VPN programmatically?

- ## Default 

![photo_2017-04-28_11-36-43](https://cloud.githubusercontent.com/assets/25146283/25514635/94c7deb6-2c08-11e7-842c-5586cd80d080.jpg)

- ## Expected

![photo_2017-04-28_11-36-39](https://cloud.githubusercontent.com/assets/25146283/25514643/9dbdbd74-2c08-11e7-961c-53b3920c2fcc.jpg)

**Comment by schwabe** [comment]
I don't think there is a way to do that. Maybe device adminstratration can do that but a normal VPN program like OpenVPN for Android cannot do that.
