### ISSUE TITLE
Doesn't connect on boot (after mobile phone restart) even if set to do so

### ISSUE THREAD

**Issue by MrThistle** [schwabe/ics-openvpn#666]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version 6.0.1
2. Android Vendor/Custom ROM Vendor, Z90a40_S363_160625_ROW
3. Device Lenovo Vibe Shot
4. Version of the app (version number/play store version/self built) 0.6.65 from Google Play
 
# Description of the issue
Despite having "Connect on boot" on, the client neither asks for connection on reboot nor connects when it asks and I confirm that I want it co connect. The phone is a Dual SIM phone. I can send application log upon request by email, if it helps.

**Comment by schwabe** [comment]
I chekced the on boot multiple times and it always worked for me. There seem to be ROMs that are jsut broken. Use always-on if your rom supports that.

**Comment by MrThistle** [comment]
Will a log file help you to find out where the problem is?

**Comment by schwabe** [comment]
if the log file has anything at the system start in it, yes. But so far I haven't be able to reproduce the problem on my devices

**Comment by MrThistle** [comment]
I will send it to you just to be sure.

**Comment by schwabe** [comment]
your device fails when booting to give my app the Tun  device:

```
2017-05-01 13:03:39 ERROR: Cannot open TUN: Permission denied (errno=13)
2017-05-01 13:03:39 MANAGEMENT: Client disconnected
2017-05-01 13:03:39 MANAGEMENT: CMD 'needok 'OPENTUN' cancel'
2017-05-01 13:03:39 Error: Android establish() method returned null (Really broken network configuration?)
2017-05-01 13:03:39 Failed to open the tun interface
```

**Comment by MrThistle** [comment]
So it is a device dependent issue? Damn it... :) But thank you checking it.
