### ISSUE TITLE
Erroneous text in notification are on reconnect

### ISSUE THREAD

**Issue by MrThistle** [schwabe/ics-openvpn#667]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version 6.0.1
2. Android Vendor/Custom ROM Vendor, Z90a40_S363_160625_ROW
3. Device Lenovo Vibe Shot
4. Version of the app (version number/play store version/self built) 0.6.65 from Google Play
 
# Description of the issue
On reconnect, when the application notifies about repeated tries, it should show the time after which the reconnect occurs. Instead, it shows text "Waiting %ss seconds ..." - probably duplicate "s" characters in the format string.

![screenshot_2017-05-04-17-20-41-181](https://cloud.githubusercontent.com/assets/25729376/25723633/1f0a0ee0-3119-11e7-8284-90d050b9caa4.jpeg)

**Comment by schwabe** [comment]
where exactly is this message displayed with %s for you? The app has multiple points where the message is displayed.

**Comment by MrThistle** [comment]
At the top of the screen, I believe the area is called the status bar.

**Comment by schwabe** [comment]
ah that is probably the ticker text. I will have a look into it
