### ISSUE TITLE
Crashes when notification screen opened.

### ISSUE THREAD

**Issue by DuoDex** [schwabe/ics-openvpn#670]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android 7.0
2. HTC
3. One A9
4. 0.6.65

Crashes when notification screen is opened. Have yet to determine reproduction steps but I suspect something to do with System UI Tuner and the icon that I can add for Open on with this app.

**Comment by schwabe** [comment]
Can you submit a crash log?

**Comment by DuoDex** [comment]
Embarrassed to say so, but I'm unsure how. I may have sent feedback via the Google email system.

Sorry.

**Comment by schwabe** [comment]
just press the report crash button, when android tells you that the app crashed.

**Comment by DuoDex** [comment]
I am now unable to reproduce this issue. I will reopen this if it occurs again. Thanks!
