### ISSUE TITLE
How to block all non-vpn traffic ?

### ISSUE THREAD

**Issue by woyaojizhu8** [schwabe/ics-openvpn#671]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
 
# Description of the issue
I'm using samsung note5 n9200 with stock rom, android 6.0.1 and openvpn for android 0.6.64 from f-droid.
 I have checked the persist tun option, but it seems this option cannot block all non-vpn traffic. When I switch from SIM A to SIM B (it's a dual SIM device), or turn on/off data connection, I can see some traffic not going through openvpn.

**Comment by schwabe** [comment]
use default route and persist-tun. That is all the app can do to prevent data not going through the VPN. Android O introduces a block non VPN data option.
