### ISSUE TITLE
Vpn disconnect, the server can not receive the message

### ISSUE THREAD

**Issue by LQG24** [schwabe/ics-openvpn#672]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1、Android 6.0.1
2、Vendor: Samsung
3、Device: SM-G900H
4、Version of the app: 0.6.64 (self built)
 
# Description of the issue
 

Vpn disconnect, the server can not receive the message

**Comment by schwabe** [comment]
You need to provide at least a log.

**Comment by LQG24** [comment]
05-15 20:31:37.175 29634-29731/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: CMD 'signal SIGTERM'
05-15 20:31:37.175 29634-29731/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: CMD 'signal SIGTERM'
05-15 20:31:37.178 29634-29634/com.gomo.vpn D/VpnSdk: main[DisconnectVPNServer.java:onServiceConnected:34]是否发信号:true
05-15 20:31:37.184 29634-29731/com.gomo.vpn I/VpnLog: LogItem:TCP/UDP: Closing socket
05-15 20:31:37.184 29634-29731/com.gomo.vpn I/VpnLog: LogItem:TCP/UDP: Closing socket
05-15 20:31:37.194 29634-29731/com.gomo.vpn I/VpnLog: LogItem:Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
05-15 20:31:37.194 29634-29731/com.gomo.vpn I/VpnLog: LogItem:Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
05-15 20:31:37.195 29634-29731/com.gomo.vpn I/VpnLog: LogItem:Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
05-15 20:31:37.195 29634-29731/com.gomo.vpn I/VpnLog: LogItem:Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
05-15 20:31:37.196 29634-29645/com.gomo.vpn I/VpnLog: LogItem:Closing TUN/TAP interface
05-15 20:31:37.196 29634-29645/com.gomo.vpn I/VpnLog: LogItem:Closing TUN/TAP interface
05-15 20:31:37.262 29634-29647/com.gomo.vpn I/VpnLog: LogItem:SIGTERM[hard,] received, process exiting
05-15 20:31:37.262 29634-29647/com.gomo.vpn I/VpnLog: LogItem:SIGTERM[hard,] received, process exiting
05-15 20:31:37.262 29634-29647/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: >STATE:1494851497,EXITING,SIGTERM,,,,,
05-15 20:31:37.262 29634-29647/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: >STATE:1494851497,EXITING,SIGTERM,,,,,
05-15 20:31:37.266 29634-29731/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: TCP send error: Broken pipe
05-15 20:31:37.266 29634-29731/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: TCP send error: Broken pipe
05-15 20:31:37.267 29634-29645/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: Client disconnected
05-15 20:31:37.267 29634-29645/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: Client disconnected
05-15 20:31:37.268 29634-29645/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: Triggering management exit
05-15 20:31:37.268 29634-29645/com.gomo.vpn I/VpnLog: LogItem:MANAGEMENT: Triggering management exit
05-15 20:31:37.269 29634-29647/com.gomo.vpn I/VpnLog: state:NOPROCESS
05-15 20:31:37.269 29634-29647/com.gomo.vpn I/VpnLog: logmessage:No process running.
05-15 20:31:37.269 29634-29647/com.gomo.vpn I/VpnLog: localizedResId:2131296618
05-15 20:31:37.269 29634-29647/com.gomo.vpn I/VpnLog: level:LEVEL_NOTCONNECTED
05-15 20:31:37.275 29634-29647/com.gomo.vpn I/VpnSdk: Binder_2[VpnListAdapter.java:onMessage:80]vpn连接状态信息LEVEL_NOTCONNECTED
05-15 20:31:37.276 29634-29647/com.gomo.vpn I/VpnLog: state:NOPROCESS
05-15 20:31:37.276 29634-29647/com.gomo.vpn I/VpnLog: logmessage:No process running.
05-15 20:31:37.276 29634-29647/com.gomo.vpn I/VpnLog: localizedResId:2131296618
05-15 20:31:37.276 29634-29647/com.gomo.vpn I/VpnLog: level:LEVEL_NOTCONNECTED
05-15 20:31:37.276 29634-29647/com.gomo.vpn I/VpnSdk: Binder_2[VpnListAdapter.java:onMessage:80]vpn连接状态信息LEVEL_NOTCONNECTED
05-15 20:31:37.276 29634-29647/com.gomo.vpn I/VpnLog: LogItem:New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
05-15 20:31:37.276 29634-29647/com.gomo.vpn I/VpnLog: LogItem:New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
05-15 20:31:37.382 29634-29647/com.gomo.vpn I/VpnLog: LogItem:New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
05-15 20:31:37.382 29634-29647/com.gomo.vpn I/VpnLog: LogItem:New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
05-15 20:31:37.382 29634-29647/com.gomo.vpn I/VpnLog: LogItem:Debug state info: CONNECTED  to WIFI "GOMO", pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
05-15 20:31:37.382 29634-29647/com.gomo.vpn I/VpnLog: LogItem:Debug state info: CONNECTED  to WIFI "GOMO", pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 



Is this signal? MANAGEMENT: CMD 'signal SIGTERM' ,why the server can not receive the message

**Comment by schwabe** [comment]
That is not even my app.

**Comment by LQG24** [comment]
No process running.
11:29 Sorry ,deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
11:29 Sorry ,deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.

11:29 SIGINT[hard,] received ,process exiting

**Comment by LQG24** [comment]
when I   disconnect Vpn?  the server can not receive the message

**Comment by schwabe** [comment]
As I said this is not my app and I do not provide free support for for apps that are probably licensing violating and commercial, see the first FAQ in the developer's README.
