### ISSUE TITLE
USB tethered device bypasses tunnel

### ISSUE THREAD

**Issue by m-terlinde** [schwabe/ics-openvpn#673]
# General information
1. Android Version
7.0, Patch Level 1. April 2017
2. Android Vendor/Custom ROM
V20d-EUR-XX
3. Device
LG G5
4. Version of the app (version number/play store version/self built)
Play Store, 0.6.66
 
# Description of the issue
First of all let me thank all of you for the great work which are you doing here!

My mobile phone is connected to a wifi and tunnels to a openvpn server.
On my phone I got a correct tunnel which I verified with a IP test.
If I connect my laptop with USB to my mobile phone and activate the USB tethering, my laptop won't get the tunneld connection. It will be tethered directly over the wifi connection.

Did I something in the settings wrong? Can you reproduce it?
I hope it isn't a duplicate to #34.

If you need a log, please let me know.

Thanks in advance.

**Comment by schwabe** [comment]
That is intended behaviour by Android. See also the FAQ.
