### ISSUE TITLE
No way to enable "IPv6 Use default Route" via .ovpn file

### ISSUE THREAD

**Issue by klyubin** [schwabe/ics-openvpn#675]
# General information
1. Android Version: 7.1.
2. Android Vendor/Custom ROM: stock image
3. Device: Google Pixel
4. Version of the app (version number/play store version/self built): v0.6.66 from Google Play

When I import a new profile (an .ovpn file), there doesn't appear to be a way to have Routing -> IPv6 -> Use default Route setting enabled automatically. Its IPv4 counterpart can be enabled by including "redirect-gateway" in the config file.

See the difference in setting of mUseDefaultRoute and mUseDefaultRoutev6 in Settings_Routing, VpnProfile and ConfigParser. I suspect "redirect-gatway" directive in .ovpn files should enable both mUseDefaultRoute and mUseDefaultRoutev6. Then again, the documentation for redirect-gateway for OpenVPN 2.4 (https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage) isn't entirely clear on this subject.

**Comment by schwabe** [comment]
you need the ipv6 parameter for redirect-gateway to also redirect ipv6 as the manpage tells you but it is not implemented in the parser.

**Comment by klyubin** [comment]
Thank you very much for such quick turnaround! Fix verified.

I do have "redirect-gateway ipv6" in my .ovpn file. Prior to this change, IPv6 Use Default Route wasn't being checked when importing this .ovpn file, whereas after this change it is getting checked.
