### ISSUE TITLE
Not all connections are routed through VPN

### ISSUE THREAD

**Issue by Klaus327** [schwabe/ics-openvpn#676]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version: 7 Nougat
2. Android Vendor ROM FRD-L09C432B360
3. Device Honor 8
4. Version of the app 0.6.66 / play store manually installed 
 
# Description of the issue
Whenever VPN is started, some connections aren't routed through vpn although they should. 

Which connections are these?
- Connections to googlecast._tcp.local (MDNS)
- http(s) Connections to www.baidu.com and connectivitycheck.gstatic.com

From my point of view, this is a routing issue (see rule 10500, which matches for all root processes and uses the direct way).

Is it possible to add another rule with higher priority to catch even those connections?

Existing rules on VPN:

 0:      from all lookup local 
10000:  from all fwmark 0xc0000/0xd0000 lookup 99
10500:  from all oif rmnet_ims uidrange 0-0 lookup 1009
10500:  from all oif wlan0 uidrange 0-0 lookup 1012
11000:  from all iif tun0 lookup 97
12000:  from all fwmark 0x0/0x20000 iif lo uidrange 0-99999 lookup 1013
12000:  from all fwmark 0xc0067/0xcffff lookup 1013
13000:  from all fwmark 0x10063/0x1ffff lookup 97
13000:  from all fwmark 0x10066/0x1ffff lookup 1012
13000:  from all fwmark 0x10067/0x1ffff uidrange 0-99999 lookup 1013 
13000:  from all fwmark 0x10067/0x1ffff uidrange 0-0 lookup 1013 
14000:  from all oif rmnet_ims lookup 1009 
14000:  from all oif wlan0 lookup 1012 
14000:  from all oif tun0 uidrange 0-99999 lookup 1013 
15000:  from all fwmark 0x0/0x10000 lookup 99 
16000:  from all fwmark 0x0/0x10000 lookup 98 
17000:  from all fwmark 0x0/0x10000 lookup 97 
19000:  from all fwmark 0x66/0x1ffff lookup 1012 
21000:  from all fwmark 0x67/0x1ffff lookup 1012 
22000:  from all lookup main 
23000:  from all lookup default 
23000:  from all fwmark 0x0/0xffff lookup 1012 
24000:  from all fwmark 0x0/0xffff uidrange 0-0 lookup main 
32000:  from all unreachable
 

existing tables:

default via 192.168.1.229 dev wlan0  table 1012  proto static 
192.168.1.0/24 dev wlan0  table 1012  proto static  scope link 
default dev tun0    table 1013  proto static  scope link 

192.168.1.0/24 dev wlan0  proto kernel  scope link  src 192.168.1.110 
192.168.7.0/24 dev tun0   proto kernel  scope link  src 192.168.7.2 

broadcast 127.0.0.0 dev lo table local  proto kernel  scope link  src 127.0.0.1 
local 127.0.0.0/8 dev lo table local  proto kernel  scope host  src 127.0.0.1 
local 127.0.0.1 dev lo table local  proto kernel  scope host  src 127.0.0.1 
broadcast 127.255.255.255 dev lo table local  proto kernel  scope link  src 127.0.0.1 
broadcast 192.168.1.0 dev wlan0 table local  proto kernel  scope link  src 192.168.1.110 
local 192.168.1.110 dev wlan0 table local  proto kernel  scope host  src 192.168.1.110 
broadcast 192.168.1.255 dev wlan0 table local  proto kernel  scope link  src 192.168.1.110 
broadcast 192.168.7.0 dev tun0 table local  proto kernel  scope link  src 192.168.7.2 
local 192.168.7.2 dev tun0 table local  proto kernel  scope host  src 192.168.7.2 
broadcast 192.168.7.255 dev tun0 table local  proto kernel  scope link  src 192.168.7.2 

unreachable default as to ::6000:0:1733:357:c367:1327 dev lo  proto kernel  metric 4294967295  error -101
unreachable default as to ::6000:0:1733:357:c367:1327 dev lo  proto kernel  metric 4294967295  error -101
unreachable default as to ::6000:0:1733:357:c367:1327 dev lo  proto kernel  metric 4294967295  error -101

default as to ::6000:0:1733:357:c367:1327 dev rmnet_ims table 1009  proto static  metric 1024 

unreachable default as to ::8000:0:1733:357:c367:1327 dev lo  proto kernel  metric 4294967295  error -101

fe80::/64 as to ::8000:0:1733:357:c367:1327 dev wlan0 table 1012  proto kernel  metric 256  mtu 1400
fe80::/64 as to ::6000:0:1733:357:c367:1327 dev wlan0 table 1012  proto static  metric 1024  mtu 1400

unreachable default as to ::7400:0:1733:357:c367:1327 dev lo  proto kernel  metric 4294967295  error -101

unreachable default as to ::6000:0:1733:357:c367:1327 dev lo table 1013  proto static  metric 1024  error -101

unreachable default as to ::6000:0:1733:357:c367:1327 dev lo  proto kernel  metric 4294967295  error -101
unreachable default as to ::6000:0:1733:357:c367:1327 dev lo  proto kernel  metric 4294967295  error -101
unreachable default as to ::7400:0:1733:357:c367:1327 dev lo  proto kernel  metric 4294967295  error -101

local ::1 as to ::7400:0:1733:357:c367:1327 dev lo table local  proto none  metric 0 

local fe80::a486:ff:a219:138a as to ::8000:0:1733:357:c367:1327 dev lo table local  proto none  metric 0 
ff00::/8 as to ::6000:0:1733:357:c367:1327 dev wlan0 table local  metric 256  mtu 1400

unreachable default as to :: dev lo  proto kernel  metric 4294967295  error -101

Thanks,
Klaus

**Comment by schwabe** [comment]
The app can only install rules via the VPNService. And it installs it only for the local user, on a table multiple users can have different VPNs. System (and that includes tethering) is not routed through a VPN. so what you are seeing is by design. You can probably add rules to change this behaviour when you are rooted but otherwise it is just as it is.

**Comment by Klaus327** [comment]
IAW: The switch located in the options of the configured VPN tunnel in ROUTING / IPv4, which spells in german "Default Route verwenden" / "Sämtlichen Internetverkehr über das VPN leiten" is not really true. You should consider to give it another name if you aren't able to route all packages through VPN.

In fact, you can't say anything for sure about which route the packages will take if I got you correctly, because you don't have the necessary tool to influence it.

**Comment by tjharman** [comment]
I was about to open a new ticket, but I'll ask here instead.

I am connecting my openvpn client but I'm not able to see my Chromecasts at home.  I am using avahi on my home router to forward the mdns to the openvpn interface.

I know the configuration works, because exaclty the same vpn configuration on my Windows PC allows me to control my Chromecasts remotely.

Can someone confirm - the issue is the vpnservice doesn't allow for mulitcast?

**Comment by schwabe** [comment]
See the allow local lan traffic option unde routing when in the lan itself. For the other part I think the google play services will only query on Wifi interfaces and the VPN is not a wifi device.
