### ISSUE TITLE
Import ics-openvpn as library

### ISSUE THREAD

**Issue by davoodfadaei** [schwabe/ics-openvpn#677]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)

 
# Description of the issue
 Hi
I write client/server app.i use ics-openvpn apk to secure communication between them.the server app is on my side and the client app side is far from.i have to send two apk file to remote.i try to use source code of ics-openvpn finally i did it!!!!
I add ics-openvpn as library to my client  project but the client merge manifest file does not have any item of ics-openvpn manifest.
Is it a normal?
How can i solve it?

**Comment by davoodfadaei** [comment]
.i have to send two apk file to remote(my client apk and ics-openvpn apk)
To decrease the human duty i like to integrate two app into one.

**Comment by davoodfadaei** [comment]
.i have to send two apk file to remote(my client apk and ics-openvpn apk)
To decrease the human duty i like to integrate two app into one.

**Comment by schwabe** [comment]
Integrating openvpn for android as library is possible but first understand that due to the GPL violations I extremely catious helping people doing this. Please read doc/README.txt.

**Comment by davoodfadaei** [comment]
I read it.i should pay for it.how much?

**Comment by davoodfadaei** [comment]
I should remember that my app is not commercial.

**Comment by bilalcaliskan** [comment]
+1

2017-05-24 5:57 GMT+03:00 davoodfadaei <notifications@github.com>:

**Comment by davoodfadaei** [comment]
I read Readme.txt
My app is not commercial.
As i understand i should pay for it.how much should i pay?

**Comment by schwabe** [comment]
For pricing details for a commercial application contact me via email (arne-openvpn@rfc2549.org). If your app is really non-commercial, why do you need a closed source license?

**Comment by davoodfadaei** [comment]
I'm not software engineer.i think that i don't need closed secure
license.the only thing that i need is make one package from ics-openvpn and
my app to make it easy my app installation.i don't need change the source
code of ics-openvpn.
I google about integrate two app.lot of documet said that i should change
one app(ics-openvpn) to library and import it to my app.i did it.but
ics-openvpn's manifest file didn't integrate into my app's manifest file.
As i said that my app is a client/server ftp and i use ics-openvpn for
secure transfering file.
My question is :
1-am i need closed secure license to integrate ics-openvpn?
If answer is NO what is my problem that i can not integrate two app?

I repeat that my app is not commercial.
Thank you very much.

**Comment by schwabe** [comment]
When you integreate ics-openvpn into your app your app will become GPL licensed and opensource.  You did not post any error message, also you don't have any open source project on github, so unless you are not forhcoming with more information, I will treat you like anyone else who is developing a commerical application

**Comment by davoodfadaei** [comment]
in my app i import two library.the first one is OK and it's manifest
elements is added to my app's manifest file but ics-open vpn was not .it
means that there aren't any elements of ics-openvpn in my app's manifest
file. also there is not any error . when i build apk package and install it
on my phone only my app and first library install.
so i make new project and try to add library one by one.i import
ics-openvpn library at first.in merge manifest file i have these
messages.(pic1)
when i click on AndroidManifest.xml file hyperlink on right window,it show
another window(pic2).when i hit on red line "
http://schemas.android.com/apk/res/android" it show this message "URL is
not registered(Settings | Languages & Frameworks | Schemas and DTDs)
also on pic3 i have the same error message.
is it possible for you to explain what is my problem?
 Thank you so much.
i apologize for my writing.

**Comment by schwabe** [comment]
Your images are missing and you seem to avoiding my question about the nature of your app, which confirms my suspicions rather than to invidalidate them. 

Sorry, if I am doing you wrong but I have gone down this road too often only to later spot a com.commercialvpnprovider package name the submitter did not hide and claimed to have a completely (non commercial) different app.

**Comment by davoodfadaei** [comment]
i sent three picture .
i send them again.

**Comment by davoodfadaei** [comment]
you can find me in  https://www.linkedin.com
i'm network engineer i don't have any specialist in software and create
commercial software.

**Comment by davoodfadaei** [comment]
davood_fadaee
find me in  https://www.linkedin.com

**Comment by schwabe** [comment]
I am chasing you in linkedIn. You are not even managing to upload pictures to github. Sorry.

**Comment by davoodfadaei** [comment]
This is first time i use github.as i said i not a programmer.i have problem
to transfer file to my branch so i deciaded to find sloution for it.this is
my first program.
You do not guiad me how should i do!!
I sent files to your email.if i should upload them to github i'll do it but
you close my issue.
You can find me in linkedin with
davood_fadaee@yahoo.com

**Comment by schwabe** [comment]
As I said, telling me exactly what your project is about to show me that is *not* a commercial VPN project would be a good first step.

**Comment by davoodfadaei** [comment]
Ok.i will send you my project.
In iran today and tomarrow are weekend and holiday.
I'll send it on saturday.

**Comment by schwabe** [comment]
Don't send me your project, I won't have time to look at it probably. Just start describing whst your project is about.

**Comment by davoodfadaei** [comment]
If you find me on linkedin you should understand that i'm network
administrator on ENbank.my bank have a lof of branch all over the iran.each
branch has dedicated lease line(these lines are not over internet).
these line are not stable sometimes so i think that every teller on branch
has android phone with internet connection so i can send emegency file to
his/her phone.i don't have any experience about android programming so i
googling to find sample ftp program for android.
I have two issues :1-becasue i want to transfer financial document i should
pay attention on security so i use ics-openvpn
2-tellers on branch are not expert on IT so when i send my app and
ics-openvpn to them.it is hard to them to install apps and prepare phone to
transfer file.
With this two issuses i decide to integrate apps into each other and make
easy installation step.
It was very very very hard to me to use source code of ics-openvpn on
android studio but finally i did it.
As i read on android studio documents if i want to integrate two app, i
should change ((plugin :"com.android.application")) on one app to
((plugin:com.android.library)).i did it for ics-openvpn.then i add it to my
app from "open module setting" and "module dependecy" but no elements of
ics-openvpn manifest file integrate into my app manifest file.
There is no error!!!!!
I don't known what is the problem!!!
When i copy openvpn manifest file elements and paste it into my app
manifest so in merge file,every elements be there but i have a lot of
othere error.
I don't know how can i solve it.

**Comment by d-schmidt** [comment]
@davoodfadaei You are working for a bank on an internal app? Just pay @schwabe ...

**Comment by xDragonZ** [comment]
Seems legit - http://iptool.xyz/185.132.213.255/

anyway why don't you use solution such as this https://pritunl.com

**Comment by davoodfadaei** [comment]
My emails are on public??


On May 26, 2017 6:59 PM, "xDragonZ" <notifications@github.com> wrote:

Seems legit - http://iptool.xyz/185.132.213.255

anyway why don't you use solution such as this https://pritunl.com

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/schwabe/ics-openvpn/issues/677#issuecomment-304297850>,
or mute the thread

**Comment by davoodfadaei** [comment]
Oh my god!!!
I sent my comments for my gmail app.i think they are private btween me and arne!!!!!!!!

**Comment by bilalcaliskan** [comment]
What a network administrator 😂

**Comment by davoodfadaei** [comment]
Not important.
If you any idea to solve my problem i appreciate!!

**Comment by schwabe** [comment]
@davoodfadaei Yeah you are replying to github notifcations, the mail even says that replying will end up on Github.

 Anyway, as I as said, I am happy to provide support/consoluting for comercial but please understand that helping commercial projects for free is not something I do (there are some expections but normally not). Contact me under arne-openvpn@rfc2549.org if you willing to do that.

**Comment by davoodfadaei** [comment]
I think it did it.Done.

**Comment by davoodfadaei** [comment]
I think i did it.Done.

**Comment by chrisbjr** [comment]
What an interesting thread

**Comment by nidhinjames** [comment]
Hello, I cant build ics-openvpn in android.  I cannot find /misc/build-native.sh.  Any help will be appreciated.
