### ISSUE TITLE
Meizu MX5 does not add pushed routes

### ISSUE THREAD

**Issue by alexpro** [schwabe/ics-openvpn#678]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
5.1
2. Android Vendor/Custom ROM
Flyme 5.1.12.0G
3. Device
Meizu MX5
4. Version of the app (version number/play store version/self built)
0.6.66
 
# Description of the issue
My English is not very good, excuse me if I said something wrong.
When I connect to VPN server, pushed routes does not appears in routing table. I see pushed routes in OpenVPN log. The same happens with default route.
I have root permissions on my device, and I can add routes by hand after connection established.
I suspect that this is due to Flyme OS specifics... I can't find any workaround for now, I have much experience in Linux, but not in Android.

**Comment by schwabe** [comment]
Routes are handled very different in Android. See also the FAQ. You won't seem in the default routing table.

**Comment by alexpro** [comment]
Thanks for answer.
Of course I know that Linux have several routing tables. But routes did not appears in any of the tables...

This is some kind of magic. After three hours of unsuccessful attempts routes appears in table 'tun0'... And of course, all works as expected.
Sorry for disturbing, I think that is a some weird issue with my mobile internet...
