### ISSUE TITLE
Option for changing language

### ISSUE THREAD

**Issue by yuriimuratov** [schwabe/ics-openvpn#681]
# General information
1. Android Version 7.1.2
2. Android Vendor/Custom ROM LineageOS 14.1
3. Device Xiaomi Redmi 3
4. Version of the app (version number/play store version/self built) 0.6.66
 
# Description of the issue
 Need option for changing language because translation of localizations is not quite good enough

**Comment by schwabe** [comment]
You can also improve the current translation on crowdin.net

**Comment by schwabe** [comment]
Btw. what language are you talking about? If it is really bad I would lik to disable its translation.

**Comment by yuriimuratov** [comment]
No, do not disable it please, am talking about russian  translation. Many 
russian-only talking people will use it well. But I prefer to use original 
language of technical termins. I am from Ukraine, but know russian well and 
my phone locale is russian, and russian translated english termins 
sometimes confuses me a lot. I beleive that many old school IT specialists 
prefer original language of technological termins for working with. That's 
because i want for option to change language. If it is hard to do, i will 
continue to use russian, and maybe I will find time to improve the translation.


Arne Schwabe <notifications@github.com> 29 мая 2017 г. 17:50:04 написал:

**Comment by antonv6** [comment]
JFYI, I'm currently trying to improve it, so the next release and probably the one after that should hopefully have more quality in the UI. But yes, some of the terms are too technical to translate well for both new users and tech savvies.

**Comment by schwabe** [comment]
@antonv6 Thanks for the effort, I marked you proofreader in crowd.in so you can approve translations.

**Comment by 5685C4A059D5** [comment]
It would still be nice to have the option.

**Comment by schwabe** [comment]
Problem is that this seem to be very problematic: https://stackoverflow.com/questions/2900023/change-language-programmatically-in-android

And I really don't want to implement my own localisation system for my app.

**Comment by azumukupoe** [comment]
I too need this.

**Comment by myocytebd** [comment]
Vote on this.

What I really need (and maybe many others) is to force UI in English, so that technical descriptions are accurate.
