### ISSUE TITLE
i18n: de.blinkt.openvpn.core.OpenVPNService.humanReadableByteCount cannot be fully localized

### ISSUE THREAD

**Issue by antonv6** [schwabe/ics-openvpn#685]
This function, `humanReadableByteCount()`, takes a number (bits or bytes) and then returns a string representing this number in a human-readable way (formatted float with units). But the units cannot be localized currently, even though the function uses `Locale` to format the number. The resulting string is also used as a part of at least one string that can be localized: `R.string.statusline_bytecount` (currently it's `↓%2$s/s %1$s - ↑%4$s/s %3$s`). It's an issue because of this inconsistency: the numbers are localized, the time units can be localized, but the data units cannot be changed by translators.

I understand making a quick-and-dirty function that just builds data units from separate characters, but to be truly human-friendly, it should allow localization. A good way to do this is to have all "bit", "kbit", "Mbit" ... and also "B", "KB", "MB" ... as translatable strings.

**Comment by schwabe** [comment]
I also uploaded the new file to crowdin.
