### ISSUE TITLE
Authentication file for proxy is not imported

### ISSUE THREAD

**Issue by modfiles** [schwabe/ics-openvpn#686]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version 5.1.1
2. Android Vendor/Custom ROM Asus
3. Device Asus Fonpad K019
4. Version of the app (version number/play store version/self built)  0.6.66 self built
 
# Description of the issue
 
I have 2 text file containing my login credential for openvpn and proxy and save in 1 directory, so basically i have this line in openvpn config
http-proxy xx.xx.xx.xx xxxx proxy-auth-file.txt basic
but when i import openvpn config, authentication file for openvpn goes along .ovpn and you can verify this by looking in basic setting tab, but authentication file for proxy is not imported, although you can specify it custom options under server list tab.
The problem is when you share your config to technically inclined people over the internet and you dont know where they save the files needed, so you cant specify the exact directory of the file prior to passing the config.
im thinking also to just embed the proxy login credentials to the source prior to compiling but i dont know what files i need to edit to attain that for i have no knowledge with c

**Comment by schwabe** [comment]
have you tried with an inline 

```
<http-proxy-user-pass>
user
pass
</http-proxy-user-pass>
```

that should survive import and end up under custom configu

**Comment by modfiles** [comment]
Thanks for the response
That doesnt seem to work if nested over <connection> block
Im getting 

> option http-proxy-user-pass cannot be used in this context ([CONNECTION-OPTIONS])

so i have this config
```
<connection>
remote 127.0.0.1 8080 tcp
http-proxy 127.0.0.1 3128 auto-nct
<http-proxy-user-pass>
user
pass
<http-proxy-user-pass>
</connection>
```

**Comment by schwabe** [comment]
Put it outside out the connection block

**Comment by modfiles** [comment]
did that and now i get this
`HTTP proxy returned: 'HTTP/1.1 407 Proxy Authentication Required'
Proxy requires authentication
PROXY AUTH BASIC: 'Proxy-Authenticate: Basic realm="Squid proxy-caching web server"'
HTTP proxy authenticate 'realm="Squid proxy-caching web server"'
HTTP proxy: support for basic auth and other cleartext proxy auth methods is disabled`

**Comment by schwabe** [comment]
Check if it is really included in the generated config. Check also if the proxy option in general settings is off. I think it overwrites whatever is in the config.

**Comment by modfiles** [comment]
the  `<http-proxy-user-pass>` is save in Advance > Custom options
Turned off Use system proxy in general setting but Im still getting the same result as my last log post

**Comment by schwabe** [comment]
That might be actually that OpenVPN cannot do the type of authentication that the Proxy requires. The proxy error message tells you that cleartext login is disabled but I am not sure if OpenVPN itself can do other authentication methods.

**Comment by modfiles** [comment]
but using http-proxy 127.0.0.1 8080 path-to-auth-file.txt basic works just fine so I dont think its an iusse with openvpn cannot do the type of authentication

**Comment by modfiles** [comment]
sorted it out, it should be `http-proxy 127.0.0.1 8080 auto` instead of auto-nct
thanks for the support schwabe
