### ISSUE TITLE
option auth-user-pass causes error

### ISSUE THREAD

**Issue by DavidXanatos** [schwabe/ics-openvpn#688]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version 7.1
2. Android Vendor/Custom ROM: OxygsnOS
3. Device Oneplus 3
4. Version of the app (version number/play store version/self built) latest
 
When i select for authentication username-passwird resultign in the option  auth-user-pass in the conf file
openvpn complains that the line with auth-user-pass is invalid i.e. unrecognized option.

also is the app compatible with SSTP?

**Comment by schwabe** [comment]
OpenVPN is not compatible with SSTP
