### ISSUE TITLE
Proxy settings are not used when VPN is connected

### ISSUE THREAD

**Issue by rprimus** [schwabe/ics-openvpn#689]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version: 7.1.2, Build: N2G47W, security patch level: June 2017
2. Android Vendor/Custom ROM: Google
3. Device: Nexus 5X
4. Version of the app (version number/play store version/self built): 0.6.69
 
# Description of the issue
 http system wide proxy settings are not used when VPN is connected.

Not sure if it's related, but I've noticed the following in the logs:
> 19:02 GDG: SIOCGIFHWADDR(lo) failed

The above is at line 286 from the ovpn logfile (below).

Captured data:
[ovpn logfile](https://git.io/vH6Qv)
[post reboot network data](https://git.io/vH6Qn)
[vpn connected network data](https://git.io/vH6Q1)
[logcat data](https://git.io/vH6b2)

From the logcat:
- Line ```25``` verifies that the proxy is configured [127.0.0.1:8118]
- Line ```26``` mentions a ```dev:sockfs``` process
- Line ```29``` does not contain any addresses related to interface ```lo```

Am using privoxy-3.0.26 and test operation by using ```http://p.p``` and ```http://adventofcode.com```.

Cheers!

**Comment by schwabe** [comment]
see FAQ. Cannot be implemented

**Comment by rprimus** [comment]
Thu Jun  8 12:57:21 BST 2017

> Proxy behaviour for VPNs
Android will keep using your proxy settings specified for the mobile/Wi-Fi connection when no DNS servers are set. OpenVPN for Android will warn you about this in the log.

I did read FAQ before opening issue.   **Will keep** implies (to me) a working situation.

Is there another FAQ entry that states this cannot be implemented?

**Comment by schwabe** [comment]
The VPNService API has no way to set a Proxy to use. And as soon as you set a DNS, the system proxy is no longer used.

**Comment by rprimus** [comment]
Thu Jun  8 13:46:09 BST 2017

Cheers!  The above statement is much clearer than the current FAQ entry.
