### ISSUE TITLE
Apostrophe not preceded by \ (Tried to manipulate the file but still the same error is popping up after rebuild)

### ISSUE THREAD

**Issue by Shiyas1910** [schwabe/ics-openvpn#690]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# Description of the issue
Couldn't build the project because the error " Apostrophe not preceded by \ " is popping up again and again. Even altered the file by going through the directories but still couldn't solve the issue. Rebuilding the project after changing the file returns to the previous stage.

Can anyone help me out to solve the issue?

**Comment by schwabe** [comment]
Your bug report is very vage and I have no problem building the project at all and also never seen that error.
