### ISSUE TITLE
Feature Request: Add GUI elements for http proxy

### ISSUE THREAD

**Issue by 7usr7local** [schwabe/ics-openvpn#691]
Hi Arne,
 
thanks for the formidable app, helps me a lot. (Using 0.6.6 from F-Droid)
I just got a configuration working with using http-proxy with authentication (you won't have to have an open proxy somewhere - will you?)
However the need to use a file for the credentials and find a place somewhere in the filesystem is a bit akward. 
Assuming I didn't miss something - would it be possible to add a password dialog (with optional saving) for http-proxy setups? Propably that means configuration options for the proxy parameters itself, which wouldn't be a bad thing either. I'd suggest `http-proxy-option VERSION 1.1` hardcoded, if not an option.

Curious about your ideas on that,

Cheers,

Peter

(In case you're wondering: I am spending a few days at a place without mobile coverage with a strange wifi setup - only email and http is allowed - even https is blocked)

**Comment by ghost** [comment]
@peterjw Can you please share the format of http-proxy settings along with options which are embedded in .ovpn and working fine for you.

Because I'm trying to include below settings in .ovpn and it is failing to connect in ics-openvpn. I tried openvpn connect tool as well.

`http-proxy XXX.XXX.XXX.XXX port auto
`

But the above line doesn't work. Should I must include `http-proxy-option VERSION 1.1` as well?
Does the order of http-proxy also matters i.e. whether it should be before `remote serverip port`

I have also tried below formats but it is not connecting as well. What is missing here?

`http-proxy XXX.XXX.XXX.XXX port auto "basic"
`
and

`http-proxy XXX.XXX.XXX.XXX port auto "none"
`

**Comment by schwabe** [comment]
@umarhayat9 see openvn manpage

**Comment by ghost** [comment]
I'm looking through documentation and tried all different formats but none works.  As it says

`--http-proxy server port [authfile|'auto'|'auto-nct'] [auth-method]`

My proxy server is Squid with no authentication. So I selected 

`http-proxy XXX.XXX.XXX.XXX port auto "none"

The manpage says 

> auth-method should be one of "none", "basic", or "ntlm".
> 
> HTTP Digest authentication is supported as well, but only via the auto or auto-nct flags (below).
> 
> The auto flag causes OpenVPN to automatically determine the auth-method and query stdin or the management interface for username/password credentials, if required. This flag exists on OpenVPN 2.1 or higher.
> `

So I was just wondering to see your .ovpn file's proxy configuration which worked for you. You can ofcourse hide ip details :)

**Comment by 7usr7local** [comment]
@umarhayat9 You need to replace "port" by its value as you replaced "server" with its ip address.
@schwabe Thanks for reopening. Guess, you realized, that umarhayats question was not the topic of this issue.

**Comment by ghost** [comment]
@peterjw Yes obviously I replaced the port value in ovpn file. In above example I just mentioned syntax. 

I think my connection problem is different i.e. once openvpn resolves my proxy domain to ip. Then on next attempt it directly tries to connect to ip of proxy. (which is blocked by ISP)

Actually my isp has firewall which blocks all ip pings. So I have a domain pointed to proxy. Now openvpn successfully resolves and connect to domain proxy. But on next attempt it gets stuck on trying to connect status. (I think it caches the IP of proxy somewhere) I have looked in log.

**Comment by 7usr7local** [comment]
@umarhayat9: Sounds more complex.
As your question is not specific to _OpenVPN for Android_, which is mainly just a GUI for OpenVPN on Android, I recommend to search help somewhere in the general OpenVPN community.
In any case I'd prefer to not discuss this here, as this issue is about a specific feature request I would like not to be smeared by our conversation.

**Comment by schwabe** [comment]
At the moment I am not planning to add http-proxy options to ui

**Comment by 7usr7local** [comment]
I'm looking forward to it :-)
