### ISSUE TITLE
question: AIDL vs a public Intent to stop VPN

### ISSUE THREAD

**Issue by Human** [schwabe/ics-openvpn#692]
Hi! I read a previous discussion about how you no longer support the ability of arbitrary apps to turn off the VPN via a public Intent, and now apps have to use AIDL. Just to be clear, doesn't this just mean that instead of a malicious app broadcasting the old public Intent, they can now just use AIDL? I'm a bit confused as to how this reduces the ability of malicious apps to turn off the VPN, unless you can explicitly whitelist known-good apps on your end.

As a secondary question, do you happen to know if [OpenVPN Tasker Plugin](https://play.google.com/store/apps/details?id=com.ffrog8.openVpnTaskerPlugin&hl=en) works by using AIDL?

**Comment by schwabe** [comment]
I never supported stopping by intents. That was never implemented in the first place. For AIDL you can get the id the of calling application and only allow command from whitelisted apps. 

For normal Intents that are *not* started bey startActivityForResult the calling application id seems not be available.

**Comment by Human** [comment]
Thanks for getting back to me so soon!

Your response is a little confusing to me because stopping the VPN with a VIEW Intent for a specific Activity class was working for me until I upgraded. (I had an older version of your app from f-droid, due to stale repositories. I'm on the latest version now.) All I had to do was modify [this example](https://collinmbarrett.com/android-tasker-openvpn/) to use your package name, instead of net.openvpn.

Are you currently using a whitelist to approve OpenVPN Tasker Plugin, or are you allowing any app to use AIDL to turn off the VPN?

**Comment by schwabe** [comment]
Hm that should never have worked that activity is not exported. For AIDL there is a mechansim to show a dialog box to grant permission the first time the app wants to use the AIDL API, much like when an app tries to use a VPN the first time. The remoteexample in this repo uses that API. And yes the OpeNVPN Tasker uses that API.

**Comment by Human** [comment]
>Hm that should never have worked that activity is not exported.

Well, it did stop the VPN from running, and I didn't see a crash popup. In fact, the entire reason I was looking into the github issues and learned about AIDL was because this stopped working for me when I upgraded.

>For AIDL there is a mechansim to show a dialog box to grant permission the first time the app wants to use the AIDL API, much like when an app tries to use a VPN the first time. The remoteexample in this repo uses that API. And yes the OpeNVPN Tasker uses that API.

FWIW, I don't recall seeing that dialog when using the OpenVPN Tasker Plugin, either through Tasker or via the associated app that it provides.

**Comment by max32002** [comment]
Me,too. I was looking into the github issues and learned about AIDL was because this stopped working for me when I upgraded.

After I call AIDL in my app, I got the message return:

> NONETWORK|

----

message received in OpenVPN for Android:
Signal received from management interface, exiting

OpenVPN do nothing.

**Comment by schwabe** [comment]
@max32002 that means the status is working. Have you checked the example AIDL app?

**Comment by max32002** [comment]
Yes I copy the remoteExample to my app, in the most devices my app communicate with OpenVPN for Android last version (0.6.73) by AIDL work well.
https://github.com/schwabe/ics-openvpn/tree/master/remoteExample

One of my device  stopped working with OpenVPN for Android last version (0.6.73).

I call prepareStartProfile(START_PROFILE_EMBEDDED); and prepareStartProfile(START_PROFILE_BYUUID); both method return message:

> NOETWORK|

I call prepareStartProfile(PROFILE_ADD_NEW); the profile is able to add into OpenVPN for Android, and able to connect to the OpenVPN Server by manually click the profile in OpenVPN for Android.

**Comment by schwabe** [comment]
does that happen for both your app and the example app? It sounds like the wrong method is being called which could be explained if I changed the AIDL in an incompatible way.

Where exactly are you getting NONETWORK? As return from the starprofile methods? What does the log of OpenVPN says in these cases?

**Comment by max32002** [comment]
I do not try the example app. I have tree test android device, 2 are work, 1 is not stable.

My scenario is:
1. call START_PROFILE_EMBEDDED in my app, 
2. call mService.disconnect();
3. call START_PROFILE_EMBEDDED in my app, 
4. I got NOETWORK|

---------
my test case is:
1. call START_PROFILE_EMBEDDED in my app at 2017-07-16 19:43:28 connected to my openvpn server.
2. call mService.disconnect();
3. call START_PROFILE_EMBEDDED in my app at 2017-07-16 19:43:38, my app got NOETWORK| message return.

Key part of log as below:
```
2017-07-16 19:43:28 New OpenVPN Status (CONNECTED->LEVEL_CONNECTED): SUCCESS,10.211.1.89,126.227.246.14,1611,192.168.43.191,46215
2017-07-16 19:43:38 MANAGEMENT: CMD 'signal SIGINT'
2017-07-16 19:43:38 TCP/UDP: Closing socket
2017-07-16 19:43:38 Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2017-07-16 19:43:38 Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2017-07-16 19:43:38 Closing TUN/TAP interface
2017-07-16 19:43:38 SIGINT[hard,] received, process exiting
2017-07-16 19:43:38 MANAGEMENT: >STATE:1500205418,EXITING,SIGINT,,,,,
2017-07-16 19:43:38 New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.
2017-07-16 19:43:38 New OpenVPN Status (NOPROCESS->LEVEL_NOTCONNECTED): No process running.

```

Full log as below:
[ics-openvpn-log-20170716.txt](https://github.com/schwabe/ics-openvpn/files/1150986/ics-openvpn-log-20170716.txt)

**Comment by max32002** [comment]
another log in openvpn, just call START_PROFILE_EMBEDDED in my app at 2017-07-16 19:43:38, my app got NOETWORK| message return.
[ics-openvpn-log-3.txt](https://github.com/schwabe/ics-openvpn/files/1150999/ics-openvpn-log-3.txt)

**Comment by schwabe** [comment]
Keep in mind that AIDL is ansynchronous. If you want just to replace a connection with another, just call connet for the new one. Otherwise the disconnect might be executed after the connect like seen in the  ics-openvpn-log-20170716.txt log (the SIGINT).

The second log has multiple status. The first one is NONETWORK but you will the other status later after that.The server does not like the client in the second log (Connection refused but that is not a fault of the VPN API).

**Comment by AlphaDE** [comment]
@max32002 did you solve that in any way?
