### ISSUE TITLE
Feature Request: Paused VPN app whitelist

### ISSUE THREAD

**Issue by mirdaki** [schwabe/ics-openvpn#694]
First off, I wanted to say thanks for the open source app! The feature I'm proposing would let the user specify certain apps that could still connect to the VPN when the "Paused VPN connection after screen off" is enabled. This would provide some of the battery savings, while being able to still use a few critical apps like normal (such as an instant messenger). 

Something similar would be [Doze - For Better Battery Life](https://play.google.com/store/apps/details?id=com.yirgalab.dzzz&hl=en). 

Another possible enhancement would be a setting to auto disable the paused VPN when charging. Again, this would let the device function like normal when battery isn't an issue.

**Comment by schwabe** [comment]
So you want some apps to be over the VPN when paused and not over the vpn when unpaused? That doesn't make much sense imo

**Comment by mirdaki** [comment]
To clarify, I don't mean I want the apps to be able to bypass the VPN. What I'm asking is for an additional setting where when the screen is off, the app will occasionally unpause the VPN to let certain apps through. I'm not sure how much an impact that would have on battery life (or how it plays with Doze). Ideally you reduce some of the battery drain, while allowing some apps to work normally.

**Comment by schwabe** [comment]
With the current VPN api from Android it is an all or nothing approach. You can say that an APP either goes via VPN or not. 

Pausing/Unpasuing regurarly during screen off would not help much as either the unpause states need very long or you need to be lucky that the apps just reconnect at the right time. There is no API to notify other apps that VPN is connected/not connected. (Technically it stays connected and just does not forward packets anymore).

Not pausing the VPN while on the charger might a valid idea.

**Comment by mirdaki** [comment]
OK I wasn't sure how Android treated VPNs. The unpause while charging change would be nice, maybe when on WiFi too (in my experience the VPN battery drain isn't as bad on WiFi).
