### ISSUE TITLE
Install of 0.6.70 version on SG3 + CM12.1 causes system crash

### ISSUE THREAD

**Issue by erittaf** [schwabe/ics-openvpn#695]
# General information
1. 5.1
2. Cyanogenmod 12.1
3. Samsung Galaxy 3 (sprint) aka d2spr
4. June 16 version (0.6.70) in Play store
 
#Description
Upon downloading this version the launcher, Trebuchet, in CM12.1 crashes and will not relaunch properly leaving only the power menu accessible.  I restored to factory defaults and narrowed down the crash to this app via trial and error installing apps one at a time.  Once OpenVPN was installed Trebuchet crashed again withing seconds without opening the app at all.  I then reset to factory defaults and loaded only the OpenVPN app from the play store to rule out any issues with interoperability of other apps downloaded on the previous attempt.  Again this cause immediate irrecoverable crash of Trebuchet.  In later tests I was able to get into the Settings > Apps menu and I began removing recently updated apps.  Upon clicking uninstall of this App the installer application would also crash.

I was never very impressed with CM12 so I have loaded a new Nougat ROM from Resurrection and did not have the same issues after installing OpenVPN app. This leads me to believe the problems I faced are more related to the combination of device (d2spr) + rom (CM12.1) + app(OepnVPN) than anything.

I don't particularly need a fix for this since it provided me an excuse to update to a newer ROM but I thought it important to raise a red flag that this revision introduced some undesired issues into the app.

**Comment by schwabe** [comment]
Okay, I have no idea what my app does that crashes Trebutechet.

**Comment by Blexsta** [comment]
I have the same problem under Cyanogenmod 13 on my Samsung Galaxy S2.
The issue seems to be related to some changes in the latest version.

After updating the app, my phone services crashed first (data, wifi, and I think also Google Play).
Then Trebuchet crashed (with notification).
This sends Trebuchet into a loop, where it restarts itself and the app, causing it to crash again.

All attempts to open OpenVPN after booting from power down will cause Trebuchet to do the reboot loop again, but without crash notification of Trebuchet.

Might be related to Cyanogenmod, but only happens with the latest version of OpenVPN.

**Comment by schwabe** [comment]
if you have a crash log of trebucht (via adb) that would be helpful

**Comment by Blexsta** [comment]
I guess I can create a logcat?
Just logged it to a file, after logcat was running I started OpenVPN and crashed my Trebuchet that way.

Hope this helps.

[logcat.txt](https://github.com/schwabe/ics-openvpn/files/1084977/logcat.txt)

**Comment by schwabe** [comment]
hm I don't see any stacktrace of a tebutchet crash in there.

**Comment by Blexsta** [comment]
Like I said, now that I am trying it again it does not actually crash Trebuchet (with a notification that Trebuchet has crashed).
That only happened directly after updating.

What it does now is that I get to see the CM robot head and it says "Apps are being started", after which I have to enter my pin, basically "crashing" my phone.
I can no longer reproduce the actual crash of Trebuchet.
It is more like an actual crash, but without the Samsung splash screen and the boot-up time.

Hard to describe, because it is unlike anything I have ever seen before.

**Comment by schwabe** [comment]
Err, if my app manages to crash something that basic in the OS, there is something very very wrong. From the changes in 0.6.70, the most noticeable is probably that it is build with the Android O SDK.

**Comment by Blexsta** [comment]
I will update my CM version to the latest nightly and see if this fixes things.

**Comment by schwabe** [comment]
also report that as bug if simply installing that apk crashes thing. An apk should never crash a ROM.

**Comment by choopm** [comment]
I can confirm this issue, running CM 12.1 on SG3Neo, Android 5.1.1, Kernel 3.4.0.
@schwabe: Already sent you an e-mail prior to seeing that there's an issue opened.

Here's a backtrace, retrieved via adb logcat: https://pastebin.com/VBYK09Z1

**Comment by xDragonZ** [comment]
@schwabe it did happen to me during development when the AndroidManifest.xml encoding is different. Try build again with different Android Gradle version?

**Comment by schwabe** [comment]
I tried installing on my 4.4.x test device the market version and also a debug version and that phone (Moto E, CDMA version, don't ask, I got that one for 25 EUR) and have no problem at all. My S6 test phone also has no problems at all. 

But the crash of @choopm indicates that it could be manifest related (```I/DEBUG   (  271):     #06 pc 00010549  /system/lib/libandroidfw.so (android::AssetManager::getBasePackageName(unsigned int)+68)```)

The base Package name has an umlaut in it (OpenVPN für Android). I think @choopm is German and might have his phone on German. For the other reporters, what language is your phone one?

**Comment by Blexsta** [comment]
While I am German as well, my phone is set to English.

Edit: Just set my phone to German, but it does not resolve the issue.

**Comment by grimmo** [comment]
I am having the same issue, Huawei SCL-L21(AKA Y6 dual sim or Honor 4A), the SoC chipset is Qualcomm MSM8909 Snapdragon 210, with unofficial CM 12.1, android 5.1.1, kernel 3.10.49. No problems til 0.6.66, it ran flawless. However, just clicking the openvpn icon on 0.6.70 reboots the phone.
I can try and send an adb logcat output to help or anything else that can help

**Comment by schwabe** [comment]
@grimmo clicking the icon as in opening the app?

**Comment by xDragonZ** [comment]
Don't think so is phone language related. Can anyone record a video so we can compare? 

I do have an apk that will reproduce this issue on cm12.1 that will send your device into crash looping until you boot into safe mode. From what i observed it only happens on some cm12.1 on some specific device model.

**Comment by schwabe** [comment]
Here is a version build with an older gradle version, lets see if that changes anything. 

http://plai.de/android/ics-openvpn-0.6.71pre.apk

But so far only Cyanogenmod/Linage OS devices are affected. You guys that are affected should definitively also open a bug on CM's side and get it resolved there.

**Comment by choopm** [comment]
@schwabe Just tested 0.6.71pre, works like a charm, doesn't crash anymore:

```
choopm ~ % adb uninstall de.blinkt.openvpn                
Success
choopm ~ % adb install Downloads/ics-openvpn-0.6.71pre.apk
[100%] /data/local/tmp/ics-openvpn-0.6.71pre.apk
	pkg: /data/local/tmp/ics-openvpn-0.6.71pre.apk
Success
```
Thanks for the quick help 👍

**Comment by grimmo** [comment]
@schwabe precisely, it doesn't even show up, the phone reboots in about a second.
I confirm that the 0.6.71 version APK works again without a hitch, so let me say a real big thank you :)
I am on an unofficial port of cyanogen, so no luck for me asking for fixes, but I hope to replace my phone soon so.. it's ok, thanks again.

**Comment by mice777** [comment]
The crashing problem is also described [here](http://www.lonelycatgames.com/wiki/xplore/crash_on_cm)
and filed as bug to Google [here](https://issuetracker.google.com/issues/64434571)

**Comment by intika** [comment]
here is the final true solution that also solve other app updates crash 
https://forum.xda-developers.com/showpost.php?p=74842530&postcount=464
the library is not phone model dependant... 
for cm12.1 and cm13
