### ISSUE TITLE
This app can't recognize .ovpn extension when add configure file

### ISSUE THREAD

**Issue by TurnOffNOD** [schwabe/ics-openvpn#697]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
7.0 NRD90M

2. Android Vendor/Custom ROM
MIUI 8 Global Developer version

3. Device
Xiaomi MI 5

4. Version of the app (version number/play store version/self built)
 google play store version and version downloaded from plaisthos.de/android/ics-openvpn-latest-stable.apk both have this issue

# Description of the issue
 Install ics-openvpn (google play version and version downloaded from plaisthos.de/android/ics-openvpn-latest-stable.apk both have this issue); 
Open it, and press "add" button, select "IMPORT";
When you are looking for your openvpn configuration file, the ics-openvpn ignore the configure file with .ovpn extension, the ics-openvpn only recognize the configure file with .txt extension.

**Comment by schwabe** [comment]
Duplicate

**Comment by TurnOffNOD** [comment]
@schwabe 
Thanks for reply, but I think you should point out which issue I duplicate with.
Just like this:
Duplicate with issue #590
