### ISSUE TITLE
Compile size  not matching to play version and gradle script seem to be not working correct

### ISSUE THREAD

**Issue by nagkumar** [schwabe/ics-openvpn#7]
when we compile it using gradle script and install it on Samsung s4 even emulator with api 21 it gives this error, I tried to use arm7 and arm profile too.

Error remains same. Could you please provide me the latest source code if any with working gradle script, if possible.

I have take then source code from https://github.com/schwabe/ics-openvpn

Also another observation is the size of the compiled apk from the source is around 700kb while the one which is present at this location is

http://plai.de/android/ is around 7 mb

Kindly help us to understand how to compile the code successfully and install it work the same way as the google play version.
This would enable us to use your work further.

![moz-screenshot-2](https://cloud.githubusercontent.com/assets/332234/5792258/9363d51e-9f35-11e4-8447-eb9a8565fda2.png)

**Comment by schwabe** [comment]
Please the README in the source code under doc. It details how to build the app.
Also please read and understand the license.

**Comment by nagkumar** [comment]
Thank You Schwabe, for the pointer. Based on this, I see we need run build-native.sh running.

Is there away to avoid this as setting up ndk on windows is a bigger pain, are there any pre-built  *.so which I can use directly by manually placing them which can make this error go away.

**Comment by schwabe** [comment]
You extract the libraries from my published apk
