### ISSUE TITLE
How to limit the use of traffic when connect vpn？

### ISSUE THREAD

**Issue by LQG24** [schwabe/ics-openvpn#700]
To make issues more manageable, I would appreciate if you fill out the details if applicable

1、Android 6.0.1
2、Vendor: Samsung
3、Device: SM-G900H
4、Version of the app: 0.6.64 (self built)
 
How to limit the use of traffic when connect vpn？

**Comment by schwabe** [comment]
OpenVPN does not provide traffic limiting functionality
