### ISSUE TITLE
Donation with Bitcoin

### ISSUE THREAD

**Issue by VernonSmith** [schwabe/ics-openvpn#703]
Hi @schwabe,
thank you so much for your awesome [Android](https://www.android.com/) [app](https://play.google.com/store/apps/details?id=de.blinkt.openvpn)! 😍
What do you think of adding your [Bitcoin](https://bitcoin.org/) address to the[ _Footnotes_]( https://github.com/schwabe/ics-openvpn/blob/master/README.md#footnotes) section next to your [PayPal](https://www.paypal.com/)?  😉

**Comment by schwabe** [comment]
Added a bitcoin address

**Comment by tortugaverde98** [comment]
Please add your bitcoin address to your f-droid page as well.

**Comment by schwabe** [comment]
I don't maintain the f-droid page. It is maintained by the fdroid project.

**Comment by tortugaverde98** [comment]
Other developers have their btc address on their app's f-droid pages, for example NewPipe, Privacy Browser, Simple gallery, OsmAnd, wireguard. It makes it very quick and easy to donate. You deserve it.

**Comment by schwabe** [comment]
@tortugaverde98 I am honestely too lazy to figure out how to add my bitcoin address there.

**Comment by leoheitmannruiz** [comment]
I've added the Bitcoin and PayPal donation links to the F-Droid page in https://gitlab.com/fdroid/fdroiddata/-/commit/f534bc5b3761f87f5f396a0b713c27b521bc41ac

https://f-droid.org/packages/de.blinkt.openvpn/
