### ISSUE TITLE
Inconsistent cipher and auth values after re-keying

### ISSUE THREAD

**Issue by mmachczynski** [schwabe/ics-openvpn#704]
# General information
1. Android Version: 7.0, compilation NPJ25-93-14
2. Android Vendor/Custom ROM: Version PVTB, SKU XT1642-DS, 2GB RAM, 16GB ROM, dual SIM
3. Device: Moto G4 Plus
4. Version of the app (version number/play store version/self built): 0.6.71 installed from Google Play
 
# Description of the issue
Initially on both sides cipher is AES-256-CBC and auth is SHA256, but after re-keying due to expired TLS key they change at Android device to respectively AES-256-GCM and [null-digest]. There are no other signs, VPN continues working, it seems, that there is no any issue induced. Hereinafter I'm attaching excerpt from server's log: 
Jun 25 20:27:18 bella openvpn[13706]: 46.169.209.12 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher AES-256-GCM'
Jun 25 20:27:18 bella openvpn[13706]: 46.169.209.12 WARNING: 'auth' is used inconsistently, local='auth SHA256', remote='auth [null-digest]'

Configuration of OpenVPN at Android has cipher and auth set to the same values like at server. VPN uses X509 certificates and TLS key for authentication.

Server is OpenVZ running virtual machine with CentOS release 6.9 (Final), OpenVPN version is:
OpenVPN 2.4.1 x86_64-redhat-linux-gnu [Fedora EPEL patched] [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [PKCS11] [MH/PKTINFO] [AEAD] built on Mar 29 2017
library versions: OpenSSL 1.0.1e-fips 11 Feb 2013, LZO 2.03
Originally developed by James Yonan
Copyright (C) 2002-2017 OpenVPN Technologies, Inc. <sales@openvpn.net>
Compile time defines: enable_async_push=no enable_comp_stub=no enable_crypto=yes enable_crypto_ofb_cfb=yes enable_debug=yes enable_def_auth=yes enable_dlopen=unknown enable_dlopen_self=unknown enable_dlopen_self_static=unknown enable_fast_install=yes enable_fragment=yes enable_iproute2=yes enable_libtool_lock=yes enable_lz4=yes enable_lzo=yes enable_management=yes enable_multi=yes enable_multihome=yes enable_pam_dlopen=no enable_pedantic=no enable_pf=yes enable_pkcs11=yes enable_plugin_auth_pam=yes enable_plugin_down_root=yes enable_plugins=yes enable_port_share=yes enable_selinux=yes enable_server=yes enable_shared=yes enable_shared_with_static_runtimes=no enable_small=no enable_static=yes enable_strict=no enable_strict_options=no enable_systemd=no enable_werror=no enable_win32_dll=yes enable_x509_alt_username=yes with_crypto_library=openssl with_gnu_ld=yes with_mem_check=no with_sysroot=no

If you have any questions do not hesitate to ask.

With best regards

Mariusz

**Comment by schwabe** [comment]
This a issue in OpenVPN itself, better report it on the openvpn issue tracker.

**Comment by mmachczynski** [comment]
Thank you for explanation. Best regards.
