### ISSUE TITLE
[Feature Request] Suggestion For Improved Auto Update 

### ISSUE THREAD

**Issue by zero77** [schwabe/ics-openvpn#705]
Can you please implement Phonegap Build (github.com/phonegap-build) to handle updates.
Another git hub project called DuckieTV uses it with their android app, and it has made the update process completely stream line.
For example, upon opening the app Phonegap Build automatically checks for updates, and if found then asks whether to ignore or update and restart, after this there is no additional action required by the user.
Thanks

**Comment by schwabe** [comment]
But why? What is wrong with Playstore updates? Also phonegab is iirc html/css/javascript based which does not apply at all to my app.
