### ISSUE TITLE
Options error: Unrecognized option or missing or extra parameter(s) in http-proxy-option 

### ISSUE THREAD

**Issue by cnsms** [schwabe/ics-openvpn#708]
Options error: Unrecognized option or missing or extra parameter(s) in http-proxy-option 
what is this？

**Comment by schwabe** [comment]
exactly that. Probably an extra parameter

**Comment by cnsms** [comment]
Yes, I need it

**Comment by schwabe** [comment]
Your extra paramter was ignored in earlier version or invalid. Please paste your config.

**Comment by cnsms** [comment]
souga

**Comment by schwabe** [comment]
I am closing this bug as you are not posting the offending line and I guess souga should mean "sucker", so no help from me.

**Comment by cnsms** [comment]
souga mean So it is
