### ISSUE TITLE
Version on F-Droid repository is out of date

### ISSUE THREAD

**Issue by ShapeShifter499** [schwabe/ics-openvpn#709]
F-Droid version is out of date. Any plans on getting the F-Droid team to update it?
 
The version on F-Droid is 0.6.66 but I see version 0.6.73 here on Github.

**Comment by schwabe** [comment]
https://f-droid.org/wiki/page/de.blinkt.openvpn/lastbuild_153 seems like they are using the wrong ndk 14 instead of ndk 15.

**Comment by ShapeShifter499** [comment]
Ok I see, but is this going to be updated? The one on F-Droid now, version 0.6.66, has begun to crash when I try to start the VPN after the latest LineageOS 14.1 nightly update. Are you going to contact F-Droid team about it?

**Comment by schwabe** [comment]
@ShapeShifter499 You should contact f-droid about this, not me. And 0.6.66 should not crash, unless Lineage OS is doing something wrong

**Comment by ShapeShifter499** [comment]
Ok I've submitted an issue request to F-Droid about the wrong NDK. https://gitlab.com/fdroid/fdroiddata/issues/781     Thanks.
