### ISSUE TITLE
Why I have the OpenSSL folder is empty

### ISSUE THREAD

**Issue by ZJLeBron** [schwabe/ics-openvpn#715]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
 
# Description of the issue

**Comment by schwabe** [comment]
See doc/README

**Comment by ZJLeBron** [comment]
thank you very much！you mean use this method“
Fetch the git submodules (the default urls for the submodules use ssh,
setup your own github ssh key or change the url to http in .gitmodules):

  git submodule init
  git submodule update”
get the “openssl” folder？

**Comment by schwabe** [comment]
yes
