### ISSUE TITLE
 Authenticate/Decrypt packet error: cipher final failed ，I have this problem ,please help me

### ISSUE THREAD

**Issue by ZJLeBron** [schwabe/ics-openvpn#716]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
 
# Description of the issue

**Comment by schwabe** [comment]
I need a more complete log than a random error message

**Comment by ZJLeBron** [comment]
Does this project have to run under Windows?

**Comment by ZJLeBron** [comment]
Does this project have to run under LInux?

**Comment by ZJLeBron** [comment]
^
openvpn//src/openvpn/ntlm.c:345:49: warning: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types with different sign [-Wpointer-sign]
        cipher_des_encrypt_ecb(key3, challenge, &ntlm_response[DES_KEY_LENGTH*2]);
                                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
openvpn/src/openvpn/crypto_backend.h:174:43: note: passing argument to parameter 'dst' here
                            unsigned char dst[DES_KEY_LENGTH]);
                                          ^
10 warnings generated.
[arm64-v8a] Compile        : openvpn <= occ.c
[arm64-v8a] Compile        : openvpn <= openvpn.c
[arm64-v8a] Compile        : openvpn <= options.c
openvpn//src/openvpn/options.c:36:10: fatal error: 'config-version.h' file not found
#include "config-version.h"

**Comment by ZJLeBron** [comment]
I hope you can provide the latest. So library files, so I do not have to compile the source code, thank you very much！

**Comment by ZJLeBron** [comment]
14:39 OpenVPN 2.5-icsopenvpn [git:icsopenvpn-d51333c645c12713+] android-21-arm64-v8a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Jun 26 2017

14:39 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
14:39 WARNING: 'cipher' is used inconsistently, local='cipher AES-256-CBC', remote='cipher BF-CBC'
14:39 GDG: SIOCGIFHWADDR(lo) failed
14:39 do_ifconfig, tt->did_ifconfig_ipv6_setup=0
14:39 Authenticate/Decrypt packet error: cipher final failed

**Comment by schwabe** [comment]
You seem to have done something horrible wrong when compiling if the OpenSSL library reports errors on crypto operations or have a seriously wrong OpenVPN config.

**Comment by Stanley8** [comment]
help my apple id disable. and support. Recoveri My new Contak yahoo & gmail
