### ISSUE TITLE
Does this project have to run under Linux?Looking forward to your reply

### ISSUE THREAD

**Issue by ZJLeBron** [schwabe/ics-openvpn#717]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
 
# Description of the issue

**Comment by schwabe** [comment]
This project is an Android project. It runs only under Android.

**Comment by ZJLeBron** [comment]
sorry， I  mean  your  Android  studio  is  on  Windows  or  Linux ?I  can't  build  success   on  Windows

**Comment by schwabe** [comment]
OS X. But someone recently fixed windows building.

**Comment by ZJLeBron** [comment]
I am in the Windows compiler when the error can not find a header file, there is a Windows version of the github address?

**Comment by ZJLeBron** [comment]
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
openvpn/src/openvpn/crypto_backend.h:174:43: note: passing argument to parameter 'dst' here
unsigned char dst[DES_KEY_LENGTH]);
^
10 warnings generated.
[arm64-v8a] Compile : openvpn <= occ.c
[arm64-v8a] Compile : openvpn <= openvpn.c
[arm64-v8a] Compile : openvpn <= options.c
openvpn//src/openvpn/options.c:36:10: fatal error: 'config-version.h' file not found
#include "config-version.h"

**Comment by schwabe** [comment]
Sorry, I cannot help you with Windows.

**Comment by modfiles** [comment]
you need to build it under linux or os x and move it to windows and use android studio to compile

**Comment by dingdev88** [comment]
Hello.
I am using ubuntu.
I git clone from your project.
but, i am getting same error on ubunt ndk-build(version 15)
[arm64-v8a] Compile : openvpn <= occ.c
[arm64-v8a] Compile : openvpn <= openvpn.c
[arm64-v8a] Compile : openvpn <= options.c
openvpn//src/openvpn/options.c:36:10: fatal error: 'config-version.h' file not found
#include "config-version.h"
