### ISSUE TITLE
MMS content does not up/download

### ISSUE THREAD

**Issue by dkogias** [schwabe/ics-openvpn#718]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
7.1.2

2. Android Vendor/Custom ROM
Stock Google

3. Device
Nexus 5X

4. Version of the app (version number/play store version/self built)
Play Store 0.6.73
 
# Description of the issue
 
With VPN disconnected, MMS content uploads and downloads without issues.

With VPN connected, when I receive an MMS, I get the notification that the I have a "media message", but the media itself does not download (repeated attempts tapping on "retry" to download in the SMS/MMS app).  Similarly, sending e.g. a photo never uploads the content.

While doing that, I am `tshark`-snooping on the phone's VPN traffic from the server side.  There is no traffic generated/routed at all that's trying to contact the MMS media server visible on the `tun` device.

**Comment by schwabe** [comment]
that is probably a bug in Android. MMS should not go over the vpn but over the APN that is for mms. The app cannot fix this as that seem to be a bug in android. And it seem halfworking as the traffic neither going via vpn.
