### ISSUE TITLE
 'void de.blinkt.openvpn.api.IOpenVPNAPIService.disconnect()' on a null object

### ISSUE THREAD

**Issue by max32002** [schwabe/ics-openvpn#719]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version: 6.0.1
2. Android Vendor/Custom ROM: HTC Desire 650
3. Device
4. Version of the app (version number/play store version/self built)
OpenVPN for Android 0.6.73
 
# Description of the issue
I copy remoteExample to my app, I call PROFILE_ADD_NEW and START_PROFILE_BYUUID to add and connect profile in OpenVPN for Android, OpenVPN for Android return message:

> CONNECTED|SUCCESS,

OpenVPN for Android crash case 1:
I manually launch OpenVPN for Android (0.6.73), click the profile that I add by AIDL, at this screen, click the right top corner more button, it will let OpenVPN for Android crash (100% Probability). 

OpenVPN for Android crash case 2:
I use START_PROFILE_EMBEDDED by AIDL, try to disconnect in OpenVPN for Android, it's easy to cause crash  (90% Probability).

After OpenVPN for Android crash, my app crash too:

```
E/AndroidRuntime: FATAL EXCEPTION: main
java.lang.NullPointerException: Attempt to invoke interface method 'void de.blinkt.openvpn.api.IOpenVPNAPIService.disconnect()' on a null object reference.

```

Crash source code:
```
                try {
                    mService.disconnect();
                } catch (RemoteException e) {
                    // TODO Auto-generated catch block
                    e.printStackTrace();
                }

```
OpenVPN for Android case1 (add profile) crash screen shot: 
![screenshot_20170711-001729](https://user-images.githubusercontent.com/4498233/28028383-f27ddd62-65ce-11e7-8e0c-09b5d21db366.png)

OpenVPN for Android case2 (embed) crash screen shot: 
![screenshot_20170711-004932](https://user-images.githubusercontent.com/4498233/28030254-907a8ad2-65d5-11e7-94db-06434dfdb1d2.png)

**Comment by schwabe** [comment]
Can you post the stacktrace from my app?
