### ISSUE TITLE
Disconnect VPN

### ISSUE THREAD

**Issue by Bradley168** [schwabe/ics-openvpn#720]
Immediately, on the server side log should receive a line similar to this `delete 192.168.32.6` when user disconnect the VPN.
I used code below to disconnect VPN and on my device the VPN was disconnected but it did not send disconnect signal(`delete 192.168.32.6`) to the server.
```
    private void stopVPN() {
        ProfileManager.setConntectedVpnProfileDisconnected(getBaseContext());
        if (mOpenVpnService != null && mOpenVpnService.getManagement() != null) {
            mOpenVpnService.getManagement().stopVPN(false);
        }
    }
```
Does my code above missed something to disconnect VPN? And how to disconnect VPN correctly?
Thank you.

**Comment by schwabe** [comment]
I have no idea what signa(delete 192.168.32.6) should be.

That code above only works in the openvpn process of the app. For the ui see the DisconnectVPN activity.
