### ISSUE TITLE
Latest version broke ECC auth ciphers

### ISSUE THREAD

**Issue by mke208** [schwabe/ics-openvpn#721]
# General information
1. Android Version - any
2. Android Vendor/Custom ROM - irellevant
3. Device - any
4. Version of the app (version number/play store version/self built) - latest github build
 
# Description of the issue

I was using tls-cipher TLS-ECDHE-ECDSA-WITH-AES-256-CBC-SHA on one of my servers. It used to work well until latest release ... Now the client does not agree with the server on the cipher:

TLS error: The server has no TLS ciphersuites in common with the client. Your --tls-cipher setting might be too restrictive.
OpenSSL: error:1408A0C1:SSL routines:SSL3_GET_CLIENT_HELLO:no shared cipher
 
Since older clients do work, and nothing has changed on the server, i has something to do with the latest release ...

**Comment by schwabe** [comment]
Hardcoding tls-cipher is almost never a good idea. And yes latest release has a rather massive hange in replacing OpenSSL 1.0.2 with OpenSSL 1.1.0. That version also still reports that cipher as supported (add show-tls as custom option). I suspect that something triggers OpenSSL not like that ciphersuite anymore (might be the SHA1 instead of some SHA2 variant in the cipher suite) or OpenSSL only doing ecdsa with with ecdsa certificates now.

**Comment by mke208** [comment]
show-tls was the first thing i did. I am sure this is an openssl issue and not an openvpn issue, but still an issue. Ill try to play with different ciphers combinations and get back if i find something

**Comment by schwabe** [comment]
It might also be a side effect of what I am doing to build openssl 1.1.0. But when I try a OpenSSL 1.1 server (Linux) with a client on OS X, I end with the same error message, so I would assume that it is OpenSSL rather than OpenVPN related.

**Comment by mke208** [comment]
No, this is not related to ics-openvpn. I compiled openvpn 2.4.3 with openssl-1.1.0f on ubuntu 16.04.2, and same result , even with identical client / server. It might have something to with the way i generated my certs ... 
Signature Algorithm: ecdsa-with-SHA512
            Public Key Algorithm: id-ecPublicKey
                Public-Key: (570 bit)
                ASN1 OID: sect571r1
                NIST CURVE: B-571
also tried without --tls-cipher option on both client/server and still same result:
TLS error: The server has no TLS ciphersuites in common with the client.

openvpn 2.4.3 with openssl-1.0.2l works fine ... 
That being said i don't believe that openssl 1.1 is quite ready for prime time yet ...

**Comment by schwabe** [comment]
Apart from your odd cipher everything else works fine with OpenSSL 1.1.0. And OpenSSL 1.1.0 is already used in a lot of places/project. I don't see why OpenSSL 1.1.0 isn't ready for prime time.

But the problem seems also not OpenVPN related at all: https://github.com/openssl/openssl/issues/2033

**Comment by mke208** [comment]
You are correct. I guess you can close this issue.

**Comment by schwabe** [comment]
Btw. if both server and client have ec certificates you get automatically ecdsa too:

Sun Jul 23 14:26:36 2017 Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-ECDSA-AES256-GCM-SHA384, 384 bit EC

**Comment by mke208** [comment]
In case anyone cares, this is related to the way openvpn, openssl 1.1 and ECC are interacting:
  *) Change the ECC default curve list to be this, in order: x25519,
     secp256r1, secp521r1, secp384r1.
     [Rich Salz]
Somehow openssl defaults to x25519 , and my certificates are using sect571r1, and passing
ecdh-curve to openvpn does not solve it.

I have added a line in src/openvpn/ssl_openssl.c:
  SSL_CTX_set1_curves_list(ctx->ctx, "sect571r1");
just under 
  SSL_CTX_set_default_passwd_cb(ctx->ctx, pem_password_callback);

This seems to have fixed it.

**Comment by schwabe** [comment]
Can you send that also to the openvpn-devel list what you found? So other devs can look into that too?

**Comment by mke208** [comment]
Sure. Maybe i can point them to this issue too ...

**Comment by mke208** [comment]
BTW the issue is only on the client. The server behaves normally , even with openssl 1.1

**Comment by eccgecko** [comment]
@mke208 I added that line to src/openvpn/ssl_openssl.c before compiling, except using brainpoolP384r1 curve instead as that's what my certs use. So `SSL_CTX_set1_curves_list(ctx->ctx, "brainpoolP384r1");`
However, the issue has unfortunately not been fixed for me.
