### ISSUE TITLE
Error APK

### ISSUE THREAD

**Issue by Rimander** [schwabe/ics-openvpn#723]
I try build steps.
but..
`Rejecting re-init on previously-failed class java.lang.Class<de.blinkt.openvpn.core.NativeUtils>: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/de.blinkt.openvpn-1/base.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_dependencies_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_0_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_1_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_2_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_3_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_4_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_5_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_6_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_7_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_8_apk.apk", zip file "/data/app/de.blinkt.openvpn-1/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/de.blinkt.
`

**Comment by schwabe** [comment]
You don't have the native libs in your apk. Try to follow the build steps more closely.
