### ISSUE TITLE
Setting for Pause VPN connection after screen off

### ISSUE THREAD

**Issue by murnur19** [schwabe/ics-openvpn#732]
Is there any setting for the kB number for this feature?
If not, can you considering to add them.  Maybe even lower it to bytes. Also the number of seconds to check if possible. Just like `--inactive n [bytes]` config in openvpn, but for pause.
When using spotify I notice openvpn often pause the connection, and make the app can't load the next song. I don't really use many background app that keep connect to the internet, so my network traffic maybe too little.
Thanks.

**Comment by schwabe** [comment]
64 kB in 60s  is already not much traffic. If you want background traffic why do enable the function?

**Comment by murnur19** [comment]
Without this options. My device unable to sleep properly and make it warm after a while.
It's never been a problem until the spotify things.

**Comment by schwabe** [comment]
I decided not to take any action on this. The setting is working as expected.
