### ISSUE TITLE
OpenVPN libray for iOS

### ISSUE THREAD

**Issue by ChineseRoyalStar** [schwabe/ics-openvpn#733]
Hi Arne,

Sorry to issue here but I failed to find your email address.

Are you available to do some consulting work to implement OpenVPN in an iOS app? I have read your discussions in  OpenVPN/openvpn3#1. In fact,  our developing app will be handed out in my enterprise and it will not be submitted to App Store, is it possible to build an iOS library or framework via open source code of OpenVPN3. 

Thanks

**Comment by schwabe** [comment]
OpenVPN 3 code is under AGPL3 which is incompatible with the Apple store license. By doing this you would violate the license of OpenVPN 3 (and probably the one of the Apple store as well)

**Comment by ChineseRoyalStar** [comment]
You mean it would violate the license of  OpenVPN3 even if my app will not submitted to App Store and only used and handed out in my enterprise via Apple Developer Enterprise Program?

**Comment by schwabe** [comment]
I don't know the license of the Apple Delevoper Program but I assume that the terms (especially the DRM ones that conflict with the GPL) are similar. Ask a lawyer if in doubt.

**Comment by ChineseRoyalStar** [comment]
Got it. Thank you for your answer.

**Comment by eltray** [comment]
Hi, @schwabe 

> OpenVPN 3 code is under AGPL3

It's not a true. You can see by this link https://github.com/OpenVPN/openvpn3/blob/master/COPYRIGHT.GPLV3, that AGPL3 license was changed to GPLV3. 

This raises the question of does it allow to use OpenVPN 3 without violating the rules of the Appstore ?

**Comment by schwabe** [comment]
@eltray I was under AGPL3 before. And the answer to your question is: it does not. Unless you are OpenVPN Inc you cannot build a App for the IOS app store using this code.

**Comment by eltray** [comment]
@schwabe 
Arne, many thanks.

**Comment by eltray** [comment]
@schwabe 
And, if I can't use OpenVPN 3, is there any possibility to do this for IOS? Without using OpenVpn connect client?
