### ISSUE TITLE
Setting IPv6 Address as suggested triggers fatal error.

### ISSUE THREAD

**Issue by PriceChild** [schwabe/ics-openvpn#734]
Android 7.1.1 (Latest Nexus 5X)

OpenVPN for Android 0.6.73 from FDroid.

If you disable "Pull Settings" (My connections have been hanging on that, no idea why...) and set an IPv6 address as it suggests:
> Enter IPv6 Address/Netmask in CIDR Format (e.g. 2000:dd::23/64)

then the log shows:

> SIGING[hard,] received, process exiting
> Options error: Unrecognized option or missing or extra parameter(s) in /data/user/0/de.blinkt.openvpn/cache/android.conf:24: ifconfig-ipv6 (2.5_master)
> Use --help for more information.
> Process exited with exit value 1

I checked the official openvpn documentation and found:
> --ifconfig-ipv6 ipv6addr/bits ipv6remote
    configure IPv6 address ipv6addr/bits on the ``tun'' device. The second parameter is used as route target for --route-ipv6 if no gateway is specified. 

Specifying the config using this format (i.e. the remote address also) works fine.

I think it'd be a good idea to clarify the in-app help text.

**Comment by PriceChild** [comment]
Would have just posted a PR but the translations scare me... it'd probably be wrong to update one and not the others! How does that work?

**Comment by schwabe** [comment]
Translation files go via a translation service. But the text is okay and IPv4 and IPv6 should behave the same. I pushed a fix to make the app actually do what it should.

**Comment by PriceChild** [comment]
That was quick! :-)

Thanks @schwabe , I'll sit tight for the new version to hit FDroid and let you know if anything goes wrong.

**Comment by schwabe** [comment]
For now just do the hack and add the pseudo ipv6 with a space as seperater in that field. Next version can take some time.
