### ISSUE TITLE
VPN TimeOut

### ISSUE THREAD

**Issue by Rimander** [schwabe/ics-openvpn#735]
Android Version: 7.0.0+
When the VPN is out of activity, X time later it is disconnected.

**Comment by schwabe** [comment]
You need to include a log from within app, so I have any idea what is happening

**Comment by Rimander** [comment]
New battery saving mode in android 6 is too much aggressive to process running in a background.
VPN will be disconnected after a while of lock screen
I think that this is the problem.
ideas?

**Comment by schwabe** [comment]
If it is Samsung please see the FAQ.
