### ISSUE TITLE
Killswitch?

### ISSUE THREAD

**Issue by SaxonRix** [schwabe/ics-openvpn#736]
# General information
1. 7.0
2. 
3. Nvidia Shield
4. 0.6.73
 
# Description of the issue
Does this app have a killswitch? I read somewhere that it does, but I can't seem to find the option anywhere. Apparently Android 7 is capable of such a thing whereas it's not been possible before without rooting.

**Comment by schwabe** [comment]
Called persistent-tun. And the first Android version which actually implement a real working killswitch is Android 8
