### ISSUE TITLE
OpenVPN for Android does not start without native assets

### ISSUE THREAD

**Issue by bullheadandplato** [schwabe/ics-openvpn#737]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android 8.0
2. Google
3. Nexus 5x
4. Version of the app (version number/play store version/self built)
 
# Description of the issue

**Comment by schwabe** [comment]
Please add a complete log and description what you are doing.

**Comment by bullheadandplato** [comment]
`writeMiniVPN(Context context)` is returning null, always. I have placed the libs in ovpnlibs/

**Comment by schwabe** [comment]
you forget the native assets too. I clarified the README a bit

**Comment by bullheadandplato** [comment]
I placed the native libs at /**src/main/ovpnlibs/assets** and placed *.so files in **/src/main/ovpnlibs/jniLibs**.
Also you need to put this is your build.gradle 

`sourceSets {
        main {
            assets.srcDirs = ['src/main/ovpnlibs/assets']
            jniLibs.srcDirs = ['src/main/ovpnlibs/jniLibs']
            jni.srcDirs = [] //disable automatic ndk-build
        }
}`

This is how I solved it. _Note: I downloaded the app from [Link in README](http://plai.de/android) and copied *.so and native libs from it to the directories I described above._
