### ISSUE TITLE
Cannot recognize the option tcp-nodelay

### ISSUE THREAD

**Issue by archlyx** [schwabe/ics-openvpn#739]
# General information
1. Android Version
Android 7.1.2
2. Android Vendor/Custom ROM
Vendor ROM
3. Device
Google Pixel XL
4. Version of the app (version number/play store version/self built)
 0.6.73
# Description of the issue
The app cannot recognize the tcp-nodelay option in the config file. If I comment it out the VPN connection can be established. 

Here is the log:

> 2017-08-03 21:35:12 Options error: Unrecognized option or missing or extra parameter(s) in /data/user/0/de.blinkt.openvpn/cache/android.conf:33: tcp-nodelay (2.5_master)
> 2017-08-03 21:35:12 Use --help for more information.
> 2017-08-03 21:35:12 Process exited with exit value 1

**Comment by schwabe** [comment]
From the man page:

```This macro sets the TCP_NODELAY socket flag  on  the  server```

server is the keyword here. 

```socket-flags TCP_NODELAY``` is for the client.
