### ISSUE TITLE
Profile randomly disappears

### ISSUE THREAD

**Issue by jomo** [schwabe/ics-openvpn#741]
This has now happened 2 or 3 times and I'm not sure why, but the imported profile I used just disappeared and OpenVPN won't connect. I'm using Android's always-on VPN setting on LineageOS.

I don't know if it's related, buy my phone turned off (without properly shutting down) shortly after startup (due to low battery) before I last noticed this.

**Comment by schwabe** [comment]
What version of the app are you using?

**Comment by jomo** [comment]
Version 0.6.73, installed via F-Droid.
