### ISSUE TITLE
Performance Request: Reduce the time-consuming of connecting

### ISSUE THREAD

**Issue by guanjianzhe** [schwabe/ics-openvpn#742]
# General information
1. Android 7.1.2
2. LG/LineageOS 14.1
3. LG-D802(lg g2)
4. self built:
```
commit 0de6ff8bdc78611ba179a1349694beccf6a883cc
Author: Arne Schwabe <arne@rfc2549.org>
Date:   Tue Aug 1 00:01:45 2017 +0200

    Clarify how the files names should look like
```

# Description of the issue
"OpenVPN Connect" consumes less time than "OpenVPN for Android" during connecting, by **using the same profiles**:

|Android VPN Client|connecting time-consuming(second)|
|:--- |:----:|
 |OpenVPN Connect 1.1.17(build 76)| 0.6|
 |OpenVPN for Android| 4|

I want to know:
1. What's the reason?
2. How to improve?

After Debug, I found most time-consuming come from:
ics-openvpn/main/src/main/java/de/blinkt/openvpn/core/OpenVPNThread.java:
```
       pb.environment().put("LD_LIBRARY_PATH", lbpath);
            mProcess = pb.start();
```
But I don't know what to do next.

**Comment by schwabe** [comment]
That is starting the openvpn process. Note that openvpn connect and openvpn for android have completely different OpenVPN implementation.

**Comment by guanjianzhe** [comment]
Is it possible to "reduce the time-consuming of connecting"?

I try to use ovpn3 as OpenVPN implementation. But "BUILD FAILED", it's say that miss "net.openvpn.ovpn3"
```  
 productFlavors {
   ovpn3 {
        dimension "implementation"
    } 
```

**Comment by schwabe** [comment]
@guanjianzhe openvpn 3 code might need fixup and is genrally not that well integrated. You will need to manually prepare OpenVPN 3 sources to work with OpenVPN for Android.

**Comment by guanjianzhe** [comment]
In ics-openvpn, "Building configuration..." consumes about 0.5 seconds, "Authenticating" consumes about 2 seconds.

It seems that "OpenVPN connect"  didn‘t need "Building configuration..." and "Authenticating". "OpenVPN connect" pullling settings from server directly after connect sesrver. Why "OpenVPN connect" can ignore "Building configuration..." and "Authenticating"?

**Comment by schwabe** [comment]
@guanjianzhe You have absolutely no idea what you are talking about, have you? Sorry, but I am not here on the bug tracker to explain how OpenVPN works.
