### ISSUE TITLE
Building error after running ./import_openssl.sh script

### ISSUE THREAD

**Issue by Moussawi90** [schwabe/ics-openvpn#743]
__Without changing any part of code__ , running the script: _./import_openssl.sh import ~/Downloads/openssl-1.1.0f.tar.gz_  cause an error when building the project using _./misc/build-native.sh_ 
The error is the following: _./obj/local/armeabi-v7a/objs/crypto/crypto/poly1305/asm/poly1305_armv4.o: function poly1305_blocks_neon: error : unexpected opcode while processing relocation R_ARM_THM_JUMP19_ 
(..........)/_bin/ld: error: conditional branch to PLT in THUMB-2 not supported yet_ 

This error becomes at the last steps of building 

_Sent from my Lge LG-H990 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by schwabe** [comment]
Yes. That is known. I did not integrate all fixes into import_openssl.sh script. Escpecially since this might be fixed by a newer OpenSSL/NDK version. You will have to manually fix this one. See the diff between your import and the files in the repository.
