### ISSUE TITLE
Error in running misc/build-native.bat

### ISSUE THREAD

**Issue by Lokarzz** [schwabe/ics-openvpn#744]
Hi schwabe

I tried to run misc/build-native.bat and the error is

[arm64-v8a] Compile        : openvpn <= options.c
[arm64-v8a] Compile        : openvpn <= plugin.c
[arm64-v8a] StaticLibrary  : libcrypto_static.a
[armeabi] Compile thumb  : openvpn <= options.c
[armeabi] Compile thumb  : openvpn <= plugin.c
[armeabi-v7a] Compile thumb  : openvpn <= options.c
[armeabi-v7a] Compile thumb  : openvpn <= plugin.c
process_begin: CreateProcess(NULL, C:/Users/Jules/AppData/Local/Android/sdk/ndk-bundle/build//../toolchains/aarch64-linux-android-4.9/prebuilt/windows-x86_64/bin/aarch64-linux-android-ar crsD ./obj/local/arm64-v8a/libcrypto_static.a ./obj/local/arm64-v8a/objs/crypto_static/crypto/aes/aes_cbc.o ./obj/local/arm64-v8a/objs/crypto_static/crypto/aes/aes_cfb.o ./obj/local/arm64-v8a/objs/crypto_static/crypto/aes/aes_core.o ./obj/local/arm64-v8a/objs/crypto_static/crypto/aes/aes_ctr.o ./obj/local/arm64-v8a/objs/crypto_static/crypto/aes/aes_ecb.o ./obj/local/arm64-v8a/objs/crypto_static/crypto/aes/aes_misc.o ./obj/local/arm64-v8a/objs/crypto_static/crypto/aes/aes_ofb.o ./obj/local/arm64-v8a/objs/crypto_static/crypto/aes/aes_wrap.o ./obj/local/arm64-v8a/objs/crypto_static/crypto/asn1/a_bitstr.o ./ ...........

(Long LINES)

ypto/sha/asm/sha1-armv4-large.o ./obj/local/armeabi-v7a/objs/crypto_static/crypto/sha/asm/sha256-armv4.o ./obj/local/armeabi-v7a/objs/crypto_static/crypto/sha/asm/sha512-armv4.o, ...) failed.
make (e=87): The parameter is incorrect.
make: *** [obj/local/armeabi-v7a/libcrypto_static.a] Error 87
The system cannot find the file specified.
The system cannot find the file specified.
Could Not Find C:\Users\Jules\Desktop\myvpn\main\libs\arm64-v8a\libcrypto.so
Could Not Find C:\Users\Jules\Desktop\myvpn\main\libs\arm64-v8a\libssl.so
arm64-v8a\*.so
The system cannot find the file specified.
        0 file(s) copied.
The system cannot find the file specified.
The system cannot find the file specified.

I'm now stuck with this. I hope you could help me

**Comment by schwabe** [comment]
While @abones recently fixed windows build, I have still no idea if it works or not. I only use OS X to build my app, Linux is also known to work. For everything else you need figure it out yourself and submit pull requests/patches to fix it.

**Comment by Lokarzz** [comment]
Thank you for the reply @schwabe, I'll just figure it out. Btw, I forgot to mention that I'm currently running in windows 10.
I also tried build-native.sh using git bash but still no luck. Same error occurred.

**Comment by isamusisi** [comment]
@karlotoy have you had any luck with your problem?
I seem to be having the same problem and i'm quite new to this. So it would be great if you could give me an update, in case you find the solution!

**Comment by Lokarzz** [comment]
@isamusisi I posted my solution here on #750

**Comment by isamusisi** [comment]
Thanks, I will give it a try.
