### ISSUE TITLE
Branch/tag for developing for Android M/N

### ISSUE THREAD

**Issue by abforce** [schwabe/ics-openvpn#746]
It seems your repo only has got a single branch (i.e. master) which targets the latest Android. However to build using lower platforms (e.g. 23), it won't compile at all. There's lots of Android O specific imports which cause the compile process fails.

Any solution for compiling using SDK 23?

**Comment by schwabe** [comment]
Compiling for SDK 23 should not be necessary since SDK 25 works fine.
