### ISSUE TITLE
Display Bug When Accessed From Notification

### ISSUE THREAD

**Issue by christantoan** [schwabe/ics-openvpn#747]
# General information
1. Android Version: 6.0.1
2. Android Vendor/Custom ROM: Cyanogenmod SultanXDA 
3. Device: OnePlus 3T
4. Version of the app (version number/play store version/self built): 0.6.73 Play Store
 
# Description of the issue
 When opening the app from the notification, the tab indicator is bugged
![screenshot_20170813-073212](https://user-images.githubusercontent.com/7300310/29245124-9e839e5a-7ff9-11e7-8a0e-775dbbba2848.png)

**Comment by schwabe** [comment]
This should be fixed now with the use of the support libraries for the UI
