### ISSUE TITLE
Add support for SNI

### ISSUE THREAD

**Issue by lanrat** [schwabe/ics-openvpn#748]
Even though OpenVPN does not use HTTPS, I would like support for setting SNI information to the server when connecting.

The primary reason for this is due to some networks I am on have a whitelist of allowed hosts users can connect to which they enforce by checking the HTTP HOST header or SNI HOST. It would also be ideal if you could manually set the SNI host to a domain other than the one you are connecting to. ;)

## General information
1. Android Version
7.1
2. Android Vendor/Custom ROM
Stock android 7.1
3. Device
Google Pixel
4. Version of the app (version number/play store version/self built)
 0.6.73

**Comment by schwabe** [comment]
This need to be against upstream OpenVPN. This app merely provides a UI on Android.

OpenSSL itself does not support SNI for its own protocol and priority for that is extremely low. For a normal HTTP Connect you can already include Host as header and HTTPS proxy connect is not supported.

**Comment by lanrat** [comment]
Looks like this feature is planned to be added in OpenVPN 3 :)

https://github.com/OpenVPN/openvpn3/blob/master/openvpn/ssl/sslconsts.hpp#L48

**Comment by lanrat** [comment]
As ics-openvpn now uses openvpn3, can this feature be added?

Thanks.

**Comment by schwabe** [comment]
@lanrat I don't think there is any benefit to using that. Aside from an internal openvpn inc build, there is no server that supports that feature and OpenVPN Inc is not even using that feature themselves, so why should I provide a feature that nobody can use?

And ics-openvpn still defaults to openvpn2 and just has openvpn3 optional. For many years in fact.

**Comment by lanrat** [comment]
This feature would be extremely useful for environments behind a firewall that inspects the SNI field of outgoing TCP/TLS connections and block any connections not matching a list of allowed hosts. The server does not need to do anything for this to work.

This is becoming more and more common on many public & hotel networks. My current solution is to use OpenVPN inside of stunnel, which hurts performance and requires additional services on the server.

Alternatively, what about providing a way for the user to specify additional lines to the config used under the Advanced tab?
This would address this and any other uncommon configs other users may have as well. As far as I can tell, the current version of the app only allows viewing the generated config, but does not allow adding anything to the config used outside of the UI.

**Comment by schwabe** [comment]
you can already specify additional custom configuration options. That feature exist from almost the very first version of this app

A OpenVPN session with SNI enabled still looks like an OpenSSL session, with tls-crypt enabled only the OpenVPN server itself will see that SNI field. I don't think anything will parse OpenVPN and then make a decision based on the SNI in the embedded TLS stream of OpenVPN. Even with SNI, OpenVPN does not look like a HTTPS session.

**Comment by lanrat** [comment]
On my desktop clients with OpenVPN3 this works as I am describing. The SNI field in the TLS handshake is not encrypted and visible on the network to any passive observer, including many network firewalls and IDS systems.

A passive monitor on a TLS session can read a few things, including the SNI field, but there is no way for it to passively determine if the encrypted traffic is HTTPS or any other protocol without first breaking TLS.

**Comment by schwabe** [comment]
@lanrat OpenVPN in TCP mode has its own header that makes it different from a HTTPS protocol, so there is a clear distinction to a normal TLS connection that does not use OpenVPN. And if you use tls-crypt, the whole OpenVPN connection is encrypted, including the TLS Client Hello that contains the SNI field.

**Comment by lanrat** [comment]
When in TCP mode, but without tls-crypt, if the SNI field is in the same location/offset at it would be in a standard TLS session, then as far as firewalls/filters are concerned, it would appear the same, right?

**Comment by schwabe** [comment]
No. As I said, OpenVPN protocol looks different.

**Comment by essoojay** [comment]
Please consider implementing this option SNI if possible Thanks

**Comment by schwabe** [comment]
@essoojay Can you please explain why you would need the option?

**Comment by sbraitti** [comment]
Hi guys, just bumped to this thread. 

I'm also looking for this feature. 
In my case I have only one Public IP Address in my server and I need to share the same port tcp/443 for both services, HTTPS and OpenVPN. 

I believe I could you nginx as a reverse proxy with stream module to decide which SNI is being used and them send it to the right backend (https to https server and openvpn to the openvpn server) (https://stackoverflow.com/a/40135151). 

With this setting, I would be able to bypass many firewalls and proxy servers as they only verify the tcp port I'm connecting and some of them also check SNI. 

Not sure if it would work straightforward with nginx stream module but I'd give it a shot.

**Comment by schwabe** [comment]
@sbraitti SNI will not help you for that. OpeNVPN does not speak standard TLS but rather TLS wrapped in its own framing. Look into `port-share` of OpenVPN for a solution to share OpenVPN port with a web server.
