### ISSUE TITLE
Use of undeclared identifier in build-native.sh

### ISSUE THREAD

**Issue by Lokarzz** [schwabe/ics-openvpn#750]
Hi schwabe

I somehow fixed the issue #744 and another problem appeared. Maybe you have any idea with this.  

jni/jniglue.c:32:38: error: use of undeclared identifier 'arm64'
    return (*env)->NewStringUTF(env, TARGET_ARCH_ABI);
                                     ^
<command line>:3:25: note: expanded from here
#define TARGET_ARCH_ABI arm64-v8a
                        ^
jni/jniglue.c:32:38: error: use of undeclared identifier 'v8a'
<command line>:3:31: note: expanded from here
#define TARGET_ARCH_ABI arm64-v8a
                              ^
2 errors generated.
make: *** [obj/local/arm64-v8a/objs/opvpnutil/jniglue.o] Error 1
make: *** Waiting for unfinished jobs....
[armeabi] Compile++ thumb: nopie_openvpn <= dummy.cpp
[armeabi] StaticLibrary  : liblzo-static.a
[armeabi] StaticLibrary  : libssl_static.a

**Comment by schwabe** [comment]
When you tell how you fixed #744 I might be able to look myself. Otherwise I am probably running in the same build errors.

**Comment by Lokarzz** [comment]
by adding the following to mk files:
LOCAL_SHORT_COMMANDS := true(Android.mk)
APP_SHORT_COMMANDS := true(Application.mk)

reference https://stackoverflow.com/questions/12598933/ndk-build-createprocess-make-e-87-the-parameter-is-incorrect
