### ISSUE TITLE
shell script on connect error

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#751]
Hello Schwabe!
i’m trying to make OpenVPN (latest https://f-droid.org/wiki/page/de.blinkt.openvpn) apply some iptables rules on connect and having errors, “Failed running command: external program exited with error status: 1” and similar.
i have in my optional parameters in vpn config (was surprised that these are not imported from .ovpn file) :
script-security 2
up /data/data/de.blinkt.openvpn/files/script.sh.

sure, i did chmod +x, chown and chgrp to that shall script to match openvpn app user/group.
it works perfectly from adb shell, also from an openvpn user. in my script there’s a single su -c command, but openvpn did not ask for permissions in LineageOS root management.
btw, i have latest build Lineage 14.1.2, Android 7.1.2.
i even tried up ‘/system/bin/ls /sdcard’, does not work. shows in log correct ls output and quits with error status 1, stopping vpn connection.
tried busybox bash instead of stock sh. same thing.
what am i doing wrong?

all that is for having all tethered traffic through vpn, i would like to turn vpn on the phone for my laptop and deny direct connections. it would be lovely if you implement this feature in the app, even if it would reasonably ask for a su rights elevation.
sorry if such posts are not in github ethics, i was unable to find you email anywhere.
D.

**Comment by schwabe** [comment]
First of su implemention: I would accept a pull request for that looks reasonable but I have no rooted device myself so I cannot test or it.

For the return status, openvpn checks if the commands return a valid return code, somewhere that seem to go wrong :/.

**Comment by ghost** [comment]
I'm not a programmer, can't do any improvement, unfortunately.

**Comment by ildar** [comment]
@d-e112211 , 
> restorecon -vv /data/data/de.blinkt.openvpn/files/script.sh

should help

**Comment by ghost** [comment]
perfect! it helped!
should be run once to fix some kind of selinux permissions, right?

**Comment by schwabe** [comment]
Problem seems to be sovled/workaround, closing issue
