### ISSUE TITLE
Multiple simultaneous connections

### ISSUE THREAD

**Issue by evan-goode** [schwabe/ics-openvpn#755]
1. Android Version
7.1.2
2. Android Vendor/Custom ROM
LineageOS 14.1
3. Device
Nexus 6P
4. Version of the app (version number/play store version/self built)
0.6.73

Does this app support opening connections to two (or more) different VPN servers at once? When I select a profile, the existing connection seems to drop and the new one takes over.

If I am not just missing something and multiple connections are _not_ in fact supported, is such functionality even within the scope of the project? I understand the app may be somewhat limited by the VPNService API.

**Comment by schwabe** [comment]
Not it does not support it. The VpnService API also only gives you a single tun.

While you could theoretically do something like client side nat and share one virtual IP for multiple VPN connection, I consider that really out of scope and won't implement something like that.
