### ISSUE TITLE
How to use certificate chains in ics-OpenVPN?

### ISSUE THREAD

**Issue by rukhrobin** [schwabe/ics-openvpn#756]
for example:
ca.crt --- server.crt
         +-- sub-ca.crt --- client.crt
how should i edit my config file with the client.crt?
This link https://community.openvpn.net/openvpn/wiki/Using_Certificate_Chains may help.

**Comment by schwabe** [comment]
This not an OpenVPN tutorial or forum. This is to report bugs or suggestions to the app.
