### ISSUE TITLE
openvpn effects tethering

### ISSUE THREAD

**Issue by gariac** [schwabe/ics-openvpn#757]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version 7.1.1
2. Android Vendor/Custom ROM Oneplus Oxygen 4.5.10
3. Device Oneplus 5
4. Version of the app (version number/play store version/self built) 0.6.73
 
# Description of the issue
Openvpn should not effect the tethering operation. That is, you should run openvpn on the tethered device rather than expect the openvpn on the phone to work with the tethered device. That said, running openvpn does have some side effect on the tether. For instance the wifi tether doesn't work at all. If you can suggest some diagnostics, I will try to be more specific.

**Comment by schwabe** [comment]
There are multiple close issues about this and even a FAQ.
