### ISSUE TITLE
Block/allow VPN for certain ports?

### ISSUE THREAD

**Issue by nviet** [schwabe/ics-openvpn#758]
To make issues more manageable, I would appreciate if you fill out the details if applicable

## General information
1. Android Version: 5.0.2
2. Android Vendor/Custom ROM: Sony
3. Device: D6502
4. Version of the app (version number/play store version/self built): 0.6.73
 
## Description of the issue
 
I can block/allow VPN for certain apps. However, is there any way to block/allow VPN for certain ports, or maybe to route the traffic from these ports not to go to the VPN?

For example, if I install a HTTP proxy server on my device, start the proxy server on port 8080 and connect to a VPN, then the traffic that passes through that proxy server (port 8080) also goes to the VPN while I want it to go directly to the Internet.

**Comment by schwabe** [comment]
The VPN api does not allow such fine grained VPN configuration.
