### ISSUE TITLE
Crashed when using ECC certificates from Android keystore

### ISSUE THREAD

**Issue by jimstar06** [schwabe/ics-openvpn#762]
# General information
1. Android Version
6.0
2. Android Vendor/Custom ROM
Huawei Honor 7 EMUI4.0 Offical ROM
4. Version of the app (version number/play store version/self built)
0.6.73 from Google Play
# Description of the issue
My OpenVPN Server use ECC certificates (secp256v1 with SHA256) on CA, servers and clients. It works fine if I select client certificate from PKCS#12 files, but crashed if using Android certificate.

**Comment by schwabe** [comment]
Known issue. External-key-management does not work with ecdsa certificates which is needed for Android certifates.
