### ISSUE TITLE
It seems profiles backup stored in google cloud.

### ISSUE THREAD

**Issue by sergeygalkin** [schwabe/ics-openvpn#764]
# General information
1. Adroid 7.1.1
2. Stock ROM on the both side
3. Nexus 6 on one side, HTC U11 on the other side
4. Version of the app 0.6.73
 
When I restored my google account on new HTC U11 after Nexus 6 I have found what all profiles already created in the new device. Is this expected behavior ? It seems what this is not very secure.

**Comment by schwabe** [comment]
That is expected behaviour. That is Google backup of Android. Wether you trust your data with Google or not is another matter.
