### ISSUE TITLE
Sound picker/disable on connect

### ISSUE THREAD

**Issue by zigzampow** [schwabe/ics-openvpn#768]
# Description of the issue
 
 This is a feature request which I can't seem to add a feature tag form web. 

Can we get an option to choose a sound for the connect chime? Can we also get a "none" option in that picker so we can silently connect?

**Comment by schwabe** [comment]
The notification should not have a sound. If you are on Android 8 you can also set the pirority of the connection notification to no sound.

**Comment by zigzampow** [comment]
Ok so it follows the normal notification sounds. I can work with that
around Tasker
