### ISSUE TITLE
Connection via local socks proxy reset, immediately after connection is established.

### ISSUE THREAD

**Issue by Skipp1** [schwabe/ics-openvpn#769]
I have an OpenVPN server that is able to connect via obfsproxy (a local socks proxy), I have set up obfsproxy via python’s pip, so I have confidence that the versions of this are all the same. I am able to connect and maintain a connection from my computer so I do know that the server is set up correctly. To install obfsproxy onto my phone I installed python (and pip) into Termux (a shell app) and installed it there.
And now for the problem: I am able to establish a connection to the sever through the proxy and the logs do say ‘Initialization sequence Complete’. However, immediately after this message appears the connection restarts with the log info ‘Connection Reset, Restarting [0]’, it will then disconnect (and I can see from the server end that the connection is reset by the client). 
It may be a case of android not playing nice with inter-app communication over localhost (if this is the case please shut me down)

I will be happy to provide logs and pcap files if needed.
Android version: 7.1.1 (security: July 1 2017)
Phone model: One Plus 5 (A5000)
ROM: Standard
Version info: 0.6.73 (both play store and self-built (commit number 1402))

**Comment by schwabe** [comment]
Should work over localhost. Can you add a log to let me see if there is anything strange happening?

**Comment by Skipp1** [comment]
[ICS OpenVPN log file.txt](https://github.com/schwabe/ics-openvpn/files/1353177/ICS.OpenVPN.log.file.txt)

**Comment by Skipp1** [comment]
Small update.
I discovered that Openvpn on my laptop displayed a similar behavior is the tun interface fails to load (it exchanges keys fine but then will not connect).
I wonder if a similar thing is happening with the proxy but because the proxy is a separate application it is not relaying the logging information back to the Openvpn app.
My hypothesis is: because this is a non native socks proxy, and not the built in HTTP proxy, it is trying to open the interface like Openvpn normals does it and not via the Android API, and hence it is failing to open the interface. 
I am not too familiar with how the default HTTP proxy handles vpn requests or how your app sends the requests to the vpn (from what I can see you are sending the API calls to the proxy (correct me on this)). More testing is definitely needed to resolve the problem (I may just be making the diagnosis up).

**Comment by schwabe** [comment]
no the problem is that the connection to the local port is reset because either android itself resets it or the proxy on the other end of the socket closes the connection.

**Comment by Skipp1** [comment]
Well I know for a fact that it isn't the server (logs say that connection was reset by client). However, I don't know enough about the internal working of android to know about the second possabilty. 
Either way is doesn't seem like the problem is with your app so feel free to close this or whatever
Thanks either way.

**Comment by kijan12345** [comment]
Caranya pake vpn gmana gan

**Comment by privatevpnsupportguy** [comment]
I have similar issue. Where I try to connect to OpenVPN TCP server via shadowsocks running in Proxy mode. It works fine on GNU/Linux, Windows.

Reported an issue here: https://github.com/shadowsocks/shadowsocks-android/issues/1620

**Comment by privatevpnsupportguy** [comment]
OpenVPN client supports per-app VPN, try to exclude shadowsocks or whatever proxy program you are using from the list. It works!

**Comment by schwabe** [comment]
I am closing this as @privatevpnsupportguy  has a workaround and I think the app cannot really workaround the real issue here

**Comment by mirfatif** [comment]
@privatevpnsupportguy same works for using [Orbot](https://play.google.com/store/apps/details?id=org.torproject.android) socks proxy on[ OpenVPN Client](https://play.google.com/store/apps/details?id=it.colucciweb.free.openvpn). Thanks
