### ISSUE TITLE
can't find .git directory on openvpn, aborting

### ISSUE THREAD

**Issue by dingdev88** [schwabe/ics-openvpn#770]
Hello.
I am trying to build your project on Linux(ubuntu)
I added ssh key to my github account.
then, I am using "git clone git@github.com:schwabe/ics-openvpn.git".
If i input this query in command line, i am putting ssh password.
then, git submodule init.
then git submodule update.
After that, i am trying to run "bash native-build.sh"
but, i am getting this error "can't find .git directory on openvpn, aborting". Please help me for this.

I used "git clone https://github.com/schwabe/ics-openvpn.git", too.
but, i am getting same error...
Please help me.

**Comment by schwabe** [comment]
Sorry, this bug tracker is not a ssh or git help forum. But try cloning via http if ssh gives you problems.
