### ISSUE TITLE
How can I replace the openssl with the version of 1.0.2f?

### ISSUE THREAD

**Issue by TaoMonkey** [schwabe/ics-openvpn#771]
I want use my own openssl with the version of 1.0.2f.How can I replace the openssl with the version of 1.0.2f? Thanks~

**Comment by schwabe** [comment]
Check the OpenSSL repository of this app, it has a 1.0.2 version in it.

**Comment by TaoMonkey** [comment]
@schwabe  Thanks for your reply. I have already compiled this app and my certificate was created with easy-rsa,which openssl version is 1.0.2k.My openvpn service used openssl with 1.0.2k.When I run this app,it can't load the certificate.It shows errors like this:Cannot load inline certificate file.I guess the problem is that version of opensll is not uniform.This app use the openssl with 1.1.0f version."it has a 1.0.2 version in it",do you mean 1.1.0f contain 1.0.2?

**Comment by schwabe** [comment]
Your problem is probably the weak hash algorithm. See the FAQ.

**Comment by TaoMonkey** [comment]
@schwabe Thank you very much. I solved this problem in FAQ with your suggestion.Thanks.
