### ISSUE TITLE
Feature Request: Allow routing specific apps through normal connection (not VPN)

### ISSUE THREAD

**Issue by forabi** [schwabe/ics-openvpn#772]
Apps that require local network access (KDE Connect for example) cannot find local devices when using VPN. Android allows VPN services to exclude apps from being routed through the VPN. It would be nice to implement this option.

**Comment by nbastin** [comment]
Does "Bypass VPN for local networks" option not work for you?  Also you can always set custom routes in the Routing tab as well.

**Comment by forabi** [comment]
I didn't realize that these settings are available in the profile-specific
settings. Thanks!
