### ISSUE TITLE
Feature Request: Information about underlying OpenVPN version

### ISSUE THREAD

**Issue by bfranske** [schwabe/ics-openvpn#773]
It would be especially helpful if the application about screen, README file, and/or FAQ had some information about the underlying OpenVPN version/features supported by the client. I was trying to track down this information today as I am in the process of updating all my OpenVPN servers to 2.4.4 and would really like to start taking advantage of features in that like the much better dual-stack support, Seamless client IP/port floating, Data channel cipher negotiation, AEAD (GCM) data channel cipher support, ECDH key exchange, LZ4 Compression and pushable compression. It's unclear if these are supported in ics-openvpn. Thanks!

**Comment by schwabe** [comment]
OpenVPN for Android tracks OpenVPN master (development branch).
