### ISSUE TITLE
Insist more on staying connected

### ISSUE THREAD

**Issue by Forage** [schwabe/ics-openvpn#775]
# General information
1. Android Version: 7.1.2
2. Android Vendor/Custom ROM: LineageOS 14.1
3. Device: Oppo R7f
4. Version of the app: 0.6.73
 
# Description of the issue
 
The app, along with its VPN connection, regularly disappears completely. On one moment you are connected, when you pick up your phone again the VPN connection is gone.

I suppose losing the connection is due to me being kicked out by the VPN server, having the following in the log:

    08:35 AUTH: Received control message: AUTH_FAILED
    08:35 SIGTERM[soft,auth-failure] received, process exiting

While this can happen, I don't quite understand why the app completely disappears and this without any notification. With or without "always-on" enabled in the general VPN settings, it should at least give me a notification that the app is giving up. There could be plenty of internet activity in the background that you want to keep tunneling through a VPN.
In addition, why does it not keep trying to reconnect? Based on the log I see no second attempt taking place. I'd like to see the app insist more, even not giving up until manual intervention.

What do you think?

**Comment by Forage** [comment]
Sorry, I accidently hit the submit button

**Comment by nihiluis** [comment]
bro do this plz. this is annoying af. dont just disconnect.

**Comment by schwabe** [comment]
It is already implemented

**Comment by Forage** [comment]
Great to hear it is implemented!

But is this your way of saying that there was already a setting for it but I haven't searched good enough or that you just implemented it and it will be committed soon?
