### ISSUE TITLE
Compile error,instruction requires: neon

### ISSUE THREAD

**Issue by jh531207323** [schwabe/ics-openvpn#776]
Hi
 Whenever I compile the project on Windows or centos, I have the following error.
how can i fix it. thanks .
  
 
![image](https://user-images.githubusercontent.com/15181617/31803811-65cd3746-b588-11e7-9058-c85e007114ef.png)

**Comment by schwabe** [comment]
Duplicate of #774

**Comment by jh531207323** [comment]
thanks a lot
