### ISSUE TITLE
Import: Match-failure and drops

### ISSUE THREAD

**Issue by M-Pixel** [schwabe/ics-openvpn#778]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. __Android Version:__ 6.0.1
2. __Android Vendor/Custom ROM:__ Samsung
3. __Device:__ Galaxy Note 4
4. __Version of the app:__ 0.6.73
 
I tried importing a config that contained various settings which were not treated correctly.

`resolv-retry 60` and `ifconfig-nowarn`: Automatically generated by the app, yet when imported is recognized as a custom option.

`preresolve`: Automatically generated by the app when `persist-tun` is present. In my case, it was, yet `preresolve` was recognized as a custom option.

`auth-nocache`: Present in my config, but not imported.

**Comment by schwabe** [comment]
Thanks for reporting.
