### ISSUE TITLE
[Feature Request] DNSCrypt Support

### ISSUE THREAD

**Issue by zero77** [schwabe/ics-openvpn#781]
Can you please add support for DNS crypt when selecting a custom DNS server.
Thanks

**Comment by schwabe** [comment]
No, Android does not support DNS crypt.

**Comment by zero77** [comment]
It looks like its supported on android now because, adguard android app has implemented it.
https://github.com/AdguardTeam/AdguardForAndroid/issues/1134

**Comment by schwabe** [comment]
I am not sure Adguard really is doing. I suspect that they implement their own resolver/DNS forwarder. That is not something I want to do/should be done in a normal VPN app.

**Comment by DI555** [comment]
DNSCrypt has compilled androids builds. But there's no UI. Imho it needs smth. like 'DNS Manager' to support dns sets and option to set folder of unpacked (from .zip) DNSCrypt.
