### ISSUE TITLE
Feature request: start specified VPN profile on app open

### ISSUE THREAD

**Issue by 2fst4u** [schwabe/ics-openvpn#783]
Would this be possible? To elaborate:

I want a certain VPN profile to start automatically when I open a certain app/apps. I want another profile to start automatically when I open other app/apps and I don't want these apps to ever have network connection unless that app profile has started.

**Comment by schwabe** [comment]
That is all nice and sounds certainly useful but unfortunately with the APIs that Android offers not possible
