### ISSUE TITLE
IPv6 leaks when only IPv4 is available on the OpenVPN server

### ISSUE THREAD

**Issue by athosmoreno** [schwabe/ics-openvpn#784]
# General information
1. Android Version: Android 6.0.1
2. Android Vendor/Custom ROM: Motorola
3. Device: Motorola Moto G 2th Generation
4. Version of the app (version number/play store version/self built): Play Store, 0.6.73 
 
# Description of the issue
 
I am using a VPN on Google Cloud Platform, which doesn't support IPv6 on virtual machines. My connection has IPv6 enabled.

When I use the OpenVPN Connect, my IPv6 from my ISP doesn't leak and it only shows my IPv4 address from the VPN. However, when connecting from this app, it shows my home IPv6 and the VPN IPv4.

This issue is also not reproducible on Windows 10 FCU. I am using https://wtfismyip.com to do the tests. I asked a friend to try out on his device and it is also reproducible.

![Android screenshot](https://user-images.githubusercontent.com/6440060/32530739-0074c244-c427-11e7-9310-68c7f5a97de9.png)

**Comment by schwabe** [comment]
Do you have allow local lan access enabled?

**Comment by athosmoreno** [comment]
I hadn't, but now I have and it stays the same.

**Comment by schwabe** [comment]
Can you post or send me a complete log from the client?

**Comment by athosmoreno** [comment]
Sure.

OpenVPN for Android (this app): https://gist.github.com/athosbr99/07a2a1b43368fdde5c976c6190b100bb

**Comment by schwabe** [comment]
That has "2017-11-08 11:20:45 Rotas excluídas: 192.168.25.219/24 " in it. Can you give a me a log without allow local lan access?

**Comment by athosmoreno** [comment]
Updated the gist: https://gist.github.com/athosbr99/2aa9a82ee215cea420a1f15cefc31af1

**Comment by athosmoreno** [comment]
I noticed that this app ignores the `setenv opt block-outside-dns` directive from the ovpn file. This prevents my IPv6 to leak on Windows, perhaps that could be the issue?

**Comment by schwabe** [comment]
nope that option is very windows specific. The log looks good and Android 6 should disable ipv6 when a VPN is connected :/

**Comment by athosmoreno** [comment]
OpenVPN Connect doensn't let me copy-pasta the log, so I'm gonna drop some screenshots here. It doesn't seem any different, so I don't know how it works there and here doesn't.

I added on imgur for convience, so it doesn't flood this page: https://imgur.com/a/BCYyA

**Comment by devlinzed** [comment]
I'm noticing this as well.  Let me know if there is any debug info I can provide, or steps I can take.

**Comment by christarazi** [comment]
I am also experiencing this on Android 7.1.2.

**Comment by aarnoud** [comment]
I prevented this on a setup by setting a bogus **server-ipv6** and **push "route-ipv6 xxx"** if you don't won't to bother with ipv6 connectivity and don't want to risk any local ipv6 real IP leak.

**Comment by schwabe** [comment]
Also newer version implement block-ipv6 which will then do icmpv6 reject to better make use of this.

**Comment by schwabe** [comment]
I still have no idea why openVPN connect is behaving different here. Could you try with the newest beta and check if with  OpenVPN 3 c++ core enabled, it behaves like openvpn connect (which uses that core too) or like old versions of app/OpenVPN 2.x?

**Comment by athosmoreno** [comment]
Oops, sorry for late response :(

I installed the latest beta on Google Play (0.7.3). The issue persists with OpenVPN 3 C++ Core enabled.

**Comment by schwabe** [comment]
Can you also upload the log with openvpn 3++ core? I am trying figure out what the difference between my app and OpenVPN connect is with using almost identical  OpenVPN code.

**Comment by athosmoreno** [comment]
Sure: https://gist.github.com/athosbr99/a2dedac9eebdfbf61aad9e6fbfa09f12

**Comment by schwabe** [comment]
that is with allow local network access on, right? Does allow lan access off with openvpn3 also leak ipv6?

**Comment by athosmoreno** [comment]
I am not sure of this app translation, but I deselected these two options on the app and now it doesn't leak ipv6 anymore.

![photo_2018-02-06_13-13-35](https://user-images.githubusercontent.com/6440060/35866957-b3aa5630-0b3f-11e8-9966-2f4967a5f390.jpg)
![photo_2018-02-06_13-13-40](https://user-images.githubusercontent.com/6440060/35866958-b3e1a39c-0b3f-11e8-8e05-7d1cd834d074.jpg)
