### ISSUE TITLE
TunBuilderBase mapping

### ISSUE THREAD

**Issue by supreethkm** [schwabe/ics-openvpn#785]
Hi,

I know this is not a supporting forum, still I have some general queries please guide me.

I'm using OPENVPN3 to develop VPN to Tizen platform, I have include almost all the OS level API in TunBuilderBase class, still i'm not able to route all network traffic though VPN tunnel.

Can I get the information about how android API mapping is done in TunBuilderBase class of OPENVPN3.

If you could provide me the details, it would be very greatness of you

Thank you 
Supreeth

**Comment by schwabe** [comment]
This app only has experimental support for OpenVPN3. You can see it here:  https://github.com/schwabe/ics-openvpn/blob/master/main/src/ovpn3/java/de/blinkt/openvpn/core/OpenVPNThreadv3.java
