### ISSUE TITLE
Imported key file missing

### ISSUE THREAD

**Issue by mesterj** [schwabe/ics-openvpn#788]
When I setup vpn profile copy file into internal storage. Setup the profile and test. With 0.6.73 version sometimes the imported key file is missing. And profile is not working. I re import key file and working again. I supervising more than 300 devices only 3 user complained with this problem.   
Please investigate it. Android version is 6.0. Device is Lenovo Tab 3.
 
Thank you.

**Comment by schwabe** [comment]
What kind of key setup are you using? PCKS12? Certificates? Android key store?

**Comment by mesterj** [comment]
Certificate pem format.

**Comment by schwabe** [comment]
I need some way to reproduce this. Were the certificates inline? If yes that should not happen. Otherwise if they were external files, I would guess a user errror (when only 3 out of 300 were affected)

**Comment by mesterj** [comment]
I accept your point of view. Close the ticket and if I will get some prove I will re-open.
