### ISSUE TITLE
i use your files for my personal work??   If its not free than how i paid for this??

### ISSUE THREAD

**Issue by srshah03** [schwabe/ics-openvpn#791]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
 
# Description of the issue

**Comment by schwabe** [comment]
I have no idea what you are talking about. You can use this project under the terms of GPLv2 for personal or commercial work. For other licenses contact me.
