### ISSUE TITLE
What are the advantages of OpenVPN for android vs OpenVPN connect

### ISSUE THREAD

**Issue by merlijn-sebrechts** [schwabe/ics-openvpn#792]
I'm te maintainer [an open source project to easily deploy an OpenVPN server](https://jujucharms.com/openvpn) and I'm considering which OpenVPN android client I should recommend to my users.

I've been trying to find if there are any advantages, but I can't seem to find them written down somewhere. It might be best do document this in the readme. I can create a PR to add it to the readme if you state the advantages here..?

**Comment by schwabe** [comment]
There is an FAQ entry about that. In app and here http://ics-openvpn.blinkt.de/FAQ.html. You are welcome to improve this entry if you want.
