### ISSUE TITLE
Is ics-openvpn project is compatible of connecting to L2TP IPsec PSK  server ?

### ISSUE THREAD

**Issue by Khsed4** [schwabe/ics-openvpn#793]
I want to implement an android application which it connects to an L2TP IPsec PSK server (my own server) on all smartphones that uses Android as their operating system, now the question is here: If ics-OpenVPN project can help me to connect to the following server?

**Comment by schwabe** [comment]
No

**Comment by Khsed4** [comment]
@schwabe First I know that my  question is irrelevant to this issue hence I will delete this comment after I get an answer.
 @schwabe  Do you know any project or a method that I can implement L2TP IPsec PSK Vpn for android?

**Comment by schwabe** [comment]
I think strongswan has an Android app. I think it is also GPL

**Comment by ahadcove** [comment]
Hey @Khsed4, have you found a solution yet? I'm in the same boat as you
