### ISSUE TITLE
[Feature Request] Provide a socks5 server port for user apps to use

### ISSUE THREAD

**Issue by zero77** [schwabe/ics-openvpn#795]
Can you please provide a socks5 server port so that individual user
apps may specify OpenVPN as their socks5 server to use, thereby
sending all their traffic directly into OpenVPN, with OpenVPN then
sending that traffic out over the VPN tunnel to the far side.

For example, the Tor daemon of torproject.org provides a socks5
server port for use by applications.
Thaks

**Comment by schwabe** [comment]
OpenVPN does not provide Socks and probably never will. You can already select which app go via the VPN for Android > 5.

**Comment by RichyHBM** [comment]
@schwabe Is there any chance this feature request may be reopened? Socks5 is the only way to chain VPN apps on android, which can be very useful when using things like netguard or dns55 to limit internet access to apps or to block ads
