### ISSUE TITLE
Per-app VPN support

### ISSUE THREAD

**Issue by Nikifor1303** [schwabe/ics-openvpn#796]
Hello,

Does your code/library support per-app VPN? Would it be technically possible to merge this code with my own student project to try to establish a per-app VPN connection, ideally upon starting of an app (e.g. in onCreate), while leaving the other app's communication on the phone intact?

Thanks in advance.

Niki

**Comment by schwabe** [comment]
Depends on what you with per-app. You can already select which app goes via VPN and which not. Or are you trying to use VPN to encrypt the communication of one app?

**Comment by Nikifor1303** [comment]
Hi Arne,

The second thing : I'm trying to use VPN to encrypt the communication of one app - my app. Like a "micro VPN" feature built into. The idea is to create an app that automatically establishes VPN for itself, when starting (with some "loading" splashscreen shown), and without entering/setting some other apps on my phone. Is this possible?

Thanks

**Comment by schwabe** [comment]
You still need to use the system VPN service if you base it on my source code. IT is probably better to use https to encrypt the traffic of only one that you control.

**Comment by Nikifor1303** [comment]
OK, thanks.

Here's an idea : when I go to Edit profile->Allowed Apps tab, and move the switch to say "VPN is used for only for selected apps", and if I selected the app itself in the list "OpenVPN for Android" will I achieve what I want? Of course, I will drop your UI and replace it with mine, while keeping all the other background logic from your code. 

If not, do you know some Android libraries I could use to achieve this? Any help much appreciated.

Sorry, still a student :)

Thanks

**Comment by schwabe** [comment]
@Nikifor1303 sure but you still get all the other nastyness that a VPN app with it. For normal apps that would be very irretating for the user.

For normal encrypted communiction just read up on SSL/TLS and HTTPS under Android. No reason to reinvent the wheel.
