### ISSUE TITLE
Wrong routing

### ISSUE THREAD

**Issue by dymm2000** [schwabe/ics-openvpn#802]
# General information
1. Android Version 7.1.2
2. Android Vendor/Custom ROM MIUI 8.5.4
3. Device Xiami Redmi 4X
4. Version of the app (version number/play store version/self built) 0.6.73
 
# Description of the issue
VPN network is 10.20.0.0. Another local network 10.10.0.0 connected via server, but app does not routing packets thru VPN.
Either Wifi connected (wifi is 10.0.0.0) or not.
 
OpenVPN Connect routes correctly.
 
Routing table (ip4) looks the same for both apps.
For ip6 slightly different.

**Comment by schwabe** [comment]
Can you post logs of both apps?

**Comment by dymm2000** [comment]
I think I understand the problem. Here is the description:
https://openvpn.net/index.php/open-source/faq/77-server/273-qifconfig-poolq-option-use-a-30-subnet-4-private-ip-addresses-per-client-when-used-in-tun-mode.html
When I made push route to gateway 10.20.0.5 instead of 10.20.0.1 it worked well
Was: push "route 10.10.0.0 255.255.255.0 10.20.0.1 50"
Now: push "route 10.10.0.0 255.255.255.0 10.20.0.5 50"

Ignoring pushed routes also helps. So I think OpenVPN Connect just does not actually push routes.

**Comment by schwabe** [comment]
This sounds more like a misconfured server config, especially since fixing the gateway ip fixes the problem
