### ISSUE TITLE
Feature request: add askpass option

### ISSUE THREAD

**Issue by montaqa** [schwabe/ics-openvpn#803]
Hi,

Can we parse the passphrase password (askpass) in the ovpn file in the same way auth-user-pass is supported today i.e. 
```
<askpass>
password
</askpass>
```

**Comment by schwabe** [comment]
I am not sure you need askpass in a client.

**Comment by montaqa** [comment]
OK, maybe i do not need it. i resolved my issue by creating password-less certificate. initially i was creating a certificate type and the app is requesting the passphrase all the time.
