### ISSUE TITLE
AUTH_FAILD saving choice bug

### ISSUE THREAD

**Issue by kotkotov** [schwabe/ics-openvpn#805]
# General information
1. Android Version 8.1
2. Android Vendor/Custom ROM Nitrogen OS
3. Device xiaomibRedmi note 3
4. Version of the app (version number/play store version/self built) gp latest
 
# Description of the issue
 Hello. In the main settings in profile after user name and password strings,  options AUTH_FAILD, don't saving choice after closing settings, always "disconnect and forgot password" but i need "ignore and reconnect"

**Comment by schwabe** [comment]
Fixed in current code (not yet released)
