### ISSUE TITLE
DNS resolution through tunnel

### ISSUE THREAD

**Issue by brianjmurrell** [schwabe/ics-openvpn#807]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. 7.1
2. LineageOS 14.1
3. LG G3
4. 1.1.25 (build 94)
 
# Description of the issue
First/main issue is to understand what the status of DNS should be when the tunnel is established.

Ideally I would like split DNS where Android is smart enough to send lookups for domains local to the VPN'd to subnet to the VPN server for the subnet and all else to the DNS configured by the network provider (i.e. mobile or WiFi provider).  I don't believe Android is capable of this but it would be nice if it were.  It could use dnsmasq or unbound, or even bind9 to do this, although something like bind9 is pretty heavy for that task.

Given the lack of proper split DNS support in Android, I would like all DNS queries to go to the DNS server of the VPN'd subnet, as the `push "dhcp-option DNS ..."` does for Windows clients.  To that end, I have tried this option in my server's config and while a small number of DNS queries seem to follow that setting, the majority of them still use the DNS servers that one sees when one does `getprop | grep dns`.

Is having any level of useful DNS resolution with the/this/any OpenVPN client at all possible?

**Comment by schwabe** [comment]
The majority should use the VPN servers. getprop is not used by android itself at all. Only legacy apps that bring their own outdated resolver lib that does not use the new calls uses the getprop dns.
