### ISSUE TITLE
submodule openvpn 61ec1d3207a058b29eb8c463550dc5958cf0e386

### ISSUE THREAD

**Issue by abrahamturing** [schwabe/ics-openvpn#809]
Hello,

I am trying to play with your awesome project, but could not succeed fetching submodules. It says:

```
fatal: reference is not a tree: 61ec1d3207a058b29eb8c463550dc5958cf0e386
Unable to checkout '61ec1d3207a058b29eb8c463550dc5958cf0e386' in submodule path 'main/openvpn'
```

Is it possible that a commit is not pushed in openvpn module, as in #529 issue?

Thanks in advance.

**Comment by schwabe** [comment]
Yeah, will be fix with new release
