### ISSUE TITLE
[SECURITY] Google Play, other releases require update to OpenSSL 1.1.0g for security and bug fixes

### ISSUE THREAD

**Issue by rmenessec** [schwabe/ics-openvpn#811]
# General information
n/a; applies to all Android devices
 
# Description of the issue
App requires update / recompile from OpenSSL 1.1.0f to OpenSSL 1.1.0g. 1.1.0g release notes are [here](https://www.openssl.org/news/openssl-1.1.0-notes.html).

**Comment by schwabe** [comment]
THe security advisory does not affect the app:

> This only affects processors that support the BMI1, BMI2 and ADX extensions like Intel Broadwell (5th generation) and later or AMD Ryzen. 

OpenSSL 1.1.0g will be part of the next normal release

**Comment by rmenessec** [comment]
> This only affects processors that support the BMI1, BMI2 and ADX extensions like Intel Broadwell (5th generation) and later or AMD Ryzen.

Android runs on these processors.

**Comment by schwabe** [comment]
Yeah. But Intel devices are already rare and all that I know of (Google Nexus TV is the newest of them) have older CPUs. There will a be new version soon anyway.
