### ISSUE TITLE
"Behaviour on AUTH_FAILED" is always "Disconnect, forget password"

### ISSUE THREAD

**Issue by rmenessec** [schwabe/ics-openvpn#812]
# General information
1. 7.1.2r36 / 14.1 - [20171222](https://mirrorbits.lineageos.org/full/shamu/20171222/lineage-14.1-20171222-nightly-shamu-signed.zip)
2. [LineageOS](https://lineageos.org/)
3. [Google Nexus 6](https://wiki.lineageos.org/devices/shamu)
4. 0.6.73 (Google Play)
 
# Description of the issue
"Behaviour on AUTH_FAILED" is always "Disconnect, forget password". All profiles were imported from known-good OpenVPN config files for Linux. No matter which option is chosen, the setting reverts to "Disconnect, forget password". There are no other problems. OpenVPN for Android behaves correctly otherwise, and VPN sessions appear to work correctly.

Please consider changing the default to "Disconnect, keep password". My assigned VPN password is exceptionally long, and can only be set reasonably by copying and pasting from a text file.

Extra custom settings, if needed:
```
# These options found in the config file do not map to config settings:
ns-cert-type server 
explicit-exit-notify 3 
mute 3 
hand-window 17 
resolv-retry 16 
tls-cipher TLS-DHE-RSA-WITH-AES-256-CBC-SHA 
key-method 2 
down-pre 
reneg-sec 0 
```

**Comment by schwabe** [comment]
Fixed in next release.

**Comment by rmenessec** [comment]
Is the fix available in the current beta?

**Comment by schwabe** [comment]
No.
