### ISSUE TITLE
a problem about making 

### ISSUE THREAD

**Issue by v515527946** [schwabe/ics-openvpn#817]
Now I have got the right source code from the gitub,but at the end of making,there apperas a new problem:
openvpn//src/openvpn/init.c:123: error: undefined reference to 'setenv_str'
openvpn//src/openvpn/init.c:125: error: undefined reference to 'setenv_str'
openvpn//src/openvpn/init.c:126: error: undefined reference to 'setenv_int'
openvpn//src/openvpn/init.c:127: error: undefined reference to 'setenv_int'
openvpn//src/openvpn/init.c:128: error: undefined reference to 'setenv_str'
openvpn//src/openvpn/init.c:131: error: undefined reference to 'setenv_str'
What makes this problem and how to solve it?
Thanks

**Comment by schwabe** [comment]
Current master is not expected to build nicely stick to last released version.
