### ISSUE TITLE
changing the openssl version in android app

### ISSUE THREAD

**Issue by raghavkmr** [schwabe/ics-openvpn#819]
To make issues more manageable, I would appreciate if you fill out the details if applicable

# General information
1. Android Version : Nougot
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self built)
 
# Description of the issue
 Hi ,
I have build the app in android studio as per the source code ,but its having openssl version 1.1.0g ,where as i want 1.0.1n ,How to change it.

**Comment by schwabe** [comment]
Changing the openssl version is not so trivial. This sounds like X for Y problem. See https://meta.stackexchange.com/questions/66377/what-is-the-xy-problem

**Comment by raghavkmr** [comment]
thanks
