### ISSUE TITLE
compress lz4

### ISSUE THREAD

**Issue by glith** [schwabe/ics-openvpn#823]
Hello,
Any plans to add an option to enable lz4 compression instead of lzo?

Thanks.

**Comment by schwabe** [comment]
LZ4 compression is already enabled. And servers can check IV_LZ4 if the clients supports it and then push compress lz4-v2. See also http://plai.de/android/peerid.py

Note that compression nowadays is almost worthless sind most communication is either compressed already (big downloads) or encrypted.
