### ISSUE TITLE
OpenVPN 3 core + redirect-gateway + ipv4 + ipv6 is not working

### ISSUE THREAD

**Issue by sergeygalkin** [schwabe/ics-openvpn#824]
# General information
Android Version - 8.0
Android Vendor - HTC
Device - U11
Version of the app - play store version - 0.6.0
 
# Description of the issue
Then I try to use OpenVPN 3 core with server with redirect-gateway and IPv6 
```
dev tun-ipv6
topology subnet
server 10.255.254.0 255.255.255.0
server-ipv6 fdff:e025:9136:fff4::/64
push "redirect-gateway def1"
push "redirect-gateway ipv6"
```
Openvpn is connecting but not using. All traffic goes not through vpn. Without 
'OpenVPN 3 core' all working but I have https://github.com/schwabe/ics-openvpn/issues/822
 
Logs without 'OpenVPN 3 Core' - https://gist.github.com/sergeygalkin/3585a91633a93d0460088f8b3ed4ac52
Logs with 'OpenVPN 3 Core'  - https://gist.github.com/sergeygalkin/b4aa2dc8f4ac00cac2037101018ca84b

**Comment by schwabe** [comment]
Hm, I am bit surprised that it works with OpenVPN 2.x. 

Can you try to use push "redirect-gateway def1 ipv6" and see if that changes OpenVPN3 behaviour?

Never mind. I found the problem

**Comment by sergeygalkin** [comment]
with "redirect-gateway def1 ipv6"  ( and with only  "redirect-gateway ipv6" also nothing changed) . OpenVPN 2.x. is working, OpenVPN 3 is not. Switched to stable version 0.6.73, this solve all my issues.
