### ISSUE TITLE
Google Play store app lags behind recent releases

### ISSUE THREAD

**Issue by tomschlenkhoff** [schwabe/ics-openvpn#826]
The Google Play store app version is outdated (6 month old).
Did you stop releasing there?
Do you recommend local releases or other repos to stay up-to-date?

**Comment by schwabe** [comment]
The Google Play app version is still the most current version. Please understand that for a project that run is run by just one person personal thing, might be more important at some times. 

However, a new version is coming up sometime soon and you can already get the Beta from the beta channel in Play.
