### ISSUE TITLE
Add an ability for the quicktile to bring up a selection of connections

### ISSUE THREAD

**Issue by bfayers** [schwabe/ics-openvpn#828]
Add functionality that would result in the quicktile producing a popup of different VPN connections that can be connected to rather than just connecting to the default.

**Comment by schwabe** [comment]
I never seen any other app do something like that. And also there is no API to have a larger selection screen like WiFi and Bluetooth are using.

**Comment by bfayers** [comment]
If the app had draw over other apps wouldn't the quicktile just be able to invoke a popped up dropdown box with an ok/cancel button?

**Comment by schwabe** [comment]
At the moment I am not going to implement something like this. I might reconsider if Android gets an API to show a selection in a quicktile

**Comment by bfayers** [comment]
Sounds good, rather annoying that the api is non-existant for the larger selection screens...
