### ISSUE TITLE
Cannot use Google Authenticator two-factor

### ISSUE THREAD

**Issue by mrz1836** [schwabe/ics-openvpn#831]
1. Android Version
7.1.1

2. Android Vendor/Custom ROM / Device
Model: SM-T350
Device: Galaxy Tab A

3. Version of the app (version number/play store version/self-built)
Version: 0.6.73

# Our Issue:
So we use Google Authenticator in our setup. Right now we are unable to connect via the OpenVPN android client. The auth_failure occurs. We do not get prompted to enter the two-factor code.

Here is an example:
https://medium.com/@egonbraun/using-google-authenticator-mfa-with-openvpn-on-ubuntu-16-04-774e4acc2852

Please advise - thanks!

**Comment by schwabe** [comment]
Well that setup looks like you just enter your 2FA code as password. You should not check the save password box.

**Comment by jayb-g** [comment]
@mrz1836 
As @schwabe suggested, you should keep save password unchecked. And enter password+otp as the password every time you want to connect. eg if your password is 'passw' and otp is '123456', you should enter 'passw123456' as password. Weird but that's how openvpn works with two factor codes.

**Comment by mcepl** [comment]
Unfortunately even with this trick I get this error in the connection log:

```
01:46 AUTH: Received control message: AUTH_FAILED,CRV1:R,E:something=:somethingelse=:Enter Your OTP Code
```

Any more thoughts?
