### ISSUE TITLE
feature request: cipher AES-256-CFB

### ISSUE THREAD

**Issue by CesarPantoja** [schwabe/ics-openvpn#835]
Greetings! Thanks for an amazing project.
I have a profile which I can not change, which uses AES-256-CFB as a cipher, but when I try to use it, I get a "Cipher 'AES-256-CFB' mode not supported". 
Any chance to add this cipher to the app?

Thanks a lot!

**Comment by schwabe** [comment]
cipher mode is the same as in upstream openvpn. If it works with normal openvpn it should work here too.

**Comment by schwabe** [comment]
Sorry double checked and it is actually my fault. Will be in the next version
