### ISSUE TITLE
OpenVPN 3 core doesnt work

### ISSUE THREAD

**Issue by TheBestTheBestTheBest** [schwabe/ics-openvpn#836]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android 8.0 & android 7.0
2. EMUI 6 and EMUI 5.0
3. Mate 9 & Mediapad M3
4. Play store Betta 0.7.3
 
If i ever use OpenVPN core 3 i just get
"connect() error: : alias == null

This is the Config File:
https://github.com/cryptostorm/cryptostorm_client_configuration_files/blob/master/linux/cstorm_linux-rome_udp.ovpn

If using the standard OpenVPN 2 core i get no issues.

**Comment by schwabe** [comment]
can you export the full log? (share button in the log window)

**Comment by TheBestTheBestTheBest** [comment]
[Log.txt](https://github.com/schwabe/ics-openvpn/files/1683555/Log.txt)
Here it is, just made it again
