### ISSUE TITLE
Cannot auto-reconnect

### ISSUE THREAD

**Issue by TheBestTheBestTheBest** [schwabe/ics-openvpn#837]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. 8.0
2. EMUI 6.0
3. Mate 9 C432
4. 0.7.3
 
When changing from 3G/4G to wifi and back, it often doesn't get to restard automatically the connection to the VPN.
Accident happens often. Here is a log of it:

This is the config file used:
https://github.com/cryptostorm/cryptostorm_client_configuration_files/blob/master/linux/cstorm_linux-rome_udp.ovpn

**Comment by schwabe** [comment]
```
2018-01-29 07:52:44 Impossibile accedere all'interfaccia tun
2018-01-29 07:52:44 Errore:Cannot bind de.blinkt.openvpn.core.OpenVPNService
2018-01-29 07:52:44 MGMT: Got unrecognized command>FATAL:ERROR: Cannot open TUN: Permission denied (errno=13)
2018-01-29 07:52:44 2 variation(s) on previous 3 message(s) suppressed by --mute
2018-01-29 07:52:44 MANAGEMENT: Client disconnected
2018-01-29 07:52:44 ERROR: Cannot open TUN: Permission denied (errno=13)

```

That seems to be the error. I have seen this kind of error before. Tun opening problem are usually ROM problems in my experience.

**Comment by TheBestTheBestTheBest** [comment]
Is it related to the android 8.0 or EMUI 6.0? or both?

**Comment by schwabe** [comment]
I have no idea, I never seen this error. Might be emui related. My Android 8 devices work fine.

**Comment by OlegAndreych** [comment]
Do we really need to stop trying after some error like that occurs?
I have same issue on Huawei P10 Plus / Android 8.0 / EMUI 8.0 / OpenVPN for Android 0.7.4.

**Comment by schwabe** [comment]
Sure when Android reports a fatal error opening the tun device there is nothing the app can do. The firmware in this issue is just broken

**Comment by TheBestTheBestTheBest** [comment]
Addendum: using ecc config files from cryptostorm the issue is mitigated because the app doesn't need to reconnect on connection type change bypassing the issue.
Blame is on huawei i think at this point.

**Comment by sso-klump** [comment]
I have the same problem on my Huawei mate 10 pro (android 8.0), and I have also feedback from users running Android 8 on a Samsung phone that they see the same.
