### ISSUE TITLE
After cloning last version the app cannot start

### ISSUE THREAD

**Issue by Moussawi90** [schwabe/ics-openvpn#838]
# General information
1. Android Version : Nougat (7.0)
2. Android Vendor/Custom ROM : LG Stock ROM
3. Device : LG V20
 
# Description of the issue

> Error while executing: am start -n "de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=de.blinkt.openvpn/.activities.MainActivity }
Error type 3
Error: Activity class {de.blinkt.openvpn/de.blinkt.openvpn.activities.MainActivity} does not exist.

Error while Launching activity

**Comment by schwabe** [comment]
I have honestly no idea what is happening there.
