### ISSUE TITLE
'SWIG_EXECUTABLE-NOTFOUND' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by 1usman** [schwabe/ics-openvpn#840]
**Error:FAILURE**: Build failed with an exception.

* What went wrong:
Execution failed for task ':main:externalNativeBuildNoovpn3Debug'.
> Build command failed.
  Error while executing process D:\UserData\Installations\Android\SDK\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\Android\Fiverr\git\ics-openvpn\main\.externalNativeBuild\cmake\noovpn3Debug\x86_64 --target ovpn3}
  [1/4] Generating ovpncli_wrap.cxx
  FAILED: cmd.exe /C "cd /D D:\Android\Fiverr\git\ics-openvpn\main\.externalNativeBuild\cmake\noovpn3Debug\x86_64 && D:\UserData\Installations\Android\SDK\cmake\3.6.4111459\bin\cmake.exe -E make_directory ovpn3 && **SWIG_EXECUTABLE-NOTFOUND** -outdir ovpn3 -c++ -java -package net.openvpn.ovpn3 -outcurrentdir -ID:/Android/Fiverr/git/ics-openvpn/main/src/main/cpp/openvpn3/client -ID:/Android/Fiverr/git/ics-openvpn/main/src/main/cpp/openvpn3 D:/Android/Fiverr/git/ics-openvpn/main/src/main/cpp/openvpn3/javacli/ovpncli.i"
  'SWIG_EXECUTABLE-NOTFOUND' is not recognized as an internal or external command,
  operable program or batch file.
  ninja: build stopped: subcommand failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

I have installed the SWIG_EXECUTABLE and its working fine on Command Prompt.

**Comment by schwabe** [comment]
Then the PATH Android studio uses is probably not correct.  Try running gradlewfrom the command line

**Comment by neighbads** [comment]
set the SWIG_EXECUTABLE and SWIG_DIR

you should remove dir "ics-openvpn\main\.externalNativeBuild"

**Comment by kay14** [comment]
I am facing the same issue.
@1usman did you resolve this issue. If yes, please let me know how.
Thanks in advance

**Comment by 1usman** [comment]
Unfortunately I can't. I preferred using a linux machine and got my result.

**Comment by kay14** [comment]
@1usman were you getting this error on windows by any chance?

**Comment by 1usman** [comment]
I'm no more using windows for this project. Try using a linux machine, its
too easy to configure with few commands only.

**Comment by kay14** [comment]
I don't have a Linux machine and won't be able to install Linux on the existing system as well. @1usman @schwabe any suggestions how to fix this issue.
Thanks in advance.

**Comment by 1usman** [comment]
Fiverr.com/Ali009
Contact me, I can help you there.

**Comment by schwabe** [comment]
On my windows machine it builds fine as long as swig is in PATH. But building takes ~30 minutes compared to 3 minutes on Linux on the same machine, no idea why.

**Comment by kay14** [comment]
swig is there in PATH. I can assure you that. I checked it with cmd as well and its working fine

**Comment by kay14** [comment]
I have the following value in PATH - C:\swigwin-3.0.12\swig, and it is accurate

**Comment by schwabe** [comment]
Then the swig find macro might not work for you. You probably have to debug what is wrong there. Btw. you can also use the Ubuntu for Windows as workaround

**Comment by kay14** [comment]
@schwabe Thanks. It works like a charm on Mac. Installed it on my friend's mac.
Will try it out on Ubuntu.

**Comment by ponnamkarthik** [comment]
Try this it worked for me

inside [main/src/main/cpp/CMakeLists.txt](https://github.com/schwabe/ics-openvpn/blob/master/main/src/main/cpp/CMakeLists.txt)

modify line no : 33

 COMMAND ${SWIG_EXECUTABLE} -outdir ovpn3

to 

 COMMAND swig -outdir ovpn3

**Comment by DavidSonNguyen** [comment]
@PonnamKarthik I tried, but it didn't work for me. Do you have other way? Thanks
