### ISSUE TITLE
VPN app randomly being killed and disconnected

### ISSUE THREAD

**Issue by Bradley168** [schwabe/ics-openvpn#841]
# General information
1. Android Version: 7.0
2. Android Vendor/Custom ROM: Peacocktion
3. Device: Samsung Galaxy S6
4. Version of the app: self-built v0.6.52
 
# Description of the issue
Keep VPN app with connected state and waits for a several days(2+ days in my testing) with normal use - At one moment you can no longer see the VPN key icon and the VPN app itself is not running in the background.

**Comment by schwabe** [comment]
anything in the log of the app or in logcat? This is hard to debug otherwise I am afraid. I had multiple day long connections on my devices without problems, so there is no general known problem here.
