### ISSUE TITLE
Open VPN always getting "Notification Error" in 8.1

### ISSUE THREAD

**Issue by BrainlabDev** [schwabe/ics-openvpn#842]
**General information**
Android Version: 8.1 Custom ROM
Android Vendor/Custom ROM: LineageOS
Device: Samsung Galaxy Note 5

**Description of the issue**
When  I connecting a vpn, getting this error.
I changed my files for Android OREO channel notification got it from your files
My core files nearly same for your vpncore*
But always seeing this problem:

```
 Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=openvpn_newstat pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x14a color=0x00000000 category=service actions=2 vis=PRIVATE)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
```

**This is my OpenVPNService.Java**

https://pastebin.com/uusX6sRr

**Comment by schwabe** [comment]
Your problem is probably the "nearly the same". Without having more information or your complete source code I am not able to help you.

**Comment by BrainlabDev** [comment]
Sorry about that. Main problem is in SmartVPNService.java about Android Oreo create channel and create notification...


So, changed my SmartVPNService.java for your files exactly same for oreo notification. But always getting this message
```
 Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=openvpn_newstat pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x14a color=0x00000000 category=service actions=2 vis=PRIVATE)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1768)
```

I think this problem channel =openvpn_newstat section.

So let's check it out my codes* 


Marked for openvpn_newstat*

![screenshot_5](https://user-images.githubusercontent.com/34866374/36258907-7c1656e4-126d-11e8-95e2-dff5e8ebf763.png)


Then.. marked again*

![screenshot_6](https://user-images.githubusercontent.com/34866374/36259001-d556e606-126d-11e8-9cf5-a252625b3b36.png)


![screenshot_7](https://user-images.githubusercontent.com/34866374/36259143-43854622-126e-11e8-808c-767ad80072fc.png)

Everything is good...
![screenshot_8](https://user-images.githubusercontent.com/34866374/36259198-7b41ca40-126e-11e8-9975-d963f3d6677a.png)


And here core repository

https://github.com/BrainlabDev/brainlabdev.github.io/tree/master/SmartVPNCore

**Comment by schwabe** [comment]
@BrainlabDev you still shared only a part of your source in that repository. Since the license of this app is GPLv2 you are required to share the whole source code of your app anyway (unless you buy an extra license from me).

Also https://www.smartvpn.com/en/ looks very commercial. See the first FAQ in here: https://github.com/schwabe/ics-openvpn/blob/master/doc/README.txt

**Comment by BrainlabDev** [comment]
Here full code

Also, I mentioned your project in my app  👍 

https://github.com/BrainlabDev/SmartVPN

Please tell me what's wrong in notification section*...
