### ISSUE TITLE
Error:A problem occurred configuring project ':main'. (import com.android.builder.model.ProductFlavor )

### ISSUE THREAD

**Issue by francescovigot** [schwabe/ics-openvpn#843]
hello 
I took a screenshot from my error its about importing com.android.builder.model.ProductFlavor on gradle file , I would be appreciated if someone tells me what should i do?

![capture](https://user-images.githubusercontent.com/29005428/36279427-57005c08-12ac-11e8-8c1e-fbae8091928d.PNG)

**Comment by schwabe** [comment]
That is not your real error. AS already tells you to open messages view to see the log and the real error.

**Comment by schwabe** [comment]
Also double posting (https://forums.openvpn.net/viewtopic.php?f=33&t=25828) will not get you different answers but only annoys me

**Comment by eleguni** [comment]
Im so sorry ,I didnt mean annoy you, I would be thankful if you could guide me 

this the log error

[idea.log](https://github.com/schwabe/ics-openvpn/files/1731969/idea.log)

**Comment by francescovigot** [comment]
I'm So sorry , I didn't mean annoy you, I would be thankful if you could guide me
this is the log error
[idea.log](https://github.com/schwabe/ics-openvpn/files/1732095/idea.log)

**Comment by schwabe** [comment]
you need to check the gradle error log or build log.
