### ISSUE TITLE
Navigation Freezes Browsing SDCard

### ISSUE THREAD

**Issue by jsgates** [schwabe/ics-openvpn#844]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version - Version 7.0o), Kernel Version 3.10.96+
3. Device - Nvidia Shield TV (2017)  (Model # P2897)
4. Version of the app (version number/play store version/self-built) - OpenVPN for Android 0.6.73
 
# Description of the issue

When attempting to browse the sdcard to load an OpenVPN profile, once the directory/file browser window opens, the application appears to freeze or hang for 5 - 10 minutes before it responsive again and allows you to select a profile to load.  Once it responds, loading the profile, saving it, and then connecting to VPN is smooth.  However, for each additional server profile you try to add you are stuck waiting for the app to become responsive again in the directory/file browser.

**Comment by schwabe** [comment]
Do you have any unresponsible smb shares mounted or anything else? My Shield TV does not exhibit this behaviour... 

Btw. are you getting the ugly browser (fallback from the app) or the file browser from the shield itself? (left side you have a selection of drives/storage providers)

Btw. as workaround you can open ovpn files from a file explorer and circumvent the file browser of the app.
