### ISSUE TITLE
Certificates not found using relative paths

### ISSUE THREAD

**Issue by neomathews** [schwabe/ics-openvpn#846]
# General information
Android 7.0NRD90M
Miui Global 9.2 | Estable 9.2.1.0(NAAMIEK)
Xiaomi mi5
Vpn for Android 0.6.73
# Description of the issue
I don't know if it is an issue but if you write only relative paths to the certs and keys in the conf file and import it from the app it doesn't found the files and you have to specify them by hand. With absolute paths works like a charm.

**Comment by modfiles** [comment]
rather than using a relative path, make your easier by making the cert, key and perm inline. its even indicated in README file

**Comment by schwabe** [comment]
The whole cert finding code is a mess and a best effort. Handling relative paths is a lot more complicated than it looks on the surface. I think this more of an edge. If you don't want to deal with external files (which is also good on desktop) use inline certificates.
