### ISSUE TITLE
BindService returns false

### ISSUE THREAD

**Issue by AjmalPL** [schwabe/ics-openvpn#848]
# General information
1. Android Version - All versions including 4.4, 6.0, 7.x,8.x
2. Stock Rom
3. Device - Nexus 5 , Galaxy Tab , Nexus 6p 
4. Version of the app (version number/play store version/self-built)
 
I had open vpn compiled in my PC, I have worked with it and tested a couple of .ovpn files. Everything was working fine. Until after around 5 months, when i re-opened the project, The bind service returns a false and service doesn't start. I have checked the logs and there's no error or anything in the logs. I also made sure the service tag is defined properly in Android Manifest. 
Last time when this project was working, i didn't made any commit that could have kept the service from running. 
Note: i also installed the original openvpn app as it is required for the service to start, still same issue. 

`Intent icsopenvpnService = new Intent(IOpenVPNAPIService.class.getName());
 icsopenvpnService.setPackage("de.blinkt.openvpn");
           boolean isCOnnected = getApplicationContext().bindService(icsopenvpnService, mConnection, Context.BIND_AUTO_CREATE);
  Log.i(Utils.TAG_CRASH_START, "isConnected = " + isCOnnected);` 

**NOTE** I tried to recompile the project for ubuntu again. I was previously following this tutorial [Compilation Tutorial](https://www.youtube.com/watch?v=gBMhaCujwrM), the last step says  

> Do cd main;./misc/build-native.sh in the main directory of the project.

In the fresh pull, when i looked into misc, there's no build-native.sh (there was build-native.bat however) ,
Is there no need to run this executable file anymore ? or it just missing ?

**Comment by schwabe** [comment]
That compilation tutorial is outdated and the current readme also does not mention that script anymore (https://github.com/schwabe/ics-openvpn/blob/master/doc/README.txt).

Double check that you have not changed the package name of IOpenVPNAPIService. For me the same code works fine in the remoteExample app. Does the remoteExample app also fail for your?

**Comment by AjmalPL** [comment]
Thank you..I rechecked the package name its same. 
However, i compiled the latest code of your example, and the remote Example works fine.
