### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by TheBestTheBestTheBest** [schwabe/ics-openvpn#849]
Hi, i tried compiling the app since there hasn't been an update in either the google play beta or f-droid. Since i'm nost knowledgeable with app compiling i failed after hours of trying to follow online guides.
Can you post a "easy a total scrub can do it" guide to compile the app, or simply compile it and put it on the beta channel?
Thanks in advance

**Comment by schwabe** [comment]
The app is already on the beta channel. And the doc/README already explain what to do to compile it.
