### ISSUE TITLE
On Android 8.1, Many Google Apps No Longer Recognize VPN Connection

### ISSUE THREAD

**Issue by ourichermath** [schwabe/ics-openvpn#851]
General Information:
1.  Android 8.1.0 (starting with initial release, but I'm currently on the February 5, 2018 Security Patch and it still happens).
2.  Plain ol' vanilla Google Android
3.  Nexus 6P
4.  Play Store version of OpenVPN for Android 0.6.73

Description:
Starting with the initial release of Android 8.1.0 on my Nexus 6P, many Google apps stopped recognizing my WiFi connection on the phone while OpenVPN for Android had the VPN connection up.  The most obvious problem for me was with Google Photos.  Unless I turn off the VPN, Google Photos will not recognize the WiFi connection and will refuse to backup/upload my photos.  I'm not sure if it's related, but the Play Store, itself, will no longer automatically update apps.  I've also seen an Android bug report that people can't download music via Google Play Music.  Here's a link to the "Doesn't Recognize Wi-Fi Connected When Using VPN" bug report:

https://issuetracker.google.com/issues/68657525

Personally, I think this is an Android 8.1 problem.  But, Google just came back in that bug report and said they won't fix it because it's intended behavior:

"Status: Won't Fix (Intended Behavior)
When a VPN is up the OS has no way to guarantee that network traffic will go on wifi. The VPN app could decide to send and receive traffic on any available interface, including cell data. Recent changes to the VPN code have made it so that if the VPN calls setUnderlyingNetworks, the networking APIs will reflect some of the properties of the underlying networks (e.g., whether they are metered or not) into the VPN's networkcapabilities. But it's up to the podcast app to use the required APIs, such as isActiveNetworkMetered."

**Comment by hkarpf** [comment]
+1

**Comment by schwabe** [comment]
I think so too because this issue is going to be fixed in Android P: https://developer.android.com/preview/behavior-changes.html#network-capabilities-vpn

**Comment by forabi** [comment]
This does not seem to be fixed on P. Maybe it requires some change on this app's side?

**Comment by schwabe** [comment]
Yeah, this is a typical case from a developer trying to be clever without understanding the whole picture and assuming that there is only WIFI and Mobile connection.
