### ISSUE TITLE
Disable spell check

### ISSUE THREAD

**Issue by adnidor** [schwabe/ics-openvpn#852]
# General information
1. Android Version

Android 7.1

2. Android Vendor/Custom ROM

Lineageos 14

3. Device

Oneplus 3

4. Version of the app (version number/play store version/self-built)

Fdroid 0.6.73
 
# Description of the issue

Spell checking is enabled in some input fields. I verified that the "Profile Name" and "remote certificate subject" fields are affected, but there may be more.

This makes editing a pain because Android doesn't allow the Cursor to be placed on a word it has deemed "wrong".

**Comment by schwabe** [comment]
This is the type set of the input field (https://developer.android.com/reference/android/text/InputType.html). Both fields have the type set to text.

I have absolutely no problem placing the cursor on a wrong word on any of my devices.

**Comment by adnidor** [comment]
Video of problem here: https://imgur.com/a/k0cfe

It's not a huge problem, but it seems easily fixable by not setting TYPE_TEXT_FLAG_AUTO_COMPLETE

**Comment by adnidor** [comment]
Sorry, I meant TYPE_TEXT_FLAG_AUTO_CORRECT

And it would maybe not even help. Changing the Type to TYPE_TEXT_VARIATION_URI may.

**Comment by schwabe** [comment]
But uri is really for uris and neither of these fields are URI. And at least for the name of the VPN connection I think the behaviour with autocomplete is exactly what I want. Profile names like company vpn or home vpn and so on are perfectly acceptable. The autocorrect type is not set at the moment. The current type is type="text" which should be the same as setting only TYPE_CLASS_TEXT

**Comment by adnidor** [comment]
For the Profile name, ok. 
But the remote certificate subject field is almost universally a FQDN, while still not quite an URI, URI is a better match than plain text.

**Comment by vgaetera** [comment]
Confirm for Custom Options.
Autocorrect there is evil for sure.
