### ISSUE TITLE
Ignore, retry on AUTH_FAILED not working

### ISSUE THREAD

**Issue by lllmio** [schwabe/ics-openvpn#853]
1. Android Version
5.1.1
2. Android Vendor/Custom ROM
PAC ROM (Custom ROM)
3. Device
TCL P561U
4. Version of the app (version number/play store version/self-built)
0.6.73 and 0.7.3 

Option to Ignore, retry on AUTH_FAILED isn't working

on 0.6.73 when I set Ignore, retry, return to connections list and then open connection settings again it shows Disconnect, forget password and behaves like Disconnect, keep password.
on 0.7.3 it shows like Ignore, retry is set, but again behaves like Disconnect, keep password. 
I get 
21:32 AUTH: Received control message: AUTH_FAILED
21:32 SIGTERM[soft,auth-failure] received, process exiting
and have to manually reconnect after that. This happens every time when phone switches between wifi/cell network or just loses network.
I have such behaviour using vpn from free protonvpn.com account, so you may test it there too.

**Comment by schwabe** [comment]
As workaround until a new version is up puth auth-retry nointeract as custom option in the config
