### ISSUE TITLE
Error parsing IPv4 address, when using static keys

### ISSUE THREAD

**Issue by omitter** [schwabe/ics-openvpn#854]
# General information
1. 7.1.2
2. LineageOS
3. Nexus 7 2011 and Motorola G4 Plus
4. 0.6.73
 
# Description of the issue

When creating a new configuration, selecting "static keys" for authentication, selecting it at "Authentication/Encryption>TLS Auth File" I get this error: "Error parsing the IPv4 address". The IPv4 address is perfectly fine and the key file is working on my computer and in another profile. Some versions ago (Openvpn App and Android) I was able to create a configuration with exact the same key file. The old configuration is still working, I just can't create a new one (with both devices, was able to copy the old configuration though).

**Comment by schwabe** [comment]
You failed to mention what exactly you put into the IPv4 address field. Common error here is to try to specify the gateway too like OpenVPN itself does with ipconfig.

**Comment by omitter** [comment]
I'm sorry. I tried a domain name and an IPv4 address (without subnet). Like this: "123.123.123.123". Even the default "openvpn.example.com" does not work.

**Comment by schwabe** [comment]
You need to provide more details, at the moment I cannot reproduce this.

**Comment by omitter** [comment]
Now that I restarted the device, the point of failure changed. Whenever I select the static key file (Authenication/Encrytion→TLS Auth File) the app crashes without a message. The error message in the generated config tab is still complaining about the IPv4 address though.

My keyfile is of the following format. Which file name extension does it need? (For now it's .key, but that might be a problem.)

```config
#
# 2048 bit OpenVPN static key
#
-----BEGIN OpenVPN Static key V1-----
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
hexhexhexhexhexhexhexhexhexhexhex
-----END OpenVPN Static key V1-----
```

Maybe this is a problem related to other software? For instance, I don't have any Play Services installed (but it worked without them in the past). Disabled the firewall (AFWall+) for testing too.

**Comment by schwabe** [comment]
Can you get a crash log for me (via adb logcat)?  With play services I would see the log in the developer console if you enabled reporting.

**Comment by omitter** [comment]
Here's the crashlog (from adb logcat).
I added a new connection, selected "static key" and and selected the certificate in a file manager.
[crashlog.txt](https://github.com/schwabe/ics-openvpn/files/1827661/crashlog.txt)

**Comment by One111** [comment]
I had same problem recently.
After create profile with static key I had IP parsing error.

0.6.73

After all, I removed profile. Then my tablet (Samsung with android 7) WIFI connection was stop working. 4G was ok.
I removed app, reset network settings, and then certain wifi network still not working, then other is ok.
It looks very strange for me, and I have no idea, where I can find some bad config and fix it.

I use AFwall too, and was tried disable it, it didn't take any effect.

When I set up profile, I probably made some weird settings. But why it can affect system even after complete uninstalled app?

Sorry for bad English please.

**Comment by h1z1** [comment]
Ran into this too, drove me crazy for a few hours because the error does not match what was broken.   Still not sure but I worked around it using a static IP in an imported profile.  

0.7.4 on an S7 running Oreo.

**Comment by pm-pm** [comment]
Same here.  :-(

Moto G5
Android 8.1
App 0.7.8
Using Static Key file like omitter
For server i used IP and DNS Name. Does not matter.

Is there any workaround?

**Comment by schwabe** [comment]
You need a valid IP config like 192.168.1.2/24 for static keys

**Comment by pm-pm** [comment]
Hello. Thanks for reply.

What Netmask should i use when i connect to an Internet VPN-Server? 61.4.5.6/??
Or is "/24" just a dummy value to skip the parsing error?

**Comment by schwabe** [comment]
@pm-pm Openvpn configuration help is out of scope here. Basically the same as in the normal openvpn just in CIDR syntax.

**Comment by pm-pm** [comment]
I understand your Point.
Normally i understand openvpn. (Used it as "tiny" admin for many years)

Some years ago i used **this app** with a openvpn-config-file for configuration and it worked well. :-)
Today i wanted to use the app-menu to configure the vpn-connection. Maybe i am missing a menu?

I will create a file (client-config) and try to Import it.

**Comment by pm-pm** [comment]
For documentation:
With a config file the configuration was successful.

**The problem is**: I missed to add the (lokal) VPN address.
Why did i missed that? The menu point "IPv4-Address" is NOT possible to edit after the first saving of the config. (But: I always saved immediately after assigning a profile name and static key. So I could never edit the IPv4 field in the following configuration steps again. My assumption was: Not possible to edit => not needed) This is a bug.

After playing around with some menus it was possible to edit this point again. Maybe someone could check this.

Thanks.

**Comment by schwabe** [comment]
Yeah that sounds like a bug.
