### ISSUE TITLE
Quistion - Sony Bravia TV Android compatibility ?

### ISSUE THREAD

**Issue by yuriw** [schwabe/ics-openvpn#855]
I am having lots of disconnect issues using  OpenVPN client out of Google Play store by Arne Schwabe (that can be found via search) ref: https://play.google.com/store/apps/details?id=de.blinkt.openvpn

However this client is not compatible with Sony Android TV, at lease this is what Google Play claims.

My question is  - is it compatible ?

**Comment by schwabe** [comment]
Should be compatible with Android TV.Note sure why it should not be. It work on my nvidia shield. Youcan also get the apk from plai.de/android

**Comment by yuriw** [comment]
@schwabe thank you , I am seeing "dropped" connections I see in OpenVPN log "Unroutable control packet received from [AF_INET]xxx.xxx.xxx.xxx(CONTROL_V1)
After that the connection can not be reestablished for awhile (assuming till states are cleaned)
Any clue what this might be ?

**Comment by schwabe** [comment]
Not sure, that is probably more a OpenVPN problem than anything else (hard to tell from a single log message). Check also the server logs
