### ISSUE TITLE
If config has proxy, other http-proxy input is ignored or set to unused options openvpn 3 core

### ISSUE THREAD

**Issue by modfiles** [schwabe/ics-openvpn#857]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 7
2. Android Vendor/Custom ROM: LG v10 stock android 7
3. Device: LG v10
4. Version of the app (version number/play store version/self-built): 0.7.4
 
# Description of the issue
Using Openvpn 3 core, any config that has proxy that is not embedded in <connection></connection> tag will ignore any http-proxy-options CUSTOM-HEADER including proxy authentication.
You can verify this by logs that indicates in Unused Option

**Comment by schwabe** [comment]
Can you post an example config? OpenVPN3 should support the CUSTOM-HEADER option
