### ISSUE TITLE
Open vpn project open to fail

### ISSUE THREAD

**Issue by myrescticat19** [schwabe/ics-openvpn#859]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

generate error : Error:A problem occurred configuring project ':main'.     when oprn project in android studio

**Comment by schwabe** [comment]
Please check the gradle build log

**Comment by AldenLei** [comment]
solved?

**Comment by schwabe** [comment]
@AldenLei Problem of the original submitter is unclear. The gradle build log from Android studio probably mentions an error like missing swig or similar.
