### ISSUE TITLE
Orbot application cannot be found

### ISSUE THREAD

**Issue by itarill** [schwabe/ics-openvpn#860]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. 6.0.1
2. MIUI 8.5.4.0 MALMIED
3. Xiaomi Redmi 3s Prime (Land)
4. 0.7.4, Play Store / Self-built
 
A) When I download the app from Play Store, it will work as intended.
B) When I compile from source, it will launch well, but after importing the same (working) profile as I did in case (A), it will display the message in the following value:

` <string name="no_orbotfound">Orbot application cannot be found. Please install Orbot or use manual Socks v5 integration.</string> `

Used in only one place in the code, 

    public static boolean checkTorReceier(Context c) {
        Intent startOrbot = getOrbotStartIntent(c);
        PackageManager pm = c.getPackageManager();
        Intent result = null;
        List<ResolveInfo> receivers =
                pm.queryBroadcastReceivers(startOrbot, 0);

        return receivers != null && receivers.size() > 0;
    }

So I tried installing Orbot, and it fixed the issue, the self-compiled version works, the app connects. However, I am not sure why I need the Orbot at all. Am I missing a module? Google does not help too much.

P.S.: As I dug just a little bit in the OrbotHelper class, it seems as if I'd need the Orbot application in case of play-store installed ics-openvpn. However, it seems to also work without that. Is it intended?

**Comment by schwabe** [comment]
Does a self compiled version of the app have a different package name? My app is looking for org.torproject.android

**Comment by itarill** [comment]
No, the package name stays the same. Apart from cloning your repo, git submodule init, git submodule update, and adding NDK to $PATH, I did not alter nothing. Not a single letter in the code was changed.

**Comment by schwabe** [comment]
@itarill of orbot, not of my app. My app is looking for org.torproject.android.

Oh sorry, or is the app trying to use orbot when you don't actually try to use orbot?

The version in the play does not have that feature yet. I thought you talked about orbot from store/self compiled

**Comment by xbtc-im** [comment]
Yeap, it's looking for orbot ignoring the configuration ... 
0.7.4 built from source, Pixel 2 XL running CopperheadOS

**Comment by schwabe** [comment]
Okay, I cannot reproduce this that openvpn thinks that orbot should be used. Can you send me the config you are using? Is the orbot radio checked or unchecked in your config?

**Comment by xbtc-im** [comment]
The "no proxy" is checked. Never used a proxy or orbot ... It does this on 2 separate configs, so i guess the config is not relevant.

**Comment by xbtc-im** [comment]
Maybe test like this: install the previous version, import config, then upgrade ics-openvpn ? I will try it myself but i don't have the time right now ... Maybe after upgrading somehow the app assumes that "use tor / orbot" is checked ?

**Comment by xbtc-im** [comment]
Did you manage to reproduce this ?

**Comment by balkan** [comment]
any updates on this? I am experiencing exactly the same issue were you able to fix this issue @xbtc-im

**Comment by schwabe** [comment]
should be already fixed in the source code. If you still experience this issue with current source code please open a new issue.

**Comment by xbtc-im** [comment]
Yes i can confirm it is fixed, pull the last source and re-compile
