### ISSUE TITLE
Master - Broken Unit Test

### ISSUE THREAD

**Issue by aarnoud** [schwabe/ics-openvpn#861]
# General information
1. N/A
2. N/A
3. N/A
4. Master: af2709bcf95654b944cac2f94975a10f8037a53f
 
# Description of the issue

Unit test are failing, last known revision to work was 9d60f71713eb20cc7ad89ee9e392d36c4ac5982b:

> :main:testNoovpn3DebugUnitTest
> 
> de.blinkt.openvpn.core.TestConfigParser > testHttpUserPassAuth FAILED
>     java.lang.AssertionError at TestConfigParser.java:129
> 
> 10 tests completed, 1 failed
> :main:testNoovpn3DebugUnitTest FAILED

**Comment by schwabe** [comment]
Fixed together with http proxy auth
