### ISSUE TITLE
Allow udp4 and tcp4-client options

### ISSUE THREAD

**Issue by ghost** [schwabe/ics-openvpn#862]
When importing an .ovpn file with `udp4` or `tcp4-client` options, those will be set to  `udp` and `tcp-client` respectively.

As a workaround, I have emptied the server name and port in the GUI and put everything into the custom section.

**Comment by schwabe** [comment]
Yes that is by design. Forcing udp4 and tcp4 is not what most people really expect it does and often creates problems, especially in mobile networks that often use NAT64.
