### ISSUE TITLE
Scroll position lost after device rotation

### ISSUE THREAD

**Issue by calbee633810** [schwabe/ics-openvpn#864]
# General information
1. Android Version
Android 23
2. Android Vendor/Custom ROM
3. Device
Nexus 4
4. Version of the app (version number/play store version/self-built)
 Version 0.6.73

# Description of the issue
Click ABOUT, scroll screen and rotate device. It automatically scrolls back to top. However, the scroll posistion should persist after device rotation. It's annoying because users have to manually scroll back after device rotation.

![bug0-before](https://user-images.githubusercontent.com/38213896/38780248-148149cc-4106-11e8-88ea-83a5076f3126.png)
Screenshot before rotation

![bug0-after](https://user-images.githubusercontent.com/38213896/38780251-1adf8658-4106-11e8-9ed2-3444f0a428eb.png)
Screenshot after rotation

**Comment by schwabe** [comment]
Yes, this is technically a bug. But I consider it minor and fixing it is just not worth the trouble (the webview in that view gave me enough headaches already)
