### ISSUE TITLE
Mobile hang after VPN is connected for few minutes at startng

### ISSUE THREAD

**Issue by arun2** [schwabe/ics-openvpn#865]
Hello developer -   I am using latest version. Tried few old versions too. Everything is fine except below -

The problem is after this VPN is connected for about 4-5 minutes nothing opens. I can not open any website or any apps.  Nothing opens.

But after 4-5 minutes waiting, all becomes normal and working very smooth after that.

I want to start work as soon as VPN is connected. But now I need to wait for few minutes.
Can you please advise. may be Android is not picking up new Routes entries. I am not sure.
Nothing abnormal in Log . Just it starts working after few minutes.

Thank you

**Comment by schwabe** [comment]
That sounds like  a problem with your VPN. And posting a log of your VPN connection + server log is minimum I need to have idea any idea what is going on
