### ISSUE TITLE
Oreo adaptive icon shape

### ISSUE THREAD

**Issue by 532910** [schwabe/ics-openvpn#866]
Please add support for icon shape
https://developer.android.com/guide/practices/ui_guidelines/icon_design_adaptive.html
https://material.io/guidelines/style/icons.html

**Comment by schwabe** [comment]
![image](https://user-images.githubusercontent.com/1038539/39100696-1a491cb2-468e-11e8-8b74-f61595e6662c.png)
Not sure if this is really an improvement, I am sceptical that this can be achieved without designing a completely new icon for the app...

**Comment by 532910** [comment]
Looks ugly ):
Is it allowed to use original logo, or google will say it's used for the OpenVN Connect app?
![](https://joscor.com/wp-content/uploads/2013/06/openvpn-logo.png)

**Comment by schwabe** [comment]
The original logo is 

a) Copyrighted by OpenVPN inc
b) I want the app to have its own logo.

**Comment by 532910** [comment]
you should fix it to upload new version to google play
https://www.xda-developers.com/google-play-app-updates-must-target-android-8-0/

**Comment by schwabe** [comment]
@c-e-p-x-u-o The app targets Android 8 for over a year already.

**Comment by ghost** [comment]
Please add support.
I agree with you.
I will.

**Comment by 532910** [comment]
First of all I'm not a designer and this is some raw thoughts how it could look.

![image](https://user-images.githubusercontent.com/14617699/84390878-d9117980-ac00-11ea-8130-1d1d7792dc3c.png)![image](https://user-images.githubusercontent.com/14617699/84390884-dadb3d00-ac00-11ea-92f6-19edcbd170da.png)

![image](https://user-images.githubusercontent.com/14617699/84391698-ff83e480-ac01-11ea-8af5-172b3459ba9c.png)![image](https://user-images.githubusercontent.com/14617699/84391704-014da800-ac02-11ea-9b19-a884b63c5790.png)

![image](https://user-images.githubusercontent.com/14617699/84392001-686b5c80-ac02-11ea-8b61-f8798c9f1a04.png)![image](https://user-images.githubusercontent.com/14617699/84391992-64d7d580-ac02-11ea-926b-947ccae8db76.png)

**Comment by 532910** [comment]
BTW, original svg is dirty and has a lot of superfluous points.

**Comment by schwabe** [comment]
closed by 28bc73163b
