### ISSUE TITLE
No Process running and there are NO VPN connection request pop-up

### ISSUE THREAD

**Issue by KentuckyPH** [schwabe/ics-openvpn#868]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Oreo 8.0.0
2. Stock ROM (Android One)
3. Xiaomi Mi A1
4. OpenVPN for Android 0.7.4
 
# Description of the issue
When I tap my config, There are NO VPN connection request pop-up. How to fix this guys? Thank You! :)

![31357579_566373630428414_7879013862656180224_n](https://user-images.githubusercontent.com/38790307/39388828-9aea4a6e-4ab5-11e8-814e-c051704b6b8e.png)
![31408185_566367540429023_7306314548221313024_n](https://user-images.githubusercontent.com/38790307/39388829-9b3efd5c-4ab5-11e8-87e3-8376ca6be8c1.png)

## **Here some logcat** 

 ![](https://i.imgur.com/ktoGzar.png)![](https://i.imgur.com/b4tNKG9.png)![](https://i.imgur.com/NywcuLs.png)

**Comment by KentuckyPH** [comment]
Help me please. 😪😢

**Comment by schwabe** [comment]
Already fixed in the next version, wait for the next beta or go back to stable

**Comment by KentuckyPH** [comment]
thank you dev. :)

**Comment by KentuckyPH** [comment]
what version is stable sir?
