### ISSUE TITLE
bash: ./misc/build-native.sh: No such file or directory

### ISSUE THREAD

**Issue by KentuckyPH** [schwabe/ics-openvpn#870]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Ubuntu 16.04
2. Linux
3. Acer Aspire
4. OpenVPN 0.7.4
 
# Description of the issue
I follow all the tutorial but this is what happen to me. :'(

![gg](https://user-images.githubusercontent.com/38790307/39394687-86de40a0-4b07-11e8-9207-3ded5be325fa.png)

**Comment by modfiles** [comment]
open project in android studio. the tutorial you follow or tutorial posted in youtube or blogs are already obsolete.
make sure to install swig

**Comment by KentuckyPH** [comment]
@modfiles but when i compiled in android studio,  I got same error in your issues posted too. :)

**Comment by schwabe** [comment]
You are using old build instructions build-native.sh is no longer current
