### ISSUE TITLE
slow to connect (compare to openvpn connect) #361 (reopen)

### ISSUE THREAD

**Issue by alichiddy** [schwabe/ics-openvpn#871]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

**Comment by alichiddy** [comment]
Hi,
Thanks for your great app, because it has more options ofcourse than OpenVPN Connect I liked to reopen the old issue which has been submitted 3 years ago.
Isn't there any way that I can let OpenVPN for Android to connect as quick as OpenVPN Conncet?
With the latest version 0.7.4-157, it's still slower than OpenVPN Connect.
Just teach me how to create a log file so I can use both apps and send the logs from both of them, 3 years and still the same, I love OpenVPN for Android more.
Thanks

**Comment by schwabe** [comment]
Please compare OpenVPN for Android with the OpenVPN 3 C++ core with OpenVPN Connect. If there is no difference in speed the difference is the OpenVPN2/3 difference.
