### ISSUE TITLE
Unable to build openvpn3

### ISSUE THREAD

**Issue by anshul-arora** [schwabe/ics-openvpn#872]
When I run this code in noopenvpn3Debug mode it runs fine but when I run with the normalDebug mode I'm unable to build it.
I'm unable to find net.openvpn in OpenVpnThreadv3.java file

Could you tell me what to do

**Comment by anshul-arora** [comment]
This is what i get when i try to run the code:-

Build command failed.
Error while executing process /home/daffolap-296/Android/Sdk/cmake/3.6.4111459/bin/cmake with arguments {--build /home/daffolap-296/Desktop/openvpn3/ics-openvpn/main/.externalNativeBuild/cmake/normalDebug/x86 --target ovpn3}
[1/4] Generating ovpncli_wrap.cxx
FAILED: cd /home/daffolap-296/Desktop/openvpn3/ics-openvpn/main/.externalNativeBuild/cmake/normalDebug/x86 && /home/daffolap-296/Android/Sdk/cmake/3.6.4111459/bin/cmake -E make_directory ovpn3 && /usr/bin/swig2.0 -outdir ovpn3 -c++ -java -package net.openvpn.ovpn3 -outcurrentdir -I/home/daffolap-296/Desktop/openvpn3/ics-openvpn/main/src/main/cpp/openvpn3/client -I/home/daffolap-296/Desktop/openvpn3/ics-openvpn/main/src/main/cpp/openvpn3 /home/daffolap-296/Desktop/openvpn3/ics-openvpn/main/src/main/cpp/openvpn3/javacli/ovpncli.i
/home/daffolap-296/Desktop/openvpn3/ics-openvpn/main/src/main/cpp/openvpn3/client/ovpncli.hpp:602: Error: Syntax error in input(3).
ninja: build stopped: subcommand failed.

**Comment by anshul-arora** [comment]
this issue was in Ubuntu 14.
I upgraded my system to Ubuntu 16 and now its working.

**Comment by zhengfish** [comment]
@anshul-arora Hello, Anshul, I got the same issue on the Ubuntu-14.04.5. I tried gcc-4.8, gcc-5.5, and gcc-7.3, also got failed. if possible, can you share your gcc version on Ubuntu-16.04? I also wander why it relates to OS version?

**Comment by schwabe** [comment]
The gcc of your os has nothing to do with this. Update your android ndk
