### ISSUE TITLE
ENHANCE: quick settings tile

### ISSUE THREAD

**Issue by kinghat** [schwabe/ics-openvpn#873]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 
8.1 apr 5th update
2. Android Vendor/Custom ROM 
stock
3. Device 
P2XL
4. Version of the app (version number/play store version/self-built)
 3.0.5
# Description of the issue
we need a quick settings tile to toggle profiles/connections on/off.

**Comment by schwabe** [comment]
It is already implemented.

**Comment by kinghat** [comment]
> It is already implemented.

where is it located because im not seeing it in the quick settings tiles that you get to choose from when you select the edit option.

**Comment by schwabe** [comment]
It is right there in the quick tiles.

**Comment by kinghat** [comment]
>It is right there in the quick tiles.

here is a video of the tiles i have with the edit menu open as well:
https://dl.dropboxusercontent.com/s/zphx156lu9snii3/2018_05_10_19_09_53_trim.mp4
you can see a similar tile but that one is for this app: 
https://play.google.com/store/apps/details?id=de.blinkt.openvpn

maybe im just missing it?

**Comment by schwabe** [comment]
The fourth icon that you added "Connect to Home VPN" is the icon/quick tile from my app. And this app is https://play.google.com/store/apps/details?id=de.blinkt.openvpn

**Comment by kinghat** [comment]
wait, so your working on official openvpn now and have your own app?
I have two openvpn apps. one by you and one by official openvpn. I don't have a quick tile for the official openvpn app, is what I'm trying to get across.

**Comment by schwabe** [comment]
This bug tracker is only for my own app. It is my personal spare time project. This issue tracker is really not for the official app from OpenVPN Inc.
