### ISSUE TITLE
Seamless tunnel is not working

### ISSUE THREAD

**Issue by mahdi-ln** [schwabe/ics-openvpn#874]
# General information
1. Android 7.1.1
2. Android Vendor: LG
3. Q6 plus
4. Version of the app (3.0.5/play store version)
 
# Description of the issue
Lots of times vpn connection disconnects (it is weird because these disconnects happen only on the phone and openvpn doesn't try to reconnect)
But seamless tunnel does not block internet.

**Comment by schwabe** [comment]
App version and seamless tunnel sound like OpenVPN Connect. This bug tracker is for a different app (OpenVPN for Android).
