### ISSUE TITLE
"Cannot resolve host address" results in infinite loop

### ISSUE THREAD

**Issue by bowiechen** [schwabe/ics-openvpn#876]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 8.1.0
2. Android Vendor/Custom ROM: stock Android, security patch level 2018-04
3. Device: Google Pixel 2
4. Version of the app: 0.7.5 from Play Store
 
# Description of the issue
When attempting to resolve a host address that results in `NXDOMAIN` or `NOERROR` but no actual IP address is returned (as in, my dynamic DNS has not updated their records), the app is stuck in an infinite host address resolution loop.

# Steps to reproduce
1. Add new `ovpn` definition
1. Add a server address that does not publicly resolve to an IP address (in this case, `server.home`).
1. Tap "connect"

Relevant log: 
```
2018-05-15 13:44:11 RESOLVE: Cannot resolve host address: server.home:1194 (No address associated with hostname)
2018-05-15 13:44:11 RESOLVE: Cannot resolve host address: server.home:1194 (No address associated with hostname)
2018-05-15 13:44:11 RESOLVE: Cannot resolve host address: server.home:1194 (No address associated with hostname)
2018-05-15 13:44:11 RESOLVE: Cannot resolve host address: server.home:1194 (No address associated with hostname)
[...]
```

Note: `server.home` is an internally resolvable hostname. I am demonstrating this edge case by attempting to connect on LTE.

**Comment by schwabe** [comment]
I my test it tries a few times (I think 10 times) and then moves on to the next server entry.

**Comment by bowiechen** [comment]
Interestingly, I can no longer reproduce the behavior on my phone once I reported it. However, it seems that the application does not terminate if there is only one hostname and that hostname is not resolvable, mimicking some sort of infinite loop case.

**Comment by bowiechen** [comment]
Interestingly, I can no longer reproduce the behavior on my phone once I reported it. However, it seems that the application does not terminate if there is only one hostname and that hostname is not resolvable, mimicking some sort of infinite loop case.
