### ISSUE TITLE
Inactivity timeout (--ping restart) restarting

### ISSUE THREAD

**Issue by panagiac** [schwabe/ics-openvpn#877]
# General information
1. Android TV 7.0 
2. Nvidia
3. Shield TV 2017
4. 0.7.5
 
# Description of the issue

I have a premium subscription with IPVanish, and decided to use your application instead the official client, thanks to features like Split Tunneling and per-app rules.

Everything works just fine, as long I use the 2 apps I set up to use VPN.

Problem is: When I use for example Netflix (which is excluded from the VPN), after some time, a lot of toast notifications just start to popup with connectivity status updates.

This is caused by this line in particular:
`Inactivity timeout (--ping restart) restarting`.

I guess this is because VPN connection became inactive. Am I right?

How can I fix this?
Connections seems to restart without any issue, but all this notifications are quite annoying (when they do, they loop even after every 3 minutes!)

Thank you in advance.
Great work by the way!

**Comment by schwabe** [comment]
Please contact their support if you have problems with their VPN. I understand that the notification can be quite annoying but the real problem here is that the VPN is constantly loosing connection (see the ping restart message).
