### ISSUE TITLE
Profile editor doesn't permit "redirect-gateway def1" and "route" simultaneously

### ISSUE THREAD

**Issue by blackwind** [schwabe/ics-openvpn#880]
# General information
1. Android Version: 7.1
2. Android Vendor/Custom ROM: LineageOS 14.1
3. Device: Samsung Galaxy S3
4. Version of the app (version number/play store version/self-built): 0.7.5
 
# Description of the issue
It appears that, on profile import, you're translating "redirect-gateway def1" to "route 0.0.0.0 0.0.0.0 vpn_gateway" and enabling the corresponding option, "Use default Route". When "Use default Route" is enabled, my "route" directive is ignored, resulting in a VPN connection that doesn't pass any data. I was able to work around this by unchecking "Use default Route" and adding either "0.0.0.0/0" to custom routes or "redirect-gateway def1" to custom options, but I suggest correcting the profile editor's logic, as using both these directives at the same time is a perfectly valid configuration.

**Comment by schwabe** [comment]
It is  perfectly fine configuration. But what are you trying to achieve with that?

redirect-gateway def1 does exactly the same as route 0/0 vpn_gateway on Android. The def1 option is internally ignored on Android.

**Comment by blackwind** [comment]
I'm connecting via HTTP proxy, so the net_gateway needs to be manually specified. If I don't include that extra "route" directive for my gateway, again, I get a VPN connection that doesn't pass any data. This seems to be a VpnService quirk, as the official iOS client never required this, but all three Android clients on the Play Store do.

An even better solution, I suppose, would be to detect the gateway and automatically add a net_gateway "route" directive for it, but that's your call. Right now, I have to update the gateway in my config whenever it changes, so if the app could do that for me, that'd be great.

**Comment by schwabe** [comment]
I still don't understand your problem. The Android client should not need net_gateway for routing since it uses a different api to avoid the routing loop. If you can give me a log from a working with def1 and a non working with route 0/0 I can check what the problem is.

**Comment by blackwind** [comment]
To be as clear as I can possibly be:

My config includes these lines:
```
redirect-gateway def1
route 1.2.3.4 255.255.255.255 net_gateway
```

Both lines are required, or the VPN passes no data.

On import, the app translates this to:
```
route 0.0.0.0 0.0.0.0 vpn_gateway
```

When I uncheck "Use default Route", my custom route, which was hidden behind "Excluded Networks", returns:
```
route 1.2.3.4 255.255.255.255 net_gateway
```

I now need to add 0.0.0.0/0 to custom routes to get what I want, which results in:
```
route 0.0.0.0 0.0.0.0 vpn_gateway
route 1.2.3.4 255.255.255.255 net_gateway
```

This produces a working VPN. Alternately, I can add "redirect-gateway def1" to custom options, which also produces a working VPN:
```
redirect-gateway def1
route 1.2.3.4 255.255.255.255 net_gateway
```

One way or the other, my net_gateway MUST be specified to produce a working VPN. The profile editor should accept this perfectly valid configuration by default instead of requiring the workarounds I've outlined. Alternately, a better solution would be to detect the gateway and automatically add a net_gateway "route" directive so HTTP proxy users don't have to mess with this at all.

> The Android client should not need net_gateway for routing since it uses a different api to avoid the routing loop.

I agree, but when an HTTP proxy is used, this apparently isn't the case. All three Android clients exhibit this behavior, so presumably, VpnService is excluding my proxy address and not the gateway, thereby producing a routing loop.

**Comment by blackwind** [comment]
Just ran and compared logs at full verbosity despite not expecting any valuable information, and I was right. Aside from timestamps, SID (`TLS: Initial packet from [AF_INET]127.0.0.1:38118, sid=01234567 89abcdef`), and my extra "route" directive in the connection profile printout, here's the one and only difference:

"Use default Route" checked, net_gateway "route" not present:
```
Routes excluded:
VpnService routes installed: 0.0.0.0/0
```

"Use default Route" unchecked, net_gateway "route" present:
```
Routes excluded: 1.2.3.4/32
VpnService routes installed: 0.0.0.0/1, 1.2.3.0/24, 128.0.0.0/3, 192.0.0.0/2
```

**Comment by schwabe** [comment]
VPNService is not excluding addreses, it is excluding sockets. The key difference in your setup is that you are talking about a *local* proxy on your phone, probably by using another app.

So your problem is actually not redirect-gateway being converted into 0.0.0.0/0 but that the import silently drops/ignores the "route 1.2.3.4 255.255.255.255 net_gateway" route, right?

Btw. for your scenario it is much easier to just exclude the http proxy app from allowed apps.

**Comment by blackwind** [comment]
> So your problem is actually not redirect-gateway being converted into 0.0.0.0/0 but that the import silently drops/ignores the "route 1.2.3.4 255.255.255.255 net_gateway" route, right?

Exactly.

> Btw. for your scenario it is much easier to just exclude the http proxy app from allowed apps.

My proxy is an ELF binary and not an app, so that wouldn't help in this case.

**Comment by vgaetera** [comment]
I have a similar issue.
Need to route all traffic through VPN-gateway except for ISP local subnet which is only available through LAN-gateway.
So it would be perfect to allow custom routes with "redirect-gateway def1" simultaneously.

**Comment by schwabe** [comment]
> My proxy is an ELF binary and not an app, so that wouldn't help in this case.

Exclude app internally in android uses UIDs. As long as your elf binary is started by some app or runs under the uid it should work.

**Comment by blackwind** [comment]
It's started via startup shell script. Again, not applicable in this case.

**Comment by vgaetera** [comment]
@blackwind as a workaround if you have administrative access to the VPN-server, you can push "redirect-gateway def1" and "route" simultaneously and it works.

**Comment by ChristophHeilmann** [comment]
I don't understand. I use Adguard in a proxy configuration and want to exclude a specific ip. What I have to do in this case?

**Comment by schwabe** [comment]
This issue seems multiple problems but none of them seem to be a real bug. Closing this now. For real bugs please open new issues.
