### ISSUE TITLE
faty...

### ISSUE THREAD

**Issue by gilcot** [schwabe/ics-openvpn#881]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version  = 5.0.2
2. Android Vendor = LG
3. Device
4. Version of the app = 0.7.5
 
# Description of the issue

Not really a bug, but a strange thing I can't understand. 
Previous versions (0.6.71 and 0.6.73 here) were 8.1M size, what was very big imho. 
Now, the application (in version 0.7.5) is 14.5M (almost twice bigger) without reason.
What happend???

**Comment by tomty89** [comment]
OpenVPN 3 Core was added (which you can opt to use in SETTINGS).

**Comment by schwabe** [comment]
what @tomty89 says
