### ISSUE TITLE
About remoteExample 

### ISSUE THREAD

**Issue by AlinaBabenko** [schwabe/ics-openvpn#883]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version - L, M. N
2. Android Vendor/Custom ROM
3. Device - Nexus 7, Samsung S4, Samsung J7
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

Hello! I have cloned and opened your library in Android Studio 3.1 and Gradl 4.4 to understand how remoteExample works. I can't synchronize the project. I got the following error
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':main'.
Can you help me? Thank you in advance.

**Comment by schwabe** [comment]
To be build the main project you need to have the requirements in the doc/README.md. Comment out :main in settings.gradle to only build the remoteExample

**Comment by AlinaBabenko** [comment]
Thank you for answer. I've run remoteExample. But when I try to press any buttons - I have nothing or crash. What should I do for using remote example with it's functionality? Maybe, I should use module :main?

**Comment by schwabe** [comment]
@AlinaBabenko I don't know what you trying to do. The remote example needs the main app to be installed.
