### ISSUE TITLE
OPENVPN 3 Crash

### ISSUE THREAD

**Issue by TheBestTheBestTheBest** [schwabe/ics-openvpn#884]
1. Android Version: 8.0
2. ROM: Huawei EMUI 8.0.0 MHA-L29 8.0.0.368 (C432)
3. Device: Huawei Mate 9
4. Version of the app 0.7.5 from Play Store

Openvpn crashes when changing from wifi to 4g and vice versa. Here is the log
Btw, changed the username to " WHY THE HELL DOES THIS KEEP THE USERNAME IN THE LOG" for privacy purposes.

[Log.txt](https://github.com/schwabe/ics-openvpn/files/2063834/Log.txt)

**Comment by sso-klump** [comment]
Have the exact same issue on my huawei mate 10 pro running android 8.0.1 
Also seen this on some samsung phones aswell

**Comment by schwabe** [comment]
2018-06-01 20:41:31 Errore:Cannot bind de.blinkt.openvpn.core.OpenVPNService

This look like an error from Android. I wonder if there are more details in logcat?

**Comment by TheBestTheBestTheBest** [comment]
If it's useful, i noticed the error happens only when the network change happens while the phone is not being used. Instead, when the phone is turned on, it didn't happen.

**Comment by schwabe** [comment]
Yeah but that sounds more like a bug in Android from huawei than anything else since it returns a very weird error on trying to opening the tun device.

**Comment by TheBestTheBestTheBest** [comment]
@sso-klump 
Can you add logs from huawei and samsung phones too? I think i am the only one who posted them and thus limiting the chance of a solution being found.

@schwabe 
Could it be some kind of problem linked to android oreo and management of processes while not being used? maybe some dumb background limitation interferes with the program working correctly. Any way to force some kind of "keep it working as if it's in the foreground"?
I'm not a programmer, just read that android oreo added some "fixes" to background usage of battery that messed up a lot of apps.

**Comment by schwabe** [comment]
@TheBestTheBestTheBest All Android 8 devices which I have are pixel devices and don't have these problems.
