### ISSUE TITLE
Add suboption to skip UDP remotes when "Use system proxy" enabled

### ISSUE THREAD

**Issue by blackwind** [schwabe/ics-openvpn#885]
The connection on which I use my HTTP proxy requires all traffic go through the proxy, so UDP traffic just gets dropped. I have my UDP remotes at the top of my config, because obviously, I want UDP to be used on any other connection. Currently, when "Use system proxy" is enabled, I have to wait for my UDP remotes to timeout before the app connects to my TCP remotes.

I understand that I could reduce my timeout (which doesn't fully solve the problem and could be problematic on slower connections) or use separate config files (which is very inconvenient), but I propose a better solution: Add a suboption to skip UDP remotes when "Use system proxy" is enabled. This probably shouldn't be the default logic since there are probably scenarios where TCP traffic must be proxied but UDP is still allowed, but for most HTTP proxy users, this would surely be a very welcome feature.

**Comment by schwabe** [comment]
This feature seems to corner case to implement for me.
