### ISSUE TITLE
this project could complie at window?

### ISSUE THREAD

**Issue by czgczg308** [schwabe/ics-openvpn#887]
I download  project in ubuntu, i want to ask for help, can i build project in window system ?
I have see somebody  to compile use ./misc/build-native.sh
but  now  i  just see build-native.bat.
As i know bat is execute in window system.
Which page i can refer to compile the project and get so file?
I'm a chinese ,my english is not well, hope you can help me

**Comment by schwabe** [comment]
Whatever information you have seen is out of date. There is a doc/README.mde that explains how to build the project. and yes  the project builds just fine under windows

**Comment by czgczg308** [comment]
thank for you help,  I want to confirm with you, the file ' doc/README.mde'  you tell me is  the same to my picture in the red frame?

![1](https://user-images.githubusercontent.com/4937739/41190396-2215af44-6c10-11e8-89ce-5aac882d0021.png)

**Comment by czgczg308** [comment]
another question  i need  you help ,the doc  you have write "The native build should with Windows and Linux "  , when  i build project ,i should build with both windows and  linux?
 or  i can just build with windows only? 
"and"  or  "or"?

**Comment by schwabe** [comment]
It builds on Windows.
