### ISSUE TITLE
Proxy option layout bug

### ISSUE THREAD

**Issue by 7twin** [schwabe/ics-openvpn#888]
The fourth proxy option is outside the view:

![Screenshot](https://i.imgur.com/GO14TSi.jpg)  

Device:
- Xiaomi Redmi Note 4
- Android 7

**Comment by blackwind** [comment]
Same problem here.

**Comment by blackwind** [comment]
Still a problem on both my Galaxy S3 (720p) and Galaxy S5 (1080p).
