### ISSUE TITLE
My develop environment should the same to you?

### ISSUE THREAD

**Issue by czgczg308** [schwabe/ics-openvpn#890]
my develop environment is 
android studio:2.2.2 
```
dependencies {
        classpath 'com.android.tools.build:gradle:2.2.2'
}
gradle version confit:distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip
-------------------------------------------------------------
I download the project  ,you environment is
 repositories {
        maven {
            url 'https://maven.google.com'
        }
        jcenter()
        google()
    }
dependencies {
        classpath 'com.android.tools.build:gradle:3.1.2'
}
gradle version confit:distributionUrl=https\://services.gradle.org/distributions/gradle-4.5-all.zip
```
------------------------------------------------------------------------------------------------------
I import download project to my environment ,and change  gradle plugin version and gradle version to myself,but build with problem can't find google()? How to deal it? Should i update my android studio and gradle version to same with you? Is your project build required relatvie gradle version?

**Comment by schwabe** [comment]
I have no idea what the question really. If this about asking for help to integrate into another project please the FAQ about commercial projects

**Comment by czgczg308** [comment]
This is about the integration of the project. After querying the data for an afternoon, I would like to withdraw this problem. I think I can handle this problem by myself.Although I cannot run after the project is imported, I can solve it by myself. Thank you for your help.This is a low level question. I'm sorry to bother you
