### ISSUE TITLE
Save password select box causes AUTH_FAILED

### ISSUE THREAD

**Issue by EmcaBorg** [schwabe/ics-openvpn#892]
OS Android 7.0

After remote app is connected  to VPN service and username and password dialog is shown and when I enter username and password and select save password and try to connect I get AUTH_FAILED,
but when I enter the same credentials but not select save password I successfully manage to connect to VPN server.

Also to mention, after first AUTH_FAILED when I reboot device try to connect again from remote app, credentials dialog doesn't show and VPN connection is successfully established with a saved credentials.

**Comment by anshul-arora** [comment]
@EmcaBorg could you tell me did you change anything in remote app, because I am unable to connect to VPN service after entering username and password in the dialog. Remote app is stuck at VPN_GENERATE_CONFIG state.

My ovpn file works in main application but not in remote app

**Comment by EmcaBorg** [comment]
@anshul-arora no I'm using custom remote application but I'm following all the steps that is implemented in remote example. I can connect without any issues without selecting save password select box, but if I select it I receive AUTH_FAILED and when I reboot device VPN is successfully connected without credentials dialog shown which mean that credentials are applied and saved at first time, but maybe ICS OpenVPN must be rebooted for action to take place

**Comment by schwabe** [comment]
Are you connecting with an inline profile (whole config send to my app as String to connect) or are you using one of the VPN profiles that exists in the app (like the user can also click).

**Comment by anshul-arora** [comment]
@schwabe I am using inline profile for connecting to the VPN server.

@EmcaBorg could you tell me few steps on how to connect to VPN profile with user credentials being entered on the dialog, I am unable to achieve this.

**Comment by EmcaBorg** [comment]
@schwabe I'm using inline profile (Stringified .ovpn config file) at the first time connection to VPN server over ICS OpenVPN client and after the connection is successfully established (CONNECTED status) I'm calling addNewVPNProfile() and if the UUID of profile is returned next time when I try to connect I'm passing UUID to ICS OpenVPN client and everything work like a charm. But if I click on save password on credentials dialog no matter whether or not I'm connecting with startProfile() or startVPN() I get AUTH_FAILED. But if I reboot a android device and after that call startVPN() passing existing UUID as a argument I can successfully connect.

@anshul-arora try add auth-user-pass options in your ovpn profile

**Comment by schwabe** [comment]
That sounds very strange indeed. It looks like startProfile does kind of a shortcut and will always try to start the profile bypassing the checks the ui normally does (e.g. asking for a password). 

When you say you say "saving a password" is that by editing basic setting or is that by starting the VPN by GUI or remote and then dialog pops up asking you for a password?

A possible workaround (depending on your specific needs) is to use
```
<auth-user-pass>
username
password
</auth-user-pass>
```
in the inline config.

**Comment by EmcaBorg** [comment]
@schwabe By saving a password I meant checking checkmark save password on dialog that is shown. Thanks for the workaround, but it does not satisfy my needs because I use SOPHOS VPN server which automatically generate .ovpn profiles for users and it can't be configured to automatically insert username password in generated profile.

**Comment by schwabe** [comment]
I am trying to understand the issue, paraphrasing your last reponse:

You add programmatically profiles to my app but the string you send is fixed since Sophos VPN generates the profiles?

Why can you not modify the profile when you add it programmatically?
