### ISSUE TITLE
connect l2pt vpn in my app

### ISSUE THREAD

**Issue by Android500** [schwabe/ics-openvpn#893]
We plan to develop an app that can use l2tp vpn account password, server address and port to establish VPN connection.I don't know if this project can be realized. Could you  give me some advice?

**Comment by schwabe** [comment]
Certainly but not on the base of this project which is a) GPL and b) OPenVPN only

**Comment by Android500** [comment]
can u give some advice to config and establish l2tp vpn connection in my own app?

**Comment by schwabe** [comment]
Sorry, I have not look into l2tp, so no idea.

**Comment by zhangjinhuang** [comment]
> can u give some advice to config and establish l2tp vpn connection in my own app?

hello,have you solve it?

**Comment by mrkhaleghi** [comment]
> 

how about you?
