### ISSUE TITLE
do you have same detail resource about how to compile

### ISSUE THREAD

**Issue by czgczg308** [schwabe/ics-openvpn#895]
"Build instructions:

- Install sdk, ndk, cmake (e.g. with Android studio), swig (3.0+)

Fetch the git submodules (the default urls for the submodules use ssh,
set up your own GitHub ssh key or change the url to http in .gitmodules):

  git submodule init
  git submodule update

Build the project using "gradle build" (Or use Android Studio). 

Android studio tends to the whole build of binaries in its sync gradle
phase to 15 minutes for initial gradle sync are completely normal.

The native build should with Windows and Linux but is rarely tested
since my main development platform is Mac Os X"

The following is the reference material you replied to me about how to compile on Windows.But the comparison is very general, very inexact.Are there any data can explain each step in detail how to operate, such as the connection demo steps in https://www.youtube.com/watch?v=gBMhaCujwrM&t=639s.When, for example, do you use build-native. bat?

Why can't I find any information to compile the ics-openvpn on Windows?Can you share some with me?
I found so many is under ubuntu linux such as url under;
https://www.youtube.com/watch?v=gBMhaCujwrM&t=639s

**Comment by schwabe** [comment]
That youtube video is really outdated. And you quoted all information you need to compile it under Windows. But as the README says I develop on OS X so the Windows build might not work. Patches to fix the Windows build are welcome.

**Comment by czgczg308** [comment]
I know that he is out of date, I just want to say that is there any  data document of such detailed steps, and your data does not even indicate when build-native.bat will be implemented

**Comment by czgczg308** [comment]
When i execute build-native.bat it show "Cannot find .git directory in openvpn, aborting". 

Before executing build-native.bat, I only did the following two steps, but there was a problem.Is there any step missing here?

Administrator@MWXOAANZXXNV4EL MINGW64 /d/source/openvpn
$ ls
ics-openvpn/

Administrator@MWXOAANZXXNV4EL MINGW64 /d/source/openvpn
$ cd ics-openvpn

Administrator@MWXOAANZXXNV4EL MINGW64 /d/source/openvpn/ics-openvpn (master)
$ git submodule init
Submodule 'main/src/main/cpp/asio' (https://github.com/chriskohlhoff/asio) registered for path 'main/src/main/cpp/asio'
Submodule 'main/src/main/cpp/lz4' (https://github.com/lz4/lz4.git) registered for path 'main/src/main/cpp/lz4'
Submodule 'main/src/main/cpp/mbedtls' (https://github.com/ARMmbed/mbedtls.git) registered for path 'main/src/main/cpp/mbedtls'
Submodule 'main/openssl' (https://github.com/schwabe/platform_external_openssl.git) registered for path 'main/src/main/cpp/openssl'
Submodule 'main/openvpn' (https://github.com/schwabe/openvpn.git) registered for path 'main/src/main/cpp/openvpn'
Submodule 'main/src/main/cpp/openvpn3' (https://github.com/schwabe/openvpn3.git) registered for path 'main/src/main/cpp/openvpn3'

Administrator@MWXOAANZXXNV4EL MINGW64 /d/source/openvpn/ics-openvpn (master)
$ git submodule update
Cloning into 'D:/source/openvpn/ics-openvpn/main/src/main/cpp/asio'...
Cloning into 'D:/source/openvpn/ics-openvpn/main/src/main/cpp/lz4'...
Cloning into 'D:/source/openvpn/ics-openvpn/main/src/main/cpp/mbedtls'...
Cloning into 'D:/source/openvpn/ics-openvpn/main/src/main/cpp/openssl'...
Cloning into 'D:/source/openvpn/ics-openvpn/main/src/main/cpp/openvpn'...
Cloning into 'D:/source/openvpn/ics-openvpn/main/src/main/cpp/openvpn3'...
Submodule path 'main/src/main/cpp/asio': checked out '9229964dc1853b375077338cb398027a6dbbb148'
Submodule path 'main/src/main/cpp/lz4': checked out 'dfed9fa1d77f0434306d377c4da1f7191d3ba08a'
Submodule path 'main/src/main/cpp/mbedtls': checked out '8be0e6db41b4a085e90cb03983f99d3a5158d450'
Submodule path 'main/src/main/cpp/openssl': checked out '216564ce74be047a96d021774e4bd128ef5f8681'
Submodule path 'main/src/main/cpp/openvpn': checked out '14adf04a2c370743d2e7f583dda954d9dd1c7f8a'
Submodule path 'main/src/main/cpp/openvpn3': checked out '983b0f28bda66e8a6dad9d73b05857555a6f07be'

**Comment by schwabe** [comment]
As I said, that video is outdated. And build-native.bat is not used anymore. So if you try to follow instruction that are wrong, clearly it does not work.

**Comment by czgczg308** [comment]
------------------------------------------------
(the default urls for the submodules use ssh,
set up your own GitHub ssh key or change the url to http in .gitmodules)
------------------------------------------------
The content above is your content.  I have do nothing about it, is that correct?

**Comment by czgczg308** [comment]
Now I understand. My previous understanding was that build-native.sh is out of date, and build-native.bat is not out of date.Now I know that both of these are out of date build-native. sh build-native. bat

**Comment by czgczg308** [comment]
(the default urls for the submodules use ssh,
set up your own GitHub ssh key or change the url to http in .gitmodules)
---------------------------------------------------------------------------------
What does that mean? I do anything in parentheses.Is that ok?

**Comment by czgczg308** [comment]
Just execute the following statement，it tell me can't find google(),how to deal it?
![image](https://user-images.githubusercontent.com/4937739/41348769-4f4e231e-6f40-11e8-8b6c-b73849962680.png)

**Comment by schwabe** [comment]
try usng the gradlew wrapper from the project and not some random gradle version.

**Comment by czgczg308** [comment]
I use the gradlew wrapper form the project to build, but it show that.How can i deal it.

![image](https://user-images.githubusercontent.com/4937739/41390204-302c97b8-6fc7-11e8-9891-e8b937ccd3cc.png)

**Comment by schwabe** [comment]
Seem to be problems with your sdk installation or Internet connection. Both are out of scope here.

**Comment by czgczg308** [comment]
The problem before i have solve . But new trouble is coming. I'm here to bother you again.
--------------------------------------------------------------------------------------------------
* What went wrong:
Execution failed for task ':main:generateJsonModelNoovpn3Debug'.
> Build command failed.
  Error while executing process D:\ProgramAndroid\AndroidSDK\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\source\openvpn\ics-openvpn\main\s
rc\main\cpp -BD:\source\openvpn\ics-openvpn\main\.externalNativeBuild\cmake\noovpn3Debug\armeabi -DANDROID_ABI=armeabi -DANDROID_PLATFORM=android-1
4 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\source\openvpn\ics-openvpn\main\build\intermediates\cmake\noovpn3\debug\obj\armeabi -DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=D:\ProgramAndroid\NDK\android-ndk-r14b -DCMAKE_TOOLCHAIN_FILE=D:\ProgramAndroid\NDK\android-ndk-r14b\build\cmake\android.toolchain.cm
ake -DCMAKE_MAKE_PROGRAM=D:\ProgramAndroid\AndroidSDK\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_
STL=c++_static}
  -- Check for working C compiler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
  -- Check for working C compiler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
  -- Check for working CXX compiler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  OpenVPN 2.x version icsopenvpn_705-0-g14adf04a
  OpenVPN 3.x version icsopenvpn_705-0-g983b0f28
  -- The ASM compiler identification is Clang
  -- Found assembler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
  CMake Error at openssl.cmake:645 (message):
    Unknown arch armeabi for source files
  Call Stack (most recent call first):
    CMakeLists.txt:20 (include)


  -- Configuring incomplete, errors occurred!
  See also "D:/source/openvpn/ics-openvpn/main/.externalNativeBuild/cmake/noovpn3Debug/armeabi/CMakeFiles/CMakeOutput.log".


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights
---------------------------------------------------------------------------------------------------------------
This  is the log file  CMakeOutput.log.
[CMakeOutput.log](https://github.com/schwabe/ics-openvpn/files/2101914/CMakeOutput.log)

**Comment by czgczg308** [comment]
The problem before i hava solve , but new trouble is coming.So I have to bother you
------------------------------------------------------------------------------
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':main:generateJsonModelNoovpn3Debug'.
> Build command failed.
  Error while executing process D:\ProgramAndroid\AndroidSDK\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\source\openvpn\ics-openvpn\main\s
rc\main\cpp -BD:\source\openvpn\ics-openvpn\main\.externalNativeBuild\cmake\noovpn3Debug\armeabi -DANDROID_ABI=armeabi -DANDROID_PLATFORM=android-1
4 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\source\openvpn\ics-openvpn\main\build\intermediates\cmake\noovpn3\debug\obj\armeabi -DCMAKE_BUILD_TYPE=Debug
-DANDROID_NDK=D:\ProgramAndroid\NDK\android-ndk-r14b -DCMAKE_TOOLCHAIN_FILE=D:\ProgramAndroid\NDK\android-ndk-r14b\build\cmake\android.toolchain.cm
ake -DCMAKE_MAKE_PROGRAM=D:\ProgramAndroid\AndroidSDK\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_
STL=c++_static}
  -- Check for working C compiler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
  -- Check for working C compiler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
  -- Check for working CXX compiler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  OpenVPN 2.x version icsopenvpn_705-0-g14adf04a
  OpenVPN 3.x version icsopenvpn_705-0-g983b0f28
  -- The ASM compiler identification is Clang
  -- Found assembler: D:/ProgramAndroid/NDK/android-ndk-r14b/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
  CMake Error at openssl.cmake:645 (message):
    Unknown arch armeabi for source files
  Call Stack (most recent call first):
    CMakeLists.txt:20 (include)


  -- Configuring incomplete, errors occurred!
  See also "D:/source/openvpn/ics-openvpn/main/.externalNativeBuild/cmake/noovpn3Debug/armeabi/CMakeFiles
----------------------------------------------------------------------
The logFile CMakeOutput.log is here
[CMakeOutput.log](https://github.com/schwabe/ics-openvpn/files/2101949/CMakeOutput.log)
/CMakeOutput.log".

**Comment by schwabe** [comment]
Try not building with totally outdated SDK/NDK

**Comment by czgczg308** [comment]
Thankyou for you help. I have build my apk, but there art two type of apk . "main-noovpn3-debug.apk" and   
"main-normal-debug.apk" , what about the different of they?

**Comment by czgczg308** [comment]
I use my build apk ,it can't connect my server,but i use OpenVPNConnect.apk the same config，it work well. this is the log image; Can you tell me where I should start to look up the problem?
![de blinkt openvpn](https://user-images.githubusercontent.com/4937739/41497161-85cd0f10-7182-11e8-95bc-9e2c61094986.png)

**Comment by schwabe** [comment]
look I am not your personal help hotline and provide you with help for every tiny obstacle you ran into. You should probably read the log more care and  figure out what is happening. And also check if it works with my official version of the app.

**Comment by czgczg308** [comment]
Thank you for your help.I'm sorry to bother you for so long.What I want to say is that after consulting you on some questions, I will continue to query the data and check the questions myself. Sometimes I can solve the problems before you reply to me, and sometimes I will get stuck for a long time.I will spend more time, thank you very much!

**Comment by czgczg308** [comment]
I use build apk can connect the server, but base on modify you code.
The image button2 can't select any .ovpn file ,i modify the file "de.blinkt.openvpn.fragments.Utils" .
I modify 
```
i.putExtra(Intent.EXTRA_MIME_TYPES, supportedMimeTypes.toArray(new String[supportedMimeTypes.size()]));
```
to
```
if(fileType!=OVPN_CONFIG){
            i.putExtra(Intent.EXTRA_MIME_TYPES, supportedMimeTypes.toArray(new String[supportedMimeTypes.size()]));
        }
```
now i can select the .ovpn file.

Original i add config by button1,it can't work.now i modify file ,by button2 way it can work.

![5](https://user-images.githubusercontent.com/4937739/41594531-46d6fd90-73f6-11e8-854b-48890927558e.png)

Hope this will make a contribution for your team

**Comment by schwabe** [comment]
OpenVPNConnect.apk is a completely different app. Selecting OpenVPN 3 C++ core under general settings might get you closer to it.

**Comment by czgczg308** [comment]
thank  you for  your help.

**Comment by aries255** [comment]
Hello @czgczg308. Have you tried to compile it on windows? Can you help me how. Im having an error compiling the app. 

OpenVPN 2.x version HEAD-HASH-NOTFOUND
Error while executing process C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\STan\Desktop\pil\main\src\main\cpp -BC:\Users\STan\Desktop\pil\main\.externalNativeBuild\cmake\normalDebug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\STan\Desktop\pil\main\build\intermediates\cmake\normal\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}
-- Found assembler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
See also "C:/Users/STan/Desktop/pil/main/.externalNativeBuild/cmake/noovpn3Debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
-- Detecting C compiler ABI info - done
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features - done
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
OpenVPN 2.x version HEAD-HASH-NOTFOUND
-- Detecting C compile features
-- Detecting CXX compiler ABI info - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
OpenVPN 2.x version HEAD-HASH-NOTFOUND
Error while executing process C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\STan\Desktop\pil\main\src\main\cpp -BC:\Users\STan\Desktop\pil\main\.externalNativeBuild\cmake\noovpn3Debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\STan\Desktop\pil\main\build\intermediates\cmake\noovpn3\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Detecting C compiler ABI info
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Detecting CXX compile features - done
-- Detecting C compile features
Build command failed.
-- Detecting CXX compile features
CMake Error at C:/Users/STan/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
Build command failed.
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compile features
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info
-- Found assembler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- The ASM compiler identification is Clang
Error while executing process C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\STan\Desktop\pil\main\src\main\cpp -BC:\Users\STan\Desktop\pil\main\.externalNativeBuild\cmake\noovpn3Release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\STan\Desktop\pil\main\build\intermediates\cmake\noovpn3\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}
-- Found assembler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
Build command failed.
Build command failed.
See also "C:/Users/STan/Desktop/pil/main/.externalNativeBuild/cmake/normalRelease/armeabi-v7a/CMakeFiles/CMakeOutput.log".
-- Detecting C compile features
-- Detecting CXX compile features
-- Configuring incomplete, errors occurred!
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting CXX compiler ABI info - done
-- The ASM compiler identification is Clang
-- Detecting CXX compiler ABI info
-- Detecting CXX compile features - done
OpenVPN 3.x version HEAD-HASH-NOTFOUND
-- Detecting CXX compiler ABI info
-- Found assembler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Detecting CXX compiler ABI info
See also "C:/Users/STan/Desktop/pil/main/.externalNativeBuild/cmake/noovpn3Release/armeabi-v7a/CMakeFiles/CMakeOutput.log".
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
OpenVPN 2.x version HEAD-HASH-NOTFOUND
-- Detecting CXX compiler ABI info - done
Error while executing process C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\STan\Desktop\pil\main\src\main\cpp -BC:\Users\STan\Desktop\pil\main\.externalNativeBuild\cmake\normalRelease\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\STan\Desktop\pil\main\build\intermediates\cmake\normal\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting C compiler ABI info - done
-- Configuring incomplete, errors occurred!
-- The ASM compiler identification is Clang
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- The ASM compiler identification is Clang
-- Detecting C compile features - done
-- Detecting C compile features - done
-- Configuring incomplete, errors occurred!
-- Configuring incomplete, errors occurred!
-- Detecting CXX compile features - done
OpenVPN 3.x version HEAD-HASH-NOTFOUND
CMake Error at C:/Users/STan/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
CMake Error at C:/Users/STan/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
-- Detecting C compile features
OpenVPN 3.x version HEAD-HASH-NOTFOUND
CMake Error at C:/Users/STan/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting CXX compile features
OpenVPN 3.x version HEAD-HASH-NOTFOUND
-- Detecting C compile features - done
See also "C:/Users/STan/Desktop/pil/main/.externalNativeBuild/cmake/normalDebug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
