### ISSUE TITLE
OpenVPN V3 log all on one line

### ISSUE THREAD

**Issue by mother3end** [schwabe/ics-openvpn#896]
4.2.2
Sony Xperia ZR variant
OpenVPN for Android v0.7.5 from PlayStore

When you tick the box to use OpenVPN v3 in settings and connect to any server (in my case I use the free ProtonVPN servers) the log tab opens, but it just loads on the first line, with each message replacing the one before it. App behaves as expected when box is unticked (running v2). 

Also, when using v3, it shows _username_@server ip connected by UDP IPv4 etc under server name on the profiles page, vs just CONNECTED, is that normal?

**Comment by schwabe** [comment]
Yes, openvpn3 is a bit different than openvpn2. To show more than one line you need to increase log visibility a bit.

**Comment by schwabe** [comment]
Yes, openvpn3 is a bit different than openvpn2. To show more than one line you need to increase log visibility a bit.

**Comment by schwabe** [comment]
Yes, openvpn3 is a bit different than openvpn2. To show more than one line you need to increase log visibility a bit.
