### ISSUE TITLE
openvpn does not work in banking applications

### ISSUE THREAD

**Issue by rdbox** [schwabe/ics-openvpn#897]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 4.22
2. Android Vendor/Custom ROM 
3. Device **samsung duos 2 sim**
4. Version of the app (version number/play store version/self-built)
 **the latest version today downloaded**

# Description of the issue
I can not access my bank's application.
In the instagram can go and open the application bank can not
gives an error there is no network

what to do?

**Comment by schwabe** [comment]
Contact you runs your VPN. Try to get more information. With the information here I cannot do anything.

**Comment by rdbox** [comment]
here I run this config file on the android device
All sites work with google instagram but the bank applications do not work.

Only ```ExpressVPN``` program helps to enter my bank applications

```
client
remote SERVER 443
proto tcp
dev tun
cipher AES-256-CBC
auth SHA512
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name true-neutral-come name
tls-version-min 1.2
compress lz4
verb 3
route SERVER  255.255.255.255 net_gateway
 
auth-nocache
connect-retry 1
route-delay 5
route-method exe
```

**Comment by rdbox** [comment]
but here is the config server
```
server 10.8.0.0 255.255.255.0
push "dhcp-option DNS 10.8.0.1"
 

proto tcp
port 443
dev tun
ca ca.crt
cert server.crt
key server.key  # This file should be kept secret
dh none
ifconfig-pool-persist ipp.txt

 
push "redirect-gateway def1 bypass-dhcp"

# Fix for the Windows 10 DNS leak described here:
# https://community.openvpn.net/openvpn/ticket/605
push block-outside-dns

client-to-client
remote-cert-tls client

# Allow multiple clients with the same common name to concurrently connect.
# In the absence of this option, OpenVPN will disconnect a client instance
# upon connection of a new client having the same common name.
# duplicate-cn

keepalive 10 120
tls-crypt ta.key # This file is secret
cipher AES-256-CBC
ncp-ciphers AES-256-GCM:AES-128-GCM

# limit the tls ciphers
tls-cipher TLS-ECDHE-RSA-WITH-AES-256-GCM-SHA384

auth SHA512
tls-version-min 1.2
compress lz4
user nobody
group nogroup
persist-key
persist-tun
 
verb 5
status /var/log/openvpn/openvpn-status.log 
log /var/log/openvpn/openvpn.log

 
sndbuf 0
rcvbuf 0
 
```

**Comment by schwabe** [comment]
In my experience these issues are usually MTU or dns related. Check test sites like test-ipv6.com or other sites to see if you have an MTU problem.

Btw. hard coding tls-cipher if you don't know what you are doing is most times a bad idea.

**Comment by rdbox** [comment]
all tests passed successfully. Except for ipv6

dns I use on my server dnsmasq
and at the output of OpenDNS

I think I need an additional setting
because all sites are working, but only bank applications do not want to work

**Comment by rdbox** [comment]
I think I need an additional setting

**Comment by rdbox** [comment]
I found a problem, it turns out my ip server was in the black list of the country.
I changed ip and the application worked as it should

I close the ticket if anyone wants to write
