### ISSUE TITLE
Unable to import ovpn with 3.05 android client

### ISSUE THREAD

**Issue by erlebc** [schwabe/ics-openvpn#898]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version  7.0
2. Android Vendor/Custom ROM  LG
3. Device  LG V20
4. Version of the app (version number/play store version/self-built)  Downloaded from Play Store today (06/20/18)  I believe it's 3.05
 
# Description of the issue
I configured my VPN router for OpenVPN support, and got an ovpn configuration file created.  I sent the file to my device and it resides within the Internal Storage Downloads folder.   
I launch the Open VPN Client and select OVPN Profile button.  I navigate to the downloads folder and the file is visible, and I select it, then there is a check mark next to it.  

Then, nothing.  There is no button to continue, or import, etc.  A long press does nothing, I am not able to scroll the page or anything so I believe I'm seeing everything.  Nothing happens at this point.  What should happen.  The only actions I can take are to press the  <- Back button, or the other <- button for Import Profile which just takes me back to the beginning.   I feel like an idiot here like I should know what to do next, but......

I uninstalled the app, then reinstalled it, but no joy.  Can I manually configure the thing?
Suggestions.

**Comment by schwabe** [comment]
3.05 is not a version of my app. That sounds like OpenVPN Connect. Also the rest of your description sounds like OpenVPN connect
