### ISSUE TITLE
How to bypass packets on Android without root ?

### ISSUE THREAD

**Issue by YumingMa** [schwabe/ics-openvpn#899]
How to bypass packets on Android without root ?
1. Get IP packet from TUN. Same as all VPN service does.
2. I do nothing.  I want to send IP packets back to the protocol stack.

How to implement step 2 ? Thanks in advance!

**Comment by schwabe** [comment]
Not, the focus of this app. For step 2 you need to implement your own TCP stack. Orbot, Shadowsocks and some other Socks tunnel apps have done this.
