### ISSUE TITLE
Unable to connect to server unless OpenVPN Connect has recently connected.

### ISSUE THREAD

**Issue by r2DoesInc** [schwabe/ics-openvpn#9]
client.conf

dev tun
proto udp
remote 10.100.4.134 1199
resolv-retry infinite
nobind
comp-lzo
persist-key
persist-tun
client
verb 3
##keys added inline here

server.conf

dev tun
proto udp
port 1199
server 10.8.0.0 255.255.255.0
ifconfig-pool-persist ipp.txt
keepalive 10 120
comp-lzo
persist-key
persist-tun
verb 3
ca ca.crt
cert server.crt
key server.key
dh dh2048.pem

"Route rejected by Android10.8.0.6/30 Bad address"

OpenVPN Connect will make the connection without issue.
The only way successfully make the connection in OpenVPN for Android is to do it just after disconnecting in OpenVPN Connect.

**Comment by schwabe** [comment]
Am 23.01.15 um 16:44 schrieb Ken:
>
> client.conf
>
> dev tun
> proto udp
> remote 10.100.4.134 1199
> resolv-retry infinite
> nobind
> comp-lzo
> persist-key
> persist-tun
> client
> verb 3
> ##keys added inline here
>
> server.conf
>
> dev tun
> proto udp
> port 1199
> server 10.8.0.0 255.255.255.0
> ifconfig-pool-persist ipp.txt
> keepalive 10 120
> comp-lzo
> persist-key
> persist-tun
> verb 3
> ca ca.crt
> cert server.crt
> key server.key
> dh dh2048.pem
>
> "Route rejected by Android10.8.0.6/30 Bad address"
>
> OpenVPN Connect will make the connection without issue.
> The only way successfully make the connection in OpenVPN for Android
> is to do it just after disconnecting in OpenVPN Connect.
>
>
Can you forward me the whole log of OpenVPN for android please?

Arne

**Comment by r2DoesInc** [comment]
Do you have an email I can send it to?

**Comment by schwabe** [comment]
arne-openvpn@rfc549.org

**Comment by schwabe** [comment]
The issue has been fixed in newer versions
