### ISSUE TITLE
Feature Request: "VPN Required" Mode

### ISSUE THREAD

**Issue by mvastola** [schwabe/ics-openvpn#900]
Something I've realized in using this app is that if the VPN disconnects for any reason (either temporarily, as in a reconnect, or permanently) -- even when it isn't prompted by the user -- the app tells the Android OS that there is no more VPN connection and therefore all apps revert to using a direct connection.

This may seem to make a lot of sense intuitively -- the VPN isn't connected, the system *should* know this. It may also seem to be obvious that this would happen. But it raises some important security concerns.

If people are using their VPN for privacy/security and especially if the VPN server is operating as the default gateway when connected, this will start putting all traffic out in the open. 

This can pose a major problem given that many apps auto-reconnect and many websites continue to fetch content even after the initial load. To make matters worse, this app isn't very loud about the connection breaking -- it just silently tries to reconnect. This could result in a false sense of security unless you happen to be observant enough to catch the status bar icon disappearing.

Ironically, the setting "Reconnect on Network Change" worsens this problem. You would think enabling this option helps keep the connection up, but on my phone at least (with UDP connections) the reconnect isn't required and the change is seamless with the connection never closing.

All that considered, I would like to request a the addition of a profile-level setting that basically locks down any internet access until a VPN connection is reestablished or it is manually disconnected. This can easily be done by simply not telling the system the VPN service has stopped and dropping all outgoing packets (or, as an added extra, maintaining backlog for TCP connections) until the server reconnects.

In this way, users can ensure there is no leaking of unsecured data from the time the VPN is activated to when it is manually turned off.

**Comment by mvastola** [comment]
This was [mentioned](https://github.com/schwabe/ics-openvpn/issues/370#issuecomment-191748786) in #370, but I'm not sure how much overlap there is. In any case, this is a simpler request and might be a good starting point.

**Comment by schwabe** [comment]
There is persist tun that keep the connection open. 

Other apps have "kill switches" or other features that sound like they help in this case but they are also only best effort solution giving you no true secuirty. (What does it help to block 95%?).

For a real solution use Android 8+ and use the Always on solution in there. THat is implemented on the OS level and actually works. 

For my app I don't want to implement a best effort solution that gives users a false sense of security

**Comment by mvastola** [comment]
Oh. That's very interesting (and very understandable). What is the mechanism that causes it to only work 95% of the time? I hadn't known that about kill switches.

And I have persist tun enabled and I still had that problem.

**Comment by schwabe** [comment]
There is no guarantee for your app not being killed or the app might just crash. And if your app does not run it cannot block traffic.

**Comment by mvastola** [comment]
Ah, I see. You can stop it from being killed by whitelisting from battery optimization. You're right about crashes though. I think I would use this feature (trusting the app not to crash), but I understand your reasoning.

**Comment by schwabe** [comment]
No, if the foreground app needs a lot of memory android will start background processes. There is no guarantee.  Battery optimisation is already not happening for this app since it displays the notifcation all the time.

**Comment by mvastola** [comment]
Oh wow. I mean I didn't think of OOM killer, but you'd think they'd make certain apps immune.

I'll check out the "always on" setting and see if it works. It would be great if that setting could at least be exposed inside the app, but I'm assuming Android doesn't allow the app to modify it. :-/

**Comment by schwabe** [comment]
No, you cannot modify it from a normal app. Only profile or device owner apps can do this (think MDM application).
