### ISSUE TITLE
Feature Request: Wi-Fi only

### ISSUE THREAD

**Issue by mvastola** [schwabe/ics-openvpn#901]
So this would likely pose a security issue unless used alongside the option requested in #900, but it would be helpful if there were some way to restrict a VPN connection from utilizing mobile data. This has a use because most people have data caps or overage fees or maximum allowances for fast mobile internet (4G/LTE). 

Many people use VPNs to mask their locations to allow them to access region-restricted multimedia content, and it can be a major issue if what they thought was a download via Wi-Fi switches to using their mobile data plan.

This is especially true for people with UDP VPNs where there won't ordinarily be a break in the VPN connection when the network switches, resulting in tunneled TCP data transfers (such as web downloads) continuing seamlessly. A setting on the VPN client would prevent this from happening.

**Comment by mvastola** [comment]
This is somewhat related to #370, but not exactly the same. I had an issue today where my wireless network was still connected, but I had the "You may not have access to the internet." warning. (There was presumably an issue with the internet connection beyond the router.) The app apparently switched to using mobile even though the Wifi was connected. 

What might have actually happened was there was no route allowing for connection to the WiFi gateway because it was removed upon switching to the mobile connection initially, so it couldn't switch back.

**Comment by schwabe** [comment]
Duplicate of #370
