### ISSUE TITLE
ip6 connections to local targets are routed through tunnel

### ISSUE THREAD

**Issue by heinrichrebehn** [schwabe/ics-openvpn#902]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: **8.1.0**
2. Android Vendor/Custom ROM: **Nokia**
3. Device: **Nokia 5**
4. Version of the app (version number/play store version/self-built)
   **OpenVPN für Android 0.6.73 via play store**
# Description of the issue

ip6 connections are routed through the tunnel although the target can be reached locally, which can be verified by disabling OpenVPN and still being able to connect (faster). This behaviour of course causes an unnecessary slowdown for local connections.

This has actually also been a temporary problem with ip4 under older Android versions. I had to disable/enable OpenVPN then. It is working now correctly with ip4

The local ip6 of the phone are
2a02:a00:e010:5001:f86e:f0af:50:8b43/64 and
2a02:a00:e010:5001:5ac9:35ff:fe1b:43e0/64
The target is at
2a02:a00:e010:5001::24/64

What am I missing? The option for specifying excluded ip6 routes is greyed out.

I am attaching a full log with the server ip replaced by $server_ip4

-Heinrich

[OpenVPN_log.txt](https://github.com/schwabe/ics-openvpn/files/2146203/OpenVPN_log.txt)

**Comment by heinrichrebehn** [comment]
Correction: App was installed via Fdroid rather than Play Store

**Comment by schwabe** [comment]
The feature to exclude local IPv6 networks is just not implemented yet.

**Comment by heinrichrebehn** [comment]
Thank you for clarifying!

May I suggest to mark not-yet-implemented features in the settings tab?
Then it would not be necessary to file a bug report.

Cheers,

	Heinrich
