### ISSUE TITLE
Internal storage permission

### ISSUE THREAD

**Issue by mesterj** [schwabe/ics-openvpn#903]
Hello

We use OpenVPN for Android on lots of devices. Many times I see OpenVPN is not connect. The problem is the read/write permission for storage is revoked from app. 
This is on Android 6 Lenovo Tablets actual stable version of program (from Play store)
Please use the Google adviced way for asking for permission to user. Or show me  how can OpenVPN work without this permission.

**Comment by schwabe** [comment]
Connecting should not be affected by internal storage permission at all. Also the app will ask for the permission. You need to provide more detail because I honestely don't understand what your problem is.

**Comment by mesterj** [comment]
I will make investigation. Close this ticket.
