### ISSUE TITLE
Reusable applications reconnecting

### ISSUE THREAD

**Issue by rdbox** [schwabe/ics-openvpn#904]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 4.2
2. Android Vendor/Custom ROM
3. Device samsung grand
4. Version of the app (version number/play store version/self-built)
 0.7.5
# Description of the issue
problem every 30-50 seconds, the application reconnects
I can not understand what's the matter, I use the same config on the laptop and everything is fine no problems.

**config client**
```
client
remote IP_SERVER 636
dev tun
proto tcp
cipher AES-128-CBC
auth SHA512
resolv-retry infinite
nobind
persist-key
persist-tun
remote-cert-tls server
verify-x509-name true-neutral-come name
tls-version-min 1.2
compress lz4
verb 3
route IP_SERVER 255.255.255.255 net_gateway


connect-retry 1
route-delay 8
auth-nocache


tun-mtu 1500
mssfix 1460

 
```

**Comment by rdbox** [comment]
logfile  openvpn for  samsung 
 [link](https://drive.google.com/file/d/1JL6A2ZgQLN1k8JnSyg4BOwCsDzz-WqbE/view?usp=drivesdk)

**Comment by schwabe** [comment]
2018-06-30 22:18:17 Connection reset, restarting [0]

THis is either a network problem or a broken Samsung energy management (see FAQ).

**Comment by rdbox** [comment]
how can you verify, and be sure that this is so?
Because it did not always happen???
