### ISSUE TITLE
Can not load .ovpn files on a Android phone

### ISSUE THREAD

**Issue by jerryx-first** [schwabe/ics-openvpn#907]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version-------Android 6.0.1
2. Android Vendor/Custom ROM---------a Chinese Vendor called XiaoMi and Rom is MIUI 8.5
3. Device------A Redmi Note 4X with Snapdragon625
4. Version of the app (version number/play store version/self-built)
 0.7.5 Get from Google Play <https://play.google.com/store/apps/details?id=de.blinkt.openvpn>
# Description of the issue
When i open this App and try to  load a configuration file from my Android phone, i can only access the folders but can not see any .ovpn or .conf files from the folders and can not load those file also. 
My provider only offers the .ovpn  certificate to me so i can not use this service with this APP

**Comment by schwabe** [comment]
Duplicate see other issues. And try to use internal file browser under Options if your phone has a strange file browser shipped with it.

**Comment by jerryx-first** [comment]
I will try. But the file broswer is a built-in broswer in MIUI ROM and no any other file broswer has been installed on this phone ever.
Maybe i need to try the file broswer for the native android?
Thanks for you answer.

Other information: I tested the OpenVPN App powered by official group and they can load the file. Maybe it help

**Comment by schwabe** [comment]
In my app you can select under general settings what file browser you want to use. If neither works, I have no idea what is wrong. Then use an external file browser=> open ovpn file => select import with openvpn.
