### ISSUE TITLE
Excluded apps in the "Allowed apps" tab are not excluded from the VPN connection

### ISSUE THREAD

**Issue by shellt0pia** [schwabe/ics-openvpn#908]
# General information
1. Android 8.1.0
2. LineageOS 15.1 for microG
3. OnePlus One (A0001)
4. Version of the app: 0.7.5 from F-Droid
 
# Description of the issue
Excluded apps in the "Allowed apps" tab are not excluded from the VPN connection. "VPN is used for all apps but exclude selected" is enabled, Netflix is enabled in the list but it's still using the VPN connection and complains about it. Same for the Android TV remote app that doesn't find my Shield TV while connected to my home Wi-Fi anymore.  

I also tried to exclude Firefox Focus but not Firefox Nightly, got to myip.com and both were showing my VPN exit node IP.  

Problem is, I don't exactly know when this problem first came up. There's a great chance though that it began when I upgraded from LineageOS 14.1 (Android 7.1.1) to LineageOS 15.1 (Android 8.1.0) last week.  

If you need me to do some testing, feel free to ask!

EDIT: I tried to recreate the VPN profile but it didn't solve the problem. I'm gonna try to erase the application data and report back.

EDIT2: I cleared the application data and recreated the profile and it didn't solve the problem either :-/

**Comment by schwabe** [comment]
OpenVPN for Android does implement basically noething for the allowed app feature and only forwards that list of apps to Android. 

What you are seeing is probably more a bug in your Android ROM.
