### ISSUE TITLE
Auto Reconnect After 1 Min

### ISSUE THREAD

**Issue by mynitehawk** [schwabe/ics-openvpn#909]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version: 8.0.0
2. Android Vendor: Samsung 
3. Device: Galaxy Note 8
4. Version of the app (version number/play store version/self-built) 3.0.5
 
# Description of the issue
1) It will auto reconnect to the server after 1 minute even after a successful connection.
2) Despite connected, IP address assigned by server, I am unable to access VPN server's internal servers.

I was able to access the same VPN server's internal servers using OpenVPN Connect app v1.1.16 with Android 7.1.

**Comment by schwabe** [comment]
You should also add a log this it contains the reason why the client thinks it needs to reconnect.
