### ISSUE TITLE
App reconnects after receiving disconnect/kill request from VPN Server 

### ISSUE THREAD

**Issue by anshul-arora** [schwabe/ics-openvpn#911]
Hello,

when the VPN server runs a script to disconnect a user from the server and perform appropriate action to blacklist the user/device, How will the app be notified about it?

Currently, I am getting Reconnect status in OpenVPN for Android application and it reconnects to the server, which I don't wish to do.

**Comment by schwabe** [comment]
it gets an AUTH_FAILED message. The app behaves like a normal OpenVPN client in this regard. So do whatever you also would do with a normal OpenVPN client. The app is not special in any sense here.
