### ISSUE TITLE
Feature Request: TAP

### ISSUE THREAD

**Issue by vezza** [schwabe/ics-openvpn#912]
It will be useful to have TAP on a rooted Android

**Comment by schwabe** [comment]
Rooted devices are becoming less and less common. Also I personally don't have any rooted devices, so I cannot develop or test this feature. And tap seems to be not commonly used anyway.

**Comment by schwabe** [comment]
Yes, but users with rooted devices are small minority and of those, people who need tap are even fewer. If tap is going to be supported, it will be the emulation that is stated in the FAQ

Also I don't have any rooted devices and cannot develop the feature. If I get a resonable pull request, I can integrate but until then, it is not something I will implement.
