### ISSUE TITLE
VPN permission revoked by OS

### ISSUE THREAD

**Issue by wryp** [schwabe/ics-openvpn#916]
- Poin2 Chromebook running the latest stable version of ChromeOS
- OpenVPN for Android 0.7.5
 
First, I very much appreciate OpenVPN for Android, thank you for doing it.

Everything was working normally but starting a few weeks ago, the VPN will disconnect a few minutes after connecting. It happens on more than one Chromebook (same model).

The log shows, for instance:

1:56 PM Initialization Sequence Completed
2:00 PM VPN permission revoked by OS (e.g. other VPN program started), stopping VPN
2:00 PM Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2:00 PM Sorry, deleting routes on Android is not possible. The VpnService API allows routes to be set on connect only.
2:00 PM SIGINT[hard,] received, process exiting

Regarding "other VPN program started", I don't have any other VPN or related program installed that I know of.

More than one user is set up on the Chromebook, and I seem to remember seeing a setting when I set up the VPN connection the first time that said something like "Share this connection with other users?", but I can't find that setting anywhere in the client settings or in the Chromebook settings. Not sure if that could be related.

Any ideas?  

Thank you.

**Comment by schwabe** [comment]
Anything else that is not a VPN program but claims to be one? (Socks proxies, Firewall apps, Tor apps)

But yes the message basically says that Android (or the Android emulator) is taking away the VPN permission from the app. On the Chromebook emulator I cannot reproduce this.
