### ISSUE TITLE
LoadLibrary

### ISSUE THREAD

**Issue by arun2** [schwabe/ics-openvpn#917]
Dear Developer-  Good day. I have a question  in mind for many years.  I  have checked all code  but  I do not understand  how  openvpn.so  is loaded.

In old code only following code is used 
`System.loadLibrary("opvpnutil");`

In latest code following 2 lines used 
```
System.loadLibrary("opvpnutil");
System.loadLibrary("ovpn3");
```

I have checked  binary  libopvpnutil.so  file . It does not link   libopenvpn.so  file .  
So how   libopenvpn.so is actually loaded.

Can you please tell me.

Thank you in advance

**Comment by schwabe** [comment]
See the FAQ in doc/readme
