### ISSUE TITLE
Options error: --http-proxy not specified but other http proxy options present

### ISSUE THREAD

**Issue by kikitte** [schwabe/ics-openvpn#919]
1. Android 8.1
2. Nitrogen OS
3. Xiaomi Redmi Note 3 pro
4. OpenVPN for Android 0.7.5
 
the config contains two lines like this, and xxx.xxx.x.x is IP Adderss
`http-proxy xxx.xxx.x.x 8080`
`http-proxy-option EXT1 'X-Online-Host: xxx.xxx.x.xx`

it works fine on version 0.7.3, but on version 0.7.5 I got this error message:

`2018-08-06 17:51:59 Options error: --http-proxy not specified but other http proxy options present`
`2018-08-06 17:51:59 Use --help for more information.`
`2018-08-06 17:51:59 Process exited with exit value 1`

but http proxy was already set, if delete the http-proxy-optons line, it works fine on version 0.7.5 too.

**Comment by schwabe** [comment]
Fixed already in 89545dcbcbd867a407c5f9c30a7f17adc76b748a
