### ISSUE TITLE
Always-on VPN breaks mobile networking?

### ISSUE THREAD

**Issue by gergelyimre** [schwabe/ics-openvpn#920]
1. Android version: 8.0.0, security match May 1, 2018, Kernel 3.18.71
3. Device: Motorola Moto G6, Software channel: reteu
4. OpenVPN for Android from the Play Story, version 0.7.5

I am using OpenVPN for Android to connect to own OpenVPN server and it works great on WiFi, and also works great on mobile network (Orange).

When I enable "Always-On" and "Block connections without VPN", and then enable mobile data, it won't connect. 4G appears in the status bar on the right, but I see an "X" on the mobile data connection icon, like there is no connection, and OpenVPN just says "network unreachable" over and over again.
This same setup works ok on WiFi. Somehow the mobile data connection gets affected by these settings.

The phone is not rooted.

Can this be a limitation of my particular Android on Motorola phones? Is there a way around it? Basically I would like to have the VPN always running, and all traffic going through it, no matter what network I'm on.

**Comment by schwabe** [comment]
Normally what you are describing works. It works at least on my Pixel phones here. Does DNS resolution of the VPN server when connecting via mobile? (Or add a log)

**Comment by gergelyimre** [comment]
The VPN server is specified with IP address, not by hostname. I did some digging through the routes with adb shell, and it seem the default gateway for the mobile connection does not get populated for some reason, see below

With all networking disabled:

ali_n:/ $ ip ru sh
0:      from all lookup local
10000:  from all fwmark 0xc0000/0xd0000 lookup 99
10500:  from all oif dummy0 uidrange 0-0 lookup 1002
12500:  from all fwmark 0x0/0x20000 iif lo uidrange 0-10199 prohibit
12500:  from all fwmark 0x0/0x20000 iif lo uidrange 10201-99999 prohibit
13000:  from all fwmark 0x10063/0x1ffff lookup 97
14000:  from all oif dummy0 lookup 1002
15000:  from all fwmark 0x0/0x10000 lookup 99
16000:  from all fwmark 0x0/0x10000 lookup 98
17000:  from all fwmark 0x0/0x10000 lookup 97
23000:  from all fwmark 0x0/0xffff uidrange 0-0 lookup main
32000:  from all unreachable

With mobile networking enabled + VPN connected but "Block connections without VPN" _disabled_:

ali_n:/ $ ip ru sh
0:      from all lookup local
10000:  from all fwmark 0xc0000/0xd0000 lookup 99
10500:  from all oif dummy0 uidrange 0-0 lookup 1002
10500:  from all oif rmnet_data0 uidrange 0-0 lookup 1006
11000:  from all iif tun0 lookup 97
12000:  from all fwmark 0x0/0x20000 iif lo uidrange 0-10199 lookup 1034
12000:  from all fwmark 0x0/0x20000 iif lo uidrange 10201-99999 lookup 1034
12000:  from all fwmark 0xc0082/0xcffff lookup 1034
13000:  from all fwmark 0x10063/0x1ffff lookup 97
13000:  from all fwmark 0x10081/0x1ffff lookup 1006
13000:  from all fwmark 0x10082/0x1ffff uidrange 0-10199 lookup 1034
13000:  from all fwmark 0x10082/0x1ffff uidrange 10201-99999 lookup 1034
13000:  from all fwmark 0x10082/0x1ffff uidrange 0-0 lookup 1034
14000:  from all oif dummy0 lookup 1002
14000:  from all oif rmnet_data0 lookup 1006
14000:  from all oif tun0 uidrange 0-10199 lookup 1034
14000:  from all oif tun0 uidrange 10201-99999 lookup 1034
15000:  from all fwmark 0x0/0x10000 lookup 99
16000:  from all fwmark 0x0/0x10000 lookup 98
17000:  from all fwmark 0x0/0x10000 lookup 97
19000:  from all fwmark 0x81/0x1ffff lookup 1006
21000:  from all fwmark 0x82/0x1ffff lookup 1006
22000:  from all fwmark 0x0/0xffff lookup 1006
23000:  from all fwmark 0x0/0xffff uidrange 0-0 lookup main
32000:  from all unreachable

ali_n:/ $ ip r sh table 1006
default via 10.192.123.61 dev rmnet_data0  proto static

With mobile network connected + VPN running and "Block connections" _enabled_:

ali_n:/ $ ip ru sh
0:      from all lookup local
10000:  from all fwmark 0xc0000/0xd0000 lookup 99
10500:  from all oif dummy0 uidrange 0-0 lookup 1002
10500:  from all oif rmnet_data0 uidrange 0-0 lookup 1006
11000:  from all iif tun0 lookup 97
12000:  from all fwmark 0x0/0x20000 iif lo uidrange 0-10199 lookup 1034
12000:  from all fwmark 0x0/0x20000 iif lo uidrange 10201-99999 lookup 1034
12000:  from all fwmark 0xc0082/0xcffff lookup 1034
12500:  from all fwmark 0x0/0x20000 iif lo uidrange 0-10199 prohibit
12500:  from all fwmark 0x0/0x20000 iif lo uidrange 10201-99999 prohibit
13000:  from all fwmark 0x10063/0x1ffff lookup 97
13000:  from all fwmark 0x10082/0x1ffff uidrange 0-10199 lookup 1034
13000:  from all fwmark 0x10082/0x1ffff uidrange 10201-99999 lookup 1034
13000:  from all fwmark 0x10082/0x1ffff uidrange 0-0 lookup 1034
13000:  from all fwmark 0x10084/0x1ffff lookup 1006
14000:  from all oif dummy0 lookup 1002
14000:  from all oif tun0 uidrange 0-10199 lookup 1034
14000:  from all oif tun0 uidrange 10201-99999 lookup 1034
14000:  from all oif rmnet_data0 lookup 1006
15000:  from all fwmark 0x0/0x10000 lookup 99
16000:  from all fwmark 0x0/0x10000 lookup 98
17000:  from all fwmark 0x0/0x10000 lookup 97
19000:  from all fwmark 0x84/0x1ffff lookup 1006
21000:  from all fwmark 0x82/0x1ffff lookup 1006
22000:  from all fwmark 0x0/0xffff lookup 1006
23000:  from all fwmark 0x0/0xffff uidrange 0-0 lookup main
32000:  from all unreachable
ali_n:/ $
ali_n:/ $ ip r sh table 1006
ali_n:/ $

I could be way off, but something seems to get messed up after enabling the "Block connections without VPN" option. I see that only two lines get added (the "prohibited" ones), unfortunately I have no root (and I dont want to root the phone) to mess around with these rules.

Does this help somewhat?

**Comment by gergelyimre** [comment]
Also, I'm getting an IP address on the mobile data interface (rmnet_data0), but the default gateway for that connection doesn't get set up, that means the VPN connection doesn't get set up, and there is no DNS (which should go through the VPN), maybe that's why the mobile data connection doesn't get set up and doesn't trigger a VPN connection, or I'm not sure what's the order... I have no idea how a network connection is set up on Android...

rmnet_data0 Link encap:UNSPEC
          inet addr:10.113.208.189  Mask:255.255.255.252
          UP RUNNING  MTU:1410  Metric:1
          RX packets:2623 errors:0 dropped:0 overruns:0 frame:0
          TX packets:2750 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:1016538 TX bytes:499245

**Comment by schwabe** [comment]
Might be interesting to use DNS instead of an IP to see if that step at least works.

My Pixel routing tables look similar  (with always on enabled but VPN disconnected):

```
marlin:/ $ ip ru sh
0:	from all lookup local 
10000:	from all fwmark 0xc0000/0xd0000 lookup 99 
10500:	from all iif lo oif dummy0 uidrange 0-0 lookup 1003 
10500:	from all iif lo oif rmnet_data7 uidrange 0-0 lookup 1016 
10500:	from all iif lo oif rmnet_data6 uidrange 0-0 lookup 1015 
10500:	from all iif lo oif rmnet_data0 uidrange 0-0 lookup 1009 
12500:	from all fwmark 0x0/0x20000 iif lo uidrange 0-10244 prohibit
12500:	from all fwmark 0x0/0x20000 iif lo uidrange 10246-99999 prohibit
13000:	from all fwmark 0x10063/0x1ffff iif lo lookup 97 
13000:	from all fwmark 0x1000b/0x1ffff iif lo lookup 1016 
13000:	from all fwmark 0xd0066/0xdffff iif lo lookup 1015 
13000:	from all fwmark 0x10065/0x1ffff iif lo lookup 1009 
14000:	from all iif lo oif dummy0 lookup 1003 
14000:	from all iif lo oif rmnet_data7 lookup 1016 
14000:	from all fwmark 0xc0000/0xc0000 iif lo oif rmnet_data6 lookup 1015 
14000:	from all iif lo oif rmnet_data0 lookup 1009 
15000:	from all fwmark 0x0/0x10000 lookup 99 
16000:	from all fwmark 0x0/0x10000 lookup 98 
17000:	from all fwmark 0x0/0x10000 lookup 97 
19000:	from all fwmark 0xb/0x1ffff iif lo lookup 1016 
19000:	from all fwmark 0x65/0x1ffff iif lo lookup 1009 
22000:	from all fwmark 0x0/0xffff iif lo lookup 1009 
32000:	from all unreachable
marlin:/ $
```

But I also don't have an X on the mobile data icon even though nothing works.

**Comment by gergelyimre** [comment]
I found this in logcat when enabling mobile networking:

08-07 14:24:30.828  2860 22758 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 134]: PROBE_DNS www.google.com 3ms FAIL
08-07 14:24:30.828  2860 22759 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 134]: PROBE_DNS connectivitycheck.gstatic.com 3ms FAIL
08-07 14:24:30.831  2860 22758 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 134]: PROBE_HTTPS https://www.google.com/generate_204 Probably not a portal: exception java.net.UnknownHostException: Unable to resolve host "www.google.com": No address associated with hostname
08-07 14:24:30.831  2860 22759 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 134]: PROBE_HTTP http://connectivitycheck.gstatic.com/generate_204 Probably not a portal: exception java.net.UnknownHostException: Unable to resolve host "connectivitycheck.gstatic.com": No address associated with hostname
08-07 14:24:30.836  2860 22680 D NetworkMonitor/NetworkAgentInfo [MOBILE (LTE) - 134]: PROBE_FALLBACK http://www.google.com/gen_204 Probably not a portal: exception java.net.UnknownHostException: Unable to resolve host "www.google.com": No address associated with hostname
08-07 14:24:30.869  2860  3232 D ConnectivityService: NetworkAgentInfo [MOBILE (LTE) - 134] validation failed

**Comment by schwabe** [comment]
It is really hard to figure out what is broken there. The app does not even know or does anything different when "Always On" or "block other conections" is enabled. From the app's perspective it is all the same.

**Comment by gergelyimre** [comment]
Check this out. When enabling the mobile connection, I get the following:

08-07 14:27:34.193  2860  4026 D ConnectivityService: registerNetworkAgent NetworkAgentInfo{ ni{[type: MOBILE[LTE], state: CONNECTED/CONNECTED, reason: connected, extra: net, failover: false, available: true, roaming: false, metered: true]}  network{135}  nethandle{579837020894}  lp{{InterfaceName: rmnet_data0 LinkAddresses: [10.113.208.189/30,]  Routes: [0.0.0.0/0 -> 10.113.208.190 rmnet_data0,] DnsAddresses: [109.166.202.53,109.166.202.54,] Domains: null MTU: 1410 TcpBufferSizes: 524288,1048576,8388608,262144,524288,4194304}}  nc{[ Transports: CELLULAR Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN LinkUpBandwidth>=51200Kbps LinkDnBandwidth>=102400Kbps Specifier: <1>]}  Score{10}  everValidated{false}  lastValidated{false}  created{false} lingering{false} explicitlySelected{false} acceptUnvalidated{false} everCaptivePortalDetected{false} lastCaptivePortalDetected{false} }
08-07 14:27:34.201  2245  2559 E Netd    : Error adding route 0.0.0.0/0 -> 10.113.208.190 rmnet_data0 to table 1006: Permission denied
08-07 14:27:34.202  2860  3232 E ConnectivityService: Exception in addRoute for gateway: java.lang.IllegalStateException: command '697 network route add 135 rmnet_data0 0.0.0.0/0 10.113.208.190' failed with '400 697 addRoute() failed (Permission denied)'
08-07 14:27:34.235  2860  3232 D ConnectivityService: Switching to new default network: NetworkAgentInfo{ ni{[type: MOBILE[LTE], state: CONNECTED/CONNECTED, reason: connected, extra: net, failover: false, available: true, roaming: false, metered: true]}  network{135}  nethandle{579837020894}  lp{{InterfaceName: rmnet_data0 LinkAddresses: [10.113.208.189/30,]  Routes: [0.0.0.0/0 -> 10.113.208.190 rmnet_data0,] DnsAddresses: [109.166.202.53,109.166.202.54,] Domains: null MTU: 1410 TcpBufferSizes: 524288,1048576,8388608,262144,524288,4194304}}  nc{[ Transports: CELLULAR Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VPN&FOREGROUND LinkUpBandwidth>=51200Kbps LinkDnBandwidth>=102400Kbps Specifier: <1>]}  Score{10}  everValidated{false}  lastValidated{false}  created{true} lingering{false} explicitlySelected{false} acceptUnvalidated{false} everCaptivePortalDetected{false} lastCaptivePortalDetected{false} }

**Comment by gergelyimre** [comment]
Why isn't it able to add the default route? That is the reason it won't go up, no default route = no network access. But why is the option "Block network without VPN" prevent it from adding a default route to the internal routing table (1006) ?

**Comment by gergelyimre** [comment]
Alright, false alarm, at least it's not an OpenVPN for Android problem, but an Android problem.

https://github.com/AndroidHardeningArchive/bugtracker/issues/744

Sorry to disturb you :)

**Comment by schwabe** [comment]
No problem. Could have been a bug in my app as well. Such details are most times not obvious to the normal user.

But from the Google bug report it sounds that this does not affect all mobile network but depends on the specific interface configuration and with Orange you are out of luck :/

Based on the date it seem that this patch should be in Android 8.1.

I am closing as it seem that other than hopeing for an Android update from Motorola (or a custom ROM), there is not much we can do at this point.

**Comment by gergelyimre** [comment]
Agreed. Thank you for a great app though. Time to donate ;)
