### ISSUE TITLE
How to update OpenSSL v 1.1.0 in Android Studio 3.1.2

### ISSUE THREAD

**Issue by softdev8** [schwabe/ics-openvpn#922]
How to update OpenSSL version 1.0.1 to 1.1.0

# General information
1. Android Studio 3.1.2, build:gradle v 3.1.3, gradle version gradle-4.5-all
2. ndk_build with jni, Android.mk
3. Android Build version 26
It working well on device. But when i try to upload on play store, it rejected. because security vulnerabilities.
The vulnerabilities were addressed in OpenSSL 1.0.2. so, I tried to update it.
I am using old version with Android.mk file on jni. How can i update it?

Hope to your good news.

**Comment by schwabe** [comment]
Care to share the source of your project?

**Comment by softdev8** [comment]
Yes, that's private by Customer. Can I build .so file using ndk_build on Android Studio 3.1.2?

**Comment by schwabe** [comment]
No it is not private. It is GPL. Unless you paid me for the license, you are legally bound to share the source code of your app. 

Please understand that I have absolutely no interest in helping people who do not repsect the license of my app.

**Comment by softdev8** [comment]
--- Build.gradle----
apply plugin: 'com.android.application'

repositories {
    mavenCentral()
}

dependencies {
    ....
}

android {
    compileSdkVersion 27
    buildToolsVersion '27.0.3'

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 27
        versionCode = 3
        versionName = "1.2"
    }

    packagingOptions {
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/NOTICE'
    }

    sourceSets {
        main {
            assets.srcDirs = ['src/main/assets', 'ovpnlibs/assets']
            jniLibs.srcDirs = ['ovpnlibs/jniLibs']
            jni.srcDirs = [] //disable automatic ndk-build
        }

        androidTest.setRoot('ovpn3')
        debug {
        }

        release {
        }
    }

    signingConfigs {
        release
    }

    lintOptions {
        enable 'BackButton', 'EasterEgg', 'StopShip', 'IconExpectedSize', 'GradleDynamicVersion', 'NewerVersionAvailable'
        disable 'MissingTranslation'
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
        }
    }

    flavorDimensions "default"

    productFlavors {
        normal
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

// ~/.gradle/gradle.properties
if (project.hasProperty('keystoreFile') &&
        project.hasProperty('keystorePassword') &&
        project.hasProperty('keystoreAliasPassword')) {
    android.signingConfigs.release.storeFile = file(keystoreFile)
    android.signingConfigs.release.storePassword = keystorePassword
    android.signingConfigs.release.keyPassword = keystoreAliasPassword
    android.signingConfigs.release.keyAlias = keystoreAlias
} else {
    android.buildTypes.release.signingConfig = null
}
-------------
--- Android.mk ---
# Path of the sources
JNI_DIR := $(call my-dir)

#optional arguments
#WITH_POLAR=1
#WITH_OPENVPN3=1
# Build openvpn with polar (OpenVPN3 core is always build with polar)
WITH_BREAKPAD=0

include lzo/Android.mk
include openssl/Android.mk

ifeq ($(TARGET_ARCH),mips)
	USE_BREAKPAD=0
endif
ifeq ($(TARGET_ARCH),mips64)
	USE_BREAKPAD=0
endif

ifeq ($(TARGET_ARCH),build-native)
	USE_BREAKPAD=0
endif

ifeq ($(WITH_POLAR),1)
	USE_POLAR=1
endif
ifeq ($(WITH_OPENVPN3),1)
	USE_POLAR=1
endif

ifeq ($(USE_POLAR),1)
	include polarssl/Android.mk
endif

include openvpn/Android.mk

ifeq ($(WITH_OPENVPN3),1)
	include ovpn3/Android.mk
endif

LOCAL_PATH := $(JNI_DIR)

# The only real JNI library
include $(CLEAR_VARS)
LOCAL_LDLIBS := -llog  -lz
LOCAL_C_INCLUDES := openssl/include openssl/crypto openssl 
LOCAL_SRC_FILES:= jniglue.c jbcrypto.cpp
LOCAL_MODULE = opvpnutil
LOCAL_SHARED_LIBRARIES :=  libcrypto
include $(BUILD_SHARED_LIBRARY)

-----------------------------------------------
What source do you need more?
Thanks for your help.

**Comment by schwabe** [comment]
See theFAQ in the README, especially this:

Q: Why are you not answering my questions about modifying
   ics-openvpn/why do not help build my app on top of ics-openvpn? I
   thought this is open source.

A: There are many people building/wanting to build commercial VPN
   clients on top of my of my client. These client often do not even
   honour the license of my app or the license of OpenVPN. Even if
   these modified software do honour the license, I don't like doing
   unpaid work/giving advice for free to commercial software
   developers.
   
   If you have a legitimate non-commercial open source project, I will
   gladly help you, but please understand my initial reservations.

In short I will not help you unless you come clear about your project or you pay me for a license and the hours I help you.
