### ISSUE TITLE
In remote example service won't bind unless you install the main app too.

### ISSUE THREAD

**Issue by UgniusV** [schwabe/ics-openvpn#924]
If you only install the remote example app on your device and try to connect to the service with:
` 
getActivity().bindService(icsopenvpnService, mConnection, Context.BIND_AUTO_CREATE);
    `
getActivity().bindService will return false and the ServiceConnection Callbacks won't be executed.

**Comment by khizar1556** [comment]
hello sir @UgniusV  your app is working well? if your app is working well please share code with me at ranakhizar1556@gmail.com becuase on my system cmakelists.txt file is not working well i cant be able to build my project coreectly

**Comment by schwabe** [comment]
yeah, the remote example is not perfect and does not catch all cases. It should just serve as a starting point to get you going. But improvements in form of pull requests are always welcome
