### ISSUE TITLE
Problems during compile

### ISSUE THREAD

**Issue by khizar1556** [schwabe/ics-openvpn#925]
Build command failed.

Error while executing process D:\sdk1\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\android_projects\vpn\ics-openvpn-master\main\src\main\cpp -BD:\android_projects\vpn\ics-openvpn-master\main\.externalNativeBuild\cmake\normalDebug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\android_projects\vpn\ics-openvpn-master\main\build\intermediates\cmake\normal\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=D:\sdk1\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=D:\sdk1\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\sdk1\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}

-- Check for working C compiler: D:/sdk1/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

-- Check for working C compiler: D:/sdk1/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: D:/sdk1/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe

-- Check for working CXX compiler: D:/sdk1/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

OpenVPN 2.x version HEAD-HASH-NOTFOUND

OpenVPN 3.x version HEAD-HASH-NOTFOUND

-- The ASM compiler identification is Clang

-- Found assembler: D:/sdk1/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

CMake Error at D:/sdk1/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):

-- Configuring incomplete, errors occurred!

See also "D:/android_projects/vpn/ics-openvpn-master/main/.externalNativeBuild/cmake/normalDebug/armeabi-v7a/CMakeFiles/CMakeOutput.log".

please make this error free i am in tension please help me to get out of this

**Comment by UgniusV** [comment]
Hi, you forgot to ran git submodule init and git submodule update. Invalidate caches and restart AS afterwards.

**Comment by khizar1556** [comment]
@UgniusV how can i ran this? can you please guide i put this on Git bash then error is occured
fatal: not a git repository (or any of the parent directories): .git

**Comment by UgniusV** [comment]
1) clone the project correctly and you won't get "fatal: not a git repository (or any of the parent directories): .git" error
2) after you cloned your project open it in AS and run the commands I mentioned before from AS terminal

**Comment by khizar1556** [comment]
Thanks for guide me @UgniusV  👍

**Comment by talwl** [comment]
You're great.Thanks. @UgniusV 👍
