### ISSUE TITLE
Only include apps feature 

### ISSUE THREAD

**Issue by paragbaxi** [schwabe/ics-openvpn#928]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 9
2. Android Vendor/Custom ROM Google 
3. Device Pixel 2 XL 
4. Version of the app (version number/play store version/self-built) 0.7.5
 
# Description of the issue
I use Chrome Beta for all work stuff on my personal phone. I want my work VPN to only include Chrome Beta. To do it today, I have to manually exclude every Android app which is very time consuming. I would like to have a quick way to only include. 

Thank you

**Comment by tomty89** [comment]
![_20180822_232637](https://user-images.githubusercontent.com/8604057/44473450-df68e700-a662-11e8-9b5f-9ce53d0913b3.JPG)
![_20180822_232615](https://user-images.githubusercontent.com/8604057/44473458-e5f75e80-a662-11e8-8751-917db840cf0f.JPG)

**Comment by schwabe** [comment]
Like @tomty89 says, already implemented.
