### ISSUE TITLE
Cached Remote Address is not updated 

### ISSUE THREAD

**Issue by chris1911** [schwabe/ics-openvpn#929]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. 7.1.2
2. Lineage
3. N7000
4. 0.7.5/f-droid
 
My OpenVPN server is at home and gets a new ip address every 24h hours.
hence one uses a ddns provider to use a dns name instead.
The dns lookup points to the new assigned ip address.
When I connect to my vpn on yesterday, the vpn client caches the ip address for the host name. But the cache is not invalidaed after 1h or so. Instead it still uses the then old ip address and the connection fails. Also a reboot of the phone did not clear the cache.

There is a common log line found in many openvpn logs on the net:
"Preserving recently used remote address: <ip-address>"
I alrady tried a search for the text in the source code but without success.
When I set the new ip address instead of the host name, the client connects flawlessly.

How do you switch off this cache for good or at least invalidate the cache every 1h?

**Comment by schwabe** [comment]
you probably have persist-tun on.  Otherwise openvpn should reresolve the address.

**Comment by 1izheng** [comment]
How do I clear this cache, I connect to different servers twice, and the IP doesn't change
@schwabe

**Comment by 1izheng** [comment]
Resolved, unsave it
@chris1911 
         ProfileManager vpl = ProfileManager.getInstance(context.get());
//            vpl.saveProfile(context.get(), vp);
//            vpl.saveProfileList(context.get());

**Comment by schwabe** [comment]
The code you have posted has absolute nothing to do with the resolve cache.

I am clsoing this issue since the underlying problem of not being able to resolve DNS when persistent tun is on is a completely different one
