### ISSUE TITLE
Run script when network changes 

### ISSUE THREAD

**Issue by rajil** [schwabe/ics-openvpn#930]
I have an up script defined to set DNS as follows,

up /data/data/de.blinkt.openvpn/cache/updns.sh

The script does execute correctly when openvpn is run for the first time. However, when the network changes from Wifi to LTE the script does not run. Is it possible to make the script each time the network changes?
Here is the log which shows that 'up' script is not executed on network change, 

2:52 PM Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA  
3:06 PM Network Status: not connected  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM Network Status: CONNECTED LTE to MOBILE apn.com  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM write UDP []: Network is unreachable (code=101)  
3:06 PM Network Status: CONNECTED  to WIFI "Guest"

**Comment by schwabe** [comment]
up is only run when openvpn reconnects. I don't see a reconnect in your log. Your service probably is OpenVPN 2.4 or newer and OpenVPN can use float and so doesn't reconnect and therefore also up is not run again.

**Comment by rajil** [comment]
I disabled 'float' on the openvpn server running on pfsense. However, still I don't see a reconnect in the client.

8:39 AM /data/data/de.blinkt.openvpn/cache/updns.sh vpnservice-tun 1500 1552 10.8.10.2 255.255.255.0 init  
8:39 AM Initialization Sequence Completed  
8:39 AM MANAGEMENT: >STATE:1535549942,CONNECTED,SUCCESS,ip address
9:14 AM Network Status: not connected  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM Network Status: CONNECTED LTE to MOBILE apn.com  
9:14 AM Network Status: CONNECTED  to WIFI "GUEST"

**Comment by rajil** [comment]
I disabled 'float' on the openvpn server running on pfsense. However, still I don't see a reconnect in the client.

8:39 AM /data/data/de.blinkt.openvpn/cache/updns.sh vpnservice-tun 1500 1552 10.8.10.2 255.255.255.0 init  
8:39 AM Initialization Sequence Completed  
8:39 AM MANAGEMENT: >STATE:1535549942,CONNECTED,SUCCESS,ip address
9:14 AM Network Status: not connected  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM write UDP []: Network is unreachable (code=101)  
9:14 AM Network Status: CONNECTED LTE to MOBILE apn.com  
9:14 AM Network Status: CONNECTED  to WIFI "GUEST"


My server config is, 


dev ovpns2
verb 1
dev-type tun
dev-node /dev/tun2
writepid /var/run/openvpn_server2.pid
#user nobody
#group nobody
script-security 3
daemon
keepalive 10 60
ping-timer-rem
persist-tun
persist-key
proto udp4
cipher AES-128-CBC
auth SHA1
up /usr/local/sbin/ovpn-linkup
down /usr/local/sbin/ovpn-linkdown
local wan-ip
engine rdrand
tls-server
server 10.8.10.0 255.255.255.0
client-config-dir /var/etc/openvpn-csc/server2
tls-verify "/usr/local/sbin/ovpn_auth_verify tls 'LanVPNServer' 1"
lport 1194
management /var/etc/openvpn/server2.sock unix
push "redirect-gateway def1"
ca /var/etc/openvpn/server2.ca
cert /var/etc/openvpn/server2.cert
key /var/etc/openvpn/server2.key
crl-verify /var/etc/openvpn/server2.crl-verify
tls-auth /var/etc/openvpn/server2.tls-auth 0
ncp-ciphers AES-256-GCM:AES-128-GCM
topology subnet
keepalive 10 60

**Comment by schwabe** [comment]
This has nothing to do with float. This the peer-id functionality that is present in newer clients (>=2.3.somethign) and 2.4.x for server.

You can try to use push-filter remove as custom option to remove this option but this may also affect the client negatively you get a new NAT address in mobile networks.
