### ISSUE TITLE
Feature: SOCKS5 mode?

### ISSUE THREAD

**Issue by bjohas** [schwabe/ics-openvpn#931]
Hope this is the right place to psot this. It looks like openvpn for Android doesn't offer chaining via socks5? Would it be feasible to add this feature?

Use case: I use netguard, a non-root firewall, using the VPN service. It can chain using SOCKS5, by routing traffic traffic via a local SOCKS5 proxy. 

However, it seems that there presently are no apps offering this, see https://forum.xda-developers.com/android/apps-games/app-netguard-root-firewall-t3233012/page740

Hence would it be feasible to build a mode into openvpn, that connects to a VPN, and offers a local socks5 port, without using the android VPN service?

**Comment by schwabe** [comment]
OpenVPN does not offer a SOCKS5 proxy since it is a VPN and not a proxy.

**Comment by bjohas** [comment]
Thanks! The netguard developer suggested that socks5 is a way of chaining vpns, hence the question.
