### ISSUE TITLE
Build Command failed

### ISSUE THREAD

**Issue by aries255** [schwabe/ics-openvpn#932]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

Hello Sir, Im having trouble building the project. I have this error. I already installed my cmake (3.6.4111459), lldb (3.1.4508709), ndk (17.1.4828580)

# General information
1. compileSdkVersion 28
2. minSdkVersion 14
3. buildToolsVersion '28.0.0'
4. externalNativeBuild {
            cmake {
                arguments '-DANDROID_TOOLCHAIN=clang',
                        '-DANDROID_STL=c++_static'
                //abiFilters "arm64-v8a"
            }
        }

5. externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }

 
# Description of the issue

Build command failed.
Error while executing process C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\STan\Desktop\pil\main\src\main\cpp -BC:\Users\STan\Desktop\pil\main\.externalNativeBuild\cmake\noovpn3Release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\STan\Desktop\pil\main\build\intermediates\cmake\noovpn3\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
OpenVPN 2.x version HEAD-HASH-NOTFOUND
OpenVPN 3.x version HEAD-HASH-NOTFOUND
-- The ASM compiler identification is Clang
-- Found assembler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
CMake Error at C:/Users/STan/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
-- Configuring incomplete, errors occurred!
See also "C:/Users/STan/Desktop/pil/main/.externalNativeBuild/cmake/noovpn3Release/armeabi-v7a/CMakeFiles/CMakeOutput.log".
Build command failed.
Error while executing process C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\STan\Desktop\pil\main\src\main\cpp -BC:\Users\STan\Desktop\pil\main\.externalNativeBuild\cmake\normalDebug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\STan\Desktop\pil\main\build\intermediates\cmake\normal\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
OpenVPN 2.x version HEAD-HASH-NOTFOUND
OpenVPN 3.x version HEAD-HASH-NOTFOUND
-- The ASM compiler identification is Clang
-- Found assembler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
CMake Error at C:/Users/STan/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
-- Configuring incomplete, errors occurred!
See also "C:/Users/STan/Desktop/pil/main/.externalNativeBuild/cmake/normalDebug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
Build command failed.
Error while executing process C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\STan\Desktop\pil\main\src\main\cpp -BC:\Users\STan\Desktop\pil\main\.externalNativeBuild\cmake\normalRelease\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\STan\Desktop\pil\main\build\intermediates\cmake\normal\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
OpenVPN 2.x version HEAD-HASH-NOTFOUND
OpenVPN 3.x version HEAD-HASH-NOTFOUND
-- The ASM compiler identification is Clang
-- Found assembler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
CMake Error at C:/Users/STan/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
-- Configuring incomplete, errors occurred!
See also "C:/Users/STan/Desktop/pil/main/.externalNativeBuild/cmake/normalRelease/armeabi-v7a/CMakeFiles/CMakeOutput.log".
Build command failed.
Error while executing process C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\STan\Desktop\pil\main\src\main\cpp -BC:\Users\STan\Desktop\pil\main\.externalNativeBuild\cmake\noovpn3Debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\STan\Desktop\pil\main\build\intermediates\cmake\noovpn3\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=C:\Users\STan\AppData\Local\Android\Sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Users\STan\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
-- Check for working C compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe
-- Check for working CXX compiler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
OpenVPN 2.x version HEAD-HASH-NOTFOUND
OpenVPN 3.x version HEAD-HASH-NOTFOUND
-- The ASM compiler identification is Clang
-- Found assembler: C:/Users/STan/AppData/Local/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
CMake Error at C:/Users/STan/AppData/Local/Android/Sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
-- Configuring incomplete, errors occurred!
See also "C:/Users/STan/Desktop/pil/main/.externalNativeBuild/cmake/noovpn3Debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".

**Comment by aries255** [comment]
I have already installed also swig and right it on the environmental variables. but no luck. same issue occur.

**Comment by AbdulRehmanNazar** [comment]
I am also facing same issue on my side.
any news from author or expert from here?

**Comment by schwabe** [comment]
Generally, I build the project under macOS. Building under Windows works for me. But I am closing this ticket since I don't know what exactly makes gradle under Windows find or not find swig. Improvements as pull requests are welome.

**Comment by aries255** [comment]
I have already build it. Im using windows.

**Comment by AbdulRehmanNazar** [comment]
I am also using MAC and I commented these lines in gradle file and it works fine now but I am curious that after commenting these lines effects on project?
externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }

**Comment by schwabe** [comment]
@AbdulRehmanNazar sure it will build but without building openvpn the app will not work all.

**Comment by AbdulRehmanNazar** [comment]
@schwabe  so what is solution to build cMake with path too in gradle?
because when I uncomment these lines then I got error

**Comment by AbdulRehmanNazar** [comment]
This is screenshot when we import your project in Studio.

<img width="1277" alt="screen shot 2018-09-04 at 8 39 56 pm" src="https://user-images.githubusercontent.com/6792823/45041835-b85ade00-b082-11e8-9fc5-abc02b47f3b9.png">

**Comment by schwabe** [comment]
@AbdulRehmanNazar there literally a dozend of issues that deal with these build errors. Please search also the closed issues and read the README. I am tried of explaining that over and over again to people that don't contribute and later even build closed source apps that violate the GPL.

**Comment by MohtashamVahid** [comment]
> This is screenshot when we import your project in Studio.
> 
> <img alt="screen shot 2018-09-04 at 8 39 56 pm" width="1277" src="https://user-images.githubusercontent.com/6792823/45041835-b85ade00-b082-11e8-9fc5-abc02b47f3b9.png">

hi
Did you slive it?

**Comment by schwabe** [comment]
The error has to be somewhere else in the log.

**Comment by asn111** [comment]
> > This is screenshot when we import your project in Studio.
> > <img alt="screen shot 2018-09-04 at 8 39 56 pm" width="1277" src="https://user-images.githubusercontent.com/6792823/45041835-b85ade00-b082-11e8-9fc5-abc02b47f3b9.png">
> 
> hi
> Did you slive it?

Did anyone solved this issue?

**Comment by schwabe** [comment]
@asn111 that log does not show an error

**Comment by asn111** [comment]
> @asn111 that log does not show an error

Hi, @schwabe , might this log could be helpful. see the images.

<img width="1440" alt="screenshot 2019-01-20 at 7 08 09 am 4" src="https://user-images.githubusercontent.com/8926549/51443590-d876fb00-1d0c-11e9-8764-e6e937c62739.png">
<img width="1440" alt="screenshot 2019-01-20 at 7 08 09 am 3" src="https://user-images.githubusercontent.com/8926549/51443591-d876fb00-1d0c-11e9-97a2-b1f66fd34ff9.png">
<img width="1440" alt="screenshot 2019-01-20 at 7 08 09 am 2" src="https://user-images.githubusercontent.com/8926549/51443592-d90f9180-1d0c-11e9-8503-e06cb34de8a7.png">
<img width="1440" alt="screenshot 2019-01-20 at 7 08 09 am 1" src="https://user-images.githubusercontent.com/8926549/51443593-d90f9180-1d0c-11e9-9780-5296dfbbf29d.png">
<img width="1440" alt="screenshot 2019-01-20 at 7 08 09 am" src="https://user-images.githubusercontent.com/8926549/51443594-d9a82800-1d0c-11e9-991f-3decb47f09d2.png">

**Comment by schwabe** [comment]
Please read the readme and also other issues. (hint submodules)

**Comment by imuhammadmehran** [comment]
Hi, @schwabe i am also facing same issue which other fellows shown above in screenshots. i have read readme file i also understand the licenses of the code.For closed sourced custom UI application and (paid) license for UI code i need your support ..

**Comment by schwabe** [comment]
@imuhammadmehran Yeah, then you basically know what to do. If I should support you on your commercial product that is not for free.

**Comment by imuhammadmehran** [comment]
@schwabe how much you will be charged to solve issue or for proper support for commercial production.?

**Comment by imuhammadmehran** [comment]
@schwabe What is the fee of this product for commercial use ?
