### ISSUE TITLE
ca fails with 'ca.crt':No such file or directory(errno=2)

### ISSUE THREAD

**Issue by gonewind73** [schwabe/ics-openvpn#934]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version. 8.0.0

2. Android Vendor/Custom ROM:  HuaWei  EMUI 8.0.0.0
3. Device. MHA-AL00
4. Version of the app (version number/play store version/self-built). OpenVPN 0.7.5
 
# Description of the issue
ca fails with 'ca.crt':No such file or directory(errno=2)
I have put the ca.crt on /Downloads, where should I put the file?

**Comment by schwabe** [comment]
The app allows you to import files even after and during import. Also you can embed the certificate files as inline files into the file.
