### ISSUE TITLE
Multiple options ignored on configuration import

### ISSUE THREAD

**Issue by vgaetera** [schwabe/ics-openvpn#935]
# General information
1. Android 6.0
1. Android Vendor ROM
1. Lenovo Vibe B A2016a40
1. OpenVPN for Android 0.7.5

# Description of the issue
Missing options on configuration import:
1. `auth-nocache`
1. `preresolve`
1. `resolve-retry 60`
1. `ifconfig-nowarn`

Original issue leading to this situation: https://github.com/schwabe/ics-openvpn/issues/778
I suspect we should review it.

## 1. preresolve
It works just fine when added manually in the Custom Options.
And it's absolutely vital when remote VPN-server provides dual stack connectivity and local ISP or WAP supports only IPv4.
Otherwise connectivity is lost completely and VPN-client freezes until you kill it from android app-settings.

## 2. auth-nocache
When added manually in the Custom Options it helps to get rid of the warning message:
> 2018-09-09 19:49:08 WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this

## 3. resolve-retry 60
`resolv-retry 60` - is mentioned in the original issue.
`resolve-retry 60` - is added to ignore options list and looks like typo.
Anyway I see no point why any of these should be ignored.

## 4. ifconfig-nowarn
Ignoring this one is also questionable.
It's not explicitly stated that it leads to connection failure or some other problem.

**Comment by vgaetera** [comment]
Also there're duplicated lines:
https://github.com/schwabe/ics-openvpn/blob/5b3dc16f936f5817d890399bb3150dc1d4a694a5/main/src/main/java/de/blinkt/openvpn/core/ConfigParser.java#L43-L45

**Comment by schwabe** [comment]
> Otherwise connectivity is lost completely and VPN-client freezes until you kill it from android app-settings.

This should not happens at all. Also the setup you are describe is quite common. There is probably something else in your setup that is different.

> auth-nocache
Yes that gets rid of the message but breaks reconnects for connections with a password.

> ifconfig-nowarn
Default configs generated by openvpn for android include this and trust that routing on Android is significantly different on Android that all the warning that are otherwise produced are bogus.


> resolv-retry 60
Also in the generated config.

Many of the ignores are so you can import a config generated by this app and do not end up with a pleothora of custom settings.

**Comment by vgaetera** [comment]
>Many of the ignores are so you can import a config generated by this app and do not end up with a pleothora of custom settings.

Removing Windows-specific and script-related options is perfectly justified by Android platform limitations.
However removing working options is another case entirely.
VPN-server administrator provides the clients with tested ovpn-profile and relies on it to guarantee the quality of service and ease of configuration.
Returning important option back manually is a lot more troublesome than removing some unimportant.

## 1. preresolve
>This should not happens at all. Also the setup you are describe is quite common. There is probably something else in your setup that is different.

DNS-server has IPv6-address and it is pushed as `dhcp-option` to the client and it works, at the same time WiFi-networks often have IPv4-connectivity only.
When I go out of WiFi-range or just reboot my own AP, connection freezes on attempt to resolve the VPN-server name and application also freezes losing ability to reconnect/disconnect.
This happens every time WiFi-signal is lost, and I have the same issue on 2 mobile phones.
With `preresolve` option everything works fine, VPN-reconnects automatically just as WiFi-signal is restored.

## 2. auth-nocache
>Yes that gets rid of the message but breaks reconnects for connections with a password.

OK, just think that removing `auth-nocache` only in case `auth-user-pass` is present would be a better solution.

## 3. ifconfig-nowarn
>Default configs generated by openvpn for android include this and trust that routing on Android is significantly different on Android that all the warning that are otherwise produced are bogus.

OK, I understand, considering it as platform-specific.

## 4. resolve-retry
>Also in the generated config.

Original issue https://github.com/schwabe/ics-openvpn/issues/778 mentions `resolv-retry`, but the application ignores `resolv_e_-retry`, that's obvious typo.
However that's not the point.
It is not a Windows-specific or script-related option but a working option which could be explicitly provided by VPN-server administrator.
Removing working options does not look right.

***
Also there's duplicated line for `route-up`, see https://github.com/schwabe/ics-openvpn/pull/936.

Thank you.

**Comment by vgaetera** [comment]
## auth-nocache
>removing `auth-nocache` only in case `auth-user-pass` is present would be a better solution

Something like this:
```
 if (options.containsKey("auth-user-pass")) { 
     options.remove("auth-nocache"); 
 } 
```
Referring to similar code:
https://github.com/schwabe/ics-openvpn/blob/20e878d3bfe1b4cf2ab1cf790de697e6157b7b7d/main/src/main/java/de/blinkt/openvpn/core/ConfigParser.java#L347-L351

**Comment by schwabe** [comment]
And why should I leave an option int the config that is only used for auth-user-pass config anyway if auth-user-pass is present?

I am not 100% sure if that option is also for certificate keys but also with certificate keys I need openvpn to cache the password.

**Comment by vgaetera** [comment]
To not confuse the users with `WARNING`-messages in the log, at least those who don't use `auth-user-pass`.
When user cares about security and privacy he will definitely start to worry when sees such things, especially because it happens every time the client connects to the server.
Being used to repeated warning messages leads to ignoring them, and in the end when the real trouble arises it could be just overlooked.

**Comment by schwabe** [comment]
@vgaetera sure, but that message is only printed when user-pass is used. And if I remove in that case reconnect stops working. So there nothing to be gained here.

**Comment by vgaetera** [comment]
>that message is only printed when user-pass is used

@schwabe alas, it is not limited to option `auth-user-pass` presence.
I can show config and log if required.

**Comment by schwabe** [comment]
The code only call ins into the function when a password of any kind is used.
