### ISSUE TITLE
IPv6 WebRTC leak

### ISSUE THREAD

**Issue by chen-ky** [schwabe/ics-openvpn#937]
# General information
1. Android Version: 8.1.0
2. Custom ROM: Resurrection Remix OS (RR-O-v6.0.0-20180425-cancro-Official)
3. Device: Xiaomi Mi 3
4. Version of the app: Fdroid (0.7.5)
 
# Description of the issue
After connecting to a VPN server, I check for WebRTC leaks using https://ip.voidsec.com. The IPv6 address shown is the public ipv6 ip from my isp, not the vpn provider. This issue will not occur if I use the official closed-source OpenVPN app from playstore.
![Picture](https://user-images.githubusercontent.com/30970698/45315623-7260b700-b567-11e8-9238-8ae0afe6cb2a.png)

**Comment by schwabe** [comment]
you probably have allow local networks enabled. Also please include a log.

**Comment by chen-ky** [comment]
Disabling "Bypass VPN for local networks" did the trick, thanks. LMK if you still need any logs.

My suggestion:
- The default config should disable this option so that user with ipv6 will not accidentally leak their ipv6 ip. 
- Also, changes will only apply after a reconnect so maybe the app should prompt the user to reconnect to apply any changes if they are connected to a vpn network.

**Comment by zaidalikhan9** [comment]
This information is sound good for me.

**Comment by zaidalikhan9** [comment]
You are supposed to restrict WebRTC at the browser level for the sake of stopping STUN leaks. Explore much more about IPV6 leaks go for [https://anonymania.com/webrtc-leak/](https://anonymania.com/webrtc-leak/) now. This can be done by editing your browser’s config files, or you can do it by installing a browser extension that does the work for you. Apart from that, if you need to resolve IPV6 leaks then the best way is to simply disable IPv6 on your OS.
