### ISSUE TITLE
Native Build Issues

### ISSUE THREAD

**Issue by leofurqan** [schwabe/ics-openvpn#938]
I am trying to build your project but I am having native build issues. I don't know what is the root cause of the problem as their is no issue of like this before

This is the error I am getting in android studio

Build command failed. |  
Error while executing process F:\Software\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\Epic Studios\Desktop\ics-openvpn-master\main\src\main\cpp -BC:\Users\Epic Studios\Desktop\ics-openvpn-master\main\.externalNativeBuild\cmake\noovpn3Release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Epic Studios\Desktop\ics-openvpn-master\main\build\intermediates\cmake\noovpn3\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=F:\Software\Android\sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=F:\Software\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=F:\Software\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static} |  
-- Check for working C compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe |  
-- Check for working C compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works |  
-- Detecting C compiler ABI info |  
-- Detecting C compiler ABI info - done |  
-- Detecting C compile features |  
-- Detecting C compile features - done |  
-- Check for working CXX compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe |  
-- Check for working CXX compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works |  
-- Detecting CXX compiler ABI info |  
-- Detecting CXX compiler ABI info - done |  
-- Detecting CXX compile features |  
-- Detecting CXX compile features - done |  
OpenVPN 2.x version HEAD-HASH-NOTFOUND |  
OpenVPN 3.x version HEAD-HASH-NOTFOUND |  
-- The ASM compiler identification is Clang |  
-- Found assembler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe |  
CMake Error at F:/Software/Android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message): |  
-- Configuring incomplete, errors occurred! |  
See also "C:/Users/Epic Studios/Desktop/ics-openvpn-master/main/.externalNativeBuild/cmake/noovpn3Release/armeabi-v7a/CMakeFiles/CMakeOutput.log". |  
Build command failed. |  
Error while executing process F:\Software\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\Epic Studios\Desktop\ics-openvpn-master\main\src\main\cpp -BC:\Users\Epic Studios\Desktop\ics-openvpn-master\main\.externalNativeBuild\cmake\normalRelease\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Epic Studios\Desktop\ics-openvpn-master\main\build\intermediates\cmake\normal\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=F:\Software\Android\sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=F:\Software\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=F:\Software\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static} |  
-- Check for working C compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe |  
-- Check for working C compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works |  
-- Detecting C compiler ABI info |  
-- Detecting C compiler ABI info - done |  
-- Detecting C compile features |  
-- Detecting C compile features - done |  
-- Check for working CXX compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe |  
-- Check for working CXX compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works |  
-- Detecting CXX compiler ABI info |  
-- Detecting CXX compiler ABI info - done |  
-- Detecting CXX compile features |  
-- Detecting CXX compile features - done |  
OpenVPN 2.x version HEAD-HASH-NOTFOUND |  
OpenVPN 3.x version HEAD-HASH-NOTFOUND |  
-- The ASM compiler identification is Clang |  
-- Found assembler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe |  
CMake Error at F:/Software/Android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message): |  
-- Configuring incomplete, errors occurred! |  
See also "C:/Users/Epic Studios/Desktop/ics-openvpn-master/main/.externalNativeBuild/cmake/normalRelease/armeabi-v7a/CMakeFiles/CMakeOutput.log". |  
Build command failed. |  
Error while executing process F:\Software\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\Epic Studios\Desktop\ics-openvpn-master\main\src\main\cpp -BC:\Users\Epic Studios\Desktop\ics-openvpn-master\main\.externalNativeBuild\cmake\noovpn3Debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Epic Studios\Desktop\ics-openvpn-master\main\build\intermediates\cmake\noovpn3\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=F:\Software\Android\sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=F:\Software\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=F:\Software\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static} |  
-- Check for working C compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe |  
-- Check for working C compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works |  
-- Detecting C compiler ABI info |  
-- Detecting C compiler ABI info - done |  
-- Detecting C compile features |  
-- Detecting C compile features - done |  
-- Check for working CXX compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe |  
-- Check for working CXX compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works |  
-- Detecting CXX compiler ABI info |  
-- Detecting CXX compiler ABI info - done |  
-- Detecting CXX compile features |  
-- Detecting CXX compile features - done |  
OpenVPN 2.x version HEAD-HASH-NOTFOUND |  
OpenVPN 3.x version HEAD-HASH-NOTFOUND |  
-- The ASM compiler identification is Clang |  
-- Found assembler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe |  
CMake Error at F:/Software/Android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message): |  
-- Configuring incomplete, errors occurred! |  
See also "C:/Users/Epic Studios/Desktop/ics-openvpn-master/main/.externalNativeBuild/cmake/noovpn3Debug/armeabi-v7a/CMakeFiles/CMakeOutput.log". |  
Build command failed. |  
Error while executing process F:\Software\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Users\Epic Studios\Desktop\ics-openvpn-master\main\src\main\cpp -BC:\Users\Epic Studios\Desktop\ics-openvpn-master\main\.externalNativeBuild\cmake\normalDebug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-14 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Users\Epic Studios\Desktop\ics-openvpn-master\main\build\intermediates\cmake\normal\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=F:\Software\Android\sdk\ndk-bundle -DCMAKE_TOOLCHAIN_FILE=F:\Software\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=F:\Software\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static} |  
-- Check for working C compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe |  
-- Check for working C compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- works |  
-- Detecting C compiler ABI info |  
-- Detecting C compiler ABI info - done |  
-- Detecting C compile features |  
-- Detecting C compile features - done |  
-- Check for working CXX compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe |  
-- Check for working CXX compiler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++.exe -- works |  
-- Detecting CXX compiler ABI info |  
-- Detecting CXX compiler ABI info - done |  
-- Detecting CXX compile features |  
-- Detecting CXX compile features - done |  
OpenVPN 2.x version HEAD-HASH-NOTFOUND |  
OpenVPN 3.x version HEAD-HASH-NOTFOUND |  
-- The ASM compiler identification is Clang |  
-- Found assembler: F:/Software/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe |  
CMake Error at F:/Software/Android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message): |  
-- Configuring incomplete, errors occurred! |

**Comment by schwabe** [comment]
CMake Error at F:/Software/Android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message): |  

You have to dig a bit deeper to figure out what is happening there. I have no idea. As I said in other issues, I develop on OS x.

**Comment by leofurqan** [comment]
do u guide me how u debug this code. I will appreciate if u tell me steps of doing this

**Comment by dzboot02** [comment]
I have exactly the same problem. did you solve it?

**Comment by strider29** [comment]
@hiddeneyes02 did you install swig?

**Comment by dzboot02** [comment]
Yes, I did and it solved the problem. Sorry for not reporting back.

**Comment by leofurqan** [comment]
I will try after installing swig
