### ISSUE TITLE
Lint check

### ISSUE THREAD

**Issue by aarnoud** [schwabe/ics-openvpn#939]
# General information
1. N/A
2. N/A
3. N/A
4. Master
 
Master is failing on lint check, it's possible it's missing a repository in current version.

> :tlsexternalcertprovider:lint FAILED
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':tlsexternalcertprovider:lint'.
> > Could not resolve all files for configuration ':tlsexternalcertprovider:lintClassPath'.
>    > Could not find com.android.tools.lint:lint-gradle:26.1.3.
>      Searched in the following locations:
>          https://jcenter.bintray.com/com/android/tools/lint/lint-gradle/26.1.3/lint-gradle-26.1.3.pom
>          https://jcenter.bintray.com/com/android/tools/lint/lint-gradle/26.1.3/lint-gradle-26.1.3.jar
>      Required by:
>          project :tlsexternalcertprovider
>

**Comment by schwabe** [comment]
That sounds more like a local problem that you are missing the android repository. com.android.tools.lint:lint-gradle:26.1.3 is probably coming from the google repository

Are you building with AS or command line gradlew

**Comment by aarnoud** [comment]
it's started from Jenkins like this on main project without any local modifications : 

`/var/lib/jenkins/tools/hudson.plugins.gradle.GradleInstallation/4.10.1/bin/gradle build`

Last successful automatic build was in August, and started to fail beginning of September

**Comment by schwabe** [comment]
This should be fixed now again. Travis does not reports build errors anymore.

**Comment by aarnoud** [comment]
all good now, thanks and good job!
