### ISSUE TITLE
DNS does not resolve through tunnel

### ISSUE THREAD

**Issue by Kline-** [schwabe/ics-openvpn#940]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. 7.1.1 / N8I11F
2. Google/Stock
3. Nexus 6
4. 0.7.5
 
# Description of the issue

I am able to connect to my VPN server and access anything within my LAN via IP address. The VPN server also runs a local BIND9 instance and I push the IP as a DNS option yet all DNS queries that should resolve within my LAN fail to resolve. What am I missing here? I thought it was an issue with prop values not updating but saw comments in #377 that said this isn't the case.

Log export attached to avoid spamming the comments.
[ics-openvpn.txt](https://github.com/schwabe/ics-openvpn/files/2387278/ics-openvpn.txt)

**Comment by schwabe** [comment]
How did you determine that the DNS is not used?

**Comment by Kline-** [comment]
I'm so incredibly sorry. It does work and the issue was I forgot to assign the VPN subnet to a view on my BIND9 server. All it took was someone asking the question to make me realize and look past the VPN config better!

For anyone who stumbles on this issue in the future: my testing/lack thereof was attempting to connect to a webserver in my LAN. It would work via IP but fail via hostname. I never once thought to watch my query logs until someone asked exactly how I determined the DNS was at fault!
