### ISSUE TITLE
Import ovpn file

### ISSUE THREAD

**Issue by AndersBillLinden** [schwabe/ics-openvpn#941]
I would like to import a ovpn file together with a ca.cert file, but only specifying the ovpn file should be sufficient, because it directs to the ca.cert file.

Would it be possible to add opvn file format support in the app?

I have those files and have successfully used them in the official openvpn app for windows.
Unfortunately, the official openvpn android app seems to fail to import the files to get a "profile", because it wants a client certificate.

The ovpn file reads like this:

````
client
dev tun2001
script-security 3
proto tcp
remote  1.2.3.4  1194
resolv-retry infinite
nobind
ca ca.crt
auth-user-pass
reneg-sec 0
cipher AES-128-CBC
tls-cipher TLS-SRP-SHA-RSA-WITH-3DES-EDE-CBC-SHA:TLS-DHE-RSA-WITH-AES-128-CBC-SHA:TLS-DHE-RSA-WITH-AES-256-CBC-SHA
````

(the ip number being replaced with a made up one in this report).

The `tls-cipher` line is information that I dont know how to put in the app in some way.

It feels like I have to tick "Use TLS Authentication" to use it, but I do not know which "TLS Auth File" I should specify (because I dont know what a TLS Auth File is).

I tried to just put the text specifying the cipher list in a file that I named foo.tls, with and without the tls-cipher word in the beginning and then selecting that file as a "TLS Auth File", but that failed.

**Comment by schwabe** [comment]
The app tries finding and importing those files along with the ovpn file and should prompt you to import the files if it does not work. However is is error prone and does not always work, especially on more modern devices.

I suggest embedding the files into ovpn file e.g with `<ca>...</ca>.`

**Comment by AndersBillLinden** [comment]
So the `ca ca.crt` line should be replaced with that? Did not seem to work for me.

**Comment by AndersBillLinden** [comment]
Should it be placed in only one line?

**Comment by AndersBillLinden** [comment]
I then got "Failed to parse profile: line too long"

**Comment by AndersBillLinden** [comment]
Oh, the problem is that there is no client certificate. I only have a ca.cert file. That has been enough on my computer, but the app will not honor it.

**Comment by vgaetera** [comment]
@AndersBillLinden copy `ca.cert` file content of inside `profile.ovpn` using inline notation:
https://community.openvpn.net/openvpn/wiki/IOSinline

**Comment by schwabe** [comment]
Or see the man page on inline files

**Comment by AndersBillLinden** [comment]
I did that without any luck.

**Comment by AndersBillLinden** [comment]
I have tried to embed the certificate without any luck.

**Comment by schwabe** [comment]
you can still manually select it.  And for the tls-cipher line, it is better to not include it. OpenVPN's default is pretty good.

What error message are you getting?
