### ISSUE TITLE
is that works with pptp server on centos?

### ISSUE THREAD

**Issue by barron9** [schwabe/ics-openvpn#943]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

**Comment by barron9** [comment]
i can login with user/pass and ip adress through vpn profile.

**Comment by schwabe** [comment]
No OpenVPN only
