### ISSUE TITLE
when i run my code  on 4.4.4 ,there is a error

### ISSUE THREAD

**Issue by czgczg308** [schwabe/ics-openvpn#945]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

1. Android Version  4.4.4 KTU84P
2. Android Vendor/Custom ROM
3. Device MI PAD

when i run my code  on pad of xiaomi, it appear a error .But my apk is run ok on other devces(6.0 of xiaom, 7.0.1)

13:44:45/17332: java.lang.VerifyError: de/blinkt/openvpn/core/OpenVpnManagementThread
        at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:596)
        at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:63)
        at de.blinkt.openvpn.core.OpenVPNService$3.run(OpenVPNService.java:547)
        at java.lang.Thread.run(Thread.java:841)

here is the code 

```java
if (!useOpenVPN3) {
            // start a Thread that handles incoming messages of the managment socket
            OpenVpnManagementThread ovpnManagementThread = new OpenVpnManagementThread(mProfile, this);    // it happend  the error
            if (ovpnManagementThread.openManagementInterface(this)) {
                Thread mSocketManagerThread = new Thread(ovpnManagementThread, "OpenVPNManagementThread");
                mSocketManagerThread.start();
                mManagement = ovpnManagementThread;
                VpnStatus.logInfo("started Socket Thread");
            } else {
                LogUtil.logE("流程17");
                endVpnService();
                return;
            }
        }

```

how can i solve it, can you help me ，thank you

**Comment by schwabe** [comment]
Can you share the complete code? The code seem to be modified from my code (Chinese log message). 

Also note the FAQ in doc/README

**Comment by czgczg308** [comment]
you need  complete  project or this code file complete file ? I just add log on this class ,no change other code 
[OpenVPNService.java.docx](https://github.com/schwabe/ics-openvpn/files/2422753/OpenVPNService.java.docx)

**Comment by czgczg308** [comment]
![image](https://user-images.githubusercontent.com/4937739/46127753-34041100-c264-11e8-93de-ca939d9a900d.png)

**Comment by schwabe** [comment]
You will need to publish the complete source code eventually anyway since the project is GPL (see doc/README).

Have you tried running my unmodified app (e.g. from plai.de/android) on that device?

**Comment by czgczg308** [comment]
I'll try and see if the original code has any problems

**Comment by czgczg308** [comment]
thank you for you help
