### ISSUE TITLE
UDP traffic is not working over OpenVPN TCP tunnel

### ISSUE THREAD

**Issue by noman720** [schwabe/ics-openvpn#946]
Hi @schwabe 
I am a novice in OpenVPN, sorry for the dumb question. I have configured an OpenVPN server (out of my country) on TCP protocol. When I make WhatsApp/Viber/VoIP calls then it doesn't work. I see in Wireshark, UDP packet has been transmitted from my android during calls (ISP has blocked UDP). Is there any way to make calls?

Thanks

**Comment by schwabe** [comment]
Sorry this is a bug tracker and not help forum for OpenVPN.
