### ISSUE TITLE
 Auto-start VPN connection

### ISSUE THREAD

**Issue by pokevas** [schwabe/ics-openvpn#948]
# General information
1. Android Version - Anyone
2. Android Vendor/Custom ROM - Anyone
3. Device - Anyone
4. Version of the app (version number/play store version/self-built) - latest lib version
 
# Description of the issue
Hello. There is a task for the VPN to automatically connect to the VPN server when the device is restarted. Is it possible to do this?

**Comment by schwabe** [comment]
Yes. Always on VPN from android and inside the app on general perferences.
