### ISSUE TITLE
persistent for trust this application Android 5.0+

### ISSUE THREAD

**Issue by pokevas** [schwabe/ics-openvpn#949]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version - 5.0 and later
2. Android Vendor/Custom ROM - anyone
3. Device - anyone
4. Version of the app (version number/play store version/self-built) - anyone
 
# Description of the issue
Google add persistent for trust this application in Android 5.0+ ?
Because after the first start of VPN, I no longer saw this message until the application was reinstalled.

**Comment by schwabe** [comment]
See FAQ.
