### ISSUE TITLE
AES-256-CBC

### ISSUE THREAD

**Issue by mesterj** [schwabe/ics-openvpn#950]
Hello

Now we use 64bit cipher (our VPN server is working very long time ago). The OpenVPN is send a warning about weak cipher now. Do you plan disallow connection with weak cipher in near future? I ask about it because we want to prepare with a new infrastrukture for this change.

**Comment by schwabe** [comment]
check the openvpn wiki for SWEET32: https://community.openvpn.net/openvpn/wiki/SWEET32

My client will follow openvpn but probably faster than other clients since it tracks master

**Comment by mesterj** [comment]
Ok. But please notify before you disable 64 bit connecting.
