### ISSUE TITLE
Enhancement: Adding support to host files:

### ISSUE THREAD

**Issue by projectextremum** [schwabe/ics-openvpn#951]
#### Enhancement request -- adding support to hosts files:

It has been an issue for non root users to use a VPN based ad blocker along with a VPN service based on OpenVPN.

I suppose some mechanism exists already for blocking certain roots, manipulating address, setting up proxy and maybe DNS too and that it isn't just provided an interface to.

It would be nice if it is possible to select one or more host files during VPN profile setup, which I think weren't provided anywhere.

**Comment by schwabe** [comment]
What exactly do you mean with host files, like in /etc/hosts?

**Comment by projectextremum** [comment]
Perhaps the same, I think that is all used by ad blockers such as blockada.

**Comment by schwabe** [comment]
OpenVPN does not fiddle with DNS or any other higher layer services. If you want something like that you need either a local DNS server or your VPN's DNS server has to offer that service.

**Comment by Eyey110** [comment]
> #### Enhancement request -- adding support to hosts files:
> It has been an issue for non root users to use a VPN based ad blocker along with a VPN service based on OpenVPN.
> 
> I suppose some mechanism exists already for blocking certain roots, manipulating address, setting up proxy and maybe DNS too and that it isn't just provided an interface to.
> 
> It would be nice if it is possible to select one or more host files during VPN profile setup, which I think weren't provided anywhere.



Have you solved it?

**Comment by cyberyanka** [comment]
> > #### Enhancement request -- adding support to hosts files:
> > It has been an issue for non root users to use a VPN based ad blocker along with a VPN service based on OpenVPN.
> > I suppose some mechanism exists already for blocking certain roots, manipulating address, setting up proxy and maybe DNS too and that it isn't just provided an interface to.
> > It would be nice if it is possible to select one or more host files during VPN profile setup, which I think weren't provided anywhere.
> 
> Have you solved it?

Yes. There is a solution for that -- another app. You can search "set vpn on no root android" (I dunno if I can reference another app here by name).

The issue for me though is I need an openvpn for work and I need to set up some custom host resolving in hosts.
I was able to set this custom hosts file but the app is working as another VPN-app, so I cannot use this two VPNs simultaneously as I need
