### ISSUE TITLE
"Reconnect on network change" setting being ignored

### ISSUE THREAD

**Issue by jmoore-vjt** [schwabe/ics-openvpn#952]
Android version: 6.0.1
Android vendor: Samsung
Device: Note 4
App version: 0.7.5

Despite having the setting "Reconnect on network change" unchecked the app always reconnects if I toggle WiFi on or off while connected.  I'm trying to use Tasker to control which networks I use OpenVPN on and this behavior is getting in the way.

**Comment by schwabe** [comment]
That controls only the forceful reconnect.
