### ISSUE TITLE
Remove the ability to edit VPN configuration from Log screen

### ISSUE THREAD

**Issue by tomasimartin** [schwabe/ics-openvpn#954]
# General information
1. Android Version
All are impacted 6 to 8
2. Android Vendor/Custom ROM
Android One or Stock ROMs from manufacturers
3. Device
Samsung Xcover 4 / Samsung Galaxy 8 / Nomu S20 / Xiaomi mi A1/A2/A2 Lite / Pixel 2
4. Version of the app (version number/play store version/self-built)
0.7.5.
# Description of the issue
Hello,  

We are starting a temporary connection on OpenVPN for Android thru AIDL.  
We noticed that we can still disclose all informations: profile and certificates from Log scren > Edit VPN configuration > Generated Config.  
  
As we do not import the profile, we do not want to be able to get these informations revealed.  
  
Thank you.

**Comment by schwabe** [comment]
Thanks for noticing. That is a corner case that I have not thought about.
