### ISSUE TITLE
OpenVPN for Android v0.7.5 can't import opvn file on Fire TV 3rd Gen Fire OS 6.2.5.3

### ISSUE THREAD

**Issue by rjm5299** [schwabe/ics-openvpn#955]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue
The issue seems to be centered around the inability of the application to access my devices storage. I get a message that states "DENY" and there is no other paramter that can be modified that would allow OpenVPN to access my internal storage. My device is not rooted and would prefer not to have to do that (assuming that could fix the issue). Only other option is to setup VPN at the Router. My VPN provider advised me that they are planning on introducing their own apk to resolve, but I'm not holding my breath for this to be developed. Please advise if the storage denial will be resolved?
![img-2747](https://user-images.githubusercontent.com/44296582/47224164-d8233880-d388-11e8-8a86-334ec45eb31f.JPG)

**Comment by schwabe** [comment]
That is a "feature" of your OS.  I have no idea why this is broken in Fire TV. You might also try to open the ovpn directly from downloads etc. to open it in my App.
