### ISSUE TITLE
Notification stuck on "Adding routes"

### ISSUE THREAD

**Issue by HrBDev** [schwabe/ics-openvpn#956]
# General information
1. Android Version
9
2. Android Vendor/Custom ROM
Google
3. Device
Nokia 7 Plus(TA-1046)
4. Version of the app (version number/play store version/self-built)
 0.7.6(play store)
# Description of the issue
The notification gets stuck on Adding routes when I switch network, the vpn works fine

**Comment by schwabe** [comment]
Could you post a completelog?
