### ISSUE TITLE
de.blinkt.openvpn.core.NativeUtils

### ISSUE THREAD

**Issue by FarnoodR** [schwabe/ics-openvpn#959]
The Application works well when I installed it from Google Play or directly install the APK where I got from http://plai.de/android/

I am in trouble when I get the latest source code from Git and I build it through Android Studio. 
I used the same OpenVPN Config file (VPN.conf or VPN.pem or VPN.ovpn) for those three versions (Google Play - APK and Android Studio Build Version)

I already installed the SDK, NDK, CMAKE (e.g. with Android studio), and swig (3.0+):
**ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)" < /dev/null 2> /dev/null
brew install swig**

git clone https://github.com/schwabe/ics-openvpn.git
cd ics-openvpn/
git pull https://github.com/schwabe/ics-openvpn.git
git submodule init
git submodule update

I am getting the following Error when I try to load the config file:

    java.lang.UnsatisfiedLinkError: de.blinkt.openvpn.core.NativeUtils
        at de.blinkt.openvpn.VpnProfile.getPlatformVersionEnvString(VpnProfile.java:658)
        at de.blinkt.openvpn.VpnProfile.getConfigFile(VpnProfile.java:339)
        at de.blinkt.openvpn.VpnProfile.writeConfigFile(VpnProfile.java:748)
        at de.blinkt.openvpn.core.OpenVPNService.startOpenVPN(OpenVPNService.java:565)
        at de.blinkt.openvpn.core.OpenVPNService.access$200(OpenVPNService.java:63)
        at de.blinkt.openvpn.core.OpenVPNService$3.run(OpenVPNService.java:544)

**Comment by FarnoodR** [comment]
![screen shot 2018-10-25 at 6 18 14 pm](https://user-images.githubusercontent.com/33512008/47539368-e55a8e80-d884-11e8-96b5-508d08638023.png)

**Comment by schwabe** [comment]
No idea. The project runs just fine here on OS X. Try building from command line with ./gradlew build and see if that works.

**Comment by FarnoodR** [comment]
Hello Schwabe, Thanks for the reply.
I just clone the source code from git and open it through Android Studio.
I only changed the CMake path to the correct one:
Still fetal with ./gradlew build 
Same error over three computers. Mac OS Mojave, Ubuntu, and Windows.

externalNativeBuilexternalNativeBuild {
    cmake {
        path "/Users/XXXX/Desktop/OpenVPN/ics-openvpn/main/src/main/cpp/lzo/CMakeLists.txt"
    }
}

**Comment by FarnoodR** [comment]
The biggest difference is that your APK size is about 16.5 Mb where I got from
http://plai.de/android/
but mine is about 2MB after the build.

**Comment by FarnoodR** [comment]
![screen shot 2018-10-26 at 4 40 57 pm](https://user-images.githubusercontent.com/33512008/47596835-1ba81480-d93e-11e8-8a1e-97c917dd0320.png)

**Comment by schwabe** [comment]
> externalNativeBuilexternalNativeBuild {
> cmake {
> path "/Users/XXXX/Desktop/OpenVPN/ics-openvpn/main/src/main/cpp/lzo/CMakeLists.txt"
> }
> }

Yeah, if you change things like that don't build the native stuff anymore, the native stuff is broken. Pretty obvious. (Only having lzo instead openvpn) kind of defeats the purpose.

But it really builds fine (see also Travis) and there have a lot of  "bugs" been reported for this, please see those for help. So I am closing this as duplicate.

And next time when you report a bug, don't tinker around changing random thing and then cry for help when it is broken

**Comment by FarnoodR** [comment]
Hello Schwabe

Thanks for the comment and complimentary.
The problem is solved by updating the Swig on the new Mac OS Mojave.
Mac OS Mojave needs to get update the Swig.

Thanks.

**brew install swig**

==> Downloading https://homebrew.bintray.com/bottles/swig-3.0.12.mojave.bottle.tar.gz
######################################################################## 100.0%
==> Pouring swig-3.0.12.mojave.bottle.tar.gz
