### ISSUE TITLE
VPN connects only when I switch network while its trying to connect

### ISSUE THREAD

**Issue by strider29** [schwabe/ics-openvpn#960]
Hi Arne,

So the vpn almost never connects when I try to connect it. But as soon as I switch the network(wifi to mobile data or vice versa) while its trying to connect, it works! I have touched the code at some places, and I am not sure where to exactly look for whats wrong.

Here is the log when i try to connect:

D/OpenVPN: started Socket Thread
I/OpenVPN: Starting openvpn
D/OpenVPN: Debug state info: CONNECTED  to WIFI "cliqz", pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
D/OpenVPN: Debug state info: CONNECTED  to WIFI "cliqz", pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
D/OpenVPN: WARNING:  Compression enabled, Compression has been used in the past to break encryption. Enabling decompression of received packet only. Sent packets are not compressed.
D/OpenVPN: Current Parameter Settings:
D/OpenVPN:   config = '/data/user/0/com.cliqz.browser.bond/cache/android.conf'
D/OpenVPN:   mode = 0
D/OpenVPN:   show_ciphers = DISABLED
D/OpenVPN:   show_digests = DISABLED
D/OpenVPN:   show_engines = DISABLED
D/OpenVPN:   genkey = DISABLED
D/OpenVPN:   key_pass_file = '[UNDEF]'
D/OpenVPN:   show_tls_ciphers = DISABLED
D/OpenVPN:   connect_retry_max = 0
D/OpenVPN: Connection profiles [0]:
D/OpenVPN:   proto = tcp-client
D/OpenVPN:   local = '[UNDEF]'
D/OpenVPN:   local_port = '[UNDEF]'
D/OpenVPN:   remote = '195.181.168.14'
D/OpenVPN:   remote_port = '443'
D/OpenVPN:   remote_float = DISABLED
D/OpenVPN:   bind_defined = DISABLED
D/OpenVPN:   bind_local = DISABLED
D/OpenVPN:   bind_ipv6_only = DISABLED
D/OpenVPN:   connect_retry_seconds = 2
D/OpenVPN:   connect_timeout = 120
D/OpenVPN:   socks_proxy_server = '[UNDEF]'
D/OpenVPN:   socks_proxy_port = '[UNDEF]'
D/OpenVPN:   tun_mtu = 1500
D/OpenVPN:   tun_mtu_defined = ENABLED
D/OpenVPN:   link_mtu = 1500
D/OpenVPN:   link_mtu_defined = DISABLED
D/OpenVPN:   tun_mtu_extra = 0
D/OpenVPN:   tun_mtu_extra_defined = DISABLED
D/OpenVPN:   fragment = 0
D/OpenVPN:   mssfix = 1450
D/OpenVPN:   explicit_exit_notification = 0
D/OpenVPN:   tls_auth_file = '[UNDEF]'
D/OpenVPN:   key_direction = not set
D/OpenVPN:   tls_crypt_file = '[UNDEF]'
D/OpenVPN: Connection profiles END
D/OpenVPN:   remote_random = DISABLED
D/OpenVPN:   ipchange = '[UNDEF]'
D/OpenVPN:   dev = 'tun'
D/OpenVPN:   dev_type = '[UNDEF]'
D/OpenVPN:   dev_node = '[UNDEF]'
D/OpenVPN:   lladdr = '[UNDEF]'
D/OpenVPN:   topology = 1
D/OpenVPN:   ifconfig_local = '[UNDEF]'
D/OpenVPN:   ifconfig_remote_netmask = '[UNDEF]'
D/OpenVPN:   ifconfig_noexec = DISABLED
D/OpenVPN:   ifconfig_nowarn = ENABLED
D/OpenVPN:   ifconfig_ipv6_local = '[UNDEF]'
D/OpenVPN:   ifconfig_ipv6_netbits = 0
D/OpenVPN:   ifconfig_ipv6_remote = '[UNDEF]'
D/OpenVPN:   shaper = 0
D/OpenVPN:   mtu_test = 0
D/OpenVPN:   mlock = DISABLED
D/OpenVPN:   keepalive_ping = 0
D/OpenVPN:   keepalive_timeout = 0
D/OpenVPN:   inactivity_timeout = 0
D/OpenVPN:   ping_send_timeout = 0
D/OpenVPN:   ping_rec_timeout = 0
D/OpenVPN:   ping_rec_timeout_action = 0
D/OpenVPN:   ping_timer_remote = DISABLED
D/OpenVPN:   remap_sigusr1 = 0
D/OpenVPN:   persist_tun = ENABLED
D/OpenVPN:   persist_local_ip = DISABLED
D/OpenVPN:   persist_remote_ip = DISABLED
D/OpenVPN:   persist_key = DISABLED
D/OpenVPN:   passtos = DISABLED
D/OpenVPN:   resolve_retry_seconds = 1000000000
D/OpenVPN:   resolve_in_advance = ENABLED
D/OpenVPN:   username = '[UNDEF]'
D/OpenVPN:   groupname = '[UNDEF]'
D/OpenVPN:   chroot_dir = '[UNDEF]'
D/OpenVPN:   cd_dir = '[UNDEF]'
D/OpenVPN:   writepid = '[UNDEF]'
D/OpenVPN:   up_script = '[UNDEF]'
D/OpenVPN:   down_script = '[UNDEF]'
D/OpenVPN:   down_pre = DISABLED
D/OpenVPN:   up_restart = DISABLED
D/OpenVPN:   up_delay = DISABLED
D/OpenVPN:   daemon = DISABLED
D/OpenVPN:   inetd = 0
D/OpenVPN:   log = DISABLED
D/OpenVPN:   suppress_timestamps = DISABLED
D/OpenVPN:   machine_readable_output = ENABLED
D/OpenVPN:   nice = 0
D/OpenVPN:   verbosity = 4
D/OpenVPN:   mute = 0
D/OpenVPN:   gremlin = 0
D/OpenVPN:   status_file = '[UNDEF]'
D/OpenVPN:   status_file_version = 1
D/OpenVPN:   status_file_update_freq = 60
D/OpenVPN:   occ = ENABLED
D/OpenVPN:   rcvbuf = 0
D/OpenVPN:   sndbuf = 0
D/OpenVPN:   sockflags = 0
D/OpenVPN:   fast_io = DISABLED
D/OpenVPN:   comp.alg = 2
D/OpenVPN:   comp.flags = 1
D/OpenVPN:   route_script = '[UNDEF]'
D/OpenVPN:   route_default_gateway = '[UNDEF]'
D/OpenVPN:   route_default_metric = 0
D/OpenVPN:   route_noexec = DISABLED
D/OpenVPN:   route_delay = 0
D/OpenVPN:   route_delay_window = 30
D/OpenVPN:   route_delay_defined = DISABLED
D/OpenVPN:   route_nopull = DISABLED
D/OpenVPN:   route_gateway_via_dhcp = DISABLED
D/OpenVPN:   allow_pull_fqdn = DISABLED
D/OpenVPN:   management_addr = '/data/user/0/com.cliqz.browser.bond/cache/mgmtsocket'
D/OpenVPN:   management_port = 'unix'
D/OpenVPN:   management_user_pass = '[UNDEF]'
D/OpenVPN:   management_log_history_cache = 250
D/OpenVPN:   management_echo_buffer_size = 100
D/OpenVPN:   management_write_peer_info_file = '[UNDEF]'
D/OpenVPN:   management_client_user = '[UNDEF]'
D/OpenVPN:   management_client_group = '[UNDEF]'
D/OpenVPN:   management_flags = 4390
D/OpenVPN:   shared_secret_file = '[UNDEF]'
D/OpenVPN:   key_direction = not set
D/OpenVPN:   ciphername = 'BF-CBC'
D/OpenVPN:   ncp_enabled = ENABLED
D/OpenVPN:   ncp_ciphers = 'AES-256-GCM:AES-128-GCM'
D/OpenVPN:   authname = 'SHA1'
D/OpenVPN:   prng_hash = 'SHA1'
D/OpenVPN:   prng_nonce_secret_len = 16
D/OpenVPN:   keysize = 0
D/OpenVPN:   engine = DISABLED
D/OpenVPN:   replay = ENABLED
D/OpenVPN:   mute_replay_warnings = DISABLED
D/OpenVPN:   replay_window = 64
D/OpenVPN:   replay_time = 15
D/OpenVPN:   packet_id_file = '[UNDEF]'
D/OpenVPN:   test_crypto = DISABLED
D/OpenVPN:   tls_server = DISABLED
D/OpenVPN:   tls_client = ENABLED
D/OpenVPN:   key_method = 2
D/OpenVPN:   ca_file = '[[INLINE]]'
D/OpenVPN:   ca_path = '[UNDEF]'
D/OpenVPN:   dh_file = '[UNDEF]'
D/OpenVPN:   cert_file = '[UNDEF]'
D/OpenVPN:   extra_certs_file = '[UNDEF]'
D/OpenVPN:   priv_key_file = '[UNDEF]'
D/OpenVPN:   pkcs12_file = '[UNDEF]'
D/OpenVPN:   cipher_list = '[UNDEF]'
D/OpenVPN:   tls_cert_profile = '[UNDEF]'
D/OpenVPN:   tls_verify = '[UNDEF]'
D/OpenVPN:   tls_export_cert = '[UNDEF]'
D/OpenVPN:   verify_x509_type = 0
D/OpenVPN:   verify_x509_name = '[UNDEF]'
D/OpenVPN:   crl_file = '[UNDEF]'
D/OpenVPN:   ns_cert_type = 0
D/OpenVPN:   remote_cert_ku[i] = 0
I/chatty: uid=10482(u0_a482) OpenVPNProcessT identical 14 lines
D/OpenVPN:   remote_cert_ku[i] = 0
D/OpenVPN:   remote_cert_eku = '[UNDEF]'
D/OpenVPN:   ssl_flags = 0
D/OpenVPN:   tls_timeout = 2
D/OpenVPN:   renegotiate_bytes = -1
D/OpenVPN:   renegotiate_packets = 0
D/OpenVPN:   renegotiate_seconds = 3600
D/OpenVPN:   handshake_window = 60
D/OpenVPN:   transition_window = 3600
D/OpenVPN:   single_session = DISABLED
D/OpenVPN:   push_peer_info = DISABLED
D/OpenVPN:   tls_exit = DISABLED
D/OpenVPN:   client = ENABLED
D/OpenVPN:   pull = ENABLED
D/OpenVPN:   auth_user_pass_file = 'stdin'
D/OpenVPN: OpenVPN 2.5-icsopenvpn [git:001b2e0] armeabi-v7a [SSL (OpenSSL)] [LZO] [LZ4] [EPOLL] [MH/PKTINFO] [AEAD] built on Oct 29 2018
D/OpenVPN: library versions: OpenSSL 1.1.1  11 Sep 2018, LZO 2.10
D/OpenVPN: MANAGEMENT: Connected to management server at /data/user/0/com.cliqz.browser.bond/cache/mgmtsocket
D/OpenVPN: MANAGEMENT: CMD 'version 2'

And after I switch the network, I get further log:

D/OpenVPN: Debug state info: not connected, pause: userPause, shouldbeconnected: false, network: PENDINGDISCONNECT 
D/OpenVPN: MANAGEMENT: CMD 'hold release'
D/OpenVPN: MANAGEMENT: CMD 'bytecount 2'
D/OpenVPN: Debug state info: CONNECTED LTE to MOBILE internet, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED 
D/OpenVPN: MANAGEMENT: CMD 'username 'Auth' cliqz'
D/OpenVPN: MANAGEMENT: CMD 'state on'
D/OpenVPN: MANAGEMENT: CMD 'password [...]'
D/OpenVPN: MANAGEMENT: CMD 'proxy NONE'
D/OpenVPN: WARNING: No server certificate verification method has been enabled.  See http://openvpn.net/howto.html#mitm for more info.
D/OpenVPN: LZO compression initializing
D/OpenVPN: Control Channel MTU parms [ L:1624 D:1210 EF:40 EB:0 ET:0 EL:3 ]
D/OpenVPN: Data Channel MTU parms [ L:1624 D:1450 EF:124 EB:406 ET:0 EL:3 ]
D/OpenVPN: Local Options String (VER=V4): 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_CLIENT,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-client'
D/OpenVPN: Expected Remote Options String (VER=V4): 'V4,dev-type tun,link-mtu 1544,tun-mtu 1500,proto TCPv4_SERVER,comp-lzo,cipher BF-CBC,auth SHA1,keysize 128,key-method 2,tls-server'
D/OpenVPN: TCP/UDP: Preserving recently used remote address: [AF_INET]195.181.168.14:443
D/OpenVPN: Socket Buffers: R=[4194304->4194304] S=[524288->524288]
D/OpenVPN: Attempting to establish TCP connection with [AF_INET]195.181.168.14:443 [nonblock]
D/OpenVPN: MANAGEMENT: >STATE:1540892432,TCP_CONNECT,,,,,,
D/OpenVPN: MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
D/OpenVPN: TCP connection established with [AF_INET]195.181.168.14:443
D/OpenVPN: MANAGEMENT: CMD 'needok 'PROTECTFD' ok'
D/OpenVPN: TCP_CLIENT link local: (not bound)
D/OpenVPN: TCP_CLIENT link remote: [AF_INET]195.181.168.14:443
D/OpenVPN: MANAGEMENT: >STATE:1540892433,WAIT,,,,,,
D/OpenVPN: MANAGEMENT: >STATE:1540892434,AUTH,,,,,,
D/OpenVPN: TLS: Initial packet from [AF_INET]195.181.168.14:443, sid=ef8c8eac 17efd9ca
D/OpenVPN: WARNING: this configuration may cache passwords in memory -- use the auth-nocache option to prevent this
D/OpenVPN: VERIFY OK: depth=1, C=US, ST=MA, L=Bedford, O=FoxyProxy, Inc., OU=openvpn, CN=localhost, name=FoxyProxy, emailAddress=ssladmin@getfoxyproxy.org
D/OpenVPN: VERIFY OK: depth=0, C=US, ST=MA, L=Bedford, O=FoxyProxy, Inc., OU=openvpn, CN=localhost, name=FoxyProxy, emailAddress=ssladmin@getfoxyproxy.org
D/OpenVPN: Control Channel: TLSv1.2, cipher TLSv1.2 ECDHE-RSA-AES256-GCM-SHA384, 2048 bit RSA
D/OpenVPN: [localhost] Peer Connection Initiated with [AF_INET]195.181.168.14:443
D/OpenVPN: MANAGEMENT: >STATE:1540892435,GET_CONFIG,,,,,,
D/OpenVPN: SENT CONTROL [localhost]: 'PUSH_REQUEST' (status=1)
D/OpenVPN: PUSH: Received control message: 'PUSH_REPLY,redirect-gateway def1,dhcp-option DNS 4.2.2.1,dhcp-option DNS 4.2.2.2,route 10.8.0.1,topology net30,ping 10,ping-restart 120,ifconfig 10.8.0.6 10.8.0.5,peer-id 0,cipher AES-256-GCM'
D/OpenVPN: OPTIONS IMPORT: timers and/or timeouts modified
D/OpenVPN: OPTIONS IMPORT: --ifconfig/up options modified
D/OpenVPN: OPTIONS IMPORT: route options modified
D/OpenVPN: OPTIONS IMPORT: --ip-win32 and/or --dhcp-option options modified
D/OpenVPN: OPTIONS IMPORT: peer-id set
D/OpenVPN: OPTIONS IMPORT: adjusting link_mtu to 1627
D/OpenVPN: OPTIONS IMPORT: data channel crypto options modified
D/OpenVPN: Data Channel: using negotiated cipher 'AES-256-GCM'
D/OpenVPN: Data Channel MTU parms [ L:1555 D:1450 EF:55 EB:406 ET:0 EL:3 ]
D/OpenVPN: Outgoing Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
D/OpenVPN: Incoming Data Channel: Cipher 'AES-256-GCM' initialized with 256 bit key
D/OpenVPN: GDG: SIOCGIFHWADDR(lo) failed
D/OpenVPN: ROUTE_GATEWAY 127.100.103.119/255.0.0.0 IFACE=lo
D/OpenVPN: do_ifconfig, ipv4=1, ipv6=0
D/OpenVPN: MANAGEMENT: >STATE:1540892436,ASSIGN_IP,,10.8.0.6,,,,
D/OpenVPN: MANAGEMENT: CMD 'needok 'IFCONFIG' ok'
D/OpenVPN: MANAGEMENT: CMD 'needok 'ROUTE' ok'
D/OpenVPN: MANAGEMENT: >STATE:1540892436,ADD_ROUTES,,,,,,
D/OpenVPN: MANAGEMENT: CMD 'needok 'ROUTE' ok'
D/OpenVPN: MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
D/OpenVPN: MANAGEMENT: CMD 'needok 'DNSSERVER' ok'
D/OpenVPN: Log (no context) resid 2131690110
D/OpenVPN: MANAGEMENT: CMD 'needok 'PERSIST_TUN_ACTION' OPEN_BEFORE_CLOSE'
D/OpenVPN: Log (no context) resid 213169013510.8.0.6|30|null|1500
D/OpenVPN: Log (no context) resid 21316898384.2.2.1, 4.2.2.2|null
D/OpenVPN: Log (no context) resid 21316905750.0.0.0/0, 10.8.0.1/32, 10.8.0.4/30|
D/OpenVPN: Log (no context) resid 2131690574|
D/OpenVPN: Log (no context) resid 21316905730.0.0.0/0|
D/OpenVPN: Log (no context) resid 2131689832
D/OpenVPN: MANAGEMENT: CMD 'needok 'OPENTUN' ok'
D/OpenVPN: Initialization Sequence Completed
D/OpenVPN: MANAGEMENT: >STATE:1540892436,CONNECTED,SUCCESS,10.8.0.6,195.181.168.14,443,10.69.221.226,54092
D/OpenVPN: Debug state info: CONNECTED LTE to MOBILE internet, pause: userPause, shouldbeconnected: true, network: SHOULDBECONNECTED

**Comment by strider29** [comment]
Also works if I pause and resume it from the notification

**Comment by schwabe** [comment]
Sounds like the state machine is somehow stuck on that phone. The debug log seems to be missing phone information. What phone/UI is that?

**Comment by strider29** [comment]
Its an honor 9. But I guess, it's because I have touched the code somewhere(Not the native files, just the java part) Now I dont know where to look at.

**Comment by schwabe** [comment]
Sorry, if you have a modified version of my software and don't even share the modifications I cannot debug or help you.
