### ISSUE TITLE
Allowed Apps in FireOS 6 (Amazon Fire TV 4K)

### ISSUE THREAD

**Issue by fegauthier** [schwabe/ics-openvpn#963]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
Fire OS 6 fork of Android 7.1
2. Android Vendor/Custom ROM
Fire OS 6
3. Device
Amazon Fire TV 4K
4. Version of the app (version number/play store version/self-built)
FireOS 6
 
# Description of the issue

The allowed apps tab doesn't work with Amazon Fire TV 4K (FireOS 6 fork of Android 7.1). I exclude Firefox from the VPN, but when I start a Speedtest, all the traffic go through the VPN. Do you have any tips of why it doesn't work?

Thank you !

**Comment by schwabe** [comment]
No. This is something that the app really does not have control over. It is more likely a bug in the OS than everything I am afraid.

**Comment by fegauthier** [comment]
Thanks for your quick answer! I will debug the app with the Amazon FireTV to see what happen!

**Comment by gouldja** [comment]
> Thanks for your quick answer! I will debug the app with the Amazon FireTV to see what happen!

I am doing the same also, if you do find out any thing if you could update here that would be great - i will do the same

**Comment by fegauthier** [comment]
Hi @gouldja ,

Unfortunately, I didn't find anything. I debug the process and the selected app are going to the Android OS VPNService but it doesn't work. The problem doesn't come from the @schwabe code.

https://developer.android.com/reference/android/net/VpnService.Builder.html#addAllowedApplication(java.lang.String)

The allowed app goes to the VPNService Builder, but the OS doesn't seem to use it. The only thing that we can do is waiting for a FireTV OS update and hope that Amazon fixed the problem...

**Comment by gouldja** [comment]
ok thanks for the update, i notice that the FireTV 4k is running on a slightly older (unaffected OS) (6.2.5.5) than the Fire TV cube (6.2.3.2), so hopefully once this rolls out the issue will be resolved - unless its closer linked to the Hardware.

Should i find anything further i will update
