### ISSUE TITLE
Can't get project to build under build variant normal(Debug|Release)

### ISSUE THREAD

**Issue by chicobel** [schwabe/ics-openvpn#965]
# General information
1. Android Version: 
2. Android Vendor/Custom ROM : Simulator / Samsung S6
3. Version of the app- main app included in project
 
# Description of the issue
I can't get the main project to build under normalDebug or normalRelease. I have followed the instructions in the readme with no luck. It seems the error is mbedtls related. The noovpn(Debug|Release) variants build fine.  Can you help please? I am trying to build on a mac. Please find below build error output

Build command failed.
Error while executing process /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/cmake/3.6.4111459/bin/cmake with arguments {--build /Users/chico/Repos/ics-openvpn/main/.externalNativeBuild/cmake/normalRelease/x86_64 --target ovpn3}
[1/81] Building C object CMakeFiles/lz4.dir/lz4/lib/lz4.c.o
[2/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/aes.c.o
[3/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/aesni.c.o
[4/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/arc4.c.o
[5/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1parse.c.o
[6/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1write.c.o
[7/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/base64.c.o
[8/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/bignum.c.o
[9/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/blowfish.c.o
[10/81] Building C object mbedtls/library/CMakeFiles/mbedcrypto.dir/camellia.c.o
FAILED: /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot  -I/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/include -isystem /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot/usr/include/x86_64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -fPIC -MD -MT mbedtls/library/CMakeFiles/mbedcrypto.dir/aesni.c.o -MF mbedtls/library/CMakeFiles/mbedcrypto.dir/aesni.c.o.d -o mbedtls/library/CMakeFiles/mbedcrypto.dir/aesni.c.o   -c /Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/aesni.c
/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/aesni.c:28:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot  -I/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/include -isystem /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot/usr/include/x86_64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -fPIC -MD -MT mbedtls/library/CMakeFiles/mbedcrypto.dir/arc4.c.o -MF mbedtls/library/CMakeFiles/mbedcrypto.dir/arc4.c.o.d -o mbedtls/library/CMakeFiles/mbedcrypto.dir/arc4.c.o   -c /Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/arc4.c
/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/arc4.c:28:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot  -I/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/include -isystem /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot/usr/include/x86_64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -fPIC -MD -MT mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1write.c.o -MF mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1write.c.o.d -o mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1write.c.o   -c /Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/asn1write.c
/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/asn1write.c:23:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot  -I/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/include -isystem /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot/usr/include/x86_64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -fPIC -MD -MT mbedtls/library/CMakeFiles/mbedcrypto.dir/base64.c.o -MF mbedtls/library/CMakeFiles/mbedcrypto.dir/base64.c.o.d -o mbedtls/library/CMakeFiles/mbedcrypto.dir/base64.c.o   -c /Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/base64.c
/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/base64.c:23:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot  -I/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/include -isystem /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot/usr/include/x86_64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -fPIC -MD -MT mbedtls/library/CMakeFiles/mbedcrypto.dir/aes.c.o -MF mbedtls/library/CMakeFiles/mbedcrypto.dir/aes.c.o.d -o mbedtls/library/CMakeFiles/mbedcrypto.dir/aes.c.o   -c /Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/aes.c
/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/aes.c:29:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot  -I/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/include -isystem /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot/usr/include/x86_64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -fPIC -MD -MT mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1parse.c.o -MF mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1parse.c.o.d -o mbedtls/library/CMakeFiles/mbedcrypto.dir/asn1parse.c.o   -c /Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/asn1parse.c
/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/asn1parse.c:23:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot  -I/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/include -isystem /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot/usr/include/x86_64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -fPIC -MD -MT mbedtls/library/CMakeFiles/mbedcrypto.dir/bignum.c.o -MF mbedtls/library/CMakeFiles/mbedcrypto.dir/bignum.c.o.d -o mbedtls/library/CMakeFiles/mbedcrypto.dir/bignum.c.o   -c /Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/bignum.c
/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/bignum.c:39:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot  -I/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/include -isystem /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot/usr/include/x86_64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -fPIC -MD -MT mbedtls/library/CMakeFiles/mbedcrypto.dir/blowfish.c.o -MF mbedtls/library/CMakeFiles/mbedcrypto.dir/blowfish.c.o.d -o mbedtls/library/CMakeFiles/mbedcrypto.dir/blowfish.c.o   -c /Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/blowfish.c
/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/blowfish.c:29:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
FAILED: /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=x86_64-none-linux-android21 --gcc-toolchain=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/toolchains/x86_64-4.9/prebuilt/darwin-x86_64 --sysroot=/Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot  -I/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/include -isystem /Users/chico/Library/Developer/Xamarin/android-sdk-macosx/ndk-bundle/sysroot/usr/include/x86_64-linux-android -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -Wextra -W -Wdeclaration-after-statement -Wwrite-strings -Wpointer-arith -Wimplicit-fallthrough -Wshadow -Wmissing-declarations -Wmissing-prototypes -Wdocumentation -Wno-documentation-deprecated-sync -Wunreachable-code -O2 -fPIC -MD -MT mbedtls/library/CMakeFiles/mbedcrypto.dir/camellia.c.o -MF mbedtls/library/CMakeFiles/mbedcrypto.dir/camellia.c.o.d -o mbedtls/library/CMakeFiles/mbedcrypto.dir/camellia.c.o   -c /Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/camellia.c
/Users/chico/Repos/ics-openvpn/main/src/main/cpp/mbedtls/library/camellia.c:29:10: fatal error: 'mbedtls/config.h' file not found
#include "mbedtls/config.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

**Comment by anshul-arora** [comment]
@chicobel, when you took the pull for this repository, I think you forgot to run the following commands from root directory of the project
`git submodule init`
`git submodule update`

**Comment by chicobel** [comment]
@anshul-arora  Thanks, I'm not really a command line/Terminal type of person when it comes to git.
Issue seemed to have arisen from my using source tree and pulling the wrong branches of some of the submodules
