### ISSUE TITLE
ndk build failed (For ndk lower than 16)

### ISSUE THREAD

**Issue by anshul-arora** [schwabe/ics-openvpn#966]
Hello schwabe

I was trying to build the application using android ndk 13-15 but i am unable to build. As i went through the logs, i found that its unable to build for mips, mips64 and armeabi.

So i just wanted to confirm am i doing something wrong or your app doesn't work for mips, mips64 and armeabi architecture

Thanks in Advance

**Comment by schwabe** [comment]
I dropped support for older ndk and therefore also mips since there seem to be virtually no device that uses mips.
