### ISSUE TITLE
[Bug] App crashes randomly while VPN is connected

### ISSUE THREAD

**Issue by Atrate** [schwabe/ics-openvpn#967]
# General information

Android Version: 8.1

Android Vendor/Custom ROM: Resurrection Remix Oreo (LOS based)

Device: Samsung Galaxy S5 (klte)

Version of the app: 0.7.6-play

Additional Modifications: Magisk, Xposed and a Substratum theme applied system-wide

# Description of the issue

Happens randomly when VPN is enabled and the notification is set to lowest priority (though I haven't tested it with it set to normal prio), not disabled (doesn't crash when notificaons disabled). 

The app just crashes, throws a stack trace as below and Android shows a standard "OpenVPN for Android has stopped".

Self-diagnosis: could really be something to do with the substratum theme (PitchBlack Origins)

Stack trace:

```
android.app.RemoteServiceException: Bad notification posted from package de.blinkt.openvpn: Couldn't inflate contentViewsandroid.widget.RemoteViews$ActionException: java.lang.NullPointerException: outValue
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1769)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6499)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
	at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
```

**Comment by schwabe** [comment]
The traceback does not even have my app in it. It seems that some  system code that handles showing notification is crashing. Maybe my app does something that triggers that but since my app does not even use a custom view (just a standard notification), I think that is unlikely. 

This might be a bug in Samsungs modifcation or the substratum theme related.

**Comment by Atrate** [comment]
Confirmed, related to the Substratum theme, closing.
