### ISSUE TITLE
pull-filter 

### ISSUE THREAD

**Issue by bklynali** [schwabe/ics-openvpn#968]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 8.1
2. Android Vendor/Custom ROM Samsung 
3. Device
4. Version of the app (version number/play store version/self-built) l
 
# Description of the issue
When using pull-filter the app ignore what you put

**Comment by schwabe** [comment]
I don't understand the issue. Do you have the problem that the pull-filter option is ignored or that the pull-filter option causes openvpn to ignore options?

**Comment by bklynali** [comment]
0.7.6 or 5 and 4 all ignore the pull-filter option and uses the sever push option

**Comment by schwabe** [comment]
I still cannot make sense of the small bits of information that you are giving me. Could please give me a step by step what you are trying to do and would you expect to see and what you see instead?

**Comment by bklynali** [comment]
so I go into the app and I put pull-filter ignore "ping" when I am using the app 0.7.1 when openvpn 2 it works the app ignore ping which is pushed by the server. Now in 0.7.6 it does not also when I check on openvpn 3 it stated on the log unused options pull-filter "ping"

**Comment by schwabe** [comment]
OpenVPN 3 does not implement the pull-filter at all. For OpenVPN 2 the feature should work. If not, please provide a log. Also ignoring the ping setting from the server is a bad idea (read and understand the man page section about ping to understand why)
