### ISSUE TITLE
Per App Filter Not Working on new 4k Fire TV Stick Device

### ISSUE THREAD

**Issue by gouldja** [schwabe/ics-openvpn#969]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

2. Android Vendor/Custom ROM - Amazon

Fire OS 6 — Based on Android 7.1 (API level 25)

3. Device
Fire TV Stick 4k (Released Oct 2018)

4. Version of the app (version number/play store version/self-built)
All Versions 0.6.70 - 0.7.5 (Current)
 
# Description of the issue
When the VPN Client is connected all applications route via the VPN. Despite using the app white listing feature. I am guessing this is device specific as this has been working on all previous iterations of the FireTV devices and other android devices.
I would be happy to help with identifying the root cause

Note this is working on Fire TV Cube which is also "Fire OS 6 — Based on Android 7.1 (API level 25)" and Fire TV Stick (non 4k) - "Fire OS 5 — Based on Android 5.1 (API Level 22)"

**Comment by schwabe** [comment]
Duplicate of other reports of this. This is almost certainly a bug in the underlying OS.

**Comment by gouldja** [comment]
thanks for the fast response
