### ISSUE TITLE
without ca certificate 

### ISSUE THREAD

**Issue by fakhriamir** [schwabe/ics-openvpn#970]
i want to connect without ca certificate and just use username and password 
Access Server version: 2.5.2
error: 
options error: unrecognized option or missing or extra parameter(s) in ....android.conf:20:ca(2.5_master)
line 20 config file:
ca file missing in config profile

**Comment by schwabe** [comment]
Direct download of Access Server profiles is not supported in this app. I suggest either downloading the ovpn profile via the AS web interface or using the OpenVPN Connect app.
