### ISSUE TITLE
Chromebook: VPN enters inconsistent state

### ISSUE THREAD

**Issue by nathankurtyka** [schwabe/ics-openvpn#974]
Hello!

First, in case it's unexpected to find a Chromebook issue here, note that this client is now [being promoted by Google](https://support.google.com/chromebook/answer/1282338?hl=en) (under "OpenVPN Support")

This issue occurs on the latest ChromeOS: "Version 70.0.3538.76 (Official Build) (64-bit)", across on multiple Chromebook devices (eg. Pixelbook and Acer 13) and 0.7.5 of the OpenVPN app.

Basically, closing and reopening the Chromebook lid causes the VPN to dis/reconnect... but the OS never resumes sending traffic through the reconnected VPN (it leaves the Chromebook unprotected).  

Fortunately, it seems that running "OpenVPN 3 Core" fixes this issue (at least I've been unable to reproduce it). But I'm not sure if this is a fix I should bank on, as we're currently evaluating deploying this app to all of our Chromebooks.

I've attached:
- Logs of the issue occurring with "OpenVPN 3 Core" disabled [not-working.log](https://github.com/schwabe/ics-openvpn/files/2612617/not-working.log)
- Logs of the issue not occurring with "OpenVPN 3 Core" enabled (but going through the same process) [working.log](https://github.com/schwabe/ics-openvpn/files/2612616/working.log)
- An image that shows the Chromebook recognizing the VPN connected, but no system traffic going through it 
![screenshot 2018-11-24 at 4 14 05 pm](https://user-images.githubusercontent.com/4063958/48973365-d134b900-f00b-11e8-914a-c21272ef7167.png)

**Comment by schwabe** [comment]
To summarise this. OpenVPN works fine but after sleep/resume cycle traffic is not gong over the VPN anymore?

This sounds really like a Chromebook OS issue rather than a issue with my app. The log show reconnecting  so I assume that is when you closed the lid.
