### ISSUE TITLE
Issue with compiling on Ubuntu 18.04 

### ISSUE THREAD

**Issue by nhx99** [schwabe/ics-openvpn#980]
I have followed the guide and installed all required tools,  i have errors when trying to compile main module. Can you help me out, thank you.

Android resource compilation failed
Output:  /home/nedim/Radna površ/ics-openvpn/main/build/intermediates/incremental/mergeNoovpn3DebugResources/merged.dir/values-it/values-it.xml:328: error: unescaped apostrophe in string
"Se non hai ottenuto una finestra di conferma VPN, hai abilitato \"Sempre in VPN \" per un'altra applicazione. In questo caso solo l'applicazione può connettersi a una VPN. Controlla in Impostazioni-> Altre reti .. -> VPNS".
/home/nedim/Radna površ/ics-openvpn/main/build/intermediates/incremental/mergeNoovpn3DebugResources/merged.dir/values-it/values-it.xml:328: error: not a valid string.

Command: /home/nedim/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-linux.jar/7ef011ab836ade163c3a218a8933a4b8/aapt2-3.2.1-4818971-linux/aapt2 compile --legacy \
        -o \
        /home/nedim/Radna površ/ics-openvpn/main/build/intermediates/res/merged/noovpn3/debug \
        /home/nedim/Radna površ/ics-openvpn/main/build/intermediates/incremental/mergeNoovpn3DebugResources/merged.dir/values-it/values-it.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-linux Daemon #2

**Comment by schwabe** [comment]
You probbly got a checkout from a version with broken strings, try checking out a version with a release tag. master does not always build.
