### ISSUE TITLE
Read / Write storage permissions denied on Amazon FireTV 3rd Gen

### ISSUE THREAD

**Issue by kasi45** [schwabe/ics-openvpn#983]
# General information
 Fire OS 6.2.5.8
 Amazon FireTV 3rd Gen
ics-openvpn 0.7.7
 
# Description of the issue

Read / Write storage permissions denied on Amazon FireTV 3rd Gen
- No dialog for granting authorization during installation
- Cannot change authorization after installation 
- VPN configurations cannot be imported

As an example:
I don't know how it works but https://www.amazon.co.uk/AFTVnews-com-Downloader/dp/B01N0BP507
has access to dl files and delete them also

![Dialog Dateizugriff ](https://user-images.githubusercontent.com/18262216/50375677-d16fa680-0601-11e9-8c83-cf7a2aa94f3a.png)

![122218154914](https://user-images.githubusercontent.com/18262216/50375842-7d19f600-0604-11e9-8e6c-191f05edb67e.png)

![122218154934](https://user-images.githubusercontent.com/18262216/50375846-91f68980-0604-11e9-930a-6f6f53d5ece2.png)

ICS-OPENVPN

No dialog permissions 

![122218161903](https://user-images.githubusercontent.com/18262216/50375909-6e800e80-0605-11e9-9da1-c436b9054d90.png)

![122218162105](https://user-images.githubusercontent.com/18262216/50375926-a4bd8e00-0605-11e9-8492-7bd276b93417.png)

![122218162254](https://user-images.githubusercontent.com/18262216/50375947-d6cef000-0605-11e9-9e75-25c590e60601.png)

![122218163053](https://user-images.githubusercontent.com/18262216/50376019-f7e41080-0606-11e9-9f0a-ec7d540fe41e.png)

Access to the stick not possible!

ICS-OPENVPN works great on a FireTV Stick Gen2!!!!

Info:
https://developer.amazon.com/de/blogs/appstore/post/2ef7b757-557e-4464-b4e8-a6cf67ccb598/managing-app-permissions-with-fire-tv-gen-3

**Comment by kasi45** [comment]
https://github.com/schwabe/ics-openvpn/issues/903

Here was probably the same problem

I think in the following article linked by me you can find the explanation why the app openvpn works on the FireTV Stick 2 and why not on the FireTV Stick 3

https://forums.developer.amazon.com/questions/92338/bug-adm-is-not-working-on-new-60-firetv-needle-dev.html

**Comment by schwabe** [comment]
The app does not need storage permission to work correctly. I need the permission for the internal file browser or when trying to import extra files. The picture of last the dialog is not even the app itself that is the Android OS file browser. If that does not show your files something else is wrong.

**Comment by kasi45** [comment]
Thanks for the quick answer.
In the next days I will analyse the problem in more detail. 
Ich erlaube mir mal in Deutsch weiter zu schreiben. Mein Englisch ist einfach zu schlecht.

Soweit ich weis (glaube) wird seit "Marshmallow" Rechte für "gefährlich" eingestufte Zugriffe zur Laufzeit vergeben. In der "AndroidManifest.xml" fand ich in einem anderen Projekt neben den Eintrag 
**uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"**
 dazu den zusätzlichen  Eintrag 
**uses-permission-sdk-23 android:name="android.permission.READ_EXTERNAL_STORAGE"**  (Android 
Run-time permission requirement since API Level 23. )
Früher musste ich Probleme bei Microdoof und Novell  analysieren - als Rentner hab ich ja nun Zeit und werde mich dann mal intensiver  mit Android beschäftigen. 
Über welche Funktion wird in deinem Projekt der Android OS-Dateibrowser aufgerufen?

Danke für deine Arbeit an diesem Projekt!

**Comment by schwabe** [comment]
The app only needs the permissin for importing VPN profiles. So if you sucessfully got the profile imported you don't need the permissions. Also if you start the import from an external file browser the app does not need the permissions.

The code to open the browser in Utils.java, getFilePickerIntent. Should be good enough as starting point to find the rest.

**Comment by gregor-hh** [comment]
Hallo, ich habe exakt das gleiche Problem, gibts hier schon eine Lösung wie man *.ovpn Dateien auf dem FireTV4k importieren kann? Das Verhalten hier ist genau das gleiche das man kein Zugriff hat auf das Dateisystem :-(

**Comment by cowst** [comment]
I don't have this problem.
I got my ovpn from nordvpn with Downloader (but I think you can just copy it to the stick however you want), then from ES explorer (external file browser, as stated already before) I selected it and told to open it with openvpn.
Worked consistently several times.

**Comment by gregor-hh** [comment]
Thank you verry verry much cowst!!!! So awesome!!!
ES Explorer + "Open with" -> OpenVPN Import ffg did the trick!! The login.conf could't be imported but username and password can be saved in the OpenVPN App, perfect.
