### ISSUE TITLE
F-Droid beta versions

### ISSUE THREAD

**Issue by 532910** [schwabe/ics-openvpn#984]
Please make beta versions available on F-Droid

**Comment by schwabe** [comment]
I am not maintainer of the F-Droid version. F-Droid itself decides if they want to pickup beta versions. I think F-droid does not have a good way to handle beta version, therefore it only picks up stable versions.

**Comment by 532910** [comment]
OK, I've opened F-Droid issue: https://gitlab.com/fdroid/fdroiddata/issues/1482

**Comment by 532910** [comment]
related: https://github.com/schwabe/ics-openvpn/issues/984

**Comment by 532910** [comment]
The F-Droid answer:

"We already include all tagged versions of OpenVPN. Compare https://github.com/schwabe/ics-openvpn/releases and https://f-droid.org/wiki/page/de.blinkt.openvpn."

The version on GPlay is 0.7.7 (for beta testers subsribers)

Could you make git tags for beta versions?

**Comment by schwabe** [comment]
There git tags for beta versions.  I missed v0.7.6 but the production tags are only for f-droid since they did not want beta versions. If they changed their mind, Note that beta versions are often almost untested so pushing them to all users might not be the best idea.

**Comment by 532910** [comment]
> I missed v0.7.6
you'd like to say 0.7.7, right?

**Comment by 532910** [comment]
relan @ fdroid gitlab:

> 0.7.5-production is a Git tag for 0.7.5. Previous versions in the 0.7.x series are missing because before 0.7.6 we used to build only *-production tags.
> So now we have the latest stable 0.7.5 and latest tagged 0.7.6. Once the author tags a new version, it'll be added automatically.

Could you add 0.7.7 so it should be added automatically

**Comment by 532910** [comment]
Dear schwabe and relan.

Looks like there is a misunderstanding.

Could you discuss this in one place please.
