### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by WindRush** [schwabe/ics-openvpn#985]
when i use android studio to build the project, it shows me this error, can you tell me how can i to do 

Android resource compilation failed
Output:  /Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/incremental/mergeNoovpn3DebugResources/merged.dir/values-it/values-it.xml:328: error: unescaped apostrophe in string
"Se non hai ottenuto una finestra di conferma VPN, hai abilitato \"Sempre in VPN \" per un'altra applicazione. In questo caso solo l'applicazione può connettersi a una VPN. Controlla in Impostazioni-> Altre reti .. -> VPNS".
/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/incremental/mergeNoovpn3DebugResources/merged.dir/values-it/values-it.xml:328: error: not a valid string.

Command: /Users/yanglihai/.gradle/caches/transforms-1/files-1.1/aapt2-3.2.1-4818971-osx.jar/bfae32c59806d4a65c4ef61d2d541157/aapt2-3.2.1-4818971-osx/aapt2 compile --legacy \
        -o \
        /Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/res/merged/noovpn3/debug \
        /Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/incremental/mergeNoovpn3DebugResources/merged.dir/values-it/values-it.xml
Daemon:  AAPT2 aapt2-3.2.1-4818971-osx Daemon #3

**Comment by schwabe** [comment]
Yes. Some version in master are not buildable. For those you have to fix it yourself or use a version with a release tag.

**Comment by WindRush** [comment]
is the tag named end with production is a release tag?

**Comment by schwabe** [comment]
yes

**Comment by WindRush** [comment]
i have  clone a release tag, but it failed again, those are the messages,please help me:
SIMPLE: Build command failed.
SIMPLE: Error while executing process /Users/yanglihai/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/src/main/cpp -B/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/.externalNativeBuild/cmake/normalRelease/armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/cmake/normal/release/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/Users/yanglihai/Library/Android/sdk/ndk-bundle -DCMAKE_TOOLCHAIN_FILE=/Users/yanglihai/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/yanglihai/Library/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}


SIMPLE: -- Check for working C compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang


SIMPLE: -- Check for working C compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works


SIMPLE: -- Detecting C compiler ABI info


SIMPLE: -- Detecting C compiler ABI info - done


SIMPLE: -- Detecting C compile features


SIMPLE: -- Detecting C compile features - done


SIMPLE: -- Check for working CXX compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++


SIMPLE: -- Check for working CXX compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works


SIMPLE: -- Detecting CXX compiler ABI info


SIMPLE: -- Detecting CXX compiler ABI info - done


SIMPLE: -- Detecting CXX compile features


SIMPLE: -- Detecting CXX compile features - done


SIMPLE: OpenVPN 2.x version v0.7.5-production-0-g2b9700c2


SIMPLE: OpenVPN 3.x version v0.7.5-production-0-g2b9700c2


SIMPLE: -- The ASM compiler identification is Clang


SIMPLE: -- Found assembler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang


SIMPLE: -- Found SWIG: /usr/local/bin/swig (found suitable version "3.0.12", minimum required is "3.0") 


SIMPLE: CMake Error at CMakeLists.txt:27 (add_subdirectory):


SIMPLE:     /Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/src/main/cpp/mbedtls


SIMPLE:   does not contain a CMakeLists.txt file.


SIMPLE: -- Configuring incomplete, errors occurred!


SIMPLE: See also "/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/.externalNativeBuild/cmake/normalRelease/armeabi-v7a/CMakeFiles/CMakeOutput.log".


SIMPLE: Build command failed.


SIMPLE: Error while executing process /Users/yanglihai/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/src/main/cpp -B/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/.externalNativeBuild/cmake/normalDebug/armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/cmake/normal/debug/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/Users/yanglihai/Library/Android/sdk/ndk-bundle -DCMAKE_TOOLCHAIN_FILE=/Users/yanglihai/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/yanglihai/Library/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}


SIMPLE: -- Check for working C compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang


SIMPLE: -- Check for working C compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works


SIMPLE: -- Detecting C compiler ABI info


SIMPLE: -- Detecting C compiler ABI info - done


SIMPLE: -- Detecting C compile features


SIMPLE: -- Detecting C compile features - done


SIMPLE: -- Check for working CXX compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++


SIMPLE: -- Check for working CXX compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works


SIMPLE: -- Detecting CXX compiler ABI info


SIMPLE: -- Detecting CXX compiler ABI info - done


SIMPLE: -- Detecting CXX compile features


SIMPLE: -- Detecting CXX compile features - done


SIMPLE: OpenVPN 2.x version v0.7.5-production-0-g2b9700c2


SIMPLE: OpenVPN 3.x version v0.7.5-production-0-g2b9700c2


SIMPLE: -- The ASM compiler identification is Clang


SIMPLE: -- Found assembler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang


SIMPLE: -- Found SWIG: /usr/local/bin/swig (found suitable version "3.0.12", minimum required is "3.0") 


SIMPLE: CMake Error at CMakeLists.txt:27 (add_subdirectory):


SIMPLE:     /Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/src/main/cpp/mbedtls


SIMPLE:   does not contain a CMakeLists.txt file.


SIMPLE: -- Configuring incomplete, errors occurred!


SIMPLE: See also "/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/.externalNativeBuild/cmake/normalDebug/armeabi-v7a/CMakeFiles/CMakeOutput.log".


SIMPLE: Build command failed.


SIMPLE: Error while executing process /Users/yanglihai/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/src/main/cpp -B/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/.externalNativeBuild/cmake/noovpn3Debug/armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/cmake/noovpn3/debug/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=/Users/yanglihai/Library/Android/sdk/ndk-bundle -DCMAKE_TOOLCHAIN_FILE=/Users/yanglihai/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/yanglihai/Library/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}


SIMPLE: -- Check for working C compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang


SIMPLE: -- Check for working C compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works


SIMPLE: -- Detecting C compiler ABI info


SIMPLE: -- Detecting C compiler ABI info - done


SIMPLE: -- Detecting C compile features


SIMPLE: -- Detecting C compile features - done


SIMPLE: -- Check for working CXX compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++


SIMPLE: -- Check for working CXX compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works


SIMPLE: -- Detecting CXX compiler ABI info


SIMPLE: -- Detecting CXX compiler ABI info - done


SIMPLE: -- Detecting CXX compile features


SIMPLE: -- Detecting CXX compile features - done


SIMPLE: OpenVPN 2.x version v0.7.5-production-0-g2b9700c2


SIMPLE: OpenVPN 3.x version v0.7.5-production-0-g2b9700c2


SIMPLE: -- The ASM compiler identification is Clang


SIMPLE: -- Found assembler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang


SIMPLE: Not budiling OpenVPN for output dir /Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/cmake/noovpn3/debug/obj/armeabi-v7a


SIMPLE: -- Configuring done


SIMPLE: CMake Error at CMakeLists.txt:170 (add_library):


SIMPLE:     openvpn/src/compat/compat-basename.c


SIMPLE:   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp


SIMPLE:   .hxx .in .txx


SIMPLE: CMake Error at openssl.cmake:649 (add_library):


SIMPLE:     openssl/crypto/aes/aes_cbc.c


SIMPLE: Call Stack (most recent call first):


SIMPLE:   CMakeLists.txt:20 (include)


SIMPLE: CMake Error at lz4.cmake:6 (add_library):


SIMPLE:     lz4/lib/lz4.c


SIMPLE:   CMakeLists.txt:19 (include)


SIMPLE: CMake Error at openssl.cmake:823 (add_library):


SIMPLE:     openssl/ssl/bio_ssl.c


SIMPLE: CMake Error: CMake can not determine linker language for target: openvpn


SIMPLE: CMake Error: CMake can not determine linker language for target: crypto


SIMPLE: CMake Error: CMake can not determine linker language for target: lz4


SIMPLE: CMake Error: CMake can not determine linker language for target: ssl


SIMPLE: -- Generating done


SIMPLE: -- Build files have been written to: /Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/.externalNativeBuild/cmake/noovpn3Debug/armeabi-v7a


SIMPLE: Build command failed.


SIMPLE: Error while executing process /Users/yanglihai/Library/Android/sdk/cmake/3.6.4111459/bin/cmake with arguments {-H/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/src/main/cpp -B/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/.externalNativeBuild/cmake/noovpn3Release/armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/cmake/noovpn3/release/obj/armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=/Users/yanglihai/Library/Android/sdk/ndk-bundle -DCMAKE_TOOLCHAIN_FILE=/Users/yanglihai/Library/Android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/Users/yanglihai/Library/Android/sdk/cmake/3.6.4111459/bin/ninja -GAndroid Gradle - Ninja -DANDROID_TOOLCHAIN=clang -DANDROID_STL=c++_static}


SIMPLE: -- Check for working C compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang


SIMPLE: -- Check for working C compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -- works


SIMPLE: -- Detecting C compiler ABI info


SIMPLE: -- Detecting C compiler ABI info - done


SIMPLE: -- Detecting C compile features


SIMPLE: -- Detecting C compile features - done


SIMPLE: -- Check for working CXX compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++


SIMPLE: -- Check for working CXX compiler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++ -- works


SIMPLE: -- Detecting CXX compiler ABI info


SIMPLE: -- Detecting CXX compiler ABI info - done


SIMPLE: -- Detecting CXX compile features


SIMPLE: -- Detecting CXX compile features - done


SIMPLE: OpenVPN 2.x version v0.7.5-production-0-g2b9700c2


SIMPLE: OpenVPN 3.x version v0.7.5-production-0-g2b9700c2


SIMPLE: -- The ASM compiler identification is Clang


SIMPLE: -- Found assembler: /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang


SIMPLE: Not budiling OpenVPN for output dir /Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/build/intermediates/cmake/noovpn3/release/obj/armeabi-v7a


SIMPLE: -- Configuring done


SIMPLE: CMake Error at CMakeLists.txt:170 (add_library):


SIMPLE:     openvpn/src/compat/compat-basename.c


SIMPLE:   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp


SIMPLE:   .hxx .in .txx


SIMPLE: CMake Error at openssl.cmake:649 (add_library):


SIMPLE:     openssl/crypto/aes/aes_cbc.c


SIMPLE: Call Stack (most recent call first):


SIMPLE:   CMakeLists.txt:20 (include)


SIMPLE: CMake Error at lz4.cmake:6 (add_library):


SIMPLE:     lz4/lib/lz4.c


SIMPLE:   CMakeLists.txt:19 (include)


SIMPLE: CMake Error at openssl.cmake:823 (add_library):


SIMPLE:     openssl/ssl/bio_ssl.c


SIMPLE: CMake Error: CMake can not determine linker language for target: openvpn


SIMPLE: CMake Error: CMake can not determine linker language for target: crypto


SIMPLE: CMake Error: CMake can not determine linker language for target: lz4


SIMPLE: CMake Error: CMake can not determine linker language for target: ssl


SIMPLE: -- Generating done


SIMPLE: -- Build files have been written to: /Users/yanglihai/AndroidStudioProjects/ics-openvpn/main/.externalNativeBuild/cmake/noovpn3Release/armeabi-v7a

**Comment by schwabe** [comment]
duplicate of other reports and failure to read README.

**Comment by WindRush** [comment]
now I have changed my OS to windows, and I got another problem, please help me :

Caused by: org.gradle.api.GradleException: executing external native build for cmake E:\androidProjects\ics-openvpn\main\src\main\cpp\CMakeLists.txt
	at com.android.build.gradle.internal.errors.SyncIssueHandlerImpl.reportIssue(SyncIssueHandlerImpl.kt:53)
	at com.android.builder.errors.EvalIssueReporter$DefaultImpls.reportError(EvalIssueReporter.kt:122)
	at com.android.build.gradle.internal.errors.SyncIssueHandler$DefaultImpls.reportError(SyncIssueHandler.kt)
	at com.android.build.gradle.internal.errors.SyncIssueHandlerImpl.reportError(SyncIssueHandlerImpl.kt:30)
	at com.android.build.gradle.tasks.ExternalNativeJsonGenerator.build(ExternalNativeJsonGenerator.java:203)
	at com.android.build.gradle.BasePlugin.lambda$createAndroidTasks$7(BasePlugin.java:818)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.createAndroidTasks(BasePlugin.java:806)
	at com.android.build.gradle.BasePlugin.lambda$null$4(BasePlugin.java:652)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:81)
	at com.android.build.gradle.BasePlugin.lambda$createTasks$5(BasePlugin.java:648)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:91)
	at org.gradle.internal.event.BroadcastDispatch$ActionInvocationHandler.dispatch(BroadcastDispatch.java:80)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
	at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
	at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
	at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
	at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy25.afterEvaluate(Unknown Source)
	at org.gradle.configuration.project.LifecycleProjectEvaluator.notifyAfterEvaluate(LifecycleProjectEvaluator.java:76)

**Comment by schwabe** [comment]
I don't test myself on Windows very often. My own development platform is macOS. The output however suggests that something went wrong with cmake, I suggest to look at the output of cmake.

**Comment by WindRush** [comment]
i have tried the macOS and windowsOS, but i failed to load the project with the cmake,  can you send me a built  version. i will be very thankful.My email is 969870523@qq.com

**Comment by schwabe** [comment]
already built version are at plai.de/android

**Comment by WindRush** [comment]
sorry i cant understand well, whats the meaning of  "plai.de/android". can you tell me the url of built version

**Comment by schwabe** [comment]
that is the url
