### ISSUE TITLE
OpenVPN doesnt work since upgrade Android to 9.0 pie

### ISSUE THREAD

**Issue by kawett** [schwabe/ics-openvpn#988]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version : 9.0 Pie
2. Android Vendor/Custom ROM : Android ONE / 
3. Device Xiaomi Mi A2 lite
4. Version of the app (version number/play store version/self-built) version 0.7.5

 
# Description of the issue
Hello and happy new year !
Since I upgraded my phone to Android 9.0 the vpn doesn't work.
I'm able to connect using my certificate but it looks like only a few paquets are received on the phone.
I'm able to send commands throught SSH but I can't display the home page of my router for instance.
I tried on another cellphone wich runs an older version of Android and it works perfectly.
I tried to unlimit usage of the battery or data for this app but still it doesn't work.

Thanks a lot for your help and thanks a lot for the good work !

**Comment by schwabe** [comment]
There is no general problem with Android 9.0. What you are describing sounds like a MTU problem. Try the MTU fix option in the app.

**Comment by kawett** [comment]
I try the "Replace MSS value by TCP..." stuff and it works !
Thanks a lot. I don't know why it began with the upgrade to Android 9...
