### ISSUE TITLE
Bad bug 

### ISSUE THREAD

**Issue by EnvelGo1** [schwabe/ics-openvpn#989]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version 8.1
2. MIUI 10
3. xiaomi redmi note 5 
4. Version app 0.7.5
 
Strange problem. I don't know how to send a video here. In general. Security updates from Google play, which is automatic if the VPN is enabled, trying to connect, but fails. This causes dozens of notifications and the notification bar goes crazy. This is the problem of this particular application.

**Comment by EnvelGo1** [comment]
The same is true when updating apps via miui.

**Comment by schwabe** [comment]
There is no general problem with Google Updates via VPN. However, I know that some VPN provider might have broken configs that cause this issue.
