### ISSUE TITLE
Problem using cert with RSA 4096 bit key on 0.7.5

### ISSUE THREAD

**Issue by jimklimov** [schwabe/ics-openvpn#990]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
6.0 mra58k
2. Android Vendor/Custom ROM
Xiaomi
3. Device
Redmi Note 4
4. Version of the app (version number/play store version/self-built)
0.7.5
 
# Description of the issue

Our server and users used certificates with rsa 1024 bit keys for many years, with no problem to update them yearly. This year keys were changed to 4096 bit, and desktop and Linux/BSD/Solaris clients had no problems updating.

The Android client however says there is no data when we import the private key file or certificate file into the connection settings, same as was done many times before.

**Comment by jimklimov** [comment]
Tried with the beta version from Play Market - the same :\

**Comment by schwabe** [comment]
Can you have a more complete bug report? Where exactly does it say "no data"? There is no general problem with 4096 bit RSA keys.

**Comment by jimklimov** [comment]
Yes, sorry. I go to the existing connection profile, tap the pencil button to edit, then for "Client certificate" and "Client certificate key" that had some (expired) summaries I tapped "Select..." and pointed to the downloaded newly generated files. Instead of seeing the new certificate data summary as expected, I got "No data" right there.

**Comment by jimklimov** [comment]
Hm... retried with older certs that worked - and it failed too. Then I had a hunch that in other apps I sometimes had similar problems reading files because the system application "Documents" is for some reason disabled after boot and has to be manually enabled when I need it.

Other apps usually detect this state and suggest what the user should do, so I was a bit baffled here.

With "Documents" enabled, I got the new cert/key data correctly.

So this issue becomes rather not the key length support, but of the app behavior when Documents are not enabled (perhaps, when a read() returns 0 bytes and/or some error?)

Thanks

**Comment by schwabe** [comment]
That is a kind of very strange error. I never seen that behaviour that returning from Documents might not return something useful. On my devices I cannot disable that app. So I cannot really test this and I don't really like buying a Xionami device for that issue.

**Comment by jimklimov** [comment]
Well... perhaps then just make a bit of documentation know-how. I am not
sure how the missing access to "documents" looks like, given that file
selector does work... but if the app has come to decide it has got "No
data" from the file, might as well pop up a suggestion what to look out for
:)

**Comment by schwabe** [comment]
I am hesitant to do anything right now because I have absolutely no idea what is going on your end, so documenting something wrong is worse than documenting nothing at all.
