### ISSUE TITLE
Could you tell me what OpenVPN version is this app using?

### ISSUE THREAD

**Issue by UgVaDevLabs** [schwabe/ics-openvpn#991]
To make issues more manageable, I would appreciate it if you fill out the following details as applicable:

# General information
1. Android Version
2. Android Vendor/Custom ROM
3. Device
4. Version of the app (version number/play store version/self-built)
 
# Description of the issue

**Comment by schwabe** [comment]
The app shows the version in the log. It is OpenVPN development version (master, the version that will eventually become 2.5)

**Comment by schwabe** [comment]
Also I already you that question on my openvpn repo. Please don't double post
