### ISSUE TITLE
How to implement PPTP

### ISSUE THREAD

**Issue by AL4AL** [schwabe/ics-openvpn#992]
Hi
My employer wants me to implement PPTP vpn app,
As far as I know PPTP is microsoft property and there is no api in sdk or third-part library for it
Can you help me what to do?
I just knew PPTP is just a protocol and server sould be compatibile with it, So if the server is PPTP I can't use  openVpn or something instead.

**Comment by schwabe** [comment]
I am not helping you for free on anything that is clearly commercial. Best thing I probably can do for you I offer (paid) consultant service on dealing with the VPNService API
