### ISSUE TITLE
old version in the google play store

### ISSUE THREAD

**Issue by montaqa** [schwabe/ics-openvpn#994]
Hi,

i was facing issues related to sending big packets (I believe more than the standard MTU size) and it seems the udp tunnel is not able to fragment it for some reason (android 8.0, Huawei mate 9). i upgraded to 0.7.7 and it starts working. this version is still not in the app store. I'm not sure why there is this lag between the published version and the one in:
http://plai.de/android/

**Comment by schwabe** [comment]
because newer versions are still beta. I am not aware of a specific change related to MTU. And the problem as always is lack of time.
