### ISSUE TITLE
generate a debug apk ,errors 

### ISSUE THREAD

**Issue by WindRush** [schwabe/ics-openvpn#995]
when i want to generate a debug version apk, it shows me errors, these are some of text:
In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:70:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address.hpp:25:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address_v6.hpp:276:38: error: unknown type name 'string_view'; did you mean 'std::string_view'?
  ASIO_DECL address_v6 make_address_v6(string_view str);
                                       ^~~~~~~~~~~
                                       std::string_view
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:70:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address.hpp:25:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address_v6.hpp:283:5: error: unknown type name 'string_view'; did you mean 'std::string_view'?
      string_view str, asio::error_code& ec);
      ^~~~~~~~~~~
      std::string_view
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:70:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address.hpp:25:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address_v6.hpp:333:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/impl/address_v6.ipp:308:28: error: unknown type name 'string_view'; did you mean 'std::string_view'?
  address_v6 make_address_v6(string_view str)
                             ^~~~~~~~~~~
                             std::string_view
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:70:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address.hpp:25:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address_v6.hpp:333:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/impl/address_v6.ipp:313:28: error: unknown type name 'string_view'; did you mean 'std::string_view'?
  address_v6 make_address_v6(string_view str,
                             ^~~~~~~~~~~
                             std::string_view
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:70:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address.hpp:217:32: error: unknown type name 'string_view'; did you mean 'std::string_view'?
  ASIO_DECL address make_address(string_view str);
                                 ^~~~~~~~~~~
                                 std::string_view
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:70:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address.hpp:225:5: error: unknown type name 'string_view'; did you mean 'std::string_view'?
      string_view str, asio::error_code& ec);
      ^~~~~~~~~~~
      std::string_view
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:70:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address.hpp:257:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/impl/address.ipp:139:22: error: unknown type name 'string_view'; did you mean 'std::string_view'?
  address make_address(string_view str)
                       ^~~~~~~~~~~
                       std::string_view
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:70:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/address.hpp:257:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/impl/address.ipp:144:22: error: unknown type name 'string_view'; did you mean 'std::string_view'?
  address make_address(string_view str,
                       ^~~~~~~~~~~
                       std::string_view
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:79:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/basic_resolver.hpp:27:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/basic_resolver_iterator.hpp:27:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/basic_resolver_entry.hpp:53:7: error: no type named 'string_view' in namespace 'asio'; did you mean 'std::string_view'?
        ASIO_STRING_VIEW_PARAM host, ASIO_STRING_VIEW_PARAM service)
        ^~~~~~~~~~~~~~~~~~~~~~
        std::string_view
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/detail/string_view.hpp:40:33: note: expanded from macro 'ASIO_STRING_VIEW_PARAM'
  # define ASIO_STRING_VIEW_PARAM asio::string_view
                                  ^~~~~~
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/client/ovpncli.cpp:30:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/openvpn3/openvpn/io/io.hpp:28:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio.hpp:79:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/basic_resolver.hpp:27:
  In file included from /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/basic_resolver_iterator.hpp:27:
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/ip/basic_resolver_entry.hpp:53:36: error: no type named 'string_view' in namespace 'asio'; did you mean 'std::string_view'?
        ASIO_STRING_VIEW_PARAM host, ASIO_STRING_VIEW_PARAM service)
                                     ^~~~~~~~~~~~~~~~~~~~~~
                                     std::string_view
  /Users/yanglihai/ovpn7.5/ovpn7.5/main/src/main/cpp/asio/asio/include/asio/detail/string_view.hpp:40:33: note: expanded from macro 'ASIO_STRING_VIEW_PARAM'
  # define ASIO_STRING_VIEW_PARAM asio::string_view
                                  ^~~~~~
  /Users/yanglihai/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/string_view:771:37: note: 'std::string_view' declared here
  typedef basic_string_view<char>     string_view;
                                      ^
  fatal error: too many errors emitted, stopping now [-ferror-limit=]
  20 errors generated.
  ninja: build stopped: subcommand failed.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by chrisstone07** [comment]
Remove the asio directory under cpp directory and clone it from github directory with the repository link given in the .gitmodules file for asio

**Comment by WindRush** [comment]
thankyou, it works for me

**Comment by chrisstone07** [comment]
👍 Are u Compiling on MacOS?

**Comment by WindRush** [comment]
yes

**Comment by chrisstone07** [comment]
Seems like you've downloaded one of the release source files, haven't you cloned from the repo with a git clone command? I've been trying from days and can't seem to get a build on Windows😅

**Comment by WindRush** [comment]
i clone the version tag v0.7.5-production with a git clone command, Windows maybe not worked anymore, because the author has say it on doc/README:The native build should with Windows and Linux but is rarely tested since my main development platform is Mac Os X

**Comment by chrisstone07** [comment]
I've read this before although it's just an abstract answer to why it doesn't work on Windows. Cant get my hands on a Mac so have to figure out a way for Windows. Last resort would be to get the whole Android studio setup on Linux and try. You can close the issue if it's resolved. Nice talking to you😄✌

**Comment by WindRush** [comment]
good luck to you, and thankyou again
